Record NNP B-NP O
date NN I-NP O
: : O O
2147-03-11 CD O B-DATE
Reason NN B-NP O
for IN B-PP O
consult VB B-NP O
: : O O
65 CD B-NP B-AGE
year NN I-NP O
old JJ I-NP O
man NN I-NP O
with IN B-PP O
progressive JJ B-NP O
LBP NNP I-NP O
, , O O
found VBD B-VP O
to TO I-VP O
have VB I-VP O
heterogeneous JJ B-NP O
marrow NN I-NP O
on IN B-PP O
MRI NNP B-NP O
, , O O
we PRP B-NP O
have VBP B-VP O
been VBN I-VP O
consulted VBN I-VP O
to TO I-VP O
help VB I-VP O
evaluate VB I-VP O
, , O O
possibly RB B-ADVP O
perform VB B-VP O
a DT B-NP O
bone NN I-NP O
marrow NN I-NP O
biopsy NN I-NP O
. . O O
HPI NNP B-NP O
: : O O
65 CD B-NP B-AGE
yo NNP I-NP O
male NN I-NP O
with IN B-PP O
PMH NNP B-NP O
significant JJ I-NP O
for IN B-PP O
DM NNP B-NP O
, , O O
autonomic JJ B-NP O
dysfunction NN I-NP O
, , O O
CRI NNP B-NP O
, , O O
depression NN B-NP O
and CC O O
arthritis NN B-NP O
who WP B-NP O
was VBD B-VP O
admitted VBN I-VP O
for IN B-PP O
progressive JJ B-NP O
lower JJR I-NP O
back NN I-NP O
pain NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
LBP NNP B-NP O
for IN B-PP O
at IN B-NP O
least JJS I-NP O
three CD I-NP O
years NNS I-NP O
which WDT B-NP O
is VBZ B-VP O
located VBN I-VP O
in IN B-PP O
his PRP$ B-NP O
mid JJ I-NP O
lumbar JJ I-NP O
region NN I-NP O
, , O O
non JJ B-NP O
radiating NN I-NP O
, , O O
worse JJR B-NP O
with IN B-PP O
standing NN B-NP O
. . O O
The DT B-NP O
pain NN I-NP O
had VBD B-VP O
progressed VBN I-VP O
such JJ B-NP O
that IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
a DT B-NP O
very RB I-NP O
poor JJ I-NP O
performance NN I-NP O
status NN I-NP O
. . O O
He PRP B-NP O
cannot VBD B-VP O
stand NN B-NP O
but CC B-PP O
for IN B-PP O
a DT B-NP O
few JJ I-NP O
minutes NNS I-NP O
at IN B-PP O
a DT B-NP O
time NN I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
focal JJ B-NP O
wekness NN I-NP O
. . O O
He PRP B-NP O
had VBD B-VP O
an DT B-NP O
MRI NNP I-NP O
of IN B-PP O
the DT B-NP O
LS NN I-NP O
spine NN I-NP O
2/02/47 IN B-PP B-DATE
which WDT B-NP O
revealed VBD B-VP O
heterogeneous JJ B-NP O
marrow NN I-NP O
concernig NN I-NP O
for IN B-PP O
an DT B-NP O
infiltrating JJ I-NP O
process NN I-NP O
in IN B-PP O
his PRP$ B-NP O
marrow NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
an DT B-NP O
SPEP NNP I-NP O
which WDT B-NP O
was VBD B-VP O
normal JJ B-ADJP O
, , O O
he PRP B-NP O
has VBZ B-VP O
had VBD I-VP O
a DT B-NP O
bone NN I-NP O
scan NN I-NP O
which WDT B-NP O
was VBD B-VP O
negatvie NN B-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
not RB I-VP O
have VB I-VP O
an DT B-NP O
elevated JJ I-NP O
protein NN I-NP O
or CC I-NP O
globulin NN I-NP O
fraction NN I-NP O
. . B-PP O
His PRP$ B-NP O
CRI NNP I-NP O
is VBZ B-VP O
longstanding JJ B-ADJP O
and CC O O
attributed VBD B-VP O
to TO B-PP O
his PRP$ B-NP O
DM. NNP I-NP O
He PRP B-NP O
was VBD B-VP O
set VBN I-VP O
up RP B-PRT O
for IN B-PP O
a DT B-NP O
outpt NN I-NP O
BM NNP I-NP O
bx VBD B-VP O
to TO I-VP O
evaluate VB I-VP O
the DT B-NP O
marrow NN I-NP O
process NN I-NP O
, , O O
but CC O O
the DT B-NP O
pain NN I-NP O
has VBZ B-VP O
been VBN I-VP O
so RB B-ADJP O
severe JJ I-ADJP O
, , O O
he PRP B-NP O
was VBD B-VP O
admitted VBN I-VP O
for IN B-PP O
an DT B-NP O
inpatient NN I-NP O
work NN I-NP O
up RB B-ADVP O
. . O O
Of IN B-PP O
note NN B-NP O
he PRP B-NP O
has VBZ B-VP O
longstanding JJ B-NP O
anemia NN I-NP O
related VBN B-VP O
to TO B-PP O
his PRP$ B-NP O
CRI NNP I-NP O
, , O O
perhaps RB B-NP O
anemia NN I-NP O
of IN B-PP O
chronic JJ B-NP O
disease NN I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
weight NN I-NP O
loss NN I-NP O
, , O O
fevers NNS B-NP O
, , O O
chills NNS B-NP O
, , O O
night NN B-NP O
sweats VBZ B-VP O
, , O O
decreased VBD B-VP O
appetite NN B-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
report NN B-NP O
fatigue NN I-NP O
which WDT B-NP O
has VBZ B-VP O
become VBN I-VP O
progressive JJ B-ADJP O
. . O O
PMH: . O O
1 CD B-LST O
. . O O
DM '' O O
2. DT B-NP O
autonomic JJ I-NP O
dysfunction NN I-NP O
with IN B-PP O
orthostatic JJ B-NP O
hypotension NN I-NP O
3. . B-NP O
diabetic NN I-NP O
retinopathy NN I-NP O
4 CD B-LST O
. . O O
depression NN O O
5 CD B-NP O
. . O O
CRI NNP O O
6 CD B-LST O
. . O O
OA NN O O
7. DT B-NP O
H/o NNP I-NP O
TB NNP I-NP O
2132 CD O B-DATE
8. . O O
C7 PRP B-NP O
radiculopthy JJ B-ADJP O
with IN B-PP O
bil CD B-NP O
hand NN I-NP O
weakness NN I-NP O
and CC O O
neck NN B-NP O
pain NN I-NP O
9 CD B-LST O
. . O O
HL '' O O
10 CD B-NP O
Seborrheic JJ I-NP O
dermatitis NN I-NP O
Meds NNS B-NP O
: : O O
lovastatin NN B-NP O
, , I-NP O
fludrocortisone NN I-NP O
, , I-NP O
celexa NN I-NP O
, , I-NP O
reglan NN I-NP O
, , I-NP O
proamatine NN I-NP O
, , I-NP O
ultram NN I-NP O
, , I-NP O
insulin NN I-NP O
, , I-NP O
colace NN I-NP O
, , O O
ecasa NN B-NP O
All DT B-NP O
: : O O
NKDA NNP O O
FH NNP B-NP O
: : O O
Father NNP B-NP O
had VBD B-VP O
Diabetes NNP B-NP O
, , O O
mother NN B-NP O
died VBD B-VP O
of IN B-PP O
breast NN B-NP O
cancer NN I-NP O
. . O O
SH NNS B-NP O
: : O O
Worked NNP B-NP O
in IN B-PP O
Foxworthy NNP B-NP B-ORGANIZATION
Industrials NNP I-NP I-ORGANIZATION
2100 CD I-NP B-DATE
- : O O
4 CD B-NP B-DATE
during IN B-PP O
which WDT B-NP O
time NN B-NP O
he PRP B-NP O
had VBD B-VP O
multple JJ B-NP O
exposures NNS I-NP O
to TO B-PP O
chemicals NNS B-NP O
. . O O
Retired NNP O O
from IN B-PP O
working VBG B-VP O
in IN B-PP O
the DT B-NP O
city NN I-NP O
of IN B-PP O
Victorville NNP B-NP B-CITY
2141 CD I-NP B-DATE
. . O O
He PRP B-NP O
reports VBZ B-VP O
a DT B-NP O
30 CD I-NP O
pyr JJ I-NP O
hx NN I-NP O
of IN B-PP O
tobacco NN B-NP O
, , O O
former JJ B-NP O
hx NN I-NP O
of IN B-PP O
heavy JJ B-NP O
ETOH NNP I-NP O
use NN I-NP O
, , O O
stopped VBD B-VP O
since IN B-PP O
12/46 CD B-NP B-DATE
. . O O
Denies NNS B-VP O
IV NNP B-NP O
DU. . O O
PE NN B-NP O
: : O O
General NNP B-NP O
: : O O
thin JJ B-NP O
gentleman NN I-NP O
, , O O
in IN B-PP O
no DT B-NP O
actute NN I-NP O
distress NN I-NP O
HEENT NNP B-NP O
: : O O
PERRLA< NNP B-NP O
EOMI NNP I-NP O
, , O O
Op NNP B-NP O
without IN B-PP O
thrush NN B-NP O
, , O O
no DT B-NP O
thyromegaly RB I-NP O
, , O O
No UH B-NP O
JVD . O O
Chest NNP B-NP O
: : O O
CTA NNP B-NP O
bil CD I-NP O
CV NNP B-NP O
: : O O
RRR NN B-NP O
nml NN I-NP O
s1 VBD B-VP O
, , O O
s2 VBD B-VP O
, , O O
no DT B-NP O
m/g/r NN I-NP O
Abd NNP B-NP O
: : O O
+ JJ B-NP O
bs NNS I-NP O
, , O O
soft JJ B-NP O
, , I-NP O
non-tender JJ I-NP O
, , I-NP O
non-distended JJ I-NP O
, , O O
no DT B-NP O
hepatosplenomegaly NN I-NP O
Ext JJ B-NP O
: : O O
no DT B-NP O
c/c/e NN I-NP O
neuro NN B-NP O
: : O O
strenth JJ B-NP O
5/5 RP I-NP O
throughout IN I-NP O
; : O O
absent JJ B-NP O
patellar NN I-NP O
reflexes NNS I-NP O
, , O O
2+ JJ B-NP O
biceps NNS I-NP O
, , O O
triceps NNS B-NP O
, , O O
brachioradialis NNS B-NP O
, , O O
downgoing VBG B-VP O
toes NNS B-NP O
bilaterally RB O O
Labs NNS B-NP O
: : O O
Cr NNP B-NP O
1.4 CD I-NP O
Bun NNP I-NP O
25 CD I-NP O
HCT NNP I-NP O
28.6 CD I-NP O
WBC NNP I-NP O
5.5 CD I-NP O
Plt NNP I-NP O
201 CD I-NP O
MCV NNP I-NP O
87 CD I-NP O
80seg CD I-NP O
; : O O
15l CD O O
ESR NNP B-NP O
35 CD I-NP O
Pt/Ptt NNP B-NP O
nml NN I-NP O
SPEP JJ B-NP O
2/47 CD I-NP B-DATE
: : O O
nml JJ B-NP O
T NNP I-NP O
prot NN I-NP O
6 CD B-NP O
Alb NNP I-NP O
3.4 CD I-NP O
MRI NNP B-NP O
1/47 CD I-NP B-DATE
: : O O
heterogenous JJ B-NP O
bonemarrow NN I-NP O
uptake NN I-NP O
in IN B-PP O
vertebrae NNS B-NP O
and CC I-NP O
pelvis NNS I-NP O
, , O O
concerning VBG B-VP O
for IN B-PP O
infiltrative JJ B-NP O
process NN I-NP O
Imp/Plan NNP B-NP O
: : O O
Mr. NNP B-NP O
Tuttle NNP I-NP B-PATIENT
is VBZ B-VP O
a DT B-NP O
65 CD I-NP B-AGE
year NN I-NP O
old JJ I-NP O
male NN I-NP O
with IN B-PP O
a DT B-NP O
three CD I-NP O
year NN I-NP O
hisotry NN I-NP O
of IN B-PP O
porgressive JJ B-NP O
lower JJR I-NP O
back RB I-NP O
pain NN I-NP O
, , O O
non-radicualr JJ B-ADJP O
in IN B-PP O
nature NN B-NP O
. . O O
The DT B-NP O
pain NN I-NP O
has VBZ B-VP O
progressed VBN I-VP O
to TO B-PP O
a DT B-NP O
significant JJ I-NP O
level NN I-NP O
such JJ B-PP O
that IN B-SBAR O
he PRP B-NP O
spends VBZ B-VP O
most JJS B-NP O
of IN B-PP O
his PRP$ B-NP O
day NN I-NP O
in IN B-PP O
bed NN B-NP O
. . O O
He PRP B-NP O
did VBD B-VP O
have VB I-VP O
an DT B-NP O
MRI NNP I-NP O
of IN B-PP O
the DT B-NP O
L/S NNP I-NP O
spine NN I-NP O
which WDT B-NP O
was VBD B-VP O
negative JJ B-ADJP O
except IN B-SBAR O
it PRP B-NP O
did VBD B-VP O
reveal VB I-VP O
heterogeous JJ B-NP O
uptake NN I-NP O
in IN B-PP O
the DT B-NP O
vertebral JJ I-NP O
and CC I-NP O
pelvic JJ I-NP O
bone NN I-NP O
marrow NN I-NP O
. . O O
They PRP B-NP O
raised VBD B-VP O
the DT B-NP O
question NN I-NP O
of IN B-PP O
multiple JJ B-NP O
myeloma NN I-NP O
or CC O O
another DT B-NP O
infiltrative JJ I-NP O
process NN I-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
have VB I-VP O
renal NN B-NP O
insufficiency NN I-NP O
, , O O
but CC O O
no DT B-NP O
other JJ I-NP O
abnormalities NNS I-NP O
to TO B-VP O
suggest VB I-VP O
MM. NNP B-NP O
We PRP B-NP O
still RB B-ADVP O
need VBP B-VP O
a DT B-NP O
few JJ I-NP O
key JJ I-NP O
pieces NNS I-NP O
of IN B-PP O
data NNS B-NP O
to TO B-VP O
rule VB I-VP O
this DT B-NP O
out RP I-NP O
. . O O
Other JJ B-NP O
infiltrative JJ I-NP O
processes NNS I-NP O
such JJ B-PP O
as IN I-PP O
malignancy NN B-NP O
from IN B-PP O
elsewhere RB B-NP O
should MD B-VP O
be VB I-VP O
excluded VBN I-VP O
. . O O
In IN B-PP O
addition NN B-NP O
, , O O
he PRP B-NP O
has VBZ B-VP O
a DT B-NP O
hx NN I-NP O
of IN B-PP O
a DT B-NP O
positive JJ I-NP O
PPD NNP I-NP O
, , O O
unclear JJ B-ADJP O
if IN B-SBAR O
he PRP B-NP O
actually RB B-ADVP O
had VBD B-VP O
active JJ B-NP O
TB NN I-NP O
or CC O O
was VBD B-VP O
treated VBN I-VP O
prophylactically RB B-ADVP O
. . O O
Is VBZ O O
any DT B-NP O
of IN B-PP O
this DT B-NP O
TB NN I-NP O
? . O O
Recommend VB B-VP O
: : O O
-- : O O
skeletal NN B-NP O
survey NN I-NP O
-- : O O
quantitative JJ B-NP O
urine NN I-NP O
bence NN I-NP O
jones NNS I-NP O
proteins VBZ B-VP O
as IN B-SBAR O
there EX B-NP O
are VBP B-VP O
non-secretory JJ B-NP O
myelomas NNS I-NP O
-- : O O
beta-2 JJ B-NP O
microglobulin NN I-NP O
-- : O O
reticulocyte NN B-NP O
count NN I-NP O
-- : O O
consider VBP B-VP O
chest NN B-NP O
CT NN I-NP O
to TO B-VP O
r/o VB I-VP O
lung NN B-NP O
cancer NN I-NP O
given VBN B-VP O
his PRP$ B-NP O
history NN I-NP O
of IN B-PP O
tobacco NN B-NP O
-- : O O
guaiac NN B-NP O
all DT B-NP O
stools NNS I-NP O
-- : O O
Will MD B-VP O
review VB I-VP O
the DT B-NP O
MRI NNP I-NP O
with IN B-PP O
radiologist NN B-NP O
to TO B-VP O
get VB I-VP O
a DT B-NP O
better JJR I-NP O
differential JJ I-NP O
-- : O O
Consider VB B-VP O
BM NNP B-NP O
biopsy NN I-NP O
next JJ B-NP O
week NN I-NP O
, , O O
unfortunately RB B-ADVP O
will MD B-VP O
not RB I-VP O
be VB I-VP O
able JJ B-ADJP O
to TO B-VP O
perform VB I-VP O
today NN B-NP O
. . O O
-- : O O
Will MD B-VP O
review VB I-VP O
smear NN B-NP O
and CC I-NP O
staff NN I-NP O
with IN B-PP O
Dr. NNP B-NP O
Landry NNP I-NP B-DOCTOR
in IN B-PP O
the DT B-NP O
afternoon NN I-NP O
. . O O
Thank VB B-VP O
you PRP B-NP O
for IN B-PP O
this DT B-NP O
consult VB B-VP O
. . O O
Ivy NNP B-NP B-DOCTOR
Whitaker NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
