Record NNP B-NP O
date NN I-NP O
: : O O
2077-03-31 CD O B-DATE
Harper NNP B-NP B-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
Intern NNP I-NP O
Admission NNP I-NP O
Note NN I-NP O
Pt NNP B-NP O
: : O O
Godwin NNP B-NP I-PATIENT
, , O I-PATIENT
Yair NNP B-NP I-PATIENT
MR# NNP B-NP O
6894069 CD I-NP B-MEDICALRECORD
Admit NNP B-NP O
Date NNP I-NP O
: : O O
3/31/77 CD O B-DATE
PCP NNP B-NP O
: : O O
Rivers NNS B-NP I-DOCTOR
, , O I-DOCTOR
Xavier NNP B-NP I-DOCTOR
( -LRB- I-NP O
Westlake NNP I-NP B-HOSPITAL
- : O O
Shenandoah JJ B-NP B-HOSPITAL
Hospital NN I-NP I-HOSPITAL
) -RRB- O O
CC NNP B-NP O
: : O O
chest NN B-NP O
pain NN I-NP O
HPI NNP B-NP O
: : O O
71 CD B-NP B-AGE
M NNP I-NP O
hx NN I-NP O
DM NNP I-NP O
, , I-NP O
HLP NNP I-NP O
, , I-NP O
HTN NNP I-NP O
, , I-NP O
p/w NN I-NP O
chest NN I-NP O
pain NN I-NP O
. . O O
Pt JJ B-NP O
reports NNS I-NP O
having VBG B-VP O
markedly RB B-NP O
reduced VBN I-NP O
right JJ I-NP O
eye NN I-NP O
visual JJ I-NP O
acuity NN I-NP O
this DT B-NP O
evening NN I-NP O
, , O O
subsequently RB B-ADVP O
became VBD B-VP O
increasingly RB B-ADVP O
anxious JJ B-NP O
and CC I-NP O
nervous JJ I-NP O
and CC I-NP O
developed JJ I-NP O
chest NN I-NP O
tightness VBD B-VP O
across IN B-PP O
chest NN B-NP O
at IN B-PP O
level NN B-NP O
of IN B-PP O
xiphoid JJ B-NP O
. . O O
Intermittently RB B-ADVP O
had VBD B-VP O
sharp JJ B-NP O
pains NNS I-NP O
in IN B-PP O
same JJ B-NP O
distribution NN I-NP O
, , O O
reaching VBG B-VP O
5/10 CD B-NP O
in IN B-PP O
severity NN B-NP O
. . O O
Associated NNP B-NP O
nausea NN I-NP O
and CC I-NP O
dry JJ I-NP O
heaving NN I-NP O
, , O O
only JJ B-NP O
briefly NN I-NP O
SOB. NNP I-NP O
No NNP I-NP O
associated JJ I-NP O
lightheadedness NN I-NP O
, , O O
diaphoresis NN B-NP O
, , O O
or CC O O
palpitations NNS B-NP O
. . O O
Called VBN B-VP O
daughter NN B-NP O
who WP B-NP O
then RB B-ADVP O
called VBD B-VP O
Shenandoah NNP B-NP B-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
emergency NN I-NP O
line NN I-NP O
, , O O
then RB B-ADVP O
called VBD B-VP O
MVH NNP B-NP B-HOSPITAL
and CC O O
came VBD B-VP O
into IN B-PP O
their PRP$ B-NP O
emergency NN I-NP O
room NN I-NP O
where WRB B-ADVP O
he PRP B-NP O
was VBD B-VP O
referred VBN I-VP O
to TO B-PP O
WMC NNP B-NP B-HOSPITAL
ER NNP I-NP O
secondary JJ I-NP O
to TO B-PP O
chest NN B-NP O
discomfort NN I-NP O
. . O O
Symptoms NNP B-NP O
had VBD B-VP O
resolved VBN I-VP O
by IN B-PP O
time NN B-NP O
of IN B-PP O
being VBG B-VP O
seen VBN I-VP O
in IN B-PP O
WMC NNP B-NP B-HOSPITAL
ER NNP I-NP O
. . O O
Of IN B-PP O
note NN B-NP O
, , O O
pt NN B-NP O
admitted VBD B-VP O
to TO B-PP O
LMC NNP B-NP B-HOSPITAL
( -LRB- I-NP O
9/76 CD I-NP B-DATE
) -RRB- I-NP O
for IN B-PP O
acute JJ B-NP O
onset NN I-NP O
SOB/CP. NNP B-NP O
At IN B-PP O
that DT B-NP O
time NN I-NP O
, , O O
had VBD B-VP O
negative JJ B-NP O
PE NN I-NP O
protocol NN I-NP O
CT NNP I-NP O
and CC O O
adeno-MIBI. DT B-NP O
Just RB I-NP O
prior RB B-ADVP O
to TO B-PP O
that DT B-NP O
was VBD B-VP O
admitted VBN I-VP O
to TO B-PP O
WMC NNP B-NP B-HOSPITAL
for IN B-PP O
similar JJ B-NP O
symptoms NNS I-NP O
and CC O O
had VBD B-VP O
negative JJ B-NP O
dissection NN I-NP O
protocol NN I-NP O
CT NNP I-NP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
. . O O
At IN B-PP O
baseline NN B-NP O
, , O O
walks VBZ B-VP O
up RP B-PRT O
to TO B-PP O
a DT B-NP O
mile NN I-NP O
without IN B-PP O
symptoms NNS B-NP O
, , O O
also RB B-ADVP O
climbs VBZ B-VP O
stairs NNS B-NP O
without IN B-PP O
symptoms NNS B-NP O
. . O O
In IN B-PP O
ER NNP B-NP O
, , O O
vitals NNS B-NP O
: : O O
T NNP B-NP O
98.2 CD I-NP O
, , O O
P NNP B-NP O
69 CD I-NP O
, , O O
BP NNP B-NP O
180/79 CD I-NP O
, , O O
RR NNP B-NP O
18 CD I-NP O
, , I-NP O
98 CD I-NP O
% NN I-NP O
RA. NNP I-NP O
Tx NNP I-NP O
ASA NNP I-NP O
325mg JJ I-NP O
, , I-NP O
lopressor JJ I-NP O
25mg JJ I-NP O
PO/5mg JJ I-NP O
IV. NNP I-NP O
Pain-free NNP I-NP O
while IN I-NP O
in IN B-PP O
ER NNP B-NP O
and CC O O
transferred VBD B-VP O
to TO B-PP O
floor NN B-NP O
in IN B-PP O
stable JJ B-NP O
condition NN I-NP O
. . O O
PMH: . O O
DM-2 . O O
HTN . O O
GERD NNP B-NP O
TURP . O O
DJD NNP B-NP O
of IN B-PP O
the DT B-NP O
spine NN I-NP O
Chronic NNP B-NP O
back RB B-ADVP O
pain NN O O
Hypercholesterolemia NNP B-NP O
Psoriasis NN B-NP O
Chronic NNP B-NP O
renal NNP I-NP O
insufficiency NN I-NP O
Macular NNP B-NP O
degeneration NN I-NP O
-reports NNS B-NP O
having VBG B-VP O
attack NN B-NP O
in IN B-PP O
2/77 CD B-NP B-DATE
, , O O
characterized VBN B-VP O
as IN B-PP O
having VBG B-VP O
acute JJ B-NP O
vision NN I-NP O
blurriness NN I-NP O
, , O O
told VBD B-VP O
at IN B-PP O
MVH NNP B-NP B-HOSPITAL
he PRP B-NP O
had VBD B-VP O
macular JJ B-NP O
degeneration NN I-NP O
Adenosine-MIB NN B-NP O
I PRP B-NP O
( -LRB- B-VP O
9/76 CD B-NP B-DATE
) -RRB- I-NP O
: : O O
The DT B-NP O
ECG JJ I-NP O
response NN I-NP O
to TO B-PP O
Adenosine NNP B-NP O
was VBD B-VP O
non-diagnostic JJ B-ADJP O
. . O O
The DT B-NP O
scan JJ I-NP O
results NNS I-NP O
demonstrated VBD B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
ischemia NN B-NP O
and/or CC I-NP O
scar NN I-NP O
. . O O
EF '' O O
54 CD B-NP O
% NN I-NP O
. . O O
Medications NNS B-NP O
: : O O
Glipizide NNP B-NP O
5mg CD I-NP O
po NN I-NP O
bid NN I-NP O
Atenolol NNP B-NP O
100mg CD I-NP O
po NN I-NP O
bid NN I-NP O
Irbesartan NNP B-NP O
150mg CD I-NP O
po NN I-NP O
qd NN I-NP O
Pioglitazone NNP B-NP O
30mg CD I-NP O
qd . O O
Lasix NNP B-NP O
20mg CD I-NP O
qd . O O
Simvastatin NNP B-NP O
20mg CD I-NP O
qd . O O
Aspirin NNP B-NP O
( -LRB- B-VP O
just RB I-VP O
started VBN I-VP O
1wk JJ B-ADJP O
ago IN B-PP O
) -RRB- O O
Vertigo NNP B-NP O
Gait NNP B-NP O
disturbance NN I-NP O
-thought NN B-NP O
secondary JJ I-NP O
to TO B-PP O
peripheral JJ B-NP O
neuropathy NN I-NP O
Allergies NNP B-NP O
: : O O
NKDA NNP O O
SH NNS B-NP O
: : O O
Patient NNP B-NP O
is VBZ B-VP O
widowed VBN I-VP O
and CC O O
lives NNS B-NP O
alone RB B-ADVP O
. . O O
He PRP B-NP O
quit VBD B-VP O
smoking VBG I-VP O
30 CD B-NP O
years NNS I-NP O
ago RB B-ADVP O
and CC O O
denies VBZ B-VP O
alcohol NN B-NP O
use NN I-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
a DT B-NP O
retired JJ I-NP O
community NN I-NP B-PROFESSION
organizer NN I-NP I-PROFESSION
. . O O
Known VBN B-VP O
prior RB B-ADVP O
asbestos NN B-NP O
exposure NN I-NP O
. . O O
FH NNP B-NP O
: : O O
Unknown JJ O O
Exam NNP B-NP O
: : O O
VS NNP B-NP O
T NNP I-NP O
97.5 CD I-NP O
P NNP I-NP O
62 CD I-NP O
BP NNP I-NP O
152/69 CD I-NP O
RR NNP I-NP O
20 CD I-NP O
95 CD I-NP O
% NN I-NP O
2L . O O
Gen NNP B-NP O
: : O O
NAD NNP B-NP O
, , O O
anxious JJ B-ADJP O
. . B-NP O
Pain-free NNP I-NP O
. . I-NP O
A&Ox3 NNP I-NP O
. . O O
HEENT NNP B-NP O
: : O O
EOMI NNP B-NP O
. . O O
No DT B-NP O
nystagmus NN I-NP O
. . O O
MMM. '' O O
Skin NNP B-NP O
: : O O
No DT B-NP O
changes NNS I-NP O
. . O O
Neck NNP B-NP O
: : O O
Supple NNP B-NP O
. . I-NP O
Brisk NNP I-NP O
carotids NNS I-NP O
, , O O
no DT B-NP O
bruits NNS I-NP O
. . O O
Chest NNP B-NP O
: : O O
CTAB. . O O
CVS NNP B-NP O
: : O O
RRR NNP B-VP O
. . B-NP O
2/6 RBR I-NP O
early JJ I-NP O
systolic JJ I-NP O
murmur NN I-NP O
, , O O
maximal JJ B-ADJP O
at IN B-PP O
RUSB NNP B-NP O
, , O O
no DT B-NP O
radiation NN I-NP O
to TO B-PP O
carotids NNS B-NP O
. . O O
Abd NNP B-NP O
: : O O
Obese NNP B-NP O
, , O O
protuberant NN B-NP O
. . O O
Normoactive JJ B-NP O
bowel NN I-NP O
sounds NNS I-NP O
. . B-NP O
Non-tender NN I-NP O
. . O O
Extr NNP B-NP O
: : O O
2+ CD B-NP O
DP NNP I-NP O
pulses NNS I-NP O
. . O O
No DT B-NP O
edema NN I-NP O
. . O O
Neuro NNP B-NP O
: : O O
Markedly RB B-NP O
decreased VBN I-NP O
visual JJ I-NP O
acuity NN I-NP O
of IN B-PP O
right JJ B-NP O
eye NN I-NP O
, , O O
otherwise RB B-ADVP O
CN NNP B-NP O
2-12 CD I-NP O
intact JJ I-NP O
. . I-NP O
Strength NNP I-NP O
5/5 VBD B-VP O
throughout IN B-ADVP O
, , O O
sensation NN B-NP O
intact JJ I-NP O
. . O O
DATA NNP B-NP O
: : O O
Chemistry NN B-NP O
Sodium NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
139 CD I-NP O
( -LRB- I-NP O
135-145 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Potassium NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NN I-NP O
) -RRB- I-NP O
5.4 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
3.4-4.8 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
HEMOLYZED NNP B-NP O
SPECIMEN NNP I-NP O
Chloride NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
110 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
100-108 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
CO2 NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
23.1 CD I-NP O
( -LRB- I-NP O
23.0-31.9 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
BUN NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
48 CD I-NP O
H NNP B-NP O
(8-25 . O O
) -RRB- O O
mg/dl . O O
Creatinine NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NN I-NP O
) -RRB- I-NP O
1.8 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.6-1.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
( -LRB- B-NP O
baseline NN I-NP O
Cr JJ I-NP O
~1.6 CD I-NP O
) -RRB- O O
Glucose FW B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
169 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
70-110 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Calcium NNP B-NP O
9.0 CD I-NP O
( -LRB- I-NP O
8.5-10.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Phosphorus NNP B-NP O
2.3 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
2.6-4.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Magnesium NNP B-NP O
1.4 CD I-NP O
( -LRB- O O
1.4-2.0) CD B-NP O
meq/L NN I-NP O
Creatine NNP B-NP O
Kinase NNP I-NP O
Isoenzymes NNP I-NP O
1.9 CD I-NP O
( -LRB- I-NP O
0.0-6.9 CD I-NP O
) -RRB- I-NP O
ng/ml . O O
CPK NNP B-NP O
Isoenzymes NNP I-NP O
Index NNP I-NP O
( -LRB- B-VP O
0.0-3.5 CD B-PP O
) -RRB- B-NP O
% NN I-NP O
CPK NNP B-NP O
and/or CC I-NP O
CKMB NNP I-NP O
too RB I-NP O
low JJ B-ADJP O
to TO B-VP O
calculate VB I-VP O
Relative NNP B-NP O
Index NNP I-NP O
. . O O
Troponin-T NNP B-NP O
<0.01 CD I-NP O
( -LRB- I-NP O
0.00-0.09 CD I-NP O
) -RRB- I-NP O
ng/ml . O O
Creatine NNP B-NP O
Kinase NNP I-NP O
106 CD I-NP O
(60-400 NN I-NP O
) -RRB- I-NP O
U/L . O O
Hematology NNP B-NP O
WBC NNP B-NP O
11.5 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
4.5-11.0) JJ I-NP O
th/cmm NN I-NP O
HCT NNP B-NP O
35.1 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
41.0-53.0) CD I-NP O
% NN I-NP O
HGB NNP B-NP O
12.4 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
13.5-17.5 CD I-NP O
) -RRB- I-NP O
gm/dl . O O
RBC NNP B-NP O
4.15 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
4.50-5.90 CD I-NP O
) -RRB- I-NP O
mil/cmm . O O
PLT NNP B-NP O
227 CD I-NP O
( -LRB- I-NP O
150-350 CD I-NP O
) -RRB- I-NP O
th/cumm . O O
MCV NN B-NP O
85 CD I-NP O
( -LRB- I-NP O
80-100 CD I-NP O
) -RRB- B-NP O
fl NN I-NP O
MCH NNP B-NP O
30.0 CD I-NP O
( -LRB- I-NP O
26.0-34.0) JJ I-NP O
pg/rbc NN I-NP O
MCHC NNP B-NP O
35.4 CD I-NP O
( -LRB- O O
31.0-37.0) CD B-NP O
g/dl NN I-NP O
RDW NNP B-NP O
15.1 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
11.5-14.5 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
DIFFERENTIAL NNP B-NP O
REQUEST NNP I-NP O
RECEIVED NNP I-NP O
Diff JJ B-NP O
Method NNP I-NP O
Auto NN I-NP O
Poly NNP B-NP O
83 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
40-70 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Lymphs NNP B-NP O
13 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
22-44 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Monos NNP B-NP O
2 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
4-11 NN I-NP O
) -RRB- B-NP O
% NN I-NP O
EOS NNP B-NP O
2 CD I-NP O
(0-8 CD I-NP O
) -RRB- O O
% NN O O
Basos NNS B-NP O
0 CD B-NP O
(0-3 JJ I-NP O
) -RRB- I-NP O
% NN I-NP O
Imaging NNP B-NP O
: : O O
CXR NN B-NP O
( -LRB- I-NP O
3/31/77 CD I-NP B-DATE
) -RRB- I-NP O
: : O O
No DT B-NP O
acute JJ I-NP O
process NN I-NP O
EKG NNP B-NP O
: : O O
NSR. NNP B-NP O
LBBB NNP I-NP O
. . O O
1mm '' O O
STD NNP B-NP O
I/II/aVf/V5-6 NNP I-NP O
. . O O
2mm '' O O
STE NNP B-NP O
V1-3 NNP I-NP O
. . I-NP O
TWI NNP I-NP O
I PRP I-NP O
, , O O
biphasic JJ B-NP O
T-wave NN I-NP O
V5-6 NN I-NP O
. . O O
( -LRB- O O
No DT B-NP O
change NN I-NP O
from IN B-PP O
prior JJ B-NP O
ekg NN I-NP O
) -RRB- O O
Impression NN B-NP O
: : O O
71 CD B-NP B-AGE
M NNP I-NP O
hx NN I-NP O
DM NNP I-NP O
, , I-NP O
HTN NNP I-NP O
, , I-NP O
HLP NNP I-NP O
, , I-NP O
p/w NN I-NP O
chest NN I-NP O
pain NN I-NP O
likely JJ I-NP O
GI NN I-NP O
related VBN B-VP O
and CC O O
not RB B-ADJP O
cardiac JJ I-ADJP O
in IN B-PP O
origin NN B-NP O
. . O O
Plan NNP B-NP O
: : O O
1 CD B-LST O
. . O O
chest NN B-VP O
pain NN B-NP O
: : O O
Unlikely RB B-ADJP O
cardiac JJ I-ADJP O
in IN B-PP O
origin NN B-NP O
given VBN I-NP O
negative JJ I-NP O
EKG NNP I-NP O
, , O O
recent JJ B-NP O
normal JJ I-NP O
stress NN I-NP O
test NN I-NP O
, , O O
and CC O O
atypical JJ B-NP O
nature NN I-NP O
. . O O
Likely RB O O
GI NNP B-NP O
related VBD B-VP O
as IN B-PP O
pt JJ B-ADJP O
with IN B-PP O
dry JJ B-NP O
heaving NN I-NP O
around IN B-PP O
time NN B-NP O
of IN B-PP O
chest NN B-NP O
tightness NN I-NP O
. . O O
-cont JJ B-NP O
asa NN I-NP O
, , O O
simvastatin NN B-NP O
, , O O
atenolol NN B-NP O
, , O O
irbesartan NN B-NP O
, , O O
and CC O O
lasix NN B-NP O
-repeat JJ B-NP O
EKG NNP I-NP O
in IN B-ADVP O
AM VBP O O
-cycle NN B-NP O
cardiac NN I-NP O
enzymes NNS I-NP O
, , O O
telemetry NN B-NP O
-check JJ B-NP O
lipid JJ I-NP O
panel NN I-NP O
-maalox NN B-NP O
prn NN I-NP O
2. . B-NP O
decreased VBD B-VP O
visual JJ B-NP O
acuity NN I-NP O
: : O O
Most RBS B-NP O
likely JJ I-NP O
worsening VBG I-NP O
macular JJ I-NP O
degeneration NN I-NP O
given VBN B-VP O
recent JJ B-NP O
chronic JJ I-NP O
history NN I-NP O
of IN B-PP O
symptoms NNS B-NP O
. . B-NP O
Absence NN I-NP O
of IN B-PP O
pain NN B-NP O
makes VBZ B-VP O
retinal JJ B-NP O
vascular JJ I-NP O
occlusion NN I-NP O
very RB B-ADJP O
unlikely JJ I-ADJP O
, , O O
no DT B-NP O
other JJ I-NP O
neurological JJ I-NP O
symptoms NNS I-NP O
to TO B-VP O
indicate VB I-VP O
CVA NNP B-NP O
. . O O
-refer NN B-NP O
pt VBD B-VP O
back RB B-ADVP O
to TO B-PP O
MVH NNP B-NP B-HOSPITAL
once RB B-ADVP O
ruled VBD B-VP O
out RP B-PRT O
for IN B-SBAR O
MI NNP B-NP O
-consider NN B-NP O
I- NNP I-NP O
CT NNP I-NP O
if IN B-PP O
more JJR B-NP O
neuro NN I-NP O
symptoms NNS I-NP O
develop VBP B-VP O
to TO I-VP O
r/o VB I-VP O
acute JJ B-NP O
stroke NN I-NP O
3. DT B-NP O
Diabetes NNP I-NP O
: : O O
-check JJ B-NP O
lipid JJ I-NP O
panel NN I-NP O
, , O O
hemoglobin NN B-NP O
A1c CC O O
-RISS NNP B-NP O
, , O O
glipizide NN B-NP O
-hold JJ B-NP O
pioglitazone NN I-NP O
( -LRB- B-VP O
not RB O O
in IN B-PP O
formulary NN B-NP O
) -RRB- O O
4 CD B-LST O
. . O O
proph NN B-VP O
: : O O
nexium JJ B-NP O
, , O O
heparin VBG B-SBAR O
Full NNP B-NP O
Code NNP I-NP O
Victor NNP B-NP B-DOCTOR
Tolbert NNP I-NP I-DOCTOR
M.D. NNP I-NP O
Pager NNP B-NP O
73483 CD I-NP B-PHONE
Call NNP B-NP O
Internal NNP I-NP O
Medicine NNP I-NP O
intern NN I-NP O
in IN B-PP O
AM NNP B-NP O
for IN B-PP O
pt JJ B-NP O
management NN I-NP O
issues NNS I-NP O
. . O O
