Record NNP B-NP O
date NN I-NP O
: : O O
2075-01-10 CD O B-DATE
CCU NNP B-NP O
JAR NNP I-NP O
ADMIT NNP I-NP O
NOTE NNP I-NP O
Sharon NNP I-NP B-PATIENT
FALLON NNP I-NP I-PATIENT
1703242 CD O B-MEDICALRECORD
DOA VB B-VP O
to TO B-PP O
CCU NNP B-NP O
01/09/75 CD I-NP B-DATE
CARDS NNP B-NP O
: : O O
Dr. NNP B-NP O
Jimenez NNP I-NP B-DOCTOR
- : O O
covered VBN B-VP O
by IN B-PP O
Dr. NNP B-NP O
Herman NNP I-NP B-DOCTOR
PCP NNP B-NP O
: : O O
Dr NNP B-NP O
Lehman NNP I-NP B-DOCTOR
. . I-NP O
Endocrine NNP I-NP O
- : O O
Dr NNP B-NP O
Saunders NNPS O B-DOCTOR
Code NNP B-NP O
status NN I-NP O
: : O O
Full VB O O
Chief NNP B-NP O
Complaint NN I-NP O
72 CD B-NP B-AGE
year NN I-NP O
old JJ I-NP O
lady NN I-NP O
w VBD B-VP O
hx PRP$ B-NP O
ESRD NNP I-NP O
on IN B-PP O
HD NNP B-NP O
, , O O
adm NN B-NP O
with IN B-PP O
SOB NNP B-NP O
, , O O
no DT B-NP O
CP CD I-NP O
, , O O
positive JJ B-NP O
troponin FW I-NP O
and CC O O
non-specific JJ B-NP O
ST-TW JJ I-NP O
changes NNS I-NP O
. . O O
History NN B-NP O
of IN B-PP O
Present NNP B-NP O
Illness NNP I-NP O
Ms NNP B-NP O
Fallon NNP I-NP B-PATIENT
is VBZ B-VP O
a DT B-NP O
72 CD I-NP B-AGE
year NN I-NP O
old JJ I-NP O
lady NN I-NP O
without IN B-PP O
significant JJ B-NP O
past JJ I-NP O
CAD NN I-NP O
who WP B-NP O
presented VBD B-VP O
to TO B-PP O
the DT B-NP O
ER NNP I-NP O
because IN B-PP O
of IN I-PP O
increasing VBG B-VP O
SOB NNP B-NP O
with IN B-PP O
minimal JJ B-NP O
exercise NN I-NP O
. . O O
She PRP B-NP O
says VBZ B-VP O
she PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
SOB NNP B-NP O
for IN B-PP O
50 CD B-NP O
years NNS I-NP O
however RB B-ADVP O
in IN B-PP O
the DT B-NP O
last JJ I-NP O
week NN I-NP O
or CC I-NP O
so RB I-NP O
, , O O
has VBZ B-VP O
noticed VBN I-VP O
increased VBN I-VP O
DOE VB I-VP O
, , O O
now RB B-ADVP O
w VBD B-VP O
minimal JJ B-NP O
exercise NN I-NP O
. . O O
No DT B-NP O
CP NNPS I-NP O
, , O O
palpitations NNS B-NP O
, , O O
sweating VBG B-VP O
, , O O
cough NN B-NP O
, , O O
sputum NN B-NP O
, , O O
fever NN B-NP O
, , O O
haemoptysis NN B-NP O
. . O O
Sleeps NNS B-NP O
in IN B-PP O
a DT B-NP O
chair NN I-NP O
for IN B-PP O
last JJ B-NP O
number NN I-NP O
of IN B-PP O
years NNS B-NP O
. . O O
No DT B-NP O
ankle NN I-NP O
swelling VBG B-VP O
. . O O
Called VBN B-VP O
EMS NNP B-NP O
and CC O O
was VBD B-VP O
given VBN I-VP O
s/l JJ B-NP O
TNG NNP I-NP O
x NN I-NP O
4 CD B-NP O
and CC I-NP O
O2 CD I-NP O
w JJ I-NP O
effect NN I-NP O
. . O O
In IN B-SBAR O
ER NNP B-NP O
was VBD B-VP O
given VBN I-VP O
ASA NNP B-NP O
and CC O O
metoprolol JJ B-NP O
5mg JJ I-NP O
iv. NN I-NP O
Refused VBN I-NP O
Kayexylate NNP I-NP O
, , I-NP O
insulin NN I-NP O
and CC I-NP O
heparin NN I-NP O
. . O O
Had VBD B-VP O
positive JJ B-NP O
troponin FW I-NP O
0.19 CD I-NP O
- : O O
previous JJ B-NP O
troponin FW I-NP O
in IN B-PP O
system NN B-NP O
was VBD B-VP O
18 CD B-NP O
months NNS I-NP O
ago IN B-PP O
- : B-NP O
0.04 CD I-NP O
. . O O
Transferred NNP O O
to TO B-PP O
CCU NNP B-NP O
as IN B-PP O
no DT B-NP O
beds NNS I-NP O
available JJ B-ADJP O
in IN B-PP O
SDU NNP B-NP O
In IN B-PP O
CCU NNP B-NP O
- : O O
Pain NNP B-NP O
free JJ I-NP O
overnight JJ I-NP O
. . O O
Feels NNS O O
significantly RB B-NP O
less RBR I-NP O
SOB. NNP I-NP O
Was VBD B-VP O
refusing VBG I-VP O
SSI NNP B-NP O
at IN B-PP O
usual JJ B-NP O
doses NNS I-NP O
out IN B-PP O
of IN B-PP O
concern NN B-NP O
for IN B-PP O
hypoglycemia NN B-NP O
. . O O
Past NNP B-NP O
Medical NNP I-NP O
History NNP I-NP O
1 CD B-NP O
) -RRB- I-NP O
DM2 NN I-NP O
for IN B-PP O
35 CD B-NP O
years NNS I-NP O
- : O O
causing VBG B-VP O
ESRD NNP B-NP O
, , O O
retinopathy NN B-NP O
with IN B-PP O
laser NN B-NP O
rx NN I-NP O
. . O O
2 CD B-NP O
) -RRB- I-NP O
HTN NN I-NP O
in IN B-PP O
past NN B-NP O
but CC O O
not RB B-VP O
treated VBN I-VP O
for IN B-PP O
several JJ B-NP O
years NNS I-NP O
due JJ B-ADJP O
to TO B-PP O
low JJ B-NP O
BP NNP I-NP O
3 CD B-NP O
) -RRB- I-NP O
Hyperlipidemia . O O
4 CD B-NP O
) -RRB- I-NP O
History NN I-NP O
of IN B-PP O
DVT NNP B-NP O
with IN B-PP O
IVC NNP B-NP O
filter NN I-NP O
5 CD B-NP O
) -RRB- I-NP O
Gout . O O
6 CD B-NP O
) -RRB- I-NP O
History NN I-NP O
of IN B-PP O
CHF NNP B-NP O
with IN B-PP O
preserved JJ B-NP O
EF NN I-NP O
7 CD B-NP O
) -RRB- I-NP O
Chronic NNP I-NP O
right RB B-ADVP O
lower JJR B-NP O
extremity NN I-NP O
venous JJ I-NP O
stasis NN I-NP O
ulcer NN I-NP O
Medications NNS B-NP O
At IN B-PP O
home NN B-NP O
: : O O
Quinine NNP B-NP O
350mg CD I-NP O
bid NN I-NP O
Phoslo NNP B-NP O
667 CD I-NP O
tid NN I-NP O
Allopurinol NNP B-NP O
200mg CD I-NP O
qd . O O
Mevacor NNP B-NP O
20mg CD I-NP O
Lantus NNP B-NP O
insulin NN I-NP O
58u/day . O O
On IN B-PP O
transfer NN B-NP O
: : O O
as IN B-PP O
above IN B-NP O
plus CC O O
ASA NNP B-NP O
325 CD I-NP O
mg NN I-NP O
qd NN I-NP O
TNG NN B-NP O
Metoprolol . O O
SSI . O O
Allergies . O O
Morphine NNP B-NP O
and CC I-NP O
Novocaine NNP I-NP O
have VBP B-VP O
made VBN I-VP O
her PRP$ B-NP O
SOB NN I-NP O
in IN B-PP O
the DT B-NP O
past NN I-NP O
Family NNP B-NP O
History NN I-NP O
None NN B-NP O
relevant JJ I-NP O
. . O O
Social NNP B-NP O
History NNP I-NP O
Ethanol NNP B-NP O
use NN I-NP O
: : O O
never RB O O
Nicotine JJ B-NP O
use NN I-NP O
: : O O
never RB B-ADVP O
. . O O
Lives NNS B-NP O
w VBD B-VP O
her PRP$ B-NP O
husband NN I-NP O
. . O O
Is VBZ B-VP O
normally RB I-VP O
fairly RB I-VP O
independent JJ I-VP O
ADLs NNP B-NP O
. . O O
Review NNP B-NP O
of IN I-NP O
Systems NNPS O O
General NNP B-NP O
: : O O
No DT B-NP O
weight NN I-NP O
loss NN I-NP O
, , O O
no DT B-NP O
sweats NNS I-NP O
, , O O
no DT B-NP O
chills NNS I-NP O
, , O O
change NN B-NP O
in IN B-PP O
appetite NN B-NP O
Respiratory NNP B-NP O
: : O O
No DT B-NP O
wheeze NN I-NP O
, , O O
cough NN B-NP O
, , O O
+SOB NNP B-NP O
, , O O
PND NNP B-NP O
, , O O
orthopnoea NN B-NP O
HEENT NNP B-NP O
: : O O
No DT B-NP O
neck NN I-NP O
swelling VBG I-NP O
, , O O
neck NN B-NP O
stiffness NN I-NP O
, , O O
hoarseness NN B-NP O
Cardiac NNP B-NP O
: : O O
No DT B-NP O
Chest NNP I-NP O
pain NN I-NP O
, , O O
no DT B-NP O
palpitations NNS I-NP O
, , O O
arrythmias NNS B-NP O
, , O O
valve NN B-NP O
disease NN I-NP O
Gastrointestinal NNP B-NP O
: : O O
No DT B-NP O
nausea NN I-NP O
, , O O
vomiting VBG B-VP O
, , O O
diarrhea NN B-NP O
, , O O
constipation NN B-NP O
, , O O
no DT B-NP O
bleeding NN I-NP O
or CC I-NP O
melena NN I-NP O
until IN B-PP O
yesterday NN B-NP O
. . O O
Neurologic NNP B-NP O
: : O O
No DT B-NP O
seizures NNS I-NP O
, , O O
headache NN B-NP O
, , O O
weakness NN B-NP O
, , O O
numbness/tingling VBG B-SBAR O
Lymph NNP B-NP O
nodes VBZ B-VP O
: : O O
No DT B-NP O
enlarged VBN I-NP O
lymph NN I-NP O
nodes NNS I-NP O
Musculoskeletal NNP B-NP O
: : O O
No DT B-NP O
back RB I-NP O
pain NN I-NP O
, , O O
neck NN B-NP O
pain NN I-NP O
, , O O
arm NN B-NP O
pain NN I-NP O
Urologic NNP B-NP O
: : O O
No DT B-NP O
hematuria NN I-NP O
, , O O
frequency NN B-NP O
, , O O
dysuria VBD B-VP O
no DT B-NP O
obstruction NN I-NP O
Physical NNP B-NP O
Exam NNP I-NP O
BP NNP B-NP O
110 CD I-NP O
- : O O
130/60 CD B-NP O
-80 : O O
Pulse NNP B-NP O
70s CD I-NP O
SR NNP I-NP O
Afebrile NNP I-NP O
97 CD I-NP O
% NN I-NP O
on IN B-PP O
4L JJ B-NP O
breathing NN I-NP O
14/min IN B-PP O
Overweight JJ B-NP O
elderly JJ I-NP O
lady NN I-NP O
, , O O
currently RB B-ADVP O
pain NN B-NP O
free JJ B-ADJP O
. . O O
H NNP B-NP O
and CC I-NP O
N NNP I-NP O
- : O O
No DT B-NP O
bruits NNS I-NP O
, , O O
no DT B-NP O
LAD NN I-NP O
, , O O
no DT B-NP O
tracheal NN I-NP O
deviation NN I-NP O
. . O O
JVP NNP B-NP O
- : O O
8cm NN B-VP O
with IN B-PP O
normal JJ B-NP O
waveform NN I-NP O
. . O O
CVS NNP B-NP O
- : O O
RRR NN B-NP O
. . B-NP O
Impalpable JJ I-NP O
apex NN I-NP O
. . O O
No DT B-NP O
M/R/G. NNP I-NP O
Faint NNP I-NP O
sounds VBZ B-VP O
. . O O
Chest NNP B-NP O
- : O O
Bilateral JJ B-NP O
absent JJ I-NP O
air NN I-NP O
entry NN I-NP O
in IN B-PP O
bases NNS B-NP O
, , O O
bilateral JJ B-NP O
crepitations NNS I-NP O
. . O O
Abdomen NNP B-NP O
- : O O
Soft JJ B-NP O
, , I-NP O
obese JJ I-NP O
, , I-NP O
non-tender JJ I-NP O
. . O O
No DT B-NP O
AAA NNP I-NP O
. . I-NP O
G NNP I-NP O
neg NN I-NP O
. . O O
Groin NNP B-NP O
- : O O
no DT B-NP O
bruits NNS I-NP O
. . O O
Legs NNS B-NP O
- : O O
Chronic JJ B-NP O
venous JJ I-NP O
stasis NN I-NP O
changes NNS I-NP O
bilaterally RB B-ADVP O
with IN B-PP O
ulcer NN B-NP O
on IN B-PP O
posterior JJ B-NP O
right JJ I-NP O
calf/ankle NN I-NP O
. . O O
LABS . O O
Plasma NNP B-NP O
Sodium NNP I-NP O
137 CD I-NP O
135-145 CD I-NP O
mmol/L . O O
Plasma NNP B-NP O
Potassium NNP I-NP O
4.9 CD I-NP O
H NNP B-NP O
3.4-4.8 CD I-NP O
mmol/L . O O
Plasma NNP B-NP O
Chloride NNP I-NP O
94 CD I-NP O
L NNP B-NP O
100-108 CD I-NP O
mmol/L . O O
Plasma NNP B-NP O
Carbon NNP I-NP O
Dioxide NNP I-NP O
27.7 CD I-NP O
24.0-30.0 CD I-NP O
mmol/L . O O
Plasma NNP B-NP O
Urea NNP I-NP O
Nitrogen NNP I-NP O
67 CD I-NP O
H NNP B-NP O
8-25 CD I-NP O
mg/dl . O O
Plasma NNP B-NP O
Creatinine NNP I-NP O
6.7 CD I-NP O
H NNP B-NP O
0.6-1.5 CD I-NP O
mg/dl . O O
Plasma NNP B-NP O
Glucose NNP I-NP O
407 CD I-NP O
H NNP B-NP O
70-110 CD I-NP O
mg/dl . O O
Calcium NNP B-NP O
8.6 CD I-NP O
8.5-10.5 CD I-NP O
mg/dl NN I-NP O
Phosphorus NNP B-NP O
6.6 CD I-NP O
H NNP B-NP O
2.6-4.5 CD I-NP O
mg/dl . O O
Magnesium NNP B-NP O
1.9 CD I-NP O
1.4-2.0 CD I-NP O
meq/L NNS I-NP O
Total JJ B-NP O
Protein NNP I-NP O
6.9 CD I-NP O
6.0-8.0 CD I-NP O
g/dl NN I-NP O
Albumin NNP B-NP O
3.0 CD I-NP O
L NNP I-NP O
3.1-4.3 CD I-NP O
g/dl NN I-NP O
Globulin NNP B-NP O
3.9 CD I-NP O
2.6-4.1 CD I-NP O
g/dl NN I-NP O
Direct JJ B-NP O
Bilirubin NNP I-NP O
0.1 CD I-NP O
0-0.4 CD I-NP O
mg/dl NN I-NP O
Total JJ B-NP O
Bilirubin NNP I-NP O
0.2 CD I-NP O
0-1.0 CD I-NP O
mg/dl NN I-NP O
Triglycerides NNS B-NP O
116 CD B-NP O
40-150 CD I-NP O
mg/dl NN I-NP O
Cholesterol NNP B-NP O
160 CD I-NP O
mg/dl NN I-NP O
High NNP B-NP O
Density NNP I-NP O
Lipoprotei NNP I-NP O
66 CD I-NP O
35-100 CD I-NP O
mg/dl NN I-NP O
Low NNP B-NP O
Density NNP I-NP O
Lipoprotein NNP I-NP O
71 CD I-NP O
mg/dl NN I-NP O
Alkaline NNP B-NP O
Phosphatase NNP I-NP O
129 CD I-NP O
H NNP B-NP O
30-100 CD I-NP O
U/L . O O
Transaminase-SGPT NNP B-NP O
9 CD I-NP O
7-30 CD I-NP O
U/L . O O
Transaminase-SGOT NNP B-NP O
24 CD I-NP O
9-25 CD I-NP O
U/L . O O
Amylase NNP B-NP O
74 CD I-NP O
3-100 CD I-NP O
units/L NN I-NP O
Lipase NNP B-NP O
2.0 CD I-NP O
1.3-6.0 CD I-NP O
U/dl . O O
Creatine JJ B-NP O
Kinase NNP I-NP O
Isoenzy NNP I-NP O
7.3 CD I-NP O
H NNP B-NP O
0.0-6.9 CD I-NP O
ng/ml . O O
Troponin-T NNP B-NP O
0.47 CD I-NP O
H NNP B-NP O
0.00-0.09 CD I-NP O
ng/ml . O O
Creatine JJ B-NP O
Kinase NNP I-NP O
83 CD I-NP O
40-150 CD I-NP O
U/L . O O
WBC NNP B-NP O
9.3 CD I-NP O
4.5-11.0 CD I-NP O
th/cmm . O O
HCT NNP B-NP O
35.7 CD I-NP O
L NNP I-NP O
36.0-46.0 CD I-NP O
% NN I-NP O
HGB NNP B-NP O
10.9 CD I-NP O
L NNP I-NP O
12.0-16.0 CD I-NP O
gm/dl NN I-NP O
RBC NNP B-NP O
3.79 CD I-NP O
L NNP B-NP O
4.00-5.20 CD I-NP O
mil/cmm . O O
PLT NNP B-NP O
204 CD I-NP O
150-350 CD I-NP O
th/cumm . O O
MCV NNP B-NP O
94 CD I-NP O
80-100 CD I-NP O
fl NN I-NP O
MCH NNP B-NP O
28.8 CD I-NP O
26.0-34.0 CD I-NP O
pg/rbc NN I-NP O
MCHC NNP B-NP O
30.6 CD I-NP O
L NNP I-NP O
31.0-37.0 CD I-NP O
g/dl NN I-NP O
RDW NNP B-NP O
15.7 CD I-NP O
H NNP I-NP O
11.5-14.5 CD I-NP O
% NN I-NP O
PT NNP B-NP O
12.9 CD I-NP O
11.1-13.1 CD I-NP O
sec NN I-NP O
APTT NNP B-NP O
25.7 CD I-NP O
22.1-35.1 CD I-NP O
sec NN I-NP O
CXR NN B-NP O
To TO B-PP O
my PRP$ B-NP O
eye NN I-NP O
, , O O
cardiomegaly JJ B-NP O
, , I-NP O
bilateral JJ I-NP O
pleural JJ I-NP O
effusions NNS I-NP O
, , O O
bilateral JJ B-NP O
lower JJR I-NP O
zone NN I-NP O
reticulo-nodular JJ I-NP O
exam NN I-NP O
. . O O
ECGs NNS B-NP O
Sinus NNP B-NP O
76 CD I-NP O
. . O O
Left VBD B-VP O
ward NN B-NP O
axis NN I-NP O
, , O O
normal JJ B-NP O
intervals NNS I-NP O
. . O O
LVH NN B-VP O
by IN B-PP O
voltage NN B-NP O
w NN I-NP O
QRS NNS I-NP O
of IN B-PP O
125 CD B-NP O
, , O O
TWI NNP B-NP O
in IN B-PP O
1 CD B-NP O
, , O O
aVL RB B-ADVP O
, , O O
laterally RB B-ADVP O
. . O O
Somewhat RB B-VP O
worsened VBN I-VP O
from IN B-PP O
ECG NNP B-NP O
in IN B-PP O
October NNP B-NP B-DATE
. . O O
ECHO . O O
MITRAL NNP B-NP O
VALVE NNP I-NP O
ABN NNP I-NP O
SEGMENT NNP I-NP O
BASE NNP I-NP O
MID NNP I-NP O
APEX NNP I-NP O
LEFT NNP B-NP O
ATRIUM NNP I-NP O
ABN NNP I-NP O
LA NNP I-NP O
43 CD I-NP O
( -LRB- I-NP O
25-38mm JJ I-NP O
) -RRB- O O
AV. NNP B-NP O
A0 NNP I-NP O
. . I-NP O
LVOT NNP I-NP O
ABN NNP I-NP O
AO NNP I-NP O
29 CD I-NP O
( -LRB- I-NP O
24-39mm JJ I-NP O
) -RRB- I-NP O
anterior JJ I-NP O
A DT O O
LEFT NNP B-NP O
VENT. NNP I-NP O
ABN NNP I-NP O
LVIDd NNP I-NP O
49 CD I-NP O
( -LRB- I-NP O
37-53mm JJ I-NP O
) -RRB- I-NP O
ant JJ I-NP O
.sep. . O O
TV NN B-NP O
. . O O
RA. '' O O
VC. NNP B-NP O
NORM NNP I-NP O
LVIDs NNP I-NP O
37 CD I-NP O
mid JJ I-NP O
.sep. NNP I-NP O
H NNP I-NP O
PV. NNP B-NP O
INF. NNP I-NP O
PA. NNP I-NP O
NORM NNP I-NP O
PWT NNP I-NP O
12 CD I-NP O
( -LRB- I-NP O
7-11mm JJ I-NP O
) -RRB- I-NP O
inf NN I-NP O
.sep. . O O
RIGHT NNP B-NP O
VENT. NNP I-NP O
NORM NNP I-NP O
IVS NNP I-NP O
13 CD I-NP O
( -LRB- I-NP O
7-11mm JJ I-NP O
) -RRB- I-NP O
inferior JJ O O
IAS. NNP B-NP O
IVS. NNP I-NP O
NORM NNP I-NP O
inf.pos NNS I-NP O
. . O O
COMPLEX NNP B-NP O
CHD NNP I-NP O
EF NNP I-NP O
51 CD I-NP O
% NN I-NP O
( -LRB- I-NP O
>50 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
pos NNS I-NP O
.lat NN I-NP O
. . O O
CORONARIES NNS B-NP O
UV NN I-NP O
lateral JJ B-NP O
H NNP I-NP O
PERICARDIUM NN B-NP O
NORM NN I-NP O
MITRAL NNP B-NP O
VALVE CD I-NP O
There EX B-NP O
is VBZ B-VP O
evidence NN B-NP O
of IN B-PP O
thickening NN B-NP O
of IN B-PP O
the DT B-NP O
anterior JJ I-NP O
mitral JJ I-NP O
leaflet NN I-NP O
. . O O
There EX O O
is VBZ O O
calcification NN B-NP O
of IN B-PP O
the DT B-NP O
anterior JJ I-NP O
and CC I-NP O
posterior JJ I-NP O
mitral JJ I-NP O
annulus NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no RB O O
evidence NN B-NP O
of IN B-PP O
mitral JJ B-NP O
valve NN I-NP O
prolapse NN I-NP O
. . O O
The DT B-NP O
peak NN I-NP O
transmitral NN I-NP O
gradient NN I-NP O
is VBZ B-VP O
10 CD B-NP O
mmHg NN I-NP O
. . O O
The DT B-NP O
mean JJ I-NP O
transmitral JJ I-NP O
gradient NN I-NP O
is VBZ B-VP O
5 CD B-NP O
mmHg NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
mild JJ B-ADJP O
to TO B-VP O
moderate VB I-VP O
mitral NN B-NP O
regurgitation NN B-NP O
by IN B-PP O
color NN B-NP O
and CC O O
spectral JJ B-NP O
Doppler NNP I-NP O
. . O O
LEFT NNP B-NP O
ATRIUM NNP I-NP O
The DT B-NP O
left JJ I-NP O
atrium NN I-NP O
is VBZ B-VP O
dilated VBN I-VP O
. . O O
AORTIC NNP B-NP O
VALVE NNP I-NP O
, , O O
AORTA NNP B-NP O
, , O O
LVOT NNP B-NP O
Multiple JJ B-NP O
aortic JJ I-NP O
leaflets NNS I-NP O
are VBP B-VP O
thickened VBN I-VP O
but CC O O
there EX B-NP O
is VBZ B-VP O
no DT B-NP O
stenosis NN I-NP O
. . O O
The DT B-NP O
aortic NN I-NP O
valve NN B-NP O
is VBZ B-VP O
tricuspid JJ B-ADJP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
aortic JJ B-NP O
insufficiency NN I-NP O
by IN B-PP O
color NN B-NP O
or CC O O
spectral JJ B-NP O
Doppler NNP I-NP O
. . O O
LEFT NNP B-NP O
VENTRICLE NNP I-NP O
The DT B-NP O
left VBD B-VP O
ventricular JJ B-NP O
cavity NN I-NP O
size NN I-NP O
is VBZ B-VP O
normal JJ B-ADJP O
. . O O
The DT O O
left VBD B-VP O
ventricular JJ B-NP O
systolic NN I-NP O
function NN B-NP O
approaches VBZ B-VP O
the DT B-NP O
lower JJR I-NP O
limits NNS I-NP O
of IN B-PP O
normal JJ B-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
symmetric JJ B-NP O
left NN I-NP O
ventricular JJ B-NP O
hypertrophy NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
segmental JJ B-NP O
apical JJ I-NP O
left NN I-NP O
ventricular NN I-NP O
dysfunction NN B-NP O
( -LRB- B-VP O
see VB I-VP O
wall NN B-NP O
motion NN I-NP O
plot NN I-NP O
) -RRB- I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
left VBN B-NP O
ventricular NN I-NP O
thrombus NN B-NP O
. . O O
The DT B-NP O
estimated VBN I-NP O
ejection NN I-NP O
fraction NN I-NP O
is VBZ B-VP O
51 CD B-NP O
% NN I-NP O
. . O O
TRICUSPID NNP B-NP O
VALVE NNP I-NP O
- : O O
IVC NNP B-NP O
, , O O
SVC NNP B-NP O
There EX B-NP O
is VBZ B-VP O
color NN B-NP O
and CC O O
spectral JJ B-NP O
Doppler NNP I-NP O
evidence NN I-NP O
of IN B-PP O
trace NN B-NP O
tricuspid JJ I-NP O
insufficiency NN I-NP O
. . O O
RIGHT NNP B-NP O
VENTRICLE NNP I-NP O
The DT B-NP O
right JJ I-NP O
ventricle NN I-NP O
is VBZ B-VP O
not RB I-VP O
dilated VBN I-VP O
. . O O
The DT B-NP O
right NN I-NP O
ventricular VBD B-VP O
systolic JJ B-NP O
function NN I-NP O
is VBZ B-NP O
within IN B-PP O
normal JJ B-NP O
limits NNS I-NP O
. . O O
PERICARDIAL NNP B-NP O
DISEASE NN I-NP O
AND CC I-NP O
EXTRACARDIAC NNPS I-NP O
MASSES NNS I-NP O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
pericardial JJ B-NP O
effusion NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
a DT B-NP O
space NN I-NP O
between IN B-PP O
visceral JJ B-NP O
and CC I-NP O
parietal NN I-NP O
pericardium NN I-NP O
most RBS B-NP O
c/w JJ I-NP O
pericardial JJ I-NP O
fat NN I-NP O
. . O O
CONCLUSIONS NNS B-NP O
Compared VBN B-VP O
to TO B-PP O
the DT B-NP O
study NN I-NP O
of IN B-PP O
9/12/73 CD B-NP B-DATE
, , O O
the DT B-NP O
EF NNP I-NP O
has VBZ B-VP O
dropped VBN I-VP O
by IN B-PP O
10 CD B-NP O
% NN I-NP O
and CC O O
apical JJ B-NP O
wall NN I-NP O
motion NN B-NP O
abnormalities NNS I-NP O
are VBP B-VP O
now RB I-VP O
noted VBN I-VP O
. . O O
CCU NNP B-NP O
Course/Plan NNP I-NP O
72 CD B-NP B-AGE
year NN I-NP O
old JJ I-NP O
woman NN I-NP O
with IN B-PP O
ESRD NNP B-NP O
, , O O
positive JJ B-NP O
troponin FW I-NP O
in IN B-PP O
setting VBG B-VP O
SOB NNP B-NP O
and CC O O
pulmonary JJ B-NP O
oedema NN I-NP O
on IN B-PP O
CXR NNP B-NP O
. . I-NP O
Suspect NNP I-NP O
leak NN I-NP O
from IN B-PP O
demand NN B-NP O
. . O O
1 CD B-NP O
) -RRB- I-NP O
ischemia NN I-NP O
: : O O
ASA NNP B-NP O
, , O O
BB NNP B-NP O
. . O O
Would MD O O
doubt NN B-VP O
she PRP B-NP O
needs VBZ B-VP O
urgent JJ B-NP O
cath NN I-NP O
but CC O O
will MD B-VP O
hold VB I-VP O
NPO NNP B-NP O
for IN B-PP O
potential JJ B-NP O
cath NN I-NP O
in IN B-PP O
am VBP B-NP O
. . O O
Would MD B-VP O
not RB I-VP O
add VB I-VP O
heparin NN B-NP O
. . O O
Check VB B-VP O
fasting VBG I-VP O
lipids NNS B-NP O
. . O O
2 CD B-NP O
) -RRB- I-NP O
rhythm NN I-NP O
: : O O
so RB B-ADVP O
far RB I-ADVP O
not RB I-ADVP O
an DT B-NP O
issue NN I-NP O
. . O O
BB NNP O O
as IN B-PP O
tolerated VBN B-NP O
. . O O
3 CD B-NP O
) -RRB- I-NP O
pump NN I-NP O
: : O O
she PRP B-NP O
has VBZ B-VP O
LVH NNP B-NP O
and CC O O
likely JJ B-NP O
diastolic JJ I-NP O
dysfunction NN I-NP O
. . O O
Would MD B-VP O
prefer VB I-VP O
to TO I-VP O
have VB I-VP O
ACE NNP B-NP O
on IN B-PP O
board NN B-NP O
- : O O
will MD B-VP O
d/w RB I-VP O
renal VB I-VP O
as IN B-PP O
to TO B-PP O
why WRB B-ADVP O
not RB I-ADVP O
. . O O
4 CD B-NP O
) -RRB- I-NP O
ESRD NNP B-NP O
- : O O
can MD B-VP O
go VB I-VP O
for IN B-PP O
HD NNP B-NP O
today NN B-NP O
. . O O
Need VB B-VP O
to TO I-VP O
contact VB I-VP O
dialysis NN B-NP O
unit NN I-NP O
to TO B-VP O
arrange VB I-VP O
time NN B-NP O
. . O O
5 CD B-NP O
) -RRB- I-NP O
DM NNP I-NP O
2 CD I-NP O
- : O O
SSI NN B-NP O
for IN B-PP O
now RB B-NP O
, , O O
will MD B-VP O
likely RB I-VP O
give VB I-VP O
back RB B-ADVP O
Lantus RB I-ADVP O
tonight RB I-ADVP O
. . O O
She PRP B-NP O
is VBZ B-VP O
v RB B-ADJP O
reluctant JJ I-ADJP O
to TO B-VP O
have VB I-VP O
SSI NNP B-NP O
, , O O
will MD B-VP O
give VB I-VP O
at IN B-PP O
half DT B-NP O
usual JJ I-NP O
doses NNS I-NP O
. . O O
6 CD B-NP O
) -RRB- I-NP O
FEN NNP I-NP O
cardiac NN I-NP O
, , O O
diabetic JJ B-NP O
diet NN I-NP O
. . O O
Hold VB B-VP O
NPO NNP B-NP O
pending VBG B-VP O
possible JJ B-NP O
cath NN I-NP O
in IN B-PP O
am VBP B-NP O
. . O O
7 CD B-NP O
) -RRB- I-NP O
Prophylaxis NNP I-NP O
: : O O
GI NNP B-NP O
: : O O
Nexium NNP B-NP O
, , O O
DVT NNP B-NP O
: : O O
Heparin NNP B-NP O
IV NNP I-NP O
; : O O
BM NNP B-NP O
: : O O
prn NN B-NP O
. . O O
8 CD B-NP O
) -RRB- I-NP O
Dispo VB B-VP O
- : O O
to TO B-PP O
SDU NNP B-NP O
today NN I-NP O
Eddie NNP B-NP B-DOCTOR
Clark NNP I-NP I-DOCTOR
, , O O
24144 CD O B-PHONE
