Record NNP B-NP O
date NN I-NP O
: : O O
2136-03-30 CD O B-DATE
SDU NNP B-NP O
JAR NNP I-NP O
Admission NNP I-NP O
Note NN I-NP O
Uecker NNP B-NP I-PATIENT
, , O I-PATIENT
Vastie NNP B-NP I-PATIENT
MR# NNP B-NP O
3038560 CD I-NP B-MEDICALRECORD
Date NNP B-NP O
of IN B-PP O
Admission NNP B-NP O
: : O O
3/30/36 CD O B-DATE
Attending VBG B-VP O
: : O O
Dr. NNP B-NP O
Zehr NNP I-NP B-DOCTOR
Admitting VBG B-NP O
Resident NN I-NP O
: : O O
Patricia NNP B-NP B-DOCTOR
Nunn NNP I-NP I-DOCTOR
Source NN B-NP O
of IN B-PP O
history NN B-NP O
: : O O
records NNS B-NP O
and CC O O
pt NN B-NP O
ID/CC NNP B-NP O
: : O O
62 CD B-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
w/ VBD B-VP O
hx NN B-NP O
of IN B-PP O
bronchiectasis NN B-NP O
s/p NN I-NP O
lobectomy NN I-NP O
, , O O
chronic JJ B-NP O
MAC NNP I-NP O
, , O O
HTN NNP B-NP O
, , O O
fibromyalgia NN B-NP O
, , O O
and CC O O
raynaud NN B-NP O
s VBZ B-VP O
presented VBN I-VP O
to TO B-PP O
OSH NNP B-NP O
w/ IN B-PP O
chest NN B-NP O
pain NN I-NP O
, , O O
transferred VBN B-VP O
to TO I-VP O
PCH VB I-VP B-HOSPITAL
w/NSTEMI NNS B-NP O
and CC I-NP O
DVTs NNS I-NP O
. . O O
HPI NNP B-NP O
: : O O
Pt NNP B-NP O
at IN B-PP O
baseline NN B-NP O
occasionally RB B-ADVP O
gets VBZ B-VP O
SOB NNP B-NP O
from IN B-PP O
her PRP$ B-NP O
bronchiectasis NN I-NP O
if IN B-SBAR O
she PRP B-NP O
has VBZ B-VP O
not RB I-VP O
had VBN I-VP O
chest NN B-NP O
PT NN I-NP O
recently RB B-ADVP O
but CC O O
otherwise RB B-VP O
is VBZ I-VP O
able JJ B-ADJP O
to TO B-VP O
walk VB I-VP O
up IN B-PRT O
multiple JJ B-NP O
flights NNS I-NP O
of IN B-PP O
stairs NNS B-NP O
without IN B-PP O
SOB. NNP B-NP O
She PRP B-NP O
has VBZ B-VP O
no DT B-NP O
known VBN I-NP O
cardiac NN I-NP O
hx NN I-NP O
but CC O O
does VBZ B-VP O
have VB I-VP O
HTN NNP B-NP O
and CC I-NP O
+ NNP I-NP O
fam NN I-NP O
hx NN I-NP O
of IN B-PP O
early JJ B-NP O
CAD. NNP I-NP O
Pt NNP I-NP O
awoke VBD B-VP O
this DT B-NP O
morning NN I-NP O
in IN B-PP O
her PRP$ B-NP O
USOH NNP I-NP O
but CC O O
quickly RB B-VP O
had VBD I-VP O
sudden JJ B-NP O
onset NN I-NP O
of IN B-PP O
10/10 CD B-NP O
sharp JJ I-NP O
SSCP NNP I-NP O
radiating NN I-NP O
to TO B-PP O
her PRP$ B-NP O
right JJ I-NP O
arm NN I-NP O
associated VBN B-VP O
w/ RB B-NP O
right JJ I-NP O
arm NN I-NP O
numbness NN I-NP O
. . O O
Pain NNP B-NP O
is VBZ B-VP O
slightly RB B-ADVP O
better JJR B-NP O
w/ NN I-NP O
sitting VBG B-VP O
up RP B-PRT O
though IN B-NP O
pt NN I-NP O
denies VBZ B-VP O
pleuritic JJ B-NP O
quality NN I-NP O
. . O O
She PRP B-NP O
then RB B-ADVP O
had VBD B-VP O
a DT B-NP O
vasovagal JJ I-NP O
attack NN I-NP O
, , O O
which WDT B-NP O
she PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
before RB B-ADVP O
in IN B-PP O
the DT B-NP O
setting NN I-NP O
of IN B-PP O
pain NN B-NP O
, , O O
and CC O O
she PRP B-NP O
started VBD B-VP O
to TO I-VP O
feel VB I-VP O
lightheaded JJ B-NP O
, , I-NP O
nauseated JJ I-NP O
, , I-NP O
and CC I-NP O
diaphoretic JJ I-NP O
. . O O
She PRP B-NP O
laid VBD B-VP O
down RP B-PRT O
on IN B-PP O
the DT B-NP O
floor NN I-NP O
and CC O O
elevated VBD B-VP O
her PRP$ B-NP O
legs NNS I-NP O
above IN B-PP O
her PRP$ B-NP O
head NN I-NP O
which WDT B-NP O
helped VBD B-VP O
a DT B-NP O
little JJ I-NP O
. . O O
Her PRP$ B-NP O
husband NN I-NP O
gave VBD B-VP O
her PRP$ B-NP O
Excedrin NNP I-NP O
w/o NN I-NP O
improvement NN I-NP O
and CC O O
called VBD B-VP O
911 CD B-NP O
. . O O
EMS NNP B-NP O
gave VBD B-VP O
her PRP B-NP O
3 CD B-NP O
puffs NNS I-NP O
of IN B-PP O
NTG NNP B-NP O
and CC O O
4 CD B-NP O
baby NN I-NP O
ASA NNP I-NP O
w/o VBD B-VP O
effect NN B-NP O
. . O O
The DT B-NP O
ambulance NN I-NP O
brought VBD B-VP O
her PRP B-NP O
to TO B-PP O
the DT B-NP O
closest JJS I-NP O
hospital NN I-NP O
, , O O
Colorow NNP B-NP B-HOSPITAL
. . O O
In IN B-PP O
the DT B-NP O
ED NNP I-NP O
, , O O
she PRP B-NP O
was VBD B-VP O
found VBN I-VP O
to TO I-VP O
be VB I-VP O
hypertensive JJ B-NP O
w/ NN I-NP O
SBP NNP B-NP O
180s CD I-NP O
, , O O
for IN B-PP O
which WDT B-NP O
she PRP B-NP O
was VBD B-VP O
started VBN I-VP O
on IN B-PP O
TNG NNP B-NP O
gtt NNP I-NP O
. . O O
She PRP B-NP O
also RB B-ADVP O
underwent VBD B-VP O
PE NN B-NP O
CT NNP I-NP O
which WDT I-NP O
per IN B-PP O
report NN B-NP O
was VBD B-VP O
neg JJ B-ADJP O
for IN B-PP O
PE NN B-NP O
but CC O O
showed VBD B-VP O
bilat IN B-PP O
DVTs NNP B-NP O
, , O O
and CC O O
she PRP B-NP O
was VBD B-VP O
started VBN I-VP O
on IN B-PP O
heparin NN B-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
given VBN I-VP O
fioricet NN B-NP O
, , I-NP O
zofran NN I-NP O
, , O O
and CC O O
fentanyl NN B-NP O
for IN B-PP O
her PRP$ B-NP O
CP CD I-NP O
w/ JJ I-NP O
relief NN I-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
then RB I-VP O
given VBN I-VP O
a DT B-NP O
dose NN I-NP O
of IN B-PP O
IV NNP B-NP O
lopressor NN I-NP O
and CC O O
also RB B-ADVP O
had VBD B-VP O
one CD B-NP O
episode NN I-NP O
of IN B-PP O
N/V NNP B-NP O
. . O O
Her PRP$ B-NP O
labs NNS I-NP O
were VBD B-VP O
significant JJ B-ADJP O
for IN B-PP O
+ NN B-NP O
cardiac NN I-NP O
markers NNS I-NP O
: : O O
1st JJ B-NP O
set NN I-NP O
w/ NN I-NP O
CK/MB/index NNP B-NP O
39/0.9/2.3 CD I-NP O
, , O O
trop FW B-NP O
I PRP I-NP O
0.03 CD I-NP O
, , I-NP O
2nd CD I-NP O
443/57.3/12.9 CD I-NP O
, , O O
trop FW B-NP O
2.22 CD I-NP O
, , O O
3rd JJ B-NP O
set NN I-NP O
686/87.3/12.7 CD B-NP O
, , O O
trop FW B-NP O
4.18 CD I-NP O
. . O O
EKGs NNP B-NP O
showed VBD B-VP O
right-bundle JJ B-NP O
morphology NN I-NP O
( -LRB- O O
though IN B-SBAR O
QRS NNP B-NP O
not RB I-NP O
wide JJ I-NP O
) -RRB- I-NP O
w/ JJ I-NP O
initial JJ I-NP O
TWI NNP I-NP O
V1-V3 NN I-NP O
which WDT B-NP O
progressed VBD B-VP O
to TO B-PP O
deepening VBG B-VP O
TWI NNP B-NP O
V1-V4 NNP I-NP O
and CC O O
some DT B-NP O
downsloping NN I-NP O
STD NNP I-NP O
V3-V4 NNP I-NP O
. . I-NP O
Pt NNP I-NP O
is VBZ B-VP O
currently RB B-ADVP O
chest NN B-NP O
pain NN I-NP O
free JJ I-NP O
, , O O
no DT B-NP O
SOB NNP I-NP O
, , O O
no DT B-NP O
palpitations NNS I-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
preceding VBG I-NP O
viral JJ I-NP O
illness NN I-NP O
or CC O O
any DT B-NP O
surprises NNS I-NP O
or CC I-NP O
acute JJ I-NP O
stressors NNS I-NP O
in IN B-PP O
her PRP$ B-NP O
life NN I-NP O
, , O O
though IN B-SBAR O
she PRP B-NP O
has VBZ B-VP O
many JJ B-NP O
chronic JJ I-NP O
medical JJ I-NP O
problems NNS I-NP O
. . O O
ROS NNP B-NP O
: : O O
as IN B-SBAR O
per IN B-NP O
HPI NN I-NP O
PMH: . O O
1 LS O O
. . B-NP O
History NN I-NP O
of IN B-PP O
bronchiectasis NN B-NP O
s/p RB B-ADJP O
right JJ I-ADJP O
middle NN B-NP O
lobectomy NN I-NP O
in IN B-PP O
2128 CD B-NP B-DATE
. . O O
2. DT B-NP O
History NN I-NP O
of IN B-PP O
MAC NNP B-NP O
with IN B-PP O
treatment NN B-NP O
interrupted JJ B-ADJP O
by IN B-PP O
hepatitis NN B-NP O
in IN B-PP O
2128 CD B-NP B-DATE
. . O O
3. DT B-NP O
Perforated JJ I-NP O
diverticulitis NN I-NP O
with IN B-PP O
sigmoid JJ B-NP O
resection NN I-NP O
in IN B-PP O
2129 CD B-NP B-DATE
. . O O
4 CD B-LST O
. . O O
Raynaud NNP B-NP O
's POS B-NP O
. . O O
5 CD B-NP O
. . O O
Fibromyalgia NNP B-NP O
. . O O
6 CD B-NP O
. . O O
Migraine NNP B-NP O
. . O O
7. DT B-NP O
Hypertension NNP I-NP O
. . O O
8. . B-NP O
GERD. NNP I-NP O
9 CD B-NP O
. . I-NP O
Hiatal NNP I-NP O
and CC O O
ventral JJ B-NP O
hernia NN I-NP O
. . O O
10 CD B-NP O
. . I-NP O
Status NNP I-NP O
post NN I-NP O
appendectomy NN I-NP O
. . O O
11 CD B-NP O
. . O O
Osteopenia NNP B-NP O
. . O O
12 CD B-NP O
. . O O
Hx NNP O O
of IN B-PP O
serum NN B-NP O
sickness NN I-NP O
in IN B-PP O
the DT B-NP O
setting NN I-NP O
of IN B-PP O
Amox-clavulanate JJ B-NP O
11/33 CD I-NP B-DATE
13 CD B-NP O
. . O O
Mild NNP B-NP O
pectus NN I-NP O
excavatum NN I-NP O
noted VBD B-VP O
on IN B-PP O
CXR NN B-NP O
14 CD B-LST O
. . O O
hx NN B-NP O
of IN B-PP O
Ophthalmic NNP B-NP O
( -LRB- I-NP O
V1 NN I-NP O
) -RRB- I-NP O
zoster NN I-NP O
in IN B-PP O
10s PRP$ B-NP B-DATE
15 CD B-LST O
. . O O
hx NN B-NP O
of IN B-PP O
R NN B-NP O
OM NN I-NP O
c/b NN I-NP O
mild JJ I-NP O
hearing NN I-NP O
loss NN I-NP O
( -LRB- B-PP O
2130 CD B-NP B-DATE
) -RRB- O O
16 CD B-LST O
. . O O
newly-diagnosed '' O O
DM . O O
Medications NNS B-NP O
: : O O
1 LS O O
. . B-NP O
Albuterol NNP I-NP O
Nebulizer NNP I-NP O
NEB NNP I-NP O
2.5 CD I-NP O
MG NNP I-NP O
BID NNP I-NP O
2. . B-NP O
Ascorbic NNP I-NP O
Acid NNP I-NP O
( -LRB- I-NP O
Vitamin NN I-NP O
C NNP I-NP O
) -RRB- I-NP O
PO NNP I-NP O
500 CD I-NP O
MG NNP I-NP O
BID NNP I-NP O
3. . B-NP O
Dicloxacillin NNP I-NP O
PO NNP I-NP O
250 CD I-NP O
MG NNP I-NP O
QID NNP I-NP O
4 CD B-LST O
. . O O
Docusate NNP B-NP O
Sodium NNP I-NP O
( -LRB- I-NP O
Colace NNP I-NP O
) -RRB- I-NP O
PO NNP I-NP O
100 CD I-NP O
MG NNP I-NP O
BID NNP I-NP O
5 CD B-NP O
. . O O
Butalbital+Apap+Caffeine NNP O O
( -LRB- O O
Fioricet NNP B-NP O
) -RRB- I-NP O
PO NNP I-NP O
1 CD I-NP O
TAB NNP I-NP O
Q4H NNP I-NP O
prn NN I-NP O
headache NN I-NP O
6 CD B-NP O
. . O O
Estradiol NNP B-NP O
Tabs NNP I-NP O
( -LRB- I-NP O
Estradiol JJ I-NP O
Patch NN I-NP O
) -RRB- I-NP O
PO NN I-NP O
2 CD I-NP O
MG NNP I-NP O
QD . O O
7. . B-NP O
Medroxyprogesterone NNP I-NP O
PO NNP I-NP O
5 CD I-NP O
MG NNP I-NP O
QD NNP I-NP O
8. CD B-NP O
Multivitamins NNP I-NP O
( -LRB- I-NP O
Multivitamin NNP I-NP O
) -RRB- I-NP O
PO NNP I-NP O
1 CD I-NP O
TAB NNP I-NP O
QD . O O
9 CD B-NP O
. . I-NP O
Nortriptyline NNP I-NP O
Hcl NNP I-NP O
( -LRB- I-NP O
Nortriptyline NNP I-NP O
) -RRB- B-PP O
PO NNP B-NP O
75 CD I-NP O
MG NNP I-NP O
QHS . O O
10 CD B-NP O
. . O O
Omeprazole NNP B-NP O
PO NNP I-NP O
20 CD I-NP O
MG NNP I-NP O
QD . O O
11 CD B-NP O
. . O O
Propranolol NNP B-NP O
Extended NNP I-NP O
Release NNP I-NP O
( -LRB- I-NP O
Inderal JJ I-NP O
La NNP I-NP O
) -RRB- I-NP O
PO NNP I-NP O
240 CD I-NP O
mg NN I-NP O
QD . O O
Allergies NNP B-NP O
: : O O
percocet/darvon/codeine NN B-NP O
GI IN B-PP O
upset JJ B-NP O
, , O O
sulfa VBD B-VP O
kidney NN B-NP O
problem NN I-NP O
, , O O
throat NN B-NP O
closed VBD B-VP O
flagyl NN B-NP O
throat NN I-NP O
closed VBN O O
SH NNS B-NP O
: : O O
married VBN B-ADJP O
, , O O
no DT B-NP O
children NNS I-NP O
, , O O
lives NNS B-NP O
w/ VBP B-VP O
husband NN B-NP O
, , O O
retired VBN B-NP O
firefighter NN I-NP B-PROFESSION
Tob NNP B-NP O
: : O O
none NN B-NP O
EtOH NNP B-NP O
: : O O
none NN B-NP O
Illicits NNS B-NP O
: : O O
Negative JJ O O
FH NNP B-NP O
: : O O
mother NN B-NP O
w/ VBD B-VP O
multiple JJ B-NP O
MIs NN I-NP O
( -LRB- I-NP O
first JJ I-NP O
age NN I-NP O
40s NNS I-NP B-AGE
) -RRB- O O
, , O O
HTN NNP B-NP O
, , O O
scleroderma NN B-NP O
, , O O
raynaud NN B-NP O
s VBZ B-LST O
Exam NNP B-NP O
: : O O
VS NNP B-NP O
: : O O
T=99.4 NNP B-NP O
HR= NNP I-NP O
77 CD I-NP O
BP NNP I-NP O
135/64 CD I-NP O
RR= NNP B-NP O
18 CD I-NP O
SaO2= NNP B-NP O
98 CD I-NP O
%2L . O O
general JJ B-NP O
: : O O
NAD NNP B-NP O
, , O O
soft JJ B-NP O
voice NN I-NP O
HEENT NNP B-NP O
: : O O
OP NNP B-NP O
w/ VBD B-VP O
MMM NNP B-NP O
, , O O
NCAT NN B-NP O
Skin NNP B-NP O
: : O O
No DT B-NP O
rashes NNS I-NP O
Neck NNP B-NP O
: : O O
Supple NN B-NP O
, , O O
full JJ B-NP O
ROM NNP I-NP O
, , O O
2+ CD B-NP O
carotids NNS I-NP O
w/o IN B-PP O
bruits NNS B-NP O
, , O O
JVP NNP B-NP O
7 CD I-NP O
cm NN I-NP O
Chest NNP B-NP O
: : O O
decreased VBN B-VP O
BS NNP B-NP O
, , O O
CTAB NNP B-NP O
CVS NNP B-NP O
: : O O
RRR NNP B-NP O
, , O O
nl JJ B-NP O
S1 NNP I-NP O
S2 NNP I-NP O
, , O O
no DT B-NP O
rub NN I-NP O
Abd NNP B-NP O
: : O O
nl JJ B-NP O
BS NNP I-NP O
, , O O
soft JJ B-NP O
, , I-NP O
non-tender JJ I-NP O
, , I-NP O
nondistended JJ I-NP O
, , O O
no DT B-NP O
organomegaly NN I-NP O
, , O O
midline NN B-NP O
scar NN I-NP O
well-healed WP B-LST O
Extr NNP B-NP O
: : O O
2+ JJ B-NP O
radial JJ I-NP O
pulses NNS I-NP O
, , O O
2+ JJ B-NP O
femoral JJ I-NP O
pulses NNS I-NP O
w/o IN B-PP O
bruits NNS B-NP O
bilat NN I-NP O
, , O O
no DT B-NP O
LE JJ I-NP O
edema NN I-NP O
, , O O
2+ CD B-NP O
DPs NNS I-NP O
bilaterally RB O O
Neuro NNP B-NP O
: : O O
alert JJ B-NP O
and CC I-NP O
oriented JJ I-NP O
x3 NNS I-NP O
, , O O
grossly RB B-ADVP O
intact JJ O O
DATA NNP B-NP O
: : O O
pending VBG B-NP O
Chem NNP B-NP O
: : O O
Chemistry NN B-NP O
Comments NNS I-NP O
Fasting VBG B-LST O
Plasma NNP B-NP O
Sodium NNP I-NP O
130 CD I-NP O
L NNP B-NP O
( -LRB- I-NP O
135-145 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Plasma NNP B-NP O
Potassium NNP I-NP O
3.5 CD I-NP O
( -LRB- I-NP O
3.4-4.8 CD B-NP O
) -RRB- I-NP O
mmol/L . O O
Plasma NNP B-NP O
Chloride NNP I-NP O
97 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
100-108 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Plasma NNP B-NP O
Carbon NNP I-NP O
Dioxide NNP I-NP O
22.4 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
23.0-31.9 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Calcium NNP B-NP O
8.7 CD I-NP O
( -LRB- I-NP O
8.5-10.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Magnesium NNP B-NP O
1.6 CD I-NP O
( -LRB- O O
1.4-2.0) CD B-NP O
meq/L NN I-NP O
Plasma NNP B-NP O
Urea NNP I-NP O
Nitrogen NNP I-NP O
9 CD I-NP O
(8-25 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Plasma NNP B-NP O
Creatinine NNP I-NP O
0.8 CD I-NP O
( -LRB- I-NP O
0.6-1.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Plasma NNP B-NP O
Glucose NNP I-NP O
112 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
70-110 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Triglycerides NNS B-NP O
192 CD B-NP O
H NNP I-NP O
( -LRB- I-NP O
40-150 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Cholesterol NNP B-NP O
212 CD I-NP O
mg/dl NN I-NP O
DESIRABLE NNP B-NP O
: : O O
<200 CD O O
High NNP B-NP O
Density NNP I-NP O
Lipoprotein NNP I-NP O
44 CD I-NP O
( -LRB- I-NP O
35-100 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Low NNP B-NP O
Density NNP I-NP O
Lipoprotein NNP I-NP O
130 CD I-NP O
mg/dl NN I-NP O
DESIRABLE NNP B-NP O
: : O O
<130 CD O O
Cardiac NNP B-NP O
Risk NNP I-NP O
Ratio NNP I-NP O
4.8 CD O O
NORMAL NNP B-NP O
RISK NNP I-NP O
RATIO NNP I-NP O
: : O O
5.0 CD B-NP O
OR JJ I-NP O
LESS NNS I-NP O
Creatine JJ B-NP O
Kinase NNP I-NP O
Isoenzymes NNP I-NP O
80.4 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.0-6.9 CD I-NP O
) -RRB- I-NP O
ng/ml . O O
CPK NNP B-NP O
Isoenzymes NNP I-NP O
Index NNP I-NP O
9.8 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.0-3.5 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Troponin-T NNP B-NP O
1.26 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.00-0.09 CD I-NP O
) -RRB- I-NP O
ng/ml . O O
Creatine JJ B-NP O
Kinase NNP I-NP O
818 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
40-150 CD I-NP O
) -RRB- I-NP O
U/L . O O
Heme NNP B-NP O
: : O O
WBC NNP B-NP O
14.2 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
4.5-11.0) JJ I-NP O
th/cmm NN I-NP O
HCT NNP B-NP O
35.2 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
36.0-46.0) CD I-NP O
% NN I-NP O
HGB NN B-NP O
12.5 CD I-NP O
( -LRB- O O
12.0-16.0) CD B-NP O
gm/dl NN I-NP O
RBC NNP B-NP O
3.94 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
4.00-5.20 CD I-NP O
) -RRB- I-NP O
mil/cmm . O O
PLT NNP B-NP O
361 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
150-350 CD I-NP O
) -RRB- I-NP O
th/cumm . O O
MCV NN B-NP O
89 CD I-NP O
( -LRB- I-NP O
80-100 CD B-PP O
) -RRB- B-NP O
fl NN I-NP O
MCH NNP B-NP O
31.8 CD I-NP O
( -LRB- I-NP O
26.0-34.0) JJ I-NP O
pg/rbc NN I-NP O
MCHC NNP B-NP O
35.7 CD I-NP O
( -LRB- O O
31.0-37.0) CD B-NP O
g/dl NN I-NP O
RDW NNP B-NP O
13.6 CD I-NP O
( -LRB- I-NP O
11.5-14.5 CD B-PP O
) -RRB- B-NP O
% NN I-NP O
PT NNP B-NP O
14.7 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
10.3-13.2 CD B-PP O
) -RRB- B-NP O
sec NN I-NP O
PT-INR NN B-NP O
1.3 CD I-NP O
APTT NNP B-NP O
131.0 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
22.1-34.0) JJ I-NP O
sec NN I-NP O
DIFFERENTIAL NNP B-NP O
REQUEST NNP I-NP O
RECEIVED NNP I-NP O
Diff JJ B-NP O
Method NNP I-NP O
Auto NN I-NP O
Poly NNP B-NP O
81 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
40-70 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Lymphs NNS B-NP O
12 CD B-NP O
L NNP I-NP O
( -LRB- I-NP O
22-44 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Monos NNP B-NP O
6 CD I-NP O
( -LRB- I-NP O
4-11 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
EOS NNS B-NP O
1 CD B-NP O
(0-8 CD I-NP O
) -RRB- O O
% NN O O
Basos NNS B-NP O
0 CD B-NP O
(0-3 JJ I-NP O
) -RRB- I-NP O
% NN I-NP O
Absolute JJ B-NP O
Neuts NNP I-NP O
11.41 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
1.8-7.7 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Lymphs NNP I-NP O
1.76 CD I-NP O
( -LRB- I-NP O
1.0-4.8 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Monos NNP I-NP O
0.88 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.2-0.4 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
EOS NNP I-NP O
0.08 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
0.1-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Basos NNP I-NP O
0.05 CD I-NP O
( -LRB- I-NP O
0.0-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Aniso NNP B-NP O
None NN I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Hypo NNP B-NP O
None NN I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Macrocytes NNP B-NP O
None NN I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Microcytes NNS B-NP O
None NN B-VP O
( -LRB- B-NP O
None NN I-NP O
) -RRB- O O
Micro NNP B-NP O
: : O O
pending VBG O O
PE NN B-NP O
CT NNP I-NP O
( -LRB- I-NP O
reviewed VBN B-VP O
w/ RB B-NP O
ED VBN I-NP O
rads NNS I-NP O
here RB B-ADVP O
) -RRB- B-VP O
: : O O
no DT B-NP O
PE NN I-NP O
to TO B-PP O
the DT B-NP O
level NN I-NP O
of IN B-PP O
subsegmental JJ B-NP O
arteries NNS I-NP O
, , O O
no DT B-NP O
dissection NN I-NP O
, , O O
no DT B-NP O
pericardial JJ I-NP O
effusion NN I-NP O
or CC I-NP O
bowing NN I-NP O
of IN B-PP O
interventricular JJ B-NP O
septum NN I-NP O
to TO B-VP O
suggest VB I-VP O
RV NN B-NP O
strain NN I-NP O
, , O O
lung NN B-NP O
parenchyma NN I-NP O
w/ NN I-NP O
scattered VBN I-NP O
nodules NNS I-NP O
, , O O
largest JJS B-NP O
6.5 CD I-NP O
mm CD I-NP O
, , O O
bilat JJ B-NP O
fem NN I-NP O
veins NNS I-NP O
w/ VBP B-VP O
filling VBG I-VP O
defects NNS B-NP O
EKG NNP B-NP O
: : O O
NSR NNP B-NP O
78 CD I-NP O
bpm NN I-NP O
, , O O
IVCD NNP B-NP O
w/ VBD B-VP O
right-bundle JJ B-NP O
morphology NN I-NP O
unchanged JJ B-ADJP O
w/ IN B-PP O
TWI NNP B-NP O
V1-V2 NNP I-NP O
, , O O
flat JJ B-NP O
Ts NNS I-NP O
I PRP B-NP O
, , O O
avL JJ B-NP O
, , I-NP O
1 CD I-NP O
mm CD I-NP O
downsloping NN I-NP O
STD NNP I-NP O
V3 NNP I-NP O
, , O O
< NNP B-NP O
1 CD I-NP O
mm CD I-NP O
horizontal JJ I-NP O
STD NNP I-NP O
V4 . O O
TTE NNP B-NP O
: : O O
prelim NN B-NP O
read VBD B-VP O
RV NN B-NP O
and CC I-NP O
LV NNP I-NP O
function NN I-NP O
wnl NN I-NP O
, , O O
no DT B-NP O
segmental JJ I-NP O
WMA NN I-NP O
Impression NN B-NP O
: : O O
62 CD B-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
w/ VBD B-VP O
hx NN B-NP O
of IN B-PP O
bronchiectasis NN B-NP O
s/p NN I-NP O
lobectomy NN I-NP O
, , O O
chronic JJ B-NP O
MAC NNP I-NP O
, , O O
HTN NNP B-NP O
, , O O
fibromyalgia NN B-NP O
, , O O
and CC O O
raynaud NN B-NP O
s VBZ B-VP O
presented VBN I-VP O
to TO B-PP O
OSH NNP B-NP O
w/ IN B-PP O
chest NN B-NP O
pain NN I-NP O
, , O O
transferred VBN B-VP O
to TO I-VP O
PCH VB I-VP B-HOSPITAL
w/ JJ B-NP O
NSTEMI NNP I-NP O
and CC I-NP O
DVTs NNP I-NP O
, , O O
now RB B-ADVP O
chest NN B-VP O
pain NN B-NP O
free JJ B-ADJP O
. . O O
Possible JJ B-NP O
etiologies NNS I-NP O
for IN B-PP O
her PRP$ B-NP O
chest NN I-NP O
pain NN I-NP O
w/ VBN B-VP O
+ IN B-PP O
cardiac JJ B-NP O
markers NNS I-NP O
include VBP B-VP O
ACS NNP B-NP O
, , I-NP O
PE NN I-NP O
, , I-NP O
myopericarditis NN I-NP O
, , I-NP O
spasm NN I-NP O
, , I-NP O
or CC I-NP O
apical JJ I-NP O
ballooning NN I-NP O
syndrome NN I-NP O
. . O O
Dissection NN B-VP O
less RBR B-NP O
likely JJ I-NP O
w/ NN I-NP O
equal JJ I-NP O
pulses NNS I-NP O
and CC O O
not RB B-VP O
seen VBN I-VP O
on IN B-PP O
PE NN B-NP O
CT. NNP B-PP O
Her PRP$ B-NP O
EKG JJ I-NP O
changes NNS I-NP O
suggest VBP B-VP O
an DT B-NP O
element NN I-NP O
of IN B-PP O
RV NN B-NP O
strain NN I-NP O
, , O O
though IN B-SBAR O
this DT B-NP O
is VBZ B-VP O
not RB I-VP O
borne VBN I-VP O
out RP B-ADJP O
on IN B-PP O
TTE NNP B-NP O
, , O O
and CC O O
review NN B-NP O
of IN B-PP O
her PRP$ B-NP O
OSH NNP I-NP O
CT NNP I-NP O
w/ VBD B-VP O
radiology NN B-NP O
here RB B-ADVP O
did VBD B-VP O
not RB I-VP O
reveal VB I-VP O
PEs NN B-NP O
( -LRB- O O
at IN B-ADVP O
least JJS I-ADVP O
to TO B-PP O
the DT B-NP O
level NN I-NP O
of IN B-PP O
subsegmental JJ B-NP O
arteries NNS I-NP O
) -RRB- B-VP O
. . O O
Her PRP$ B-NP O
TTE NN I-NP O
did VBD B-VP O
not RB I-VP O
show VB I-VP O
WMA NNP B-NP O
, , O O
and CC O O
her PRP$ B-NP O
story NN I-NP O
could MD B-VP O
be VB I-VP O
c/w JJ B-NP O
ACS NNP I-NP O
or CC I-NP O
c/w JJ I-NP O
myopericarditis NN I-NP O
or CC O O
apical JJ B-NP O
ballooning NN I-NP O
syndrome NN I-NP O
(esp NN I-NP O
w/ IN B-PP O
hx NN B-NP O
of IN B-PP O
fibromyalgia NN B-NP O
, , O O
raynaud NN B-NP O
s VBZ B-VP O
, , O O
migraines NNS B-NP O
, , O O
etc FW B-NP O
) -RRB- I-NP O
, , O O
though IN B-SBAR O
w/ JJ B-NP O
+ NN I-NP O
cardiac NN I-NP O
enzymes NNS I-NP O
and CC O O
dynamic JJ B-NP O
EKG JJ I-NP O
changes NNS I-NP O
, , O O
need NN B-NP O
to TO B-VP O
have VB I-VP O
low JJ B-NP O
threshold NN I-NP O
to TO B-PP O
cath NN B-NP O
if IN B-PP O
develops VBZ B-NP O
pain NN I-NP O
. . O O
Plan NNP B-NP O
: : O O
1 CD B-LST O
. . O O
ischemia NN O O
bblocker NN B-NP O
, , O O
ASA NNP B-NP O
check NN B-NP O
fasting VBG I-NP O
lipids NNS I-NP O
, , O O
start NN B-NP O
statin NN I-NP O
cont NN B-NP O
heparin NN I-NP O
, , O O
restart NN B-NP O
TNG NN I-NP O
gtt NN I-NP O
if IN B-PP O
pain NN B-NP O
recurs NNS I-NP O
start VB B-VP O
IIbIIIa NNP B-NP O
if IN B-PP O
persistent JJ B-NP O
pain NN I-NP O
2. . B-NP O
rhythm NN I-NP O
NSR NN B-NP O
On IN B-PP O
bblocker NN B-NP O
3. . O O
? . O O
DVT/PE . O O
check NN B-NP O
LENIS NNS I-NP O
cont NN B-NP O
heparin NN I-NP O
4 CD B-LST O
. . O O
leukocytosis NN O O
cx NN B-NP O
if IN B-SBAR O
spikes NNS B-NP O
f/u NN B-NP O
urine NN I-NP O
cx NN I-NP O
5 CD B-NP O
. . O O
MAC NNP O O
cont NN B-NP O
dicloxacillin VBG I-NP O
6 CD B-LST O
. . O O
DM '' O O
RISS NNP B-NP O
Diabetic JJ B-NP O
diet NN I-NP O
7. CD B-NP O
FEN NNS I-NP O
Monitor NN B-NP O
hyponatremia NN I-NP O
( -LRB- B-NP O
dates NNS I-NP O
back RB B-ADVP O
at IN B-ADVP O
least JJS I-ADVP O
as RB B-ADVP O
far RB I-ADVP O
as IN B-PP O
10/35 CD B-NP B-DATE
) -RRB- O O
8. . B-NP O
prophy NN I-NP O
heparin NN B-NP O
nexium . O O
FULL NNP B-NP O
CODE NNP I-NP O
( -LRB- B-VP O
per IN B-PP O
my PRP$ B-NP O
discussion NN I-NP O
w/ NN I-NP O
pt NN I-NP O
) -RRB- O O
Patricia NNP B-NP B-DOCTOR
Nunn NNP I-NP I-DOCTOR
, , O O
MD . O O
Pager NNP B-NP O
# # I-NP O
64177 CD O B-PHONE
