Record NNP B-NP O
date NN I-NP O
: : O O
2091-08-09 CD O B-DATE
August NNP B-NP B-DATE
9 CD I-NP I-DATE
, , I-NP I-DATE
2091 CD I-NP I-DATE
Billie NNP B-NP B-DOCTOR
Givens NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
138 CD B-NP B-STREET
Cross NNP I-NP I-STREET
Street NNP I-NP I-STREET
Juana NNP B-NP B-CITY
Diaz NNP I-NP I-CITY
, , O O
CT NNP B-NP B-STATE
89568 CD I-NP B-ZIP
Re NNP B-NP O
: : O O
Horn NNP B-NP I-PATIENT
, , O I-PATIENT
Gregory NNP B-NP I-PATIENT
BCC NNP B-NP B-HOSPITAL
Unit NNP I-NP O
# # I-NP O
: : O O
977-82-23 CD O B-MEDICALRECORD
Dear NNP B-NP O
Dr. NNP I-NP O
Givens NNP I-NP B-DOCTOR
: : O O
I PRP B-NP O
had VBD B-VP O
the DT B-NP O
pleasure NN I-NP O
of IN B-PP O
seeing VBG B-VP O
your PRP$ B-NP O
patient NN I-NP O
, , O O
Mr. NNP B-NP O
Horn NNP I-NP B-PATIENT
, , O O
in IN B-PP O
follow-up JJ B-NP O
regarding VBG I-NP O
possible JJ I-NP O
interstitial JJ I-NP O
lung NN I-NP O
disease NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
managed VBN I-VP O
to TO I-VP O
lose VB I-VP O
3 CD B-NP O
lbs NNS I-NP O
. . O O
on IN B-PP O
his PRP$ B-NP O
own JJ I-NP O
personal JJ I-NP O
diet NN I-NP O
plan NN I-NP O
, , O O
and CC O O
feels VBZ B-VP O
his PRP$ B-NP O
diabetes NN I-NP O
is VBZ B-VP O
coming VBG I-VP O
under IN B-PP O
slightly RB B-NP O
better JJR I-NP O
control NN I-NP O
. . O O
His PRP$ B-NP O
cough NN I-NP O
is VBZ B-VP O
virtually RB I-VP O
gone VBN I-VP O
and CC O O
now RB B-VP O
has VBZ I-VP O
only RB B-NP O
rare JJ I-NP O
cough NN I-NP O
with IN B-PP O
a DT B-NP O
little JJ I-NP O
bit NN I-NP O
of IN B-PP O
phlegm NN B-NP O
, , O O
grading VBG B-VP O
it PRP B-NP O
as IN B-PP O
2 CD B-NP O
out IN B-PP O
of IN B-PP O
10 CD B-NP O
vs. CC I-NP O
8-9 CD I-NP O
out IN B-PP O
of IN B-PP O
10 CD B-NP O
, , O O
to TO B-PP O
which WDT B-NP O
his PRP$ B-NP O
wife NN I-NP O
agrees VBZ B-VP O
. . O O
They PRP B-NP O
both DT O O
attribute VBP B-VP O
it PRP B-NP O
to TO B-PP O
the DT B-NP O
Prilosec. NNP I-NP O
He PRP B-NP O
now RB B-ADVP O
sleeps VBZ B-VP O
well RB B-ADVP O
and CC O O
does VBZ B-VP O
not RB I-VP O
use VB I-VP O
his PRP$ B-NP O
wedge NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
no DT B-NP O
snoring NN I-NP O
, , O O
daytime JJ B-NP O
hypersomnolence NN I-NP O
, , O O
or CC O O
morning NN B-NP O
headaches NNS I-NP O
- : O O
no RB B-ADVP O
longer RB I-ADVP O
falls VBZ B-VP O
asleep RB B-ADVP O
at IN B-PP O
work NN B-NP O
. . O O
Allergies NNP B-NP O
and CC O O
nasal JJ B-NP O
congestion NN I-NP O
are VBP B-VP O
not RB O O
evident JJ B-ADJP O
. . O O
No DT B-NP O
lower JJR I-NP O
extremity NN I-NP O
edema NN I-NP O
, , O O
swollen JJ B-NP O
glands NNS I-NP O
, , O O
or CC O O
fevers NNS B-NP O
. . O O
Mildly RB B-NP O
less RBR I-NP O
prominent JJ I-NP O
exertional JJ I-NP O
breathlessness NN I-NP O
- : O O
He PRP B-NP O
now RB B-ADVP O
occasionally RB B-ADVP O
has VBZ B-VP O
to TO I-VP O
go VB I-VP O
up IN B-PRT O
one CD B-NP O
flight NN I-NP O
of IN B-PP O
stairs NNS B-NP O
without IN B-PP O
stopping VBG B-NP O
. . O O
On IN B-PP O
examination NN B-NP O
, , O O
he PRP B-NP O
is VBZ B-VP O
well RB I-VP O
appearing VBG I-VP O
. . B-NP O
Respiratory NN I-NP O
rate NN I-NP O
22 CD I-NP O
and CC I-NP O
unlabored JJ I-NP O
. . O O
Blood NN B-NP O
pressure NN I-NP O
90/50 IN B-PP O
with IN B-PP O
a DT B-NP O
small JJ I-NP O
cuff NN I-NP O
. . O O
Conjunctivae NNS B-NP O
are VBP B-VP O
clear JJ B-ADJP O
. . O O
Oropharynx NNP B-NP O
is VBZ B-VP O
clear JJ B-ADJP O
. . O O
Trachea NNP B-NP O
is VBZ B-VP O
midline NN B-NP O
, , O O
no DT B-NP O
goiter NN I-NP O
or CC I-NP O
adenopathy NN I-NP O
. . O O
Back RP O O
: : O O
Normal JJ B-NP O
configuration NN I-NP O
. . O O
Chest NNP B-NP O
: : O O
Normal JJ B-NP O
percussion NN I-NP O
note NN I-NP O
, , O O
good JJ B-NP O
air NN I-NP O
movement NN I-NP O
bilaterally RB B-ADVP O
; : O O
fine JJ B-NP O
expiratory NN I-NP O
crackles NNS I-NP O
at IN B-PP O
the DT B-NP O
lateral JJ I-NP O
bases NNS I-NP O
. . O O
Cardiac NNP B-NP O
: : O O
Faint NNP B-NP O
left VBD B-VP O
parasternal JJ B-NP O
impulse NN I-NP O
, , O O
mildly RB B-NP O
prominent JJ I-NP O
P2 NN I-NP O
, , O O
normal JJ B-NP O
S1 NNP I-NP O
, , O O
S2 NNP B-NP O
, , O O
without IN B-PP O
murmur NN B-NP O
, , O O
rub NN B-NP O
, , O O
or CC O O
gallop NN B-NP O
. . O O
JVP '' O O
is VBZ B-VP O
7 CD B-NP O
cm NN I-NP O
with IN B-PP O
borderline NN B-NP O
HJR. NNP I-NP O
Abdomen NNP I-NP O
: : O O
Soft NNP B-NP O
, , I-NP O
nontender NN I-NP O
, , O O
no DT B-NP O
hepatosplenomegaly NN I-NP O
or CC I-NP O
mass NN I-NP O
. . O O
Extremities NNS B-NP O
: : O O
No DT B-NP O
cyanosis NN I-NP O
or CC I-NP O
edema NN I-NP O
, , I-NP O
borderline NN I-NP O
clubbing NN I-NP O
. . O O
Pulmonary JJ B-NP O
function NN I-NP O
tests NNS I-NP O
today NN I-NP O
show VBP B-VP O
very RB B-NP O
stable JJ I-NP O
values NNS I-NP O
per IN B-PP O
spirometry NN B-NP O
, , O O
a DT B-NP O
slight JJ I-NP O
down IN I-NP O
- : O O
. . B-VP O
. . O O
in IN B-PP O
total JJ B-NP O
lung NN I-NP O
capacity NN I-NP O
, , O O
but CC O O
still RB B-ADVP O
approximately RB B-NP O
70 CD I-NP O
% NN I-NP O
predicted VBN B-VP O
, , O O
and CC O O
DLCO NNP B-NP O
stable NN I-NP O
in IN B-PP O
the DT B-NP O
60 CD I-NP O
% NN I-NP O
predicted VBD I-NP O
range NN I-NP O
. . O O
My PRP$ B-NP O
review NN I-NP O
of IN B-PP O
CT NNP B-NP O
scan NN I-NP O
of IN B-PP O
the DT B-NP O
chest NN I-NP O
shows VBZ B-VP O
faint JJ B-NP O
peripheral JJ I-NP O
subpleural JJ I-NP O
reticular JJ I-NP O
pattern NN I-NP O
with IN B-PP O
cyst NN B-NP O
formation NN I-NP O
and CC O O
no DT B-NP O
significant JJ I-NP O
nodules NNS I-NP O
. . O O
Impression NN B-NP O
: : O O
1 LS O O
. . B-NP O
Interstitial NNP I-NP O
lung NN I-NP O
disease NN I-NP O
- : O O
Mild JJ B-NP O
objective NN I-NP O
impairment NN I-NP O
by IN B-PP O
functional JJ B-NP O
status NN I-NP O
. . B-VP O
Pulmonary VB I-VP O
function NN B-NP O
tests NNS I-NP O
- : O O
Overall RB B-ADVP O
, , O O
these DT B-NP O
were VBD B-VP O
stable JJ B-ADJP O
, , O O
and CC O O
the DT B-NP O
CT NNP I-NP O
scan NN I-NP O
is VBZ B-VP O
quite RB B-ADJP O
suggestive JJ I-ADJP O
of IN B-PP O
pulmonary JJ B-NP O
fibrosis NN I-NP O
. . O O
However RB B-ADVP O
, , O O
as IN B-SBAR O
I PRP B-NP O
reviewed VBN B-VP O
with IN B-PP O
the DT B-NP O
patient NN I-NP O
and CC O O
his PRP$ B-NP O
wife NN I-NP O
, , O O
it PRP B-NP O
is VBZ B-VP O
well RB I-VP O
established VBN I-VP O
that IN B-PP O
10 CD B-NP O
% NN I-NP O
of IN B-PP O
the DT B-NP O
time NN I-NP O
, , O O
another DT B-NP O
disorder NN I-NP O
, , O O
such JJ B-PP O
as IN I-PP O
occult JJ B-NP O
hypersensitivity NN I-NP O
pneumonitis NN I-NP O
or CC O O
nonspecific JJ B-NP O
interstitial JJ I-NP O
pneumonitis NN I-NP O
can MD B-VP O
be VB I-VP O
found VBN I-VP O
on IN B-PP O
lung NN B-NP O
biopsy NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
a DT B-NP O
rheumatologic NN I-NP O
disorder NN I-NP O
nor CC O O
any DT B-NP O
evidence NN I-NP O
of IN B-PP O
chronic JJ B-NP O
aspiration NN I-NP O
, , O O
other JJ B-ADJP O
than IN B-PP O
that IN B-NP O
associated VBN B-VP O
with IN B-PP O
GE NNP B-NP O
reflux NNP I-NP O
, , O O
to TO B-VP O
explain VB I-VP O
his PRP$ B-NP O
lung NN I-NP O
disease NN I-NP O
. . O O
He PRP B-NP O
would MD B-VP O
be VB I-VP O
a DT B-NP O
very RB I-NP O
reasonable JJ I-NP O
candidate NN I-NP O
for IN B-PP O
gamma NN B-NP O
interferon NN I-NP O
, , O O
although IN B-SBAR O
this DT B-NP O
likely JJ I-NP O
would MD B-VP O
necessitate VB I-VP O
low-dose JJ B-NP O
steroids NNS I-NP O
- : O O
the DT B-NP O
latter JJ I-NP O
treatment NN I-NP O
would MD B-VP O
certainly RB I-VP O
have VB I-VP O
an DT B-NP O
impact NN I-NP O
on IN B-PP O
his PRP$ B-NP O
diabetes NN I-NP O
. . O O
2. . B-NP O
GE NNP I-NP O
reflux NNP I-NP O
- : O O
This DT B-NP O
is VBZ B-VP O
the DT B-NP O
main JJ I-NP O
source NN I-NP O
of IN B-PP O
his PRP$ B-NP O
cough NN I-NP O
and CC O O
is VBZ B-VP O
well RB I-VP O
established VBN I-VP O
to TO I-VP O
be VB I-VP O
associated VBN I-VP O
with IN B-PP O
pulmonary JJ B-NP O
fibrosis NN I-NP O
. . O O
If IN B-SBAR O
he PRP B-NP O
is VBZ B-VP O
able JJ B-ADJP O
to TO B-VP O
lose VB I-VP O
weight NN B-NP O
and CC O O
change VB B-VP O
his PRP$ B-NP O
lifestyle NN I-NP O
, , O O
he PRP B-NP O
can MD B-VP O
have VB I-VP O
very RB B-NP O
good JJ I-NP O
control NN I-NP O
of IN B-PP O
this DT B-NP O
. . O O
3. VBG B-VP O
Possible JJ B-NP O
mild JJ I-NP O
pulmonary JJ I-NP O
hypertension NN I-NP O
related VBN B-VP O
to TO B-PP O
the DT B-NP O
pulmonary JJ I-NP O
fibrosis NN I-NP O
. . O O
4 CD B-LST O
. . O O
Possible JJ B-NP O
sleep NN I-NP O
disorder NN I-NP O
- : O O
Currently RB B-ADVP O
is VBZ B-VP O
entirely RB B-ADVP O
without IN B-PP O
symptoms NNS B-NP O
, , O O
now RB B-ADVP O
that IN B-PP O
his PRP$ B-NP O
reflux NN I-NP O
is VBZ B-VP O
well RB I-VP O
controlled VBN I-VP O
. . O O
5 CD B-NP O
. . O O
Chronic NNP B-NP O
cough NN I-NP O
. . O O
6 CD B-NP O
. . O O
Diabetes NNP O O
- : O O
Better RBR B-NP O
controlled VBN B-VP O
. . O O
7. CD B-NP O
Obesity NN I-NP O
- : O O
He PRP B-NP O
continues VBZ B-VP O
to TO I-VP O
need VB I-VP O
aggressive JJ B-NP O
weight NN I-NP O
loss NN I-NP O
program NN I-NP O
. . O O
As IN B-SBAR O
I PRP B-NP O
mentioned VBD B-VP O
to TO B-PP O
him PRP B-NP O
, , O O
he PRP B-NP O
would MD B-VP O
not RB I-VP O
be VB I-VP O
a DT B-NP O
candidate NN I-NP O
for IN B-PP O
lung NN B-NP O
transplantation NN I-NP O
evaluation NN I-NP O
while IN B-SBAR O
he PRP B-NP O
is VBZ B-VP O
at IN B-PP O
such JJ B-NP O
as IN I-NP O
weight NN I-NP O
, , O O
but CC O O
he PRP B-NP O
is VBZ B-VP O
starting VBG I-VP O
to TO I-VP O
make VB I-VP O
some DT B-NP O
progress NN I-NP O
. . O O
Recommendations NNS B-NP O
: : O O
1 CD B-NP O
. . O O
Continue NNP O O
proton NN B-NP O
pump NN I-NP O
inhibitor VBZ B-VP O
at IN B-PP O
b.i.d NN B-NP O
. . B-NP O
dosing NN I-NP O
, , O O
as RB B-CONJP O
well RB I-CONJP O
as IN I-CONJP O
lifestyle NN B-NP O
modifications NNS I-NP O
, , O O
including VBG B-PP O
marked VBN B-NP O
decrease NN I-NP O
in IN B-PP O
caffeine NN B-NP O
intake NN I-NP O
. . O O
2. DT B-NP O
Referral NNP I-NP O
to TO B-PP O
Dr. NNP B-NP O
Harry NNP I-NP B-DOCTOR
Yerger NNP I-NP I-DOCTOR
for IN B-PP O
VATS NNP B-NP O
lung NN I-NP O
biopsy NN I-NP O
. . O O
3. POS B-NP O
Cardiovascular NNP I-NP O
evaluation NN I-NP O
by IN B-PP O
you PRP B-NP O
, , O O
prior RB B-ADVP O
to TO B-PP O
his PRP$ B-NP O
surgery NN I-NP O
, , O O
would MD B-VP O
be VB I-VP O
appreciated VBN I-VP O
. . O O
It PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
a DT B-NP O
pleasure NN I-NP O
to TO B-VP O
participate VB I-VP O
in IN B-PP O
his PRP$ B-NP O
care NN I-NP O
. . B-VP O
Please VB I-VP O
feel VB I-VP O
free JJ B-ADJP O
to TO B-VP O
call VB I-VP O
with IN B-PP O
any DT B-NP O
questions NNS I-NP O
or CC I-NP O
comments NNS I-NP O
. . O O
Sincerely RB B-ADVP O
, , O O
Paul NNP B-NP B-DOCTOR
N. NNP I-NP I-DOCTOR
Tam NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
PNT NNP B-NP B-DOCTOR
/ NNP I-NP O
ivester NN I-NP B-DOCTOR
/ NN I-NP O
yanez . O B-DOCTOR
