Record NNP B-NP O
date NN I-NP O
: : O O
2081-10-18 CD O B-DATE
CCU NNP B-NP O
JAR NNP I-NP O
ADMIT NNP I-NP O
NOTE NNP I-NP O
Patient NNP B-NP O
Name NN I-NP O
: : O O
Jonathan NNP B-NP B-PATIENT
Oswald NNP I-NP I-PATIENT
MRN NNP B-NP O
: : O O
4989555 CD O B-MEDICALRECORD
Date NNP B-NP O
of IN B-PP O
Admission NNP B-NP O
: : O O
10/18/8 CD B-NP I-DATE
1 CD I-NP I-DATE
Cardiology NNP B-NP O
: : O O
Xiang NNP O B-DOCTOR
CCU NNP B-NP O
Attending VBG I-NP O
: : O O
Dennis NNP B-NP B-DOCTOR
Donnelly NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
HISTORY NN B-NP O
OF IN B-PP O
PRESENT JJ B-NP O
ILLNESS NNS I-NP O
: : O O
This DT B-NP O
is VBZ B-VP O
a DT B-NP O
55 CD I-NP B-AGE
yr JJ I-NP O
old JJ I-NP O
male NN I-NP O
with IN B-PP O
cardiac JJ B-NP O
risk NN I-NP O
factors NNS I-NP O
of IN B-PP O
Hypertension NNP B-NP O
, , O O
Type NNP B-NP O
II NNP I-NP O
DM NNP I-NP O
, , O O
+FH NNP B-NP O
, , O O
low JJ B-NP O
HDL NNP I-NP O
, , O O
and CC O O
obesity NN B-NP O
who WP B-NP O
was VBD B-VP O
in IN B-PP O
his PRP$ B-NP O
USOH NNP I-NP O
until IN B-PP O
yesterday NN B-NP O
morning NN I-NP O
when WRB B-ADVP O
he PRP B-NP O
developed VBD B-VP O
3/10 CD B-NP O
pain NN I-NP O
across IN B-PP O
his PRP$ B-NP O
anterior JJ I-NP O
chest NN I-NP O
while IN B-ADVP O
at IN B-PP O
rest NN B-NP O
that IN B-SBAR O
he PRP B-NP O
describes VBZ B-VP O
as IN B-PP O
burning VBG B-VP O
in IN B-PP O
quality NN B-NP O
with IN B-PP O
radiation NN B-NP O
into IN B-PP O
both DT B-NP O
jaws NNS I-NP O
and CC O O
through IN B-PP O
to TO B-PP O
his PRP$ B-NP O
back NN I-NP O
. . O O
The DT B-NP O
pain NN I-NP O
subsided VBD B-VP O
without IN B-PP O
intervention NN B-NP O
after IN B-PP O
about IN B-NP O
30 CD I-NP O
minutes NNS I-NP O
. . O O
He PRP B-NP O
remained VBD B-VP O
pain NN B-NP O
free JJ I-NP O
until IN B-PP O
this DT B-NP O
morning NN I-NP O
when WRB B-ADVP O
around IN B-NP O
6:45 CD I-NP O
am VBP I-NP O
, , O O
he PRP B-NP O
again RB B-ADVP O
experienced VBD B-VP O
this DT B-NP O
burning NN I-NP O
sensation NN I-NP O
in IN B-PP O
the DT B-NP O
same JJ I-NP O
distribution NN I-NP O
. . O O
He PRP B-NP O
also RB B-ADVP O
felt VBD B-VP O
nauseated JJ B-ADJP O
and CC I-ADJP O
diaphoretic JJ I-ADJP O
. . O O
On IN B-PP O
the DT B-NP O
way NN I-NP O
to TO B-PP O
the DT B-NP O
hospital NN I-NP O
, , O O
the DT B-NP O
pain NN I-NP O
subsided VBD B-VP O
. . O O
He PRP B-NP O
was VBD B-VP O
pain NN B-NP O
free JJ B-ADJP O
upon IN B-PP O
presentation NN B-NP O
to TO B-PP O
the DT B-NP O
ER NNP I-NP O
, , O O
but CC O O
developed VBD B-VP O
chest NN B-NP O
pain NN I-NP O
briefly NN I-NP O
while IN B-ADVP O
in IN B-PP O
triage NN B-NP O
that WDT B-NP O
had VBD B-VP O
again RB I-VP O
disappeared VBN I-VP O
by IN B-PP O
the DT B-NP O
time NN I-NP O
he PRP B-NP O
was VBD B-VP O
evaluated VBN I-VP O
in IN B-PP O
Trauma NNP B-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
SOB NNP I-NP O
, , I-NP O
fever NN I-NP O
, , I-NP O
chills NNS I-NP O
, , I-NP O
or CC I-NP O
cough NN I-NP O
. . O O
There EX B-NP O
was VBD B-VP O
no DT B-NP O
positional JJ I-NP O
component NN I-NP O
to TO B-PP O
his PRP$ B-NP O
pain NN I-NP O
nor CC O O
could MD O O
he PRP B-NP O
identify VB B-VP O
any DT B-NP O
relieving NN I-NP O
or CC I-NP O
exacerbating NN I-NP O
factors NNS I-NP O
. . O O
HOSPITAL NNP B-NP O
COURSE NNP I-NP O
: : O O
On IN B-SBAR O
presentation NN B-NP O
to TO B-PP O
the DT B-NP O
ER NNP I-NP O
, , O O
the DT B-NP O
patient NN I-NP O
's POS B-NP O
BP NNP I-NP O
was VBD B-VP O
155/8 CD B-NP O
3 CD I-NP O
HR NN I-NP O
77 CD B-NP O
RR NNP I-NP O
20 CD I-NP O
T96.2 CD I-NP O
O2 NNS I-NP O
sat VBD B-VP O
90 CD B-NP O
% NN I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
ASA NNP B-NP O
325mg CD I-NP O
po NN I-NP O
x NN I-NP O
1 CD I-NP O
, , O O
lopressor NN B-NP O
5mg CD I-NP O
IV NNP I-NP O
x NN I-NP O
3 CD B-NP O
doses NNS I-NP O
, , O O
IV NNP B-NP O
TNG NNP I-NP O
, , O O
a DT B-NP O
heparin NN I-NP O
bolus NN I-NP O
of IN B-PP O
5000 CD B-NP O
and CC O O
started VBD B-VP O
on IN B-PP O
a DT B-NP O
drip NN I-NP O
at IN B-PP O
1500 CD B-NP O
u/hr NN I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
taken VBN I-VP O
to TO B-PP O
the DT B-NP O
cath NN I-NP O
lab NN I-NP O
. . O O
CATH NNP B-NP O
DATA NNP I-NP O
: : O O
RCA NN B-NP O
: : O O
clean JJ O O
PDA NNP B-NP O
with IN B-PP O
60 CD B-NP O
% NN I-NP O
distal JJ I-NP O
occlusion NN I-NP O
LM NNP B-NP O
: : O O
clean JJ O O
LAD NN B-NP O
: : O O
95 CD B-NP O
% NN I-NP O
stenosis NN I-NP O
after IN B-PP O
"huge JJ B-NP O
" `` I-NP O
diagonal JJ I-NP O
branch NN I-NP O
Left VBN B-NP O
CX NNP I-NP O
: : O O
clean JJ B-ADJP O
with IN B-PP O
large JJ B-NP O
OMB NNS I-NP O
Ramus NNP B-NP O
: : O O
clean JJ O O
LVEDP NNP B-NP O
15 CD I-NP O
PTCA NNP B-NP O
of IN B-PP O
LAD NNP B-NP O
and CC O O
stent JJ B-NP O
placed VBN B-VP O
with IN B-PP O
"excellent JJ B-NP O
" `` I-NP O
results NNS I-NP O
. . O O
PMH: . O O
1 CD B-NP O
. . O O
Type NNP B-NP O
II NNP I-NP O
DM-last JJ I-NP O
HGA1C IN I-NP O
7.4 CD I-NP O
in IN B-PP O
10/8 CD B-NP I-DATE
1 CD I-NP I-DATE
2. . B-NP O
Nephrotic NNP I-NP O
Range NNP I-NP O
Proteinuria NNP I-NP O
( -LRB- I-NP O
in IN B-PP O
setting NN B-NP O
of IN B-PP O
naprosyn NN B-NP O
) -RRB- O O
3. . B-NP O
Obesity NN I-NP O
4 CD B-NP O
. . O O
Hypertension NNP O O
5 CD B-LST O
. . O O
Hereditary IN B-PP O
spherocytosis NN B-NP O
: : O O
s/p NN B-NP O
splenectomy NN I-NP O
at IN B-PP O
age NN B-NP O
18 CD I-NP B-AGE
( -LRB- O O
pneumovax NN B-NP O
12/2080 CD I-NP B-DATE
) -RRB- O O
6 CD B-NP O
. . O O
OSA NNP B-NP O
; : O O
has VBZ B-VP O
been VBN I-VP O
prescribed VBN I-VP O
CPAP NNS B-NP O
but CC O O
not RB B-VP O
currently RB I-VP O
using VBG I-VP O
7. CD B-NP O
DJD NNP I-NP O
; : O O
bilateral JJ B-NP O
knees NNS I-NP O
8. . O O
Gout CC O O
9 CD B-NP O
. . O O
H/O NNP B-NP O
nephrolithiasis NN I-NP O
10 CD B-NP O
. . O O
S/P NNP B-NP O
Pneumonia NNP I-NP O
: : O O
12/2078 CD B-NP B-DATE
. . O O
11 CD B-NP O
. . O O
Venous NNP B-NP O
stasis NN I-NP O
; : O O
R>L NNP B-NP O
secondary JJ I-NP O
to TO B-PP O
old JJ B-NP O
injury NN I-NP O
; : O O
ALLERGIES NNS B-NP O
: : O O
Keflex-hives . O O
HOME NNP B-NP O
MEDICATIONS NNP I-NP O
: : O O
NIFEDIPINE NNP B-NP O
SR NNP I-NP O
30MG NNP I-NP O
, , O O
1 CD B-NP O
TabletPO NN I-NP O
QD . O O
ENALAPRIL NNP B-NP O
20MG CD I-NP O
, , I-NP O
2 CD I-NP O
Tablets NNP I-NP O
PO NNP I-NP O
QD . O O
FUROSEMIDE NNP B-NP O
40MG NNP I-NP O
, , O O
1 CD B-NP O
Tablets NNP I-NP O
PO NNP I-NP O
BID NNP I-NP O
DOXAZOSIN VB B-VP O
8MG JJ B-ADJP O
, , O O
1 CD B-NP O
Tablet NN I-NP O
QD . O O
ALLOPURINOL NNP B-NP O
300MG NNP I-NP O
1 CD I-NP O
Tablet NN I-NP O
QD . O O
SOCIAL JJ B-NP O
HISTORY NN I-NP O
: : O O
Lives NNS B-NP O
with IN B-PP O
his PRP$ B-NP O
wife NN I-NP O
in IN B-PP O
Tornillo NNP B-NP B-CITY
. . O O
Does VBZ B-VP O
not RB I-VP O
currently RB I-VP O
smoke NN I-VP O
; : O O
social JJ B-NP O
ETOH NNP I-NP O
use NN I-NP O
. . B-VP O
Admits NNS B-NP O
to TO B-PP O
past JJ B-NP O
history NN I-NP O
of IN B-PP O
recreational/illicit NN B-NP O
drug NN I-NP O
use NN I-NP O
. . O O
Admits NNS B-NP O
to TO B-PP O
past JJ B-NP O
cocaine NN I-NP O
use NN I-NP O
and CC O O
remote JJ B-NP O
barbiturate NN I-NP O
, , O O
and CC O O
"psychedelic JJ B-NP O
use NN I-NP O
" '' O O
. . B-NP O
Last JJ I-NP O
use NN I-NP O
of IN B-PP O
cocaine NN B-NP O
was VBD B-VP O
1-2 JJ B-NP O
yrs NNS I-NP O
ago RB B-ADVP O
; : O O
denies VBZ B-VP O
recent JJ B-NP O
use NN I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
past IN B-PP O
marijuania NN B-NP O
use NN I-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
retired VBN I-VP O
and CC O O
previously RB B-VP O
ran VBD I-VP O
an DT B-NP O
Italian JJ I-NP B-ORGANIZATION
restaurant NN I-NP I-ORGANIZATION
. . O O
FH NNP B-NP O
: : O O
Father NNP B-NP O
with IN B-PP O
MI NNP B-NP O
at IN B-PP O
age NN B-NP O
48 CD I-NP B-AGE
and CC O O
stroke NN B-NP O
in IN B-PP O
his PRP$ B-NP O
80 CD I-NP I-AGE
's POS B-NP I-AGE
. . I-NP O
Grandfather NNP I-NP O
with IN B-PP O
MI NNP B-NP O
at IN B-PP O
unknown JJ B-NP O
age NN I-NP O
. . O O
ROS NNP B-NP O
: : O O
General NNP B-NP O
: : O O
denies VBZ B-VP O
fever NN B-NP O
, , O O
wt JJ B-NP O
change NN I-NP O
, , O O
or CC O O
night NN B-NP O
sweats NNS I-NP O
HEENT NNP B-NP O
: : O O
no DT B-NP O
headaches NNS I-NP O
, , O O
visual JJ B-NP O
problems NNS I-NP O
or CC O O
dysphagia NN B-NP O
CV NN B-NP O
: : O O
see VB B-VP O
HPI NNS B-NP O
Respiratory NN B-NP O
: : O O
no DT B-NP O
hemoptysis NN I-NP O
or CC I-NP O
sputum NN I-NP O
production NN I-NP O
ABD NNP B-NP O
: : O O
no DT B-NP O
diarrhea NN I-NP O
, , I-NP O
constipation NN I-NP O
or CC I-NP O
melena NN I-NP O
Neuro NNP B-NP O
: : O O
no DT B-NP O
paralysis NN I-NP O
or CC I-NP O
seizures NNS I-NP O
End NN B-NP O
: : O O
no DT B-NP O
p/p/p/hot JJ I-NP O
or CC I-NP O
cold JJ I-NP O
intolerance NN I-NP O
MS NNP B-NP O
: : O O
no DT B-NP O
myalgias NNS I-NP O
or CC I-NP O
arthralgias NNS I-NP O
HEME NN B-NP O
: : O O
no DT B-NP O
epistaxis NN I-NP O
or CC I-NP O
gingival NN I-NP O
bleeding NN I-NP O
. . O O
Physical JJ B-NP O
Exam NNP I-NP O
: : O O
Vital JJ B-NP O
Signs NNS I-NP O
: : O O
BP NNP B-NP O
123/64 CD I-NP O
HR NNP B-NP O
68-79 CD I-NP O
02 CD B-NP O
sat VBD B-VP O
99 CD B-NP O
% NN I-NP O
on IN B-PP O
2L CD B-NP O
Temp NNP B-NP O
95 CD I-NP O
GENERAL NNP B-NP O
: : O O
morbidly RB B-NP O
obese JJ I-NP O
gentleman NN I-NP O
in IN B-PP O
NAD NNP B-NP O
HEENT NNP B-NP O
: : O O
PERRLA NNP B-NP O
; : O O
EOMI NNP B-NP O
; : O O
oropharynx NN B-NP O
moist JJ I-NP O
with IN B-PP O
generous JJ B-NP O
soft JJ I-NP O
tissue NN I-NP O
. . B-VP O
JVP RB B-ADJP O
difficult JJ I-ADJP O
to TO B-VP O
assess VB I-VP O
due JJ B-ADJP O
to TO B-PP O
body NN B-NP O
habitus NN I-NP O
. . O O
Carotid '' O O
upstrokes VBZ B-VP O
2+ RP B-PRT O
without IN B-NP O
bruit NN I-NP O
. . O O
Chest NNP B-NP O
: : O O
CTAB NNP B-NP O
but CC O O
distant JJ B-NP O
Heart NNP B-NP O
: : O O
distant JJ B-NP O
S1S2 NN I-NP O
Abdomen NNP B-NP O
: : O O
obese JJ B-NP O
+BS NNP I-NP O
nt/nd NN I-NP O
; : O O
well-healed JJ B-NP O
left JJ I-NP O
sided JJ I-NP O
scar NN I-NP O
from IN B-PP O
splenectomy NN B-NP O
Extremities NNS B-NP O
: : O O
2+ CD B-NP O
DP NNP I-NP O
, , I-NP O
brachial JJ I-NP O
, , I-NP O
and CC I-NP O
radial JJ I-NP O
pulses NNS I-NP O
. . O O
chronic NN B-VP O
venous JJ B-NP O
stasis NN I-NP O
changes NNS I-NP O
with IN B-PP O
1+ JJ B-NP O
edema NN I-NP O
to TO B-PP O
the DT B-NP O
knees NNS I-NP O
. . O O
Hematoma NNP O O
in IN B-PP O
the DT B-NP O
left JJ I-NP O
antecubital NN I-NP O
fossa NN I-NP O
from IN B-PP O
sheath NN B-NP O
removal NN I-NP O
. . O O
Sensation NN B-VP O
intact JJ B-ADJP O
in IN B-PP O
forearm NN B-NP O
and CC I-NP O
hand NN I-NP O
. . O O
Neurological JJ B-NP O
: : O O
CN NNP B-NP O
II-XII NNP I-NP O
. . I-NP O
MS NNP I-NP O
5/5 CD I-NP O
in IN B-PP O
bilateral JJ B-NP O
upper JJ I-NP O
and CC I-NP O
lower JJR I-NP O
extremities NNS I-NP O
. . O O
Babinski NNP B-NP O
downgoing VBG B-VP O
bilaterally RB O O
DATABASE NNP B-NP O
: : O O
Sodium NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
137 CD O O
Ptassium NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
3.6 CD O O
Chloride NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
105 CD O O
CO2 NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
28.5 CD O O
BUN NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NN I-NP O
) -RRB- I-NP O
25 CD O O
Creatinine NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NN I-NP O
) -RRB- O O
1.2 CD O O
Glucose FW B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
212 CD O O
Calcium NNP B-NP O
9.6 CD I-NP O
Phosphorus NNP B-NP O
2.6 CD I-NP O
Magnesium NNP B-NP O
1.9 CD I-NP O
Total JJ B-NP O
Protein NNP I-NP O
7.7 CD O O
Albumin NNP B-NP O
3.6 CD I-NP O
Globulin NNP B-NP O
4.1 CD I-NP O
Direct JJ B-NP O
Bilirubin NNP I-NP O
0.2 CD O O
Total JJ B-NP O
Bilirubin NNP I-NP O
0.7 CD O O
Transaminase-SGPT NNP B-NP O
27 CD I-NP O
Amylase NNP B-NP O
294 CD I-NP O
Lipase NNP B-NP O
3.1 CD I-NP O
Transaminase-SGOT NNP B-NP O
22 CD I-NP O
WBC NNP B-NP O
9.7 CD I-NP O
HCT NNP B-NP O
46 CD I-NP O
. . O O
PLT NNP B-NP O
471 CD I-NP O
MCV NNP B-NP O
86 CD I-NP O
RDW NNP B-NP O
14.0 CD I-NP O
Superstat NNP B-NP O
PT NNP I-NP O
13.0 CD I-NP O
11.1-13.1 CD I-NP O
sec NN I-NP O
Superstat NNP B-NP O
PT-INR NNP I-NP O
1.2 CD O O
Superstat NNP B-NP O
APTT NNP I-NP O
28.0 CD I-NP O
22.1-35.1 CD I-NP O
sec NN I-NP O
Lipids NNS B-NP O
: : O O
07-Feb-2081 . O B-DATE
Triglycerides NNS B-NP O
78 CD B-NP O
Cholesterol NNP B-NP O
131 CD I-NP O
High NNP B-NP O
Density NNP I-NP O
Lipoprotei NNP I-NP O
28 CD O O
Low NNP B-NP O
Density NNP I-NP O
Lipoprotein NNP I-NP O
87 CD O O
Cardiac NNP B-NP O
Risk NNP I-NP O
Ratio NNP I-NP O
4.7 CD O O
Cardiac NNP B-NP O
Enzymes NNP I-NP O
: : O O
# # B-NP O
1 CD I-NP O
# # I-NP O
2 CD I-NP O
# # O O
3 CD O O
CPK NNP B-NP O
60 CD I-NP O
72 CD O O
CK-MB NNP B-NP O
neg NN I-NP O
2.7 CD O O
Troponin-T NNP B-NP O
neg NN I-NP O
<0.01 CD O O
BNMC NNP B-NP B-HOSPITAL
CARDIAC NNP I-NP O
ULTRASOUND NNP I-NP O
2080 CD O B-DATE
MITRAL NNP B-NP O
VALVE CD I-NP O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
mitral JJ B-NP O
stenosis NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
mitral NN B-NP O
valve NN B-NP O
prolapse NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
mitral JJ B-NP O
regurgitation NN I-NP O
by IN B-PP O
color NN B-NP O
or CC O O
spectral JJ B-NP O
Doppler NNP I-NP O
. . O O
LEFT NNP B-NP O
ATRIUM NNP I-NP O
The DT B-NP O
left JJ I-NP O
atrium NN I-NP O
is VBZ B-VP O
dilated VBN I-VP O
. . O O
AORTIC NNP B-NP O
VALVE NNP I-NP O
, , O O
AORTA NNP B-NP O
, , O O
LVOT NNP B-NP O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
valvular JJ B-NP O
aortic JJ I-NP O
stenosis NN I-NP O
. . O O
The DT B-NP O
aortic JJ I-NP O
valve NN I-NP O
is VBZ B-SBAR O
tricuspid JJ B-ADJP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
aortic JJ B-NP O
insufficiency NN I-NP O
by IN B-PP O
color NN B-NP O
or CC I-NP O
spectral NN I-NP O
Doppler NNP B-NP O
. . O O
The DT B-NP O
aortic JJ I-NP O
root NN I-NP O
appears VBZ B-VP O
dilated VBN I-VP O
. . O O
The DT B-NP O
aortic JJ I-NP O
diameter NN I-NP O
at IN B-PP O
the DT O O
sinotubular JJ B-NP O
junction NN I-NP O
is VBZ B-VP O
39 CD B-NP O
mm UH I-NP O
. . O O
LEFT NNP B-NP O
VENTRICLE NNP I-NP O
The DT B-NP O
left JJ I-NP O
ventricular NN I-NP O
size NN I-NP O
and CC O O
systolic JJ B-NP O
function NN I-NP O
are VBP B-VP O
within IN B-PP O
normal JJ B-NP O
limits NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
symmetric JJ B-NP O
left JJ I-NP O
ventricular JJ I-NP O
hypertrophy NN I-NP O
. . O O
There EX B-NP O
are VBP B-VP O
no DT B-NP O
obvious JJ I-NP O
segmental JJ B-NP O
wall NN I-NP O
motion NN I-NP O
abnormalities NNS I-NP O
. . O O
The DT B-NP O
estimated VBN I-NP O
ejection NN I-NP O
fraction NN I-NP O
is VBZ B-VP O
69 CD B-NP O
% NN I-NP O
. . O O
TRICUSPID NNP B-NP O
VALVE NNP I-NP O
- : O O
IVC NNP B-NP O
, , O O
SVC NNP B-NP O
The DT B-NP O
tricuspid JJ I-NP O
valve NN I-NP O
appears VBZ B-VP O
normal JJ B-ADJP O
. . O O
PULMONARY NNP B-NP O
VALVE NNP I-NP O
, , O O
INFUND. NNP B-NP O
, , O O
P.A. . O O
The DT B-NP O
pulmonary JJ I-NP O
valve NN I-NP O
appears VBZ B-VP O
normal JJ B-ADJP O
. . O O
RIGHT NNP B-NP O
VENTRICLE NNP I-NP O
The DT B-NP O
right JJ I-NP O
ventricle NN I-NP O
is VBZ B-VP O
not RB I-VP O
dilated VBN I-VP O
. . O O
The DT B-NP O
right NN I-NP O
ventricular VBD B-VP O
systolic JJ B-NP O
function NN I-NP O
is VBZ B-NP O
within IN B-PP O
normal JJ B-NP O
limits NNS I-NP O
. . O O
EKG NNP B-NP O
: : O O
EW NNP B-NP O
: : O O
NSR NNP B-NP O
78 CD I-NP O
with IN B-PP O
first JJ B-NP O
degree NN I-NP O
AV IN B-PP O
block NN B-NP O
. . O O
PR NNP B-NP O
0.22 CD I-NP O
. . O O
Q NNP B-NP O
waves NNS I-NP O
V1-V4 CD B-NP O
. . O O
STE NNP O O
in IN B-PP O
V1-V6 NNP B-NP O
. . B-NP O
ST JJS I-NP O
segment NN I-NP O
scooping NN I-NP O
in IN B-PP O
I PRP B-NP O
and CC O O
L. NNP B-NP O
1mm NNP I-NP O
STE NNP I-NP O
in IN B-PP O
II NNP B-NP O
, , O O
III NNP B-NP O
, , O O
F. NNP B-NP O
AVR NNP I-NP O
with IN B-PP O
1mm CD B-NP O
STD. . O O
CCU NNP B-NP O
ADMIT NNP I-NP O
: : O O
NSR NNP B-NP O
61 CD I-NP O
with IN B-PP O
first JJ B-NP O
degree NN I-NP O
AV IN B-PP O
block NN B-NP O
. . O O
PR NNP B-NP O
interval NN I-NP O
0.22 CD B-NP O
. . O O
Q NNP B-NP O
waves NNS I-NP O
V1-V2 CD B-NP O
. . O O
STE NNP B-NP O
V1-V5 NNP I-NP O
. . I-NP O
TW NNP I-NP O
flattening VBG I-NP O
CXR NN B-NP O
: : O O
IMPRESSION NN B-NP O
: : O O
Clear JJ B-NP O
lungs NNS I-NP O
. . O O
The DT B-NP O
aorta NN I-NP O
is VBZ B-VP O
tortuous JJ B-ADJP O
. . O O
Detail NNP O O
of IN B-PP O
the DT B-NP O
lung NN I-NP O
is VBZ B-VP O
suboptimally RB B-ADVP O
to TO B-PP O
body NN B-NP O
habitus NN B-NP O
of IN B-PP O
the DT B-NP O
patient NN I-NP O
. . O O
Assesment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
: : O O
This DT B-NP O
is VBZ B-VP O
a DT B-NP O
55 CD I-NP B-AGE
yr JJ I-NP O
old JJ I-NP O
male NN I-NP O
with IN B-PP O
cardiac JJ B-NP O
risk NN I-NP O
factors NNS I-NP O
of IN B-PP O
hypertension NN B-NP O
, , O O
DM NNP B-NP O
, , O O
+FH NNP B-NP O
, , O O
low JJ B-NP O
HDL NNP I-NP O
, , O O
and CC O O
obesity NN B-NP O
who WP B-NP O
presents VBZ B-VP O
with IN B-PP O
anterior JJ B-NP O
STEMI NNP I-NP O
that WDT B-NP O
was VBD B-VP O
successfully RB I-VP O
treated VBN I-VP O
with IN B-PP O
PCI NNP B-NP O
to TO B-PP O
the DT B-NP O
LAD NN I-NP O
Ischemia NNP B-NP O
: : O O
Treatment NNP B-NP O
ASA NNP B-NP O
325mg JJ I-NP O
po NN I-NP O
qd NN I-NP O
Plavix NNP B-NP O
load NN I-NP O
then RB B-VP O
75mg VBG I-VP O
po NN B-NP O
qd . O O
Continue NNP B-NP O
Vasotec NNP I-NP O
20mg CD I-NP O
po NN I-NP O
qd NN I-NP O
Initiate JJ B-NP O
Lopressor NNP I-NP O
at IN B-PP O
12.5mg CD B-NP O
po NN I-NP O
tid JJ I-NP O
and CC I-NP O
titrate JJ I-NP O
as IN B-PP O
bp NN B-NP O
and CC I-NP O
pulse NN I-NP O
tolerates NNS I-NP O
( -LRB- I-NP O
monitor NN I-NP O
PR NN I-NP O
which WDT B-NP O
was VBD B-VP O
0.22 CD B-NP O
on IN B-PP O
admit VBP B-NP O
) -RRB- O O
Lipitor NNP B-NP O
20mg CD I-NP O
po NN I-NP O
qd NN I-NP O
Reopro NNP B-NP O
for IN I-NP O
12 CD I-NP O
hours NNS I-NP O
IV NNP B-NP O
TNG NNP I-NP O
prn NN I-NP O
bp NN I-NP O
control NN I-NP O
until IN B-PP O
oral JJ B-NP O
regimen NN I-NP O
stable NN I-NP O
Evaluation/Risk NN B-NP O
Factor NNP I-NP O
Modification NNP I-NP O
Check VB B-NP O
homocysteine NN I-NP O
level NN I-NP O
Re-check NN B-NP O
Fasting VBG B-VP O
lipid JJ B-NP O
profile NN I-NP O
Will MD B-NP O
need VB B-VP O
extensive JJ B-NP O
risk NN I-NP O
factor NN I-NP O
modication NN I-NP O
including VBG B-VP O
wt JJ B-NP O
loss NN I-NP O
, , O O
diabetes NN B-NP O
control NN I-NP O
, , O O
and CC O O
exercise NN B-NP O
program NN I-NP O
Rhythm NN B-NP O
: : O O
Routine NNP B-NP O
peri-MI JJ I-NP O
monitoring NN I-NP O
Replete JJ B-NP O
K NNP I-NP O
and CC I-NP O
MG NNP I-NP O
prn NN I-NP O
Pump NNP B-NP O
: : O O
Last JJ B-NP O
known VBN I-NP O
EF NNP I-NP O
69 CD I-NP O
% NN I-NP O
with IN B-PP O
no DT B-NP O
current JJ I-NP O
signs NNS I-NP O
of IN B-PP O
failure NN B-NP O
Gently RB B-NP O
hydrate JJ I-NP O
following VBG I-NP O
cath NN O O
Will MD O O
hold VB B-VP O
off RP B-PRT O
on IN B-NP O
lasix NN I-NP O
( -LRB- I-NP O
takes VBZ B-VP O
this DT B-NP O
at IN B-PP O
home NN B-NP O
for IN B-PP O
LE JJ B-NP O
edema NN I-NP O
) -RRB- O O
while IN B-SBAR O
hydrating VBG B-UCP O
BP NNP B-NP O
control NN I-NP O
with IN B-PP O
Vasotec NNP B-NP O
, , O O
Lopressor NNP B-NP O
, , O O
TNG NNP B-NP O
prn NN I-NP O
OSA NNP B-NP O
: : O O
noncompliant JJ B-ADJP O
at IN B-PP O
home NN B-NP O
with IN B-PP O
CPAP NNP B-NP O
due JJ I-NP O
to TO B-PP O
uncomfortable JJ B-NP O
mask NN I-NP O
Will MD B-NP O
ask VB B-VP O
respiratory JJ B-NP O
therapy NN I-NP O
to TO B-VP O
initiate VB I-VP O
in-house JJ B-ADJP O
and CC O O
try VBP B-VP O
to TO I-VP O
find VB I-VP O
comfortable JJ B-NP O
mask NN I-NP O
Continue JJ B-NP O
education NN I-NP O
on IN B-PP O
importance NN B-NP O
of IN B-PP O
compliance NN B-NP O
with IN B-PP O
CPAP NNP B-NP O
DM . O O
Check VB B-VP O
HGA1C CC O O
CZI NN B-NP O
for IN B-PP O
now RB B-NP O
. . O O
Will MD B-VP O
gather VB I-VP O
data NNS B-NP O
for IN B-PP O
1-2 JJ B-NP O
days NNS I-NP O
. . O O
Will MD O O
likely JJ B-NP O
need VB B-VP O
outpatient JJ B-NP O
treatment NN I-NP O
. . O O
Initiate JJ B-NP O
oral JJ I-NP O
med JJ I-NP O
at IN B-PP O
discharge NN B-NP O
Will MD B-VP O
need VB I-VP O
diabetes NNS B-NP O
education NN I-NP O
Prophylaxis NNP B-NP O
: : O O
heparin NN B-NP O
SQ NN I-NP O
Zantac NNP B-NP O
150mg CD I-NP O
po NN I-NP O
bid NN I-NP O
Giselle NNP B-NP B-DOCTOR
Ulysses-Lyon NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Pager NNP B-NP O
16924 CD I-NP B-PHONE
