Record NNP B-NP O
date NN I-NP O
: : O O
2083-07-18 CD O B-DATE
July NNP B-NP B-DATE
18 CD I-NP I-DATE
, , I-NP I-DATE
2083 CD O I-DATE
Vincent NNP B-NP B-DOCTOR
Ventura NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
4971 CD B-NP B-STREET
Edmatteric NNP I-NP I-STREET
Drive NNP I-NP I-STREET
Cheney NNP B-NP B-CITY
, , O O
TX NNP B-NP B-STATE
37523 CD I-NP B-ZIP
RE RB B-ADVP O
: : O O
Peggy NNP B-NP B-PATIENT
Tinsley NNP I-NP I-PATIENT
MR NNP B-NP O
# # I-NP O
236-67-03-3 CD O B-MEDICALRECORD
Dear NNP B-NP O
Dr. NNP I-NP O
Ventura NNP I-NP B-DOCTOR
: : O O
Peggy NNP B-NP B-PATIENT
Tinsley NNP I-NP I-PATIENT
was VBD B-VP O
seen VBN I-VP O
in IN B-PP O
the DT B-NP O
renal JJ I-NP O
clinic NN I-NP O
today NN B-NP O
. . O O
This DT B-NP O
patient NN I-NP O
with IN B-PP O
end NN B-NP O
stage NN I-NP O
renal JJ I-NP O
disease NN I-NP O
secondary JJ B-ADJP O
to TO B-PP O
diabetes NNS B-NP O
was VBD B-VP O
initiated VBN I-VP O
on IN B-PP O
hemodialysis NN B-NP O
2 CD B-NP O
weeks NNS I-NP O
ago RB B-ADVP O
in IN B-PP O
MH NNP B-NP B-HOSPITAL
. . O O
She PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
doing VBG I-VP O
well RB O O
except IN B-PP O
for IN B-PP O
the DT B-NP O
complaint NN I-NP O
of IN B-PP O
fevers NNS B-NP O
and CC I-NP O
rigors NNS I-NP O
intermittently RB B-ADVP O
for IN B-PP O
the DT B-NP O
past JJ I-NP O
week NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
history NN I-NP O
of IN B-PP O
cough NN B-NP O
, , O O
dyspnea NN B-NP O
, , O O
or CC O O
chest NN B-NP O
pain NN B-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
dysuria NN I-NP O
, , O O
urgency NN B-NP O
, , O O
or CC O O
frequency NN B-NP O
. . O O
Her PRP$ B-NP O
blood NN I-NP O
sugars NNS B-NP O
at IN B-PP O
home NN B-NP O
have VBP B-VP O
been VBN I-VP O
between IN B-PP O
120 CD B-NP O
and CC I-NP O
180 CD I-NP O
. . O O
Her PRP$ B-NP O
current JJ I-NP O
medications NNS I-NP O
include VBP B-VP O
Tums NNP B-NP O
5 CD I-NP O
to TO B-PP O
6 CD B-NP O
tabs NNS I-NP O
with IN B-PP O
meals NNS B-NP O
, , O O
Erythropoietin NNP B-NP O
, , I-NP O
Premarin NNP I-NP O
and CC I-NP O
Provera NNP I-NP O
, , O O
Nephrox NNP B-NP O
150 CD I-NP O
mg NN I-NP O
tid NN I-NP O
, , O O
insulin NN B-NP O
NPH RB B-NP O
10 CD I-NP O
units NNS I-NP O
qam NN I-NP O
. . O O
On IN B-PP O
July NNP B-NP B-DATE
17 CD I-NP I-DATE
, , O O
after IN B-PP O
hemodialysis NN B-NP O
, , O O
Ms. NNP B-NP O
Tinsley NNP I-NP B-PATIENT
was VBD B-VP O
given VBN I-VP O
a DT B-NP O
partial JJ I-NP O
dose NN B-NP O
of IN B-PP O
Vancomycin NNP B-NP O
and CC O O
developed VBD B-VP O
pruritus JJ B-ADVP O
. . O O
CBC NNP O O
at IN B-PP O
the DT B-NP O
time NN I-NP O
revealed VBD B-VP O
a DT B-NP O
white JJ I-NP O
count NN I-NP O
of IN B-PP O
6.2 CD B-NP O
with IN B-PP O
a DT B-NP O
hematocrit NN I-NP O
of IN B-PP O
25.2 CD B-NP O
. . O O
Blood NN O O
cultures NNS B-NP O
were VBD B-VP O
sent VBN I-VP O
. . O O
On IN B-PP O
examination NN B-NP O
today NN I-NP O
this DT B-NP O
lady NN I-NP O
appeared VBD B-VP O
well RB B-ADVP O
with IN B-PP O
a DT B-NP O
BP NNP I-NP O
of IN B-PP O
110/60 CD B-NP O
and CC O O
a DT B-NP O
pulse NN I-NP O
of IN B-PP O
88. DT B-NP O
She PRP B-NP O
was VBD B-VP O
afebrile JJ B-ADJP O
. . O O
Head NNP B-NP O
and CC O O
neck NN B-NP O
examination NN I-NP O
was VBD B-VP O
unremarkable JJ B-ADJP O
and CC O O
chest NN B-NP O
was VBD B-VP O
clear JJ B-ADJP O
to TO B-PP O
IPPA. NNP B-NP O
On IN B-SBAR O
cardiovascular NN B-NP O
examination NN B-NP O
JVP NNP I-NP O
was VBD B-VP O
at IN B-PP O
the DT B-NP O
sternal JJ I-NP O
angle NN I-NP O
and CC O O
there EX B-NP O
was VBD B-VP O
no RB O O
peripheral JJ B-NP O
edema NN I-NP O
. . O O
Heart NN B-NP O
sounds NNS I-NP O
were VBD B-VP O
normal JJ B-ADJP O
. . O O
Urinalysis NNP B-NP O
did VBD B-VP O
not RB I-VP O
reveal VB I-VP O
and CC O O
white JJ B-NP O
cells NNS I-NP O
and CC O O
contained VBD B-VP O
3+ CD O O
protein NN B-NP O
and CC I-NP O
2+ JJ I-NP O
glucose NN I-NP O
. . O O
Miss NNP B-NP O
Tinsley NNP I-NP B-PATIENT
should MD B-VP O
be VB I-VP O
followed VBN I-VP O
up RP B-ADVP O
at IN B-PP O
her PRP$ B-NP O
dialysis NN I-NP O
center NN I-NP O
. . O O
There EX B-NP O
does VBZ B-VP O
not RB I-VP O
appear VB I-VP O
to TO I-VP O
be VB I-VP O
any DT B-NP O
evidence NN I-NP O
of IN B-PP O
a DT B-NP O
graft NN I-NP O
infection NN I-NP O
. . O O
She PRP B-NP O
should MD B-VP O
also RB I-VP O
have VB I-VP O
a DT B-NP O
urine NN I-NP O
sent VBN B-VP O
for IN B-PP O
culture NN B-NP O
to TO B-VP O
rule VB I-VP O
out RP B-PRT O
urinary RB O O
tract NN B-NP O
infection NN I-NP O
. . O O
Because IN B-PP O
of IN I-PP O
her PRP$ B-NP O
early JJ I-NP O
satiety NN I-NP O
she PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
eating VBG B-VP O
poorly RB B-ADVP O
and CC O O
we PRP B-NP O
might MD B-VP O
suggest VB I-VP O
that IN B-SBAR O
she PRP B-NP O
be VB B-VP O
started VBN I-VP O
on IN B-PP O
a DT B-NP O
gastroprokinetic JJ B-NP O
agent NN I-NP O
such JJ B-PP O
as IN I-PP O
Cisapride NNP B-NP O
10 CD I-NP O
mg NN I-NP O
qid NN I-NP O
. . O O
Vincent NNP B-NP B-DOCTOR
Ventura NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
-2- . O O
RE RB B-ADVP O
: : O O
Peggy NNP B-NP B-PATIENT
Tinsley NNP I-NP I-PATIENT
MR NNP B-NP O
# # I-NP O
236-67-03-3 CD O B-MEDICALRECORD
Thank VB B-VP O
you PRP B-NP O
for IN B-PP O
allowing VBG B-VP O
us PRP B-NP O
to TO B-VP O
be VB I-VP O
involved VBN I-VP O
in IN B-PP O
the DT B-NP O
care NN I-NP O
of IN B-PP O
this DT O O
patient NN B-NP O
. . O O
Yours PRP B-NP O
sincerely RB B-ADVP O
, , O O
Martin NNP B-NP B-DOCTOR
Y NNP I-NP I-DOCTOR
. . I-NP I-DOCTOR
Pruitt NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Renal NNP B-NP O
Fellow NNP I-NP O
Y PRP B-NP I-DOCTOR
. . B-VP I-DOCTOR
Quinton NNP B-NP I-DOCTOR
Xanders NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Attending VBG B-NP O
Physician NN I-NP O
DD NNP B-NP O
: : O O
07/18/8 CD B-NP I-DATE
3 CD I-NP I-DATE
DT NNP B-NP O
: : O O
07/23/8 CD B-NP I-DATE
3 CD I-NP I-DATE
DV NNP B-NP O
: : O O
07/18/8 CD B-NP I-DATE
3 CD I-NP I-DATE
/ NN B-NP O
bradford NN I-NP B-DOCTOR
cc NN B-NP O
: : O O
Dr. NNP B-NP O
Uriel NNP I-NP B-DOCTOR
Palmer NNP I-NP I-DOCTOR
Dr. NNP B-NP O
Isaac NNP I-NP B-DOCTOR
Upson NNP I-NP I-DOCTOR
, , O O
Cheney NNP B-NP B-CITY
, , O O
TX NNP B-NP B-STATE
37523 CD I-NP B-ZIP
