Record NNP B-NP O
date NN I-NP O
: : O O
2065-02-04 CD O B-DATE
TRIBAL NNP B-NP B-HOSPITAL
INTERNAL NNP I-NP O
MEDICINE NNP I-NP O
ASSOCIATES NNP I-NP O
Hart NNP I-NP I-PATIENT
, , O I-PATIENT
Matthew NNP B-NP I-PATIENT
46103196 CD O B-MEDICALRECORD
2-4-65 CD O B-DATE
HPI NNP B-NP O
: : O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
a DT B-NP O
41 CD I-NP B-AGE
year NN I-NP O
old JJ I-NP O
man NN I-NP O
with IN B-PP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
non-insulin NN B-NP O
dependent JJ B-NP O
diabetes NNS I-NP O
, , O O
hypertension NN B-NP O
, , I-NP O
obesity NN I-NP O
and CC I-NP O
substance NN I-NP O
abuse NN I-NP O
who WP B-NP O
I PRP O O
learned VBN B-NP O
today NN I-NP O
was VBD B-VP O
recently RB I-VP O
admitted VBN I-VP O
for IN B-PP O
deep JJ B-NP O
venous JJ I-NP O
thrombosis NN I-NP O
and CC O O
is VBZ O O
presenting VBG B-VP O
for IN B-PP O
follow VB B-NP O
up IN B-PP O
of IN B-PP O
his PRP$ B-NP O
DVT. NNP I-NP O
The DT B-NP O
patient NN I-NP O
's POS B-NP O
current JJ I-NP O
medical JJ I-NP O
problems NNS B-NP O
include VBP B-VP O
: : O O
1 CD B-LST O
. . O O
Recent JJ B-VP O
DVT. NNP B-NP O
The DT B-NP O
patient NN I-NP O
was VBD B-VP O
admitted VBN I-VP O
between IN B-PP O
the DT B-NP O
days NNS I-NP O
of IN B-PP O
1-24 CD B-NP B-DATE
and CC O O
1-30 CD B-NP B-DATE
secondary JJ I-NP O
to TO B-PP O
the DT B-NP O
development NN I-NP O
of IN B-PP O
a DT B-NP O
right NN I-NP O
lower JJR B-NP O
extremity NN I-NP O
DVT. . O O
The DT B-NP O
patient NN I-NP O
told VBD B-VP O
me PRP B-NP O
that IN B-SBAR O
he PRP B-NP O
had VBD B-VP O
been VBN I-VP O
doing VBG I-VP O
well RB B-ADVP O
and CC O O
denied VBD B-VP O
any DT O O
previous JJ B-NP O
trauma NN I-NP O
to TO B-PP O
his PRP$ B-NP O
leg NN I-NP O
or CC I-NP O
other JJ I-NP O
predisposing NN I-NP O
factors NNS I-NP O
such JJ B-PP O
as IN I-PP O
long JJ O O
car NN B-NP O
or CC I-NP O
airplane NN I-NP O
trips NNS I-NP O
and CC O O
he PRP B-NP O
stated VBD B-VP O
he PRP B-NP O
had VBD B-VP O
been VBN I-VP O
as RB B-ADJP O
active JJ I-ADJP O
as IN B-PP O
previously RB B-ADVP O
over IN B-PP O
the DT B-NP O
recent JJ I-NP O
few JJ I-NP O
weeks NNS I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
stated VBD B-VP O
he PRP B-NP O
awoke VBD B-VP O
in IN B-PP O
the DT B-NP O
morning NN I-NP O
of IN B-PP O
the DT B-NP O
24th JJ I-NP B-DATE
and CC I-NP O
noted JJ I-NP O
tightness NN I-NP O
in IN B-PP O
his PRP$ B-NP O
right NN I-NP O
quadriceps NNS B-NP O
and CC O O
right JJ B-NP O
calf NN I-NP O
. . O O
He PRP B-NP O
later RB B-ADVP O
developed VBD B-VP O
progressive JJ B-NP O
swelling VBG I-NP O
of IN B-PP O
the DT B-NP O
leg NN I-NP O
and CC O O
therefore RB B-VP O
presented VBN I-VP O
to TO B-PP O
the DT B-NP O
THD NNP I-NP B-HOSPITAL
emergency NN I-NP O
department NN B-NP O
. . O O
He PRP B-NP O
had VBD B-VP O
lower JJR B-NP O
extremity NN I-NP O
non-invasives NNS I-NP O
performed VBN B-VP O
which WDT O O
confirmed VBN B-VP O
the DT B-NP O
presence NN I-NP O
of IN B-PP O
a DT B-NP O
right NN I-NP O
lower JJR B-NP O
extremity NN I-NP O
DVT. NNP I-NP O
He PRP B-NP O
was VBD B-VP O
admitted VBN B-VP O
and CC I-VP O
heparinized VBN I-VP O
and CC O O
then RB O O
Coumadinized NNP B-NP O
prior RB B-ADVP O
to TO B-PP O
discharge NN B-NP O
. . O O
The DT B-NP O
patient NN I-NP O
disclosed VBD B-VP O
a DT B-NP O
history NN I-NP O
that IN B-PP O
his PRP$ B-NP O
daughter NN I-NP O
had VBD B-VP O
a DT B-NP O
DVT NN I-NP O
at IN B-PP O
the DT O O
time NN B-NP O
of IN B-PP O
her PRP$ B-NP O
pregnancy NN I-NP O
and CC O O
therefore RB B-ADVP O
a DT B-NP O
hypercoagulability NN I-NP O
work-up NN I-NP O
was VBD B-SBAR O
sent VBN B-VP O
off RP B-NP O
which WDT B-NP O
was VBD B-VP O
negative JJ B-ADJP O
. . O O
The DT O O
patient NN B-NP O
currently RB B-ADVP O
returns VBZ B-VP O
to TO B-PP O
me PRP B-NP O
complaining VBG B-VP O
of IN B-PP O
further RB B-NP O
right JJ I-NP O
calf NN I-NP O
pain NN I-NP O
and CC O O
swelling VBG B-VP O
. . O O
He PRP B-NP O
states VBZ B-VP O
that IN B-SBAR O
he PRP B-NP O
was VBD B-VP O
interested JJ B-ADJP O
in IN B-PP O
physical JJ B-NP O
therapy NN I-NP O
but CC O O
states NNS B-NP O
that IN B-PP O
that DT B-NP O
did VBD B-VP O
not RB O O
occur VB B-VP O
during IN B-PP O
his PRP$ B-NP O
hospital NN I-NP O
course NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
was VBD B-VP O
also RB B-ADVP O
angry JJ B-ADJP O
and CC O O
upset JJ B-ADJP O
that IN B-SBAR O
I PRP B-NP O
had VBD B-VP O
not RB I-VP O
visited VBN I-VP O
him PRP B-NP O
during IN B-PP O
his PRP$ B-NP O
hospital NN I-NP O
stay VB B-VP O
. . O O
I PRP O O
explained VBD B-VP O
to TO B-PP O
him PRP B-NP O
that IN B-SBAR O
I PRP B-NP O
had VBD B-VP O
not RB I-VP O
been VBN I-VP O
notified VBN I-VP O
of IN B-PP O
his PRP$ B-NP O
admission NN I-NP O
or CC O O
of IN B-PP O
his PRP$ B-NP O
emergency NN I-NP O
department NN I-NP O
visit NN I-NP O
. . O O
I PRP B-NP O
called VBD B-VP O
all DT B-NP O
of IN B-PP O
the DT B-NP O
parties NNS I-NP O
responsible JJ B-ADJP O
for IN B-PP O
his PRP$ B-NP O
admission NN I-NP O
to TO B-VP O
clear VB I-VP O
the DT B-NP O
confusion NN I-NP O
that WDT B-NP O
had VBD B-VP O
occurred VBD O O
. . O O
2. DT B-NP O
Hypertension NNP I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
's VBZ B-VP O
previously RB I-VP O
been VBN I-VP O
on IN B-PP O
anti-hypertensives NNS B-NP O
including VBG B-PP O
lisinopril NN B-NP O
, , O O
unfortunately RB B-ADVP O
the DT B-NP O
patient NN I-NP O
has VBZ B-VP O
not RB I-VP O
tolerated VBN I-VP O
ACE NNP B-NP O
inhibitors NNS B-NP O
secondary JJ I-NP O
to TO B-PP O
a DT B-NP O
severe JJ I-NP O
cough NN I-NP O
and CC O O
therefore RB B-NP O
these DT I-NP O
were VBD B-LST O
discontinued VBN B-VP O
recently RB B-ADVP O
. . O O
With IN B-PP O
a DT B-NP O
discontinuation NN I-NP O
of IN B-PP O
his PRP$ B-NP O
drinking NN I-NP O
, , O O
the DT O O
patient NN B-NP O
's POS B-NP O
blood NN I-NP O
pressures NNS I-NP O
have VBP B-VP O
been VBN I-VP O
under IN B-PP O
much JJ B-NP O
better JJR I-NP O
control NN I-NP O
. . O O
3. DT B-NP O
Adult NN I-NP O
onset RB B-ADVP O
diabetes VBZ B-VP O
mellitus JJ B-ADJP O
. . O O
I PRP B-NP O
recently RB B-ADVP O
started VBD B-VP O
the DT B-NP O
patient NN I-NP O
on IN B-PP O
insulin NN B-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
scheduled VBN I-VP O
for IN B-PP O
a DT B-NP O
follow VBP B-VP O
up IN B-PP O
visit NN B-NP O
but CC O O
unfortunately RB O O
did VBD B-VP O
not RB I-VP O
make VB I-VP O
his PRP$ B-NP O
visit NN I-NP O
. . O O
His PRP$ B-NP O
insulin NN I-NP O
dose NN I-NP O
was VBD B-VP O
adjusted VBN I-VP O
during IN B-PP O
his PRP$ B-NP O
recent JJ B-NP O
hospitalization NN I-NP O
and CC O O
his PRP$ B-NP O
current JJ I-NP O
dosage NN I-NP O
is VBZ B-VP O
35 CD B-NP O
units NNS I-NP O
of IN B-PP O
NPH NNP B-NP O
in IN B-PP O
the DT B-NP O
morning NN I-NP O
and CC O O
15 CD B-NP O
units NNS I-NP O
of IN B-PP O
regular JJ B-NP O
. . O O
In IN B-PP O
the DT B-NP O
evening NN I-NP O
he PRP B-NP O
takes VBZ B-VP O
10 CD B-SBAR O
units NNS B-NP O
of IN B-PP O
NPH NNP B-NP O
and CC O O
10 CD B-NP O
units NNS I-NP O
of IN B-PP O
regular JJ B-NP O
. . O O
The DT B-NP O
patient NN I-NP O
does VBZ B-VP O
not RB I-VP O
yet RB I-VP O
have VB I-VP O
a DT B-NP O
home NN I-NP O
glucometer NN I-NP O
. . O O
We PRP B-NP O
will MD B-VP O
arrange VB I-VP O
for IN B-PP O
this DT B-NP O
. . O O
THD IN B-PP B-HOSPITAL
INTERNAL NNP B-NP O
MEDICINE NNP I-NP O
ASSOCIATES NNP I-NP O
Hart NNP I-NP I-PATIENT
, , O I-PATIENT
Matthew NNP B-NP I-PATIENT
Page NNP B-NP O
2 CD I-NP O
46103196 CD O B-MEDICALRECORD
2-4-65 CD O B-DATE
Physical JJ B-NP O
Examination NNP I-NP O
: : O O
Vital JJ B-NP O
signs NNS I-NP O
showed VBD B-VP O
a DT B-NP O
heart NN I-NP O
rate NN I-NP O
of IN B-PP O
90 CD B-NP O
. . O O
Blood NN O O
pressure NN B-NP O
: : O O
135/92 CD B-NP O
. . O O
Respiratory NN B-VP O
rate NN B-NP O
: : O O
14 CD B-NP O
and CC I-NP O
unlabored JJ I-NP O
. . O O
HEENT NNP B-NP O
: : O O
pupils NNS B-NP O
equal JJ B-NP O
, , I-NP O
round JJ I-NP O
and CC I-NP O
reactive JJ I-NP O
to TO B-PP O
light NN B-NP O
, , O O
extraocular JJ B-NP O
movements NNS I-NP O
intact JJ B-ADJP O
, , O O
oropharynx NN B-NP O
clear JJ I-NP O
. . O O
Mucous JJ B-NP O
membranes NNS I-NP O
moist JJ B-VP O
. . B-NP O
Cardiac NNP I-NP O
: : O O
regular JJ B-NP O
rate NN I-NP O
and CC O O
rhythm NN B-NP O
, , O O
normal JJ B-NP O
S1 NNP I-NP O
, , O O
S2 NNP B-NP O
, , O O
no DT B-NP O
murmurs NNS I-NP O
, , O O
rubs NNS B-NP O
, , O O
or CC O O
gallops NNS B-NP O
. . O O
Lungs NNP B-NP O
: : O O
clear JJ B-ADJP O
to TO O O
ausculation NN B-NP O
. . O O
Abdomen IN B-PP O
soft JJ B-NP O
, , I-NP O
nontender JJ I-NP O
with IN B-PP O
active JJ B-NP O
bowel NN I-NP O
sounds NNS I-NP O
. . O O
Extremities NNS B-NP O
: : O O
There EX B-NP O
was VBD B-VP O
notable JJ B-NP O
edema NN I-NP O
of IN B-PP O
his PRP$ B-NP O
right NN I-NP O
lower RBR B-NP O
extremity NN I-NP O
with IN B-LST O
significant JJ B-NP O
pain NN I-NP O
and CC O O
a DT B-NP O
positive JJ I-NP O
Homan NNP I-NP O
's POS B-NP O
sign NN I-NP O
. . O O
Impression NN B-NP O
: : O O
1 CD B-NP O
) -RRB- I-NP O
DVT. NNP I-NP O
Given VBN B-VP O
his PRP$ B-NP O
current JJ I-NP O
physical JJ I-NP O
examination NN I-NP O
, , O O
and CC O O
lack NN B-NP O
of IN B-PP O
recent JJ B-NP O
PT NN I-NP O
check NN B-NP O
since IN B-PP O
time NN B-NP O
of IN B-PP O
discharge NN B-NP O
on IN B-PP O
the DT B-NP O
30th JJ I-NP B-DATE
, , O O
I PRP B-NP O
am VBP B-VP O
sending VBG I-VP O
a DT B-NP O
stat NN I-NP O
PT. NNP I-NP O
I PRP O O
encouraged VBD B-VP O
the DT B-NP O
patient NN I-NP O
to TO B-VP O
elevate VB I-VP O
the DT B-NP O
leg NN I-NP O
. . O O
My PRP$ B-NP O
feeling NN I-NP O
is VBZ B-VP O
that IN B-SBAR O
the DT B-NP O
DVT NN I-NP O
has VBZ B-VP O
not RB I-VP O
successfully RB I-VP O
been VBN I-VP O
treated VBN I-VP O
and CC O O
that IN B-SBAR O
likely JJ B-NP O
his PRP$ I-NP O
PT NNP I-NP O
is VBZ B-VP O
not RB O O
therapeutic JJ B-NP O
at IN B-PP O
the DT B-NP O
present JJ I-NP O
time NN I-NP O
. . O O
I PRP B-NP O
have VBP B-VP O
arranged VBN I-VP O
for IN B-PP O
the DT B-NP O
patient NN I-NP O
to TO O O
follow VB B-VP O
up RP B-PRT O
with IN B-PP O
Aguilar NNP B-NP B-DOCTOR
, , O O
the DT B-NP O
Internal NNP I-NP O
Medicine NNP I-NP O
nurse NN I-NP O
, , O O
on IN B-PP O
Wednesday NNP B-NP B-DATE
for IN B-PP O
a DT B-NP O
repeat NN I-NP O
check NN B-NP O
of IN B-PP O
his PRP$ B-NP O
PT. NNP I-NP O
I PRP B-NP O
left VBD B-VP O
instructions NNS B-NP O
that IN B-SBAR O
I PRP B-NP O
should MD B-VP O
be VB I-VP O
called VBN I-VP O
immediately RB B-ADVP O
upon IN B-PP O
receiving VBG B-VP O
the DT B-NP O
PT NNP I-NP O
value NN I-NP O
, , O O
I PRP B-NP O
also RB B-ADVP O
arranged VBD B-VP O
for IN B-SBAR O
the DT B-NP O
patient NN B-NP O
to TO B-VP O
meet VB I-VP O
with IN B-PP O
the DT B-NP O
physical JJ I-NP O
therapist NN I-NP O
for IN B-PP O
the DT B-NP O
provision NN I-NP O
of IN B-PP O
a DT B-NP O
cane NN B-NP O
to TO B-VP O
help VB I-VP O
with IN B-PP O
ambulation NN B-NP O
. . O O
2 CD B-NP O
) -RRB- I-NP O
Adult NN I-NP O
onset RB B-ADVP O
diabetes VBZ B-VP O
. . O O
I PRP B-NP O
will MD B-VP O
recheck VB I-VP O
a DT B-NP O
hemoglobin NN I-NP O
A1C IN B-PP O
value NN B-NP O
at IN B-PP O
his PRP$ B-NP O
next JJ B-NP O
office NN I-NP O
visit NN I-NP O
. . O O
A DT B-NP O
finger NN I-NP O
stick VB B-VP O
in IN B-PP O
the DT B-NP O
office NN I-NP O
approximately RB B-NP O
three CD I-NP O
hours NNS B-NP O
after IN B-PP O
eating NN B-NP O
is VBZ B-VP O
253 CD B-NP O
. . O O
I PRP B-NP O
feel VBP B-VP O
this DT B-NP O
is VBZ B-VP O
still RB B-ADVP O
too RB B-ADJP O
elevated JJ I-ADJP O
. . O O
I PRP O O
will MD B-VP O
therefore RB I-VP O
adjust VB I-VP O
his PRP$ B-NP O
insulin NN I-NP O
dose NN I-NP O
when WRB B-ADVP O
I PRP B-NP O
see VBP B-VP O
him PRP B-NP O
next JJ B-NP O
week NN I-NP O
. . O O
I PRP O O
will MD O O
follow VB B-VP O
up RP B-PRT O
with IN B-PP O
the DT B-NP O
patient NN I-NP O
next JJ B-NP O
week NN I-NP O
and CC O O
make VB B-VP O
any DT B-NP O
necessary JJ I-NP O
adjustments NNS B-NP O
in IN B-PP O
his PRP$ B-NP O
medications NNS I-NP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
. . O O
Michael NNP B-NP B-DOCTOR
Uecker NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
PD:UD:1698 . O B-IDNUM
DD NNP B-NP O
: : O O
2-19-65 CD O B-DATE
DT NNP B-NP O
: : O O
2-22-65 CD O B-DATE
DV NNP B-NP O
: : O O
2-4-65 CD O B-DATE
