Record NNP B-NP O
date NN I-NP O
: : O O
2067-05-03 CD O B-DATE
Narrative JJ B-NP O
History NN I-NP O
55 CD B-NP B-AGE
yo NNP I-NP O
woman NN I-NP O
who WP B-NP O
presents VBZ B-VP O
for IN B-PP O
f/u NN B-NP O
Seen NNP B-NP O
in IN B-PP O
Cardiac NNP B-NP O
rehab NN I-NP O
locally RB I-NP O
last JJ B-NP O
week NN I-NP O
and CC O O
BP NNP B-NP O
170/80 CD I-NP O
. . O O
They PRP B-NP O
called VBD B-VP O
us PRP B-NP O
and CC O O
we PRP B-NP O
increased VBD B-VP O
her PRP$ B-NP O
HCTZ NN I-NP O
to TO B-PP O
25 CD B-NP O
mg NN I-NP O
from IN B-PP O
12.5 CD B-NP O
mg NN I-NP O
. . O O
States NNPS B-VP O
her PRP$ B-NP O
BP NNP I-NP O
's POS B-NP O
were VBD B-VP O
fine JJ B-ADJP O
there RB B-NP O
since IN I-NP O
- : O O
130-140/70-80 CD B-NP O
. . O O
Saw VBD O O
Dr NNP B-NP O
Oakley NNP I-NP B-DOCTOR
4/5/67 CD I-NP B-DATE
- : O O
she PRP B-NP O
was VBD B-VP O
happy JJ B-ADJP O
with IN B-PP O
results NNS B-NP O
of IN B-PP O
ETT NNP B-NP O
at IN B-PP O
Clarkfield NNP B-NP B-HOSPITAL
. . O O
To TO B-VP O
f/u VB I-VP O
7/67 CD B-NP B-DATE
. . O O
No DT O O
CP NNP B-NP O
's POS B-NP O
since IN I-NP O
last JJ O O
admit VB B-VP O
. . O O
Back RB B-ADVP O
to TO B-PP O
work NN B-NP O
and CC O O
starting VBG B-VP O
to TO I-VP O
walk VB I-VP O
. . O O
No DT B-NP O
wt NN I-NP O
loss NN I-NP O
and CC O O
discouraged VBN B-VP O
by IN B-PP O
this DT B-NP O
, , O O
but CC O O
just RB B-VP O
starting VBG I-VP O
to TO I-VP O
exercise VB I-VP O
. . O O
No DT B-NP O
smoking NN I-NP O
for IN B-PP O
3 CD B-NP O
months NNS I-NP O
now RB B-ADVP O
! . O O
Still RB B-ADVP O
with IN B-PP O
hotflashes NNS B-NP O
, , O O
wakes VBZ B-VP O
her PRP$ B-NP O
up RB B-ADVP O
at IN B-PP O
night NN B-NP O
. . O O
Problems NNS B-NP O
FH NNP B-NP O
breast NN I-NP O
cancer NN I-NP O
37 CD B-NP B-AGE
yo NNP I-NP O
s PRP B-LST O
FH NNP B-NP O
myocardial JJ I-NP O
infarction NN I-NP O
mother NN I-NP O
died VBD B-VP O
66 CD B-NP B-AGE
yo CD I-NP O
Hypertension NN B-NP O
Uterine NNP B-NP O
fibroids NNS I-NP O
u/s VBD B-VP O
2062 CD I-VP B-DATE
Smoking VBG O O
hyperlipidemia NN B-NP O
CRF NNP I-NP O
mild JJ I-NP O
chol NN I-NP O
, , O O
cigs NNS B-NP O
, , O O
HTN NNP B-NP O
, , O O
Fhx NNP B-NP O
and CC O O
known VBN B-VP O
hx NN B-NP O
CAD NN I-NP O
in IN B-PP O
pt NN B-NP O
. . O O
borderline NN B-NP O
diabetes NNS I-NP O
mellitus JJ B-ADJP O
4/63 CD B-NP B-DATE
125 CD I-NP O
, , O O
follow VBP B-VP O
hgbaic NN B-NP O
VPB NNP B-NP O
2065 CD I-NP B-DATE
- : O O
ETT NNP B-NP O
showed VBD B-VP O
freq JJ B-ADJP O
PVC . O O
coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
s/p VBZ B-VP O
ant JJ B-NP O
SEMI NNP I-NP O
+ NNP I-NP O
stent NN I-NP O
LAD NNP B-NP O
2/67 CD I-NP B-DATE
, , O O
Dr NNP B-NP O
Oakley NNP I-NP B-DOCTOR
thyroid DT B-NP O
nodule NN I-NP O
2065 CD I-NP B-DATE
, , O O
hot JJ B-ADVP O
, , O O
follow VB B-VP O
TSH. . O O
Medications NNS B-NP O
NORVASC NNP B-NP O
( -LRB- I-NP O
AMLODIPINE NNP I-NP O
) -RRB- I-NP O
5MG . B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
PLAVIX NNP B-NP O
( -LRB- I-NP O
CLOPIDOGREL NN I-NP O
) -RRB- I-NP O
75 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
QD . O O
ATENOLOL NNP B-NP O
50MG VBD B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
ASA NNP B-NP O
(ACETYLSALICYLIC NN I-NP O
ACID NNP I-NP O
) -RRB- I-NP O
325MG JJ I-NP O
1 CD I-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
ZESTRIL NNP B-NP O
( -LRB- I-NP O
LISINOPRIL NNP I-NP O
) -RRB- I-NP O
40MG . B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
LIPITOR NNP B-NP O
( -LRB- I-NP O
ATORVASTATIN NNP I-NP O
) -RRB- I-NP O
10MG . B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
HCTZ NN B-NP O
( -LRB- I-NP O
HYDROCHLOROTHIAZIDE NNP I-NP O
) -RRB- I-NP O
25MG . B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
NITROGLYCERIN NNP B-NP O
1/150 CD I-NP O
( -LRB- I-NP O
0.4 CD I-NP O
MG) NN I-NP O
1 CD I-NP O
TAB NNP I-NP O
SL NNP I-NP O
x1 VBD B-VP O
PRN NNP B-NP O
prn NN I-NP O
CP CD O O
Allergies . O O
CECLOR NN B-NP O
( -LRB- I-NP O
CEFACLOR NN I-NP O
) -RRB- I-NP O
Rash . O O
Vital JJ B-NP O
Signs NNS I-NP O
BLOOD NN B-NP O
PRESSURE-SITTING JJ I-NP O
150/70 CD O O
repeat NN B-NP O
145/8 CD I-NP O
0 CD I-NP O
HR NNP I-NP O
60 CD I-NP O
reg NN I-NP O
WT NNP B-NP O
202 CD I-NP O
lbs NNS I-NP O
Physical NNP B-NP O
Exam NNP I-NP O
Looks VBZ B-VP O
well RB B-ADVP O
. . O O
Lungs '' O O
clear JJ B-ADVP O
, , O O
CVS NNP B-NP O
RRRs1s2 NNP I-NP O
, , O O
Ext NNP B-NP O
- : O O
no DT B-NP O
edema NN I-NP O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
1 LS B-NP O
. . O O
H/M VB B-VP O
- : O O
Pe NNP B-NP O
next IN B-PP O
appt NN B-NP O
in IN B-PP O
few JJ B-NP O
months NNS I-NP O
. . O O
Overdue NN B-VP O
for IN B-PP O
mammo NN B-NP O
- : O O
will MD B-VP O
need VB I-VP O
to TO I-VP O
stress VB I-VP O
this DT B-NP O
. . O O
2. CD B-NP O
CAD NN I-NP O
- : O O
cont NN B-NP O
with IN B-PP O
cardiac JJ B-NP O
rehab NN I-NP O
, , O O
exercise NN B-NP O
, , O O
Dr NNP B-NP O
Oakley NNP I-NP B-DOCTOR
, , O O
but CC O O
doing VBG B-VP O
well RB B-ADVP O
. . O O
3. DT B-NP O
BP NNP I-NP O
- : O O
better RB B-ADVP O
on IN B-PP O
increased VBN B-NP O
HCTZ. NNP I-NP O
Check VB I-NP O
labs NNS I-NP O
next JJ B-NP O
visit NN I-NP O
, , O O
good JJ B-NP O
K NNP I-NP O
recently RB I-NP O
and CC B-PP O
on IN B-PP O
ACEI. NNP B-NP O
4 CD B-LST O
. . O O
Cigs NNPS O O
- : O O
great JJ B-ADJP O
! . O O
5 CD B-NP O
. . O O
Hot NNP B-NP O
flashes NNS I-NP O
- : O O
does VBZ B-VP O
n't RB I-VP O
want VB I-VP O
to TO I-VP O
try VB I-VP O
any DT B-NP O
other JJ I-NP O
meds NNS I-NP O
- : O O
will MD B-VP O
try VB I-VP O
to TO I-VP O
put VB I-VP O
up RP B-PRT O
with IN B-PP O
it PRP B-NP O
. . O O
6 CD B-NP O
. . O O
Hot NNP B-NP O
thyroid VBD B-VP O
nodule JJ B-ADJP O
- : O O
recheck NN B-NP O
TSH NNS I-NP O
next JJ B-NP O
visit NN I-NP O
. . O O
7. . B-NP O
Borderline NNP I-NP O
glc FW I-NP O
- : O O
ok NN B-NP O
hgba1c JJ B-NP O
3/67 CD I-NP B-DATE
. . O O
8. DT B-NP O
Chol NNP I-NP O
- : O O
ok NN B-NP O
, , O O
fasting VBG B-VP O
on IN B-PP O
next JJ B-NP O
visit NN I-NP O
. . O O
