Record NNP B-NP O
date NN I-NP O
: : O O
2164-08-24 CD O B-DATE
CARDIOLOGY NN B-NP O
NORTHLAND NNP B-NP B-HOSPITAL
MEDICAL NNP I-NP I-HOSPITAL
CLINIC NN I-NP I-HOSPITAL
Reason NN B-NP O
for IN B-PP O
visit NN B-NP O
: : O O
Follow VB B-VP O
up IN B-ADVP O
of IN B-PP O
CAD NN B-NP O
s/p NN I-NP O
CABG NNP B-VP O
adn IN B-PP O
multiple JJ B-NP O
CV NNS I-NP O
risk NN I-NP O
factors NNS I-NP O
Interval NNP B-NP O
History NN I-NP O
: : O O
A DT B-NP O
74 CD I-NP B-AGE
yo NNP I-NP O
man NN I-NP O
with IN B-PP O
a DT B-NP O
long JJ I-NP O
history NN I-NP O
of IN B-PP O
CAD NN B-NP O
eventually RB I-NP O
necessitating JJ I-NP O
CABG NNP I-NP O
in IN B-PP O
4/2161 CD B-NP B-DATE
. . O O
He PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
several JJ B-NP O
chest NN I-NP O
pain NN I-NP O
syndromes NNS I-NP O
over IN B-PP O
the DT B-NP O
years NNS I-NP O
but CC O O
, , O O
as IN B-PP O
of IN B-PP O
late JJ B-NP O
, , O O
has VBZ B-VP O
been VBN I-VP O
doing VBG I-VP O
quite RB B-ADVP O
well RB I-ADVP O
in IN B-PP O
that DT B-NP O
regard NN I-NP O
. . O O
His PRP$ B-NP O
last JJ I-NP O
CV NN I-NP O
evaluation NN I-NP O
was VBD B-VP O
an DT B-NP O
Adenosine NNP I-NP O
PET NNP I-NP O
in IN B-PP O
4/63 CD B-NP B-DATE
which WDT B-NP O
showed VBD B-VP O
an DT B-NP O
EF NN I-NP O
46 CD I-NP O
with IN B-PP O
anterior JJ B-NP O
and CC I-NP O
anterolateral JJ I-NP O
flow NN I-NP O
abnormalites NNS I-NP O
. . O O
These DT B-NP O
are VBP B-VP O
consistent JJ B-ADJP O
with IN B-PP O
his PRP$ B-NP O
known VBN I-NP O
occluded VBD B-VP O
diagonal JJ B-NP O
( -LRB- I-NP O
also RB B-NP O
unbypassed JJ I-NP O
) -RRB- I-NP O
. . O O
His PRP$ B-NP O
last JJ I-NP O
cath NN I-NP O
in IN B-PP O
6/62 CD B-NP B-DATE
showed VBD B-VP O
patent NN B-NP O
vein NN I-NP O
grafts NNS B-VP O
to TO B-PP O
his PRP$ B-NP O
OM NN I-NP O
and CC B-PP O
to TO B-PP O
his PRP$ B-NP O
RCA NNP I-NP O
and CC O O
a DT B-NP O
patent NN I-NP O
but CC O O
atretic JJ B-NP O
LIMA. NNP I-NP O
He PRP B-NP O
has VBZ B-VP O
an DT B-NP O
occluded JJ I-NP O
RCA NN I-NP O
, , O O
an DT B-NP O
80 CD I-NP O
% NN I-NP O
OM NN I-NP O
, , O O
and CC O O
a DT B-NP O
60 CD I-NP O
% NN I-NP O
LAD NN I-NP O
in IN B-PP O
addition NN B-NP O
to TO B-PP O
the DT B-NP O
occluded JJ I-NP O
diagonal JJ I-NP O
( -LRB- I-NP O
fills NNS I-NP O
via IN B-PP O
OM NN B-NP O
collaterals NNS I-NP O
) -RRB- B-VP O
. . O O
He PRP B-NP O
was VBD B-VP O
admitted VBN I-VP O
to TO B-PP O
Fahey NNP B-NP B-HOSPITAL
Center NNP I-NP I-HOSPITAL
in IN B-PP O
May NNP B-NP B-DATE
with IN B-PP O
syncope NN B-NP O
associated VBN B-VP O
with IN B-PP O
bradycardia NN B-NP O
. . O O
His PRP$ B-NP O
atenolol NN I-NP O
was VBD B-VP O
changed VBN I-VP O
to TO B-PP O
coreg NN B-NP O
and CC O O
he PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
no DT B-NP O
difficulties NNS I-NP O
since IN B-PP O
that DT B-NP O
time NN I-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
have VB I-VP O
a DT B-NP O
long-standing JJ I-NP O
trifasicular JJ I-NP O
block NN I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
chest NN I-NP O
pain NN I-NP O
, , O O
orthopnea NN B-NP O
, , O O
PND NNP B-NP O
, , O O
LEE NNP B-NP O
, , O O
palpitations NNS B-NP O
, , O O
or CC O O
syncope NN B-NP O
since IN B-PP O
that DT B-NP O
admission NN I-NP O
. . O O
Someone NN B-NP O
started VBD B-VP O
him PRP B-NP O
on IN B-PP O
Niaspan NNP B-NP O
which WDT B-NP O
has VBZ B-VP O
been VBN I-VP O
associated VBN I-VP O
with IN B-PP O
diffuse JJ B-NP O
flushing NN I-NP O
, , O O
itching VBG B-VP O
, , O O
and CC O O
a DT B-NP O
burning NN I-NP O
sensation NN I-NP O
. . O O
Past JJ B-NP O
medical JJ I-NP O
history NN I-NP O
: : O O
CAD NN B-NP O
with IN B-PP O
CABG NNP B-NP O
in IN B-PP O
4/61 CD B-NP B-DATE
, , O O
LIMA NNP B-NP O
to TO B-PP O
LAD NNP B-NP O
, , O O
V NNP B-NP O
to TO B-PP O
RCA NNP B-NP O
PLVB NNP I-NP O
, , O O
V NNP B-NP O
to TO B-PP O
OM NNP B-NP O
-- : O O
he PRP B-NP O
has VBZ B-VP O
an DT B-NP O
unbypassed JJ I-NP O
occluded JJ I-NP O
Diagonal NNP I-NP O
with IN B-PP O
collaterals NNS B-NP O
from IN B-PP O
the DT B-NP O
OM NN I-NP O
Dressler NNP B-NP O
's POS B-NP O
HTN . O O
lipids NNS B-NP O
DM . O O
neuropathy NN B-NP O
Frozen NNP B-NP O
shoulder NN I-NP O
GERD NNP B-NP O
TIAs NNP B-NP O
2153 CD I-NP B-DATE
and CC O O
12/2160 CD O B-DATE
Bladder NNP B-NP O
CA NNP I-NP O
s/p NN B-NP O
TURP NNS I-NP O
Medications NNS B-NP O
( -LRB- B-VP O
Confirmed VBN B-NP O
) -RRB- I-NP O
: : O O
aspirin NN B-NP O
Coreg NNP B-NP O
3.125mg CD I-NP O
po NN I-NP O
qd NN I-NP O
Diovan NNP B-NP O
Insulin NNP B-NP O
syringes NNS I-NP O
Klor NNP B-NP O
con RB I-NP O
10meq CD I-NP O
po NN I-NP O
qd NN I-NP O
Lasix NNP B-NP O
40mg CD I-NP O
po NN I-NP O
qd NN I-NP O
Neurontin NNP B-NP O
300 CD I-NP O
mg NN I-NP O
po NN I-NP O
tid NN I-NP O
Nexium NNP B-NP O
40mg CD I-NP O
po NN I-NP O
qd NN I-NP O
NPH NNP B-NP O
insulin NN I-NP O
48units VBZ B-VP O
sc NN B-NP O
qam NN I-NP O
Onetouch RB O O
strips NNS B-NP O
Pravachol NNP B-NP O
20mg CD I-NP O
po NN I-NP O
qd NN I-NP O
regular JJ B-NP O
insulin NN I-NP O
sc NN I-NP O
Zetia NNP B-NP O
10mg CD I-NP O
po NN I-NP O
qd NN I-NP O
Allergies NNP B-NP O
: : O O
Drug NN B-NP O
allergy NN I-NP O
Vioxx NNP I-NP O
. . I-NP O
Zestril NNP I-NP O
, , O O
gives VBZ B-VP O
a DT B-NP O
cough NN I-NP O
. . O O
Penicillin NNP B-NP O
allergy NN I-NP O
Penicillin NNP I-NP O
. . O O
Family NNP B-NP O
history NN I-NP O
: : O O
Mother NN B-NP O
died VBD B-VP O
at IN B-PP O
67 CD B-NP B-AGE
, , O O
had VBD B-VP O
MI NNP B-NP O
in IN B-PP O
her PRP$ B-NP O
50s NNS I-NP B-AGE
Father NNP B-NP O
died VBD B-VP O
in IN B-PP O
his PRP$ B-NP O
80s NNS I-NP B-AGE
, , O O
had VBD B-VP O
DM NNP B-NP O
and CC I-NP O
PVD NNP I-NP O
Social JJ B-NP O
history NN I-NP O
: : O O
Married VBN B-VP O
. . B-NP O
Retired NNP I-NP O
sales NNS I-NP B-PROFESSION
specialist NN I-NP I-PROFESSION
. . B-PP O
Paints NNS B-NP O
and CC O O
enjoys VBZ B-VP O
model NN B-NP O
trains NNS I-NP O
. . O O
Quit NNP B-NP O
smoking NN I-NP O
2152 CD B-NP B-DATE
. . O O
No UH B-ADVP O
ETOH. . O O
Review NNP B-NP O
of IN B-PP O
systems NNS B-NP O
: : O O
As IN B-PP O
above RB B-NP O
. . O O
Also RB O O
some DT B-NP O
memory NN I-NP O
lapses NNS I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
some DT B-NP O
productive JJ I-NP O
cough NN I-NP O
, , O O
but CC O O
no DT B-NP O
change NN I-NP O
from IN B-PP O
prior JJ B-NP O
. . O O
Otherwise RB B-ADJP O
negative JJ I-ADJP O
in IN B-PP O
detail NN B-NP O
. . O O
Physical JJ B-NP O
examination NN I-NP O
: : O O
-Pulse NN B-NP O
: : O O
62 CD O O
-General JJ B-NP O
: : O O
No DT B-NP O
acute JJ I-NP O
distress NN I-NP O
. . O O
-Skin NNP B-NP O
: : O O
No DT B-NP O
rashes NNS I-NP O
, , O O
anicteric JJ B-ADJP O
. . O O
-Neck NN B-NP O
: : O O
Carotids NNP B-NP O
2+ CD I-NP O
without IN B-PP O
bruits NNS B-NP O
. . O O
JVP NN B-NP O
7 CD I-NP O
no DT B-NP O
jugular NN I-NP O
venous JJ I-NP O
distention NN I-NP O
. . O O
-Chest NN B-NP O
: : O O
Clear NNP B-NP O
to TO B-PP O
auscultation NN B-NP O
and CC I-NP O
percussion NN I-NP O
. . O O
-Cardiac JJ B-NP O
: : O O
Left VBN B-VP O
ventricular JJ B-NP O
impulse NN I-NP O
discrete NN I-NP O
and CC O O
nondisplaced JJ B-NP O
. . O O
Regular JJ B-NP O
rate NN I-NP O
and CC I-NP O
rhythm NN I-NP O
, , O O
normal JJ B-NP O
S1 NNP I-NP O
and CC I-NP O
S2 NNP I-NP O
, , O O
with IN B-PP O
no DT B-NP O
S3 NNP I-NP O
or CC I-NP O
S4 NNP I-NP O
. . O O
There EX B-NP O
were VBD B-VP O
no DT B-NP O
murmurs NNS I-NP O
, , O O
clicks VBZ B-VP O
or CC I-VP O
rubs VBZ I-VP O
. . O O
-Abdomen NNS B-NP O
: : O O
Normal JJ B-NP O
bowel NN I-NP O
sounds NNS I-NP O
, , O O
soft JJ B-NP O
and CC I-NP O
nontender JJ I-NP O
, , O O
with IN B-PP O
no DT B-NP O
hepatosplenomegaly NN I-NP O
or CC I-NP O
masses NNS I-NP O
appreciated VBN B-VP O
. . O O
-Extremities NNS B-NP O
: : O O
No DT B-NP O
cyanosis NN I-NP O
, , I-NP O
clubbing VBG I-NP O
or CC I-NP O
edema NN I-NP O
. . O O
2+ '' O O
femoral JJ B-NP O
pulses NNS I-NP O
without IN B-PP O
bruits NNS B-NP O
. . O O
2+ CD B-NP O
pedal NN I-NP O
pulses NNS I-NP O
. . O O
-BP JJ B-NP O
: : O O
152/66 CD O O
-resp. DT B-NP O
rate NN I-NP O
: : O O
12 CD O O
-weight NN B-NP O
: : O O
216 CD B-NP O
lbs NN I-NP O
. . O O
-Heent JJ B-NP O
: : O O
Unremarkable JJ O O
EKG NNP B-NP O
: : O O
NSR NNP B-NP O
with IN B-PP O
trifasicular JJ B-NP O
block NN I-NP O
. . O O
CR VBD B-VP O
c/w NN B-NP O
COPD. . O O
Compared VBN B-VP O
to TO B-PP O
9/63 CD B-NP B-DATE
, , O O
HR NNP B-NP O
has VBZ B-VP O
increased VBN I-VP O
. . O O
Selected NNP B-NP O
recent JJ I-NP O
labs NNS I-NP O
: : O O
Metabolic NNP B-NP O
Date NNP B-NP O
K NNP I-NP O
CRE NNP I-NP O
07/29/64 CD B-NP B-DATE
3.8 CD I-NP O
1.1 CD O O
Lipid/Thyroid NNP B-NP O
Date NNP B-NP O
CHOL NNP I-NP O
TRIG NNP I-NP O
HDL NNP I-NP O
LDL NNP I-NP O
07/20/64 CD B-NP B-DATE
125 CD I-NP O
118 CD I-NP O
42 CD I-NP O
59 CD O O
Assessment NNP B-NP O
and CC I-NP O
plan NN I-NP O
: : O O
A DT B-NP O
74 CD I-NP B-AGE
yo NNP I-NP O
man NN I-NP O
with IN B-PP O
multiple JJ B-NP O
chest NN I-NP O
pain NN I-NP O
syndromes NNS I-NP O
and CC O O
CV JJ B-NP O
risk NN I-NP O
factors NNS I-NP O
associated VBN B-VP O
with IN B-PP O
CAD NN B-NP O
and CC I-NP O
mild JJ I-NP O
LV NNP I-NP O
dysfunction NN I-NP O
. . O O
His PRP$ B-NP O
chest NN I-NP O
pain NN I-NP O
syndromes NNS I-NP O
have VBP B-VP O
resolved VBN I-VP O
. . O O
He PRP B-NP O
has VBZ B-VP O
a DT B-NP O
long-standing JJ I-NP O
trifasicular JJ I-NP O
block NN I-NP O
and CC O O
had VBD B-VP O
what WP B-NP O
sounds NNS I-NP O
like IN B-PP O
syncope NN B-NP O
a DT B-NP O
few JJ I-NP O
months NNS I-NP O
ago RB B-ADVP O
. . O O
This DT B-NP O
was VBD B-VP O
associated VBN I-VP O
with IN B-PP O
bradycardia NN B-NP O
and CC O O
has VBZ B-VP O
resolved VBN I-VP O
with IN B-PP O
changing VBG B-VP O
him PRP B-NP O
to TO B-PP O
low JJ B-NP O
dose NN I-NP O
coreg NN I-NP O
. . O O
CV NNP B-NP O
risk NN I-NP O
factor NN I-NP O
modification NN I-NP O
remains VBZ B-VP O
our PRP$ B-NP O
primary JJ I-NP O
focus NN I-NP O
. . O O
Plan NNP B-NP O
. . O O
1 CD B-LST O
. . O O
CAD-increase NN B-VP O
asa NN B-NP O
to TO B-PP O
325 CD B-NP O
and CC O O
take VB B-VP O
at IN B-PP O
night NN B-NP O
with IN B-PP O
niaspan NN B-NP O
in IN B-PP O
hopes NNS B-NP O
of IN B-PP O
lessening VBG B-VP O
side NN B-NP O
effects NNS I-NP O
. . O O
He PRP B-NP O
needs VBZ B-VP O
an DT B-NP O
ARB NN I-NP O
, , O O
so RB B-ADVP O
will MD B-VP O
try VB I-VP O
again RB B-ADVP O
to TO B-VP O
get VB I-VP O
him PRP B-NP O
to TO B-VP O
take VB I-VP O
diovan NN B-NP O
at IN B-PP O
80 CD B-NP O
a DT B-NP O
day NN I-NP O
( -LRB- O O
I PRP B-NP O
gave VBD B-VP O
samples NNS B-NP O
and CC O O
a DT B-NP O
Rx NN I-NP O
) -RRB- I-NP O
. . O O
2. . B-NP O
LV NNP I-NP O
dysfunction--we , O O
will MD B-VP O
check VB I-VP O
a DT B-NP O
GBPS NNP I-NP O
for IN B-PP O
EF. NNP B-NP O
3. DT B-NP O
DM-followed NNP I-NP O
by IN B-PP O
Dr. NNP B-NP O
Orton NNP I-NP B-DOCTOR
. . O O
Continue NNP O O
to TO B-VP O
aim VB I-VP O
for IN B-PP O
an DT B-NP O
A1c NNP I-NP O
of IN B-PP O
7.0 CD B-NP O
4 CD B-LST O
. . O O
Carotid NNP B-NP O
disease--this VBD B-VP O
seems VBZ B-NP O
to TO B-VP O
be VB I-VP O
limited VBN I-VP O
to TO B-PP O
the DT B-NP O
external JJ I-NP O
carotid NN I-NP O
, , O O
so IN O O
I PRP B-NP O
do VBP B-VP O
n't RB I-VP O
think VB I-VP O
any DT B-NP O
intervention NN I-NP O
will MD B-VP O
be VB I-VP O
necessary JJ B-ADJP O
. . O O
Continue NNP O O
to TO B-PP O
Rx NNP B-NP O
risk NN I-NP O
factors NNS I-NP O
. . O O
5 CD B-NP O
. . O O
Lipids-look NNP B-NP O
great JJ I-NP O
today NN B-NP O
. . O O
Continue VB B-VP O
as RB I-VP O
is VBZ I-VP O
, , O O
but CC O O
given VBN B-VP O
his PRP$ B-NP O
past JJ I-NP O
intolerance NN I-NP O
of IN B-PP O
and CC O O
noncompliance NN B-VP O
with IN B-PP O
meds NNS B-NP O
, , O O
I PRP B-NP O
suspect VBP B-VP O
he PRP B-NP O
will MD B-VP O
give VB I-VP O
up RP B-PRT O
the DT B-NP O
Niaspan NNP I-NP O
soon RB B-ADVP O
! . O O
We PRP B-NP O
will MD B-VP O
try VB I-VP O
to TO I-VP O
give VB I-VP O
asa NN B-NP O
with IN B-PP O
it PRP B-NP O
to TO B-VP O
help VB I-VP O
with IN B-PP O
the DT B-NP O
side NN I-NP O
effects NNS I-NP O
. . O O
6 CD B-NP O
. . O O
HTN--home NNP B-NP O
BPs NNPS I-NP O
have VBP B-VP O
been VBN I-VP O
higher JJR I-VP O
too RB B-ADVP O
on IN B-PP O
coreg NN B-NP O
. . O O
I PRP B-NP O
am VBP B-VP O
trying VBG I-VP O
to TO I-VP O
get VB I-VP O
him PRP B-NP O
on IN B-PP O
an DT B-NP O
ARB NN I-NP O
again RB B-ADVP O
. . O O
Diovan NNP O O
at IN B-PP O
80 CD B-NP O
a DT B-NP O
day NN I-NP O
. . O O
He PRP B-NP O
will MD B-VP O
get VB I-VP O
f/u RB B-NP O
labs NNS I-NP O
in IN B-PP O
one CD B-NP O
month NN I-NP O
f/u NN B-NP O
6months NNS I-NP O
Changes NNS B-NP O
to TO B-PP O
Medications NNS B-NP O
this DT B-NP O
visit NN I-NP O
regular JJ B-NP O
insulin NN I-NP O
sc NN I-NP O
14u IN B-PP O
qam NN B-NP O
and CC O O
14u CD B-NP O
qpm NN I-NP O
QTY NNP B-NP O
:1 CD I-NP O
Refills NNP I-NP O
:6 CD I-NP O
Start NNP I-NP O
: : O O
11/25/2160 CD O B-DATE
NPH NNP B-NP O
insulin NN I-NP O
48units VBZ B-VP O
sc NN B-NP O
qam NN I-NP O
16 CD B-NP O
units NNS I-NP O
qpm IN B-PP O
QTY:3month JJ B-NP O
supply NN I-NP O
Refills NNS I-NP O
:5 IN B-PP O
Start NNP B-NP O
: : O O
10/20/2153 CD O B-DATE
Diovan NNP B-NP O
80mg CD I-NP O
po NN I-NP O
qd NN I-NP O
QTY NNP B-NP O
:90 CD I-NP O
Refills NNP I-NP O
:3 CD I-NP O
Start NNP I-NP O
: : O O
08/24/2164 CD O B-DATE
Coreg NNP B-NP O
3.125mg CD I-NP O
po NN I-NP O
bid NN I-NP O
QTY:30 IN B-PP O
Refills NNP B-NP O
:5 CD I-NP O
Start NNP I-NP O
: : O O
06/16/2164 CD O B-DATE
Zetia NNP B-NP O
10mg CD I-NP O
po NN I-NP O
qd NN I-NP O
QTY NNP B-NP O
:90 CD I-NP O
Refills NNP I-NP O
:3 CD I-NP O
Start NNP I-NP O
: : O O
10/25/2162 CD O B-DATE
Nexium NNP B-NP O
40mg CD I-NP O
po NN I-NP O
qd VBD B-VP O
QTY:30 CD B-NP O
Refills NNS I-NP O
:3 IN B-PP O
Start NNP B-NP O
: : O O
08/18/2164 CD O B-DATE
Klor NNP B-NP O
con RB I-NP O
10meq CD I-NP O
po NN I-NP O
qd CC O O
take VB B-VP O
with IN B-PP O
food NN B-NP O
; : O O
do VBP B-VP O
not RB I-VP O
chew VB I-VP O
tabs NNS B-NP O
QTY NNP I-NP O
:90 CD I-NP O
Refills NNP I-NP O
:3 CD I-NP O
Start NNP I-NP O
: : O O
04/11/2161 CD O B-DATE
Lasix NNP B-NP O
40mg CD I-NP O
po NN I-NP O
qd VBD B-VP O
QTY:30 CD B-NP O
Refills NNS I-NP O
:1yr IN B-PP O
Start NNP B-NP O
: : O O
07/28/2161 CD O B-DATE
aspirin NN B-NP O
325 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd VBD B-VP O
QTY NNP B-NP O
:90 CD I-NP O
Refills NNS I-NP O
:3 . O O
Pravachol NNP B-NP O
20mg CD I-NP O
po NN I-NP O
qd VBD B-VP O
QTY:30 CD B-NP O
Refills NNS I-NP O
:5 IN B-PP O
Start NNP B-NP O
: : O O
05/25/2161 CD O B-DATE
Neurontin NNP B-NP O
300 CD I-NP O
mg NN I-NP O
po NN I-NP O
tid JJ B-ADJP O
QTY NNP B-NP O
:90 CD I-NP O
Refills NNP I-NP O
:11 CD I-NP O
Start NNP I-NP O
: : O O
05/25/2161 CD O B-DATE
Onetouch IN B-SBAR O
strips NNS B-NP O
use VBP B-VP O
5xday IN B-PP O
# # B-NP O
200 CD I-NP O
with IN B-PP O
1 CD B-NP O
year NN I-NP O
Insulin NNP B-NP O
syringes NNS I-NP O
BD CC O O
U-100 DT B-NP O
1cc JJ I-NP O
# # I-NP O
100 CD I-NP O
w/11 CD I-NP O
refills NNS I-NP O
DX NNP B-NP O
Tests NNS I-NP O
Ordered VBD B-VP O
: : O O
GBPS . O O
BMP NNP B-NP O
in IN B-PP O
one CD B-NP O
month NN I-NP O
CC NNP B-NP O
: : O O
Dr. NNP B-NP O
Barbara NNP I-NP B-DOCTOR
Chavez NNP I-NP I-DOCTOR
Signed VBN B-VP O
electronically RB B-ADVP O
by IN B-PP O
Riley NNP B-NP B-DOCTOR
L NNP I-NP I-DOCTOR
Overby NNP I-NP I-DOCTOR
MD NNP I-NP O
on IN B-PP O
Aug NNP B-NP B-DATE
24 CD I-NP I-DATE
, , O I-DATE
2164 CD O I-DATE
