Record NNP B-NP O
date NN I-NP O
: : O O
2093-01-28 CD O B-DATE
Problems NNS B-NP O
Health NNP B-NP O
maintenance NN I-NP O
Depression NN B-NP O
: : O O
Per IN B-PP O
daughter NN B-NP O
, , O O
depression NN B-NP O
significant JJ I-NP O
component NN I-NP O
of IN B-PP O
back RB B-NP O
pain NN I-NP O
. . O O
Pt NNP B-NP O
's POS B-NP O
home NN I-NP O
was VBD B-VP O
funeral JJ B-NP O
home NN I-NP O
prior RB B-ADVP O
. . O O
By IN B-SBAR O
family NN B-NP O
report NN I-NP O
pt NN I-NP O
asserts VBZ B-VP O
she PRP B-NP O
can MD B-VP O
" `` I-VP O
smell VB I-VP O
" '' I-VP O
odors NNS B-NP O
from IN B-PP O
funeral NN B-NP O
home NN I-NP O
use NN I-NP O
. . O O
Osteoporosis NN B-NP O
GERD NNP B-NP O
HTN . O O
Interstitial NNP B-NP O
nephritis NN I-NP O
H/O NNP B-NP O
Systemic NNP I-NP O
lupus FW I-NP O
erythematosis NN I-NP O
: : O O
Diagnosed VBN B-VP O
2083 CD B-NP B-DATE
with IN B-PP O
ANA NNP B-NP O
+ NNP I-NP O
, , O O
1:5120 CD B-NP O
speckled JJ I-NP O
pattern NN I-NP O
; : O O
Anti NNP B-NP O
Ro+ NNP I-NP O
. . O O
Abdominal JJ B-NP O
pain NN I-NP O
H/O NNP B-NP O
Coronary NNP I-NP O
artery NN I-NP O
disease NN I-NP O
: : O O
S/p NNP B-NP O
RCA NNP I-NP O
PTCA NNP I-NP O
12/2082 CD I-NP B-DATE
. . O O
Diabetes NNP B-NP O
mellitus NN I-NP O
type NN I-NP O
2 CD O O
Bile NNP B-NP O
duct NN I-NP O
obstruction NN I-NP O
: : O O
Abdominal JJ B-NP O
CT NNP I-NP O
- : O O
dilated JJ B-NP O
intrahepatic JJ I-NP O
ducts NNS I-NP O
and CC O O
common JJ B-NP O
bile NN I-NP O
duct NN I-NP O
confirmed VBN B-VP O
by IN B-PP O
RUQ NNP B-NP O
ultrasound NN I-NP O
. . O O
On IN B-PP O
ERCP NNP B-NP O
- : O O
bulging VBG B-VP O
papilla NN B-NP O
; : O O
cannulation NN B-NP O
difficult JJ I-NP O
, , I-NP O
excess JJ I-NP O
papillotomy NN I-NP O
was VBD B-VP O
performed VBN I-VP O
; : O O
entire JJ B-NP O
biliary JJ I-NP O
system NN I-NP O
severely RB B-VP O
dilated VBN I-VP O
with IN B-PP O
CBD NNP B-NP O
measuring VBG B-VP O
~13 CD B-NP O
mm CD I-NP O
, , O O
no DT B-NP O
filling VBG I-NP O
defects NNS I-NP O
seen VBN B-VP O
; : O O
small JJ B-NP O
amount NN I-NP O
of IN B-PP O
debris NN B-NP O
was VBD B-VP O
removed VBN I-VP O
. . B-NP O
Excess NNP I-NP O
papillotomy NN I-NP O
was VBD B-VP O
extended VBN I-VP O
and CC O O
the DT B-NP O
papilla NN I-NP O
fibrotic JJ I-NP O
, , I-NP O
suggestive JJ I-NP O
of IN B-PP O
passage NN B-NP O
of IN B-PP O
stones NNS B-NP O
. . O O
Narrative JJ B-NP O
History NN I-NP O
Here RB B-ADVP O
for IN B-PP O
f/u NN B-NP O
of IN B-PP O
multiple JJ B-NP O
medical JJ I-NP O
problems NNS I-NP O
. . O O
In IN B-PP O
brief JJ B-NP O
, , O O
complicated VBN B-VP O
60 CD B-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
w/ , O O
SLE NNP B-NP O
, , O O
CAD NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
DM NNP B-NP O
, , O O
multiple JJ B-NP O
histories NNS I-NP O
of IN B-PP O
joint JJ B-NP O
pain NN I-NP O
. . O O
She PRP B-NP O
now RB B-ADVP O
reports VBZ B-VP O
she PRP B-NP O
had VBD B-VP O
a DT B-NP O
piece NN I-NP O
of IN B-PP O
meat NN B-NP O
about IN B-PP O
a DT B-NP O
month NN I-NP O
ago RB B-ADVP O
and CC O O
since IN B-SBAR O
then RB B-ADVP O
has VBZ B-VP O
had VBN I-VP O
a DT B-NP O
"poking NN I-NP O
" `` I-NP O
sensation NN I-NP O
within IN B-PP O
her PRP$ B-NP O
proximal JJ I-NP O
oral JJ I-NP O
pharyngeal JJ I-NP O
space NN I-NP O
. . O O
She PRP B-NP O
notes VBZ B-VP O
odynophagia NNS B-NP O
which WDT B-NP O
she PRP B-NP O
localizes VBZ B-VP O
to TO B-PP O
the DT B-NP O
proximal JJ I-NP O
superior JJ I-NP O
throat NN I-NP O
and CC O O
describes VBZ B-VP O
being VBG I-VP O
hoarse JJ B-ADJP O
since IN B-PP O
the DT B-NP O
onset NN I-NP O
these DT B-NP O
symptoms NNS I-NP O
a DT B-NP O
month NN I-NP O
ago RB B-ADVP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
rhinnorhea NN B-NP O
but CC O O
has VBZ B-VP O
had VBN I-VP O
a DT B-NP O
sensation NN I-NP O
of IN B-PP O
nasal JJ B-NP O
congestion NN I-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
cough NN B-NP O
independent JJ B-ADJP O
or CC O O
during IN B-PP O
eating VBG B-NP O
, , O O
fevers NNS B-NP O
, , O O
night NN B-NP O
sweats VBZ B-VP O
, , O O
malaise NN B-NP O
, , O O
or CC O O
HA NNP B-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
a DT B-NP O
sensation NN I-NP O
of IN B-PP O
neck NN B-NP O
fullness RB B-ADVP O
on IN B-PP O
the DT B-NP O
left JJ I-NP O
side NN I-NP O
and CC O O
denies VBZ B-VP O
noting VBG I-VP O
any DT B-NP O
focal JJ I-NP O
swelling VBG I-NP O
, , I-NP O
rash NN I-NP O
, , I-NP O
or CC I-NP O
warmth NN I-NP O
. . O O
She PRP B-NP O
thinks VBZ B-VP O
she PRP B-NP O
has VBZ B-VP O
an DT B-NP O
intermittent NN I-NP O
pulsatile NN I-NP O
pain NN I-NP O
at IN B-PP O
the DT B-NP O
base NN I-NP O
of IN B-PP O
her PRP$ B-NP O
teeth NNS I-NP O
that WP B-NP O
is VBZ B-VP O
generalized VBN I-VP O
to TO B-PP O
the DT B-NP O
upper JJ I-NP O
jaw NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
N/V NNP I-NP O
, , I-NP O
abdominal JJ I-NP O
pain NN I-NP O
, , I-NP O
diarrhea NN I-NP O
or CC I-NP O
melena NN I-NP O
. . O O
In IN B-PP O
addition NN B-NP O
, , O O
she PRP B-NP O
considers VBZ B-VP O
her PRP$ B-NP O
functional JJ I-NP O
status NN I-NP O
to TO B-VP O
be VB I-VP O
at IN B-PP O
baseline NN B-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
chest NN B-NP O
pain NN I-NP O
, , O O
SOB NNP B-NP O
, , O O
DOE NNP B-NP O
, , O O
orthopnea NN B-NP O
or CC O O
PND. NNP B-NP O
Her PRP$ I-NP O
exertion NN I-NP O
is VBZ B-VP O
limited VBN I-VP O
to TO B-PP O
ambulation NN B-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
arthralgias NNS B-NP O
, , O O
new JJ B-NP O
rashes NNS I-NP O
, , O O
or CC O O
myalgias NNS B-NP O
. . O O
She PRP B-NP O
reports VBZ B-VP O
excellent JJ B-NP O
adherence NN I-NP O
to TO B-PP O
medications NNS B-NP O
. . O O
Allergies . O O
CELECOXIB NNP B-NP O
- : O O
SOB NN B-VP O
: : O O
" `` O O
that IN B-NP O
triggered VBD B-VP O
her PRP$ B-NP O
asthma NN I-NP O
" '' O O
Medications NNS B-NP O
Aspirin NNP B-NP O
(ACETYLSALICYLIC NN I-NP O
Acid NN I-NP O
) -RRB- I-NP O
81 CD I-NP O
MG NNP I-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Calcium NNP B-NP O
Gluconate NNP I-NP O
500MG . I-NP O
TABLET NNP I-NP O
take VBP B-VP O
2 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
x1 . O O
Vitamin NN B-NP O
D NNP I-NP O
( -LRB- I-NP O
ERGOCALCIFEROL NNP I-NP O
) -RRB- I-NP O
PO NNP I-NP O
QD . O O
Protonix NNP B-NP O
( -LRB- I-NP O
PANTOPRAZOLE NN I-NP O
) -RRB- I-NP O
40MG . I-NP O
TABLET NNP I-NP O
EC NNP I-NP O
take VBP B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD NNP I-NP O
x NNP I-NP O
30 CD I-NP O
days NNS I-NP O
Lipitor NNP B-NP O
( -LRB- I-NP O
ATORVASTATIN NNP I-NP O
) -RRB- I-NP O
20MG VBP I-NP O
TABLET NNP I-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD NNP I-NP O
x NNP I-NP O
90 CD I-NP O
days NNS I-NP O
HYDROXYCHLOROQUINE NNP B-NP O
200MG VBD B-VP O
TABLET NNP B-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
BID NNP I-NP O
x NNP I-NP O
30 CD I-NP O
days NNS I-NP O
Mycophenolate NNP B-NP O
Mofetil IN I-NP O
1000 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
500MG JJ I-NP O
TABLET NN I-NP O
take NN I-NP O
2 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
BID NNP I-NP O
x NNP I-NP O
30 CD I-NP O
days NNS I-NP O
PREDNISONE JJ B-NP O
10MG JJ I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD NNP I-NP O
x NNP I-NP O
30 CD I-NP O
days NNS I-NP O
GLIPIZIDE NNP B-NP O
5 CD I-NP O
MG NNP I-NP O
(5MG NNP I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
BID . O O
ATENOLOL NNP B-NP O
25MG NNP I-NP O
TABLET NNP I-NP O
PO NNP I-NP O
QD . O O
Fluoxetine NNP B-NP O
Hcl NNP I-NP O
20 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
20MG JJ I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
Iron NNP B-NP O
( -LRB- I-NP O
FERROUS NNP I-NP O
Sulfate NNP I-NP O
) -RRB- I-NP O
325 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
325(65)MG JJ I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
Colace NNP B-NP O
( -LRB- B-VP O
DOCUSATE VB I-VP O
Sodium NNP B-NP O
) -RRB- I-NP O
100 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
100MG JJ I-NP O
TABLET NN I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
Q12H . O O
LISINOPRIL NNP B-NP O
10 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
10MG JJ I-NP O
TABLET NN I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
Review NNP B-NP O
of IN I-NP O
Systems NNPS O O
Negative JJ B-ADJP O
in IN B-PP O
detail NN B-NP O
except IN B-PP O
as IN I-PP O
noted VBN B-NP O
in IN B-PP O
narrative NN B-NP O
above IN I-NP O
. . O O
Vital JJ B-NP O
Signs NNS I-NP O
BLOOD NN B-NP O
PRESSURE JJ I-NP O
192/94 CD O O
PULSE NNP B-NP O
72 CD I-NP O
RESPIRATORY NN B-NP O
RATE NN I-NP O
15 CD O O
WEIGHT NNP B-NP O
199 CD I-NP O
lb NN I-NP O
Physical NNP B-NP O
Exam NNP I-NP O
Cushingoid NNP B-NP O
habitus NN I-NP O
w/ NN I-NP O
moon NN I-NP O
facies NNS I-NP O
. . O O
Affect NN B-VP O
cheerful JJ B-ADJP O
; : O O
well RB B-NP O
groomed VBN I-NP O
today NN B-NP O
. . O O
HEENT NNP B-NP O
- : O O
PERRL NN B-NP O
, , O O
EOMI NNP B-NP O
. . I-NP O
Sclerae NNP I-NP O
anicteric JJ I-NP O
, , I-NP O
conjunctivae JJ I-NP O
pale JJ I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
sinus IN B-PP O
tenderness NN B-NP O
with IN B-PP O
palpation NN B-NP O
of IN B-PP O
maxillary NN B-NP O
sinuses NNS I-NP O
, , O O
radiating VBG B-VP O
to TO B-PP O
upper JJ B-NP O
jaw NN I-NP O
. . O O
There EX B-NP O
are VBP B-VP O
no DT B-NP O
masses NNS I-NP O
in IN B-PP O
neck NN B-NP O
. . O O
L NNP B-NP O
aspect NN I-NP O
of IN B-PP O
neck NN B-NP O
is VBZ B-VP O
assymetrically RB I-VP O
swollen VBN I-VP O
along IN B-PP O
border NN B-NP O
of IN B-PP O
proximal JJ B-NP O
sternocleidomastoid NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
tenderness NN B-NP O
when WRB B-ADVP O
pressing VBG B-VP O
the DT B-NP O
SCM. NNP I-NP O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
focal JJ I-NP O
area NN I-NP O
of IN B-PP O
associated JJ B-NP O
fluctuance NN I-NP O
, , O O
solid JJ B-NP O
mass NN I-NP O
, , O O
erythema NN B-NP O
, , O O
or CC O O
warmth NN B-NP O
. . O O
Chest NNP B-NP O
- : O O
CTA NNP B-NP O
B. NNP I-NP O
COR JJ O O
- : O O
RRR NN B-NP O
. . B-NP O
Nl NNP I-NP O
S1 NNP I-NP O
, , O O
S2 NNP B-NP O
, , O O
distant JJ B-NP O
. . O O
No DT B-NP O
MRG. NNP I-NP O
JVP NNP I-NP O
6 CD I-NP O
cm NN I-NP O
. . O O
Abd NNP B-NP O
- : O O
NABS NNP B-NP O
, , O O
TTP NNP B-NP O
generally RB B-ADVP O
with IN B-PP O
mild JJ B-NP O
pressure NN I-NP O
, , O O
no DT B-NP O
guarding VBG I-NP O
. . O O
Ext JJ O O
- : O O
No DT B-NP O
edema NN I-NP O
, , O O
cyanosis NN B-NP O
, , O O
clubbing VBG B-VP O
. . B-NP O
FROM NNP I-NP O
B. NNP I-NP O
Skin VB B-VP O
- : O O
slightly RB B-ADJP O
translucent JJ I-ADJP O
c/w NN B-NP O
chronic NN I-NP O
steroid NN I-NP O
use NN I-NP O
. . O O
Health NNP B-NP O
Maintenance NNP I-NP O
Influenza NNP B-NP O
Vaccine NNP I-NP O
11/05/2092 CD O B-DATE
Breast NN B-NP O
Exam NNP I-NP O
03/27/2090 CD I-NP B-DATE
Bil NNP I-NP O
fibrocystic JJ I-NP O
appearance NN I-NP O
without IN B-PP O
dominant JJ B-NP O
mass NN I-NP O
or CC I-NP O
nipple NN I-NP O
discharge NN I-NP O
. . O O
No DT B-NP O
axillary NN I-NP O
lymphadenopathy NN I-NP O
or CC I-NP O
assymetry NN I-NP O
. . O O
No DT B-NP O
skin NN I-NP O
changes NNS I-NP O
. . O O
Cholesterol NNP B-NP O
11/11/2092 CD I-NP B-DATE
117 CD I-NP O
DESIRABLE NNP I-NP O
: : O O
<200 CD O O
M-alb/creat JJ B-NP O
ratio NN I-NP O
10/16/2092 CD O B-DATE
10.4 CD O O
Mammogram NNP B-NP O
12/01/2092 CD I-NP B-DATE
see VBP B-VP O
report NN B-NP O
in IN B-PP O
Results NNS B-NP O
Pap NNP B-NP O
Smear NNP I-NP O
08/14/2091 JJS I-NP B-DATE
see VBP B-VP O
report NN B-NP O
in IN B-PP O
Results NNS B-NP O
UA-Protein NNP B-NP O
11/10/2092 CD I-NP B-DATE
1+SAMPLE JJ I-NP O
SENT NNP I-NP O
TO TO B-PP O
HEME NNP B-NP O
LAB NNP I-NP O
FOR IN B-PP O
ADDITIONAL NNP B-NP O
TESTING NNP I-NP O
Urine NNP B-NP O
Culture NNP I-NP O
11/10/2092 CD I-NP B-DATE
see VBP B-VP O
report NN B-NP O
in IN B-PP O
Results NNS B-NP O
Td DT B-NP O
Booster NNP I-NP O
10/15/2092 CD I-NP B-DATE
TD NNP B-NP O
113 CD I-NP O
Injected VBD B-VP O
to TO B-PP O
LUE. NNP B-NP O
Triglycerides NNS B-NP O
11/11/2092 CD B-NP B-DATE
90 CD I-NP O
Cholesterol-LDL NNP B-NP O
11/11/2092 CD I-NP B-DATE
62 CD I-NP O
DESIRABLE NNP I-NP O
: : O O
<130 CD O O
Microalbumin NNP B-NP O
10/16/2092 CD I-NP B-DATE
3.1 CD O O
Bone NNP B-NP O
Density NNP I-NP O
05/18/2091 JJS I-NP B-DATE
see VBP B-VP O
report NN B-NP O
in IN B-PP O
Results NNS B-NP O
Hct NNP B-NP O
( -LRB- I-NP O
Hematocrit NN I-NP O
) -RRB- I-NP O
11/13/2092 CD I-NP B-DATE
31.7 CD O O
Cholesterol-HDL NNP B-NP O
11/11/2092 CD I-NP B-DATE
37 CD O O
MHCT NNP B-NP O
( -LRB- I-NP O
micro-Hematocrit NN I-NP O
) -RRB- O O
09/26/8 CD B-NP I-DATE
1 CD I-NP I-DATE
29 CD O O
Hgb NNP B-NP O
( -LRB- I-NP O
Hemoglobin NNP I-NP O
) -RRB- I-NP O
11/13/2092 CD I-NP B-DATE
10.0 CD O O
HbA1c NN B-NP O
10/16/2092 CD I-NP B-DATE
6.90 CD O O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
1 LS O O
. . B-NP O
Odynophagia/hoarseness/swelling NNP I-NP O
. . O O
Constellation NNP B-NP O
of IN B-PP O
symptoms NNS B-NP O
concerning VBG B-VP O
for IN B-PP O
mass NN B-NP O
effect NN I-NP O
involving VBG B-VP O
soft JJ B-NP O
tissue NN I-NP O
. . O O
Ordering '' O O
neck NN B-NP O
CT NNP I-NP O
I+ NNP I-NP O
to TO B-VP O
examine VB I-VP O
for IN B-PP O
infiltrating JJ B-NP O
process NN I-NP O
. . O O
If IN B-SBAR O
unrevealing NN B-NP O
would MD B-VP O
proceed VB I-VP O
to TO B-PP O
barium NN B-NP O
swallow NN I-NP O
to TO B-VP O
evaluate VB I-VP O
odynophagia NN B-NP O
and CC I-NP O
hoarseness NN I-NP O
. . O O
She PRP B-NP O
will MD B-VP O
continue VB I-VP O
current JJ B-NP O
diet NN I-NP O
as IN B-PP O
sx NN B-NP O
do VBP B-VP O
not RB I-VP O
interfere VB I-VP O
with IN B-PP O
consumption NN B-NP O
. . O O
2. . O O
HTN. . O O
Chronic NNP B-NP O
problem NN I-NP O
. . O O
I PRP B-NP O
discontinued VBN B-VP O
isordil NN B-NP O
recently RB B-ADVP O
. . O O
Can MD O O
increase VB B-VP O
lisinopril NN B-NP O
to TO B-PP O
10 CD B-NP O
this DT B-NP O
visit NN I-NP O
and CC I-NP O
titrate NN I-NP O
thereafter RB B-ADVP O
. . O O
I PRP B-NP O
would MD B-VP O
favor VB I-VP O
addition NN B-NP O
of IN B-PP O
diuretic JJ B-NP O
, , O O
HCTZ NNP B-NP O
, , O O
for IN B-PP O
additional JJ B-NP O
management NN I-NP O
and CC O O
anticipate VB B-VP O
BP NNP B-NP O
mgmt NN I-NP O
will MD B-VP O
require VB I-VP O
further JJ B-NP O
polypharmacy NN I-NP O
. . O O
She PRP B-NP O
is VBZ B-VP O
returning VBG I-VP O
on IN B-PP O
2/2/93 CD B-NP B-DATE
and CC O O
will MD B-VP O
have VB I-VP O
NP NNP B-NP O
visit NN I-NP O
. . O O
3. . B-NP O
Musculoskeletal NNP I-NP O
pain/deconditioning NN I-NP O
. . O O
RLE NNP B-NP O
radiculopathy NN I-NP O
has VBZ B-VP O
resolved VBN I-VP O
fairly RB B-ADVP O
spontaneously RB I-ADVP O
, , O O
as IN B-NP O
did VBD B-VP O
the DT B-NP O
contralateral JJ I-NP O
presentation NN I-NP O
, , O O
without IN B-PP O
intervention NN B-NP O
. . O O
She PRP B-NP O
needs VBZ B-VP O
to TO B-PP O
recondition NN B-NP O
, , O O
increase NN B-NP O
range NN I-NP O
of IN B-PP O
motion NN B-NP O
and CC O O
physical JJ B-NP O
capacity NN I-NP O
in IN B-SBAR O
order NN O O
to TO B-VP O
improve VB I-VP O
stamina NN B-NP O
and CC I-NP O
strength NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
opted VBN I-VP O
not RB O O
to TO B-VP O
follow VB I-VP O
through IN B-PP O
with IN B-PP O
PT. NNP B-NP O
4 CD B-LST O
. . O O
CAD. '' O O
Cont NNP B-NP O
ASA NNP I-NP O
, , O O
statin NN B-NP O
, , O O
BB NNP B-NP O
, , O O
ACE. NNP B-NP O
5 CD B-LST O
. . O O
DM. '' O O
Cont NNP B-NP O
glipizide NN I-NP O
; : O O
continue VB B-VP O
ACE RB B-ADVP O
I PRP B-NP O
as RB B-ADVP O
above RB I-ADVP O
. . O O
BG NNP B-NP O
125 CD I-NP O
today NN B-NP O
. . O O
6 CD B-NP O
. . O O
Lupus NNP B-NP O
nephritis NN I-NP O
. . O O
Cr NNP B-NP O
stable NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
asked VBN I-VP O
me PRP B-NP O
to TO B-VP O
renew VB I-VP O
immunomodulatory JJ B-NP O
agents NNS I-NP O
but CC O O
I PRP B-NP O
would MD B-VP O
like VB I-VP O
to TO I-VP O
defer VB I-VP O
to TO B-PP O
rheumatology NN B-NP O
service NN I-NP O
. . O O
7. . O O
HCM. . O O
Stable NNP B-NP O
. . O O
Requesting NNP B-NP O
female NN I-NP O
provider NN I-NP O
to TO B-VP O
perform VB I-VP O
breast/pap NN B-NP O
. . O O
Scheduled '' O O
for IN B-PP O
2/2/93 CD B-NP B-DATE
. . O O
John NNP B-NP B-DOCTOR
V. NNP I-NP I-DOCTOR
Hood NNP I-NP I-DOCTOR
, , O O
MD . O O
Attending VBG B-NP O
note NN I-NP O
: : O O
Pt NNP B-NP O
discussed VBD B-VP O
with IN B-PP O
Dr NNP B-NP O
Hood NNP I-NP B-DOCTOR
, , O O
and CC O O
agree VB B-VP O
with IN B-PP O
his PRP$ B-NP O
evaluation NN I-NP O
and CC I-NP O
plan NN I-NP O
. . O O
Neck RB B-ADJP O
Sx JJ I-ADJP O
as IN B-PP O
described VBN B-NP O
. . O O
I PRP B-NP O
do VBP B-VP O
n't RB I-VP O
feel VB I-VP O
a DT B-NP O
mass NN I-NP O
or CC I-NP O
adenopathy NN I-NP O
, , O O
but CC O O
worth JJ B-NP O
further JJ I-NP O
evaluation NN I-NP O
with IN B-PP O
CT NNP B-NP O
, , O O
barium NN B-NP O
swallow NN I-NP O
if IN B-PP O
sx NN B-NP O
persist VBP B-VP O
. . B-NP O
BP NNP I-NP O
needs VBZ B-VP O
better JJR B-NP O
control NN I-NP O
, , O O
goal NN B-NP O
130/80 CD I-NP O
, , O O
addition NN B-NP O
diuretic JJ I-NP O
and CC I-NP O
increase NN I-NP O
in IN B-PP O
ACE-I NNP B-NP O
appropriate JJ I-NP O
. . O O
T. NNP B-NP B-DOCTOR
Quintela NNP I-NP I-DOCTOR
MD NNP I-NP O
