Record NNP B-NP O
date NN I-NP O
: : O O
2063-11-28 CD O B-DATE
HPI . O O
51 CD B-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
with IN B-PP O
MMP NNP B-NP O
comes VBZ B-VP O
to TO I-VP O
establish VB I-VP O
primary JJ B-NP O
care NN I-NP O
as IN B-SBAR O
she PRP B-NP O
is VBZ B-VP O
unhappy JJ B-ADJP O
with IN B-PP O
the DT B-NP O
cre NN I-NP O
she PRP B-NP O
is VBZ B-VP O
geting VBG I-VP O
at IN B-PP O
CityMemorial NNP B-NP B-HOSPITAL
. . O O
She PRP B-NP O
was VBD B-VP O
40 CD B-NP O
mislate NN I-NP O
to TO B-PP O
her PRP$ B-NP O
appt NN I-NP O
and CC I-NP O
time NN I-NP O
was VBD B-VP O
limited VBN I-VP O
. . O O
She PRP B-NP O
has VBZ B-VP O
multiple JJ B-NP O
medical JJ I-NP O
problems NNS I-NP O
for IN B-PP O
which WDT B-NP O
she PRP B-NP O
is VBZ B-VP O
on IN B-PP O
a DT B-NP O
variety NN I-NP O
of IN B-PP O
medications NNS B-NP O
, , O O
none NN B-NP O
o IN B-PP O
which WDT B-NP O
she PRP B-NP O
has VBZ B-VP O
taken VBN I-VP O
x1 CD B-NP O
month NN I-NP O
as IN B-SBAR O
she PRP B-NP O
ran VBD B-VP O
out IN B-PP O
of IN B-PP O
refills NNS B-NP O
. . O O
1 CD B-LST O
. . O O
CVA-She -RRB- O O
reports VBZ B-VP O
3-4 CD B-NP O
mos NN I-NP O
ago IN B-SBAR O
she PRP B-NP O
had VBD B-VP O
a DT B-NP O
stroke NN I-NP O
( -LRB- O O
she PRP B-NP O
was VBD B-VP O
told VBN I-VP O
there EX B-NP O
was VBD B-VP O
a DT B-NP O
clot NN I-NP O
in IN B-PP O
her PRP$ B-NP O
brain NN I-NP O
) -RRB- O O
which WDT B-NP O
left VBD B-VP O
the DT B-NP O
L NNP I-NP O
side NN I-NP O
of IN B-PP O
her PRP$ B-NP O
face NN I-NP O
paralyzed VBN B-VP O
and CC O O
some DT B-NP O
residual JJ I-NP O
weakness NN I-NP O
in IN B-PP O
her PRP$ B-NP O
LUE. NNP I-NP O
She PRP B-NP O
also RB B-ADVP O
notes VBZ B-VP O
her PRP$ B-NP O
handwriting NN I-NP O
has VBZ B-VP O
completely RB I-VP O
changed VBN I-VP O
since IN B-PP O
. . B-NP O
Since IN B-PP O
the DT B-NP O
stroke NN I-NP O
she PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
multiple JJ B-NP O
episodes NNS I-NP O
during IN B-PP O
which WDT B-NP O
her PRP$ B-NP O
tongue NN I-NP O
becomes VBZ B-VP O
very RB B-ADJP O
heavy JJ I-ADJP O
and CC O O
she PRP B-NP O
has VBZ B-VP O
difficulty NN B-NP O
speaking VBG I-NP O
( -LRB- B-VP O
distinctly RB B-ADJP O
different JJ I-ADJP O
from IN B-PP O
her PRP$ B-NP O
now RB I-NP O
mildly RB I-NP O
imapired JJ I-NP O
baseline NN I-NP O
) -RRB- I-NP O
At IN B-PP O
these DT B-NP O
times NNS I-NP O
she PRP B-NP O
feel VBP B-VP O
somewhat RB I-VP O
confused VBN I-VP O
and CC O O
her PRP$ B-NP O
L NNP I-NP O
vison NN I-NP O
seems VBZ B-VP O
blurry JJ B-ADJP O
. . O O
This DT B-NP O
has VBZ B-VP O
happened VBN I-VP O
4-5 CD B-NP O
times NNS I-NP O
and CC O O
lasts VBZ B-VP O
all DT B-NP O
day NN I-NP O
. . O O
er NN B-NP O
family NN I-NP O
has VBZ B-VP O
encouraged VBN I-VP O
her PRP$ B-NP O
to TO B-VP O
seek VB I-VP O
medical JJ B-NP O
care NN I-NP O
but CC O O
she PRP B-NP O
has VBZ B-VP O
refused VBN I-VP O
bc IN B-SBAR O
she PRP B-NP O
did VBD B-VP O
not RB I-VP O
think VB I-VP O
they PRP B-NP O
would MD B-VP O
do VB I-VP O
antyhing NN B-NP O
for IN B-PP O
her PRP B-NP O
. . O O
Of IN B-PP O
note NN B-NP O
, , O O
pt NN B-NP O
has VBZ B-VP O
not RB I-VP O
been VBN I-VP O
on IN B-PP O
ASA NNP B-NP O
as IN B-SBAR O
it PRP B-NP O
was VBD B-VP O
d/cd VBN I-VP O
when WRB B-ADVP O
she PRP B-NP O
changed VBD B-VP O
to TO I-VP O
celebrex VB I-VP O
. . B-NP O
Pt NNP I-NP O
also RB B-ADVP O
c/o VBD B-VP O
memory NN B-NP O
loss NN I-NP O
that WDT B-NP O
started VBD B-VP O
even RB B-ADVP O
before IN B-PP O
the DT B-NP O
CVA NNP I-NP O
. . O O
2. DT B-NP O
CAD-She NNP I-NP O
reports VBZ B-VP O
a DT B-NP O
h/o NN I-NP O
multiple JJ I-NP O
MIs NNS I-NP O
, , O O
incl VBG B-VP O
cardiac JJ B-NP O
cath NN I-NP O
x2 NNS I-NP O
, , O O
unknown JJ B-ADJP O
if IN B-SBAR O
she PRP B-NP O
had VBD B-VP O
intevention NN B-NP O
, , O O
she PRP B-NP O
thinks VBZ B-VP O
the DT B-NP O
last JJ I-NP O
was VBD I-NP O
about IN B-PP O
1 CD B-NP O
yr NN I-NP O
ago RB B-ADVP O
. . O O
She PRP B-NP O
has VBZ B-VP O
stable JJ B-NP O
3 CD I-NP O
pillow NN I-NP O
orthopnea NN I-NP O
. . O O
She PRP B-NP O
becomes VBZ B-VP O
SOB NNP B-NP O
when WRB B-ADVP O
she PRP B-NP O
climbs VBZ B-VP O
5 CD B-NP O
steps NNS I-NP O
and CC O O
gets VBZ B-VP O
SOB NNP B-NP O
sometimes RB B-ADVP O
when WRB B-ADVP O
she PRP B-NP O
walks VBZ B-VP O
, , O O
which WDT B-NP O
resolves VBZ B-VP O
ith IN B-PP O
rest NN B-NP O
, , O O
but CC O O
she PRP B-NP O
is VBZ B-VP O
able JJ B-ADJP O
to TO B-VP O
walk VB I-VP O
a DT B-NP O
fair JJ I-NP O
amt NN I-NP O
still RB B-ADVP O
( -LRB- B-VP O
cannot NN B-NP O
pin NN I-NP O
down IN B-PP O
how WRB B-NP O
much JJ I-NP O
) -RRB- I-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
CP CD B-NP O
with IN B-PP O
exertion NN B-NP O
, , O O
did VBD B-VP O
have VB I-VP O
CP CD B-NP O
with IN B-PP O
her PRP$ B-NP O
MIs NN I-NP O
. . O O
She PRP B-NP O
says VBZ B-VP O
smx NN B-NP O
she PRP B-NP O
has VBZ B-VP O
lower JJR B-NP O
and CC I-NP O
upper JJ I-NP O
extremity NN I-NP O
edema NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
not RB I-VP O
had VBN I-VP O
a DT B-NP O
recent JJ I-NP O
ETT. NNP I-NP O
3. DT B-NP O
DM-Pt NNP I-NP O
has VBZ B-VP O
been VBN I-VP O
on IN B-PP O
glucophage NN B-NP O
and CC O O
Humulin NNP B-NP O
70/30 CD I-NP O
100U CD I-NP O
in IN B-PP O
am VBP B-NP O
and CC O O
60 CD B-NP O
in IN B-PP O
pm NN B-NP O
, , O O
but CC O O
has VBZ B-VP O
not RB I-VP O
been VBN I-VP O
monitoring VBG I-VP O
her PRP$ B-NP O
BS NNP I-NP O
or CC I-NP O
taking VBG I-NP O
insulin NN I-NP O
for IN B-PP O
the DT B-NP O
past JJ I-NP O
month NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
all DT B-NP O
the DT I-NP O
necessary JJ I-NP O
equipment NN I-NP O
. . O O
She PRP B-NP O
says VBZ B-VP O
she PRP B-NP O
tries VBZ B-VP O
o IN B-PP O
monior JJR B-NP O
her PRP$ I-NP O
carb NN I-NP O
intake NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
gaining VBG I-VP O
weight NN B-NP O
, , O O
bout IN B-ADVP O
5 CD B-NP O
lbs NN I-NP O
in IN B-PP O
the DT B-NP O
past NN I-NP O
2 CD I-NP O
mos NNPS I-NP O
, , O O
and CC O O
notes NNS B-NP O
polydypsia NNS I-NP O
and CC O O
polyuria NN B-NP O
fo VB B-VP O
the DT B-NP O
past JJ I-NP O
2 CD I-NP O
weeks NNS I-NP O
. . O O
4 CD B-LST O
. . O O
HTN-has . B-VP O
not RB I-VP O
been VBN I-VP O
taking VBG I-VP O
Zestoretic JJ B-NP O
or CC I-NP O
Atenolol JJ I-NP O
x1 NN I-NP O
mo NN I-NP O
5 CD B-NP O
. . O O
Depression-Pt NNP B-NP O
has VBZ B-VP O
h/o VBN I-VP O
depression NN B-NP O
for IN B-PP O
which WDT B-NP O
she PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
medicated VBN I-VP O
in IN B-PP O
the DT B-NP O
past NN I-NP O
. . O O
She PRP B-NP O
currently RB B-VP O
feels VBZ I-VP O
she PRP B-NP O
has VBZ B-VP O
very RB B-NP O
depressed JJ I-NP O
mood NN I-NP O
, , O O
apathy RB B-ADVP O
, , O O
trouble NN B-NP O
sleeping NN I-NP O
and CC B-PP O
with IN B-PP O
memory NN B-NP O
tasks NNS I-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
SI/HI/AH. VBG I-VP O
6 CD B-LST O
. . O O
In IN B-PP O
terms NNS B-NP O
of IN B-PP O
health NN B-NP O
maintenance NN I-NP O
, , O O
her PRP$ B-NP O
last JJ I-NP O
PAP NNP I-NP O
was VBD B-VP O
2 CD B-NP O
yrs NNS I-NP O
ago RB B-ADVP O
as IN B-NP O
was VBD B-VP O
her PRP$ B-NP O
last JJ I-NP O
Mammo NNP I-NP O
. . O O
Her PRP$ B-NP O
last JJ I-NP O
HgA1C NNP I-NP O
is VBZ B-VP O
fr JJ B-NP O
199 CD I-NP O
as IN B-ADVP O
are VBP B-VP O
her PRP$ B-NP O
lipids NNS I-NP O
. . O O
PMH . O O
HTN . O O
IRDM . O O
CAD NN B-NP O
HX NN B-NP O
OF IN B-PP O
GASTRITIS NNP B-NP O
BY NNP I-NP O
UGIS NNP I-NP O
H NNP I-NP O
PYLORI NNP I-NP O
+ . O O
S/P NNP B-NP O
TAH NNP I-NP O
2/2 CD I-NP O
FIBROIDS NNS I-NP O
Depression NN B-NP O
CVA . O O
MEDS NNS B-NP O
ATENOLOL NNP B-NP O
50 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
QD NNP I-NP O
x NN I-NP O
30 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Azmacort NNP B-NP O
Inh NNP I-NP O
5 CD I-NP O
PUFF NNP I-NP O
AER NNP I-NP O
BID NNP I-NP O
x NN I-NP O
30 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Insulin NNP B-NP O
70/30 CD I-NP O
( -LRB- O O
HUMAN NNP B-NP O
) -RRB- I-NP O
50 CD I-NP O
U NNP I-NP O
SC NNP I-NP O
QAM NNP I-NP O
x NN I-NP O
30 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
GLUCOPHAGE NN B-NP O
500 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
BID NNP I-NP O
x NN I-NP O
30 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Claritin NNP B-NP O
D NNP I-NP O
10 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
QD NNP I-NP O
x NN I-NP O
30 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
LIPITOR NNP B-NP O
40 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
QD NNP I-NP O
x NN I-NP O
30 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
CELEBREX NNP B-NP O
100 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
QD NNP I-NP O
x NN I-NP O
30 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Humulin NNP B-NP O
70/30 CD I-NP O
30 CD I-NP O
UNITS NNS I-NP O
qpm IN B-PP O
x NN B-NP O
30 CD I-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Zestoretic NNP B-NP O
( -LRB- I-NP O
LISINOPRIL/HYDROCHLOROTHIAZIDE NNP I-NP O
) -RRB- I-NP O
20-12.5 CD I-NP O
, , I-NP O
1 CD I-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD NNP I-NP O
x NNP I-NP O
30 CD I-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Ranitidine NNP B-NP O
Hcl NNP I-NP O
150MG NNP I-NP O
, , O O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
BID NNP I-NP O
x NNP I-NP O
30 CD I-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Ecasa NNP B-NP O
( -LRB- I-NP O
ASPIRIN NNP I-NP O
Enteric NNP I-NP O
Coated NNP I-NP O
) -RRB- B-VP O
325MG JJ B-ADJP O
, , O O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NNP I-NP O
QD NNP I-NP O
x NN I-NP O
30 CD B-NP O
day NN I-NP O
ALLERGIES NNP B-NP O
NKDA NNP I-NP O
FAMILY NNP B-NP O
HISTORY NN I-NP O
Defered . O O
SOCIAL JJ B-NP O
HISTORY NN I-NP O
Currrently RB B-ADVP O
unemployed VBN O O
Sexual JJ B-NP O
History NN I-NP O
: : O O
defered VBN O O
ETOH/Drugs/Tab NNP B-NP O
:denies NNS I-NP O
. . O O
Quit NN B-NP O
tab NN I-NP O
20 CD B-NP O
yrs NNS I-NP O
ago IN O O
Nutrition NNP B-NP O
: : O O
tries VBZ B-VP O
to TO I-VP O
eat VB I-VP O
low JJ B-NP O
carb NN I-NP O
diet NN I-NP O
Exercise NN B-NP O
: : O O
walking VBG B-SBAR O
PHYSICAL NNP B-NP O
EXAM NNPS I-NP O
VS NNP B-NP O
: : O O
BP NNP B-NP O
172/100 CD I-NP O
HR NNP I-NP O
84 CD I-NP O
Wt NNP I-NP O
166 CD I-NP O
lbs NNS I-NP O
FS NNS I-NP O
347 CD O O
General NNP B-NP O
: : O O
Pleasant NNP B-NP O
in IN B-PP O
NAD NNP B-NP O
, , O O
facial JJ B-NP O
asymmetry NN I-NP O
HEENT NNP B-NP O
: : O O
PERRL. NNP B-NP O
EOMI NNP I-NP O
. . I-NP O
Oropharynx NNP I-NP O
clear JJ I-NP O
. . I-NP O
TMs NNP I-NP O
intact JJ I-NP O
. . O O
Fundi NNP B-NP O
could MD B-VP O
not RB I-VP O
be VB I-VP O
visualized VBN I-VP O
. . O O
Neck NNP B-NP O
: : O O
No DT B-NP O
JVD. NNP I-NP O
No DT B-NP O
thyromegaly NN I-NP O
. . B-PP O
No DT B-NP O
LAD. NNP I-NP O
No DT B-NP O
carotid NN I-NP O
bruits NNS I-NP O
. . O O
Cor NNP B-NP O
: : O O
RRR NNP B-NP O
, , O O
nl JJ B-NP O
S1S2 NNP I-NP O
, , O O
2/6 CD B-NP O
sys NNS I-NP O
M NNP B-NP O
at IN B-PP O
LUSB NNP B-NP O
Lungs NNP B-NP O
: : O O
CTA NNP B-NP O
b/l NN I-NP O
, , O O
no DT B-NP O
rales NNS I-NP O
, , O O
rhonchi NNP B-NP O
or CC O O
wheezes POS O O
Abd NNP B-NP O
: : O O
Soft NNP B-NP O
, , O O
NTND. NNP B-NP O
Normal NNP I-NP O
active JJ I-NP O
bowel NN I-NP O
sounds NNS I-NP O
. . O O
No DT B-NP O
hepatosplenomegaly NN I-NP O
. . O O
Breast/GYN NN B-NP O
: : O O
defered VBN B-VP O
. . O O
Ext NNP B-NP O
: : O O
No DT B-NP O
clubbing NN I-NP O
, , I-NP O
cyanosis NN I-NP O
or CC I-NP O
edema NN I-NP O
. . O O
Distal NNP B-NP O
pulses VBZ B-VP O
present JJ B-ADJP O
and CC I-ADJP O
symmetric JJ I-ADJP O
. . O O
Neuro NNP B-NP O
: : O O
A DT B-NP O
+ NN I-NP O
O NNP B-NP O
x3 CD I-NP O
. . O O
Cranial NNP B-NP O
nerve NN I-NP O
exam NN I-NP O
sig NN I-NP O
for IN B-PP O
L NNP B-NP O
sided VBD B-VP O
facial JJ B-NP O
hemiparesis NN I-NP O
, , O O
unable JJ B-ADJP O
to TO B-VP O
smile VB I-VP O
or CC I-VP O
raise VB I-VP O
eyebrow NN B-NP O
. . O O
o/w JJ B-NP O
cn NN I-NP O
II NNP I-NP O
, , I-NP O
III NNP I-NP O
, , I-NP O
IV NNP I-NP O
, , I-NP O
VI NNP I-NP O
intact JJ I-NP O
, , O O
VII/VII NNP B-NP O
I PRP B-NP O
intact JJ B-ADJP O
, , O O
IX NNP B-NP O
, , O O
X NNP B-NP O
,XI NNP I-NP O
intact JJ I-NP O
. . O O
Tongue NNP B-NP O
deviates NNS I-NP O
to TO B-PP O
R. NNP B-NP O
Strength NNP I-NP O
5/5 VBD B-VP O
throughout IN B-PP O
except IN B-PP O
LUE NNP B-NP O
extensors NNS I-NP O
4/5 VBD B-VP O
. . B-NP O
Sensation NNP I-NP O
: : O O
intact JJ B-NP O
to TO B-PP O
light JJ B-NP O
touch NN I-NP O
and CC O O
temp JJ B-ADJP O
throughout IN B-PP O
. . O O
DTR NNP B-NP O
's POS B-NP O
1+ JJ I-NP O
throughout IN I-NP O
, , O O
Babinski NNP B-NP O
difficult JJ I-NP O
to TO B-VP O
interpret VB I-VP O
2/2 DT B-NP O
very RB I-NP O
strong JJ I-NP O
withdrawal NN I-NP O
response NN I-NP O
(ticklish JJ I-NP O
) -RRB- I-NP O
. . O O
No DT B-NP O
nystagmus NN I-NP O
. . B-NP O
Normal JJ I-NP O
gait NN I-NP O
. . O O
A/P NNP B-NP O
51 CD I-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
with IN B-PP O
MMP NNP B-NP O
incl IN B-PP O
recent JJ B-NP O
CVA NNP I-NP O
, , O O
CAD NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
DM NNP B-NP O
, , O O
Depression NNP B-NP O
p/t , O O
transfer VB B-VP O
her PRP$ B-NP O
primary JJ I-NP O
care NN I-NP O
. . O O
1 LS O O
. . B-NP O
Neuro-h/o NNP I-NP O
recent JJ I-NP O
CVA NNS I-NP O
per IN B-PP O
pt NN B-NP O
report NN I-NP O
with IN B-PP O
residual JJ B-NP O
L NNP I-NP O
facial NN I-NP O
hemiparesis NN I-NP O
and CC O O
LUE NNP B-NP O
weakness NN I-NP O
, , O O
no DT B-NP O
records NNS I-NP O
available JJ B-ADJP O
. . O O
Concern NNP O O
that IN B-SBAR O
she PRP B-NP O
continues VBZ B-VP O
to TO I-VP O
have VB I-VP O
TIAs NNP B-NP O
, , O O
is VBZ B-VP O
high JJ B-NP O
risk NN I-NP O
for IN B-PP O
another DT B-NP O
CVA NNP I-NP O
. . O O
--head NN B-NP O
MRI NNP I-NP O
--ECASA NNP B-NP O
325 CD I-NP O
mg NN I-NP O
qd NN I-NP O
--referal JJ B-ADJP O
to TO B-PP O
Neurology NNP B-NP O
--instructed JJ B-NP O
pt NN I-NP O
to TO B-VP O
present VB I-VP O
to TO B-PP O
ER NNP B-NP O
if IN B-SBAR O
she PRP B-NP O
notes VBZ B-VP O
neurologic JJ B-NP O
sx NN I-NP O
. . O O
2. . B-NP O
CV-CAD NNP I-NP O
:h/o NNP I-NP O
MI NNP I-NP O
and CC O O
2 CD B-NP O
cardiac JJ I-NP O
caths NNS I-NP O
per IN B-PP O
pt NN B-NP O
, , O O
stable JJ B-NP O
othopnea NNP I-NP O
, , O O
exertional JJ B-NP O
dyspnea NN I-NP O
wich WDT B-NP O
may MD B-VP O
be VB I-VP O
aginal JJ B-ADJP O
equivalent JJ I-ADJP O
. . O O
HTN NNP B-NP O
: : O O
poorly RB B-VP O
conrolled VBN I-VP O
but CC O O
has VBZ B-VP O
not RB I-VP O
been VBN I-VP O
taking VBG I-VP O
meds NNS B-NP O
. . O O
--Will NNP B-NP O
try VBP B-VP O
to TO I-VP O
obtain VB I-VP O
records NNS B-NP O
fr IN B-PP O
OSH NNP B-NP O
of IN B-PP O
caths NNS B-NP O
--check NN B-NP O
EKG NN I-NP O
--check NN B-NP O
lipid VBD B-VP O
profile NN B-NP O
and CC I-NP O
LFTs NNS I-NP O
--Add JJ B-NP O
ECASA NNP I-NP O
, , O O
cont NN B-NP O
Lipitor NNP I-NP O
, , I-NP O
Atenolol NNP I-NP O
, , I-NP O
Lisinopril/HCTZ NNP I-NP O
--Monitor NN B-NP O
BP NNP I-NP O
closely RB B-LST O
--Will JJ B-NP O
need NN I-NP O
ETT NNP I-NP O
in IN B-PP O
the DT B-NP O
future NN I-NP O
3. DT B-NP O
Endocrine--DM NNP I-NP O
, , O O
FS NNS B-NP O
today NN I-NP O
347 CD B-NP O
, , O O
very RB B-NP O
lrge JJ I-NP O
insulin NN I-NP O
requirement NN I-NP O
but CC I-NP O
pt NN I-NP O
has VBZ B-VP O
been VBN I-VP O
extremely RB B-ADJP O
noncompliant JJ I-ADJP O
with IN B-PP O
insulin NN B-NP O
regimen NNS I-NP O
. . O O
--Cont JJ B-NP O
glucophage NN I-NP O
--Humulin NNP B-NP O
70/30 CD I-NP O
cut NN I-NP O
in IN B-PP O
half NN B-NP O
to TO B-PP O
50 CD B-NP O
in IN B-PP O
am VBP B-NP O
and CC O O
30 CD B-NP O
in IN B-PP O
pm NN B-NP O
for IN B-PP O
now RB B-NP O
. . O O
--Instructed JJ B-NP O
pt NN I-NP O
to TO B-VP O
take VB I-VP O
her PRP$ B-NP O
fasting JJ I-NP O
BS NNP I-NP O
in IN B-PP O
am VBP B-NP O
and CC O O
before IN B-PP O
dinner NN B-NP O
and CC O O
keep VB B-VP O
a DT B-NP O
careful JJ I-NP O
record NN I-NP O
. . O O
She PRP B-NP O
will MD B-VP O
increase VB I-VP O
her PRP$ B-NP O
Humulin NNP I-NP O
if IN B-SBAR O
her PRP B-NP O
BS NNP B-NP O
remains VBZ B-VP O
very RB B-ADJP O
high JJ I-ADJP O
. . O O
Reinforced NNP B-NP O
importance NN I-NP O
of IN B-PP O
tight JJ B-NP O
glucose NN I-NP O
control NN I-NP O
and CC O O
low JJ B-NP O
carb NN I-NP O
diet NN I-NP O
. . O O
--nutrition NN B-NP O
referal NN I-NP O
for IN B-PP O
diabetic JJ B-NP O
teaching NN I-NP O
--referal JJ B-ADJP O
to TO B-PP O
Bridget NNP B-NP B-DOCTOR
Jamieson NNP I-NP I-DOCTOR
NP NNP I-NP O
for IN B-PP O
diabetic JJ B-NP O
teaching NN I-NP O
and CC I-NP O
close NN I-NP O
follow VBP B-VP O
up IN B-ADVP O
of IN B-PP O
BS NNP B-NP O
--will JJ B-NP O
check NN I-NP O
HgA1C NNP I-NP O
, , O O
microalbuminuria NN B-NP O
, , O O
chem NN B-NP O
7 CD I-NP O
--pt NN B-NP O
will MD B-VP O
need VB I-VP O
optho NN B-NP O
and CC I-NP O
podiatry NN I-NP O
referal NN I-NP O
at IN B-PP O
next JJ B-NP O
visit NN I-NP O
4 LS O O
. . B-NP O
Depression--Pt NNP I-NP O
has VBZ B-VP O
sx VBN I-VP O
and CC O O
history NN B-NP O
of IN B-PP O
depression NN B-NP O
. . O O
Will MD B-VP O
start VB I-VP O
Celexa NNP B-NP O
20 CD I-NP O
mg NN I-NP O
qd NN I-NP O
and CC O O
follow VB B-VP O
closely RB O O
5 CD B-NP O
. . O O
Health NNP B-NP O
maint--will , O O
refer VBP B-VP O
for IN B-PP O
mammo NN B-NP O
at IN B-PP O
next JJ B-NP O
visit NN I-NP O
. . O O
Will MD B-VP O
perform VB I-VP O
PAP NNS B-NP O
and CC O O
full JJ B-NP O
breast NN I-NP O
exam NN I-NP O
at IN B-PP O
next JJ B-NP O
visit NN I-NP O
as RB B-ADJP O
wel JJ I-ADJP O
as IN B-PP O
obtain VBP B-VP O
close JJ B-NP O
sexual JJ I-NP O
history NN I-NP O
. . O O
Will MD B-VP O
check VB I-VP O
lipids NNS B-NP O
as IN B-PP O
above JJ B-ADJP O
. . O O
6 CD B-NP O
. . O O
F/u NNP B-NP O
in IN B-PP O
1 CD B-NP O
mo NN I-NP O
Ione NN B-NP B-DOCTOR
Kerr NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
== NN B-NP O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
Preceptor NNP B-NP O
's POS B-NP O
Note NNP I-NP O
== NNP I-NP O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
I PRP B-NP O
saw VBD B-VP O
and CC I-VP O
evaluated VBD I-VP O
the DT B-NP O
patient NN I-NP O
and CC O O
agree VB B-VP O
with IN B-PP O
Dr NNP B-NP O
Kerr NNP I-NP B-DOCTOR
's POS B-NP O
findings NNS I-NP O
and CC I-NP O
plan NN I-NP O
as IN B-SBAR O
documented VBN B-VP O
in IN B-PP O
her PRP$ B-NP O
note NN I-NP O
. . O O
Ursula NNP B-NP B-DOCTOR
Olivia NNP I-NP I-DOCTOR
Oconnell NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
