Record NNP B-NP O
date NN I-NP O
: : O O
2094-12-24 CD O B-DATE
SECTIONS NNS B-NP O
OF IN B-PP O
THIS DT B-NP O
NOTE JJ I-NP O
WERE NNP I-NP O
CREATED NNP I-NP O
WITH IN B-PP O
A DT B-NP O
'COPY JJ I-NP O
AND CC I-NP O
PASTE' JJ I-NP O
ACTION. NNP I-NP O
THESE NNP I-NP O
SECTIONS NNP I-NP O
MAY NNP I-NP O
NOT NNP I-NP O
HAVE NNP I-NP O
COPIED NNP I-NP O
COMPLETELY NNP I-NP O
. . I-NP O
PLEASE NNP I-NP O
USE NNP I-NP O
CAUTION NNP I-NP O
WHEN WRB B-ADVP O
RENDERING NNP B-NP O
CLINICAL NNP I-NP O
JUDGMENT NNP I-NP O
BASED NNP I-NP O
ON IN B-PP O
THE DT B-NP O
INFORMATION NN I-NP O
IN IN B-PP O
THIS NNP B-NP O
NOTE. NNP I-NP O
Urology NNP B-NP O
Consult NNP I-NP O
Note NN I-NP O
Patient NNP B-NP O
Name NN I-NP O
: : O O
Michael NNP B-NP B-PATIENT
Yee NNP I-NP I-PATIENT
PH NNP B-NP B-HOSPITAL
# # I-NP O
: : O O
69044681 CD O B-MEDICALRECORD
Date/Time NNP B-NP O
: : O O
12/24/94 CD B-NP B-DATE
; : O O
2:30 CD B-NP O
PM NNP I-NP O
Attending VBG B-VP O
: : O O
Dr. NNP B-NP O
Quintrell NNP I-NP B-DOCTOR
Ferreira NNP I-NP I-DOCTOR
CC NNP B-NP O
: : O O
presumed VBN B-VP O
UTI NNP B-NP O
in IN B-PP O
the DT B-NP O
setting NN I-NP O
of IN B-PP O
indwelling VBG B-NP O
B NNP I-NP O
ureteral NN I-NP O
stents NNS I-NP O
HPI NNP B-NP O
: : O O
77 CD B-NP B-AGE
M NNP I-NP O
w/ NNS I-NP O
multiple JJ I-NP O
medical JJ I-NP O
problems NNS I-NP O
including VBG B-VP O
muscular JJ B-NP O
dystrophy NN I-NP O
and CC I-NP O
B NNP I-NP O
ureteral NN I-NP O
obstruction NN I-NP O
( -LRB- I-NP O
diagnosed VBD B-VP O
10/93 CD B-NP B-DATE
in IN B-PP O
the DT B-NP O
setting NN I-NP O
of IN B-PP O
B NNP B-NP O
hydroureteronephrosis NN I-NP O
and CC I-NP O
ARF NN I-NP O
) -RRB- I-NP O
managed VBD B-VP O
initially RB B-ADVP O
with IN B-PP O
B NNP B-NP O
ureteral NN I-NP O
stents NNS I-NP O
( -LRB- O O
most RBS B-ADVP O
recently RB I-ADVP O
changed VBN B-NP O
2/26/94 CD I-NP B-DATE
) -RRB- I-NP O
, , O O
currently RB B-VP O
admitted VBN I-VP O
to TO B-PP O
the DT B-NP O
medical JJ I-NP O
service NN I-NP O
12/23/94 CD B-NP B-DATE
with IN B-PP O
FTT NNP B-NP O
, , I-NP O
anemia NN I-NP O
, , I-NP O
hyperkalemia NN I-NP O
, , O O
and CC O O
a DT B-NP O
presumed VBN B-VP O
UTI. . O O
He PRP B-NP O
was VBD B-VP O
brought VBN I-VP O
to TO B-PP O
the DT B-NP O
PH NNP I-NP B-HOSPITAL
ED NNP I-NP O
yesterday NN B-NP O
by IN B-PP O
his PRP$ B-NP O
wife NN I-NP O
, , O O
who WP B-NP O
noted VBD B-VP O
that IN B-SBAR O
he PRP B-NP O
was VBD B-VP O
lethargic JJ B-ADJP O
and CC O O
confused VBN B-VP O
for IN B-PP O
3 CD B-NP O
days NNS I-NP O
( -LRB- B-PP O
reportedly RB B-NP O
similar JJ I-NP O
to TO B-PP O
previous JJ B-NP O
UTI JJ I-NP O
presentations NNS I-NP O
) -RRB- I-NP O
. . O O
She PRP B-NP O
felt VBD B-VP O
that IN B-SBAR O
his PRP$ B-NP O
urine JJ I-NP O
output NN I-NP O
had VBD B-VP O
decreased VBN I-VP O
at IN B-PP O
home NN B-NP O
, , O O
and CC O O
that IN B-SBAR O
his PRP$ B-NP O
urine NN I-NP O
had VBD B-VP O
been VBN I-VP O
foul-smelling JJ B-ADJP O
for IN B-PP O
two CD B-NP O
days NNS I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
treated VBN I-VP O
empirically RB B-ADVP O
with IN B-PP O
levofloxacin NN B-NP O
and CC O O
transfused VBD B-VP O
2U JJ B-NP O
PRBC NNP I-NP O
for IN B-PP O
HCT NNP B-NP O
26 CD I-NP O
. . O O
His PRP$ B-NP O
Cr NNP I-NP O
was VBD B-VP O
elevated VBN I-VP O
at IN B-PP O
3.1 CD B-NP O
, , O O
and CC O O
his PRP$ B-NP O
K NNP I-NP O
was VBD B-VP O
6.4. DT B-NP O
He PRP B-NP O
was VBD B-VP O
admitted VBN I-VP O
to TO B-PP O
a DT B-NP O
telemetry NN I-NP O
bed NN I-NP O
on IN B-PP O
the DT B-NP O
medical JJ I-NP O
service NN I-NP O
for IN B-PP O
management NN B-NP O
of IN B-PP O
the DT B-NP O
above JJ I-NP O
issues NNS I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
been VBN I-VP O
hemodynamically RB B-ADJP O
stable JJ I-ADJP O
, , O O
and CC O O
his PRP$ B-NP O
only JJ I-NP O
subjective JJ I-NP O
complaint NN I-NP O
has VBZ B-VP O
been VBN I-VP O
general JJ B-NP O
malaise NN I-NP O
. . O O
We PRP B-NP O
are VBP B-VP O
consulted VBN I-VP O
with IN B-PP O
the DT B-NP O
question NN I-NP O
of IN B-PP O
whether IN I-PP O
his PRP$ B-NP O
stents NNS I-NP O
may MD B-VP O
be VB I-VP O
changed VBN I-VP O
during IN B-PP O
his PRP$ B-NP O
current JJ I-NP O
admission NN I-NP O
. . O O
PMH: NNP B-NP O
Duchenne&#8217 CD I-NP O
;s NNS I-NP O
muscular JJ B-NP O
dystrophy NN I-NP O
, , O O
COPD NNP B-NP O
( -LRB- I-NP O
2.5L JJ I-NP O
home NN I-NP O
O2 IN B-PP O
) -RRB- B-NP O
, , O O
IDDM NNP B-NP O
, , O O
recurrent JJ B-NP O
UTIs NNP I-NP O
w/ NN I-NP O
previous JJ B-NP O
Candida NNP I-NP O
tropicalis NN I-NP O
fungemia NN I-NP O
( -LRB- B-VP O
followed VBN I-VP O
by IN B-PP O
Dr. NNP B-NP O
Phoebe NNP I-NP B-DOCTOR
Abreu NNP I-NP I-DOCTOR
) -RRB- I-NP O
, , O O
B NNP B-NP O
ureteral NN I-NP O
obstruction NN I-NP O
s/p NN I-NP O
ureteral JJ I-NP O
stent NN I-NP O
placement NN I-NP O
, , O O
CAD NNP B-NP O
s/p VBD B-VP O
CABG NNP B-NP O
, , O O
PVD NNP B-NP O
, , O O
SZ NNP B-NP O
disorder NN I-NP O
, , O O
hyperkalemia NN B-NP O
secondary JJ I-NP O
to TO B-PP O
hyperaldosteronemia NN B-NP O
( -LRB- I-NP O
type NN I-NP O
III NNP I-NP O
RTA NNP I-NP O
) -RRB- I-NP O
, , O O
CRI NNP B-NP O
( -LRB- I-NP O
baseline NN I-NP O
1.5 CD I-NP O
) -RRB- O O
PSH NNP B-NP O
: : O O
CABG NNP B-NP O
; : O O
cystoscopy NN B-NP O
, , O O
B NNP B-NP O
RPG NNP I-NP O
, , O O
B NNP B-NP O
ureteral JJ I-NP O
stent NN I-NP O
placement NN I-NP O
11/93 CD I-NP B-DATE
; : O O
cystoscopy NN B-NP O
, , O O
B NNP B-NP O
ureteral NN I-NP O
stent NN I-NP O
change NN I-NP O
2/94 . O B-DATE
MED NNP B-NP O
: : O O
vancomycin NN B-NP O
, , I-NP O
ceftriaxone NN I-NP O
, , I-NP O
fluconazole NN I-NP O
, , I-NP O
lactulose NN I-NP O
, , I-NP O
senna NN I-NP O
, , I-NP O
kayexalate NN I-NP O
, , I-NP O
tramadol JJ I-NP O
, , I-NP O
sarna NN I-NP O
, , I-NP O
nystatin NN I-NP O
, , I-NP O
paxil NN I-NP O
, , I-NP O
lipitor NN I-NP O
, , I-NP O
lantus NN I-NP O
, , I-NP O
humalog NN I-NP O
ISS NNP I-NP O
, , I-NP O
keppra NN I-NP O
, , I-NP O
labetalol NN I-NP O
, , I-NP O
meclizine NN I-NP O
, , O O
prilosec NN B-NP O
ALL NNP B-NP O
: : O O
PCN NN B-NP O
PE NN B-NP O
: : O O
AVSS NNS B-NP O
NAD NNP B-NP O
; : O O
alert JJ B-NP O
, , I-NP O
responsive JJ I-NP O
, , I-NP O
and CC I-NP O
interactive JJ I-NP O
S/NT/ND NN B-NP O
Phallus NN B-NP O
uncircumcised JJ I-NP O
w/ NN I-NP O
easily RB B-NP O
retractible JJ I-NP O
foreskin NN I-NP O
; : O O
meatus NN B-NP O
WNL . O O
Testes NNP B-NP O
descended VBD B-VP O
bilaterally RB B-ADVP O
and CC I-ADVP O
nontender RB I-ADVP O
Foley NNP B-NP O
to TO I-NP O
gravity NN I-NP O
draining VBG B-VP O
clear JJ B-NP O
urine NN I-NP O
with IN B-PP O
sediment NN B-NP O
LABS NNP B-NP O
: : B-VP O
Chem7 FW B-NP O
( -LRB- I-NP O
12/24 CD I-NP B-DATE
) -RRB- I-NP O
&#8211 CD I-NP O
; : O O
137/6.0/108/16/8 CD B-NP O
3/2.7/79 CD I-NP O
CBC NNP B-NP O
( -LRB- I-NP O
12/24 CD I-NP B-DATE
) -RRB- I-NP O
&#8211 CD I-NP O
; : O O
6.4/33.4/233 CD O O
Coags NNS B-NP O
( -LRB- B-VP O
12/24 CD B-NP B-DATE
) -RRB- I-NP O
&#8211 CD I-NP O
; : O O
13/58/1.1 CD O O
U/A NNP B-NP O
( -LRB- I-NP O
12/23 CD I-NP B-DATE
) -RRB- I-NP O
&#8211 CD I-NP O
; : O O
305W CD B-NP O
, , O O
&gt NNP B-NP O
;100R NNP I-NP O
, , O O
tr NN B-NP O
LE JJ I-NP O
, , I-NP O
neg JJ I-NP O
NIT NNP I-NP O
, , O O
1+ JJ B-NP O
bac NN I-NP O
, , O O
+ JJ B-NP O
pro FW I-NP O
, , O O
lg NN B-NP O
heme NN I-NP O
UCx NN B-NP O
( -LRB- I-NP O
12/23 CD I-NP B-DATE
) -RRB- I-NP O
&#8211 CD I-NP O
; : O O
NGSF NN B-NP O
RADS NNP B-NP O
: : O O
CT NNP B-NP O
A/P NNP I-NP O
W/O NNP I-NP O
CONTRAST NNP I-NP O
&#8211 NNP I-NP O
; : O O
pending VBG B-NP O
A/P NNP B-NP O
: : O O
77 CD B-NP B-AGE
M NNP I-NP O
w/ NNS I-NP O
multiple JJ I-NP O
medical JJ I-NP O
problems NNS I-NP O
including VBG B-VP O
muscular JJ B-NP O
dystrophy NN I-NP O
and CC O O
B NNP B-NP O
ureteral NN I-NP O
obstruction NN I-NP O
, , O O
now RB B-VP O
admitted VBN I-VP O
w/ NNS B-NP O
ARF NN I-NP O
, , O O
hyperkalemia NN B-NP O
, , O O
anemia NN B-NP O
, , O O
and CC O O
a DT B-NP O
presumed VBN I-NP O
UTI. NNP I-NP O
His PRP$ I-NP O
U/A NNP I-NP O
and CC I-NP O
UCx NNP I-NP O
are VBP B-VP O
not RB I-VP O
overwhelmingly RB I-VP O
c/w VBD I-VP O
a DT B-NP O
UTI NNP I-NP O
, , O O
but CC O O
his PRP$ B-NP O
clinical JJ I-NP O
presentation NN I-NP O
was VBD B-VP O
reportedly RB O O
similar JJ B-ADJP O
to TO B-PP O
prior JJ B-NP O
UTI NNP I-NP O
presentations NNS I-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
being VBG I-VP O
managed VBN I-VP O
by IN B-PP O
ID. NNP B-NP O
His PRP$ I-NP O
ureteral JJ I-NP O
stents NNS I-NP O
were VBD B-VP O
last JJ B-NP O
changed VBN I-NP O
2/94 CD I-NP B-DATE
, , O O
but CC O O
he PRP B-NP O
has VBZ B-VP O
never RB I-VP O
obtained VBN I-VP O
a DT B-NP O
diagnosis NN I-NP O
for IN B-PP O
his PRP$ B-NP O
B NNP I-NP O
ureteral NN I-NP O
obstruction NN I-NP O
. . O O
His PRP$ B-NP O
abdominal JJ I-NP O
CT NN I-NP O
is VBZ B-VP O
pending VBG I-VP O
. . O O
He PRP B-NP O
remains VBZ B-VP O
clinically RB B-ADJP O
stable JJ I-ADJP O
, , O O
with IN B-PP O
significantly RB B-NP O
improved VBN I-NP O
cognition NN I-NP O
and CC I-NP O
awareness NN I-NP O
since IN B-PP O
admission NN B-NP O
. . O O
As IN B-PP O
such JJ B-ADJP O
, , O O
we PRP B-NP O
recommend VBP B-VP O
: : O O
--F/U JJ B-NP O
UCx NNP I-NP O
and CC I-NP O
ID NNP I-NP O
recs NNS I-NP O
, , O O
as IN B-SBAR O
you PRP B-NP O
are VBP B-VP O
doing VBG I-VP O
. . O O
--F/U JJ B-NP O
CT NNP I-NP O
A/P NNP I-NP O
to TO B-VP O
assess VB I-VP O
for IN B-PP O
recurrent JJ B-NP O
hydronephrosis NN I-NP O
. . O O
Depending VBG B-VP O
on IN B-PP O
the DT B-NP O
results NNS I-NP O
of IN B-PP O
this DT B-NP O
study NN I-NP O
, , O O
we PRP B-NP O
will MD B-VP O
consider VB I-VP O
ureteral JJ B-NP O
stent NN I-NP O
change NN I-NP O
vs. CC O O
staged VBD B-VP O
removal NN B-NP O
. . O O
Regardless RB B-ADVP O
of IN B-PP O
his PRP$ B-NP O
eventual JJ I-NP O
stent NN I-NP O
plan NN I-NP O
, , O O
he PRP B-NP O
should MD B-VP O
be VB I-VP O
medically RB I-VP O
cleared VBN I-VP O
for IN B-PP O
an DT B-NP O
operative JJ I-NP O
procedure NN I-NP O
, , O O
which WDT B-NP O
would MD B-VP O
entail VB I-VP O
stabilization NN B-NP O
of IN B-PP O
his PRP$ B-NP O
hyperkalemia NN I-NP O
prior RB B-ADVP O
to TO B-PP O
undergoing VBG B-NP O
anaesthesia NN I-NP O
. . O O
D/w NNP B-NP O
Dr. NNP I-NP O
Ferreira NNP I-NP B-DOCTOR
, , O O
who WP B-NP O
agrees VBZ B-VP O
with IN B-PP O
above JJ B-NP O
plan NN I-NP O
. . O O
Thank VB B-VP O
you PRP B-NP O
for IN B-PP O
allowing VBG B-VP O
us PRP B-NP O
to TO B-VP O
continue VB I-VP O
our PRP$ B-NP O
involvement NN I-NP O
in IN B-PP O
the DT B-NP O
care NN I-NP O
of IN B-PP O
this DT B-NP O
unfortunate JJ I-NP O
patient NN I-NP O
. . O O
Leo NNP B-NP B-DOCTOR
Richard NNP I-NP I-DOCTOR
Edward NNP I-NP I-DOCTOR
, , O I-DOCTOR
III NNP B-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
PGY-4 NN B-NP O
Urology NNP I-NP O
Consult NNP I-NP O
Resident NN I-NP O
