Record NNP B-NP O
date NN I-NP O
: : O O
2080-05-04 CD O B-DATE
Quin NNP B-NP B-PATIENT
is VBZ B-VP O
a DT B-NP O
69 CD I-NP B-AGE
y/o NN I-NP O
male NN I-NP O
with IN B-PP O
: : O O
Problems NNS B-NP O
Coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
: : O O
CABG NNP B-NP O
x2 CD I-NP O
vessels NNS I-NP O
, , O O
2/78 CD B-NP B-DATE
. . O O
Aortic JJ B-NP O
stenosis NN I-NP O
: : O O
AVR NNP B-NP O
2/78 CD I-NP B-DATE
/Dr NNP I-NP O
Bonilla NNP I-NP B-DOCTOR
Diabetes NNP B-NP O
mellitus NN I-NP O
: : O O
Dr NNP B-NP O
Ayala NNP I-NP B-DOCTOR
- : O O
Skiff NN B-NP B-HOSPITAL
Atrial NNP B-NP O
fibrillation NN I-NP O
Spinal JJ B-NP O
stenosis NN I-NP O
: : O O
C3-4;C5-6 NN B-NP O
; : O O
C7-T1 : O O
Medications NNS B-NP O
Asa NNP B-NP O
(ACETYLSALICYLIC NN I-NP O
ACID NNP I-NP O
) -RRB- I-NP O
81MG VBP I-NP O
TABLET NNP I-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Furosemide NNP B-NP O
40 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
40MG JJ I-NP O
TABLET NN I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
Metformin NNP B-NP O
500MG VBD B-VP O
TABLET NNP B-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
2 CD I-NP O
am VBP I-NP O
, , O O
1 CD B-NP O
pm NN I-NP O
, , O O
for IN B-PP O
blood NN B-NP O
sugar NN I-NP O
Lopressor NNP B-NP O
( -LRB- I-NP O
METOPROLOL JJ I-NP O
TARTRATE NN I-NP O
) -RRB- O O
50MG . B-NP O
TABLET NNP I-NP O
PO NNP I-NP O
TID NNP I-NP O
Lisinopril NNP B-NP O
5MG VBD B-VP O
TABLET NNP B-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Digoxin NNP B-NP O
125MCG CD I-NP O
TABLET NNP I-NP O
PO NNP I-NP O
QD . O O
Simvastatin NNP B-NP O
5MG VBD B-VP O
TABLET NNP B-NP O
PO NNP I-NP O
QHS . O O
Viagra NNP B-NP O
( -LRB- I-NP O
SILDENAFIL NN I-NP O
) -RRB- I-NP O
25 CD I-NP O
MG-50 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
50MG JJ I-NP O
TABLET NN I-NP O
) -RRB- I-NP O
PO NN I-NP O
x NN I-NP O
1 CD B-NP O
, , O O
Take VB B-VP O
1/2-1 JJ B-NP O
tab NN I-NP O
as IN B-PP O
directed VBN B-NP O
. . O O
Metrogel NNP B-NP O
0.75 CD I-NP O
% NN I-NP O
( -LRB- I-NP O
METRONIDAZOLE NNP I-NP O
) -RRB- I-NP O
1 CD I-NP O
APPLICATION NN I-NP O
TOP NNP I-NP O
BID NNP I-NP O
Warfarin NNP B-NP O
SODIUM NNP I-NP O
5 CD I-NP O
MG NNP I-NP O
(5MG NNP I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NNP I-NP O
QPM NNP I-NP O
, , O O
Takes NNP B-NP O
total NN I-NP O
of IN B-PP O
6.5 CD B-NP O
mg NN I-NP O
QD. . O O
Warfarin NNP B-NP O
SODIUM NNP I-NP O
1.5 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
1MG JJ I-NP O
TABLET NN I-NP O
) -RRB- I-NP O
PO NN I-NP O
QPM NNP I-NP O
, , O O
Takes VBZ B-VP O
1.5MG VBG I-VP O
along IN B-PRT O
w/ DT B-NP O
5MG JJ I-NP O
tab NN I-NP O
for IN B-PP O
total JJ B-NP O
of IN B-PP O
6.5 CD B-NP O
mg JJ I-NP O
daily JJ I-NP O
. . O O
Alprazolam NNP B-NP O
0.25 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
0.5MG NN I-NP O
TABLET NN I-NP O
take NN I-NP O
0.5 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QHS NNP I-NP O
PRN NNP I-NP O
Allergies . O O
NKA . O O
He PRP B-NP O
has VBZ B-VP O
some DT B-NP O
chronic JJ I-NP O
complaints NNS I-NP O
. . O O
Itchy JJ B-NP O
throat NN I-NP O
and CC O O
runny JJ B-NP O
nose NN I-NP O
. . O O
No DT B-NP O
runny NN I-NP O
, , O O
ithcy RB B-ADVP O
eyes NNS B-NP O
. . O O
Cor- NNP B-NP O
No DT B-NP O
SOB NNP I-NP O
with IN B-PP O
walking VBG B-NP O
but CC O O
with IN B-PP O
heavy JJ B-NP O
lifting NN I-NP O
. . O O
No DT O O
palpitations NNPS B-NP O
. . O O
No DT B-NP O
lighthead NN I-NP O
. . B-PP O
No DT B-NP O
PND. NNP I-NP O
No DT B-NP O
orthopnea NN I-NP O
. . O O
No DT B-NP O
claudication NN I-NP O
. . O O
No DT B-NP O
edema NN I-NP O
. . B-PP O
No DT B-NP O
nausea NN I-NP O
Has VBZ B-NP O
had VBD B-VP O
chest NN B-NP O
pain NN I-NP O
since IN B-PP O
heart NN B-NP O
surgery NN I-NP O
. . O O
Not RB B-VP O
related VBN I-VP O
to TO B-PP O
activity NN B-NP O
. . O O
Always RB B-ADJP O
present JJ I-ADJP O
. . O O
Has VBZ B-VP O
MIBI NNP B-NP O
schedueld NN I-NP O
for IN B-PP O
5/8 CD B-NP I-DATE
0 CD I-NP I-DATE
. . O O
2. DT B-NP O
DM- NNP I-NP O
home NN I-NP O
gou NN I-NP O
120-150 CD I-NP O
. . O O
Followed NNP O O
at IN B-PP O
Skiff NNP B-NP B-HOSPITAL
. . O O
Endocrine NNP B-NP O
: : O O
No DT B-NP O
polydipsia NN I-NP O
, , O O
polyphagia NN B-NP O
, , O O
weight NN B-NP O
change NN I-NP O
, , O O
sweats VBZ B-VP O
,heat NN B-NP O
intolerance IN B-PP O
.Stable JJ B-NP O
nocturia NN I-NP O
x3 NN I-NP O
. . O O
GI- -RRB- O O
No DT B-NP O
nausea NN I-NP O
. . O O
No DT B-NP O
vomitting NN I-NP O
. . O O
No DT B-NP O
dyspepsia NN I-NP O
. . O O
No DT B-NP O
reflux NN I-NP O
. . B-PP O
No DT B-NP O
abdo NN I-NP O
pain NN I-NP O
. . O O
No DT B-NP O
diarrhea NN I-NP O
. . O O
No DT B-NP O
constipation NN I-NP O
. . O O
No DT B-NP O
melena NN I-NP O
. . O O
No DT B-NP O
BRBPR NN I-NP O
. . O O
3. VBG B-PP O
With IN B-PP O
persistent JJ B-NP O
neck NN I-NP O
an DT B-NP O
dright NN I-NP O
shoulder NN I-NP O
pain NN I-NP O
. . O O
4 LS O O
. . B-NP O
Anxious. NNP I-NP O
, , O O
Verys RB B-VP O
stressed/tensed VBN I-VP O
. . O O
With IN B-SBAR O
depression.Memory NN B-NP O
is VBZ B-VP O
not RB O O
as RB B-ADJP O
good JJ I-ADJP O
. . O O
Alprazolam NNP B-NP O
is VBZ B-VP O
very RB B-ADJP O
helpful JJ I-ADJP O
. . O O
Flowsheets NNS B-NP O
BLOOD NN B-NP O
PRESSURE JJ I-NP O
102/70 CD O O
PULSE NNP B-NP O
76 CD I-NP O
WEIGHT NNP B-NP O
203 CD I-NP O
lb NN I-NP O
WD NNP B-NP O
,WN,NAD NN I-NP O
Neck NNP B-NP O
- : O O
limited JJ B-NP O
lateral JJ I-NP O
movment NN I-NP O
. . O O
No DT B-NP O
JVD. NNP I-NP O
No DT B-NP O
bruit NN I-NP O
. . O O
No DT B-NP O
LAN. NNP I-NP O
No NNP I-NP O
thyromegaly . O O
Shoulder- NNP B-NP O
limted VBD B-VP O
ROM NNP B-NP O
right JJ I-NP O
shoulder NN I-NP O
with IN B-PP O
pain NN B-NP O
. . O O
Pulm NNP B-NP O
- : O O
NO DT B-NP O
accessory JJ I-NP O
muscle NN I-NP O
use NN I-NP O
. . B-NP O
Percussion NN I-NP O
- : O O
normal JJ B-NP O
. . B-NP O
Palpation-soreness NNP I-NP O
anterior JJ I-NP O
chest NN I-NP O
. . O O
Auscultation-clear JJ B-ADJP O
. . O O
Cor- NNP B-NP O
reg NNP I-NP O
rhyhm NNP I-NP O
. . I-NP O
S1S2 NNP I-NP O
normal JJ I-NP O
. . O O
No DT B-NP O
gallop NN I-NP O
. . O O
No DT B-NP O
rub NN I-NP O
. . O O
NO DT B-NP O
murmer NN I-NP O
. . O O
Abdo NNP B-NP O
- : O O
normal JJ B-NP O
BS NNP B-NP O
;soft NNP I-NP O
with IN B-PP O
no DT B-NP O
HSM. NNP I-NP O
No DT B-NP O
mass NN I-NP O
. . B-PP O
No DT B-NP O
tenderness NN I-NP O
ASS NNP B-NP O
: : O O
Frozen VBN B-VP O
right JJ B-NP O
shoulder NN I-NP O
. . O O
OA-neck NNP B-NP O
and CC I-NP O
shoulder NN I-NP O
Anxiety/tension/depression NN B-NP O
P- NNP B-NP O
ROM NNP I-NP O
exercsies NNS I-NP O
. . O O
Educ NNP B-NP O
re NN I-NP O
: : O O
neck NN B-NP O
and CC I-NP O
shoulder NN I-NP O
. . O O
Discussed VBN B-NP O
adaptation NN I-NP O
ot IN B-PP O
age NN B-NP O
change NN I-NP O
and CC I-NP O
health NN I-NP O
problems NNS I-NP O
. . O O
For IN B-PP O
now RB B-ADVP O
, , O O
take VB B-VP O
alprazolam NN B-NP O
BID NNP I-NP O
PRN NNP I-NP O
since IN B-PP O
this DT B-NP O
seems VBZ B-VP O
to TO I-VP O
be VB I-VP O
helpful JJ B-ADJP O
. . O O
More JJR B-NP O
than IN I-NP O
50 CD I-NP O
% NN I-NP O
of IN B-PP O
25 CD B-NP O
min NN I-NP O
spent VBN B-VP O
discussing VBG I-VP O
this DT B-NP O
. . O O
