Record NNP B-NP O
date NN I-NP O
: : O O
2097-11-06 CD O B-DATE
History NN B-NP O
of IN B-PP O
Present NNP B-NP O
Illness NNP I-NP O
Asked VBN B-VP O
by IN B-PP O
Dr. NNP B-NP O
Ehlers NNS I-NP B-DOCTOR
to TO B-VP O
consult VB I-VP O
on IN B-PP O
glycemic JJ B-NP O
management NN I-NP O
for IN B-PP O
Mr. NNP B-NP O
Ulysses NNP I-NP B-PATIENT
Ehlers NNP I-NP I-PATIENT
who WP B-NP O
has VBZ B-VP O
no DT B-NP O
history NN I-NP O
of IN B-PP O
DM NNP B-NP O
but CC O O
was VBD B-VP O
noted VBN I-VP O
to TO I-VP O
be VB I-VP O
hyperglycemic JJ B-NP O
postop NN I-NP O
. . O O
Mr. NNP B-NP O
Ehlers NNP I-NP B-PATIENT
is VBZ B-VP O
POD NNP B-NP O
1 CD I-NP O
, , O O
s/p JJ B-NP O
C4 NNP I-NP O
. . O O
His PRP$ B-NP O
family NN I-NP O
history NN I-NP O
is VBZ B-VP O
positive JJ B-ADJP O
for IN B-PP O
diabetes NNS B-NP O
( -LRB- B-NP O
mother NN I-NP O
diagnosed VBD B-VP O
in IN B-PP O
her PRP$ B-NP O
80s NNS I-NP B-AGE
) -RRB- I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
required VBN I-VP O
a DT B-NP O
regular JJ I-NP O
insulin NN I-NP O
gtt NN I-NP O
protocol NN I-NP O
intermittently RB B-ADJP O
postop JJ I-ADJP O
. . O O
He PRP B-NP O
is VBZ B-VP O
now RB B-ADVP O
on IN B-PP O
a DT B-NP O
full JJ I-NP O
liquid NN I-NP O
diet NN I-NP O
. . O O
Max NNP B-NP O
BG NNP I-NP O
: : O O
197 CD O O
Current JJ B-NP O
BG NNP I-NP O
: : O O
145 CD O O
Insulin NNP B-NP O
gtt VBD B-VP O
off RP B-PRT O
at IN B-NP O
present NN I-NP O
Mr. NNP B-NP O
Ehlers NNP I-NP B-PATIENT
is VBZ B-VP O
a DT B-NP O
69 CD I-NP B-AGE
yo NNP I-NP O
M NNP I-NP O
h/o , O O
CAD NNP B-NP O
s/p VBD B-VP O
MI NNP B-NP O
2084 CD I-NP B-DATE
( -LRB- I-NP O
posterolateral NN I-NP O
) -RRB- I-NP O
, , I-NP O
HTN NNP I-NP O
, , I-NP O
hyperlipidemia NN I-NP O
, , I-NP O
a-fib NN I-NP O
, , O O
AAA NNP B-NP O
, , O O
PVD NNP B-NP O
, , O O
smoking NN B-NP O
( -LRB- I-NP O
50 CD I-NP O
pk NN I-NP O
yr NN I-NP O
) -RRB- O O
who WP B-NP O
presents VBZ B-VP O
for IN B-PP O
CABG. NNP B-NP O
Initially RB B-ADVP O
presented VBD B-VP O
to TO B-PP O
Bonner NNP B-NP B-HOSPITAL
General NNP I-NP I-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
9/97 VBD B-VP B-DATE
for IN B-PP O
w/u NN B-NP O
of IN B-PP O
exertional JJ B-NP O
chest NN I-NP O
pain NN I-NP O
. . O O
Cardiac NNP B-NP O
cath NN I-NP O
was VBD B-VP O
unsuccessful JJ B-ADJP O
via IN B-PP O
femoral JJ B-NP O
approach NN I-NP O
due JJ B-ADJP O
to TO B-PP O
presumed VBN B-NP O
aortoiliac JJ I-NP O
occlusion NN I-NP O
. . O O
Subsequent JJ B-NP O
cath NN I-NP O
10/18/97 CD B-NP B-DATE
revealed VBD B-VP O
left VBN I-VP O
main JJ B-NP O
stenosis NN I-NP O
with IN B-PP O
distal JJ B-NP O
occlusion NN I-NP O
, , O O
RCA NNP B-NP O
proximal JJ I-NP O
occlusion NN I-NP O
and CC O O
diffuse JJ B-NP O
LAD NN I-NP O
stenosis NN I-NP O
. . O O
Pt NNP B-NP O
was VBD B-VP O
transferred VBN I-VP O
to TO B-PP O
BHCC NNP B-NP B-HOSPITAL
on IN B-PP O
10/19 CD B-NP B-DATE
for IN B-PP O
further JJ B-NP O
evaluation NN I-NP O
by IN B-PP O
the DT B-NP O
cardiology NN I-NP O
service NN I-NP O
. . O O
On IN B-PP O
10/21 CD B-NP B-DATE
he PRP I-NP O
underwent IN B-PP O
echo NN B-NP O
which WDT B-NP O
revealed VBD B-VP O
EF JJ B-NP O
55 CD I-NP O
% NN I-NP O
with IN B-PP O
mild JJ B-NP O
AS. NNP I-NP O
On IN B-PP O
10/22 CD B-NP B-DATE
, , O O
cardiac JJ B-NP O
cath NN I-NP O
revealed VBD B-VP O
3 CD B-NP O
V NNP I-NP O
disease NN I-NP O
. . O O
Cardiac NNP B-NP O
surgery NN I-NP O
was VBD B-VP O
consulted VBN I-VP O
and CC O O
recommended VBN B-VP O
CABG NNP B-NP O
after IN B-PP O
medical JJ B-NP O
optimization NN I-NP O
. . O O
His PRP$ B-NP O
anginal JJ I-NP O
symptoms NNS I-NP O
remained VBD B-VP O
stable JJ B-ADJP O
and CC O O
he PRP B-NP O
was VBD B-VP O
subsequently RB I-VP O
discharged VBN I-VP O
home NN B-NP O
on IN B-PP O
10/23 CD B-NP B-DATE
. . O O
He PRP B-NP O
now RB B-ADVP O
returns VBZ B-VP O
for IN B-PP O
surgical JJ B-NP O
revascularization NN I-NP O
. . O O
Since IN B-PP O
his PRP$ B-NP O
discharge NN I-NP O
on IN B-PP O
10/23 CD B-NP B-DATE
, , O O
he PRP B-NP O
has VBZ B-VP O
not RB I-VP O
experienced VBN I-VP O
any DT B-NP O
new JJ I-NP O
or CC I-NP O
worsening VBG I-NP O
chest NN I-NP O
pain NN I-NP O
or CC I-NP O
SOB. NNP I-NP O
Denies NNS I-NP O
orthopnea NN I-NP O
, , O O
PND. . O O
Preoperative JJ B-NP O
Cardiac NNP I-NP O
Status NNP I-NP O
: : O O
Myocardial JJ B-NP O
infarction NN I-NP O
2084 CD B-NP B-DATE
, , O O
requiring VBG B-VP O
hospitalization NN B-NP O
. . O O
Myocardial '' O O
infarction NN B-NP O
2084 CD I-NP B-DATE
, , O O
requiring VBG B-VP O
hospitalization NN B-NP O
. . B-PP O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
class NN B-NP O
I PRP B-NP O
angina MD B-VP O
( -LRB- I-VP O
no DT B-NP O
limitation NN I-NP O
of IN B-PP O
ordinary JJ B-NP O
physical JJ I-NP O
activity NN I-NP O
) -RRB- I-NP O
. . O O
There EX B-NP O
has VBZ B-VP O
been VBN I-VP O
no DT B-NP O
recent JJ I-NP O
angina NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
does VBZ B-VP O
not RB I-VP O
have VB I-VP O
symptomatic JJ B-NP O
heart NN I-NP O
failure NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
in IN B-PP O
normal JJ B-NP O
sinus NN I-NP O
rhythm NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
AF/flutter NN B-NP O
Previous JJ B-NP O
Cardiovascular NNP I-NP O
Interventions NNS I-NP O
: : O O
None NN B-NP O
. . O O
Past NNP B-NP O
Medical NNP I-NP O
History NNP I-NP O
: : O O
Hypertension NNP B-NP O
. . I-NP O
Peripheral NNP I-NP O
vascular JJ I-NP O
disease NN I-NP O
3.6cm VBZ B-VP O
abdominal JJ B-NP O
aortic JJ I-NP O
aneurysm NN I-NP O
. . O O
Dyslipidemia NNP O O
. . O O
CAD NNP B-NP O
Atrial NNP I-NP O
fibrillation NN I-NP O
BPH NNP I-NP O
Chronic NNP I-NP O
back RB I-NP O
pain NN I-NP O
PVD NNP I-NP O
Bicuspid NNP I-NP O
aortic JJ I-NP O
valve NN I-NP O
, , O O
mild JJ B-ADJP O
AS/A IN B-SBAR O
I PRP B-NP O
/Creatinine VBP B-VP O
Clearance NN B-NP O
(estimate NN I-NP O
) -RRB- I-NP O
: : O O
77.31 CD B-NP O
cc/min NN I-NP O
Past NNP B-NP O
Surgical NNP I-NP O
History NNP I-NP O
: : O O
s/p NN B-NP O
R NN I-NP O
inguinal JJ I-NP O
hernia NN I-NP O
repair NN I-NP O
Family NNP B-NP O
History NNP I-NP O
: : O O
Coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
. . O O
Father NNP B-NP O
died VBD B-VP O
of IN B-PP O
CAD NN B-NP O
at IN B-PP O
age NN B-NP O
88 CD I-NP B-AGE
Social NNP B-NP O
History NNP I-NP O
: : O O
History NN B-NP O
of IN B-PP O
tobacco NN B-NP O
use NN I-NP O
. . O O
50 CD B-NP O
pack NN I-NP O
year NN I-NP O
cigarette NN I-NP O
smoking NN I-NP O
history NN I-NP O
. . O O
Used '' O O
within IN B-PP O
the DT B-NP O
last JJ I-NP O
year NN I-NP O
. . O O
History NN B-NP O
of IN B-PP O
alcohol NN B-NP O
use NN I-NP O
. . O O
1/month '' O O
. . O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
a DT B-NP O
Cardiology NNP I-NP B-PROFESSION
Technologist NNP I-NP I-PROFESSION
. . O O
Allergies NNP B-NP O
: : O O
Flecanide NNP B-NP O
- : O O
unknown JJ O O
Medications NNS B-NP O
: : O O
lopressor NN B-NP O
50 CD I-NP O
po NN I-NP O
bid NN I-NP O
/ IN B-PP O
ramipril NNP B-NP O
10 CD I-NP O
po NN I-NP O
daily JJ I-NP O
/ NNP I-NP O
aspirin NN I-NP O
325 CD B-NP O
po NN I-NP O
daily JJ I-NP O
/ NNS I-NP O
atorvastatin IN B-PP O
80 CD B-NP O
po JJ I-NP O
daily JJ I-NP O
/ NN I-NP O
ezetimbe VBD B-VP O
10 CD B-NP O
po NN I-NP O
daily RB B-ADVP O
/ . O O
Physical NNP B-NP O
Exam NNP I-NP O
100.3-107-18 CD B-NP O
99 CD I-NP O
% NN I-NP O
on IN B-PP O
4L JJ B-NP O
155/65 CD I-NP O
Neuro NNP B-NP O
: : O O
A&O NNP B-NP O
x3 CD I-NP O
Edema NNP B-NP O
: : O O
+BLE JJ B-NP O
edema NN I-NP O
Lab NNP B-NP O
Tests NNS I-NP O
A1c JJ B-NP O
6.6 CD I-NP O
Cr NNP B-NP O
1.2 CD I-NP O
WBC NNP B-NP O
10.5 CD I-NP O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
Hyperglycemia NNP B-NP O
uncontrolled JJ I-NP O
in IN B-PP O
the DT B-NP O
setting NN I-NP O
of IN B-PP O
surgery/stress/inactivity NN B-NP O
with IN B-PP O
no DT B-NP O
history NN I-NP O
of IN B-PP O
DM NNP B-NP O
and CC O O
c/w VBD B-VP O
impaired VBN I-VP O
glucose NN B-NP O
tolerance NN I-NP O
. . O O
Regardless RB O O
of IN B-PP O
etiology NN B-NP O
this DT B-NP O
pt NN I-NP O
will MD B-VP O
benefit VB I-VP O
from IN B-PP O
tight JJ B-NP O
glycemic JJ I-NP O
control NN I-NP O
. . O O
Suggest NNP B-NP O
: : O O
1 CD B-NP O
. . O O
Nutrition NNP O O
consult VB B-VP O
for IN B-PP O
carbohydrate NN B-NP O
consistent JJ I-NP O
diet NN I-NP O
when WRB B-ADVP O
eating NN B-NP O
. . O O
2. DT B-NP O
Insulin NNP I-NP O
gtt NNP I-NP O
protocol NN I-NP O
until IN B-PP O
POD NNP B-NP O
# # I-NP O
3 CD I-NP O
or CC I-NP O
eating VBG I-NP O
AND CC I-NP O
POD NN I-NP O
2 LS I-NP O
then RB B-ADVP O
can MD B-NP O
trial NN I-NP O
Novolog NNP B-NP O
SS NNP I-NP O
as IN B-PP O
below RB B-NP O
. . O O
Restart VB B-VP O
insulin NN B-NP O
gtt NN I-NP O
protocol NN I-NP O
for IN B-PP O
BG>150 CD B-NP O
. . O O
3. DT B-NP O
Novolog NNP I-NP O
SS NNP I-NP O
ac NN I-NP O
Give VB B-VP O
when WRB B-NP O
meal NN I-NP O
in IN B-PP O
front NN B-NP O
of IN B-PP O
pt NN B-NP O
. . O O
4 CD B-LST O
. . O O
We PRP B-NP O
will MD B-VP O
follow VB I-VP O
. . O O
Thank VB B-VP O
you PRP B-NP O
, , O O
please VB B-VP O
call VB I-VP O
with IN B-PP O
any DT B-NP O
questions NNS I-NP O
, , O O
Diabetes NNP B-NP O
Center NNP I-NP O
beeper NN I-NP O
# # I-NP O
51158 CD I-NP B-PHONE
. . O O
Joyce NNP B-NP B-DOCTOR
R. NNP I-NP I-DOCTOR
Barton NNP I-NP I-DOCTOR
,N.P. . O O
