Record NNP B-NP O
date NN I-NP O
: : O O
2064-07-17 CD O B-DATE
Name VB B-VP O
: : O O
Xochilt NNP B-NP B-PATIENT
Vuong NNP I-NP I-PATIENT
MRN NNP B-NP O
: : O O
6398353 CD O B-MEDICALRECORD
REASON NNP B-NP O
FOR IN B-PP O
VISIT NNP B-NP O
: : O O
Xochilt NNP B-NP B-PATIENT
Vuong NNP I-NP I-PATIENT
is VBZ B-VP O
a DT B-NP O
74 CD I-NP B-AGE
-year-old JJ I-NP O
patient NN I-NP O
of IN B-PP O
Dr. NNP B-NP O
Wanda NNP I-NP B-DOCTOR
Yeomans NNP I-NP I-DOCTOR
, , O O
and CC O O
is VBZ B-VP O
sent VBN I-VP O
because IN B-PP O
of IN I-PP O
rising VBG B-VP O
serum NN B-NP O
creatinine NN I-NP O
. . O O
HISTORY NN B-NP O
OF IN B-PP O
PRESENT JJ B-NP O
ILLNESS NNS I-NP O
: : O O
Ms. NNP B-NP O
Vuong NNP I-NP B-PATIENT
has VBZ B-VP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
diabetes NN B-NP O
mellitus NN I-NP O
going VBG B-VP O
back RB B-ADVP O
more RBR B-NP O
than IN I-NP O
10 CD I-NP O
years NNS I-NP O
. . O O
She PRP B-NP O
also RB B-ADVP O
has VBZ B-VP O
had VBN I-VP O
hypertension NN B-NP O
and CC O O
elevated VBD B-VP O
lipids NNS B-NP O
over IN B-PP O
approximately RB B-NP O
the DT I-NP O
same JJ I-NP O
period NN I-NP O
of IN B-PP O
time NN B-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
a DT B-NP O
complicated JJ I-NP O
history NN I-NP O
including VBG B-NP O
lung NN I-NP O
cancer NN I-NP O
and CC I-NP O
colon NN I-NP O
cancer NN I-NP O
, , O O
both DT B-NP O
treated VBN I-NP O
and CC I-NP O
in IN B-PP O
remission NN B-NP O
. . O O
Her PRP$ O O
creatinine NN B-NP O
has VBZ B-VP O
been VBN I-VP O
rising VBG I-VP O
gradually RB B-ADVP O
over IN B-PP O
recent JJ B-NP O
years NNS I-NP O
with IN B-PP O
a DT B-NP O
value NN I-NP O
of IN B-PP O
1.0 CD B-NP O
in IN B-PP O
2062 CD B-NP B-DATE
, , O O
1.2 CD B-NP O
in IN B-PP O
May NNP B-NP B-DATE
2063 CD I-NP I-DATE
, , I-NP O
2.1 CD I-NP O
and CC I-NP O
1.8 CD I-NP O
in IN B-PP O
early JJ B-NP O
2064 CD I-NP B-DATE
with IN B-PP O
2.3 CD B-NP O
in IN B-PP O
May NNP B-NP B-DATE
2064 CD I-NP I-DATE
, , O O
and CC O O
recently RB B-NP O
3.1 CD I-NP O
obtained VBN B-VP O
on IN B-PP O
July NNP B-NP B-DATE
06 CD I-NP I-DATE
, , I-NP I-DATE
2064 CD I-NP I-DATE
. . O O
She PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
quite RB B-ADJP O
anemic JJ I-ADJP O
in IN B-PP O
the DT B-NP O
recent JJ I-NP O
months NNS I-NP O
with IN B-PP O
a DT B-NP O
hematocrit NN I-NP O
level NN I-NP O
of IN B-PP O
24.9 CD B-NP O
. . O O
Her PRP$ B-NP O
serum NN I-NP O
folate NN I-NP O
, , O O
B12 NNP B-NP O
, , O O
and CC O O
iron NN B-NP O
and CC O O
are VBP B-VP O
not RB O O
particularly RB B-ADJP O
low JJ I-ADJP O
, , O O
and CC O O
MCV NNP B-NP O
is VBZ B-VP O
normal JJ O O
at IN B-PP O
81 CD B-NP O
. . O O
Urinalysis NNP B-NP O
showed VBD B-VP O
3+ JJ B-NP O
albumin NN I-NP O
in IN B-PP O
September NNP B-NP B-DATE
2062 CD I-NP I-DATE
and CC O O
persisting VBG B-SBAR O
proteinuria NN B-NP O
since IN B-PP O
that DT B-NP O
time NN I-NP O
. . O O
Dr. NNP B-NP O
Yeomans NNP I-NP B-DOCTOR
obtained VBD B-VP O
an DT B-NP O
ultrasound JJ I-NP O
examination NN I-NP O
in IN B-PP O
March NNP B-NP B-DATE
, , O O
which WDT B-NP O
showed VBD B-VP O
diffusely JJ B-NP O
thinned JJ I-NP O
renal JJ I-NP O
cortices NNS I-NP O
, , O O
but CC O O
no DT B-NP O
evidence NN I-NP O
of IN B-SBAR O
obstruction NN B-NP O
, , O O
stones NNS B-NP O
, , O O
or CC O O
masses NNS B-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
visited VBN I-VP O
an DT B-NP O
ophthalmologist NN I-NP O
regularly RB B-ADVP O
for IN B-PP O
macular JJ B-NP O
degeneration NN I-NP O
. . O O
She PRP B-ADVP O
does VBZ O O
not RB B-ADVP O
know VB B-VP O
whether IN B-SBAR O
signs NNS B-NP O
of IN B-PP O
diabetes NNS B-NP O
are VBP B-VP O
present JJ B-ADJP O
, , O O
but CC O O
she PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
no DT B-NP O
laser NN I-NP O
treatment NN I-NP O
for IN B-PP O
any DT B-NP O
proliferative JJ I-NP O
retinopathy NN I-NP O
. . O O
Recently RB B-ADVP O
, , O O
she PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
feeling VBG I-VP O
unusually RB B-NP O
fatigued JJ I-NP O
with IN B-PP O
diminished JJ B-NP O
appetite NN I-NP O
and CC O O
almost RB B-NP O
constant JJ I-NP O
nausea NN I-NP O
. . O O
She PRP B-NP O
vomits VBZ B-VP O
rarely RB B-ADVP O
. . O O
Her PRP$ B-NP O
weight NN I-NP O
has VBZ B-VP O
fallen VBN I-VP O
by IN B-PP O
about RB B-NP O
20 CD I-NP O
pounds NNS B-NP O
. . O O
She PRP B-NP O
is VBZ B-VP O
slightly RB I-VP O
constipated VBN I-VP O
. . O O
She PRP B-NP O
is VBZ B-VP O
moderately RB B-ADJP O
dyspneic JJ I-ADJP O
on IN B-PP O
exertion NN B-NP O
. . O O
She PRP O O
is VBZ B-VP O
not RB I-VP O
troubled VBN I-VP O
by IN B-PP O
muscle NN B-NP O
cramps NNS I-NP O
or CC O O
by IN B-SBAR O
unusual JJ B-NP O
itching NN I-NP O
of IN B-PP O
her PRP$ B-NP O
skin NN I-NP O
. . O O
Her PRP$ B-NP O
medications NNS I-NP O
continue VBP B-VP O
as IN B-SBAR O
listed VBN B-VP O
with IN B-PP O
ACE NNP B-NP O
inhibitors NNS I-NP O
, , O O
" `` O O
statins NNS B-NP O
, , O O
" '' O O
and CC O O
a DT B-NP O
rather RB I-NP O
large JJ B-NP O
dose NN I-NP O
of IN B-PP O
Lasix NNP B-NP O
at IN B-PP O
80 CD B-NP O
mg NN I-NP O
twice RB B-ADVP O
a DT B-NP O
day NN I-NP O
. . O O
Medications NNS B-NP O
Paxil NNP B-NP O
20.0 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
1 CD I-NP O
TAB NNP I-NP O
QD . O O
Synthroid NNP B-NP O
0.05 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
1 CD I-NP O
TAB NNP I-NP O
QD . O O
Multivitamins NNP B-NP O
1 CD I-NP O
TAB NNP I-NP O
QD . O O
One CD B-NP O
Touch NNP I-NP O
Test NNP I-NP O
Strips NNP I-NP O
: : O O
As IN B-PP O
directed VBN B-NP O
. . O O
LORAZEPAM NNP B-NP O
0.5 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
1 CD I-NP O
TAB NNP I-NP O
QD . O O
Accupril NNP B-NP O
( -LRB- I-NP O
QUINAPRIL NN I-NP O
) -RRB- I-NP O
10 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
1 CD I-NP O
TAB NNP I-NP O
QD . O O
Calcium NNP B-NP O
Gluconate NNP I-NP O
500MG NNP I-NP O
, , O O
2 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
BID . O O
Serevent NN B-NP O
( -LRB- I-NP O
SALMETEROL NNP I-NP O
) -RRB- I-NP O
2 CD I-NP O
PUFFS NNP I-NP O
NAS NNP I-NP O
BID NNP I-NP O
Atrovent NNP B-NP O
Inhaler NNP I-NP O
( -LRB- I-NP O
IPRATROPIUM NN I-NP O
Inhaler NN I-NP O
) -RRB- I-NP O
2 CD I-NP O
PUFFS NNP I-NP O
NAS NNP I-NP O
BID NNP I-NP O
Ecasa NNP B-NP O
( -LRB- I-NP O
ASPIRIN NNP I-NP O
Enteric NNP I-NP O
Coated NNP I-NP O
) -RRB- B-VP O
81MG JJ B-ADJP O
, , O O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
1 CD I-NP O
TAQD . O O
Lasix NNP B-NP O
( -LRB- I-NP O
FUROSEMIDE NNP I-NP O
) -RRB- I-NP O
80MG VBP B-VP O
, , O O
2 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
BID . O O
Lopressor NNP B-NP O
( -LRB- I-NP O
METOPROLOL JJ I-NP O
Tartrate NN I-NP O
) -RRB- I-NP O
50MG CD I-NP O
, , I-NP O
0.5 CD I-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
BID . O O
Fe NNP B-NP O
Gluconate NNP I-NP O
( -LRB- I-NP O
FERROUS NNP I-NP O
Gluconate NNP I-NP O
) -RRB- B-VP O
325MG JJ B-ADJP O
, , O O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
TID NN I-NP O
Glucophage NNP B-NP O
( -LRB- I-NP O
METFORMIN NN I-NP O
) -RRB- I-NP O
500MG CD I-NP O
, , I-NP O
2 CD I-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
: : O O
2 CD B-NP O
tabs NN I-NP O
po NN I-NP O
qam NN I-NP O
, , O O
2 CD B-NP O
tabs NNS I-NP O
po NN I-NP O
qpm NN I-NP O
. . O O
Caltrate NNP B-NP O
600 CD I-NP O
1 CD I-NP O
TAB NNP I-NP O
PO NNP I-NP O
BID NNP I-NP O
Avandia NNP B-NP O
( -LRB- I-NP O
ROSIGLITAZONE NNP I-NP O
) -RRB- B-VP O
4MG JJ B-ADJP O
, , O O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
BID . O O
Ocuvite NNP B-NP O
( -LRB- I-NP O
MULTIVITAMINS NNS I-NP O
) -RRB- I-NP O
1 CD I-NP O
TAB NNP I-NP O
PO NNP I-NP O
QD . O O
Fosamax NNP B-NP O
( -LRB- I-NP O
ALENDRONATE NNP I-NP O
) -RRB- I-NP O
70MG NNP I-NP O
, , O O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QWEEK NN I-NP O
Prilosec NNP B-NP O
( -LRB- I-NP O
OMEPRAZOLE NN I-NP O
) -RRB- I-NP O
20MG CD I-NP O
, , I-NP O
1 CD I-NP O
Capsule( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
BID . O O
Lipitor NNP B-NP O
40 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
1 CD I-NP O
TAB NNP I-NP O
QD . O O
PHYSICAL NNP B-NP O
EXAMINATION VBP B-VP O
: : O O
On IN B-PP O
examination NN B-NP O
today NN I-NP O
, , O O
she PRP B-NP O
looks VBZ B-VP O
tired VBN I-VP O
but CC O O
reasonably RB B-ADJP O
comfortable JJ I-ADJP O
. . O O
She PRP B-NP O
speaks VBZ B-VP O
in IN B-PP O
a DT B-NP O
high-pitched JJ I-NP O
somewhat RB I-NP O
hoarse JJ I-NP O
voice NN I-NP O
, , O O
which WDT B-NP O
has VBZ B-VP O
persisted VBN I-VP O
since IN B-PP O
one CD B-NP O
of IN B-PP O
her PRP$ B-NP O
surgical JJ I-NP O
procedures NNS I-NP O
. . O O
Her PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
in IN B-PP O
the DT B-NP O
right JJ I-NP O
arm NN I-NP O
, , O O
sitting VBG B-VP O
, , O O
is VBZ B-VP O
148/60 CD B-NP O
with IN B-PP O
regular JJ B-NP O
pulse NN I-NP O
72 CD B-NP O
. . O O
Her PRP$ B-NP O
chest NN I-NP O
has VBZ B-VP O
a DT B-NP O
few JJ I-NP O
basal NN I-NP O
crackles NNS B-NP O
but CC O O
in IN B-PP O
general JJ B-NP O
is VBZ B-VP O
clear JJ B-ADJP O
and CC O O
air NN B-NP O
moves NNS I-NP O
comfortably RB B-ADVP O
. . O O
JVP JJ B-NP O
fills NNS I-NP O
below IN B-PP O
the DT B-NP O
sternal JJ B-NP O
angle NN I-NP O
heart NN I-NP O
shows VBZ B-VP O
a DT B-NP O
grade NN I-NP O
2 CD I-NP O
systolic JJ I-NP O
murmur NN I-NP O
, , O O
loudest JJS B-NP O
at IN B-PP O
the DT B-NP O
upper JJ I-NP O
left NN I-NP O
sternal JJ B-NP O
border NN I-NP O
. . O O
Abdomen '' O O
is VBZ B-VP O
soft JJ B-ADJP O
and CC I-ADJP O
nontender JJ I-ADJP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
renal JJ I-NP O
tenderness NN I-NP O
. . O O
Extremities NNS B-NP O
have VBP B-VP O
no DT B-NP O
edema NN I-NP O
. . O O
IMPRESSION NN B-NP O
: : O O
Progressive JJ B-NP O
renal JJ I-NP O
failure NN I-NP O
in IN B-PP O
a DT B-NP O
74 CD I-NP B-AGE
-year-old JJ I-NP O
woman NN I-NP O
with IN B-PP O
more JJR B-NP O
than IN I-NP O
10 CD B-NP O
years NNS I-NP O
' POS B-NP O
history NN I-NP O
of IN B-PP O
diabetes NN B-NP O
as RB B-CONJP O
well RB I-CONJP O
has VBZ B-VP O
hypertension NN B-NP O
and CC I-NP O
hyperlipidemia NN I-NP O
. . O O
The DT O O
proteinuria NN B-NP O
, , O O
if IN B-SBAR O
confirmed VBN B-VP O
, , O O
would MD B-VP O
support VB I-VP O
the DT B-NP O
diagnosis NN I-NP O
of IN B-PP O
diabetic JJ B-NP O
nephropathy NN I-NP O
but CC O O
this DT B-NP O
would MD B-VP O
be VB I-VP O
unusual JJ B-ADJP O
in IN B-PP O
the DT B-NP O
absence NN I-NP O
of IN B-PP O
retinopathy NN B-NP O
. . O O
It PRP B-NP O
would MD B-VP O
be VB I-VP O
useful JJ B-ADJP O
to TO B-VP O
know VB I-VP O
from IN B-PP O
her PRP$ B-NP O
ophthalmologist NN I-NP O
whether IN B-PP O
retinopathy NN B-NP O
is VBZ B-VP O
present JJ B-ADJP O
. . O O
It PRP B-NP O
is VBZ B-VP O
, , O O
of IN B-PP O
course NN B-NP O
, , O O
also RB B-ADVP O
possible JJ B-ADJP O
that IN B-SBAR O
she PRP B-NP O
has VBZ B-VP O
vascular JJ B-NP O
disease NN I-NP O
involving VBG B-VP O
the DT B-NP O
kidneys NNS I-NP O
. . O O
Their PRP$ B-NP O
symmetry NN I-NP O
and CC O O
the DT B-NP O
presence NN I-NP O
of IN B-PP O
proteinuria NN B-NP O
would MD B-VP O
argue VB I-VP O
against IN B-PP O
this DT B-NP O
possibility NN I-NP O
. . O O
The DT B-NP O
ACE NNP I-NP O
inhibitor NN B-NP O
in IN B-PP O
the DT B-NP O
presence NN I-NP O
of IN B-PP O
vascular JJ B-NP O
disease NN I-NP O
might NN I-NP O
of IN B-PP O
course NN B-NP O
raise VB B-VP O
her PRP B-NP O
serum NN B-NP O
creatinine VBN B-VP O
by IN B-PP O
reducing VBG B-VP O
renal JJ B-NP O
blood NN I-NP O
flow NN I-NP O
somewhat RB B-ADVP O
. . O O
Her PRP$ B-NP O
loss NN I-NP O
of IN B-PP O
appetite NN B-NP O
and CC O O
nausea NN B-NP O
may MD B-VP O
well RB I-VP O
be VB I-VP O
related VBN I-VP O
to TO B-PP O
the DT B-NP O
degree NN I-NP O
of IN B-PP O
renal JJ B-NP O
failure NN I-NP O
. . O O
RECOMMENDATION NN B-NP O
: : O O
I PRP B-NP O
would MD B-VP O
suggest VB I-VP O
that IN B-SBAR O
she PRP B-NP O
see VBP B-VP O
Filomena NNP B-NP B-DOCTOR
Xia NNP I-NP I-DOCTOR
, , O O
RD NNP B-NP O
, , O O
a DT B-NP O
renal NN I-NP O
dietitian NN B-NP O
, , O O
to TO B-VP O
learn VB I-VP O
a DT B-NP O
diet NN I-NP O
appropriate JJ B-ADJP O
for IN B-PP O
renal JJ B-NP O
failure NN I-NP O
as RB B-ADVP O
well RB I-ADVP O
as IN B-PP O
for IN B-PP O
her PRP$ B-NP O
diabetes NN I-NP O
and CC O O
hyperlipidemia NN B-NP O
. . O O
This DT B-NP O
might MD B-VP O
succeed VB I-VP O
in IN B-PP O
reducing VBG B-VP O
some DT B-NP O
of IN B-PP O
her PRP$ B-NP O
nausea NN I-NP O
. . O O
It PRP B-NP O
think VB B-VP O
it PRP B-NP O
would MD B-VP O
be VB I-VP O
worthwhile JJ B-ADJP O
as IN B-PP O
an DT B-NP O
experiment NN I-NP O
to TO B-VP O
reduce VB I-VP O
or CC I-VP O
discontinue VB I-VP O
her PRP$ B-NP O
Accupril NNP I-NP O
and CC O O
perhaps RB B-ADVP O
her PRP B-NP O
Lasix NNP O O
temporarily RB B-ADVP O
to TO B-VP O
see VB I-VP O
whether IN B-PP O
serum NN B-NP O
creatinine NN I-NP O
falls VBZ B-VP O
with IN B-PP O
less JJR B-NP O
ACE NNP I-NP O
inhibition NN I-NP O
and CC O O
somewhat RB B-NP O
more JJR I-NP O
fluid NN I-NP O
volume NN I-NP O
. . B-VP O
If IN B-SBAR O
, , O O
of IN B-PP O
course NN B-NP O
, , O O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
worsens NNS I-NP O
or CC O O
edema NN B-NP O
appears VBZ B-VP O
, , O O
then RB B-ADVP O
returning VBG B-VP O
to TO B-PP O
the DT B-NP O
Lasix NNP I-NP O
would MD B-VP O
be VB I-VP O
reasonable JJ B-ADJP O
. . O O
It PRP B-NP O
might MD B-VP O
be VB I-VP O
that IN B-PP O
a DT B-NP O
longer RB I-NP O
acting VBG I-NP O
, , I-NP O
milder NN I-NP O
diuretic JJ I-NP O
, , O O
such JJ B-PP O
as IN I-PP O
5 CD B-NP O
mg NN I-NP O
of IN B-PP O
metolazone NN B-NP O
might MD B-VP O
help VB I-VP O
to TO I-VP O
control VB I-VP O
edema NN B-NP O
( -LRB- O O
and CC O O
potassium NN B-NP O
) -RRB- I-NP O
and CC O O
reduce VB B-VP O
the DT B-NP O
requirement NN B-NP O
for IN B-PP O
Lasix NNP B-NP O
. . O O
If IN B-PP O
serum JJ B-NP O
creatinine NN I-NP O
fell VBD B-VP O
appreciably RB B-ADVP O
with IN B-PP O
less JJR B-NP O
ACE NNP I-NP O
and CC O O
diuresis NN B-NP O
, , O O
it PRP B-NP O
would MD B-VP O
reassure VB I-VP O
us PRP B-NP O
that IN B-SBAR O
the DT B-NP O
damage NN I-NP O
was VBD B-VP O
not RB O O
all DT B-NP O
structural JJ I-NP O
, , O O
and CC O O
it PRP B-NP O
might MD O O
be VB B-VP O
then RB B-ADJP O
possible JJ I-ADJP O
to TO B-VP O
return VB I-VP O
to TO B-PP O
these DT B-NP O
medicines NNS I-NP O
with IN B-PP O
less JJR B-NP O
worry NN I-NP O
. . O O
Her PRP$ B-NP O
anemia NN I-NP O
is VBZ B-VP O
no DT B-NP O
doubt NN I-NP O
related VBN B-VP O
to TO B-PP O
lack NN B-NP O
of IN B-PP O
erythropoietin NN B-NP O
and CC O O
would MD B-VP O
likely RB I-VP O
benefit VB I-VP O
from IN B-PP O
instituting VBG B-VP O
therapy NN B-NP O
with IN B-PP O
Epogen NN B-NP O
( -LRB- I-NP O
such JJ B-PP O
as IN I-PP O
4000 CD B-NP O
units NNS I-NP O
twice RB B-NP O
a DT I-NP O
week NN I-NP O
) -RRB- O O
or CC O O
Aranesp NNP B-NP O
) -RRB- I-NP O
. . O O
PLAN NNP B-NP O
: : O O
We PRP B-NP O
will MD B-VP O
send VB I-VP O
a DT B-NP O
urine NN I-NP O
today NN I-NP O
for IN B-PP O
total JJ B-NP O
protein NN I-NP O
to TO B-VP O
creatinine VB I-VP O
ratio NN B-NP O
, , O O
which WDT B-NP O
may MD O O
help NN B-NP O
us PRP B-NP O
decide VBP B-VP O
whether IN B-SBAR O
the DT B-NP O
problem NN I-NP O
is VBZ B-VP O
mainly RB B-NP O
diabetic JJ I-NP O
nephropathy NN I-NP O
. . O O
If IN B-ADVP O
so RB I-ADVP O
, , O O
the DT O O
measures NNS B-NP O
proposed VBN B-VP O
would MD B-VP O
be VB I-VP O
appropriate JJ B-ADJP O
. . O O
We PRP B-NP O
discussed VBD B-VP O
the DT B-NP O
eventual JJ I-NP O
probable JJ I-NP O
need NN B-NP O
for IN B-PP O
dialysis NN B-NP O
( -LRB- O O
assuming VBG B-VP O
no DT B-NP O
other JJ I-NP O
intercurrent JJ I-NP O
medical JJ I-NP O
catastrophes NNS I-NP O
) -RRB- I-NP O
. . O O
It PRP B-NP O
would MD O O
be VB B-VP O
useful JJ B-ADJP O
for IN B-SBAR O
her PRP B-NP O
to TO B-VP O
visit VB I-VP O
the DT B-NP O
DCGH NNP I-NP B-HOSPITAL
Renal NNP I-NP O
Department NNP I-NP O
( -LRB- B-VP O
located VBN I-VP O
here RB B-ADVP O
on IN B-PP O
our PRP$ B-NP O
floor NN B-NP O
at IN B-PP O
592G CD B-NP O
, , O O
along RB B-ADVP O
with IN B-PP O
Ms. NNP B-NP O
Xia NNP I-NP B-DOCTOR
's POS B-NP O
office NN I-NP O
) -RRB- I-NP O
to TO B-VP O
learn VB I-VP O
about IN B-PP O
modes NNS B-NP O
of IN B-PP O
dialysis NN B-NP O
. . O O
We PRP B-NP O
discussed VBD B-VP O
construction NN B-NP O
of IN B-PP O
a DT B-NP O
forearm JJ I-NP O
fistula NN I-NP O
, , O O
which WDT B-NP O
should MD B-VP O
be VB I-VP O
done VBN I-VP O
well RB B-ADVP O
before IN B-PP O
a DT B-NP O
need NN I-NP O
for IN B-SBAR O
it PRP B-NP O
arises VBZ B-VP O
. . O O
I PRP B-NP O
would MD B-VP O
, , O O
in IN B-PP O
fact NN B-NP O
, , O O
recommend VB B-VP O
that IN B-SBAR O
she PRP B-NP O
proceed VBP B-VP O
to TO I-VP O
have VB I-VP O
this DT B-NP O
done VBN B-VP O
in IN B-PP O
the DT B-NP O
next JJ I-NP O
few JJ I-NP O
months NNS I-NP O
. . O O
This DT B-NP O
could MD B-VP O
be VB I-VP O
arranged VBN I-VP O
through IN B-PP O
Dr. NNP B-NP O
Xaysana NNP I-NP B-DOCTOR
's POS B-NP O
office NN I-NP O
or CC O O
perhaps RB B-ADVP O
by IN B-PP O
speaking VBG B-VP O
with IN B-PP O
Dr. NNP B-NP O
Najee NNP I-NP B-DOCTOR
Yuan NNP I-NP I-DOCTOR
. . O O
I PRP B-NP O
will MD B-VP O
, , O O
of IN B-PP O
course NN B-NP O
, , O O
help VB B-VP O
with IN B-PP O
any DT B-NP O
of IN B-PP O
these DT B-NP O
measures NNS I-NP O
as IN B-PP O
necessary JJ B-ADJP O
. . O O
Xander NNP B-NP B-DOCTOR
Xie NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Wanda NNP B-NP B-DOCTOR
Urine NNP B-NP O
total JJ I-NP O
protein/creatinine NN I-NP O
ratio NN I-NP O
is VBZ B-VP O
only RB B-NP O
0.11 CD I-NP O
( -LRB- I-NP O
corresponding JJ I-NP O
to TO B-PP O
about IN B-NP O
0.1 CD I-NP O
g/day NN I-NP O
or CC I-NP O
proteinuria NN I-NP O
) -RRB- I-NP O
. . O O
This DT B-NP O
is VBZ B-VP O
a DT B-NP O
very RB I-NP O
small JJ I-NP O
amount NN I-NP O
for IN B-PP O
diabetic NN B-NP O
nephropathy NN I-NP O
, , O O
and CC O O
argues VBZ B-VP O
in IN B-PP O
favor NN B-NP O
of IN B-PP O
vascular JJ B-NP O
disease NN I-NP O
. . O O
I PRP B-NP O
would MD B-VP O
suggest VB I-VP O
getting VBG I-VP O
a DT B-NP O
MRA NNP I-NP O
of IN B-PP O
renal JJ B-NP O
arteries NNS I-NP O
to TO B-VP O
look VB I-VP O
for IN B-PP O
any DT B-NP O
main JJ I-NP O
artery NN I-NP O
obstruction NN I-NP O
. . O O
If IN B-PP O
present JJ B-NP O
it PRP B-NP O
would MD B-VP O
account VB I-VP O
for IN B-PP O
the DT B-NP O
sensitivity NN I-NP O
of IN B-PP O
her PRP$ B-NP O
creatinine NN I-NP O
to TO B-PP O
ACE NNP B-NP O
or CC O O
changes NNS B-NP O
in IN B-PP O
hydration NN B-NP O
. . O O
Kyle NNP B-NP B-DOCTOR
