Record NNP B-NP O
date NN I-NP O
: : O O
2072-01-01 CD O B-DATE
EDVISIT^ NNP B-NP O
84091519 CD I-NP B-MEDICALRECORD
^ , O O
THOMAS-YOSEF NNP B-NP I-PATIENT
, , O I-PATIENT
JULIA NNP B-NP I-PATIENT
^ VBD B-VP O
01/01/72 CD B-NP B-DATE
^ NN I-NP O
HOFFMAN NNP I-NP I-DOCTOR
, , O I-DOCTOR
VICTOR NN B-NP I-DOCTOR
Seen NNP B-NP O
by IN B-PP O
me PRP B-NP O
along IN B-PP O
with IN B-PP O
Dr. NNP B-NP O
Ickes NNP I-NP B-DOCTOR
on IN B-PP O
01/01/2072 CD B-NP B-DATE
. . O O
History NNP O O
as IN B-PP O
documented VBN B-VP O
by IN B-PP O
Dr. NNP B-NP O
Ickes NNP I-NP B-DOCTOR
was VBD B-VP O
reviewed VBN I-VP O
by IN B-PP O
me PRP B-NP O
with IN B-PP O
the DT B-NP O
patient NN I-NP O
and CC O O
found VBN B-VP O
to TO I-VP O
be VB I-VP O
accurate JJ B-ADJP O
and CC I-ADJP O
complete JJ I-ADJP O
. . O O
The DT B-NP O
physical JJ I-NP O
exam NN I-NP O
was VBD B-SBAR O
confirmed VBN B-VP O
by IN B-PP O
my PRP$ B-NP O
examination NN I-NP O
. . O O
Evaluation NN B-NP O
and CC I-NP O
management NN I-NP O
was VBD B-VP O
also RB I-VP O
concurred VBN B-VP O
with IN B-PP O
. . O O
HISTORY NN B-NP O
OF IN B-PP O
PRESENT JJ B-NP O
ILLNESS NNS I-NP O
: : O O
In IN B-PP O
brief NN B-NP O
, , O O
this DT B-NP O
is VBZ B-VP O
a DT B-NP O
51 CD I-NP B-AGE
-year-old NN I-NP O
woman NN B-NP O
with IN B-PP O
history NN B-NP O
of IN B-PP O
coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
status NN I-NP O
post NN I-NP O
MI NN I-NP O
stenting VBG B-VP O
in IN B-PP O
2068 CD B-NP B-DATE
, , O O
presents VBZ B-VP O
with IN B-PP O
3-day JJ B-NP O
history NN I-NP O
of IN B-PP O
substernal JJ B-NP O
chest NN I-NP O
pain NN B-NP O
radiating VBG B-VP O
to TO B-PP O
her PRP$ B-NP O
back NN I-NP O
, , O O
and CC O O
also RB B-ADVP O
complaining VBG B-VP O
of IN B-PP O
mild JJ B-NP O
pain NN I-NP O
of IN B-PP O
inner JJ B-NP O
medial JJ I-NP O
aspect NN I-NP O
of IN B-PP O
her PRP$ B-NP O
right JJ I-NP O
arm NN I-NP O
, , O O
feels VBZ B-VP O
like IN B-PP O
her PRP B-NP O
anginal . O O
symptoms NNS B-NP O
that IN B-SBAR O
she PRP B-NP O
had VBD B-VP O
in IN B-PP O
2068 CD B-NP B-DATE
with IN B-PP O
some DT B-NP O
very RB I-NP O
mild JJ I-NP O
shortness NN I-NP O
of IN B-PP O
breath NN B-NP O
and CC O O
even RB B-SBAR O
though IN I-SBAR O
she PRP B-NP O
is VBZ B-VP O
quite RB B-ADJP O
sedentary JJ I-ADJP O
and CC O O
she PRP B-NP O
noted VBD B-VP O
that IN B-SBAR O
there EX B-NP O
is VBZ B-VP O
an DT B-NP O
increase NN I-NP O
in IN B-PP O
pain NN B-NP O
with IN B-PP O
exertion NN B-NP O
, , I-NP O
position NN I-NP O
, , O O
as RB B-CONJP O
well RB I-CONJP O
as IN I-CONJP O
eating VBG B-VP O
. . O O
She PRP B-NP O
took VBD B-VP O
many JJ B-NP O
Tums NNS I-NP O
with IN B-PP O
no DT B-NP O
relief NN I-NP O
and CC O O
says VBZ B-VP O
takes VBZ B-NP O
Zantac NNP O O
chronically RB B-ADVP O
, , O O
but CC O O
ran VBD B-VP O
out IN B-ADVP O
of IN B-PP O
it PRP B-NP O
. . O O
She PRP B-NP O
says VBZ B-VP O
that IN B-SBAR O
the DT B-NP O
pain NN I-NP O
is VBZ B-LST O
burning VBG B-VP O
epigastric JJ B-ADJP O
at IN B-PP O
times NNS B-NP O
, , O O
and CC O O
the DT B-NP O
thing NN I-NP O
that WDT B-NP O
is VBZ B-VP O
concerning VBG I-VP O
was VBD I-VP O
her PRP B-NP O
back RB B-ADVP O
pain NN B-VP O
that DT B-NP O
was VBD B-VP O
reminiscent JJ B-ADJP O
of IN B-PP O
the DT B-NP O
pain NN I-NP O
that IN B-SBAR O
she PRP B-NP O
had VBD B-VP O
when WRB I-VP O
she PRP B-NP O
had VBD B-VP O
her PRP$ B-NP O
MI NNP I-NP O
. . O O
PAST NN B-NP O
MEDICAL NNP I-NP O
HISTORY NNP I-NP O
: : O O
She PRP B-NP O
has VBZ B-VP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
hypertension NN B-NP O
, , O O
diabetes NNS B-NP O
, , O O
MI NNP B-NP O
, , O O
and CC O O
breast NN B-NP O
cancer NN I-NP O
status NN I-NP O
post NN I-NP O
lumpectomy NN I-NP O
and CC O O
radiation NN B-NP O
. . O O
Last JJ O O
stress NN B-NP O
test NN I-NP O
was VBD B-VP O
may MD B-VP O
be VB I-VP O
in IN B-PP O
October NNP B-NP B-DATE
, , O O
which WDT B-NP O
was VBD B-VP O
normal JJ B-ADJP O
. . O O
FAMILY NNP B-NP O
HISTORY NNP I-NP O
: : O O
Positive JJ B-ADJP O
for IN B-PP O
breast NN B-NP O
cancer NN I-NP O
and CC O O
diabetes NN B-NP O
mellitus NN B-NP O
. . O O
SOCIAL JJ B-NP O
HISTORY NN I-NP O
: : O O
She PRP B-NP O
does VBZ B-VP O
not RB I-VP O
drink VB I-VP O
. . O O
She PRP B-NP O
smoked VBD B-VP O
in IN B-PP O
the DT B-NP O
past NN I-NP O
, , O O
quit VB B-VP O
15 CD B-NP O
years NNS I-NP O
ago RB B-ADVP O
. . O O
REVIEW NN B-NP O
OF IN B-PP O
SYSTEMS NNP B-NP O
: : O O
As IN B-SBAR O
documented VBN B-VP O
in IN B-PP O
the DT B-NP O
chart NN I-NP O
. . O O
Please VB B-VP O
see VB I-VP O
notes NNS B-NP O
for IN B-PP O
details NNS B-NP O
. . O O
ALLERGIES NNS B-NP O
: : O O
As IN B-SBAR O
documented VBN B-VP O
in IN B-PP O
the DT B-NP O
chart NN I-NP O
. . O O
Please VB B-VP O
see VB I-VP O
notes NNS B-NP O
for IN B-PP O
details NNS B-NP O
. . O O
MEDICATIONS NNS B-NP O
: : O O
As IN B-SBAR O
documented VBN B-VP O
in IN B-PP O
the DT B-NP O
chart NN I-NP O
. . O O
Please VB B-VP O
see VB I-VP O
notes NNS B-NP O
for IN B-PP O
details NNS B-NP O
. . O O
PHYSICAL NNP B-NP O
EXAMINATION NNP I-NP O
: : O O
Awake NN B-NP O
, , I-NP O
alert JJ I-NP O
, , I-NP O
well-developed JJ I-NP O
, , O O
well-nourished JJ B-NP O
woman NN I-NP O
, , O O
and CC O O
in IN B-PP O
no DT B-NP O
apparent JJ I-NP O
distress NN I-NP O
. . O O
Afebrile '' O O
, , O O
slightly RB B-NP O
96.7 CD I-NP O
, , I-NP O
pulse NN I-NP O
72 CD I-NP O
, , O O
respirations NNS B-NP O
16 CD B-NP O
, , O O
blood NN B-NP O
pressure NN I-NP O
124/72 CD B-NP O
, , O O
and CC O O
O2 CD B-NP O
saturation NN I-NP O
98 CD B-NP O
% NN I-NP O
. . O O
Anicteric JJ B-NP O
sclerae NNS I-NP O
. . O O
Mucous NNP B-NP O
membranes NNS I-NP O
are VBP I-NP O
moist JJ B-NP O
. . I-NP O
Neck NNP I-NP O
is VBZ B-VP O
supple NN B-NP O
. . O O
Lungs NNS B-NP O
are VBP B-VP O
clear JJ B-ADJP O
of IN B-PP O
rales NNS B-NP O
, , O O
wheezes NNS B-NP O
, , O O
or CC O O
rhonchi NNP B-NP O
. . I-NP O
Cardiovascular NNP I-NP O
: : O O
Regular JJ B-NP O
rate NN I-NP O
and CC I-NP O
rhythm NN I-NP O
. . O O
Abdomen '' O O
is VBZ O O
obese NN B-NP O
. . O O
Bowel NNP B-NP O
sounds VBZ B-VP O
normoactive JJ B-ADJP O
, , O O
nontender NN B-NP O
, , O O
and CC O O
no DT B-NP O
guarding VBG I-NP O
, , O O
rebound NN B-NP O
, , O O
or CC O O
rigidity NN B-NP O
. . O O
The DT B-NP O
skin NN I-NP O
is VBZ B-VP O
intact JJ B-ADJP O
, , I-ADJP O
warm JJ I-ADJP O
, , O O
and CC O O
dry JJ B-NP O
. . O O
She PRP O O
has VBZ O O
point NN B-NP O
tenderness NN I-NP O
over IN B-PP O
the DT B-NP O
upper JJ I-NP O
thoracic NN I-NP O
cage NN I-NP O
and CC I-NP O
trace NN I-NP O
pedal NN I-NP O
edema NN B-NP O
. . O O
LABORATORY NNP B-NP O
DATA NNP I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
a DT B-NP O
normal JJ I-NP O
CBC NNP I-NP O
and CC I-NP O
normal JJ I-NP O
electrolytes NNS B-NP O
. . B-NP O
D-dimer NN I-NP O
was VBD B-VP O
less JJR B-NP O
than IN I-NP O
200 CD I-NP O
. . I-NP O
Troponin NNP I-NP O
and CC O O
CK NNP B-NP O
were VBD B-LST O
normal JJ B-ADJP O
. . O O
IMAGING NNP B-NP O
STUDIES NNS I-NP O
: : O O
EKG NNP B-NP O
sinus IN B-PP O
rhythm NN B-NP O
with IN B-PP O
unchanged JJ B-NP O
from IN B-PP O
previous JJ B-NP O
. . O O
Chest NNP B-NP O
CT NNP I-NP O
was VBD B-VP O
negative JJ B-ADJP O
PE. . O O
EMERGENCY NNP B-NP O
DEPARTMENT NNP I-NP O
COURSE NNP I-NP O
: : O O
As IN B-PP O
such JJ B-NP O
, , O O
she PRP B-NP O
was VBD B-VP O
admitted VBN I-VP O
to TO B-PP O
the DT B-NP O
Observation NNP B-NP O
Unit NN I-NP O
for IN B-PP O
a DT B-NP O
second JJ I-NP O
set NN I-NP O
of IN B-PP O
enzymes NNS B-NP O
which WDT B-NP O
if IN B-PP O
normal JJ B-NP O
will MD O O
be VB B-VP O
discharged VBN B-NP O
home NN I-NP O
, , O O
after IN B-PP O
walking VBG B-VP O
to TO I-VP O
see VB I-VP O
if IN B-SBAR O
she PRP B-NP O
has VBZ B-VP O
any DT O O
exertional JJ B-NP O
component NN I-NP O
, , O O
as IN B-PP O
such JJ B-NP O
, , O O
she PRP B-NP O
was VBD B-VP O
subsequently RB I-VP O
discharged VBN I-VP O
to TO I-VP O
home NN B-NP O
in IN B-PP O
stable JJ B-NP O
and CC I-NP O
satisfactory JJ I-NP O
condition NN I-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
admitted VBN I-VP O
to TO I-VP O
the DT B-NP O
Observation NNP I-NP O
Unit NN I-NP O
01/01/2072 NN I-NP B-DATE
with IN B-PP O
diagnosis NN B-NP O
of IN B-PP O
chest NN B-NP O
pain NN I-NP O
. . O O
HOFFMAN NNP B-NP I-DOCTOR
, , O I-DOCTOR
VICTOR NNP B-NP I-DOCTOR
M.D. NNP I-NP O
D NNP B-NP O
: : O O
01/01/72 CD O B-DATE
T NNP B-NP O
: : O O
01/02/72 CD O B-DATE
Dictated NNP B-NP O
By IN I-NP O
: : O O
HOFFMAN NNP B-NP I-DOCTOR
, , O I-DOCTOR
VICTOR NN B-NP I-DOCTOR
eScription NN B-NP O
document NN I-NP O
: : O O
0-5469816 CD B-NP B-IDNUM
BFFocus NN I-NP O
******** NN B-NP O
Not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Physician JJ B-NP O
******** NNS I-NP O
