Record NNP B-NP O
date NN I-NP O
: : O O
2091-03-19 CD O B-DATE
CCU NNP B-NP O
Admission NNP I-NP O
Note NN I-NP O
Patient NNP B-NP O
Name NNP I-NP O
: : O O
Justus NNP B-NP I-PATIENT
, , O I-PATIENT
Quiana NNP B-NP I-PATIENT
MR# NNP B-NP O
9814048 CD I-NP B-MEDICALRECORD
Location NN B-NP O
: : O O
Internal NNP B-NP O
Medicine NNP I-NP O
PCP NNP B-NP O
: : O O
Xayachack NNP B-NP I-DOCTOR
, , O I-DOCTOR
Ida NNP B-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Date NNP B-NP O
of IN B-PP O
Admission NNP B-NP O
: : O O
3/18/91 CD O B-DATE
CC NNP B-NP O
: : O O
STEMI NNP O O
HPI NNP B-NP O
: : O O
79 CD B-NP B-AGE
yo NNP I-NP O
lady NN I-NP O
with IN B-PP O
DM NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
HL NNP B-NP O
who WP B-NP O
presented VBD B-VP O
with IN B-PP O
new JJ B-NP O
onset NN I-NP O
chest NN I-NP O
pain NN I-NP O
and CC I-NP O
shortness NN I-NP O
of IN B-PP O
breath NN B-NP O
and CC O O
was VBD B-VP O
found VBN I-VP O
to TO I-VP O
have VB I-VP O
lateral JJ B-NP O
STEMI NNP I-NP O
. . O O
It PRP B-NP O
began VBD B-VP O
last JJ B-NP O
Sunday NNP I-NP B-DATE
, , O O
when WRB B-ADVP O
she PRP B-NP O
noticed VBD B-VP O
the DT B-NP O
new JJ I-NP O
onset NN I-NP O
of IN B-PP O
back RB B-NP O
pain NN I-NP O
, , O O
which WDT B-NP O
progressed VBD B-VP O
and CC O O
was VBD B-VP O
associated VBN I-VP O
with IN B-PP O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
by IN B-PP O
Monday NNP B-NP B-DATE
. . O O
She PRP B-NP O
apparently RB B-ADVP O
called VBD B-VP O
EMS NNP B-NP O
on IN B-PP O
Tuesday NNP B-NP B-DATE
then RB B-ADVP O
and CC O O
en IN B-PP O
route NN B-NP O
she PRP B-NP O
had VBD B-VP O
a DT B-NP O
long JJ I-NP O
run NN I-NP O
of IN B-PP O
VT NNP B-NP O
, , O O
which WDT B-NP O
responded VBD B-VP O
to TO B-PP O
50mg CD B-NP O
of IN B-PP O
Lidocaine NNP B-NP O
IV. NNP I-NP O
She PRP B-NP O
was VBD B-VP O
intubated VBN I-VP O
on IN B-PP O
arrival NN B-NP O
in IN B-PP O
the DT B-NP O
ED NNP I-NP O
for IN B-PP O
progressive JJ B-NP O
respiratory NN I-NP O
distress NN I-NP O
. . O O
ECG '' O O
showed VBD B-VP O
lateral JJ B-NP O
ST NNP I-NP O
elevations NNS I-NP O
and CC O O
a DT B-NP O
CT NNP I-NP O
scan NN I-NP O
of IN B-PP O
her PRP$ B-NP O
chest NN I-NP O
was VBD B-VP O
negative JJ B-ADJP O
for IN B-PP O
any DT B-NP O
signs NNS I-NP O
of IN B-PP O
aortic JJ B-NP O
dissection NN I-NP O
. . O O
Of IN B-PP O
note NN B-NP O
, , O O
she PRP B-NP O
was VBD B-VP O
also RB I-VP O
noticed VBN I-VP O
to TO I-VP O
have VB I-VP O
elevated VBN B-NP O
blood NN I-NP O
sugars NNS I-NP O
in IN B-PP O
the DT B-NP O
500s NNS I-NP O
in IN B-PP O
the DT B-NP O
ED VBN B-VP O
with IN B-PP O
an DT B-NP O
AG NNP I-NP O
of IN B-PP O
20 CD B-NP O
, , O O
that WDT B-NP O
came VBD B-VP O
down RP B-NP O
to TO B-PP O
16 CD B-NP O
. . O O
On IN B-PP O
immediate JJ B-NP O
LHC NNP I-NP O
, , O O
a DT B-NP O
100 CD I-NP O
% NN I-NP O
occlusion NN I-NP O
of IN B-PP O
her PRP$ B-NP O
OM1 NNP I-NP O
was VBD B-VP O
found VBN I-VP O
and CC O O
recannalized VBN B-VP O
as RB B-ADVP O
well RB I-ADVP O
as IN B-SBAR O
stented VBN B-VP O
with IN B-PP O
a DT B-NP O
Vision NNP I-NP O
BMS NNP I-NP O
, , O O
resulting VBG B-VP O
in IN B-PP O
TIMI NN B-NP O
2 CD I-NP O
flow NN I-NP O
. . O O
Her PRP$ B-NP O
LAD NN I-NP O
was VBD B-VP O
found VBN I-VP O
to TO I-VP O
be VB I-VP O
patent NN B-NP O
but CC O O
and CC O O
her PRP$ B-NP O
RCA NN I-NP O
showed VBD B-VP O
diffuse JJ B-NP O
atherosclerosis NN I-NP O
up IN B-NP O
to TO I-NP O
60 CD I-NP O
% NN I-NP O
stenosis NN I-NP O
at IN B-PP O
most JJS B-NP O
. . I-NP O
LV NNP I-NP O
ventriculogram NN I-NP O
showed VBD B-VP O
inferior JJ B-NP O
hypokinesis NN I-NP O
with IN B-PP O
moderate JJ B-NP O
MR. NNP I-NP O
An DT B-NP O
IABP NNP I-NP O
was VBD B-VP O
placed VBN I-VP O
with IN B-PP O
her PRP$ B-NP O
initial JJ I-NP O
augmented JJ I-NP O
diastolic JJ I-NP O
pressures NNS I-NP O
recorded VBN B-VP O
in IN B-PP O
the DT B-NP O
80s CD I-NP O
, , O O
which WDT B-NP O
led VBD B-VP O
to TO B-PP O
the DT B-NP O
initiation NN I-NP O
of IN B-PP O
Levophed NNP B-NP O
, , I-NP O
Dobutamine NNP I-NP O
and CC I-NP O
Dopamine NNP I-NP O
. . O O
A DT B-NP O
PAC NNP I-NP O
was VBD B-VP O
placed VBN I-VP O
in IN B-PP O
the DT B-NP O
cath NN I-NP O
lab NN I-NP O
as RB B-ADVP O
well RB I-ADVP O
with IN B-PP O
her PRP$ B-NP O
initial JJ I-NP O
Wedge NN I-NP O
reported VBD B-VP O
as IN B-PP O
19-20 CD B-NP O
, , O O
PAPs NNS B-NP O
in IN B-PP O
the DT B-NP O
50s NNS I-NP O
. . O O
On IN B-SBAR O
transfer NN B-NP O
to TO B-PP O
the DT B-NP O
CCU NNP I-NP O
, , O O
she PRP B-NP O
was VBD B-VP O
intubated VBN I-VP O
, , O O
sedated VBD B-VP O
, , O O
being VBG B-VP O
on IN B-PP O
IV NNP B-NP O
Levophed NNP I-NP O
at IN B-PP O
20/hr CD B-NP O
, , O O
Dobutamine NNP B-NP O
at IN B-PP O
200/hr CD B-NP O
and CC I-NP O
Dopamine NNP I-NP O
at IN B-PP O
300/hr NNP B-NP O
. . O O
Her PRP$ B-NP O
CO NNP I-NP O
was VBD B-VP O
recorded VBN I-VP O
as IN B-PP O
6.0, CD B-NP O
her PRP B-PP O
CI NNP B-NP O
3.5 CD I-NP O
with IN B-PP O
an DT B-NP O
initial JJ I-NP O
SVR NN I-NP O
of IN B-PP O
1012 CD B-NP O
. . O O
Her PRP$ B-VP O
Temp NNP B-NP O
. . O O
was VBD B-VP O
96.1 CD B-NP O
, , O O
HR NNP B-NP O
115 CD I-NP O
bpm NN I-NP O
, , O O
augmented VBD B-VP O
diastolic JJ B-NP O
BP NNP I-NP O
of IN B-PP O
124 CD B-NP O
, , O O
which WDT B-NP O
subsequently RB B-ADVP O
ranged VBD B-VP O
between IN B-PP O
70 CD B-NP O
and CC I-NP O
100 CD I-NP O
on IN B-PP O
the DT B-NP O
day NN I-NP O
of IN B-PP O
her PRP$ B-NP O
admission NN I-NP O
. . O O
She PRP B-NP O
spiked VBN B-VP O
a DT B-NP O
temperature NN I-NP O
up IN B-NP O
to TO I-NP O
101 CD I-NP O
on IN B-PP O
the DT B-NP O
evening NN I-NP O
of IN B-PP O
admission NN B-NP O
after IN B-SBAR O
she PRP B-NP O
received VBD B-VP O
a DT B-NP O
dose NN I-NP O
of IN B-PP O
Levaquin NNP B-NP O
IV NNP I-NP O
in IN B-PP O
the DT B-NP O
setting NN I-NP O
of IN B-PP O
a DT B-NP O
rising VBG I-NP O
WBC NNP I-NP O
up IN B-PP O
to TO B-PP O
40K. DT B-NP O
Vasopressin NNP I-NP O
was VBD B-VP O
added VBN I-VP O
IV NNP B-NP O
, , O O
which WDT B-NP O
provided VBD B-VP O
further JJ B-NP O
support NN I-NP O
of IN B-PP O
her PRP$ B-NP O
MAP. NNP I-NP O
Intermittent NNP I-NP O
NS NNP I-NP O
fluid NN I-NP O
boluses NNS I-NP O
helped VBD B-VP O
to TO I-VP O
bring VB I-VP O
her PRP$ B-NP O
HR NNP I-NP O
down IN B-PP O
per IN B-PP O
RN NNP B-NP O
and CC O O
supported VBD B-VP O
her PRP$ B-NP O
MAPs NNS I-NP O
with IN B-PP O
her PRP$ B-NP O
PAD NN I-NP O
ranging VBG B-VP O
between IN B-PP O
18-24 CD B-NP O
and CC O O
a DT B-NP O
urine JJ I-NP O
output NN I-NP O
between IN B-PP O
30 CD B-NP O
and CC I-NP O
100 CD I-NP O
cc/hr NN I-NP O
. . O O
When WRB B-VP O
her PRP$ B-NP O
CI NNP I-NP O
dropped VBD B-VP O
to TO B-PP O
1.9 CD B-NP O
around IN B-PP O
9.30 CD B-NP O
pm NN I-NP O
with IN B-PP O
an DT B-NP O
increased VBN I-NP O
SVR NN I-NP O
of IN B-PP O
1550 CD B-NP O
, , O O
the DT B-NP O
cardiac JJ I-NP O
fellow NN I-NP O
was VBD B-VP O
called VBN I-VP O
and CC O O
the DT B-NP O
decision NN I-NP O
was VBD B-VP O
made VBN I-VP O
to TO I-VP O
wean VB I-VP O
her PRP$ B-NP O
Levophed NNP I-NP O
as IN B-PP O
tolerated JJ B-ADJP O
, , O O
which WDT B-NP O
was VBD B-VP O
then RB I-VP O
brought VBN I-VP O
down RP B-NP O
to TO B-VP O
16/hr VB I-VP O
with IN B-PP O
her PRP$ B-NP O
Dopamine NN I-NP O
having VBG B-VP O
been VBN I-VP O
weaned VBN I-VP O
off RP B-PRT O
and CC O O
continued VBD B-VP O
Dobutamine NNP B-NP O
and CC I-NP O
Vasopressin NNP I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
was VBD B-VP O
also RB I-VP O
maintained VBN I-VP O
on IN B-PP O
Reopro NNP B-NP O
and CC O O
Heparin NNP B-NP O
IV NNP I-NP O
for IN B-PP O
her PRP$ B-NP O
STEMI NNP I-NP O
. . O O
PMHx NNP B-NP O
: : O O
Hypertension NN B-NP O
DM NNP B-NP O
type NN I-NP O
2 CD O O
Hyperlipidemia NNP B-NP O
Iron NNP B-NP O
deficiency NN I-NP O
anemia NN I-NP O
with IN B-PP O
pt JJ B-NP O
refusing NN I-NP O
colonoscopy NN I-NP O
for IN B-PP O
several JJ B-NP O
months NNS I-NP O
DJD NNP B-NP O
of IN B-PP O
hands NNS B-NP O
- : O O
involving VBG B-VP O
PIP NNP B-NP O
's POS B-NP O
, , O O
DIP NNP B-NP O
's POS B-NP O
, , O O
1st JJ B-NP O
CMC's NNP I-NP O
. . O O
Spinal JJ B-NP O
Stenosis NNP I-NP O
L3-4 . O O
Bilateral JJ B-NP O
carpal JJ I-NP O
tunnel NN I-NP O
syndrome NN I-NP O
- : O O
s/p JJ B-NP O
bilateral JJ I-NP O
releases NNS I-NP O
in IN B-PP O
spring NN B-NP B-DATE
2090 CD I-NP I-DATE
. . O O
Cataracts NNS B-NP O
Hyperparathyroidism NN B-NP O
Thyroid NNP B-NP O
nodule NN I-NP O
- : O O
benign JJ B-NP O
, , I-NP O
biopsied JJ I-NP O
2089 CD I-NP B-DATE
. . O O
Allergies NNP B-NP O
: : O O
Atorvastatin NNP B-NP O
- : O O
myalgias NNS B-NP O
Pravastatin NNP B-NP O
&#8211 CD I-NP O
; : O O
myalgias NNS B-NP O
Medications NNS B-NP O
prior RB B-ADVP O
to TO B-PP O
Admission NNP B-NP O
: : O O
Atenolol NNP B-NP O
100 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
QD . O O
Ativan NNP B-NP O
0.5 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
TID NNP I-NP O
ASA NNP B-NP O
81 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
QD . O O
Colace NNP B-NP O
100 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
qd . O O
Glyburide NNP B-NP O
5MG VBD B-VP O
PO NNP B-NP O
BID NNP I-NP O
Ibuprofen NNP B-NP O
800 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
TID NNP I-NP O
K-dur NNP B-NP O
10 CD I-NP O
MEQ NNP I-NP O
PO NNP I-NP O
QD . O O
Lasix NNP B-NP O
20 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
qd . O O
Lescol NNP B-NP O
20 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
QHS . O O
Lisinopril NNP B-NP O
40 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
QD . O O
Metformin NNP B-NP O
1000 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
BID NNP I-NP O
Norvasc NNP B-NP O
10MG VBD B-VP O
PO NNP B-NP O
QD . O O
Ultram NNP B-NP O
50 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
BID NNP I-NP O
SH NNS B-NP O
: : O O
Lives NNS B-NP O
in IN B-PP O
Racine NNP B-NP B-CITY
. . O O
She PRP B-NP O
is VBZ B-VP O
married VBN I-VP O
. . O O
She PRP B-NP O
lives VBZ B-VP O
with IN B-PP O
her PRP$ B-NP O
husband NN I-NP O
. . O O
They PRP B-NP O
often RB B-ADVP O
argue VBP B-VP O
with IN B-PP O
each DT B-NP O
other JJ I-NP O
but CC O O
there EX B-NP O
is VBZ B-VP O
no DT B-NP O
history NN I-NP O
of IN B-PP O
domestic JJ B-NP O
violence NN I-NP O
. . O O
Retired VBN B-NP O
credit NN I-NP B-PROFESSION
manager NN I-NP I-PROFESSION
. . O O
FH NNP B-NP O
: : O O
Sister NNP B-NP O
s/p VBD B-VP O
thyroid DT B-NP O
surgery NN I-NP O
. . O O
No DT B-NP O
h/o NN I-NP O
RA NNP B-NP O
, , O O
SLE NNP B-NP O
, , O O
psoriasis NN B-NP O
. . O O
ROS NNP B-NP O
: : O O
As IN B-SBAR O
noted VBN B-VP O
in IN B-PP O
HPI. NNP B-NP O
Exam NNP B-NP O
: : O O
VS NNP B-NP O
: : O O
T=96.1 CD B-NP O
HR=115 CD I-NP O
SR NNP I-NP O
Augment NNP I-NP O
. . I-NP O
DBP= NNP I-NP O
124 CD I-NP O
MAP=86 IN B-PP O
RR=12 CD B-NP O
SaO2=92-100 CD I-NP O
% NN I-NP O
on IN B-PP O
FiO2 NNP B-NP O
0.5 CD I-NP O
General NNP B-NP O
: : O O
elderly JJ B-NP O
Caucasian NNP I-NP O
woman NN I-NP O
, , O O
intubated VBN B-VP O
, , O O
sedated VBN B-UCP O
HEENT NNP B-NP O
: : O O
PERRL NN B-NP O
, , O O
OGT NNP B-NP O
in IN B-PP O
place NN B-NP O
with IN B-PP O
dark JJ B-NP O
output NN I-NP O
on IN B-PP O
low JJ B-NP O
vacuum NN I-NP O
to TO B-PP O
wall NN B-NP O
suction NN I-NP O
Neck NNP B-NP O
: : O O
Supple NN B-NP O
, , O O
full JJ B-NP O
ROM NNP I-NP O
, , O O
no DT B-NP O
LAD NN I-NP O
, , O O
no DT B-NP O
central JJ I-NP O
line NN I-NP O
in IN B-PP O
the DT B-NP O
neck NN I-NP O
region NN I-NP O
( -LRB- I-NP O
PAC NNP I-NP O
via IN B-PP O
R NN B-NP O
groin NN I-NP O
) -RRB- O O
Chest NNP B-NP O
: : O O
CTA NNP B-NP O
b/l , O O
from IN B-PP O
anterior JJ B-NP O
, , O O
no DT B-NP O
wheezing JJ I-NP O
, , I-NP O
crackles NNS I-NP O
, , I-NP O
or CC I-NP O
ronchi NN I-NP O
CVS NNP B-NP O
: : O O
RRR NNP B-NP O
nl , O O
S1 NNP B-NP O
S2 NNP I-NP O
, , O O
no DT B-NP O
m/r/g NN I-NP O
, , O O
CVP NNP B-NP O
9-14 CD I-NP O
, , O O
IABP NNP B-NP O
in IN B-PP O
place NN B-NP O
, , O O
running VBG B-VP O
at IN B-PP O
1:1 CD B-NP O
Abd NNP B-NP O
: : O O
soft JJ B-NP O
, , I-NP O
nontender JJ I-NP O
, , I-NP O
nl JJ I-NP O
BS NNP I-NP O
, , O O
no DT B-NP O
rebound NN I-NP O
, , O O
IABP NNP B-NP O
via IN B-PP O
right NN B-NP O
groin NN I-NP O
Extr NNP B-NP O
: : O O
trace NN B-VP O
edema NN B-NP O
b/l NN I-NP O
, , O O
2+ JJ B-NP O
DP NNP I-NP O
pulses NNS I-NP O
present JJ I-NP O
b/l NN I-NP O
, , O O
warm JJ B-ADJP O
and CC O O
well RB B-ADJP O
perfused VBN I-ADJP O
Neuro NNP B-NP O
: : O O
sedated JJ B-NP O
, , I-NP O
not RB I-NP O
moving VBG B-VP O
spontanously RB O O
Skin NNP B-NP O
: : O O
no DT B-NP O
rashes NNS I-NP O
, , I-NP O
jaundice NN I-NP O
or CC I-NP O
cyanosis NN I-NP O
DATA NNP B-NP O
: : O O
Lytes NNS B-NP O
on IN B-PP O
admission NN B-NP O
were VBD B-VP O
normal JJ B-ADJP O
except IN B-PP O
hyponatremia NN B-NP O
, , O O
metabolic JJ B-NP O
acidosis NN I-NP O
, , O O
Bicarb NNP B-NP O
of IN B-PP O
15.9 CD B-NP O
, , O O
which WDT B-NP O
remained VBD B-VP O
around IN B-ADVP O
16 CD B-NP O
on IN B-PP O
the DT B-NP O
day NN I-NP O
of IN B-PP O
her PRP$ B-NP O
admission NN I-NP O
. . O O
Mg NN B-NP O
was VBD B-VP O
1.2 CD B-NP O
only RB I-NP O
, , O O
which WDT B-NP O
was VBD B-VP O
repleted VBN I-VP O
with IN B-PP O
4g CD B-NP O
of IN B-PP O
Mg NNP B-NP O
IV. . O O
Initial JJ B-NP O
glucose NN I-NP O
above IN B-PP O
500 CD B-NP O
, , O O
which WDT B-NP O
came VBD B-VP O
down RB B-ADVP O
to TO B-PP O
200s CD O O
Lactic JJ B-NP O
acid NN I-NP O
was VBD B-VP O
6.4 CD B-NP O
on IN B-PP O
admission NN B-NP O
, , O O
which WDT B-NP O
came VBD B-VP O
down RB B-ADVP O
to TO B-PP O
4.8 CD B-NP O
at IN B-PP O
1pm JJ B-ADJP O
. . O O
LFTs NNS B-NP O
were VBD B-VP O
only RB B-ADVP O
slightly RB B-ADJP O
abnormal JJ I-ADJP O
with IN B-PP O
normal JJ B-NP O
bilirubins NNS I-NP O
. . O O
Initial JJ B-NP O
WBC NNP I-NP O
22 CD I-NP O
, , O O
which WDT B-NP O
increased VBD B-VP O
to TO B-PP O
40 CD B-NP O
and CC O O
then RB O O
returned VBD B-VP O
to TO B-PP O
28 CD B-NP O
. . O O
Hct NNP B-NP O
dropped VBD B-VP O
from IN B-PP O
40 CD B-NP O
down IN B-PP O
to TO B-PP O
29 CD B-NP O
on IN B-PP O
day NN B-NP O
of IN B-PP O
admission NN B-NP O
over IN B-PP O
24 CD B-NP O
hours NNS I-NP O
. . O O
Plts NNS B-NP O
were VBD B-VP O
normal JJ B-ADJP O
and CC I-ADJP O
stable JJ I-ADJP O
. . O O
Coags NNS B-NP O
normal JJ I-NP O
except IN B-PP O
elevated JJ B-NP O
PTT NNP I-NP O
in IN B-PP O
setting VBG B-VP O
of IN B-PP O
IV NNP B-NP O
Heparin NNP I-NP O
. . O O
03/18/91 CD B-NP B-DATE
03/18/91 CD I-NP B-DATE
03/18/91 IN B-PP B-DATE
03/18/91 CD B-NP B-DATE
03/18/91 CD I-NP B-DATE
20:25 CD B-NP O
13 CD I-NP O
:26 IN B-PP O
11:08 CD B-NP O
11:06 CD I-NP O
07 CD I-NP O
:05 . O O
NT-BNP NNP B-NP O
3161(HT) CD I-NP O
CK NNP B-NP O
4877( CD I-NP O
H) NNP I-NP O
5811( CD I-NP O
H) NNP I-NP O
4268( CD I-NP O
H) NNP B-NP O
382( CD I-NP O
H) . O O
CK-MB NNP B-NP O
348.0( CD I-NP O
H) NNP I-NP O
393.7( CD I-NP O
H) NNP B-NP O
30.4( CD I-NP O
H) . O O
CKMBRI NNP B-NP O
7.1( CD I-NP O
H) NNP B-NP O
6.8( CD I-NP O
H) . O O
TROP-T NN B-NP O
25.56( CD I-NP O
H) NNP I-NP O
18.01( CD I-NP O
H) NNP I-NP O
13.89( CD I-NP O
H) NNP B-NP O
0.66( CD I-NP O
H) . O O
Fasting VBG B-NP O
lipids NNS I-NP O
: : O O
CHOL NNP B-NP O
195( CD I-NP O
T NNP I-NP O
) -RRB- O O
TRIG NNP B-NP O
155( CD I-NP O
H) . O O
HDL NNP B-NP O
31( JJ I-NP O
L NNP I-NP O
) -RRB- O O
LDL NNP B-NP O
133( JJ I-NP O
T NNP I-NP O
) -RRB- O O
Initial JJ B-NP O
ABG NNP I-NP O
was VBD B-VP O
7.12/39/61 CD B-NP O
, , O O
which WDT B-NP O
gradually RB B-ADVP O
improved VBD B-VP O
up RP B-PRT O
to TO B-PP O
7.37/32/110 CD B-NP O
in IN B-PP O
the DT B-NP O
evening NN I-NP O
of IN B-PP O
her PRP$ B-NP O
admission NN I-NP O
. . O O
CXR NN B-NP O
: : O O
Bilateral NNP B-NP O
somewhat RB I-NP O
symmetric JJ I-NP O
perihilar NN I-NP O
airspace NN I-NP O
opacities NNS I-NP O
both DT B-NP O
lungs NNS I-NP O
. . O O
This DT B-NP O
could MD B-VP O
be VB I-VP O
edema NN B-NP O
or CC I-NP O
pneumonia NN I-NP O
. . O O
No DT B-NP O
large JJ I-NP O
pleural JJ I-NP O
effusions NNS I-NP O
or CC I-NP O
pneumothoraces NNS I-NP O
. . O O
Interval NN B-NP O
placement NN I-NP O
of IN B-PP O
the DT B-NP O
due JJ I-NP O
left NN I-NP O
lower JJR B-NP O
lobe NN I-NP O
monitor NN I-NP O
line NN I-NP O
below IN B-PP O
. . B-NP O
Endotracheal NNP I-NP O
tube NN I-NP O
and CC O O
4.6 CD B-NP O
cm NN I-NP O
. . O O
NG VBD B-VP O
tube NN B-NP O
to TO B-PP O
stomach NN B-NP O
. . O O
CT NNP B-NP O
Chest/Abdomen/Pelvis NNP I-NP O
&#8211 CC I-NP O
; : O O
AD NN B-NP O
protocol NN I-NP O
: : O O
No DT B-NP O
evidence NN I-NP O
of IN B-PP O
aortic JJ B-NP O
dissection NN I-NP O
, , O O
narrowed VBN B-VP O
SMA NNP B-NP O
at IN B-PP O
its PRP$ B-NP O
origin NN I-NP O
. . O O
Bilateral NNP B-NP O
consolidation NN I-NP O
in IN B-PP O
the DT B-NP O
dependent JJ I-NP O
portions NNS I-NP O
of IN B-PP O
the DT B-NP O
upper JJ I-NP O
and CC I-NP O
lower JJR I-NP O
lobes NNS I-NP O
, , O O
consistent JJ B-ADJP O
with IN B-PP O
aspiration NN B-NP O
and/or CC I-NP O
pneumonia NN I-NP O
. . O O
Interlobular NNP B-NP O
septal JJ I-NP O
thickening NN I-NP O
and CC O O
small JJ B-NP O
bilateral JJ I-NP O
pleural JJ I-NP O
effusions NNS I-NP O
, , O O
consistent JJ B-ADJP O
with IN B-PP O
pulmonary JJ B-NP O
edema NN I-NP O
. . O O
Indeterminate NNP B-NP O
hypodense NN I-NP O
lesion NN I-NP O
in IN B-PP O
the DT B-NP O
body NN I-NP O
of IN B-PP O
the DT B-NP O
pancreas NNS I-NP O
. . O O
Differential JJ B-NP O
considerations NNS I-NP O
include VBP B-VP O
a DT B-NP O
cyst NN I-NP O
and CC O O
IPMN. NNP B-NP O
Bilateral NNP I-NP O
renal NNP I-NP O
hypodensities NNS I-NP O
, , O O
the DT B-NP O
largest JJS I-NP O
of IN B-PP O
which WDT B-NP O
are VBP B-VP O
consistent JJ B-ADJP O
with IN B-PP O
simple JJ B-NP O
cysts NNS I-NP O
. . O O
Heterogeneous NNP B-NP O
thyroid VBD B-VP O
gland NN B-NP O
, , O O
with IN B-PP O
areas NNS B-NP O
of IN B-PP O
hypodensity NN B-NP O
. . O O
Bedside NN B-NP O
TTE NNP I-NP O
: : O O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
papillary NN B-NP O
muscle NN I-NP O
rupture NN I-NP O
, , O O
moderate JJ B-NP O
MR NNP I-NP O
present NN I-NP O
EKG NNP B-NP O
in IN B-PP O
ED NNP B-NP O
at IN B-PP O
6.32AM CD B-NP O
: : O O
NSR NNP B-NP O
, , O O
STE NNP B-NP O
in IN B-PP O
I PRP B-NP O
, , O O
II NNP B-NP O
, , O O
aVF NN B-NP O
, , O O
V5 NNP B-NP O
, , O O
V6 . O O
EKG NNP B-NP O
in IN B-PP O
ED NNP B-NP O
at IN B-PP O
7.31AM CD B-NP O
: : O O
RAD NN B-NP O
, , O O
VT NNP B-NP O
, , O O
STE NNP B-NP O
in IN B-PP O
I PRP B-NP O
, , O O
aVL RB B-ADVP O
, , O O
V5,V6 . O O
EKG NNP B-NP O
on IN B-PP O
CCU NNP B-NP O
Admission NNP I-NP O
: : O O
NSR NNP B-NP O
at IN B-PP O
113 CD B-NP O
, , O O
RBBB NNP B-NP O
, , O O
left VBD B-VP O
posterior JJ B-NP O
fascicular JJ I-NP O
block NN I-NP O
, , O O
3-4 CD B-NP O
mm CD I-NP O
STE NNP I-NP O
in IN B-PP O
V4-V6 NNP B-NP O
, , O O
2-3 CD B-NP O
mm CD I-NP O
in IN B-PP O
II NNP B-NP O
,III NNP I-NP O
, , O O
AvF NNP B-NP O
Repeat NN B-NP O
EKG NNP I-NP O
9 CD I-NP O
hours NNS I-NP O
after IN B-PP O
CCU NNP B-NP O
Admission NNP I-NP O
: : O O
NSR NNP B-NP O
at IN B-PP O
99 CD B-NP O
, , O O
RBBB NNP B-NP O
, , O O
left VBD B-VP O
posterior JJ B-NP O
fascicular JJ I-NP O
block NN I-NP O
, , O O
3-4 CD B-NP O
mm CD I-NP O
STE NNP I-NP O
in IN B-PP O
V4-V6 NNP B-NP O
, , O O
II NNP B-NP O
,III NNP I-NP O
, , O O
AvF NNP B-NP O
resolving NN I-NP O
. . O O
Impression NN B-NP O
: : O O
79 CD B-NP B-AGE
yo NNP I-NP O
lady NN I-NP O
with IN B-PP O
DM NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
HL NNP B-NP O
who WP B-NP O
presented VBD B-VP O
with IN B-PP O
lateral JJ B-NP O
STEMI NNP I-NP O
with IN B-PP O
occluded JJ B-NP O
OM1 NNP I-NP O
, , O O
s/p NN B-NP O
BM NNP I-NP O
stent NN I-NP O
and CC O O
is VBZ B-VP O
now RB B-ADVP O
in IN B-PP O
cardiogenic JJ B-NP O
and CC I-NP O
septic JJ I-NP O
shock NN I-NP O
. . O O
Plan NNP B-NP O
: : O O
1 LS O O
. . B-NP O
CV NNP I-NP O
Pump NNP I-NP O
: : O O
cardiogenic JJ B-NP O
shock NN I-NP O
: : O O
continue VB B-VP O
vasopressor NN B-NP O
and CC I-NP O
inotrope NN I-NP O
support NN I-NP O
with IN B-PP O
Dobutamine NNP B-NP O
, , O O
Levophed NNP B-NP O
, , O O
Vasopressin NNP B-NP O
, , O O
goal NN B-NP O
to TO B-VP O
wean VB I-VP O
Levophed VBN I-VP O
to TO B-VP O
reduce VB I-VP O
afterload NN B-NP O
and CC I-NP O
increase NN I-NP O
CI NNP I-NP O
, , O O
continue VBP B-VP O
to TO I-VP O
give VB I-VP O
fluid NN B-NP O
boluses NNS I-NP O
intermittently RB B-ADVP O
as IN B-SBAR O
she PRP B-NP O
appeared VBD B-VP O
preload RB B-ADJP O
dependent JJ I-ADJP O
possibly RB B-ADJP O
due JJ I-ADJP O
to TO B-PP O
RV NN B-NP O
involvement NN I-NP O
, , O O
MAP NNP B-NP O
goal NN I-NP O
above IN B-PP O
65 CD B-NP O
, , O O
goal NN B-NP O
to TO B-VP O
keep VB I-VP O
CI NNP B-NP O
above IN B-PP O
2.2 CD B-NP O
, , O O
f/u CC O O
urine JJ B-NP O
output NN I-NP O
with IN B-PP O
goal NN B-NP O
to TO B-VP O
keep VB I-VP O
above IN B-PP O
25 CD B-NP O
, , O O
trending VBG B-VP O
lactic JJ B-NP O
acid NN I-NP O
2. . B-NP O
CV NNP I-NP O
Ischemia NNP I-NP O
: : O O
STEMI NNP B-NP O
, , O O
cont NN B-NP O
. . O O
ASA NNP B-NP O
, , O O
Plavix NNP B-NP O
, , O O
Heparin NNP B-NP O
, , O O
Reopro NNP B-NP O
, , O O
holding VBG B-VP O
BB NNP B-NP O
and CC I-NP O
ACE NNP I-NP O
in IN B-PP O
setting VBG B-VP O
of IN B-PP O
hypotension NN B-NP O
, , O O
will MD B-VP O
check VB I-VP O
HbA1c . O O
3. . B-NP O
CV NNP I-NP O
Rhythm NNP I-NP O
: : O O
currently RB B-ADVP O
NSR NNP B-NP O
, , O O
on IN B-PP O
Tele NNP B-NP O
4 CD B-LST O
. . O O
Septic NNP B-NP O
shock NN I-NP O
: : O O
aspiration NN B-NP O
event NN I-NP O
vs. IN B-PP O
possibly RB B-NP O
CAP NNP I-NP O
, , O O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
other JJ B-NP O
infectious JJ I-NP O
source NN I-NP O
, , O O
covering VBG B-VP O
empirically RB B-ADVP O
with IN B-PP O
Vancomycin/Levaquin NNP B-NP O
IV NNP I-NP O
given VBN I-NP O
absence NN I-NP O
of IN B-PP O
recent JJ B-NP O
hospitalization NN I-NP O
over IN B-PP O
the DT B-NP O
past JJ I-NP O
90 CD I-NP O
days NNS I-NP O
, , O O
checking VBG B-VP O
C.diff RB B-ADVP O
, , O O
will MD B-VP O
have VB I-VP O
low JJ B-NP O
threshold NN I-NP O
to TO B-VP O
broaden VB I-VP O
coverage NN B-NP O
further RBR B-ADVP O
if IN B-SBAR O
necessary JJ B-UCP O
5 CD B-NP O
. . O O
HTN NNP O O
: : O O
currently RB B-ADVP O
hypotensive NN B-NP O
, , O O
holding VBG B-VP O
BP NNP B-NP O
meds NNS I-NP O
6 CD B-NP O
. . O O
DM NNP B-NP O
: : O O
holding VBG B-VP O
Metformin NNP B-NP O
, , O O
RISS NNP B-NP O
7. DT B-NP O
FEN NNP I-NP O
: : O O
NPO NNP B-VP O
for IN B-NP O
now RB B-ADVP O
with IN B-PP O
NGT NNP B-NP O
on IN B-PP O
continous JJ B-NP O
suctioning NN I-NP O
8. CD B-NP O
Prophylaxis NNP I-NP O
: : O O
Heparin NNP B-NP O
IV NNP I-NP O
, , O O
PPI NNP B-NP O
IV NNP I-NP O
bid NN I-NP O
9 CD B-NP O
. . O O
Code NNP B-NP O
Status NNP I-NP O
: : O O
Full NNP B-NP O
Code NNP I-NP O
10 CD B-NP O
. . O O
Dispo NNP B-NP O
: : O O
pending VBG B-NP O
resolution NN I-NP O
of IN B-PP O
acute JJ B-NP O
medical JJ I-NP O
issues NNS I-NP O
Xai-Micah NNP B-NP B-DOCTOR
Church NNP I-NP I-DOCTOR
, , O O
MD NNP B-NP O
- : O O
Pager NNP B-VP O
# # B-NP O
73615 CD I-NP B-PHONE
Junior NNP B-NP O
resident NN I-NP O
, , O O
Department NNP B-NP O
of IN B-PP O
Internal NNP B-NP O
Medicine NNP I-NP O
