Record NNP B-NP O
date NN I-NP O
: : O O
2073-10-24 CD O B-DATE
10/24/73 CD O B-DATE
This DT B-NP O
is VBZ B-VP O
my PRP$ B-NP O
first JJ I-NP O
visit NN I-NP O
with IN B-PP O
Teresa NNP B-NP B-PATIENT
Hardy NNP I-NP I-PATIENT
( -LRB- I-NP O
MR# JJ I-NP O
36052413 CD I-NP B-MEDICALRECORD
) -RRB- I-NP O
, , O O
a DT B-NP O
54 CD I-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
here RB B-ADVP O
to TO O O
meet VB B-VP O
her PRP$ B-NP O
new JJ I-NP O
PCP. NNP I-NP O
She PRP B-NP O
has VBZ B-VP O
not RB I-VP O
seen VBN I-VP O
a DT B-NP O
doctor NN I-NP O
in IN B-PP O
many JJ B-NP O
years NNS I-NP O
. . O O
She PRP B-NP O
made VBD B-VP O
this DT B-NP O
appt NN I-NP O
, , O O
because IN B-SBAR O
she PRP B-NP O
had VBD B-VP O
heavy JJ B-NP O
vaginal JJ I-NP O
bleeding NN I-NP O
2 CD B-NP O
weeks NNS I-NP O
ago RB B-ADVP O
. . O O
She PRP B-NP O
normally RB B-ADVP O
has VBZ B-VP O
her PRP$ I-VP O
periods NNS B-NP O
q28d VBD B-VP O
, , O O
with IN B-PP O
5 CD B-NP O
days NNS I-NP O
of IN B-PP O
heavy JJ B-NP O
flow NN I-NP O
. . O O
Her PRP$ B-NP O
last JJ I-NP O
period NN I-NP O
lasted VBD B-VP O
for IN B-PP O
15 CD B-NP O
days NNS I-NP O
with IN B-PP O
the DT B-NP O
usual JJ I-NP O
clots NNS I-NP O
and CC O O
heavy JJ B-NP O
flow NN I-NP O
. . O O
The DT B-NP O
bleeding NN I-NP O
stopped VBD B-VP O
2 CD B-NP O
weeks NNS I-NP O
ago RB B-ADVP O
, , O O
and CC O O
there EX B-NP O
is VBZ B-VP O
no DT B-NP O
spotting NN I-NP O
now RB B-ADVP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
abd NN I-NP O
pain NN I-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
possiblity NN B-NP O
of IN B-PP O
pregnancy NN B-NP O
, , O O
although IN B-SBAR O
she PRP B-NP O
has VBZ B-VP O
unprotected JJ B-NP O
intercourse NN I-NP O
with IN B-PP O
a DT B-NP O
longtime JJ I-NP O
partner NN I-NP O
. . O O
PMH: NNP B-NP O
staph NN I-NP O
aureus NN I-NP O
UTI NNP B-NP O
2066 CD I-NP B-DATE
h/o NN B-NP O
multiple JJ B-NP O
UTI NNP I-NP O
's POS B-LST O
last JJ B-NP O
PAP NNP I-NP O
in IN B-PP O
5/64 CD B-NP B-DATE
- : O O
squamous JJ B-NP O
metaplasia NN I-NP O
Allergies NNP B-NP O
: : O O
NKDA NNP O O
Meds NNS B-NP O
: : O O
MVI NNP B-NP O
, , O O
Vit NNP B-NP O
E NNP I-NP O
, , O O
Calcium NNP B-NP O
supplement NN I-NP O
SHx NNP B-NP O
: : O O
former JJ B-NP O
banker NN I-NP B-PROFESSION
,but CC O O
now RB B-ADVP O
investment NN B-NP B-PROFESSION
consultant NN I-NP I-PROFESSION
. . O O
No DT B-NP O
tob NN I-NP O
, , O O
EtOH NNP B-NP O
, , O O
IVDA. NNP B-NP O
Reports NNS B-VP O
1 CD B-NP O
blood NN I-NP O
transufion NN I-NP O
before IN B-PP O
2064 CD B-NP B-DATE
when WRB B-ADVP O
she PRP B-NP O
had VBD B-VP O
a DT B-NP O
UTI. NNP I-NP O
Divorced NNP I-NP O
. . O O
No DT B-NP O
children NNS I-NP O
. . O O
Fhx NNP B-NP O
: : O O
M NNP B-NP O
90 CD I-NP B-AGE
- : O O
DM JJ B-NP O
, , I-NP O
esophageal JJ I-NP O
CA NNP I-NP O
F NNP B-NP O
- : O O
died VBD B-VP O
of IN B-PP O
old JJ B-NP O
age NN I-NP O
5 CD B-NP O
brothers NNS I-NP O
and CC O O
3 CD B-NP O
sisters NNS I-NP O
2 CD B-NP O
brothers NNS I-NP O
and CC O O
1 CD B-NP O
sister NN I-NP O
with IN B-PP O
HTN NNP B-NP O
, , O O
1 CD B-NP O
sister NN I-NP O
with IN B-PP O
DM. NNP B-NP O
PE NN B-NP O
: : O O
pleasant JJ B-NP O
, , I-NP O
cooperative JJ I-NP O
, , I-NP O
talkative JJ I-NP O
, , I-NP O
obese JJ I-NP O
, , I-NP O
NAD NNP I-NP O
VS NNP B-NP O
: : O O
P96 CD B-NP O
BP NNP I-NP O
162/100 CD I-NP O
Skin NNP B-NP O
: : O O
warm JJ B-NP O
, , I-NP O
dry JJ I-NP O
, , O O
no DT B-NP O
rashes NNS I-NP O
HEENT NNP B-NP O
: : O O
NC NNP B-NP O
AT WDT B-NP O
EOMI NNP I-NP O
PERRL NNP I-NP O
3/3-> JJ I-NP O
2/2 CD I-NP O
, , O O
OP NNP B-NP O
clear JJ I-NP O
Neck NNP B-NP O
: : O O
no DT B-NP O
LAD NN I-NP O
or CC O O
thyromegaly RB B-ADVP O
, , O O
carotids NNS B-NP O
2+ VBP B-VP O
s PRP B-NP O
bruits NNS B-NP O
, , O O
JVP NNP B-NP O
6 CD I-NP O
cm NN I-NP O
Lungs NNP B-NP O
: : O O
CTA NNP B-NP O
B NNP I-NP O
CV NNP B-NP O
: : O O
RRR NNP B-NP O
S1 NNP I-NP O
S2 . O O
no DT B-NP O
m/r/g NN I-NP O
Breasts NNS B-NP O
: : O O
symmetric JJ B-ADJP O
. . O O
NO DT O O
palpable JJ B-NP O
masses NNS I-NP O
Abd NNP B-NP O
: : O O
obese NN B-NP O
, , O O
NT NNP B-NP O
ND NNP I-NP O
+ NNP I-NP O
BS NNP I-NP O
Back RB B-ADVP O
: : O O
no DT B-NP O
CVA NNP I-NP O
, , I-NP O
spinal JJ I-NP O
, , I-NP O
paraspinal JJ I-NP O
tenderness NN I-NP O
Rectal NNP B-NP O
: : O O
heme NN B-NP O
negative JJ I-NP O
, , O O
no DT B-NP O
masses NNS I-NP O
Pelvic NNP B-NP O
: : O O
normal JJ B-NP O
external JJ I-NP O
genitalia NNS I-NP O
, , O O
mild JJ B-NP O
vaginal JJ I-NP O
prolapse NN I-NP O
. . B-NP O
Cervix NN I-NP O
normal JJ I-NP O
. . O O
No UH O O
lesions NNS B-NP O
or CC I-NP O
masses NNS I-NP O
. . O O
PAP NN B-NP O
samples NNS I-NP O
taken VBN B-VP O
. . B-NP O
Bimanual NNP I-NP O
exam NN I-NP O
unremarkable JJ O O
Ext JJ B-NP O
: : O O
trace NN B-NP O
to TO B-PP O
1+ CD B-NP O
BLE NN I-NP O
edema NN I-NP O
( -LRB- I-NP O
pretibial NN I-NP O
) -RRB- O O
Neuro NNP B-NP O
: : O O
nonfocal JJ O O
Impression NN B-NP O
: : O O
54 CD B-NP B-AGE
yo NNP I-NP O
perimenopausal JJ I-NP O
woman NN I-NP O
. . O O
Plan NNP B-NP O
: : O O
1 CD B-NP O
. . O O
GYN NNP O O
- : O O
prolonged JJ B-NP O
menstrual JJ I-NP O
cycle NN I-NP O
likely JJ I-NP O
from IN B-PP O
perimenopausal JJ B-NP O
state NN I-NP O
. . O O
Since IN O O
this DT B-NP O
was VBD B-VP O
her PRP$ B-NP O
first JJ I-NP O
episode NN I-NP O
of IN B-PP O
prolonged JJ B-NP O
bleeding NN I-NP O
, , O O
will MD B-VP O
not RB I-VP O
pursue VB I-VP O
further JJ B-NP O
w/u NN I-NP O
at IN B-PP O
this DT B-NP O
point NN I-NP O
. . O O
Pt '' O O
given VBN B-NP O
reassurance NN I-NP O
, , O O
and CC O O
asked VBD B-VP O
to TO I-VP O
continue VB I-VP O
to TO I-VP O
record VB I-VP O
the DT B-NP O
dates NNS I-NP O
and CC O O
duration NN B-NP O
of IN B-PP O
her PRP$ B-NP O
menses NNS I-NP O
. . O O
Pt NNP B-NP O
denied VBD B-VP O
h/o NN B-NP O
fibroids NNS I-NP O
or CC O O
FHx NNP B-NP O
of IN B-PP O
GYN NNP B-NP O
cancer NN I-NP O
. . O O
2. DT B-NP O
CV NNP I-NP O
- : O O
pt JJ B-NP O
reports NNS I-NP O
h/o IN B-PP O
BP NNP B-NP O
's POS B-NP O
of IN I-NP O
160/8 CD I-NP O
0 CD I-NP O
in IN B-PP O
the DT B-NP O
past NN I-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
162/100 CD B-NP O
today NN I-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
very RB B-ADJP O
reluctant JJ I-ADJP O
to TO B-VP O
initiate VB I-VP O
any DT B-NP O
BP NNP I-NP O
medicine NN I-NP O
( -LRB- O O
I PRP B-NP O
suggested VBD B-VP O
atenolol IN B-PP O
25 CD B-NP O
mg NN I-NP O
po NN B-NP O
QAM NNP I-NP O
) -RRB- I-NP O
, , O O
and CC O O
want VB B-VP O
to TO I-VP O
try VB I-VP O
diet NN B-NP O
and CC I-NP O
exercise NN I-NP O
first RB B-ADVP O
. . O O
She PRP B-NP O
understands VBZ B-VP O
the DT B-NP O
health NN I-NP O
risks NNS B-NP O
of IN B-PP O
HTN NNP B-NP O
and CC O O
knows VBZ B-VP O
that IN B-SBAR O
it PRP B-NP O
is VBZ B-VP O
very RB B-ADJP O
common JJ I-ADJP O
among IN B-PP O
African JJ B-NP O
Americans NNPS I-NP O
. . O O
Will MD O O
follow VB B-VP O
this DT B-NP O
issue NN I-NP O
closely RB B-ADVP O
and CC O O
readdress VBD B-VP O
at IN B-PP O
next JJ B-NP O
visit NN I-NP O
. . O O
3. CD B-NP O
Health NNP I-NP O
maintenance NN I-NP O
- : O O
await VBP B-VP O
PAP NNP B-NP O
results NNS I-NP O
. . O O
Will NNP B-NP O
check NN I-NP O
CBC NNP I-NP O
, , I-NP O
SMA7 NNP I-NP O
and CC I-NP O
lipid POS I-NP O
panel NN B-NP O
today NN I-NP O
. . O O
Will MD B-VP O
schedule VB I-VP O
screening VBG I-VP O
mammogram NN B-NP O
at IN B-PP O
next JJ B-NP O
visit NN I-NP O
. . O O
4 LS O O
. . O O
f/u VB B-VP O
with IN B-PP O
me PRP B-NP O
in IN B-PP O
1 CD B-NP O
month NN I-NP O
. . O O
Preceptor NNP B-NP O
EVANS,NELSON NNP I-NP O
MAC NNP I-NP O
,M.D. NNP I-NP O
Note NNP I-NP O
: : O O
Seen NNP B-NP O
with IN B-PP O
Dr. NNP B-NP O
Thorpe NNP I-NP O
and CC O O
discussed VBD B-VP O
. . B-NP O
Is VBZ B-VP O
perimenopausal NN B-NP O
, , O O
had VBD B-VP O
15-day JJ B-NP O
period NN I-NP I-DOCTOR
once RB B-ADVP I-DOCTOR
. . O I-DOCTOR
No DT B-NP I-DOCTOR
pap NN I-NP I-DOCTOR
since IN B-PP O
2064 CD B-NP O
. . O O
BP NNP B-NP O
was VBD B-VP O
162/100 CD B-NP O
. . O O
Dr. NNP B-NP O
Thorpe NNP I-NP B-DOCTOR
did VBD B-VP O
a DT B-NP O
pap NN I-NP O
, , O O
will MD B-VP O
follow VB I-VP O
periods NNS B-NP O
. . O O
SUspect NN B-NP O
she PRP B-NP O
is VBZ B-VP O
hypertensive JJ B-ADJP O
, , O O
but CC O O
she PRP B-NP O
is VBZ B-VP O
reluctant JJ B-ADJP O
to TO B-VP O
take VB I-VP O
meds NNS B-NP O
. . O O
Discussed VBN O O
risks NNS B-NP O
of IN B-PP O
htn NN B-NP O
with IN B-PP B-DATE
her PRP B-NP O
. . O O
She PRP B-NP O
will MD B-VP O
FU VB I-VP O
with IN B-PP O
Dr. NNP B-NP O
Thorpe NNP I-NP O
. . O I-DOCTOR
******** NN B-NP I-DOCTOR
Approved NNP I-NP O
by IN B-PP O
Preceptor NNP B-NP O
EVANS,NELSON NNP I-NP O
MAC NNP I-NP O
,M.D. NNP I-NP O
******** . O O
