Record NNP B-NP O
date NN I-NP O
: : O O
2093-09-13 CD O B-DATE
HMS NNP B-NP B-HOSPITAL
Cardiovascular NNP I-NP O
Division NNP I-NP O
CVD NNP B-NP O
R56 CD I-NP O
82 CD B-NP B-STREET
Ferry NNP I-NP I-STREET
Road NNP I-NP I-STREET
OCAMPO NNP I-NP I-PATIENT
, , O I-PATIENT
NATHAN-OLIVER NNP B-NP I-PATIENT
Foxborough NNP B-NP B-CITY
, , O O
TX NNP B-NP B-STATE
58771 CD I-NP B-ZIP
80531359 CD O B-MEDICALRECORD
( -LRB- B-NP I-PHONE
564 CD I-NP I-PHONE
) -RRB- I-NP I-PHONE
243-4471 CD I-NP I-PHONE
09/13/93 CD O B-DATE
Kenneth NNP B-NP B-DOCTOR
X NNP I-NP I-DOCTOR
. . I-NP I-DOCTOR
Sylvester NNP I-NP I-DOCTOR
, , I-NP I-DOCTOR
Jr. NNP I-NP I-DOCTOR
, , I-NP O
M.D. NNP I-NP O
Holden NNP B-NP B-HOSPITAL
District NNP I-NP I-HOSPITAL
Hospital NN I-NP I-HOSPITAL
62 CD B-NP B-STREET
Ferry NNP I-NP I-STREET
Road NNP I-NP I-STREET
Cardiology NNP I-NP O
Foxborough NNP B-NP B-CITY
, , O O
TX NNP B-NP B-STATE
58771 CD I-NP B-ZIP
Dear NNP B-NP O
Ken NNP I-NP B-DOCTOR
: : O O
Mr. NNP B-NP O
Ocampo NNP I-NP B-PATIENT
returns VBZ B-VP O
to TO B-PP O
the DT B-NP O
office NN I-NP O
following VBG B-VP O
his PRP$ B-NP O
recent JJ I-NP O
coronary JJ I-NP O
artery NN I-NP O
bypass VBD B-VP O
graft NN B-NP O
surgery NN I-NP O
. . O O
As IN B-SBAR O
you PRP B-NP O
know VBP B-VP O
, , O O
Dr. NNP B-NP O
Todd NNP I-NP B-DOCTOR
Banks NNPS I-NP I-DOCTOR
took VBD B-VP O
him PRP B-NP O
to TO B-PP O
the DT B-NP O
operating NN I-NP O
room NN I-NP O
on IN B-PP O
August NNP B-NP B-DATE
17th JJ I-NP I-DATE
, , O O
at IN B-PP O
which WDT B-NP O
point NN I-NP O
, , O O
he PRP B-NP O
underwent VBD B-VP O
multivessel NN B-NP O
bypass NN I-NP O
surgery NN I-NP O
with IN B-PP O
placement NN B-NP O
of IN B-PP O
a DT B-NP O
left JJ I-NP O
internal JJ I-NP O
mammary NN I-NP O
artery NN I-NP O
to TO B-PP O
his PRP$ B-NP O
LAD NN I-NP O
and CC O O
reverse VB B-VP O
saphenous JJ B-NP O
vein NN I-NP O
grafts NNS I-NP O
to TO B-PP O
his PRP$ B-NP O
PDA NNP I-NP O
, , O O
first RB B-ADVP O
obtuse VB B-VP O
marginal JJ B-ADJP O
, , O O
and CC O O
second JJ B-NP O
obtuse NN I-NP O
marginal JJ I-NP O
. . O O
He PRP B-NP O
tolerated VBD B-VP O
the DT B-NP O
procedure NN I-NP O
uneventfully RB B-ADVP O
. . O O
His PRP$ B-NP O
postoperative JJ I-NP O
course NN I-NP O
was VBD B-VP O
notable JJ B-ADJP O
for IN B-PP O
intermittent NN B-NP O
atrial JJ I-NP O
fibrillation NN I-NP O
for IN B-PP O
which WDT B-NP O
he PRP B-NP O
was VBD B-VP O
eventually RB I-VP O
started VBN I-VP O
on IN B-PP O
amiodarone JJ B-NP O
therapy NN I-NP O
. . O O
He PRP B-NP O
also RB B-ADVP O
had VBD B-VP O
some DT B-NP O
difficulty NN I-NP O
with IN B-PP O
urinary JJ B-NP O
retention NN I-NP O
and CC O O
had VBD B-VP O
a DT B-NP O
Foley NNP I-NP O
placed VBD B-VP O
, , O O
which WDT B-NP O
has VBZ B-VP O
stayed VBN I-VP O
in IN B-PP O
since IN B-PP O
discharge NN B-NP O
. . O O
He PRP B-NP O
spent VBD B-VP O
approximately RB B-NP O
10 CD I-NP O
days NNS I-NP O
in IN B-PP O
Gadsden NNP B-NP B-HOSPITAL
Medical NNP I-NP I-HOSPITAL
and CC O O
has VBZ B-VP O
now RB I-VP O
been VBN I-VP O
discharged VBN I-VP O
to TO B-PP O
home NN B-NP O
. . O O
Currently RB B-ADVP O
, , O O
he PRP B-NP O
complains VBZ B-VP O
of IN B-PP O
a DT B-NP O
variety NN I-NP O
of IN B-PP O
musculoskeletal NN B-NP O
complaints NNS I-NP O
involving VBG B-VP O
his PRP$ B-NP O
upper JJ I-NP O
chest NN I-NP O
and CC O O
left JJ B-NP O
arm NN I-NP O
; : O O
however RB B-ADVP O
, , O O
he PRP B-NP O
denies VBZ B-VP O
symptoms NNS B-NP O
of IN B-PP O
active JJ B-NP O
angina NN I-NP O
, , O O
congestive JJ B-NP O
failure NN I-NP O
, , O O
or CC O O
sensed VBD B-VP O
arrhythmias NNS B-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
slowly RB I-VP O
recovering VBG I-VP O
his PRP$ B-NP O
overall JJ I-NP O
strength NN I-NP O
. . O O
The DT B-NP O
last JJ I-NP O
blood NN I-NP O
studies NNS I-NP O
available JJ B-ADJP O
to TO B-PP O
me PRP B-NP O
indicate VBP B-VP O
a DT B-NP O
random JJ I-NP O
glucose NN I-NP O
of IN B-PP O
118 CD B-NP O
, , O O
creatinine CD B-NP O
of IN B-PP O
1.1 CD B-NP O
, , O O
normal JJ B-NP O
liver NN I-NP O
function NN I-NP O
studies NNS I-NP O
, , O O
cholesterol NN B-NP O
of IN B-PP O
124 CD B-NP O
, , O O
triglyceride NN B-NP O
of IN B-PP O
124 CD B-NP O
, , O O
HDL NNP B-NP O
39 CD I-NP O
, , O O
LDL NNP B-NP O
60 CD I-NP O
, , O O
hematocrit NN B-NP O
of IN B-PP O
33.3 CD B-NP O
. . O O
On IN B-PP O
a DT B-NP O
regimen NN I-NP O
of IN B-PP O
amiodarone JJ B-NP O
200 CD I-NP O
mg JJ I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
enteric-coated JJ B-NP O
aspirin NN I-NP O
81 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
Niferex NNP B-NP O
150 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
p.r.n NN B-NP O
. . O O
Tylenol NNP B-NP O
No. NN I-NP O
3 CD B-NP O
, , O O
Hytrin NNP B-NP O
10 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
Proscar NNP B-NP O
5 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
Toprol-XL NNP B-NP O
50 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
Pletal NNP B-NP O
100 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
b.i.d. '' O O
, , O O
possibly RB B-ADVP O
simvastatin VBG B-VP O
at IN B-PP O
20 CD B-NP O
mg JJ I-NP O
p.o NN I-NP O
. . O O
q.d '' O O
. . O O
Physical JJ B-NP O
exam NN I-NP O
today NN I-NP O
reveals VBZ B-VP O
a DT B-NP O
pleasant JJ I-NP O
male NN I-NP O
in IN B-PP O
no DT B-NP O
acute JJ I-NP O
distress NN I-NP O
. . O O
Blood NN B-NP O
pressure NN I-NP O
right JJ I-NP O
arm NN I-NP O
sitting VBG B-VP O
110/50 CD B-NP O
, , O O
heart NN B-NP O
rate NN I-NP O
65 CD I-NP O
and CC O O
regular JJ B-NP O
, , O O
respirations NNS B-NP O
14 CD I-NP O
and CC O O
unlabored JJ B-ADVP O
, , O O
and CC O O
weight NN B-NP O
183 CD I-NP O
pounds NNS I-NP O
. . O O
The DT B-NP O
neck NN I-NP O
is VBZ B-VP O
supple NN B-NP O
, , O O
JVP NNP B-NP O
flat JJ I-NP O
, , O O
carotids NNS B-NP O
are VBP B-VP O
2+ JJ B-ADJP O
without IN B-PP O
significant JJ B-NP O
bruits NNS I-NP O
. . O O
Chest NNP B-NP O
is VBZ B-VP O
clear JJ B-ADJP O
. . O O
Cardiac NNP B-NP O
exam NN I-NP O
shows VBZ B-VP O
normal JJ B-NP O
S1 NNP I-NP O
, , O O
physiologically RB B-VP O
split VBN I-VP O
S2 NN B-NP O
with IN B-PP O
1/6 CD B-NP O
systolic JJ I-NP O
ejection NN I-NP O
murmur NN I-NP O
radiating NN I-NP O
from IN B-PP O
the DT B-NP O
apex NN I-NP O
to TO B-PP O
the DT B-NP O
base NN I-NP O
, , O O
no DT B-NP O
significant JJ I-NP O
diastolic JJ I-NP O
murmur NN I-NP O
or CC I-NP O
rub NN I-NP O
. . O O
The DT B-NP O
abdomen NN I-NP O
is VBZ B-VP O
benign JJ B-ADJP O
. . O O
Extremities NNS B-NP O
reveal VBP B-VP O
markedly RB I-VP O
diminished VBN I-VP O
peripheral JJ B-NP O
pulses NNS I-NP O
and CC O O
1+ JJ B-NP O
pedal NN I-NP O
edema NN I-NP O
. . O O
Electrocardiogram NNP B-NP O
shows VBZ B-VP O
sinus IN B-PP O
rhythm NN B-NP O
at IN B-PP O
a DT B-NP O
rate NN I-NP O
of IN B-PP O
60 CD B-NP O
, , O O
PR NNP B-NP O
interval NN I-NP O
0.14 CD B-NP O
, , O O
QRS NNP B-NP O
0.12 CD I-NP O
, , O O
QT NNP B-NP O
0.38 CD I-NP O
, , I-NP O
axis NN I-NP O
-20 CC I-NP O
degrees NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
evidence NN B-NP O
of IN B-PP O
left JJ B-NP O
bundle-branch NN I-NP O
block NN I-NP O
with IN B-PP O
secondary JJ B-NP O
ST NNS I-NP O
and CC O O
T-wave JJ B-NP O
changes NNS I-NP O
. . O O
An DT B-NP O
echocardiogram NN I-NP O
performed VBD B-VP O
prior RB B-ADVP O
to TO B-VP O
discharge VB I-VP O
revealed VBN I-VP O
mildly RB I-VP O
reduced VBN I-VP O
left VBN I-VP O
ventricular JJ B-NP O
systolic JJ I-NP O
function NN I-NP O
with IN B-PP O
a DT B-NP O
global JJ I-NP O
ejection NN I-NP O
fraction NN I-NP O
of IN B-PP O
40 CD B-NP O
% NN I-NP O
at IN B-PP O
a DT B-NP O
time NN I-NP O
when WRB B-ADVP O
he PRP B-NP O
had VBD B-VP O
a DT B-NP O
very RB I-NP O
rapid JJ I-NP O
heart NN I-NP O
rate NN I-NP O
. . O O
No DT B-NP O
subsequent JJ I-NP O
echocardiogram NN I-NP O
has VBZ B-VP O
been VBN I-VP O
performed VBN I-VP O
when WRB B-ADVP O
he PRP B-NP O
is VBZ B-VP O
in IN B-PP O
sinus NN B-NP O
rhythm NN I-NP O
. . O O
Impression NN B-NP O
and CC I-NP O
Plan NNP I-NP O
: : O O
Mr. NNP B-NP O
Ocampo NNP I-NP B-PATIENT
is VBZ B-VP O
making VBG I-VP O
a DT B-NP O
slow JJ I-NP O
but CC I-NP O
study NN I-NP O
recovery NN I-NP O
from IN B-PP O
his PRP$ B-NP O
multivessel NN I-NP O
coronary JJ I-NP O
bypass IN B-PP O
graft NN B-NP O
surgery NN I-NP O
. . O O
I PRP B-NP O
suggested VBD B-VP O
he PRP I-VP O
undergo VB I-VP O
repeat NN B-NP O
echocardiogram NN I-NP O
to TO B-VP O
document VB I-VP O
current JJ B-NP O
left NN I-NP O
ventricular JJ I-NP O
function NN I-NP O
now RB B-ADVP O
that IN B-SBAR O
he PRP B-NP O
is VBZ B-VP O
back RB B-ADVP O
in IN B-PP O
sinus NN B-NP O
rhythm NN I-NP O
. . O O
I PRP B-NP O
told VBD B-VP O
him PRP B-NP O
he PRP B-NP O
would MD B-VP O
stay VB I-VP O
on IN B-PP O
amiodarone NN B-NP O
for IN B-PP O
approximately RB B-NP O
3-6 CD I-NP O
months NNS I-NP O
, , O O
and CC O O
assuming VBG B-NP O
, , O O
he PRP B-NP O
was VBD B-VP O
in IN B-PP O
normal JJ B-NP O
sinus NN I-NP O
rhythm NN I-NP O
throughout IN B-PP O
this DT B-NP O
time NN I-NP O
period NN I-NP O
, , O O
his PRP$ B-NP O
amiodarone NN I-NP O
would MD B-VP O
then RB I-VP O
be VB I-VP O
discontinued VBN I-VP O
. . O O
At IN B-PP O
that DT B-NP O
time NN I-NP O
, , O O
I PRP B-NP O
would MD B-VP O
also RB I-VP O
discontinue VB I-VP O
his PRP$ B-NP O
Coumadin NN I-NP O
. . O O
In IN B-PP O
addition NN B-NP O
, , O O
at IN B-PP O
the DT B-NP O
time NN I-NP O
of IN B-PP O
his PRP$ B-NP O
diagnostic JJ I-NP O
catheterization NN I-NP O
, , O O
he PRP B-NP O
had VBD B-VP O
evidence NN B-NP O
for IN B-PP O
severe JJ B-NP O
peripheral NN I-NP O
vascular JJ I-NP O
disease NN I-NP O
, , O O
and CC O O
he PRP B-NP O
understands VBZ B-VP O
that IN B-PP O
when WRB B-ADVP O
he PRP B-NP O
has VBZ B-VP O
completed VBN I-VP O
his PRP$ B-NP O
recovery NN I-NP O
from IN B-PP O
his PRP$ B-NP O
recent JJ I-NP O
surgery NN I-NP O
, , O O
I PRP B-NP O
would MD B-VP O
strongly RB I-VP O
encourage VB I-VP O
further JJ B-NP O
evaluation NN I-NP O
of IN B-PP O
his PRP$ B-NP O
lower JJR I-NP O
extremity NN I-NP O
arterial NN I-NP O
system NN I-NP O
with IN B-PP O
an DT B-NP O
eye NN I-NP O
toward IN B-PP O
potential JJ B-NP O
percutaneous JJ I-NP O
intervention NN I-NP O
. . O O
In IN B-PP O
addition NN B-NP O
, , O O
I PRP B-NP O
have VBP B-VP O
asked VBN I-VP O
him PRP B-NP O
to TO B-VP O
obtain VB I-VP O
copies NNS B-NP O
of IN B-PP O
his PRP$ B-NP O
discharge NN I-NP O
summary NN I-NP O
from IN B-PP O
the DT B-NP O
Gadsden NNP I-NP B-HOSPITAL
Medical NNP I-NP I-HOSPITAL
Center NNP I-NP I-HOSPITAL
. . O O
I PRP B-NP O
would MD B-VP O
like VB I-VP O
to TO I-VP O
resume VB I-VP O
ACE NNP B-NP O
inhibitor IN B-PP O
therapy NN B-NP O
in IN B-PP O
light NN B-NP O
of IN B-PP O
his PRP$ B-NP O
significant JJ I-NP O
CAD NN I-NP O
and CC O O
probable JJ B-NP O
left JJ I-NP O
ventricular JJ I-NP O
dysfunction NN I-NP O
. . O O
He PRP B-NP O
will MD B-VP O
have VB I-VP O
routine JJ B-NP O
blood NN I-NP O
studies NNS I-NP O
obtained VBN B-VP O
today NN B-NP O
. . O O
I PRP B-NP O
would MD B-VP O
target VB I-VP O
his PRP$ B-NP O
LDL NNP I-NP O
cholesterol NN I-NP O
to TO B-PP O
the DT B-NP O
70 CD I-NP O
range NN I-NP O
. . O O
Beyond IN B-PP O
this DT B-NP O
, , O O
I PRP B-NP O
have VBP B-VP O
not RB I-VP O
altered VBN I-VP O
his PRP$ B-NP O
current JJ I-NP O
regimen NNS I-NP O
. . O O
Thank VB B-VP O
you PRP B-NP O
very RB B-ADVP O
much RB I-ADVP O
for IN B-PP O
allowing VBG B-VP O
me PRP B-NP O
to TO B-VP O
assist VB I-VP O
in IN B-PP O
his PRP$ B-NP O
care NN I-NP O
. . O O
Sincerely RB B-ADVP O
yours PRP B-NP O
, , O O
Nicholas NNP B-NP B-DOCTOR
Gomes NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Dictated NNP B-NP O
By IN I-NP O
: : O O
Nicholas NNP B-NP B-DOCTOR
Gomes NNP I-NP I-DOCTOR
eScription NN B-NP O
document NN I-NP O
: : O O
5-3575980 CD B-NP B-IDNUM
AFFocus NN I-NP O
DD NNP B-NP O
: : O O
09/13/93 CD O B-DATE
DT NNP B-NP O
: : O O
09/14/93 CD O B-DATE
DV NNP B-NP O
: : O O
09/13/93 CD O B-DATE
