Record NNP B-NP O
date NN I-NP O
: : O O
2137-02-27 CD O B-DATE
CARDIOLOGY NN B-NP O
PACIFIC NNP B-NP B-HOSPITAL
COAST NNP I-NP I-HOSPITAL
HOSPITAL NNP I-NP I-HOSPITAL
Reason NN B-NP O
for IN B-PP O
visit NN B-NP O
: : O O
transfer NN B-NP O
from IN B-PP O
Colorow NNP B-NP B-HOSPITAL
, , O O
chest NN B-NP O
pain NN I-NP O
in IN B-PP O
setting NN B-NP O
of IN B-PP O
known VBN B-NP O
CAD NN I-NP O
Interval NNP B-NP O
History NN I-NP O
: : O O
63 CD B-NP B-AGE
-year-old JJ I-NP O
woman NN I-NP O
with IN B-PP O
multiple JJ B-NP O
medical JJ I-NP O
problems NNS I-NP O
, , O O
notably RB B-ADVP O
CAD NNP B-NP O
, , O O
s/p NN B-NP O
RCA NNP I-NP O
and CC I-NP O
LCx NNP I-NP O
PCI NNP I-NP O
in IN B-PP O
the DT B-NP O
context NN I-NP O
of IN B-PP O
NSTEMI NNP B-NP O
in IN B-PP O
March NNP B-NP I-DATE
, , O I-DATE
2136 CD B-NP I-DATE
, , O O
with IN B-PP O
return NN B-NP O
to TO B-VP O
PCH VB I-VP B-HOSPITAL
in IN B-PP O
July NNP B-NP I-DATE
, , O I-DATE
2136 CD B-NP I-DATE
with IN B-PP O
recurrent JJ B-NP O
chest NN I-NP O
discomfort NN I-NP O
. . O O
Cardiac NNP B-NP O
catheterization NN I-NP O
during IN B-PP O
that DT B-NP O
visit NN I-NP O
revealed VBD B-VP O
in-stent JJ B-NP O
stenosis NN I-NP O
in IN B-PP O
LCx NNP B-NP O
stent NN I-NP O
, , O O
successfully RB B-ADVP O
addressed VBD B-VP O
with IN B-PP O
bare JJ B-NP O
metal NN I-NP O
stent NN I-NP O
placement NN I-NP O
. . O O
Most RBS B-NP O
recent JJ I-NP O
nuc. NN I-NP O
stress NN I-NP O
10/03/36 VBZ B-VP B-DATE
showed VBN I-VP O
no DT B-NP O
definite JJ I-NP O
ischemia NN I-NP O
, , O O
mild JJ B-NP O
apical JJ I-NP O
and CC I-NP O
mild JJ I-NP O
inferolateral JJ I-NP O
thinning NN I-NP O
not RB B-ADVP O
clearly RB I-ADVP O
outside IN B-PP O
normal JJ B-ADJP O
per IN B-PP O
report NN B-NP O
. . O O
She PRP B-NP O
incidentally RB B-ADVP O
also RB B-ADVP O
was VBD B-VP O
inpt JJ B-ADJP O
. . O O
for IN B-PP O
small JJ B-NP O
bowel NN I-NP O
obstruction NN I-NP O
surgery NN I-NP O
w/ IN B-PP O
ileostomy NN B-NP O
and CC O O
subsequent JJ B-NP O
takedown NN I-NP O
of IN B-PP O
ileostomy NN B-NP O
in IN B-PP O
January NNP B-NP B-DATE
. . O O
has VBZ B-VP O
been VBN I-VP O
doing VBG I-VP O
well RB B-ADVP O
and CC O O
only RB B-VP O
taking VBG I-VP O
Fioricet NNP B-NP O
for IN B-PP O
postop JJ B-NP O
pain NN I-NP O
q RB B-NP O
12 CD I-NP O
hrs NNS I-NP O
( -LRB- O O
due JJ B-PP O
to TO B-PP O
allergies NNS B-NP O
to TO B-PP O
most RBS B-NP O
other JJ I-NP O
pain NN I-NP O
meds NNS I-NP O
) -RRB- B-VP O
. . O O
Now RB B-ADVP O
returned VBD B-VP O
to TO B-PP O
Colorow NNP B-NP B-HOSPITAL
ED NNP I-NP O
due JJ B-ADJP O
to TO B-VP O
recurrant VB I-VP O
SSCP NNP B-NP O
c/w RB B-ADVP O
previously RB B-ADVP O
experienced VBN B-VP O
CP CD B-NP O
- : O O
described VBN B-VP O
as IN B-PP O
SS NNP B-NP O
chest NN I-NP O
pressure NN I-NP O
rad NN I-NP O
. . B-VP O
to TO B-PP O
right JJ B-NP O
arm NN I-NP O
and CC I-NP O
back NN I-NP O
that WDT B-NP O
started VBD B-VP O
at IN B-PP O
1:30 CD B-NP O
am VBP B-VP O
rel NN B-NP O
. . O O
w/ VBD B-VP O
3 CD B-NP O
sl NN I-NP O
NTG NN I-NP O
, , O O
also RB B-ADVP O
had VBD B-VP O
clammy JJ B-NP O
skin NN I-NP O
and CC O O
loose JJ B-NP O
BMs NNS I-NP O
after IN B-PP O
this DT B-NP O
, , O O
went VBD B-VP O
back RB B-ADVP O
to TO B-PP O
sleep VB B-NP O
then RB B-ADVP O
CP CD B-NP O
recurred VBD B-VP O
when WRB B-ADVP O
up RP B-NP O
in IN B-NP O
am VBP B-VP O
resolved VBN I-VP O
with IN B-PP O
ASA NNP B-NP O
in IN B-PP O
am VBP B-NP O
, , O O
then RB B-ADVP O
recurred VBD B-VP O
again RB B-ADVP O
in IN B-PP O
aft NN B-NP O
. . O O
so RB O O
went VBD B-VP O
to TO B-PP O
ED NNP B-NP O
, , O O
states NNS B-NP O
it PRP B-NP O
was VBD B-VP O
rel NN B-NP O
. . O O
after IN B-PP O
NTG NNP B-NP O
again RB B-ADVP O
but CC O O
has VBZ B-VP O
waxed VBN I-VP O
and CC O O
waned VBD B-VP O
since IN B-PP O
going VBG B-VP O
to TO B-PP O
ED NNP B-NP O
at IN B-PP O
OSH NNP B-NP O
- : O O
transferred VBN B-VP O
to TO I-VP O
PCH VB I-VP B-HOSPITAL
per IN B-PP O
pt NN B-NP O
. . O O
request NN B-NP O
for IN B-PP O
further JJ B-NP O
eval NN I-NP O
. . O O
and CC O O
management NN B-NP O
. . O O
EKG -RRB- O O
there EX B-NP O
w/ VBD B-VP O
no DT B-NP O
reported VBD I-NP O
acute JJ I-NP O
STAs NNS I-NP O
at IN B-PP O
OSH. NNP B-NP O
Biomarkers NNP I-NP O
deferred VBN B-VP O
to TO I-VP O
be VB I-VP O
drawn VBN I-VP O
at IN B-PP O
PCH NNP B-NP B-HOSPITAL
per IN B-PP O
pt NN B-NP O
. . B-NP O
request NN I-NP O
. . O O
On IN B-PP O
admit VBP B-VP O
to TO B-PP O
Internal NNP B-NP O
Medicine NNP I-NP O
, , O O
pt VBD B-VP O
. . B-NP O
states NNS I-NP O
has VBZ B-VP O
3/10 CD B-NP O
SSCP NNP I-NP O
, , I-NP O
sbp JJ I-NP O
180/80 CD I-NP O
. . O O
IV NNP B-NP O
NTG NNP I-NP O
started VBD B-VP O
and CC I-VP O
enz VBD I-VP O
, , O O
troponin FW B-VP O
to TO I-VP O
be VB I-VP O
drawn VBN I-VP O
and CC I-VP O
cycled VBN I-VP O
. . O O
EKG NNP B-NP O
SR NNP I-NP O
, , O O
LAD NNP B-NP O
TWIs NNP I-NP O
V1 NNP I-NP O
, , O O
V2 NNP B-NP O
c/w VBD B-VP O
previous JJ B-NP O
comparison NN I-NP O
EKG. NNP B-NP O
CP CD I-NP O
resolving NN I-NP O
after IN B-PP O
IV NNP B-NP O
NTG NNP I-NP O
started VBD B-VP O
. . O O
Past JJ B-NP O
medical JJ I-NP O
history NN I-NP O
: : O O
1 LS O O
. . B-NP O
CAD NNP I-NP O
, , O O
s/p JJ B-NP O
NSTEMI NNP I-NP O
in IN B-PP O
March NNP B-NP I-DATE
, , O I-DATE
2136 CD B-NP I-DATE
with IN B-PP O
BM NNP B-NP O
stent NN I-NP O
placement NN I-NP O
to TO B-PP O
LCx NNP B-NP O
and CC I-NP O
RCA NNP I-NP O
Coronary JJ B-NP O
angiogram NN I-NP O
in IN B-PP O
July NNP B-NP I-DATE
, , O I-DATE
2136 CD B-NP I-DATE
: : O O
- : O O
in-stent JJ B-NP O
stenosis NN I-NP O
( -LRB- I-NP O
diffuse NN I-NP O
, , O O
80-90 JJ B-NP O
% NN I-NP O
) -RRB- I-NP O
in IN B-PP O
the DT B-NP O
previously RB I-NP O
placed VBN I-NP O
LCx NNP I-NP O
stent NN I-NP O
. . O O
- : O O
other JJ B-NP O
stenoses NNS I-NP O
included VBD B-VP O
diagonal JJ B-NP O
branch NN I-NP O
60 CD I-NP O
% NN I-NP O
stenosis NN I-NP O
, , O O
right JJ B-ADJP O
PDA NNP B-NP O
70 CD I-NP O
% NN I-NP O
- : O O
previously RB B-VP O
placed VBN I-VP O
RCA NNP B-NP O
stent NN I-NP O
contained VBD B-VP O
15 CD B-NP O
% NN I-NP O
stenosis NN I-NP O
. . O O
- : O O
LCx JJ B-NP O
in-stent JJ I-NP O
stenosis NN I-NP O
presumed VBN B-VP O
to TO I-VP O
be VB I-VP O
culprit JJ B-NP O
lesion NN I-NP O
, , O O
and CC O O
was VBD B-VP O
re-opened VBN I-VP O
successfully RB B-ADVP O
with IN B-PP O
2.25 CD B-NP O
X NNP I-NP O
12mm CD I-NP O
MicroDriver NNP I-NP O
stent NN I-NP O
. . O O
2. . B-NP O
Hyperlipidemia NNP I-NP O
3. . B-NP O
Hypertension NNP I-NP O
4 LS O O
. . B-NP O
MAC NNP I-NP O
, , O O
previous JJ B-NP O
treatment NN I-NP O
course NN I-NP O
terminated VBN B-VP O
due JJ B-ADJP O
to TO B-PP O
hepatitis NN B-NP O
in IN B-PP O
2128 CD B-NP B-DATE
5 CD B-NP O
. . O O
Bronchiectasis NNP B-NP O
, , O O
s/p RB B-NP O
right JJ I-NP O
middle NN I-NP O
lobectomy NN I-NP O
in IN B-PP O
2128 CD B-NP B-DATE
6 CD B-NP O
. . O O
Raynaud NNP B-NP O
's POS B-NP O
Syndrome NNP I-NP O
7. . B-NP O
Fibromyalgia NNP I-NP O
8. CD B-NP O
Migraine NNP I-NP O
headaches NNS I-NP O
9 CD B-NP O
. . I-NP O
Hiatal NNP I-NP O
and CC O O
ventral JJ B-NP O
hernias NNS I-NP O
10 CD B-NP O
. . O O
Previous NNP B-NP O
appendectomy NN I-NP O
11 CD B-NP O
. . O O
Osteopenia NNP O O
12 CD B-NP O
. . O O
Previous NNP B-NP O
ophthalmic NNP I-NP O
zoster NN I-NP O
infection NN I-NP O
13 CD B-NP O
. . O O
Mild NNP B-NP O
hearing VBG I-NP O
loss NN O O
14 CD B-NP O
. . O O
Amoxicillin-clavulanate NNP B-NP O
reaction NN I-NP O
in IN B-PP O
2133 CD B-NP B-DATE
15 CD B-NP O
. . O O
GERD NNP O O
16 CD B-NP O
. . O O
DM NNP B-NP O
, , O O
on IN B-PP O
oral JJ B-NP O
hypoglycemics NNS I-NP O
as IN B-PP O
an DT B-NP O
outpatient NN I-NP O
17 CD B-NP O
. . O O
Prior RB O O
GI NNP B-NP O
bleed CC O O
18 CD B-LST O
. . O O
1/37 CD B-NP B-DATE
small JJ I-NP O
bowel NN I-NP O
obstruction NN I-NP O
surgical JJ I-NP O
repair NN I-NP O
and CC O O
ileostomy NN B-NP O
and CC O O
then RB O O
takedown VB O O
Home NNP B-NP O
medical JJ I-NP O
regimen NNS I-NP O
: : O O
1 LS O O
. . B-NP O
Aspirin NNP I-NP O
325mg JJ I-NP O
daily JJ I-NP O
2. DT B-NP O
Plavix NNP I-NP O
75mg CD I-NP O
daily JJ O O
3. . B-NP O
Inderal NNP I-NP O
LA NNP I-NP O
120mg CD I-NP O
bid NN I-NP O
4 CD B-LST O
. . O O
Tekturna NNP B-NP O
75mg CD I-NP O
daily JJ O O
5 CD B-NP O
. . O O
Lipitor NNP B-NP O
80mg CD I-NP O
daily JJ O O
7. CD B-NP O
Hormone NNP I-NP O
replacement NN I-NP O
therapy NN I-NP O
qd VBN B-VP O
(estradiol NNP B-NP O
2mg CD I-NP O
, , O O
medroxyprogesterone JJ B-NP O
5mg JJ I-NP O
) -RRB- O O
8. . B-NP O
Amlodipine NNP I-NP O
10 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
9 CD B-NP O
. . O O
Multivitamin NNP B-NP O
qd . O O
11 CD B-NP O
. . O O
Metformin NNP B-NP O
1000mg CD B-NP O
bid NN I-NP O
12 CD B-NP O
. . O O
Albuterol NNP B-NP O
neb JJ I-NP O
2.5mg CD I-NP O
bid NN I-NP O
13 CD B-NP O
. . O O
Colace NNP B-NP O
100mg CD B-NP O
bid NN I-NP O
14 CD B-NP O
. . O O
Fioricet NNP B-NP O
PRN NNP I-NP O
headache NN I-NP O
and CC O O
q RB B-NP O
12 CD I-NP O
hr NN I-NP O
prn NN I-NP O
postop NN I-NP O
pain NN I-NP O
( -LRB- B-VP O
since IN I-VP O
allergic VBN I-VP O
to TO B-PP O
usual JJ B-NP O
pain NN I-NP O
meds NNS I-NP O
) -RRB- O O
15 CD B-NP O
. . O O
Prilosec NNP B-NP O
20 CD I-NP O
mg JJ I-NP O
po NN I-NP O
bid NN I-NP O
Allergies NNP B-NP O
: : O O
Tylenol NNP B-NP O
HAs NNP I-NP O
Azithromycin NNP B-NP O
rash NN I-NP O
darvocet NN B-NP O
GI NNP I-NP O
upset NN I-NP O
percocet NN B-NP O
GI NNP I-NP O
upset NN I-NP O
Darvon NNP B-NP O
GI NNP I-NP O
upste NN I-NP O
codeine NN B-NP O
GI NNP I-NP O
upset NN I-NP O
sulfa NN B-NP O
angioedema NN I-NP O
flagyl NN B-NP O
angioedema NN I-NP O
levofloxacin NN B-NP O
rash NN I-NP O
Hydrocodone NNP B-NP O
GI NNP I-NP O
upset NN I-NP O
Onions/garlic NNP B-NP O
GI NNP I-NP O
upset NN I-NP O
Peanuts NNP B-NP O
HAs NNP I-NP O
ACE NNP B-NP O
I PRP B-NP O
cough VB O O
ARB NN B-NP O
unknown NN I-NP O
Family NNP B-NP O
history NN I-NP O
: : O O
Early-onset NNP B-NP O
CAD NNP I-NP O
in IN B-PP O
mother NN B-NP O
Social JJ B-NP O
history NN I-NP O
: : O O
Married VBN B-VP O
, , O O
lives VBZ B-VP O
w/ JJ B-NP O
husband NN I-NP O
. . O O
Retired VBN B-NP O
firefighter NN I-NP B-PROFESSION
Tob NNP B-NP O
: : O O
denies VBZ O O
EtOH NNP B-NP O
: : O O
denies VBZ O O
Illicits NNS B-NP O
: : O O
denies VBZ O O
Review NNP B-NP O
of IN B-PP O
systems NNS B-NP O
: : O O
See VB B-NP O
interval NN I-NP O
history NN I-NP O
Physical JJ B-NP O
examination NN I-NP O
: : O O
-temperature NN B-NP O
: : O O
afebrile NN B-NP O
-Pulse NN B-NP O
: : O O
76 CD O O
-resp. DT B-NP O
rate NN I-NP O
: : O O
16 CD O O
-General JJ B-NP O
appearance NN I-NP O
: : O O
No DT B-NP O
acute JJ I-NP O
distress NN I-NP O
. . O O
-Skin JJ B-NP O
: : O O
Warm NNP B-NP O
, , O O
dry JJ B-ADJP O
, , O O
no DT B-NP O
ecchymoses NNS I-NP O
or CC I-NP O
lesions NNS I-NP O
-HEENT JJ B-NP O
: : O O
Unremarkable JJ O O
-Neck NN B-NP O
: : O O
Carotids NNP B-NP O
2+ CD I-NP O
without IN B-PP O
bruits NNS B-NP O
. . O O
JVP NN B-VP O
no DT B-NP O
jugular JJ I-NP O
venous JJ I-NP O
distention NN I-NP O
-Chest NN B-NP O
: : O O
Clear NNP B-NP O
to TO B-PP O
auscultation NN B-NP O
and CC I-NP O
percussion NN I-NP O
. . O O
-Cardiac NNP B-NP O
: : O O
No DT B-NP O
lift NN I-NP O
or CC I-NP O
heave NN I-NP O
, , I-NP O
non-displaced JJ I-NP O
and CC I-NP O
discrete JJ I-NP O
PMI NNP I-NP O
, , O O
regular JJ B-NP O
S1S2 NN I-NP O
, , O O
no DT B-NP O
S3S4 NNP I-NP O
, , O O
no DT B-NP O
rubs NNS I-NP O
or CC I-NP O
murmurs NNS I-NP O
. . O O
-Abdomen NNS B-NP O
: : O O
Normal JJ B-NP O
bowel NN I-NP O
sounds NNS I-NP O
, , O O
soft JJ B-NP O
, , I-NP O
non-tender JJ I-NP O
, , I-NP O
abd NN I-NP O
. . O O
incision NN B-VP O
well RB B-ADJP O
healing JJ I-ADJP O
, , O O
no DT B-NP O
erythema NN I-NP O
or CC I-NP O
drge NN I-NP O
. . O O
, , O O
no DT B-NP O
masses NNS I-NP O
or CC I-NP O
organomegaly NN I-NP O
-Extremities NNS B-NP O
: : O O
No DT B-NP O
groin NN I-NP O
hematoma NN I-NP O
or CC I-NP O
bruits NNS I-NP O
, , O O
femoral JJ B-NP O
pulses NNS I-NP O
+2 VBP B-VP O
bilaterally RB B-ADVP O
, , O O
DP/PT NNP B-NP O
pulses VBZ B-VP O
+2 IN B-PP O
bilaterally RB B-ADVP O
, , O O
no DT B-NP O
lower JJR I-NP O
extremity NN I-NP O
edema NN I-NP O
-BP JJ B-NP O
: : O O
148/76 CD O O
-Neuro NNP B-NP O
: : O O
A&amp;O NNP B-NP O
x3 CD I-NP O
, , O O
CN NNP B-NP O
2-12 CD I-NP O
grossly RB I-NP O
intact JJ I-NP O
Selected NNP B-NP O
recent JJ I-NP O
labs NNS I-NP O
: : O O
pending VBG O O
Impression NN B-NP O
: : O O
63 CD B-NP B-AGE
y NN I-NP O
.o NN I-NP O
. . O O
female NN B-NP O
w/ VBD B-VP O
knowd VBN I-VP O
CAD NN B-NP O
as IN B-PP O
detailed JJ B-NP O
above JJ I-NP O
. . O O
With IN B-PP O
recurrant JJ B-NP O
CP CD I-NP O
c/w NN I-NP O
previous JJ B-NP O
CP. NNP I-NP O
Rel NNP I-NP O
. . B-NP O
w/ NNS I-NP O
NTG. . O O
Biomarkers NNS B-NP O
pending VBG B-VP O
. . B-NP O
EKG NNP I-NP O
w/ VBD B-VP O
no DT B-NP O
change NN I-NP O
from IN B-PP O
previous JJ B-NP O
comparison NN I-NP O
EKG. . O O
Dr. NNP B-NP O
Aldrich NNP I-NP B-DOCTOR
covering VBG B-VP O
for IN B-PP O
Dr. NNP B-NP O
Zehr NNP I-NP B-DOCTOR
this DT B-NP O
eve NN I-NP O
notified VBD B-VP O
of IN B-PP O
pts NNS B-NP O
. . B-NP O
admission NN I-NP O
. . O O
Cycle NNP B-NP O
biomarkers NNS I-NP O
and CC I-NP O
EKGs NNS I-NP O
tonoc. . O O
On IN B-PP O
ASA NNP B-NP O
, , O O
Plavix NNP B-NP O
, , O O
statin NN B-NP O
, , O O
BB NNP B-NP O
, , O O
IV NNP B-NP O
NTG. NNP I-NP O
Keep VB B-VP O
home NN B-NP O
med VBN B-VP O
Inderal NNP B-NP O
LA NNP I-NP O
due JJ B-ADVP O
to TO B-PP O
pts NNS B-NP O
. . O O
many JJ B-NP O
prev. VBD I-NP O
problems NNS I-NP O
w/ VBP B-VP O
allergies NNS B-NP O
as IN B-PP O
above JJ B-NP O
. . O O
Allergic NNP O O
to TO B-PP O
ACE NNP B-NP O
I PRP B-NP O
and CC O O
ARB. NNP B-NP O
Tentatively RB B-ADVP O
plan NN B-VP O
cath NN B-NP O
on IN B-PP O
Saturday NNP B-NP B-DATE
. . O O
Hold VB B-VP O
on IN B-PP O
Heparin NNP B-NP O
gtt NNP I-NP O
unless IN B-PP O
Sx NNP B-NP O
recur NNP I-NP O
. . O O
Monitor NNP B-NP O
BS NNP I-NP O
, , O O
prn NN B-NP O
sliding VBG I-NP O
scale NN I-NP O
insulin NN I-NP O
. . O O
Hold VB B-VP O
Metformin NNP B-NP O
precath NN I-NP O
. . O O
Mucomyst NNP B-NP O
precath NN I-NP O
ordered VBD B-VP O
. . O O
Check VB B-NP O
lipids NNS I-NP O
, , O O
LFTs NNP B-NP O
in IN B-LST O
am VBP B-VP O
. . O O
Diet NNP B-NP O
consult VB B-VP O
ordered VBN I-VP O
. . O O
Consider VB B-VP O
stopping VBG I-VP O
HRT. NNP B-NP O
Pt NNP I-NP O
. . O O
states NNS B-VP O
she PRP B-NP O
has VBZ B-VP O
discussed VBN I-VP O
this DT B-NP O
w/ NN I-NP O
Dr. NNP I-NP O
Zehr NNP I-NP B-DOCTOR
in IN B-PP O
the DT B-NP O
past NN I-NP O
and CC O O
they PRP B-NP O
have VBP B-VP O
agreed VBN I-VP O
for IN B-SBAR O
it PRP B-NP O
ot RB B-ADVP O
continue VBP B-VP O
. . O O
NPo NNP B-NP O
after IN B-PP O
MN NNP B-NP O
Fri NNP I-NP B-DATE
likely JJ I-NP O
for IN B-PP O
cath NN B-NP O
Sat . O B-DATE
Further JJ B-NP O
recs NNS I-NP O
. . O O
per IN B-PP O
Dr. NNP B-NP O
Zehr NNP I-NP B-DOCTOR
. . O O
Reema NNP B-NP B-DOCTOR
N. NNP I-NP I-DOCTOR
Imler NNP I-NP I-DOCTOR
pager NN I-NP O
# # I-NP O
36201 CD O B-PHONE
Signed VBN B-VP O
electronically RB B-ADVP O
by IN B-PP O
Reema NNP B-NP B-DOCTOR
N. NNP I-NP I-DOCTOR
Imler NNP I-NP I-DOCTOR
Document NNP B-NP O
Status NNP I-NP O
: : O O
Final JJ O O
