Record NNP B-NP O
date NN I-NP O
: : O O
2118-09-26 CD O B-DATE
Reason NN B-NP O
for IN B-PP O
Visit NNP B-NP O
Patient NNP B-NP O
presents VBZ B-VP O
today NN B-NP O
for IN B-PP O
a DT B-NP O
routine JJ I-NP O
physical NN I-NP O
; : O O
her PRP$ B-NP O
last JJ I-NP O
one NN I-NP O
was VBD B-VP O
in IN B-PP O
12 CD B-NP B-DATE
. . O O
She PRP B-NP O
has VBZ B-VP O
the DT B-NP O
following VBG I-NP O
concerns NNS I-NP O
that IN B-SBAR O
she PRP B-NP O
would MD B-VP O
like VB I-VP O
to TO I-VP O
have VB I-VP O
addressed VBN I-VP O
: : O O
concerned VBN B-VP O
about IN B-PP O
allergies NNS B-NP O
needs NNS B-NP O
PT NNP I-NP O
for IN B-PP O
recently RB B-NP O
fractured VBN I-NP O
humerus NN I-NP O
Past NNP B-NP O
Medical NNP I-NP O
History NNP I-NP O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
no DT B-NP O
history NN I-NP O
of IN B-PP O
cancer NN B-NP O
, , O O
CAD NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
Diabetes NNP B-NP O
, , O O
or CC O O
immune JJ B-NP O
disorder NN I-NP O
. . O O
Past NNP B-NP O
Surgical NNP I-NP O
History NN I-NP O
0 CD O O
Family NNP B-NP O
History NN I-NP O
Father NNP B-NP O
: : O O
age NN B-NP O
78 CD I-NP B-AGE
prostate NN I-NP O
cancer NN I-NP O
; : O O
diabetes NN B-NP O
Mother NN B-NP O
: : O O
age NN B-NP O
40 CD I-NP B-AGE
+ NN I-NP O
uterine NN I-NP O
cancer NN I-NP O
Siblings NNP B-NP O
:1b CD I-NP O
Marital NNP B-NP O
status NN I-NP O
:m . O O
Children NNS B-NP O
:1F IN B-PP O
- : O O
14 CD O B-AGE
FH NNP B-NP O
is VBZ B-VP O
notable JJ B-ADJP O
for IN B-PP O
the DT B-NP O
presence NN I-NP O
( -LRB- I-NP O
+ NN I-NP O
) -RRB- I-NP O
or CC I-NP O
absence(-) JJ I-NP O
of IN B-PP O
CAD NNP B-NP O
;Cancer NNP I-NP O
+ NNP I-NP O
+ NNP I-NP O
;diabetes VBZ B-VP O
+ JJ B-NP O
;HTN NN I-NP O
; : O O
genetic JJ B-NP O
disorder NN I-NP O
Social NNP B-NP O
History NNP I-NP O
Smokes NNS B-NP O
:1ppd CC O O
Alcohol NN B-NP O
:1-2 NN I-NP O
Occupation NNP B-NP O
: : O O
butcher NN B-NP B-PROFESSION
Exercise NNP B-NP O
:0 CD I-NP O
OB/GYN NNP B-NP O
History NN I-NP O
Menopausal JJ O O
- : O O
8 CD B-NP O
years NNS I-NP O
ago IN O O
Review NNP B-NP O
of IN I-NP O
Systems NNPS O O
CONSITUTIONAL NNP B-NP O
: : O O
no DT B-NP O
fever NN I-NP O
, , O O
chills NNS B-NP O
, , O O
weight NN B-NP O
change NN I-NP O
EYES NNS B-NP O
: : O O
no DT B-NP O
blurring NN I-NP O
, , O O
visual JJ B-NP O
changes NNS I-NP O
, , O O
pain NN B-NP O
, , O O
diplopia NN B-NP O
, , O O
or CC O O
discharge NN B-NP O
EARS NNS B-NP O
: : O O
no DT B-NP O
hearing NN I-NP O
loss NN I-NP O
, , O O
dizziness NN B-NP O
, , O O
tinnitus NN B-NP O
, , O O
ear NN B-NP O
pain NN I-NP O
or CC O O
discharge NN B-NP O
NECK NNP B-NP O
: : O O
no DT B-NP O
sore JJ I-NP O
throat NN I-NP O
, , O O
dysphagia NN B-NP O
, , I-NP O
swelling VBG I-NP O
or CC I-NP O
lumps NNS I-NP O
CVS NNP B-NP O
:no NNP I-NP O
chest NN I-NP O
pain NN I-NP O
on IN B-PP O
exertion NN B-NP O
no DT B-NP O
shortness NN I-NP O
of IN B-PP O
breath NN B-NP O
no DT B-NP O
palpitations NNS I-NP O
no DT B-NP O
ankle NN I-NP O
swelling VBG I-NP O
no DT B-NP O
cough NN I-NP O
GI NNP B-NP O
: : O O
no DT B-NP O
anorexia NN I-NP O
no DT B-NP O
nausea NN I-NP O
no DT B-NP O
heartburn NN I-NP O
no DT B-NP O
abdominal JJ I-NP O
pain NN I-NP O
no DT B-NP O
bowel NN I-NP O
dysfunction NN I-NP O
no DT B-NP O
blood NN I-NP O
in IN B-PP O
stool NN B-NP O
GU NNP B-NP O
: : O O
no DT B-NP O
dysuria NN I-NP O
no DT B-NP O
nocturia NN I-NP O
no DT B-NP O
frequency NN I-NP O
or CC I-NP O
poor JJ I-NP O
stream NN I-NP O
no DT B-NP O
incontinence NN I-NP O
CNS NNP B-NP O
:no NNP I-NP O
headaches NNS I-NP O
no DT B-NP O
dizziness NN I-NP O
no DT B-NP O
diplopia NN I-NP O
no DT B-NP O
memory NN I-NP O
disorder NN I-NP O
no DT B-NP O
weakness NN I-NP O
no DT B-NP O
seizures NNS I-NP O
MUSCULUSKELETAL NNP B-NP O
:no NN I-NP O
pains NNS I-NP O
or CC I-NP O
limitation NN I-NP O
of IN B-PP O
mobility NN B-NP O
SKIN JJ B-NP O
:no NNP I-NP O
hives NNS I-NP O
, , O O
rashes NNS B-NP O
, , O O
changing VBG B-VP O
moles NNS B-NP O
Vital JJ B-NP O
Signs NNS I-NP O
BLOOD NN B-NP O
PRESSURE JJ I-NP O
102/8 CD I-NP O
0 CD O O
HEIGHT NNP B-NP O
63.5 CD I-NP O
in IN B-PP O
. . O O
WEIGHT NNP B-NP O
162 CD I-NP O
lb NN I-NP O
Physical NNP B-NP O
Exam NNP I-NP O
CONSTITUTIONAL NNP B-NP O
: : O O
well RB B-VP O
developed VBN I-VP O
, , O O
in IN B-PP O
no DT B-NP O
acute JJ I-NP O
distress NN I-NP O
EYES:conjuntiva NN B-NP O
clear JJ I-NP O
; : O O
no DT B-NP O
icterus NN I-NP O
; : O O
EOM NN B-NP O
full JJ I-NP O
; : O O
no DT B-NP O
strabismus NN I-NP O
or CC I-NP O
nystagmus NN I-NP O
; : O O
fundi NN B-NP O
normal JJ I-NP O
ENT NNP B-NP O
: : O O
no DT B-NP O
wax NN I-NP O
; : O O
membranes NNS B-NP O
intact JJ B-NP O
;hearing VBG B-VP O
grossly RB B-NP O
normal JJ I-NP O
; : O O
nose NN B-NP O
no DT B-NP O
obvious JJ I-NP O
abnormality NN I-NP O
;sinuses VBZ B-VP O
not RB I-VP O
tender NN I-VP O
; : O O
pharynx NN B-NP O
no DT B-NP O
exudate NN I-NP O
NECK NNP B-NP O
: : O O
supple NN B-NP O
; : O O
no DT B-NP O
thyromegaly NN I-NP O
; : O O
no DT B-NP O
lymphadenopathy NN I-NP O
; : O O
carotids NNS B-NP O
palpable NN I-NP O
with IN B-PP O
no DT B-NP O
bruits NNS I-NP O
BREASTS NNS B-NP O
: : O O
no DT B-NP O
masses NNS I-NP O
or CC I-NP O
tenderness NN I-NP O
; : O O
no DT B-NP O
nipple NN I-NP O
abnormality NN I-NP O
or CC I-NP O
discharge NN I-NP O
; : O O
no DT B-NP O
adenopathy NN I-NP O
CARDIOVASCULAR NN B-NP O
SYSTEM NNP I-NP O
: : O O
pulse NN B-NP O
68 CD I-NP O
per IN B-PP O
min. NN B-NP O
, , O O
regular JJ B-ADJP O
; : O O
no DT B-NP O
cardiomegaly NN I-NP O
; : O O
heart NN B-NP O
sounds VBZ B-VP O
1 CD B-NP O
and CC I-NP O
2 CD I-NP O
only RB B-ADVP O
; : O O
no DT B-NP O
murmurs NNS I-NP O
no DT B-NP O
rubs NNS I-NP O
no DT B-NP O
gallop NN I-NP O
pedal VB B-NP O
pulses NNS I-NP O
- : O O
absent JJ B-NP O
left JJ I-NP O
leg NN I-NP O
; : O O
bruit NN B-NP O
over RB B-ADVP O
right RB B-ADJP O
femoral JJ I-ADJP O
no DT B-NP O
edema NN I-NP O
or CC I-NP O
varicosities NNS I-NP O
RESPIRATORY NN B-NP O
: : O O
Chest VB B-VP O
expansion NN B-NP O
- : O O
normal JJ O O
Percussion NN B-NP O
-normal JJ I-NP O
Auscultation NNP B-NP O
- : O O
clear JJ B-NP O
without IN B-PP O
rales NNS B-NP O
or CC O O
rhonchi NN B-NP O
ABDOMEN NNS B-NP O
: : O O
no DT B-NP O
visceromegaly NN I-NP O
no DT B-NP O
masses NNS I-NP O
no DT B-NP O
tenderness NN I-NP O
hernial PRP$ B-NP O
orifices NNS I-NP O
normal JJ O O
WILL MD O O
SEE NNP B-NP O
GYNE VB O O
CENTRAL NNP B-NP O
NERVOUS NNP I-NP O
SYSTEM NNP I-NP O
: : O O
alert JJ B-NP O
and CC I-NP O
oriented VBN I-NP O
cranial JJ B-NP O
nerves NNS I-NP O
pupils NNS B-NP O
-equal JJ B-ADVP O
, , O O
reactive VBG B-UCP O
fundi FW O O
- : O O
no DT B-NP O
papilledema NN I-NP O
tone NN B-NP O
- : O O
normal JJ O O
power NN B-NP O
- : O O
normal JJ O O
coordination NN B-NP O
- : O O
normal JJ O O
reflexes NNS B-NP O
normal JJ I-NP O
JOINTS NNS B-NP O
: : O O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
arthritis NN B-NP O
Spine NNP B-NP O
no DT B-NP O
tenderness NN I-NP O
SKIN JJ B-NP O
: : O O
no DT B-NP O
rashes NNS I-NP O
, , O O
hives NNS B-NP O
, , O O
changing VBG B-NP O
moles NNS I-NP O
normal JJ O O
Recommendation NN B-NP O
Based VBN B-PP O
on IN B-PP O
history NN B-NP O
and CC I-NP O
examination NN I-NP O
today NN B-NP O
the DT B-NP O
following VBG I-NP O
tests NNS I-NP O
were VBD B-VP O
ordered VBN I-VP O
: : O O
lipid JJ B-NP O
profile NN I-NP O
glucose NN B-NP O
stool NN B-NP O
HOB NN I-NP O
flex NN B-NP O
sig.....to VBD B-VP O
set VBN I-VP O
up IN B-PRT O
mammogram NN B-NP O
.... : O O
5/18 CD O B-DATE
bone NN B-NP O
density NN I-NP O
scan....to VBD B-VP O
set VBN I-VP O
up IN B-PRT O
EKG . O O
cxr NN B-NP O
Diet NNP B-NP O
Exercise NN B-NP O
Stop VB B-VP O
smoking VBG I-VP O
Further JJ B-NP O
recommendations NNS I-NP O
will MD B-VP O
be VB I-VP O
made VBN I-VP O
on IN B-PP O
the DT B-NP O
basis NN I-NP O
of IN B-PP O
the DT B-NP O
results NNS I-NP O
obtained VBN O O
Follow VB B-VP O
up RB I-VP O
advised VBN I-VP O
with IN B-PP O
vascular JJ B-NP O
surgeon NN I-NP O
to TO B-VP O
evaluate VB I-VP O
peripheral JJ B-NP O
vas NNS I-NP O
disease NN I-NP O
Given VBN B-NP O
sample NN I-NP O
of IN B-PP O
allegra DT B-NP O
180 CD I-NP O
referred VBN B-VP O
for IN B-PP O
PT VBG B-UCP O
