Record NNP B-NP O
date NN I-NP O
: : O O
2133-03-06 CD O B-DATE
SDU NNP B-NP O
JAR NNP I-NP O
ADMIT NNP I-NP O
NOTE NNP I-NP O
Patient NNP B-NP O
: : O O
Daniel NNP B-NP B-PATIENT
Doherty NNP I-NP I-PATIENT
MR# NNP B-NP O
: : O O
7670238 CD O B-MEDICALRECORD
Admit NNP B-NP O
Date NNP I-NP O
: : O O
3/05/33 CD O B-DATE
Attending VBG B-VP O
: : O O
Cotton NN B-NP B-DOCTOR
PCP NNP B-NP O
: : O O
Trahan NNP O B-DOCTOR
Code NNP B-NP O
Status NNP I-NP O
: : O O
FULL NNP B-NP O
CC NNP B-NP O
: : O O
Pre-CABG NNP O O
HPI NNP B-NP O
: : O O
68 CD B-NP B-AGE
y NN I-NP O
M NNP I-NP O
s/p NN I-NP O
recent JJ B-NP O
NAMC NNP I-NP B-HOSPITAL
hospitalization NN I-NP O
after IN B-PP O
having VBG B-VP O
a DT B-NP O
vfib NN I-NP O
arrest NN I-NP O
at IN B-PP O
the DT B-NP O
mall NN I-NP O
on IN B-PP O
02/04/33 CD B-NP B-DATE
, , O O
with IN B-PP O
defibrillation NN B-NP O
x NN I-NP O
5 CD I-NP O
in IN B-PP O
the DT B-NP O
field NN I-NP O
( -LRB- B-NP O
3x CD I-NP O
by IN B-PP O
bystanders NNS B-NP O
, , O O
and CC O O
2x CD B-NP O
by IN B-PP O
EMS NNP B-NP O
) -RRB- I-NP O
. . O O
Pt NNP B-NP O
converted VBD B-VP O
to TO B-PP O
NSR NNP B-NP O
in IN B-PP O
the DT B-NP O
field NN I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
stabilized VBN I-VP O
at IN B-PP O
Blakely NNP B-NP B-HOSPITAL
House NNP I-NP I-HOSPITAL
, , O O
then RB B-ADVP O
transferred VBN B-VP O
to TO B-PP O
NAMC NNP B-NP B-HOSPITAL
. . O O
At IN B-PP O
NAMC NNP B-NP B-HOSPITAL
, , O O
patient NN B-NP O
had VBD B-VP O
electrocardiac JJ B-NP O
cath NN I-NP O
, , O O
which WDT B-NP O
showed VBD B-VP O
3vd JJ B-NP O
disease NN I-NP O
and CC O O
Dr. NNP B-NP O
Albright NNP I-NP B-DOCTOR
s VBZ B-VP O
team NN B-NP O
was VBD B-VP O
consulted VBN I-VP O
. . O O
As IN B-SBAR O
pt NN B-NP O
was VBD B-VP O
encephalopathic JJ B-NP O
s/p NN I-NP O
arrest NN I-NP O
, , O O
he PRP B-NP O
was VBD B-VP O
transferred VBN I-VP O
to TO B-PP O
Fremont NNP B-NP B-HOSPITAL
Medical NNP I-NP I-HOSPITAL
Center NNP I-NP I-HOSPITAL
on IN B-PP O
02/21/33 CD B-NP B-DATE
, , O O
where WRB B-ADVP O
he PRP B-NP O
was VBD B-VP O
rehabilitated VBN I-VP O
and CC O O
his PRP$ B-NP O
mental JJ I-NP O
status NN I-NP O
improved VBD B-VP O
. . O O
At IN B-PP O
FMC NNP B-NP B-HOSPITAL
, , O O
his PRP$ B-NP O
diuretics NNS I-NP O
were VBD B-VP O
titrated VBN I-VP O
( -LRB- B-NP O
lasix RB I-NP O
20 CD I-NP O
mg NN I-NP O
-> JJ I-NP O
40 CD I-NP O
mg NN I-NP O
) -RRB- I-NP O
, , O O
and CC O O
psychiatry NN B-NP O
weighed VBD B-VP O
in IN B-PRT O
on IN B-PP O
his PRP$ B-NP O
posthypoxic JJ I-NP O
encephalopathy NN I-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
transferred VBN I-VP O
back RB B-ADVP O
to TO B-PP O
NAMC NNP B-NP B-HOSPITAL
today NN I-NP O
in IN B-PP O
preparation NN B-NP O
for IN B-PP O
CABG NNP B-NP O
, , O O
planned VBD B-VP O
3/07/33 CD B-NP B-DATE
. . O O
PMH: . O O
V-fib JJ B-NP O
arrest NN I-NP O
on IN B-PP O
02/04/33 CD B-NP B-DATE
due JJ I-NP O
to TO B-PP O
severe JJ B-NP O
CAD NN I-NP O
Severe JJ B-NP O
coronary JJ I-NP O
artery NN I-NP O
disease NN I-NP O
, , O O
3-vd JJ O O
Hypertension NN B-NP O
Hyperlipidemia NNP B-NP O
Resolving VBG B-VP O
postcardiac JJ B-NP O
arrest NN I-NP O
hypoxic NN I-NP O
encephalopathy NN I-NP O
History NN B-NP O
of IN B-PP O
smoking VBG B-NP O
Bipolar NNP B-NP O
disorder NN I-NP O
Depression NN B-NP O
Schizophrenia NNP B-NP O
H/o NNP B-NP O
abnormal JJ I-NP O
SPEP NN I-NP O
Vitamin NNP B-NP O
B12 NNP I-NP O
deficiency NN I-NP O
Gallstones NNP B-NP O
: : O O
2074 CD O B-DATE
Pancreatitis NNP B-NP O
: : O O
2110 CD O B-DATE
Dermatitis NNP B-NP O
: : O O
seborrheic NN B-NP O
Chronic NNP B-NP O
fatigue NN I-NP O
syndrome NN I-NP O
Humerus NNP B-NP O
fracture NN I-NP O
: : O O
L NNP B-NP O
arm NN I-NP O
. . O O
s/p '' O O
fall NN O O
Tonsillectomy NN B-NP O
H/o NNP B-NP O
Adenomatous NNP I-NP O
polyp NN I-NP O
: : O O
tubular JJ B-NP O
adenoma NN I-NP O
with IN B-PP O
high JJ B-NP O
grade NN I-NP O
dysplasia NN I-NP O
. . O O
Skin NNP B-NP O
cancer NN I-NP O
: : O O
Basal NNP B-NP O
cell NN I-NP O
CA. NN I-NP O
L NNP I-NP O
cheek NN I-NP O
. . O O
S/P NNP B-NP O
MOHs NNP I-NP O
, , O O
2129 CD O B-DATE
Medications NNS B-NP O
: : O O
1 LS O O
. . B-NP O
Trazodone NNP I-NP O
100 CD I-NP O
mg NN I-NP O
at IN B-PP O
bedtime NN B-NP O
2. . B-NP O
Olanzapine NNP I-NP O
10 CD I-NP O
mg NN I-NP O
at IN B-PP O
bed NN B-NP O
3. DT B-NP O
Fragmin NNP I-NP O
2500 CD I-NP O
units NNS I-NP O
sub VBN B-VP O
cu RB B-ADVP O
daily RB I-ADVP O
4 CD B-LST O
. . O O
Lasix NNP B-NP O
40 CD I-NP O
mg NN I-NP O
daily RB B-SBAR O
5 CD B-NP O
. . O O
Darvocet-N NNP B-NP O
100 CD I-NP O
1 CD I-NP O
tablet NN I-NP O
po NN I-NP O
q4 IN B-PP O
hours NNS B-NP O
prn VBP B-VP O
pain NN B-NP O
6 CD B-NP O
. . O O
Olanzapine NNP B-NP O
tablet NN I-NP O
5 CD B-NP O
mg NN I-NP O
q6 CD B-NP O
hours NNS I-NP O
prn JJ B-NP O
anxiety NN I-NP O
and CC O O
agitation NN B-NP O
7. DT B-NP O
Lopressor NNP I-NP O
25 CD I-NP O
mg NN I-NP O
q12 CD B-NP O
hours NNS I-NP O
8. DT B-NP O
Nystatin NNP I-NP O
powder NN I-NP O
applied VBD B-VP O
to TO B-PP O
the DT B-NP O
groin NN I-NP O
and CC I-NP O
skin NN I-NP O
folds NNS I-NP O
bid NN I-NP O
9 CD B-LST O
. . O O
Ipratropium NN B-VP O
bromide NN B-NP O
0.5 CD I-NP O
mg NN I-NP O
inh IN B-PP O
nebulization NN B-NP O
q4 CD I-NP O
hours NNS I-NP O
prn JJ B-NP O
shortness NN I-NP O
of IN B-PP O
breath NN B-NP O
10 CD B-NP O
. . O O
Albuterol NNP B-NP O
nebulizer NN I-NP O
2.5 CD B-NP O
mg NN I-NP O
q4 CD B-NP O
hours NNS I-NP O
prn JJ B-NP O
shortness NN I-NP O
of IN B-PP O
breath NN B-NP O
11 CD B-NP O
. . O O
Vitamin NNP B-NP O
B12 NNP I-NP O
, , O O
cyanocobalamin NN B-NP O
1000 CD I-NP O
mcg NN I-NP O
po NN I-NP O
daily RB O O
12 CD B-NP O
. . O O
Lipitor NNP B-NP O
80 CD I-NP O
mg JJ I-NP O
po NN I-NP O
daily RB O O
13 CD B-NP O
. . O O
Tylenol NNP B-NP O
650 CD I-NP O
mg NN I-NP O
po NN I-NP O
q6 CD B-NP O
hours NNS I-NP O
prn . O O
14 CD B-NP O
. . O O
Magnesium NNP B-NP O
hydroxide NN I-NP O
and CC I-NP O
aluminium NN I-NP O
hydroxide NN I-NP O
15 CD B-NP O
mL NN I-NP O
q4 CD B-NP O
hours NNS I-NP O
prn . O O
constipation NN B-NP O
15 CD B-NP O
. . O O
Senna NNP B-NP O
2 CD I-NP O
tablets VBZ B-VP O
po NN B-NP O
bid NN I-NP O
constipation NN I-NP O
16 CD B-NP O
. . O O
Bisacodyl NNP B-NP O
suppository NN I-NP O
10 CD B-NP O
mg NN I-NP O
pr NN I-NP O
prn NN I-NP O
constipation NN I-NP O
17 CD B-NP O
. . O O
Colace NNP B-NP O
100 CD I-NP O
mg JJ I-NP O
po NN I-NP O
bid NN I-NP O
18 CD B-LST O
. . O O
Psyllium NN B-VP O
seeds NNS B-NP O
3.7 CD B-NP O
gr NN I-NP O
po NN I-NP O
daily RB B-ADVP O
at IN B-PP O
bedtime NN B-NP O
Allergies NNP B-NP O
: : O O
NKDA NNP B-NP O
FH NNP B-NP O
: : O O
Father NNP B-NP O
died VBD B-VP O
of IN B-PP O
AMI NNP B-NP O
. . O O
SH NNS B-NP O
: : O O
Lives NNS B-NP O
alone RB B-ADVP O
TOB NN B-NP O
: : O O
quit VB B-VP O
20y PRP B-NP O
prior RB B-ADVP O
ETOH NNP B-NP O
: : O O
occasional JJ O O
ILLICITS NNS B-NP O
: : O O
unknown NN B-NP O
ROS NNP B-NP O
: : O O
See VB B-VP O
HPI NNP B-NP O
, , O O
o/w VBZ B-VP O
negative JJ B-ADJP O
in IN B-PP O
detail NN B-NP O
. . O O
Exam NNP B-NP O
: : O O
VS NNP B-NP O
: : O O
T NNP B-NP O
98.4 CD I-NP O
P NNP I-NP O
60s-70s CD I-NP O
BP NNP I-NP O
130s-140s/70s-80s CD I-NP O
RR NNP B-NP O
18 CD I-NP O
SaO2 NNP I-NP O
94 CD I-NP O
% NN I-NP O
RA NNP I-NP O
Gen NNP B-NP O
: : O O
NAD NNP B-NP O
, , I-NP O
friendly JJ I-NP O
, , I-NP O
interactive JJ I-NP O
. . I-NP O
A&Ox3 NNP I-NP O
( -LRB- O O
knew VBD B-VP O
NAMC NNP B-NP B-HOSPITAL
, , O O
year NN B-NP O
, , O O
53rd JJ B-NP O
floor NN I-NP O
, , O O
name NN B-NP O
, , O O
but CC O O
March NNP B-NP B-DATE
03 CD I-NP I-DATE
) -RRB- O O
HEENT NNP B-NP O
: : O O
PERRL NN B-NP O
, , O O
sclera NN B-NP O
clear JJ I-NP O
, , O O
OP NNP B-NP O
clear JJ I-NP O
Neck NNP B-NP O
: : O O
Supple NNP B-NP O
, , O O
no DT B-NP O
LAD NN I-NP O
Chest NNP B-NP O
: : O O
Good JJ B-NP O
A/E NNP I-NP O
throughout IN B-PP O
. . B-NP O
Bibasilar NNP I-NP O
rales NNP I-NP O
. . O O
No DT O O
wheezes NNPS B-NP O
. . O O
CV NNP B-NP O
: : O O
RRR NNP B-NP O
, , O O
no DT B-NP O
m/g/r NN I-NP O
. . O O
Nl NNP B-NP O
S1 NNP I-NP O
, , O O
S2 NNP B-NP O
. . O O
Abd NNP B-NP O
: : O O
Soft NNP B-NP O
, , O O
nd/nt NN B-NP O
. . O O
NABS. '' O O
No DT B-NP O
masses NNS I-NP O
. . O O
Ext JJ B-NP O
: : O O
WWP. NNP B-NP O
No NNP I-NP O
c/c/e NN I-NP O
. . O O
Neuro NNP B-NP O
: : O O
CN NNP B-NP O
II-XII NNP I-NP O
and CC O O
4 CD B-NP O
extremity NN I-NP O
strength NN I-NP O
grossly RB B-ADJP O
intact JJ I-ADJP O
. . O O
Data NNP B-NP O
: : O O
Hematology NNP B-NP O
Detail NNP I-NP O
for IN B-PP O
DOHERTY NNP B-NP I-PATIENT
, , O I-PATIENT
DANIEL NNP B-NP I-PATIENT
FMC NNP B-NP B-HOSPITAL
05-Mar-2133 CD I-NP B-DATE
08:15 CD I-NP O
Accession NNP B-NP O
# # B-ADJP O
5715 CD O I-MEDICALRECORD
:Z59777 CD O I-MEDICALRECORD
Test NNP B-NP O
Description NNP I-NP O
Result NNP I-NP O
Flags NNP I-NP O
Ref NNP I-NP O
. . I-NP O
Range NNP I-NP O
Units . O O
WBC NNP B-NP O
8.6 CD I-NP O
# # I-NP O
( -LRB- I-NP O
4.8-10.8 CD I-NP O
) -RRB- I-NP O
K/mm3 . O O
RBC NNP B-NP O
3.70 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
4.7-6.1 CD I-NP O
) -RRB- I-NP O
M/uL . O O
HEMOGLOBIN NNP B-NP O
10.9 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
14.0-18.0) JJ I-NP O
g/L NN I-NP O
HEMATOCRIT NNP B-NP O
31.8 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
42-52 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
MCV NN B-NP O
85.9 CD I-NP O
( -LRB- I-NP O
80-94 CD B-PP O
) -RRB- B-NP O
fl NN I-NP O
MCH NNP B-NP O
29.5 CD I-NP O
( -LRB- I-NP O
27-31 CD I-NP O
) -RRB- I-NP O
pg . O O
MCHC NNP B-NP O
34.3 CD I-NP O
( -LRB- I-NP O
33-37 CD I-NP O
) -RRB- I-NP O
g/dl . O O
PLATELET NNP B-NP O
COUNT NN I-NP O
180 CD B-NP O
( -LRB- I-NP O
130-400 CD I-NP O
) -RRB- I-NP O
K/uL . O O
GRANULOCYTES NNS B-NP O
62.0 CD B-NP O
( -LRB- I-NP O
37-80 CD B-PP O
) -RRB- B-NP O
% NN I-NP O
LYMPHOCYTE NN B-NP O
21.8 CD I-NP O
( -LRB- I-NP O
10-50 CD B-PP O
) -RRB- B-NP O
% NN I-NP O
MONOCYTES VBZ O O
8.2 CD B-NP O
(0-12 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
EOS NNS B-NP O
% NN I-NP O
7.1 CD I-NP O
H NNP I-NP O
(0-7 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
BASO NNP B-NP O
% NN I-NP O
0.9 CD B-NP O
(0-2.5 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
GRAN NNP B-NP O
# # I-NP O
5.3 CD O O
FMC NNP B-NP B-HOSPITAL
05-Mar-2133 CD I-NP B-DATE
08:15 CD I-NP O
Accession NNP B-NP O
# # B-ADJP O
6804 CD O I-MEDICALRECORD
:Q02120 CD O I-MEDICALRECORD
Test NNP B-NP O
Description NNP I-NP O
Result NNP I-NP O
Flags NNP I-NP O
Ref NNP I-NP O
. . I-NP O
Range NNP I-NP O
Units . O O
BUN JJ B-NP O
20 CD I-NP O
( -LRB- I-NP O
9-26 CD I-NP O
) -RRB- I-NP O
mg/dL . O O
CREATININE NNP B-NP O
1.3 CD I-NP O
( -LRB- I-NP O
0.7-1.3 CD B-PP O
) -RRB- B-NP O
mg/dL . O O
SODIUM JJ B-NP O
144 CD I-NP O
( -LRB- I-NP O
136-145 CD I-NP O
) -RRB- I-NP O
mEq/L . O O
POTASSIUM NNP B-NP O
4.2 CD I-NP O
( -LRB- I-NP O
3.4-4.8 CD I-NP O
) -RRB- I-NP O
mEq/L . O O
CHLORIDE NNP B-NP O
104 CD I-NP O
(98-107 CD I-NP O
) -RRB- I-NP O
mEq/L . O O
CARBON NNP B-NP O
DIOXIDE NNP I-NP O
27 CD I-NP O
( -LRB- I-NP O
21-30 CD I-NP O
) -RRB- I-NP O
mEq/L . O O
Test NNP B-NP O
Description NNP I-NP O
Result NNP I-NP O
Flags NNP I-NP O
Ref NNP I-NP O
. . I-NP O
Range NNP I-NP O
Units . O O
UA-Color NN B-NP O
Yellow NNP I-NP O
( -LRB- O O
YELLOW) NN O O
UA-Turbidity NN B-NP O
Clear NNP I-NP O
( -LRB- I-NP O
CLEAR NN I-NP O
) -RRB- O O
UA-Glucose JJ B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Bili JJ B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Ketones NNP B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Specific JJ B-NP O
Gravity NNP I-NP O
1.012 CD I-NP O
( -LRB- I-NP O
1.001-1.035 CD I-NP O
) -RRB- O O
UA-Occult JJ B-NP O
Blood NN I-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-pH NN B-NP O
5.5 CD I-NP O
( -LRB- I-NP O
5.0-9.0) CD O O
UA-Albumin NN B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Urobilinogen NN B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Nitrite JJ B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-WBC NNP B-NP O
Screen NNP I-NP O
NEGATIVE NNP I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
2/18/33 CD B-NP B-DATE
Carotid NNP I-NP O
Duplex NNP I-NP O
1 LS O O
. . B-NP O
Bilateral NNP I-NP O
minimal JJ I-NP O
1-19 CD I-NP O
% NN I-NP O
stenosis NN I-NP O
of IN B-PP O
the DT B-NP O
internal JJ I-NP O
carotid NN I-NP O
arteries NNS I-NP O
. . O O
2. `` O O
No DT B-NP O
significant JJ I-NP O
stenosis NN I-NP O
in IN B-PP O
the DT B-NP O
external JJ I-NP O
carotid NN I-NP O
arteries NNS I-NP O
bilaterally RB B-ADVP O
. . O O
3. VBD O O
Antegrade NNP B-NP O
flow NN I-NP O
in IN B-PP O
both DT B-NP O
vertebral JJ I-NP O
arteries NNS I-NP O
. . O O
Radiology NNP B-NP O
: : O O
ANATOMIC NNP B-NP O
REGION NNP I-NP O
STATUS NNP I-NP O
ROUTINE NNP I-NP O
DIMENSIONS NNP I-NP O
REGIONAL NNP I-NP O
WALL NNP I-NP O
MOTION NN I-NP O
( -LRB- B-NP O
normal JJ I-NP O
) -RRB- B-NP O
( -LRB- B-VP O
completed VBN I-VP O
only RB B-ADVP O
if IN B-PP O
abn JJ B-ADJP O
. . O O
) -RRB- O O
MITRAL NNP B-NP O
VALVE NNP I-NP O
ABN NNP I-NP O
SEGMENT NNP I-NP O
BASE NNP I-NP O
MID NNP I-NP O
APEX NNP I-NP O
LEFT NNP B-NP O
ATRIUM NNP I-NP O
ABN NNP I-NP O
LA NNP I-NP O
48 CD I-NP O
( -LRB- I-NP O
25-38mm JJ I-NP O
) -RRB- O O
AV. NNP B-NP O
A0 NNP I-NP O
. . I-NP O
LVOT NNP I-NP O
ABN NNP I-NP O
AO NNP I-NP O
38 CD I-NP O
( -LRB- I-NP O
24-39mm JJ I-NP O
) -RRB- I-NP O
anterior CC O O
LEFT NNP B-NP O
VENT. NNP I-NP O
ABN NNP I-NP O
LVIDd NNP I-NP O
61 CD I-NP O
( -LRB- O O
37-53mm JJ B-NP O
) -RRB- I-NP O
ant JJ I-NP O
.sep. . O O
TV NN B-NP O
. . O O
RA. '' O O
VC. NNP B-NP O
NORM NNP I-NP O
LVIDs NNP I-NP O
53 CD I-NP O
mid NN I-NP O
.sep. . O O
PV. NNP B-NP O
INF. NNP I-NP O
PA. NNP I-NP O
NORM NNP I-NP O
PWT NNP I-NP O
13 CD I-NP O
( -LRB- O O
7-11mm UH B-VP O
) -RRB- B-NP O
inf NN I-NP O
.sep. . O O
RIGHT NNP B-NP O
VENT. NNP I-NP O
NORM NNP I-NP O
IVS NNP I-NP O
11 CD I-NP O
( -LRB- I-NP O
7-11mm JJ I-NP O
) -RRB- I-NP O
inferior JJ O O
IAS. NNP B-NP O
IVS. NNP I-NP O
NORM NNP I-NP O
inf.pos NNS I-NP O
. . O O
COMPLEX NNP B-NP O
CHD NNP I-NP O
EF NNP I-NP O
35 CD I-NP O
% NN I-NP O
( -LRB- I-NP O
>50 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
pos NNS I-NP O
.lat NN I-NP O
. . O O
CORONARIES NNS B-NP O
UV NN I-NP O
lateral JJ O O
PERICARDIUM NN B-NP O
NORM NN I-NP O
Wall NNP B-NP O
Motion NNP I-NP O
Abbreviations NNP I-NP O
: : O O
N=Normal JJ B-NP O
H=Hypokinetic JJ I-NP O
A=Akinetic JJ I-NP O
D=Dyskinetic JJ I-NP O
RefMD NNP B-NP O
IANNONE NNP I-NP B-DOCTOR
MD NNP I-NP O
, , O O
FISCHER NNP B-NP B-DOCTOR
. . I-NP O
Reason NNP I-NP O
CAD NNP I-NP O
; : O O
S/P NNP B-NP O
CABG NNP I-NP O
; : O O
? . B-NP O
LV NNP I-NP O
fxn NN I-NP O
; : O O
? . B-NP O
Valve NNP I-NP O
DZ NNP I-NP O
; : O O
Tape NNP B-NP O
Color NNP I-NP O
: : O O
Number NN B-NP O
: : O O
Footage NN B-NP O
: : O O
- : O O
Study VB B-VP O
Quality NN B-NP O
: : O O
4 CD O O
Color NNP B-NP O
Flow NNP I-NP O
Doppler NNP I-NP O
TTE . O O
-Technically RB B-ADVP O
Difficult JJ B-ADJP O
Study- . O O
Sub NNP B-NP O
optimal JJ I-NP O
parasternal JJ I-NP O
images NNS I-NP O
. . O O
MITRAL NNP B-NP O
VALVE CD I-NP O
There EX B-NP O
is VBZ B-VP O
calcification NN B-NP O
of IN B-PP O
the DT B-NP O
posterior JJ I-NP O
mitral JJ I-NP O
annulus NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
mitral JJ B-NP O
valve NN I-NP O
prolapse NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
mitral JJ B-NP O
regurgitation NN I-NP O
by IN B-PP O
color NN B-NP O
and CC I-NP O
spectral JJ I-NP O
Doppler NNP I-NP O
. . O O
LEFT NNP B-NP O
ATRIUM NNP I-NP O
The DT B-NP O
left JJ I-NP O
atrium NN I-NP O
is VBZ B-VP O
dilated VBN I-VP O
. . O O
AORTIC NNP B-NP O
VALVE NNP I-NP O
, , O O
AORTA NNP B-NP O
, , O O
LVOT NNP B-NP O
Multiple JJ B-NP O
aortic JJ I-NP O
leaflets NNS I-NP O
are VBP B-VP O
thickened VBN I-VP O
but CC O O
there EX B-NP O
is VBZ B-VP O
no DT B-NP O
stenosis NN I-NP O
. . O O
The DT B-NP O
aortic NN I-NP O
valve NN B-NP O
is VBZ B-VP O
tricuspid JJ B-ADJP O
. . O O
There EX B-NP O
is VBZ B-VP O
evidence NN B-NP O
of IN B-PP O
trace NN B-NP O
aortic JJ I-NP O
insufficiency NN I-NP O
by IN B-PP O
color NN B-NP O
and CC O O
spectral JJ B-NP O
Doppler NNP I-NP O
. . O O
LEFT NNP B-NP O
VENTRICLE NNP I-NP O
The DT B-NP O
left VBD B-VP O
ventricular JJ B-NP O
cavity NN I-NP O
size NN I-NP O
is VBZ B-VP O
dilated VBN I-VP O
. . O O
The DT O O
left VBD B-VP O
ventricular JJ B-NP O
systolic NN I-NP O
function NN B-NP O
is VBZ B-VP O
moderately RB I-VP O
impaired VBN I-VP O
. . O O
The DT B-NP O
left VBN I-NP O
ventricle NN I-NP O
is VBZ B-VP O
diffusely RB B-ADJP O
hypokinetic JJ I-ADJP O
with IN B-PP O
regional JJ B-NP O
variation NN I-NP O
. . O O
The DT B-NP O
estimated VBN I-NP O
ejection NN I-NP O
fraction NN I-NP O
is VBZ B-VP O
35 CD B-NP O
% NN I-NP O
. . O O
TRICUSPID NNP B-NP O
VALVE NNP I-NP O
- : O O
IVC NNP B-NP O
, , O O
SVC NNP B-NP O
There EX B-NP O
is VBZ B-VP O
color NN B-NP O
and CC O O
spectral JJ B-NP O
Doppler NNP I-NP O
evidence NN I-NP O
of IN B-PP O
trace NN B-NP O
tricuspid JJ I-NP O
insufficiency NN I-NP O
. . O O
PULMONARY NNP B-NP O
VALVE NNP I-NP O
, , O O
INFUND. NNP B-NP O
, , O O
P.A. . O O
There EX B-NP O
is VBZ B-VP O
an DT B-NP O
insufficient JJ I-NP O
tricuspid JJ I-NP O
regurgitation NN I-NP O
Doppler NNP I-NP O
profile NN I-NP O
to TO B-VP O
estimate VB I-VP O
an DT B-NP O
RV NN I-NP O
systolic JJ I-NP O
pressure NN I-NP O
. . O O
RIGHT NNP B-NP O
VENTRICLE NNP I-NP O
The DT B-NP O
right JJ I-NP O
ventricle NN I-NP O
is VBZ B-VP O
not RB I-VP O
dilated VBN I-VP O
. . O O
The DT B-NP O
right NN I-NP O
ventricular VBD B-VP O
systolic JJ B-NP O
function NN I-NP O
is VBZ B-NP O
within IN B-PP O
normal JJ B-NP O
limits NNS I-NP O
. . O O
PERICARDIAL NNP B-NP O
DISEASE NN I-NP O
AND CC I-NP O
EXTRACARDIAC NNPS I-NP O
MASSES NNS I-NP O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
pericardial JJ B-NP O
effusion NN I-NP O
. . O O
2/11/33 CD B-NP B-DATE
Left VBD B-VP O
Heart NNP B-NP O
Cath NNP I-NP O
1 CD B-NP O
) -RRB- I-NP O
Three CD I-NP O
vessel NN I-NP O
coronary JJ I-NP O
artery NN I-NP O
disease NN B-NP O
. . O O
The DT B-NP O
Left NNP I-NP O
Main NNP I-NP O
is VBZ B-VP O
large JJ B-ADJP O
and CC O O
has VBZ B-VP O
only RB B-NP O
mild JJ I-NP O
irregularities NNS I-NP O
. . O O
The DT B-NP O
LAD NN I-NP O
is VBZ B-LST O
diffusely JJ B-NP O
diseased JJ I-NP O
( -LRB- I-NP O
30 CD I-NP O
- : O O
40 CD B-NP O
% NN I-NP O
) -RRB- O O
and CC O O
has VBZ B-VP O
a DT B-NP O
distal JJ I-NP O
80 CD I-NP O
% NN I-NP O
stenosis NN I-NP O
. . O O
The DT B-NP O
Left NNP I-NP O
Cx NNP I-NP O
is VBZ O O
totally RB B-ADVP O
occluded VBD B-VP O
The DT B-NP O
LCx NNP I-NP O
receives VBZ B-VP O
faint JJ B-NP O
collaterals NNS I-NP O
from IN B-PP O
the DT B-NP O
LAD NN I-NP O
territority NN I-NP O
. . O O
The DT B-NP O
ramus JJ I-NP O
branch NN I-NP O
has VBZ B-VP O
diffuse JJ B-NP O
disease NN I-NP O
with IN B-PP O
a DT B-NP O
80 CD I-NP O
% NN I-NP O
proximal JJ I-NP O
stenosis NN I-NP O
and CC O O
a DT B-NP O
70 CD I-NP O
% NN I-NP O
mid . O O
stenosis NN B-NP O
. . O O
The DT B-NP O
RCA NNP I-NP O
is VBZ B-VP O
occluded VBN I-VP O
proximally RB B-ADVP O
and CC O O
there EX B-NP O
are VBP B-VP O
right JJ B-ADJP O
to TO B-PP O
right NN B-NP O
collaterals NNS B-NP O
. . O O
There EX B-NP O
are VBP B-VP O
80 CD B-NP O
% NN I-NP O
mid NN I-NP O
and CC O O
80 CD B-NP O
% NN I-NP O
distal JJ I-NP O
stenoses NNS I-NP O
in IN B-PP O
the DT B-NP O
RCA NNP I-NP O
. . O O
2 CD B-NP O
) -RRB- I-NP O
LV NN I-NP O
gram NN I-NP O
shows VBZ B-VP O
EF NNS B-NP O
of IN B-PP O
30 CD B-NP O
% NN I-NP O
, , O O
with IN B-PP O
anterior/apical JJ B-NP O
akinesis NN I-NP O
and CC O O
inferior JJ B-NP O
hypokinesis NN B-NP O
. . O O
3 CD B-NP O
) -RRB- I-NP O
Right RB I-NP O
dominant JJ I-NP O
system NN I-NP O
EKG NNP B-NP O
: : O O
Admission NN B-NP O
( -LRB- B-VP O
no DT B-NP O
recent JJ I-NP O
EKG NNP I-NP O
available JJ I-NP O
for IN B-PP O
comparison NN B-NP O
upon IN B-PP O
admit VB B-NP O
) -RRB- O O
NSR NNP B-NP O
@ NNP I-NP O
66 CD I-NP O
, , I-NP O
LAD NNP I-NP O
, , I-NP O
IVCD NNP I-NP O
( -LRB- I-NP O
QRS NNP I-NP O
114 CD I-NP O
) -RRB- I-NP O
with IN B-PP O
partial JJ B-NP O
LBBB NNP I-NP O
morphology NN I-NP O
, , O O
PRWP NNP B-NP O
, , O O
nonspecific JJ B-NP O
STTW NN I-NP O
changes NNS I-NP O
( -LRB- O O
inverted VBN B-VP O
I PRP B-NP O
, , O O
II NNP B-NP O
, , O O
L) NNP B-NP O
. . O O
Impression NN B-NP O
: : O O
68 CD B-NP B-AGE
yo NNP I-NP O
M NNP I-NP O
with IN B-PP O
h/o JJ B-NP O
vfib NN I-NP O
arrest NN I-NP O
and CC O O
severe JJ B-NP O
3-vd JJ I-NP O
, , O O
transferred VBN B-VP O
back RB B-ADVP O
to TO B-PP O
NAMC NNP B-NP B-HOSPITAL
from IN B-PP O
FMC NNP B-NP B-HOSPITAL
in IN B-PP O
preparation NN B-NP O
for IN B-PP O
CABG NNP B-NP O
planned VBD B-VP O
03/07/33 CD B-NP B-DATE
. . O O
Plan NNP B-NP O
: : O O
CV NNP B-NP O
Admitted NNP I-NP O
for IN B-PP O
CABG NNP B-NP O
Ischemia NNP B-NP O
: : O O
Continue NNP B-NP O
BB NNP I-NP O
, , O O
titrate NN B-NP O
as IN B-PP O
needed VBN B-NP O
, , I-NP O
statin NN I-NP O
. . O O
Pt NNP O O
not RB O O
on IN B-PP O
ASA NNP B-NP O
( -LRB- I-NP O
d/c NN I-NP O
d VBN B-VP O
during IN B-PP O
last JJ B-NP O
hospitalization NN I-NP O
) -RRB- I-NP O
, , O O
will MD B-VP O
clarify VB I-VP O
in IN B-PP O
AM. NNP B-NP O
Pre-op NNP I-NP O
work-up NN I-NP O
per IN B-PP O
cardiac NN B-NP O
surgery NN I-NP O
in IN B-PP O
preparation NN B-NP O
for IN B-PP O
CABG. NNP B-NP O
Pump NNP B-NP O
: : O O
Euvolemia NNP B-NP O
. . O O
Will MD B-VP O
continue VB I-VP O
Lasix NNP B-NP O
40 CD I-NP O
mg NN I-NP O
and CC O O
BB NNP B-NP O
. . I-NP O
Strict NNP I-NP O
Is/Os NNP I-NP O
, , O O
daily JJ B-NP O
wts NNS I-NP O
. . O O
Rhythm NN B-NP O
: : O O
Cont NNP B-NP O
BB NNP I-NP O
. . I-NP O
Replete NNP I-NP O
lytes VBZ B-VP O
prn NN B-NP O
. . O O
PULM NNP B-NP O
Wheezing NNP I-NP O
during IN B-PP O
recent JJ B-NP O
hospitalization NN I-NP O
( -LRB- I-NP O
?cardiac NN I-NP O
) -RRB- I-NP O
, , O O
and CC O O
smoking NN B-NP O
hx NN I-NP O
. . O O
--Albuterol/Atrovent JJ B-NP O
prn NN I-NP O
ID NNP B-NP O
afebrile NN I-NP O
, , O O
no DT B-NP O
leukocytosis NN I-NP O
, , O O
UA NNP B-NP O
neg NN I-NP O
. . O O
--Monitor NN B-NP O
for IN B-PP O
occult JJ B-NP O
infxn NN I-NP O
pre-operatively RB B-LST O
--Cont JJ B-NP O
Nystatin NNP I-NP O
powder NN I-NP O
as IN B-SBAR O
needed VBN O O
NEURO/PSYCH NNP B-NP O
S/p NNP I-NP O
hypoxic JJ I-NP O
encephalopathy NN I-NP O
. . O O
H/o NNP B-NP O
BAD NNP I-NP O
, , O O
depression NN B-NP O
, , O O
schizophrenia NN B-NP O
--Cont JJ B-NP O
Trazodone NNP I-NP O
and CC I-NP O
Olanzapine NNP I-NP O
qhs NNP I-NP O
, , O O
Olanzapine NNP B-NP O
prn NN I-NP O
anxiety/agitation NN I-NP O
--Holding JJ B-NP O
Darvocet NNP I-NP O
to TO B-VP O
assist VB I-VP O
mental JJ B-NP O
clarity NN I-NP O
pre-operatively RB B-ADVP O
, , O O
and CC O O
uncertain JJ B-NP O
indication NN I-NP O
FEN NNS B-NP O
--Euvolemia NN B-NP O
--Monitor NN B-NP O
lytes NNS I-NP O
--Cont JJ B-NP O
MVI NNP I-NP O
, , O O
B12 NNP B-NP O
, , O O
cardiac NN B-NP O
diet NN I-NP O
PPx NN B-NP O
--Lovenox NN B-NP O
( -LRB- I-NP O
will MD B-VP O
clarify VB I-VP O
timing NN B-NP O
of IN B-PP O
surgery NN B-NP O
and CC I-NP O
hold NN I-NP O
accordingly RB B-ADVP O
) -RRB- O O
--Bowel NN B-NP O
regimen NNS I-NP O
--PP NN B-NP O
I PRP O O
PT/OT JJ B-NP O
: : O O
deferred VBN O O
Access NNP B-NP O
: : O O
PIV NN B-NP O
IV NNP B-NP O
fluids NNS I-NP O
: : O O
none NN B-NP O
Telemetry NNP B-NP O
: : O O
continuous JJ O O
Lines/Tubes NNP B-NP O
: : O O
none NN B-NP O
Precautions NNS B-NP O
: : O O
none NN B-NP O
Code NNP B-NP O
Status NNP I-NP O
: : O O
full JJ O O
Disposition NN B-NP O
: : O O
plan NN B-NP O
for IN B-PP O
CABG NNP B-NP O
on IN B-PP O
3/07 CD B-NP B-DATE
Ulysess NNP B-NP B-DOCTOR
Dodge NNP I-NP I-DOCTOR
, , O O
MD . O O
Pager NNP B-NP O
# # I-NP O
11365 CD O B-PHONE
