Record NNP B-NP O
date NN I-NP O
: : O O
2079-06-14 CD O B-DATE
EDVISIT^ NNP B-NP O
46103196 CD I-NP B-MEDICALRECORD
^ , O O
HART NNP B-NP I-PATIENT
, , O I-PATIENT
MATTHEW NNP B-NP I-PATIENT
^ NNP I-NP O
06/14/79 CD I-NP B-DATE
^ NN I-NP O
NAPOLITANO NNP I-NP I-DOCTOR
, , O I-DOCTOR
URSULA NNP B-NP I-DOCTOR
HISTORY NN B-NP O
OF IN B-PP O
PRESENT JJ B-NP O
ILLNESS NNS I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
a DT B-NP O
56 CD I-NP B-AGE
-year-old JJ I-NP O
male NN I-NP O
with IN B-PP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
end-stage NN B-NP O
renal JJ I-NP O
disease NN I-NP O
on IN B-PP O
hemodialysis NN B-NP O
, , O O
history NN B-NP O
of IN B-PP O
coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
, , O O
diabetes NNS B-NP O
, , O O
hypertension NN B-NP O
, , O O
and CC O O
DVT NNP B-NP O
on IN B-PP O
Coumadin NNP B-NP O
who WP B-NP O
comes VBZ B-VP O
in IN B-ADVP O
to TO B-PP O
the DT B-NP O
ER NNP I-NP O
because IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
recently RB O O
missed VBN B-NP O
dialysis NN I-NP O
appointment NN I-NP O
and CC O O
he PRP B-NP O
feels VBZ B-VP O
increased VBN I-VP O
abdominal NN B-NP O
girth NN B-NP O
and CC I-NP O
shortness NN I-NP O
of IN B-PP O
breath NN B-NP O
. . O O
He PRP B-NP O
said VBD B-VP O
that IN O O
his PRP$ B-NP O
father NN I-NP O
has VBZ B-VP O
been VBN I-VP O
sick JJ B-ADVP O
, , O O
so IN O O
he PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
spending VBG I-VP O
a DT B-NP O
significant JJ I-NP O
amount NN I-NP O
of IN B-PP O
time NN B-NP O
helping VBG B-VP O
him PRP B-NP O
and CC O O
because IN B-PP O
of IN I-PP O
that DT B-NP O
had VBD B-VP O
a DT B-NP O
short JJ I-NP O
dialysis NN I-NP O
on IN B-PP O
Wednesday NNP B-NP B-DATE
and CC O O
missed VBD B-VP O
his PRP$ B-NP O
Friday NNP I-NP B-DATE
dialysis NN I-NP O
run NN I-NP O
. . O O
Today NN B-NP O
is VBZ B-VP O
Sunday NNP B-NP B-DATE
and CC O O
he PRP B-NP O
generally RB B-ADVP O
gets VBZ B-VP O
dialysis NN B-NP O
on IN B-PP O
Sunday NNP B-NP B-DATE
as IN B-PP O
well RB B-NP O
. . O O
When WRB B-ADVP O
I PRP B-NP O
asked VBD B-VP O
if IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
having VBG I-VP O
chest NN B-NP O
pain NN I-NP O
, , O O
he PRP B-NP O
says VBZ B-VP O
he PRP B-NP O
has VBZ B-VP O
not RB I-VP O
had VBN I-VP O
chest NN B-NP O
pain NN I-NP O
, , O O
but CC O O
he PRP B-NP O
did VBD B-VP O
have VB I-VP O
a DT B-NP O
tickling NN I-NP O
in IN B-PP O
his PRP$ B-NP O
chest NN I-NP O
that WDT B-NP O
lasted VBD B-VP O
seconds NNS B-NP O
and CC O O
was VBD B-VP O
not RB I-VP O
accompanying VBG I-VP O
with IN B-PP O
any DT B-NP O
diaphoresis NN I-NP O
or CC I-NP O
radiation NN I-NP O
of IN B-PP O
the DT O O
pain NN B-NP O
. . O O
Even RB O O
he PRP B-NP O
was VBD B-VP O
ambulatory JJ B-ADJP O
into IN B-PP O
the DT B-NP O
ED NNP I-NP O
, , O O
he PRP B-NP O
had VBD B-VP O
no DT B-NP O
chest NN I-NP O
pain NN I-NP O
when WRB B-ADVP O
he PRP B-NP O
was VBD B-VP O
exerting VBG I-VP O
himself PRP B-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
feel VB I-VP O
slightly RB B-ADJP O
increased VBN I-ADJP O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
and CC I-NP O
worse JJR I-NP O
when WRB B-ADVP O
he PRP B-NP O
walks VBZ B-VP O
around RB B-ADVP O
, , O O
but CC O O
he PRP B-NP O
thinks VBZ B-VP O
that IN B-PP O
because IN B-PP O
of IN I-PP O
increased VBN B-NP O
fluids NNS I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
no DT B-NP O
fevers NNS I-NP O
or CC O O
chills NNS B-NP O
, , O O
no DT B-NP O
lightheadedness NN I-NP O
, , O O
no DT B-NP O
nausea NN I-NP O
, , I-NP O
vomiting NN I-NP O
and CC O O
no DT B-NP O
diarrhea NN I-NP O
. . O O
PAST NN B-NP O
MEDICAL NNP I-NP O
HISTORY NNP I-NP O
: : O O
End-stage NN B-NP O
renal JJ I-NP O
disease NN I-NP O
on IN B-PP O
hemodialysis NN B-NP O
, , O O
coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
, , O O
hyperlipidemia NN B-NP O
, , O O
osteoarthritis NN B-NP O
, , O O
diabetes NNS B-NP O
, , O O
DVT NNP B-NP O
on IN B-PP O
Coumadin NNP B-NP O
, , O O
hypertension NN B-NP O
, , O O
bladder NN B-NP O
cancer NN I-NP O
, , O O
substance NN B-NP O
abuse NN I-NP O
and CC O O
GERD. NNP B-NP O
PAST NNP B-NP O
SURGICAL NNP I-NP O
HISTORY NNP I-NP O
: : O O
AV NNP B-NP O
fistula NN I-NP O
in IN B-PP O
01/2078 CD B-NP B-DATE
. . O O
SOCIAL JJ B-NP O
HISTORY NNP I-NP O
: : O O
No DT B-NP O
tobacco NN I-NP O
, , I-NP O
rare JJ I-NP O
alcohol NN I-NP O
and CC O O
occasional JJ B-NP O
cocaine NN I-NP O
use NN B-NP O
. . O O
FAMILY NNP B-NP O
HISTORY NNP I-NP O
: : O O
Breast NN B-NP O
cancer NN I-NP O
and CC I-NP O
prostate NN I-NP O
cancer NN I-NP O
. . O O
REVIEW NN B-NP O
OF IN B-PP O
SYSTEMS NNP B-NP O
: : O O
As IN B-SBAR O
mentioned VBN B-VP O
in IN B-PP O
HPI NNP B-NP O
, , O O
otherwise RB B-ADVP O
negative JJ B-ADJP O
. . O O
MEDICATIONS NNS B-NP O
: : O O
Reviewed VBN B-VP O
, , O O
please VBP B-VP O
see VB I-VP O
the DT B-NP O
list NN I-NP O
. . O O
ALLERGIES NNS B-NP O
: : O O
Include VB B-VP O
cephalosporin NN B-NP O
and CC I-NP O
simvastatin NN I-NP O
. . O O
PHYSICAL NNP B-NP O
EXAMINATION NNP I-NP O
: : O O
Temperature NNP B-NP O
97.3 CD I-NP O
, , I-NP O
heart NN I-NP O
rate NN I-NP O
92 CD I-NP O
, , O O
respiratory JJ B-NP O
rate NN I-NP O
28 CD I-NP O
, , I-NP O
blood NN I-NP O
pressure NN I-NP O
155/8 CD B-NP O
4 CD I-NP O
and CC O O
O2 CD B-NP O
saturation NN I-NP O
100 CD B-NP O
% NN I-NP O
on IN B-PP O
room NN B-NP O
air NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
awake JJ B-ADJP O
, , I-ADJP O
alert JJ I-ADJP O
, , O O
talking VBG B-VP O
in IN B-PP O
complete JJ B-NP O
sentences NNS B-NP O
, , O O
appears VBZ B-VP O
to TO I-VP O
be VB I-VP O
mildly RB B-ADJP O
uncomfortable JJ I-ADJP O
. . O O
ENT NNP B-NP O
: : O O
Atraumatic NNP B-NP O
. . O O
Neck NNP B-NP O
: : O O
Normal JJ B-NP O
to TO B-PP O
inspection NN B-NP O
, , I-NP O
supple NN I-NP O
. . O O
Chest NNP B-NP O
: : O O
Clear NNP B-NP O
to TO I-NP O
auscultation NN B-NP O
bilaterally RB I-NP O
, , O O
no DT B-NP O
rales NNS I-NP O
. . O O
Cardiovascular NNP B-NP O
: : O O
Regular NNP O O
rate NN B-NP O
and CC I-NP O
rhythm NN I-NP O
, , O O
no DT B-NP O
murmurs NNS I-NP O
, , O O
rubs NNS B-NP O
, , O O
or CC O O
gallops NNS B-NP O
. . O O
Abdomen NNP B-NP O
: : O O
Minimal NNP O O
distention NN B-NP O
, , O O
soft JJ B-ADJP O
. . O O
No DT B-NP O
focal JJ I-NP O
tenderness NN I-NP O
. . O O
Skin NNP B-NP O
is VBZ B-VP O
intact JJ B-ADJP O
. . O O
Extremities NNS B-NP O
: : O O
No DT B-NP O
lower JJR I-NP O
extremity NN I-NP O
swelling VBG I-NP O
or CC I-NP O
edema NN I-NP O
, , O O
no DT B-NP O
calf NN I-NP O
tenderness NN B-NP O
bilaterally RB B-ADVP O
. . B-VP O
Neuropsychiatric JJ B-ADJP O
: : O O
Oriented JJ B-NP O
x3 NNS I-NP O
. . O O
Cranial NN O O
nerves NNS B-NP O
II NNP I-NP O
through IN B-PP O
XII NNP B-NP O
tested VBD B-VP O
and CC O O
intact JJ B-ADJP O
. . O O
No DT B-NP O
motor NN I-NP O
or CC I-NP O
sensory JJ I-NP O
deficits NNS B-NP O
. . O O
Gait NN B-NP O
is VBZ B-VP O
normal JJ B-ADJP O
. . O O
EMERGENCY NNP B-NP O
DEPARTMENT NNP I-NP O
COURSE NNP I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
received VBD B-VP O
an DT B-NP O
EKG NNP I-NP O
, , O O
which WDT O O
showed VBD B-VP O
normal JJ B-ADJP O
sinus IN B-PP O
rhythm NN B-NP O
. . O O
No DT B-NP O
significant JJ I-NP O
ST NNP I-NP O
or CC I-NP O
T NNP I-NP O
abnormalities NNS B-NP O
, , O O
no DT B-NP O
significant JJ I-NP O
peaked JJ I-NP O
T NNP I-NP O
waves NNS I-NP O
are VBP B-VP O
consistent JJ B-ADJP O
with IN B-PP O
his PRP$ B-NP O
previous JJ I-NP O
EKG. NNP I-NP O
PA NNP I-NP O
lateral JJ I-NP O
chest NN I-NP O
x-ray NN I-NP O
showed VBD B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-SBAR O
acute JJ B-NP O
cardiopulmonary JJ I-NP O
infiltrates NNS I-NP O
. . O O
Only RB O O
labs NNS B-NP O
which WDT B-NP O
resulted VBD B-LST O
initially RB B-ADVP O
were VBD B-VP O
CBC NNP B-NP O
, , O O
which WDT B-NP O
showed VBD B-VP O
a DT B-NP O
hematocrit NN I-NP O
of IN B-PP O
33.2 CD B-NP O
, , O O
platelets NNS B-NP O
423,000 CD B-NP O
and CC O O
white JJ B-NP O
count NN I-NP O
of IN B-PP O
6.74 CD B-NP O
. . O O
We PRP B-NP O
made VBD B-VP O
contact NN B-NP O
with IN B-PP O
the DT B-NP O
renal NN I-NP O
fellow NN B-NP O
who WP B-NP O
recommended VBD B-VP O
that IN B-SBAR O
we PRP B-NP O
proceed VBP B-VP O
dialysis NN B-NP O
while IN B-SBAR O
the DT B-NP O
dialysis NN B-NP O
unit NN I-NP O
still RB B-ADVP O
open JJ B-ADJP O
and CC O O
we PRP B-NP O
felt VBD B-VP O
that IN B-SBAR O
it PRP B-NP O
was VBD B-VP O
safe JJ B-ADJP O
for IN B-SBAR O
this DT B-NP O
patient NN B-NP O
. . O O
His PRP$ B-NP O
potassium NN I-NP O
was VBD B-VP O
not RB O O
back RB B-ADVP O
at IN B-PP O
the DT B-NP O
time NN I-NP O
that IN B-SBAR O
he PRP B-NP O
left VBD B-VP O
the DT O O
department NN B-NP O
, , O O
however RB B-ADVP O
, , O O
he PRP B-NP O
was VBD B-VP O
well RB I-VP O
appearing VBG I-VP O
and CC O O
had VBD B-VP O
no DT B-NP O
arrhythmias NNS I-NP O
on IN B-PP O
the DT B-NP O
monitor NN I-NP O
and CC O O
we PRP B-NP O
think VBP B-VP O
that IN B-PP O
his PRP$ B-NP O
tickling NN I-NP O
chest NN I-NP O
sensation NN I-NP O
is VBZ O O
very RB B-ADJP O
atypical JJ I-ADJP O
for IN B-PP O
cardiac JJ B-NP O
symptom NN I-NP O
, , O O
not RB O O
being VBG B-VP O
, , O O
so IN O O
we PRP B-NP O
will MD B-VP O
reassess VB I-VP O
when WRB B-ADVP O
he PRP B-NP O
comes VBZ B-VP O
back RB B-ADVP O
and CC I-ADVP O
likely RB I-ADVP O
check VB B-VP O
a DT B-NP O
second JJ I-NP O
troponin NN I-NP O
to TO B-VP O
be VB I-VP O
sure JJ O O
that IN B-SBAR O
this DT B-NP O
is VBZ B-VP O
unlikely JJ B-ADJP O
to TO B-VP O
be VB I-VP O
acute JJ B-NP O
coronary JJ I-NP O
syndrome NN I-NP O
. . O O
After IN O O
he PRP O O
left VBD O O
the DT B-NP O
department NN I-NP O
, , O O
additional JJ B-NP O
labs NNS I-NP O
came VBD B-VP O
back RB I-VP O
include VB I-VP O
INR NNP B-NP O
of IN B-PP O
2.1 CD B-NP O
and CC O O
a DT B-NP O
Chem-7 NNP I-NP O
showing VBG B-VP O
a DT B-NP O
sodium NN I-NP O
of IN B-PP O
142 CD B-NP O
, , O O
a DT B-NP O
potassium NN I-NP O
of IN B-PP O
6.4 CD B-NP O
, , O O
a DT O O
chloride NN B-NP O
of IN B-PP O
102 CD B-NP O
, , O O
bicarbonate NN B-NP O
of IN B-PP O
21 CD B-NP O
, , O O
BUN NNP B-NP O
of IN B-PP O
106 CD B-NP O
, , O O
creatinine CD B-NP O
6.18 CD I-NP O
, , O O
glucose NN B-NP O
of IN B-PP O
195 CD B-NP O
, , O O
CK NNP B-NP O
of IN B-PP O
157 CD B-NP O
, , O O
troponin FW O O
of IN B-PP O
less JJR B-NP O
than IN I-NP O
0.04 CD I-NP O
, , O O
calcium NN B-NP O
8.6 CD B-NP O
, , O O
phosphorus NN B-NP O
of IN B-PP O
5.1 CD B-NP O
, , O O
and CC O O
magnesium NN B-NP O
of IN B-PP O
2.3 CD B-NP O
and CC O O
promptly RB B-VP O
called VBN I-VP O
the DT B-NP O
renal JJ I-NP O
fellow NN I-NP O
who WP B-NP O
was VBD B-VP O
aware JJ B-ADJP O
of IN B-PP O
the DT B-NP O
elevated JJ I-NP O
potassium NN I-NP O
and CC O O
have VB B-SBAR O
the DT B-NP O
patient NN I-NP O
on IN B-PP O
the DT B-NP O
monitor NN I-NP O
in IN B-PP O
the DT B-NP O
Dialysis NNP I-NP O
Unit NN I-NP O
and CC O O
agreed VBD B-VP O
to TO I-VP O
treat VB B-VP O
him PRP B-NP O
there RB B-ADVP O
acutely RB B-ADVP O
. . O O
Again RB B-ADVP O
after IN B-PP O
the DT B-NP O
dialysis NN I-NP O
, , O O
the DT B-NP O
patient NN I-NP O
will MD B-VP O
return VB I-VP O
to TO B-PP O
the DT B-NP O
Emergency NNP I-NP O
Department NNP I-NP O
. . O O
We PRP B-NP O
will MD B-VP O
reassess VB I-VP O
if IN B-PP O
symptoms NNS B-NP O
and CC O O
see VBP B-VP O
how WRB B-ADVP O
he PRP B-NP O
feels VBZ B-VP O
, , O O
check VB B-VP O
a DT B-NP O
second JJ I-NP O
cardiac NN I-NP O
enzymes NNS I-NP O
. . O O
If IN B-SBAR O
he PRP B-NP O
feels VBZ B-VP O
significantly RB I-VP O
improved VBN I-VP O
and CC O O
he PRP B-NP O
continues VBZ B-VP O
to TO I-VP O
have VB I-VP O
no RB B-PRT O
chest NN B-NP O
pain NN I-NP O
, , O O
we PRP B-NP O
feel VBP B-VP O
that IN B-PP O
his PRP$ B-NP O
symptoms NNS I-NP O
are VBP B-VP O
likely JJ B-ADJP O
atypical JJ I-ADJP O
for IN B-PP O
acute JJ B-NP O
coronary JJ I-NP O
syndrome NN I-NP O
and CC O O
we PRP B-NP O
also RB B-ADVP O
called VBD B-VP O
that IN B-SBAR O
this DT B-NP O
was VBD B-VP O
not RB O O
acute JJ B-NP O
coronary JJ I-NP O
syndrome NN I-NP O
if IN B-PP O
two CD B-NP O
troponins NNS I-NP O
are VBP B-VP O
not RB I-VP O
elevated VBN I-VP O
and CC O O
he PRP B-NP O
will MD B-VP O
be VB I-VP O
able JJ B-ADJP O
to TO B-VP O
follow VB I-VP O
up RB B-ADVP O
and CC O O
resume VB B-VP O
his PRP$ B-NP O
regular JJ I-NP O
dialysis NN I-NP O
schedule NN B-NP O
. . O O
PRIMARY NNP B-NP O
DIAGNOSIS NNP I-NP O
: : O O
Volume NN B-NP O
overload NN I-NP O
. . O O
SECONDARY NNP B-NP O
DIAGNOSIS NNP I-NP O
: : O O
End-stage NN B-NP O
renal JJ I-NP O
disease NN I-NP O
, , O O
on IN B-PP O
hemodialysis NN B-NP O
. . O O
DISPOSITION NN B-NP O
: : O O
Pending NNP B-NP O
. . O O
Please RB B-ADVP O
see VB B-VP O
ED VBN B-NP O
note NN I-NP O
for IN B-PP O
further JJ B-NP O
ED JJ I-NP O
course NN I-NP O
. . O O
This DT B-NP O
was VBD B-VP O
a DT B-NP O
shared VBN I-NP O
visit NN B-NP O
with IN B-PP O
resident JJ B-NP O
physician NN I-NP O
, , O O
Dr. NNP B-NP O
Adam NNP I-NP B-DOCTOR
Mcclure NNP I-NP I-DOCTOR
. . O O
NAPOLITANO NNP B-NP I-DOCTOR
, , O I-DOCTOR
URSULA NNP B-NP I-DOCTOR
M.D. NNP I-NP O
D NNP B-NP O
: : O O
06/14/79 CD O B-DATE
T NNP B-NP O
: : O O
06/14/79 CD O B-DATE
Dictated NNP B-NP O
By IN I-NP O
: : O O
NAPOLITANO NNP B-NP I-DOCTOR
, , O I-DOCTOR
URSULA NNP B-NP I-DOCTOR
eScription NN B-NP O
document NN I-NP O
: : O O
4-65347834 CD B-NP B-IDNUM
BFFocus NN I-NP O
******** NN B-NP O
Not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Physician JJ B-NP O
******** NNS I-NP O
