Record NNP B-NP O
date NN I-NP O
: : O O
2086-03-02 CD O B-DATE
Internal NNP B-NP O
Medicine NNP I-NP O
Reason NN B-NP O
for IN B-PP O
visitDyspnea NN B-NP O
on IN B-PP O
exertion NN B-NP O
Chest NNP B-NP O
discomfort NN I-NP O
of IN B-PP O
exertion NN B-NP O
Sore JJ B-NP O
throat NN I-NP O
Cough IN O O
History NN B-NP O
of IN B-PP O
present JJ B-NP O
problemThe NN I-NP O
patient NN I-NP O
is VBZ B-VP O
here RB I-VP O
indicating VBG I-VP O
that IN B-SBAR O
she PRP B-NP O
has VBZ B-VP O
joined VBN I-VP O
a DT B-NP O
gym NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
experiencing VBG I-VP O
chest NN B-NP O
discomfort NN I-NP O
and CC I-NP O
heavyness NN I-NP O
with IN B-PP O
dyspnea NN B-NP O
on IN B-PP O
exertion NN B-NP O
. . O O
The DT B-NP O
symptoms NNS I-NP O
appears VBZ B-VP O
when WRB B-ADVP O
she PRP B-NP O
is VBZ B-VP O
on IN B-PP O
the DT B-NP O
treadmill NN I-NP O
and CC O O
last JJ B-NP O
several JJ I-NP O
minutes NNS I-NP O
after IN B-SBAR O
she PRP B-NP O
stops VBZ B-VP O
. . O O
She PRP B-NP O
is VBZ B-VP O
worried VBN B-ADJP O
about IN B-PP O
it PRP B-NP O
. . O O
She PRP B-NP O
also RB B-ADVP O
complains VBZ B-VP O
of IN B-PP O
sore JJ B-NP O
throat NN I-NP O
and CC I-NP O
cough NN I-NP O
. . O O
Medical NNP B-NP O
historyCoronary JJ I-NP O
vasospastic JJ I-NP O
events NNS I-NP O
Glucose DT B-NP O
intolerance NN I-NP O
with IN B-PP O
post NN B-NP O
prandial JJ B-NP O
hyperglycemia NN I-NP O
Hyperlipidemia NNP B-NP O
Hypertension NN B-NP O
Postmenopausal NN B-NP O
Cervical JJ B-NP O
osteoarthritis NN I-NP O
DDD . O O
Microscopic NNP B-NP O
hematuria NN I-NP O
with IN B-PP O
negative JJ B-NP O
work NN I-NP O
up IN B-LST O
Obesity NN B-NP O
Medications NNS B-NP O
Amlodipine NNP B-NP O
5 CD I-NP O
mg NN I-NP O
qd NN I-NP O
Metoprolol NNP B-NP O
XL NNP I-NP O
50 CD I-NP O
mg NN I-NP O
qd NN I-NP O
Valsartan NNP B-NP O
HCTZ NNP I-NP O
160/25 CD I-NP O
mg NN I-NP O
Atorvastatin NNP B-NP O
20 CD I-NP O
mg NN I-NP O
Aspirin NNP B-NP O
81 CD I-NP O
mg NN I-NP O
qd NN I-NP O
Metformin NNP B-NP O
500 CD I-NP O
mg NN I-NP O
bid NN I-NP O
Health NNP B-NP O
maintenance NN I-NP O
overview NN I-NP O
Last JJ B-NP O
Pap NNP I-NP O
smear NN I-NP O
2085 CD I-NP B-DATE
normal JJ O O
Last JJ B-NP O
mammogram NN I-NP O
2086 CD O B-DATE
Last JJ B-NP O
densitometry NN I-NP O
2084 CD O B-DATE
Last JJ B-NP O
colonoscopy NN I-NP O
2084 CD I-NP B-DATE
normal JJ O O
Last JJ B-NP O
tonometry NN I-NP O
2083 CD O B-DATE
Last JJ B-NP O
audiogram NN I-NP O
unknown NN I-NP O
Last JJ B-NP O
skin NN I-NP O
exam VB B-VP O
unknown JJ O O
Last JJ B-NP O
CXR NNP I-NP O
2085 CD O B-DATE
Last JJ B-NP O
ECG NNP I-NP O
2085 CD O B-DATE
Last JJ B-NP O
ETT NNP I-NP O
2085 CD O B-DATE
Immunization NN B-NP O
Up IN B-PP O
to TO B-PP O
date NN B-NP O
AllergiesNone . O O
Social NNP B-NP O
historyPlace NN I-NP O
of IN B-PP O
birth NN B-NP O
Gambia NNP I-NP B-COUNTRY
Home NNP I-NP O
residence NN I-NP O
Jaffrey NNP I-NP B-CITY
, , O O
AL NNP B-NP B-STATE
Marital NNP I-NP O
status NN I-NP O
MarriedHousehold NNP I-NP O
members NNS I-NP O
FamilyOccupation NNP I-NP O
Carpentry NNP I-NP B-PROFESSION
Supervisor NNP I-NP I-PROFESSION
Support NNP I-NP O
resources NNS I-NP O
autonomous . O O
Risk NN B-NP O
factors NNS I-NP O
and CC O O
habitsTobacco NN B-NP O
smoking NN I-NP O
none NN I-NP O
Alcohol NN B-NP O
intake IN B-PP O
social JJ B-NP O
, , I-NP O
&lt JJ I-NP O
;3 CD I-NP O
drinks NNS I-NP O
per IN B-PP O
week NN B-NP O
Xantines NNS B-NP O
caffeine NN I-NP O
moderate JJ O O
Radiation NN B-NP O
exposure NN I-NP O
noneFumes NNS I-NP O
toxins NNS I-NP O
exposure NN I-NP O
none NN I-NP O
Hospitalizations NNS B-NP O
none NN I-NP O
in IN B-PP O
last JJ B-NP O
yearBlood NN I-NP O
transfusions NNS I-NP O
none NN I-NP O
Sun NNP B-NP O
exposure NN I-NP O
moderateSunscreen JJ I-NP O
use NN I-NP O
yes RB O O
Seat NNP B-NP O
belt NN I-NP O
use NN I-NP O
yes RB O O
Smoke NNP B-NP O
detector NN I-NP O
yesExercise RB B-ADJP O
moderate JJ I-ADJP O
Recreational JJ B-NP O
drugs NNS I-NP O
none NN O O
Injury NN B-NP O
risk NN I-NP O
low JJ B-ADJP O
to TO B-VP O
moderateSTD VB I-VP O
risk NN B-NP O
lowViolence NN I-NP O
and CC I-NP O
abuse NN I-NP O
not RB B-NP O
a DT I-NP O
current JJ I-NP O
issue NN I-NP O
Family NNP B-NP O
historyMother NN I-NP O
A DT B-NP O
dementia NN I-NP O
Father NNP B-NP O
A DT B-NP O
diabetes NN I-NP O
Brothers NNP B-NP O
0 CD I-NP O
Sisters NNP B-NP O
1 CD I-NP O
Spouse NN B-NP O
A DT O O
Children NNS B-NP O
2 CD O O
Cancer NNP B-NP O
0 CD I-NP O
Diabetes NNP B-NP O
+ NNP I-NP O
F NNP I-NP O
+ NN B-NP O
M NNP I-NP O
CV NNP B-NP O
Disease NNP I-NP O
0 CD O O
Stroke NNP B-NP O
0 CD I-NP O
Review NNP B-NP O
of IN B-PP O
systemsHand NN B-NP O
dexterity NN I-NP O
rightDenies NNS I-NP O
fever NN I-NP O
, , O O
nausea NN B-NP O
, , O O
vomiting VBG B-VP O
, , O O
diarrhea NN B-NP O
, , O O
chest NN B-NP O
pain NN I-NP O
, , O O
dyspnea NN B-NP O
, , O O
coughWeight NN B-NP O
changes NNS I-NP O
over IN B-PP O
last JJ B-NP O
year NN I-NP O
minimalSleep NN I-NP O
consolidatedSnoring VBG B-VP O
noneDiet RB B-NP O
omnivorous JJ I-NP O
Denies NNS B-NP O
other JJ I-NP O
significant JJ I-NP O
problems NNS I-NP O
with IN B-PP O
following VBG B-NP O
organs NNS I-NP O
or CC I-NP O
systems NNS I-NP O
: : O O
skin NN B-NP O
, , I-NP O
head NN I-NP O
, , I-NP O
eyes NNS I-NP O
, , I-NP O
nose NN I-NP O
, , I-NP O
throat NN I-NP O
, , I-NP O
neck NN I-NP O
, , I-NP O
endocrine NN I-NP O
, , I-NP O
breasts NNS I-NP O
, , I-NP O
heart NN I-NP O
, , I-NP O
lungs NNS I-NP O
, , I-NP O
gastrointestinal NN I-NP O
, , I-NP O
kidney NN I-NP O
, , I-NP O
urinary JJ I-NP O
, , I-NP O
genital JJ I-NP O
, , I-NP O
musculoskeletal NN I-NP O
, , I-NP O
neurologic NN I-NP O
, , I-NP O
blood NN I-NP O
, , I-NP O
lymphatic JJ I-NP O
. . O O
Denies NNS B-NP O
psychological JJ B-ADJP O
or CC I-ADJP O
psychiatric JJ I-ADJP O
problems NNS B-NP O
. . O O
Physical NNP B-NP O
Exam NNP I-NP O
56 CD B-NP B-AGE
yo NNP I-NP O
WDWN NNP I-NP O
person NN I-NP O
in IN B-PP O
NAD. NNP B-NP O
Habitus NNP B-NP O
meso-endomorphic JJ I-NP O
Weight NNP B-NP O
80 CD I-NP O
kgHeight JJ I-NP O
170 CD I-NP O
cmBMI NN I-NP O
27 CD O O
Vital JJ B-NP O
signs NNS I-NP O
: : O O
TF NN B-NP O
97.8BP NNP I-NP O
123/74HR CD I-NP O
66RR NN I-NP O
12 CD O O
Mental NNP B-NP O
statusAlert NN I-NP O
, , O O
oriented VBN B-VP O
x NN B-NP O
3.Cognition IN B-PP O
adequate JJ B-NP O
.SkinWarm NN I-NP O
, , O O
moist JJ B-ADVP O
, , O O
no DT B-NP O
cyanosis NN I-NP O
. . O O
Nails VBZ B-VP O
neat JJ B-NP O
, , I-NP O
hard JJ I-NP O
, , I-NP O
smooth JJ I-NP O
, , O O
no DT B-NP O
clubbing.LymphaticBilateral JJ I-NP O
submandibular JJ I-NP O
lymphadenopathy NN I-NP O
. . O O
No DT B-NP O
peripheral JJ I-NP O
edema. NN I-NP O
HeadEyes NNP I-NP O
- : O O
Conjunctiva NNP B-NP O
pink NN I-NP O
, , O O
no DT B-NP O
exudates NNS I-NP O
, , O O
cornea NN B-NP O
clear JJ I-NP O
, , O O
irides VBZ B-VP O
equal JJ B-NP O
ERL NNP I-NP O
, , O O
no DT B-NP O
nystagmus.Ears NNS I-NP O
- : O O
Tympanic JJ B-NP O
membranes NNS I-NP O
visible JJ B-ADJP O
, , O O
intact JJ B-NP O
, , I-NP O
light JJ I-NP O
reflection NN I-NP O
adequate JJ I-NP O
.Nose NN I-NP O
- : O O
Nasal JJ B-NP O
mucosa NN I-NP O
red NN I-NP O
, , O O
no DT B-NP O
edema NN I-NP O
, , O O
secretions.Thro NN B-NP O
- : O O
Posterior NNP B-NP O
pharyngeal NN I-NP O
wall NN I-NP O
red JJ I-NP O
, , O O
post NN B-NP O
nasal NN I-NP O
drip.Neck NN I-NP O
- : O O
Thyroid DT B-NP O
impression NN I-NP O
not RB B-ADJP O
visible JJ I-ADJP O
, , O O
trachea NN B-NP O
midline NN I-NP O
and CC O O
mobile JJ B-NP O
, , O O
no DT B-NP O
JVD.Chest NNP I-NP O
Symmetrical NNP I-NP O
expansion.Clear NN I-NP O
to TO B-PP O
auscultation NN B-NP O
bilaterally RB B-ADVP O
. . O O
Breasts NNS B-NP O
Deferred NNP I-NP O
. . O O
HeartRate NN B-NP O
and CC I-NP O
rhythm NN I-NP O
regular.Auscultation NN I-NP O
of IN B-PP O
five CD B-NP O
points NNS I-NP O
S1 NNP I-NP O
and CC I-NP O
S2 NNP I-NP O
, , O O
no DT B-NP O
murmurs NNS I-NP O
, , O O
no DT B-NP O
clicks VBZ B-VP O
/snaps RB B-NP O
.Vascular JJ I-NP O
Peripheral JJ I-NP O
pulses NNS I-NP O
symmetrical JJ I-NP O
. . O O
No DT B-NP O
aortic NN I-NP O
, , I-NP O
carotid NN I-NP O
or CC I-NP O
renal JJ I-NP O
bruits NNS I-NP O
.AbdomenSymmetric JJ B-ADJP O
, , O O
no DT B-NP O
protrusions.Palpation NN I-NP O
soft JJ I-NP O
, , I-NP O
non JJ I-NP O
tender NN I-NP O
, , O O
no DT B-NP O
rebound NN I-NP O
tenderness NN I-NP O
. . O O
No DT B-NP O
hepatosplenomegaly NN I-NP O
, , O O
no DT B-NP O
masses NNS I-NP O
. . O O
Percussion NN B-NP O
of IN B-PP O
costovertebral JJ B-NP O
angles NNS I-NP O
is VBZ B-VP O
non JJ B-NP O
tender NN I-NP O
. . O O
No DT B-NP O
arterial NN I-NP O
pulses VBZ B-VP O
transmitted VBN I-VP O
through IN B-PP O
abdominal JJ B-NP O
wall NN I-NP O
. . O O
Genitalia NNP B-NP O
female NN I-NP O
Deferred NNP B-NP O
. . O O
Anus NNP B-NP O
and CC I-NP O
rectum NN I-NP O
Deferred NNP B-NP O
. . O O
MusculoskeletalSpine NNP B-NP O
straight RB B-ADVP O
when WRB B-ADVP O
erect JJ I-ADVP O
, , O O
no DT B-NP O
rib NN I-NP O
hump NN I-NP O
on IN B-PP O
forward JJ B-NP O
flexion NN I-NP O
. . O O
Shoulders NNS B-VP O
at IN B-PP O
even RB B-NP O
levels NNS I-NP O
. . O O
Iliac NN B-NP O
crests VBZ B-VP O
at IN B-PP O
even RB B-NP O
levels NNS I-NP O
. . O O
Extremities NNS B-NP O
symmetrical JJ B-ADJP O
in IN B-PP O
appearance NN B-NP O
. . O O
Muscles NNPS O O
strength NN B-VP O
symmetrical JJ B-NP O
, , I-NP O
conserved JJ I-NP O
bilaterally RB B-ADVP O
. . O O
Joints VB B-VP O
non JJ B-NP O
tender NN I-NP O
, , O O
no DT B-NP O
locking VBG I-NP O
, , O O
no DT B-NP O
clicking NN I-NP O
, , O O
no DT B-NP O
limitations NNS I-NP O
, , O O
range NN B-NP O
of IN B-PP O
motion NN B-NP O
conserved VBN B-VP O
. . B-NP O
Neurologic NNP I-NP O
Cranial NNP I-NP O
nerves NNS I-NP O
II-XII CC O O
grossly RB B-ADJP O
intact JJ I-ADJP O
. . O O
Gait NNP B-NP O
coordinated VBD B-VP O
and CC O O
even RB B-ADVP O
. . B-VP O
Romberg JJ B-NP O
test NN I-NP O
negative JJ I-NP O
. . O O
Rapid NNP O O
alternating VBG B-VP O
movements NNS B-NP O
coordinated VBN B-VP O
. . B-NP O
Finger-nose NNP I-NP O
adequate JJ I-NP O
, , O O
no DT B-NP O
dysmetria NN I-NP O
, , O O
no DT B-NP O
ataxia NN I-NP O
. . O O
Epicritic NNP B-NP O
and CC O O
protopathic JJ B-NP O
sensations NNS I-NP O
intact JJ B-VP O
. . B-NP O
Deep JJ I-NP O
tendon NN I-NP O
reflexes VBZ B-VP O
symmetrical JJ B-NP O
2+ JJ I-NP O
in IN B-PP O
all DT B-NP O
extremities NNS I-NP O
. . O O
Babinski NNP B-NP O
sign NN I-NP O
absent JJ B-ADVP O
bilaterally RB B-ADVP O
. . O O
Ankle DT B-NP O
clonus NN I-NP O
absent JJ I-NP O
. . O O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
Chest NNP B-NP O
pressure NN I-NP O
and CC I-NP O
dyspnea NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
known VBN I-VP O
coronary JJ B-NP O
vasospastic JJ I-NP O
events NNS I-NP O
for IN B-PP O
which WDT B-NP O
she PRP B-NP O
has VBZ B-VP O
consulted VBN I-VP O
with IN B-PP O
cardiology NN B-NP O
. . O O
The DT B-NP O
symptoms NNS I-NP O
that IN B-SBAR O
she PRP B-NP O
describes VBZ B-VP O
suggest VB I-VP O
possible JJ B-NP O
symptomatic JJ I-NP O
cardiac NN I-NP O
ischemia NN I-NP O
. . O O
She PRP B-NP O
had VBD B-VP O
a DT B-NP O
baseline NN I-NP O
ECG NN I-NP O
today NN I-NP O
in IN B-PP O
my PRP$ B-NP O
office NN I-NP O
that WDT B-NP O
was VBD B-VP O
normal JJ B-ADJP O
. . O O
I PRP B-NP O
have VBP B-VP O
instructed VBN I-VP O
the DT B-NP O
patient NN I-NP O
to TO B-VP O
follow VB I-VP O
up RP B-PRT O
with IN B-NP O
cardiology NN I-NP O
for IN B-PP O
further JJR B-NP O
assessment NN I-NP O
and CC O O
an DT B-NP O
ETT. NNP I-NP O
I PRP B-NP O
will MD B-VP O
communicate VB I-VP O
with IN B-PP O
Dr. NNP B-NP O
Wright NNP I-NP B-DOCTOR
. . O O
The DT B-NP O
description NN I-NP O
of IN B-PP O
symptoms NNS B-NP O
do VBP B-VP O
not RB I-VP O
suggest VB I-VP O
unstable JJ B-NP O
angina NN I-NP O
. . O O
Glucose DT B-NP O
intolerance NN I-NP O
with IN B-PP O
post NN B-NP O
prandial JJ I-NP O
hyperglycemia NN I-NP O
. . O O
Continue NNP B-NP O
metformin NN I-NP O
, , O O
well RB B-VP O
tolerated VBN I-VP O
, , O O
HbA1c NNP B-NP O
requested VBD B-VP O
. . O O
Hyperlipidemia NNP B-NP O
. . B-VP O
On IN B-PP O
atorvastatin NN B-NP O
. . O O
Target VB B-VP O
LDL NNP B-NP O
&lt NNP I-NP O
;70 CD I-NP O
, , O O
new JJ B-NP O
values NNS I-NP O
requested VBD B-VP O
. . O O
Hypertension NNP B-NP O
. . I-NP O
Stable NNP I-NP O
, , O O
continue VBP B-VP O
current JJ B-NP O
medications NNS I-NP O
. . O O
Microscopic NNP B-NP O
hematuria NN I-NP O
with IN B-PP O
negative JJ B-NP O
work NN I-NP O
up IN B-PP O
. . B-NP O
Surveillance NNP I-NP O
UA NNP I-NP O
and CC I-NP O
cytology NN I-NP O
requested VBD B-VP O
. . O O
Rhinopharyngitis NNP B-NP O
. . I-NP O
Amoxicillin NNP I-NP O
and CC O O
fluticasone NN B-NP O
initiated VBN B-VP O
. . O O
Gynecology NNP B-NP O
contact NN I-NP O
information NN I-NP O
provided VBN B-VP O
. . O O
Ophthalmology NNP B-NP O
contact NN I-NP O
information NN I-NP O
provided VBN B-VP O
. . O O
Bone NNP B-NP O
densitometry NN I-NP O
requested VBD B-VP O
. . O O
Labs NNP B-NP O
requested VBD B-VP O
. . O O
Follow VB B-VP O
up RP B-PRT O
after IN B-NP O
tests NNS I-NP O
or CC O O
in IN B-PP O
3-6 CD B-NP O
months NNS I-NP O
. . O O
David NNP B-NP B-DOCTOR
Delgado NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
