Record NNP B-NP O
date NN I-NP O
: : O O
2082-01-22 CD O B-DATE
Infectious JJ B-NP O
Disease NNP I-NP O
Fellow NNP I-NP O
Consult NNP I-NP O
Note NN I-NP O
Patient NNP B-NP O
Name NNP I-NP O
: : O O
Yerger NN B-NP I-PATIENT
, , O I-PATIENT
Urania NNP B-NP I-PATIENT
MRN NNP B-NP O
: : O O
58348900 CD O B-MEDICALRECORD
Location NN B-NP O
: : O O
47N CD O O
Admit NNP B-NP O
Date NNP I-NP O
: : O O
1/21/8 CD B-NP I-DATE
2 CD I-NP I-DATE
Consult NNP B-NP O
Date NNP I-NP O
: : O O
1/22/8 CD B-NP I-DATE
2 CD I-NP I-DATE
HPI NNP B-NP O
: : O O
Ms. NNP B-NP O
Yerger NNP I-NP B-PATIENT
is VBZ B-VP O
an DT B-NP O
84 CD I-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
with IN B-PP O
CAD NNP B-NP O
, , O O
DM NNP B-NP O
, , O O
CHF NNP B-NP O
, , O O
Htn NNP B-NP O
, , O O
HL NNP B-NP O
, , O O
and CC O O
right JJ B-NP O
ankle NN I-NP O
fracture JJ I-NP O
s/p NN I-NP O
ORIF IN B-PP O
on IN B-NP O
11/04/8 CD I-NP I-DATE
1 CD I-NP I-DATE
who WP B-NP O
presents VBZ B-VP O
with IN B-PP O
poor JJ B-NP O
healing NN I-NP O
over IN B-PP O
the DT B-NP O
medial JJ I-NP O
malleolus NN I-NP O
; : O O
we PRP B-NP O
were VBD B-VP O
consulted VBN I-VP O
by IN B-PP O
Dr. NNP B-NP O
Felton NNP I-NP B-DOCTOR
for IN B-PP O
recommendations NNS B-NP O
on IN B-PP O
antibiotic JJ B-NP O
management NN I-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
initially RB I-VP O
seen VBN I-VP O
on IN B-PP O
11/01/8 CD B-NP I-DATE
1 CD I-NP I-DATE
after IN B-PP O
a DT B-NP O
mechanical JJ I-NP O
fall NN I-NP O
which WDT B-NP O
resulted VBD B-VP O
in IN B-PP O
comminuted JJ B-NP O
bimalleolar JJ I-NP O
ankle NN I-NP O
fracture NN I-NP O
for IN B-PP O
which WDT B-NP O
she PRP B-NP O
underwent VBD B-VP O
ORIF NNP B-NP O
on IN B-PP O
11/04/8 CD B-NP I-DATE
1 CD I-NP I-DATE
. . O O
She PRP B-NP O
had VBD B-VP O
follow-up JJ B-ADJP O
with IN B-PP O
her PRP$ B-NP O
orthopaedist NN I-NP O
on IN B-PP O
1/15/8 CD B-NP I-DATE
1 CD I-NP I-DATE
at IN B-PP O
which WDT B-NP O
time NN I-NP O
she PRP B-NP O
was VBD B-VP O
noted VBN I-VP O
to TO I-VP O
have VB I-VP O
an DT B-NP O
eschar NN I-NP O
with IN B-PP O
poor JJ B-NP O
wound NN I-NP O
healing VBG B-VP O
around IN B-PP O
the DT B-NP O
medial JJ I-NP O
malleolus NN I-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
therefore RB I-VP O
admitted VBN I-VP O
yesterday NN B-NP O
for IN B-PP O
I&D NNP B-NP O
of IN B-PP O
the DT B-NP O
open JJ I-NP O
lesion NN I-NP O
on IN B-PP O
her PRP B-NP O
ankle NN B-NP O
, , O O
as RB B-CONJP O
well RB I-CONJP O
as IN I-CONJP O
hardware NN B-NP O
removal NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
operative JJ I-NP O
report NN I-NP O
from IN B-PP O
the DT B-NP O
procedure NN I-NP O
. . O O
Reportedly RB O O
there EX B-NP O
was VBD B-VP O
non-union NN B-NP O
of IN B-PP O
the DT B-NP O
fracture NN I-NP O
, , O O
so RB B-ADVP O
hardware NN B-NP O
was VBD B-VP O
removed VBN I-VP O
. . O O
Tissue NNP B-NP O
appeared VBD B-VP O
fairly RB B-ADJP O
healthy JJ I-ADJP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
having VBG I-VP O
any DT B-NP O
recent JJ I-NP O
fevers NNS I-NP O
, , O O
chills NNS B-NP O
, , O O
night NN B-NP O
sweats VBZ B-VP O
, , O O
or CC O O
particular JJ B-NP O
pain NN I-NP O
in IN B-PP O
the DT B-NP O
ankle NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
doing VBG I-VP O
some DT B-NP O
weight NN I-NP O
bearing VBG B-VP O
with IN B-PP O
use NN B-NP O
of IN B-PP O
a DT B-NP O
walker NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
some DT B-NP O
mild JJ I-NP O
serous JJ I-NP O
drainage NN I-NP O
from IN B-PP O
the DT B-NP O
ankle NN I-NP O
, , O O
but CC O O
no DT B-NP O
purulent JJ I-NP O
drainage NN I-NP O
. . O O
ROS NNP B-NP O
: : O O
See VB B-VP O
HPI PRP B-NP O
for IN B-PP O
positives NNS B-NP O
. . O O
ROS NNP O O
otherwise RB B-ADJP O
negative JJ I-ADJP O
in IN B-PP O
detail NN B-NP O
. . O O
PMH: . O O
1 LS O O
. . B-NP O
CAD NNP I-NP O
: : O O
s/p JJ B-NP O
NSTEMI NNP I-NP O
in IN B-PP O
2078 CD B-NP B-DATE
, , O O
followed VBN B-VP O
by IN B-PP O
CABG NNP B-NP O
( -LRB- I-NP O
SVG NNP I-NP O
to TO B-PP O
ramus NNP B-NP O
, , O O
OM2 NNP B-NP O
, , O O
RCA NNP B-NP O
, , O O
and CC O O
LIMA NNP B-NP O
to TO B-PP O
LAD NNP B-NP O
) -RRB- O O
2. DT B-NP O
CHF NNP I-NP O
: : O O
diastolic JJ B-NP O
dysfunction NN I-NP O
, , O O
EF RB B-ADVP O
60 CD B-NP O
% NN I-NP O
with IN B-PP O
mod JJ B-NP O
MR/TR NNP I-NP O
, , O O
flash NN B-NP O
pulm NN I-NP O
edema NN I-NP O
in IN B-PP O
setting NN B-NP O
of IN B-PP O
coronary JJ B-NP O
ischemia NN I-NP O
3. DT B-NP O
DM NNP I-NP O
for IN B-PP O
10-15yrs CD B-NP O
4 CD B-LST O
. . O O
HTN '' O O
5 CD B-NP O
. . O O
Hyperlipidemia NNP O O
6 CD B-NP O
. . O O
Osteoporosis NNP O O
7. CD B-NP O
R NN I-NP O
TKR NN I-NP O
Medications NNS B-NP O
: : O O
1 LS O O
. . B-NP O
Vancomycin NNP I-NP O
1gm . I-NP O
IV NNP I-NP O
q24h . O O
2. DT B-NP O
Also RB I-NP O
on IN B-PP O
lovenox NN B-NP O
, , I-NP O
simvastatin NN I-NP O
, , I-NP O
amlodipine NN I-NP O
, , I-NP O
toprol NN I-NP O
xl NN I-NP O
, , O O
losartan NN B-NP O
, , O O
lasix NN B-NP O
, , O O
glipizide NN B-NP O
, , O O
colace NN B-NP O
, , O O
aspirin NN B-NP O
, , O O
morphine NN B-NP O
, , O O
MOM NNP B-NP O
, , O O
maalox NN B-NP O
Home NNP B-NP O
medications NNS I-NP O
: : O O
ECASA NNP B-NP O
325 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
Lasix NNP B-NP O
60 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
Toprol-XL JJ B-NP O
50 CD I-NP O
mg JJ I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
Losartan NNP B-NP O
100 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
Simvastatin NNP B-NP O
10 CD I-NP O
mg JJ I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
Glipizide NNP B-NP O
10 CD I-NP O
mg JJ I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
Avandia NNP B-NP O
4mg CD I-NP O
p.o NN I-NP O
. . O O
daily RB O O
Norvasc NNP B-NP O
5mg CD I-NP O
po NN I-NP O
qod NN I-NP O
Fosamax NNP B-NP O
70mg CD I-NP O
po NN I-NP O
qweek NN I-NP O
Multivitamin NN B-NP O
Allergies NNP B-NP O
: : O O
Ciprofloxacin NNP B-NP O
causes VBZ B-VP O
unknown JJ B-NP O
reaction NN I-NP O
. . O O
Metformin NNP B-NP O
causes VBZ B-VP O
GI JJ B-NP O
intolerance NN I-NP O
. . O O
Tylenol NNP B-NP O
causes VBZ B-VP O
reaction NN B-NP O
. . O O
SHx NNP B-NP O
: : O O
Lives NNS B-NP O
alone RB B-ADVP O
in IN B-PP O
Cohasset NNP B-NP B-CITY
, , O O
but CC O O
with IN B-PP O
5 CD B-NP O
supporting JJ I-NP O
daughters NNS I-NP O
nearby RB B-ADVP O
. . O O
No DT B-NP O
tob NN I-NP O
, , O O
EtOH. . O O
PE NN B-NP O
: : O O
Gen NNP B-NP O
: : O O
pleasant JJ B-NP O
, , I-NP O
elderly JJ I-NP O
, , O O
well RB B-VP O
appearing VBG I-VP O
lady NN B-NP O
, , O O
in IN B-PP O
NAD NNP B-NP O
VS NNP B-NP O
: : O O
Tmax NNP B-NP O
:97.8 CD I-NP O
Tc:97.8 CD I-NP O
BP NNP I-NP O
142/64 CD I-NP O
P NNP I-NP O
81 CD I-NP O
R NN I-NP O
18 CD I-NP O
94 CD I-NP O
% NN I-NP O
on IN B-PP O
RA NNP B-NP O
HEENT NNP B-NP O
: : O O
PERRL NN B-NP O
, , O O
EOMI NNP B-NP O
, , O O
OP NNP B-NP O
without IN B-PP O
lesions NNS B-NP O
, , O O
+ NNS B-NP O
dentures NNS I-NP O
Neck NNP B-NP O
: : O O
supple NN B-NP O
, , O O
no DT B-NP O
cervical JJ I-NP O
LAN NN I-NP O
Pulm NNP B-NP O
: : O O
CTA NNP B-NP O
bilaterally RB B-ADVP O
, , O O
no DT B-NP O
rales/wheezes NNS I-NP O
CV NNP B-NP O
: : O O
RRR NNP B-NP O
, , O O
II/V NNP B-NP O
I PRP B-NP O
HSM RB B-ADVP O
at IN B-PP O
LSB NNP B-NP O
, , O O
normal JJ B-NP O
S1/S2 NN I-NP O
, , O O
well RB B-VP O
healed VBN I-VP O
sternotomy NN B-NP O
incision NN I-NP O
Abd NNP B-NP O
: : B-VP O
soft JJ B-ADJP O
, , O O
NT NNP B-NP O
, , O O
ND NNP B-NP O
, , O O
NABS NNP B-NP O
, , O O
no DT B-NP O
HSM NNP I-NP O
Ext JJ B-NP O
: : O O
no DT B-NP O
c/c/e NN I-NP O
, , O O
W&WP NNP B-NP O
, , O O
right JJ B-NP O
foot NN I-NP O
in IN B-PP O
cast NN B-NP O
, , O O
toes NNS B-NP O
with IN B-PP O
good JJ B-NP O
perfusion NN I-NP O
, , O O
drain VB B-VP O
in IN B-PP O
place NN B-NP O
with IN B-PP O
serosanguenous JJ B-NP O
drainage NN I-NP O
Skin NNP B-NP O
: : O O
no DT B-NP O
rash NN I-NP O
Labs NNS B-NP O
: : O O
WBC NNP B-NP O
10.9 CD I-NP O
, , O O
Hct NNP B-NP O
30 CD I-NP O
, , O O
Plt NNP B-NP O
383 CD I-NP O
, , O O
Diff NNP B-NP O
: : O O
not RB B-NP O
done VBN I-NP O
BUN/Cr NNP B-NP O
: : O O
36 CD B-NP O
/ NN I-NP O
1.3 CD B-NP O
( -LRB- I-NP O
on IN B-PP O
1/19/8 CD B-NP I-DATE
2 CD I-NP I-DATE
) -RRB- O O
LFTs NNP B-NP O
: : B-VP O
not RB I-VP O
done VBN I-VP O
INR NNP B-NP O
1.1 CD I-NP O
, , O O
PTT NNP B-NP O
29 CD I-NP O
ESR JJ B-NP O
92 CD I-NP O
( -LRB- I-NP O
1/22/8 CD I-NP I-DATE
2 CD I-NP I-DATE
) -RRB- O O
Micro NNP B-NP O
: : O O
Right RB B-ADVP O
ankle NN B-VP O
culture NN B-NP O
( -LRB- I-NP O
1/21/8 CD I-NP I-DATE
2 CD I-NP I-DATE
) -RRB- I-NP O
: : O O
FEW JJ B-NP O
SUSPECTED NNP I-NP O
STAPHYLOCOCCUS NNP I-NP O
AUREUS NNP I-NP O
( -LRB- I-NP O
gm NN I-NP O
stain-no NN I-NP O
polys NNS I-NP O
, , O O
no DT B-NP O
org NN I-NP O
) -RRB- O O
Radiology NNP B-NP O
: : O O
Right RB B-ADVP O
ankle NN B-NP O
xrays VBZ B-VP O
pending VBG I-VP O
( -LRB- B-NP O
1/21/8 FW I-NP I-DATE
2 CD I-NP I-DATE
) -RRB- O O
Impression/Recommendations NNS B-NP O
: : O O
84 CD B-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
with IN B-PP O
CAD NNP B-NP O
, , O O
DM NNP B-NP O
, , O O
CHF NNP B-NP O
, , O O
Htn NNP B-NP O
, , O O
HL NNP B-NP O
, , O O
and CC O O
right JJ B-NP O
ankle NN I-NP O
fracture JJ I-NP O
s/p NN I-NP O
ORIF IN B-PP O
on IN B-NP O
11/04/8 CD I-NP I-DATE
1 CD I-NP I-DATE
who WP B-NP O
presents VBZ B-VP O
with IN B-PP O
poor JJ B-NP O
healing NN I-NP O
over IN B-PP O
the DT B-NP O
medial JJ I-NP O
malleolus NN I-NP O
, , O O
now RB B-ADVP O
s/p JJ B-NP O
I&D NN I-NP O
of IN B-PP O
the DT B-NP O
open JJ I-NP O
medial JJ I-NP O
malleolus NN I-NP O
wound NN I-NP O
; : O O
we PRP B-NP O
were VBD B-VP O
consulted VBN I-VP O
by IN B-PP O
Dr. NNP B-NP O
Felton NNP I-NP B-DOCTOR
for IN B-PP O
recommendations NNS B-NP O
on IN B-PP O
antibiotic JJ B-NP O
management NN I-NP O
. . O O
The DT B-NP O
extent NN I-NP O
of IN B-PP O
infection NN B-NP O
is VBZ B-VP O
a DT B-NP O
surgical JJ I-NP O
diagnosis NN I-NP O
. . O O
If IN B-SBAR O
the DT B-NP O
swabs NNS I-NP O
were VBD B-VP O
obtained VBN I-VP O
from IN B-PP O
the DT B-NP O
superficial JJ I-NP O
wound NN I-NP O
, , O O
then RB B-ADVP O
this DT B-NP O
may MD B-VP O
represent VB I-VP O
merely RB B-NP O
a DT I-NP O
wound NN I-NP O
infection NN I-NP O
which WDT B-NP O
requires VBZ B-VP O
2 CD B-NP O
weeks NNS I-NP O
of IN B-PP O
antibiotics NNS B-NP O
. . O O
However RB B-ADVP O
if IN B-SBAR O
the DT B-NP O
infection NN I-NP O
was VBD B-VP O
felt VBN I-VP O
on IN B-PP O
surgical JJ B-NP O
inspection NN I-NP O
to TO B-VP O
extend VB I-VP O
to TO B-PP O
the DT B-NP O
region NN I-NP O
of IN B-PP O
the DT B-NP O
removed VBN I-NP O
hardware NN I-NP O
, , O O
then RB B-ADVP O
this DT B-NP O
represents VBZ B-VP O
osteomyelitis NN B-NP O
by IN B-PP O
definition NN B-NP O
, , O O
and CC O O
she PRP B-NP O
will MD B-VP O
need VB I-VP O
6 CD B-NP O
weeks NNS I-NP O
of IN B-PP O
IV NNP B-NP O
antibiotics NNS I-NP O
with IN B-PP O
consideration NN B-NP O
of IN B-PP O
the DT B-NP O
removal NN I-NP O
of IN B-PP O
the DT B-NP O
remaining VBG I-NP O
hardware NN I-NP O
. . O O
After IN B-PP O
discussion NN B-NP O
with IN B-PP O
the DT B-NP O
ortho NN I-NP O
resident NN I-NP O
, , O O
it PRP B-NP O
seems VBZ B-VP O
that IN B-SBAR O
the DT B-NP O
culture NN I-NP O
was VBD B-VP O
obtained VBN I-VP O
from IN B-PP O
the DT B-NP O
site NN I-NP O
of IN B-PP O
screw NN B-NP O
removal NN I-NP O
. . O O
Thus RB B-ADVP O
, , O O
we PRP B-NP O
have VBP B-VP O
to TO I-VP O
assume VB I-VP O
hardware NN B-NP O
infection NN I-NP O
with IN B-PP O
concomitant JJ B-NP O
osteomyelitis NN I-NP O
. . O O
Thus RB B-ADVP O
6 CD B-NP O
weeks NNS I-NP O
of IN B-PP O
IV NNP B-NP O
antibiotics NNS I-NP O
is VBZ B-VP O
necessary JJ B-ADJP O
. . O O
We PRP B-NP O
cannot MD B-VP O
rule VB I-VP O
out RP B-NP O
infection NN I-NP O
of IN B-PP O
the DT B-NP O
remaining VBG I-NP O
hardware NN I-NP O
, , O O
however RB B-ADVP O
I PRP B-NP O
understand VBP B-VP O
the DT B-NP O
reluctance NN I-NP O
to TO B-VP O
remove VB I-VP O
the DT B-NP O
remainder NN I-NP O
of IN B-PP O
the DT B-NP O
hardware NN I-NP O
by IN B-PP O
the DT B-NP O
ortho NN I-NP O
service NN I-NP O
. . O O
Thus RB B-ADVP O
would MD B-VP O
pursue VB I-VP O
6 CD B-NP O
week NN I-NP O
course NN I-NP O
of IN B-PP O
therapy NN B-NP O
, , O O
then RB B-ADVP O
monitor VB B-VP O
closely RB B-ADVP O
for IN B-PP O
signs NNS B-NP O
of IN B-PP O
failure NN B-NP O
. . O O
1 LS B-NP O
. . O O
Continue VB B-VP O
vancomycin RB B-ADVP O
until IN B-PP O
susceptibilities NNS B-NP O
are VBP B-VP O
available JJ B-ADJP O
; : O O
will MD B-VP O
determine VB I-VP O
whether IN B-SBAR O
the DT B-NP O
addition NN I-NP O
of IN B-PP O
rifampin NN B-NP O
in IN B-PP O
necessary JJ B-NP O
given VBN I-NP O
retained VBN I-NP O
hardware NN I-NP O
based VBN B-PP O
on IN B-PP O
susceptibility NN B-NP O
results NNS I-NP O
2. `` O O
Please VB B-VP O
obtain VB I-VP O
vanc NN B-NP O
trough NN I-NP O
prior RB B-ADVP O
to TO B-VP O
3rd VB I-VP O
dose NN B-NP O
3. `` O O
Please VB B-VP O
obtain VB I-VP O
LFTs JJ O O
Patient NNP B-NP O
seen VBN B-VP O
and CC I-VP O
examined VBN I-VP O
with IN B-PP O
ID NNP B-NP O
Attending NNP I-NP O
, , O O
Dr. NNP B-NP O
Ulysses NNP I-NP B-DOCTOR
Xayasane NNP I-NP I-DOCTOR
. . O O
We PRP B-NP O
will MD B-VP O
continue VB I-VP O
to TO I-VP O
follow VB I-VP O
along RP B-PRT O
with IN B-PP O
you PRP B-NP O
. . O O
Thank VB B-VP O
you PRP B-NP O
for IN B-PP O
the DT B-NP O
consult VB I-NP O
. . O O
Rosa NNP B-NP B-DOCTOR
Molina NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Infectious JJ B-NP O
Disease NNP I-NP O
Fellow NNP I-NP O
Pager NNP B-NP O
12906 CD I-NP B-PHONE
