Record NNP B-NP O
date NN I-NP O
: : O O
2072-07-06 CD O B-DATE
JOSHI NNP B-NP I-PATIENT
, , O I-PATIENT
KATHY . O I-PATIENT
15842112 CD O B-MEDICALRECORD
07/06/2072 CD O B-DATE
Benjamin NNP B-NP B-DOCTOR
W. NNP I-NP I-DOCTOR
Taylor NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Illini NNP B-NP B-HOSPITAL
Community NNP I-NP I-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
66 CD B-NP B-STREET
Cardinal NNP I-NP I-STREET
Circle NNP I-NP I-STREET
Three CD B-NP B-CITY
Rivers NNS I-NP I-CITY
, , O O
NM NNP B-NP B-STATE
11424 CD I-NP B-ZIP
Dear NNP B-NP O
Dr. NNP I-NP O
Taylor NNP I-NP B-DOCTOR
: : O O
Mrs. NNP B-NP O
Joshi NNP I-NP B-PATIENT
returns VBZ B-VP O
to TO B-PP O
the DT B-NP O
office NN I-NP O
for IN B-PP O
routine JJ B-NP O
followup NN I-NP O
. . O O
Since IN O O
last JJ B-NP O
seen VBN I-NP O
, , O O
she PRP B-NP O
apparently RB B-ADVP O
was VBD B-VP O
without IN B-PP O
evidence NN B-NP O
of IN B-PP O
increasing VBG B-VP O
BUN NNP B-NP O
and CC O O
creatinine VB B-VP O
and CC I-VP O
for IN B-PP O
this DT B-NP O
reason NN I-NP O
was VBD B-VP O
advised VBN I-VP O
to TO I-VP O
transiently VB I-VP O
hold VB I-VP O
both DT B-NP O
her PRP$ I-NP O
lisinopril NN I-NP O
and CC I-NP O
Zaroxolyn NNP I-NP O
. . O O
By IN B-PP O
doing VBG B-VP O
so RB B-ADVP O
, , O O
her PRP$ B-NP O
creatinine NN I-NP O
fell VBD B-VP O
from IN B-PP O
2.2 CD B-NP O
to TO B-PP O
1.6 CD B-NP O
and CC O O
BUN NNP B-NP O
from IN B-PP O
117 CD B-NP O
to TO B-PP O
57 CD B-NP O
. . O O
She PRP B-NP O
subsequently RB B-ADVP O
has VBZ B-VP O
resumed VBN I-VP O
her PRP$ B-NP O
lisinopril JJ I-NP O
therapy NN I-NP O
, , O O
as IN B-PP O
apparently RB B-NP O
her PRP$ I-NP O
blood NN I-NP O
pressure NN I-NP O
increased VBN B-VP O
off IN B-PP O
her PRP$ B-NP O
ACE NNP I-NP O
inhibitor NN I-NP O
. . O O
In IN B-PP O
addition NN B-NP O
, , O O
as IN B-PP O
part NN B-NP O
of IN B-PP O
her PRP$ B-NP O
followup NN I-NP O
last JJ B-NP O
March NNP I-NP B-DATE
, , O O
she PRP B-NP O
underwent VBD B-VP O
an DT B-NP O
adenosine NN I-NP O
MIBI JJ I-NP O
stress NN I-NP O
test NN I-NP O
during IN B-PP O
which WDT B-NP O
time NN B-NP O
she PRP B-NP O
achieved VBD B-VP O
a DT B-NP O
peak JJ I-NP O
heart NN I-NP O
rate NN I-NP O
of IN B-PP O
65 CD B-NP O
, , O O
peak JJ B-NP O
blood NN I-NP O
pressure NN I-NP O
of IN B-PP O
129/50 CD B-NP O
, , O O
stopping VBG B-VP O
because IN B-SBAR O
she PRP B-NP O
reached VBD B-VP O
the DT B-NP O
end NN I-NP O
of IN B-PP O
the DT B-NP O
adenosine NN I-NP O
infusion NN I-NP O
protocol NN I-NP O
. . O O
Her PRP$ B-VP O
gated VBN I-VP O
SPECT NNP B-NP O
imaging NN I-NP O
demonstrated VBD B-VP O
a DT B-NP O
global JJ I-NP O
left NN I-NP O
ventricular NN I-NP O
ejection NN I-NP O
fraction NN I-NP O
of IN B-PP O
38 CD B-NP O
% NN I-NP O
with IN B-PP O
a DT B-NP O
mildly RB I-NP O
dilated VBN I-NP O
left VBN I-NP O
ventricle NN I-NP O
and CC I-NP O
akinesis NN I-NP O
of IN B-PP O
the DT B-NP O
basal NN I-NP O
inferoseptal NN I-NP O
and CC O O
entire JJ B-NP O
inferior JJ I-NP O
wall NN I-NP O
. . B-PP O
Her PRP$ B-NP O
rest-stress NN I-NP O
perfusion NN I-NP O
imaging VBG B-VP O
showed VBD I-VP O
similarly RB B-NP O
a DT I-NP O
large JJ I-NP O
fixed JJ I-NP O
perfusion NN I-NP O
defect NN I-NP O
in IN B-PP O
the DT B-NP O
inferior JJ I-NP O
and CC I-NP O
basal JJ I-NP O
inferoseptal JJ I-NP O
wall NN I-NP O
without IN B-PP O
any DT B-NP O
area NN I-NP O
of IN B-PP O
reversible JJ B-NP O
ischemia NN I-NP O
. . O O
Her PRP$ B-NP O
last JJ I-NP O
echocardiogram NN I-NP O
performed VBN B-VP O
in IN B-PP O
July NNP B-NP B-DATE
2071 CD I-NP I-DATE
showed VBD B-VP O
a DT B-NP O
residual NN I-NP O
of IN B-PP O
left JJ B-NP O
ventricular JJ I-NP O
ejection NN I-NP O
fraction NN I-NP O
mildly RB B-ADVP O
reduced VBN B-VP O
at IN B-PP O
45 CD B-NP O
% NN I-NP O
with IN B-PP O
severe JJ B-NP O
inferoseptal NN I-NP O
and CC O O
inferior JJ B-NP O
hypokinesis NN I-NP O
. . O O
In IN B-PP O
addition NN B-NP O
, , O O
at IN B-PP O
that DT B-NP O
time NN I-NP O
showed VBD B-VP O
evidence NN B-NP O
for IN B-PP O
trivial JJ B-NP O
mitral NN I-NP O
and CC O O
tricuspid JJ B-NP O
regurgitation NN I-NP O
and CC O O
her PRP$ B-NP O
echo NN I-NP O
was VBD B-VP O
essentially RB B-ADJP O
unchanged JJ I-ADJP O
from IN B-PP O
her PRP$ B-NP O
prior JJ I-NP O
study NN I-NP O
in IN B-PP O
March NNP B-NP B-DATE
2071 CD I-NP I-DATE
. . O O
Currently RB B-ADVP O
, , O O
she PRP B-NP O
is VBZ B-VP O
concerned VBN I-VP O
primarily RB B-ADVP O
about IN B-PP O
her PRP$ B-NP O
inability NN I-NP O
to TO B-VP O
lose VB I-VP O
weight NN B-NP O
, , O O
and CC O O
in IN B-PP O
fact NN B-NP O
states NNS I-NP O
that WDT B-NP O
during IN B-PP O
a DT B-NP O
recent JJ I-NP O
vacation NN I-NP O
she PRP B-NP O
actually RB B-ADVP O
discontinued VBN B-VP O
her PRP$ B-NP O
diet NN I-NP O
. . O O
Presently RB B-ADVP O
, , O O
she PRP B-NP O
continues VBZ B-VP O
on IN B-PP O
a DT B-NP O
regimen NN I-NP O
of IN B-PP O
Toprol-XL NNP B-NP O
37.5 CD I-NP O
mg JJ I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
simvastatin VBG B-VP O
80 CD B-NP O
mg JJ I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
lisinopril IN B-PP O
5 CD B-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
potassium NN B-NP O
chloride NN I-NP O
20 CD I-NP O
mEq NN I-NP O
p.o NN I-NP O
. . O O
b.i.d. '' O O
, , O O
furosemide RB B-ADVP O
160 CD B-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
b.i.d. '' O O
, , O O
Coumadin NNP B-NP O
, , O O
enteric-coated JJ B-NP O
aspirin NN I-NP O
81 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
, , O O
Niferex NNP B-NP O
150 CD I-NP O
mg NN I-NP O
p.o RB B-ADVP O
. . O O
daily JJ B-ADVP O
, , O O
Humulin NNP B-NP O
N NNP I-NP O
20 CD I-NP O
units NNS I-NP O
subcutaneous JJ B-NP O
q.a.m NNP I-NP O
. . O O
and CC O O
Humulin NNP B-NP O
N NNP I-NP O
20 CD I-NP O
units NNS I-NP O
subcutaneous JJ B-NP O
q.p.m NNP I-NP O
. . O O
Physical JJ B-NP O
exam NN I-NP O
reveals VBZ B-VP O
a DT B-NP O
pleasant JJ I-NP O
, , I-NP O
mildly RB I-NP O
overweight JJ I-NP O
woman NN I-NP O
in IN B-PP O
no DT B-NP O
acute JJ I-NP O
distress NN I-NP O
. . O O
Blood NN B-NP O
pressure NN I-NP O
right JJ I-NP O
arm NN I-NP O
sitting VBG B-VP O
120/52 CD B-NP O
, , O O
heart NN B-NP O
rate NN I-NP O
45 CD B-NP O
and CC I-NP O
irregularly RB I-NP O
regular JJ I-NP O
, , I-NP O
respirations NNS I-NP O
14 CD I-NP O
and CC O O
unlabored JJ B-ADVP O
, , O O
and CC O O
weight NN B-NP O
253 CD I-NP O
pounds NNS I-NP O
, , O O
which WDT B-NP O
is VBZ B-VP O
12 CD B-NP O
pounds NNS I-NP O
above IN B-PP O
her PRP$ B-NP O
weight NN I-NP O
of IN B-PP O
six CD B-NP O
months NNS I-NP O
ago RB B-ADVP O
. . O O
The DT B-NP O
neck NN I-NP O
is VBZ B-VP O
supple NN B-NP O
. . O O
JVP NNP B-NP O
is VBZ B-VP O
flat JJ B-ADJP O
. . O O
Carotids NNPS O O
are VBP B-VP O
without IN B-PP O
significant JJ B-NP O
bruits NNS I-NP O
. . O O
Chest NNP B-NP O
remains VBZ B-VP O
clear JJ B-ADJP O
. . O O
Cardiac NNP B-NP O
exam NN I-NP O
shows VBZ B-VP O
normal JJ B-NP O
S1 NNP I-NP O
, , O O
physiologically RB B-VP O
split VBN I-VP O
S2 NN B-NP O
with IN B-PP O
a DT B-NP O
soft JJ I-NP O
systolic JJ I-NP O
ejection NN I-NP O
murmur NN I-NP O
radiating NN I-NP O
from IN B-PP O
the DT B-NP O
apex NN I-NP O
to TO B-PP O
the DT B-NP O
base NN I-NP O
. . O O
No DT B-NP O
significant JJ I-NP O
diastolic JJ I-NP O
murmur NN I-NP O
or CC I-NP O
rub NN I-NP O
. . O O
The DT B-NP O
abdomen NN I-NP O
is VBZ B-VP O
overweight JJ B-ADJP O
, , O O
but CC O O
otherwise RB B-NP O
benign JJ I-NP O
without IN B-PP O
evidence NN B-NP O
of IN B-PP O
abdominal JJ B-NP O
aneurysm NN I-NP O
or CC I-NP O
bruit NN I-NP O
. . O O
Extremities NNS B-NP O
reveal VBP B-VP O
trace NN B-NP O
bipedal NN I-NP O
edema NN I-NP O
. . O O
Peripheral JJ B-NP O
pulses NNS I-NP O
are VBP B-VP O
detectable JJ B-ADJP O
, , O O
albeit IN B-SBAR O
mildly RB B-ADVP O
diminished VBN B-VP O
. . O O
Electrocardiogram NNP B-NP O
shows VBZ B-VP O
atrial JJ B-NP O
fibrillation NN I-NP O
flutter NN I-NP O
with IN B-PP O
at IN B-PP O
times NNS B-NP O
of IN B-PP O
significant JJ B-NP O
AV NN I-NP O
block NN I-NP O
with IN B-PP O
pauses NNS B-NP O
as RB B-ADJP O
high JJ I-ADJP O
as IN B-PP O
approximately RB B-NP O
2 CD I-NP O
seconds NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
evidence NN B-NP O
of IN B-PP O
a DT B-NP O
prior JJ I-NP O
inferior JJ I-NP O
myocardial JJ I-NP O
infarction NN I-NP O
and CC O O
minor JJ B-NP O
nonspecific JJ I-NP O
ST NNS I-NP O
and CC O O
T-wave JJ B-NP O
changes NNS I-NP O
. . O O
Compared VBN B-VP O
with IN B-PP O
her PRP$ B-NP O
last JJ I-NP O
electrocardiogram NN I-NP O
, , O O
her PRP$ B-NP O
heart NN I-NP O
rate NN I-NP O
at IN B-PP O
times NNS B-NP O
is VBZ B-VP O
slower JJR B-ADJP O
. . O O
Impression NN B-NP O
: : O O
Ms. NNP B-NP O
Joshi NNP I-NP B-PATIENT
remains VBZ B-VP O
stable JJ B-ADJP O
from IN B-PP O
a DT B-NP O
cardiovascular JJ I-NP O
perspective NN I-NP O
, , O O
however RB B-ADVP O
, , O O
I PRP B-NP O
am VBP B-VP O
obviously RB I-VP O
concerned VBN I-VP O
about IN B-PP O
her PRP$ B-NP O
potential JJ I-NP O
for IN B-PP O
lightheadedness NN B-NP O
in IN B-PP O
light NN B-NP O
of IN B-PP O
her PRP$ B-NP O
bradycardia NN I-NP O
. . O O
I PRP B-NP O
have VBP B-VP O
asked VBN I-VP O
her PRP B-NP O
to TO B-VP O
decrease VB I-VP O
her PRP$ B-NP O
Toprol-XL NNP I-NP O
to TO I-NP O
25 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
daily RB B-ADVP O
and CC O O
to TO B-VP O
repeat VB I-VP O
an DT B-NP O
EKG NNP I-NP O
four CD I-NP O
to TO B-PP O
five CD B-NP O
days NNS I-NP O
after IN B-PP O
doing VBG B-VP O
so RB B-ADVP O
. . O O
I PRP B-NP O
of IN B-PP O
course NN B-NP O
have VBP B-VP O
reminded VBN I-VP O
her PRP B-NP O
as IN B-PP O
to TO B-PP O
the DT B-NP O
importance NN I-NP O
of IN B-PP O
getting VBG B-VP O
in IN B-PP O
contact NN B-NP O
with IN B-PP O
you PRP B-NP O
or CC O O
myself PRP B-NP O
straight RB B-ADVP O
away RB B-ADVP O
should MD O O
she PRP B-NP O
develop VB B-VP O
any DT B-NP O
symptoms NNS I-NP O
suggestive VBP B-VP O
of IN B-PP O
lightheadedness NN B-NP O
or CC I-NP O
dizziness NN I-NP O
. . O O
She PRP B-NP O
understands VBZ B-VP O
that IN B-SBAR O
she PRP B-NP O
may MD B-VP O
require VB I-VP O
a DT B-NP O
permanent JJ I-NP O
pacemaker NN I-NP O
in IN B-PP O
the DT B-NP O
future NN I-NP O
. . O O
Most RBS O O
recent JJ B-NP O
blood NN I-NP O
studies NNS I-NP O
show VBP B-VP O
a DT B-NP O
significantly RB I-NP O
elevated VBN I-NP O
glucose NN I-NP O
of IN B-PP O
183 CD B-NP O
( -LRB- I-NP O
she PRP B-NP O
states VBZ B-VP O
she PRP B-NP O
is VBZ B-VP O
trying VBG I-VP O
to TO I-VP O
tailor VB I-VP O
her PRP$ B-NP O
insulin NN I-NP O
regimen VBN B-VP O
with IN B-PP O
you PRP B-NP O
) -RRB- O O
and CC B-PP O
in IN B-PP O
January NNP B-NP B-DATE
, , O O
normal JJ B-NP O
liver NN I-NP O
function NN I-NP O
studies NNS I-NP O
except IN B-PP O
for IN B-PP O
an DT B-NP O
alkaline NN I-NP O
phosphatase NN I-NP O
of IN B-PP O
304 CD B-NP O
and CC O O
lipid VBD B-VP O
profile NN I-VP O
last JJ B-NP O
September NNP I-NP B-DATE
notable JJ I-NP O
for IN B-PP O
a DT B-NP O
cholesterol NN I-NP O
of IN B-PP O
134 CD B-NP O
, , O O
triglyceride NN B-NP O
of IN B-PP O
74 CD B-NP O
, , O O
HDL NNP B-NP O
58 CD I-NP O
, , O O
and CC O O
LDL NNP B-NP O
61 CD I-NP O
. . O O
She PRP B-NP O
understands VBZ B-VP O
the DT B-NP O
importance NN I-NP O
of IN B-PP O
continuing VBG B-VP O
to TO I-VP O
adhere VB I-VP O
to TO B-PP O
a DT B-NP O
low-saturated JJ I-NP O
fat JJ I-NP O
, , I-NP O
low-cholesterol JJ I-NP O
diet NN I-NP O
while IN B-SBAR O
remaining VBG B-VP O
on IN B-PP O
her PRP$ B-NP O
antilipemic JJ I-NP O
therapy NN I-NP O
. . O O
She PRP B-NP O
will MD B-VP O
discuss VB I-VP O
with IN B-PP O
you PRP B-NP O
and CC O O
her PRP B-NP O
nephrologist NN B-VP O
the DT B-NP O
optimal JJ I-NP O
management NN I-NP O
of IN B-PP O
her PRP$ B-NP O
mild JJ I-NP O
renal JJ I-NP O
insufficiency NN I-NP O
. . O O
In IN B-PP O
light NN B-NP O
of IN B-PP O
both DT B-NP O
her PRP$ I-NP O
diabetes NNS I-NP O
and CC O O
coronary JJ B-NP O
disease NN I-NP O
, , O O
it PRP B-NP O
certainly RB B-ADVP O
would MD B-VP O
be VB I-VP O
optimal JJ B-ADJP O
if IN B-PP O
possible JJ B-ADJP O
to TO B-VP O
continue VB I-VP O
her PRP B-NP O
on IN B-PP O
her PRP$ B-NP O
ACE NNP I-NP O
inhibitor NN I-NP O
. . O O
At IN B-PP O
the DT B-NP O
present JJ I-NP O
time NN I-NP O
, , O O
she PRP B-NP O
does VBZ B-VP O
not RB I-VP O
meet VB I-VP O
criteria NNS B-NP O
for IN B-PP O
prophylactic JJ B-NP O
placement NN I-NP O
of IN B-PP O
an DT B-NP O
AICD NNP I-NP O
and CC O O
her PRP$ B-NP O
New NNP I-NP O
York NNP I-NP O
Heart NNP I-NP O
Association NNP I-NP O
class NN I-NP O
I PRP B-NP O
to TO B-PP O
II NNP B-NP O
status NN I-NP O
precludes VBZ B-VP O
the DT B-NP O
need NN I-NP O
for IN B-PP O
consideration NN B-NP O
of IN B-PP O
biventricular JJ B-NP O
pacing NN I-NP O
. . O O
Other JJ B-ADJP O
than IN B-PP O
reducing VBG B-VP O
her PRP$ B-NP O
beta-blocker NN I-NP O
regimen NNS I-NP O
as IN B-SBAR O
described VBN B-VP O
above IN B-ADVP O
, , O O
I PRP B-NP O
have VBP B-VP O
not RB I-VP O
further RB I-VP O
altered VBN I-VP O
her PRP$ B-NP O
current JJ I-NP O
medical JJ I-NP O
program NN I-NP O
. . O O
I PRP B-NP O
thank VBP B-VP O
you PRP B-NP O
very RB B-ADVP O
much RB I-ADVP O
for IN B-PP O
allowing VBG B-VP O
me PRP B-NP O
to TO B-VP O
assist VB I-VP O
in IN B-PP O
her PRP$ B-NP O
care NN I-NP O
. . O O
Sincerely RB B-ADVP O
yours PRP B-NP O
, , O O
Brandon NNP B-NP B-DOCTOR
W NNP I-NP I-DOCTOR
Neilson NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
eScription NN B-NP O
document NN I-NP O
: : O O
0-2421626 CD B-NP B-IDNUM
RU NNS I-NP I-IDNUM
CC NNP B-NP O
: : O O
James NNP B-NP B-DOCTOR
Nolen NNP I-NP I-DOCTOR
M.D. . O O
48 CD B-NP B-STREET
Auburn NNP I-NP I-STREET
Street NNP I-NP I-STREET
Rehoboth NNP B-NP B-CITY
, , O O
NM NNP B-NP B-STATE
42761 CD I-NP B-ZIP
DD NNP B-NP O
: : O O
07/06/72 CD O B-DATE
DT NNP B-NP O
: : O O
07/07/72 CD O B-DATE
DV NNP B-NP O
: : O O
07/06/72 CD O B-DATE
