Record NNP B-NP O
date NN I-NP O
: : O O
2069-09-17 CD O B-DATE
OFFICE NNP B-NP O
NOTE NNP I-NP O
Andrew NNP B-NP B-PATIENT
Conner NNP I-NP I-PATIENT
MRN NNP B-NP O
: : O O
9911852 CD O B-MEDICALRECORD
September NNP B-NP B-DATE
17 CD I-NP I-DATE
, , I-NP I-DATE
2069 CD O I-DATE
Problems NNS B-NP O
: : O O
1 LS O O
. . B-NP O
Diabetes NNP I-NP O
mellitus NN I-NP O
. . O O
He PRP B-NP O
continues VBZ B-VP O
on IN B-PP O
Glucotrol NNP B-NP O
and CC O O
Glucophage NNP B-NP O
. . I-NP O
Blood NNP I-NP O
sugars NNS I-NP O
appear VBP B-VP O
to TO I-VP O
be VB I-VP O
in IN B-PP O
pretty RB B-NP O
good JJ I-NP O
range NN I-NP O
. . O O
Last JJ B-NP O
A1C NNP I-NP O
was VBD B-VP O
respectable JJ B-ADJP O
. . O O
To TO B-VP O
be VB I-VP O
repeated VBN I-VP O
today NN B-NP O
. . O O
2. DT B-NP O
Hyperlipidemia NNP I-NP O
. . O O
Lipids NNS B-NP O
are VBP B-VP O
pending VBG I-VP O
. . O O
3. DT B-NP O
Angina NNP I-NP O
. . I-NP O
Previous NNP I-NP O
stress NN I-NP O
test NN I-NP O
showed VBD B-VP O
positive JJ B-NP O
EKG NN I-NP O
changes NNS B-NP O
, , O O
equivocal JJ B-NP O
scan NN I-NP O
. . O O
Mild NNP B-NP O
angina NN I-NP O
. . O O
Started VBN B-VP O
on IN B-PP O
trans NNS B-NP O
- : O O
derm NN B-NP O
nitro NN I-NP O
. . B-NP O
Totally RB B-ADVP O
must MD B-VP O
quit VB I-VP O
all DT B-NP O
cigars NNS I-NP O
. . O O
Lipids NNS B-VP O
to TO I-VP O
be VB I-VP O
repeated VBN B-ADJP O
. . O O
4 LS O O
. . B-NP O
Hypertension NNP I-NP O
. . O O
On IN B-PP O
captopril NN B-NP O
, , I-NP O
atenolol NN I-NP O
and CC I-NP O
trans-derm NN I-NP O
nitro NN B-NP O
. . O O
Blood NN B-NP O
pressure NN I-NP O
/70 CD B-NP O
, , O O
pulse NN B-NP O
60 CD I-NP O
and CC O O
regular JJ B-NP O
, , I-NP O
COR JJ I-NP O
normal JJ B-ADJP O
. . O O
Impression NN B-NP O
: : O O
Good JJ B-NP O
control NN I-NP O
. . O O
5 CD B-NP O
. . O O
Weight NNP O O
. . O O
His PRP$ B-NP O
weight NN I-NP O
is VBZ B-VP O
192 CD B-NP O
, , O O
should MD B-VP O
be VB I-VP O
175 CD B-NP O
. . O O
Discussed VBN B-VP O
. . O O
Overall RB B-ADVP O
, , O O
he PRP B-NP O
has VBZ B-VP O
got VBN I-VP O
things NNS B-NP O
he PRP B-NP O
can MD B-VP O
do VB I-VP O
to TO B-VP O
improve VB I-VP O
, , O O
and CC O O
these DT B-NP O
were VBD B-VP O
all DT B-NP O
discussed VBN B-VP O
in IN B-PP O
detail NN B-NP O
with IN B-PP O
the DT B-NP O
patient NN I-NP O
and CC O O
his PRP$ B-NP O
wife NN I-NP O
. . O O
Brandon NNP B-NP B-DOCTOR
Walls NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Dictated/Not NN B-NP O
read VBN I-NP O
BW NNP B-NP B-DOCTOR
/ NN I-NP O
yamamoto NN I-NP B-DOCTOR
