Record NNP B-NP O
date NN I-NP O
: : O O
2097-08-11 CD O B-DATE
EDVISIT^ NNP B-NP O
29964344 CD I-NP B-MEDICALRECORD
^ , O O
WHITAKER NNP B-NP I-PATIENT
, , O I-PATIENT
VINCENT NNP B-NP I-PATIENT
^ VBD B-VP O
08/11/97 CD B-NP B-DATE
^ NN I-NP O
TRAN NNP I-NP I-DOCTOR
, , O I-DOCTOR
FREDDY NNP B-NP I-DOCTOR
I PRP B-NP O
confirm VBP B-VP O
that IN B-SBAR O
I PRP B-NP O
have VBP B-VP O
interviewed VBN I-VP O
and CC O O
examined VBN B-VP O
the DT B-NP O
patient NN I-NP O
, , O O
reviewed VBN B-VP O
the DT B-NP O
resident NN I-NP O
's POS B-NP O
documentation NN I-NP O
on IN B-PP O
the DT B-NP O
patient NN I-NP O
's POS B-NP O
chart NN I-NP O
, , O O
and CC O O
discussed VBD B-VP O
the DT B-NP O
evaluation NN I-NP O
, , O O
plan NN B-NP O
of IN B-PP O
care NN B-NP O
, , O O
and CC O O
disposition NN B-NP O
with IN B-PP O
the DT O O
patient NN B-NP O
and CC O O
the DT B-NP O
resident NN I-NP O
, , O O
Dr. NNP B-NP O
Nieto NNP I-NP B-DOCTOR
. . O O
Please VB B-VP O
see VB I-VP O
her PRP B-NP O
note NN B-VP O
for IN B-PP O
full JJ B-NP O
details NNS I-NP O
. . O O
HISTORY NN B-NP O
OF IN B-PP O
PRESENT JJ B-NP O
ILLNESS NNS I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
a DT B-NP O
65 CD I-NP B-AGE
-year-old JJ I-NP O
gentleman NN B-NP O
with IN B-PP O
significant JJ B-NP O
past JJ I-NP O
medical JJ I-NP O
history NN I-NP O
of IN B-PP O
hypertension NN B-NP O
; : O O
diabetes NNS B-NP O
; : O O
AFib NNP B-NP O
; : O O
CHF NNP B-NP O
; : O O
chronic JJ B-NP O
renal JJ I-NP O
insufficiency NN I-NP O
; : O O
end-stage NN B-NP O
renal NN I-NP O
disease NN B-NP O
on IN B-PP O
hemodialysis NN B-NP O
Monday NNP B-NP B-DATE
, , O O
Wednesday NNP B-NP B-DATE
and CC O O
Friday NNP B-NP B-DATE
; : O O
history NN B-NP O
of IN B-SBAR O
PE NN B-NP O
and CC I-NP O
cardiac NN I-NP O
arrest NN I-NP O
as RB B-ADVP O
well RB I-ADVP O
as IN B-PP O
bacteremia NN B-NP O
who WP B-NP O
presents VBZ B-VP O
with IN B-PP O
cough NN B-NP O
, , O O
weakness NN B-NP O
, , O O
chest NN B-NP O
pain NN I-NP O
, , O O
and CC O O
palpitations NNS B-NP O
. . O O
At IN B-PP O
dialysis NN B-NP O
he PRP B-LST O
was VBD B-VP O
found VBN I-VP O
coughing NN B-NP O
and CC O O
was VBD B-VP O
sent VBN I-VP O
here RB B-ADVP O
via IN B-PP O
ambulance NN B-NP O
. . O O
He PRP B-NP O
notes NNS B-LST O
decreased VBN B-NP O
appetite NN I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
fevers NNS I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
noted VBN I-VP O
some DT O O
chills NNS B-NP O
, , O O
some DT B-NP O
sweats NNS I-NP O
, , O O
and CC O O
some DT B-NP O
shortness NN I-NP O
of IN B-PP O
breath NN B-NP O
. . O O
PHYSICAL NNP B-NP O
EXAMINATION NN I-NP O
: : O O
He PRP B-NP O
is VBZ B-VP O
slow JJ B-ADJP O
. . O O
Temperature NNP B-NP O
95.9 CD I-NP O
, , O O
pulse NN B-NP O
89 CD I-NP O
, , O O
respiratory JJ B-NP O
rate NN I-NP O
18 CD I-NP O
, , O O
blood NN B-NP O
pressure NN I-NP O
180/71 CD B-NP O
, , O O
and CC O O
saturation NN B-NP O
is VBZ B-VP O
95 CD B-NP O
% NN I-NP O
on IN B-PP O
2 CD B-NP O
liters NNS I-NP O
. . O O
He PRP B-NP O
looks VBZ B-VP O
dyspneic VBN I-VP O
, , O O
dehydrated VBN B-VP O
with IN B-PP O
neck NN B-NP O
that WDT B-NP O
is VBZ B-VP O
supple NN B-NP O
. . O O
No DT B-NP O
rales NNS I-NP O
, , O O
rhonchi NNP B-NP O
, , O O
or CC O O
wheezing CD B-NP O
. . O O
Heart NNP B-NP O
is VBZ B-VP O
regular JJ O O
without IN B-PP O
a DT B-NP O
murmur NN I-NP O
. . O O
Abdomen '' O O
is VBZ B-VP O
soft JJ B-ADJP O
, , O O
nontender JJ B-ADJP O
, , O O
and CC O O
nondistended JJ B-ADJP O
. . O O
Skin NNP B-NP O
is VBZ B-VP O
intact JJ B-ADJP O
. . O O
He PRP B-NP O
has VBZ B-VP O
2+ JJ B-NP O
pedal NN I-NP O
edema NN I-NP O
. . O O
He PRP B-NP O
appears VBZ B-VP O
to TO I-VP O
be VB I-VP O
lethargic NN B-NP O
but CC O O
no DT B-NP O
focal JJ I-NP O
neurologically RB I-NP O
. . O O
LABORATORY NNP B-NP O
DATA NNP I-NP O
: : O O
Review NNP B-NP O
of IN B-PP O
his PRP$ B-NP O
blood NN I-NP O
work NN I-NP O
shows VBZ B-VP O
a DT B-NP O
BUN NNP I-NP O
of IN B-PP O
31 CD B-NP O
, , O O
creatinine CD B-NP O
of IN B-PP O
6.07 CD B-NP O
, , O O
sodium NN B-NP O
of IN B-PP O
139 CD B-NP O
, , O O
potassium NN B-NP O
of IN B-PP O
5.6 CD B-NP O
and CC O O
bicarbonate NN B-NP O
of IN B-PP O
32 CD B-NP O
. . O O
LFTs NNP B-NP O
are VBP B-VP O
normal JJ B-NP O
. . B-NP O
Lipase NNP I-NP O
is VBZ B-VP O
63 CD B-NP O
. . O O
BNP NNP B-NP O
is VBZ B-VP O
501 CD B-NP O
. . O O
Lactic JJ B-NP O
acid NN I-NP O
is VBZ B-VP O
3. DT B-NP O
Troponin NNP I-NP O
is VBZ B-VP O
0.04 CD B-NP O
. . O O
White NNP B-NP O
count NN I-NP O
5 CD B-NP O
, , O O
hematocrit NN B-NP O
42 CD B-NP O
, , O O
and CC O O
INR NNP B-NP O
2. VBD B-VP O
Chest NNP B-NP O
x-ray NN I-NP O
shows VBZ B-VP O
cardiomegaly NN B-NP O
, , O O
no DT B-NP O
acute JJ I-NP O
pneumonia NN B-NP O
. . O O
An DT O O
EKG NNP O O
with IN B-PP O
rate NN B-NP O
106 CD I-NP O
, , O O
normal JJ B-NP O
ST-T JJ I-NP O
changes NNS I-NP O
. . O O
EMERGENCY NNP B-NP O
DEPARTMENT NNP I-NP O
COURSE NNP I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
was VBD B-VP O
covered VBN I-VP O
empirically RB O O
with IN B-PP O
vancomycin NN B-NP O
, , O O
ceftazidime NN B-NP O
, , O O
given VBN B-VP O
gentle JJ B-NP O
IV NNP I-NP O
fluid NN I-NP O
bolus NN I-NP O
and CC O O
is VBZ O O
being VBG B-VP O
admitted VBN I-VP O
to TO B-PP O
Renal NNP B-NP O
Medicine NNP I-NP O
. . O O
At IN B-PP O
this DT B-NP O
time NN I-NP O
, , O O
he PRP B-NP O
is VBZ B-VP O
hemodynamically RB B-ADVP O
stable JJ B-ADJP O
. . O O
PRIMARY NNP B-NP O
DIAGNOSIS NNP I-NP O
: : O O
Weakness NNP B-NP O
, , O O
end-stage NN B-NP O
renal JJ I-NP O
disease NN I-NP O
, , O O
and CC O O
possible JJ B-NP O
early JJ I-NP O
infection NN I-NP O
including VBG I-NP O
bacteremia NN I-NP O
. . O O
TRAN NNP B-NP I-DOCTOR
, , O I-DOCTOR
FREDDY NNP B-NP I-DOCTOR
M.D. NNP I-NP O
D NNP B-NP O
: : O O
08/11/97 CD O B-DATE
T NNP B-NP O
: : O O
08/11/97 CD O B-DATE
Dictated NNP B-NP O
By IN I-NP O
: : O O
TRAN NNP B-NP I-DOCTOR
, , O I-DOCTOR
FREDDY NNP B-NP I-DOCTOR
eScription NN B-NP O
document NN I-NP O
: : O O
1-0225776 CD B-NP B-IDNUM
BFFocus NN I-NP O
******** NN B-NP O
Not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Physician JJ B-NP O
******** NNS I-NP O
