Record NNP B-NP O
date NN I-NP O
: : O O
2097-01-27 CD O B-DATE
RENAL JJ B-NP O
FELLOW NNP I-NP O
CONSULTATION NN I-NP O
NOTE . O O
PATIENT NNP B-NP O
: : O O
WHITAKER NN B-NP I-PATIENT
, , O I-PATIENT
VINCENT NNP B-NP I-PATIENT
UNIT# NNP B-NP O
: : O O
29964344 CD O B-MEDICALRECORD
ADMIT NNP B-NP O
DATE NNP I-NP O
: : O O
1/26/97 CD O B-DATE
ATTENDING NN B-NP O
: : O O
Dr. NNP B-NP O
Noor NNP I-NP B-DOCTOR
Uyeda NNP I-NP I-DOCTOR
Source NN B-NP O
: : O O
Notes NNS B-NP O
Reason RB B-ADVP O
for IN B-PP O
consult VB B-NP O
: : O O
Acute NNP B-NP O
on IN B-PP O
chronic JJ B-NP O
renal JJ I-NP O
failure NN I-NP O
HPI NNP B-NP O
: : O O
65 CD B-NP B-AGE
y/o JJ I-NP O
man NN I-NP O
with IN B-PP O
PMH NNP B-NP O
of IN B-PP O
stage NN B-NP O
IV NNP I-NP O
CKD NNP I-NP O
, , O O
HTN NNP B-NP O
, , O O
CAD NNP B-NP O
, , O O
RAS NNP B-NP O
, , O O
DM NNP B-NP O
, , O O
who WP B-NP O
was VBD B-VP O
admitted VBN I-VP O
to TO B-PP O
the DT B-NP O
CCU NNP I-NP O
on IN B-PP O
1/26 CD B-NP B-DATE
after IN B-PP O
an DT B-NP O
episode NN I-NP O
of IN B-PP O
bradycardia NN B-NP O
and CC I-NP O
PEA NN I-NP O
arrest NN I-NP O
at IN B-PP O
home NN B-NP O
. . O O
Pt NNP B-NP O
was VBD B-VP O
found VBN I-VP O
by IN B-PP O
his PRP$ B-NP O
wife NN I-NP O
yesterday NN B-NP O
to TO B-VP O
be VB I-VP O
complaining VBG I-VP O
of IN B-PP O
severe JJ B-NP O
chest NN I-NP O
pain NN I-NP O
and CC O O
SOB. NNP B-NP O
She PRP B-NP O
called VBD B-VP O
EMS. NNP B-NP O
Upon IN B-PP O
arrival NN B-NP O
of IN B-PP O
EMS NNP B-NP O
, , O O
pt NN B-NP O
was VBD B-VP O
in IN B-PP O
respiratory JJ B-NP O
distress NN I-NP O
and CC I-NP O
bradycardic NN I-NP O
with IN B-PP O
a DT B-NP O
HR NN I-NP O
in IN B-PP O
the DT B-NP O
20s NNS I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
intubated JJ B-ADJP O
. . O O
He PRP B-NP O
subsequently RB B-ADVP O
became VBD B-VP O
puloseless JJ B-ADJP O
and CC I-ADJP O
asystolic JJ I-ADJP O
and CC O O
was VBD B-VP O
coded VBN I-VP O
for IN B-PP O
about IN B-NP O
10 CD I-NP O
minutes NNS I-NP O
with IN B-PP O
3 CD B-NP O
rounds NNS I-NP O
of IN B-PP O
epinephrine NN B-NP O
and CC I-NP O
atropine NN I-NP O
before IN B-SBAR O
he PRP B-NP O
regained VBD B-VP O
his PRP$ B-NP O
pulse NN I-NP O
. . O O
In IN B-PP O
the DT B-NP O
ED NNP I-NP O
, , O O
his PRP$ B-NP O
BP NNP I-NP O
was VBD B-VP O
230/120 CD B-NP O
and CC O O
he PRP B-NP O
was VBD B-VP O
started VBN I-VP O
on IN B-PP O
a DT B-NP O
nitro NN I-NP O
gtt NN I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
noted VBN I-VP O
to TO I-VP O
have VB I-VP O
blood NN B-NP O
in IN B-PP O
his PRP$ B-NP O
OG JJ I-NP O
tube NN I-NP O
. . O O
CXR NN B-NP O
showed VBD B-VP O
bilateral JJ B-NP O
patchy JJ I-NP O
infiltrates NNS I-NP O
consistent JJ B-ADJP O
with IN B-PP O
pulmonary JJ B-NP O
edema NN I-NP O
. . O O
Chest NNP B-NP O
CT NNP I-NP O
showed VBD B-VP O
multiple JJ B-NP O
rib NN I-NP O
fractures NNS I-NP O
with IN B-PP O
substernal JJ B-NP O
hematoma NN I-NP O
and CC O O
bilateral JJ B-NP O
modest JJ I-NP O
pleural JJ I-NP O
effusions NNS I-NP O
with IN B-PP O
adjacent JJ B-NP O
atelectasis NN I-NP O
vs IN B-PP O
consolidations NNS B-NP O
. . O O
On IN B-PP O
admission NN B-NP O
, , O O
pt&#8217 DT B-NP O
;s NNP I-NP O
BUN NNP I-NP O
and CC O O
creatinine CD B-NP O
were VBD B-VP O
43 CD B-NP O
and CC I-NP O
4.35 CD I-NP O
, , O O
respectively RB B-ADVP O
. . O O
He PRP B-NP O
was VBD B-VP O
started VBN I-VP O
on IN B-PP O
a DT B-NP O
lasix NN I-NP O
gtt NN I-NP O
for IN B-PP O
diuresis NN B-NP O
without IN B-PP O
a DT B-NP O
good JJ I-NP O
response NN I-NP O
. . B-PP O
His PRP$ B-NP O
Cr NNP I-NP O
started VBD B-VP O
to TO I-VP O
rise VB I-VP O
: : O O
4.6 CD B-NP O
&# NN I-NP O
224 CD I-NP O
; : O O
4.9 CD B-NP O
&# JJ I-NP O
224 CD I-NP O
; : O O
5.4 CD B-NP O
&# NN I-NP O
224 CD I-NP O
; : O O
5.33 CD B-NP O
&# NN I-NP O
224 CD I-NP O
; : O O
6.3 CD B-NP O
&# NN I-NP O
224 CD I-NP O
; : O O
7.0. RP B-NP O
His PRP$ B-NP O
urine JJ I-NP O
output NN I-NP O
continued VBD B-VP O
to TO I-VP O
be VB I-VP O
poor JJ B-ADJP O
, , O O
and CC O O
renal JJ B-NP O
consult VB I-NP O
was VBD B-VP O
called VBN I-VP O
. . O O
MEDICAL NNP B-NP O
HISTORY NNP I-NP O
: : O O
Stage NN B-NP O
IV NNP I-NP O
CKD . O O
Right-sided JJ B-NP O
RAS NNS I-NP O
HTN . O O
CAD NN B-NP O
DM . O O
Anemia NN B-NP O
GERD NNP B-NP O
Impotence NN B-NP O
MEDICATIONS NNS B-NP O
: : O O
Versed NNP B-NP O
gtt NN I-NP O
Propofol NNP B-NP O
gtt NN I-NP O
Fentanyl NNP B-NP O
gtt NN I-NP O
Heparin NNP B-NP O
5000 CD I-NP O
units NNS I-NP O
Q8h . O O
Levofloxacin NNP B-NP O
250mg CD I-NP O
IV NNP I-NP O
Q48h . O O
Flagyl NNP B-NP O
250mg CD I-NP O
IV NNP I-NP O
Q8h . O O
ASA NNP B-NP O
325mg JJ I-NP O
daily JJ I-NP O
Pepcid NNP B-NP O
20mg CD I-NP O
IV NNP I-NP O
daily JJ I-NP O
Colace NNP B-NP O
100mg CD I-NP O
BID . O O
Tylenol NNP B-NP O
PRN NNP I-NP O
Maalox NNP B-NP O
PRN NNP I-NP O
Mucomyst NNP B-NP O
1200mg CD I-NP O
BID NNP I-NP O
x NN I-NP O
4 CD B-NP O
doses NNS I-NP O
ALLERGIES NNS B-NP O
: : O O
NKDA NNP B-NP O
SOCIAL JJ B-NP O
HISTORY NN I-NP O
: : O O
Tobacco NNP B-NP O
&#8211 CD I-NP O
; : O O
Denies NNS B-NP O
EtOH NNP B-NP O
&#8211 CD I-NP O
; : O O
Denies NNS B-NP O
Illicits NNS B-NP O
&#8211 CD B-NP O
; : O O
Denies NNS B-NP O
Lives NNS B-NP O
with IN B-PP O
wife NN B-NP O
and CC O O
4 CD B-NP O
children NNS I-NP O
PHYSICAL NNP B-NP O
EXAM NNP I-NP O
: : O O
VITALS NNS B-NP O
: : O O
T NNP B-NP O
99.7 CD I-NP O
, , O O
pulse NN B-NP O
58 CD I-NP O
, , O O
BP NNP B-NP O
120/60 CD I-NP O
, , O O
CVP NNP B-NP O
9 CD I-NP O
Vent NNP B-NP O
: : O O
AC NNP B-NP O
14 CD I-NP O
x NN I-NP O
600 CD B-NP O
/ JJ I-NP O
40 CD I-NP O
% NN I-NP O
/ NN I-NP O
+5 . O O
U/O NNP B-NP O
: : O O
0-30cc/hr NN B-NP O
GEN NNP B-NP O
: : O O
Intubated NNP B-NP O
and CC O O
sedated JJ B-NP O
HEENT NNP B-NP O
: : O O
Atraumatic . O O
NECK NNP B-NP O
: : O O
Right RB B-ADVP O
IJ IN B-PP O
central JJ B-NP O
line NN I-NP O
. . O O
HEART NNP B-NP O
: : O O
RRR NNP B-NP O
, , O O
S1S2 NNP B-NP O
normal JJ I-NP O
, , O O
no DT B-NP O
M/R/G NN I-NP O
LUNG NN B-NP O
: : O O
Coarse NNP B-NP O
vented VBD B-VP O
breath NN B-NP O
sounds NNS I-NP O
ABD NNP B-NP O
: : O O
Soft NNP B-NP O
, , O O
NT NNP B-NP O
, , O O
ND NNP B-NP O
EXT NNP B-NP O
: : O O
Trace NNP B-NP O
edema NN I-NP O
SKIN JJ B-NP O
: : O O
No DT B-NP O
rashes NNS I-NP O
NEURO NNP B-NP O
: : O O
Unable JJ B-ADJP O
to TO B-VP O
assess VB I-VP O
LAB NNP B-NP O
RESULTS NNS I-NP O
: : O O
CBC NNP B-NP O
: : O O
WBC NNP B-NP O
9.1 CD I-NP O
, , O O
Hgb NNP B-NP O
7.9 CD I-NP O
, , I-NP O
plts NNS I-NP O
188k CC O O
BCP NNP B-NP O
: : O O
Na NNP B-NP O
136 CD I-NP O
, , O O
K NNP B-NP O
5.2 CD I-NP O
, , O O
Cl NNP B-NP O
106 CD I-NP O
, , O O
HCO3 NNP B-NP O
18 CD I-NP O
, , O O
BUN NNP B-NP O
68 CD I-NP O
, , O O
Cr NNP B-NP O
7.0, CD I-NP O
glucose NN I-NP O
139 CD O O
Ca MD O O
7.9 CD B-NP O
, , O O
Mg NNP B-NP O
2.4 CD I-NP O
Coags NNS B-NP O
: : O O
INR NNP B-NP O
1.2 CD I-NP O
, , O O
PTT NNP B-NP O
28.6 CD I-NP O
ABG NNP B-NP O
: : O O
7.33 CD B-NP O
/ NN I-NP O
37 CD B-NP O
/ NN I-NP O
171 CD O O
U/A NNP B-NP O
: : O O
1.010 CD B-NP O
, , O O
pH NN B-NP O
5.5 CD I-NP O
, , I-NP O
2+ CD I-NP O
prot NN I-NP O
, , O O
1+ JJ B-NP O
blood NN I-NP O
, , O O
14 CD B-NP O
hyaline NN I-NP O
casts NNS I-NP O
, , O O
6 CD B-NP O
RBC NNP I-NP O
, , I-NP O
7 CD I-NP O
WBC . O O
IMPRESSION NN B-NP O
: : O O
65 CD B-NP B-AGE
y/o JJ I-NP O
man NN I-NP O
with IN B-PP O
stage NN B-NP O
IV NNP I-NP O
CKD NNP I-NP O
, , O O
DM NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
CAD NNP B-NP O
, , O O
s/p NN B-NP O
bradycardia NN I-NP O
and CC I-NP O
PEA NN I-NP O
arrest NN I-NP O
, , O O
now RB B-VP O
intubated VBN I-VP O
with IN B-PP O
oligoanuric JJ B-NP O
acute JJ I-NP O
on IN B-PP O
chronic JJ B-NP O
renal JJ I-NP O
failure NN I-NP O
. . O O
Etiology NN B-VP O
most RBS B-ADVP O
likely JJ I-ADVP O
2/2 IN B-PP O
cardiac JJ B-NP O
arrest NN I-NP O
with IN B-PP O
hypotension NN B-NP O
resulting VBG B-VP O
in IN B-PP O
ischemic JJ B-NP O
ATN. NNP I-NP O
Given VBN B-VP O
his PRP$ B-NP O
hyperkalemia NN I-NP O
and CC I-NP O
acidemia NN I-NP O
in IN B-PP O
the DT B-NP O
context NN I-NP O
of IN B-PP O
anuria NNS B-NP O
, , O O
we PRP B-NP O
will MD B-VP O
start VB I-VP O
the DT B-NP O
pt NN I-NP O
on IN B-PP O
CVVH NNP B-NP O
today NN B-NP O
. . O O
If IN B-PP O
his PRP$ B-NP O
BP NNP I-NP O
tolerates NNS I-NP O
it PRP B-NP O
, , O O
he PRP B-NP O
may MD B-VP O
be VB I-VP O
able JJ B-ADJP O
to TO B-PP O
transition NN B-NP O
over IN B-PP O
to TO B-PP O
intermittent JJ B-NP O
HD NNP I-NP O
soon RB B-ADVP O
. . O O
1 LS B-NP O
. . B-VP O
Will VB I-VP O
place NN B-NP O
right RB B-ADVP O
femoral JJ B-NP O
vein NN I-NP O
hemodialysis NN I-NP O
catheter NN I-NP O
. . O O
2. DT B-NP O
Start NNP I-NP O
citrate NN I-NP O
CVVH NNP B-NP O
120/2000 CD I-NP O
with IN B-PP O
DFL NNP B-NP O
of IN B-PP O
50cc/hr JJ B-NP O
as IN B-PP O
BP NNP B-NP O
tolerates NNS I-NP O
3. `` O O
I PRP B-NP O
will MD B-VP O
examine VB I-VP O
his PRP$ B-NP O
urinary JJ I-NP O
sediment NN I-NP O
. . O O
4 CD B-LST O
. . O O
Please VB B-VP O
check NN B-NP O
urine NN I-NP O
Na NNP I-NP O
, , O O
urea NN B-NP O
nitrogen NN I-NP O
, , O O
total JJ B-NP O
protein NN I-NP O
, , I-NP O
creatinine NN I-NP O
. . O O
5 CD B-LST O
. . O O
Please VB B-VP O
order NN B-NP O
renal JJ B-ADJP O
US. . O O
6 CD B-NP O
. . O O
Renally NNP O O
dose NN B-VP O
all DT B-NP O
medications NNS I-NP O
for IN B-PP O
CVVH. NNP B-NP O
Travis NNP B-NP B-DOCTOR
X NNP I-NP I-DOCTOR
. . I-NP I-DOCTOR
Vogel NNP I-NP I-DOCTOR
, , O O
MD . O O
Longview NNP B-NP B-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
Renal NNP I-NP O
Fellow NNP I-NP O
Pager NNP B-NP O
5-6394 CD I-NP B-PHONE
