Record NNP B-NP O
date NN I-NP O
: : O O
2061-01-31 CD O B-DATE
EDVISIT^ NNP B-NP O
32707420 CD I-NP B-MEDICALRECORD
^ , O O
GIPSON NNP B-NP I-PATIENT
, , O I-PATIENT
ALEXANDER NNP B-NP I-PATIENT
^ NNP I-NP O
01/31/61 CD I-NP B-DATE
^ , I-NP O
VELASQUEZ NNP I-NP I-DOCTOR
, , I-NP I-DOCTOR
WALTER NNP I-NP I-DOCTOR
This DT B-NP O
patient NN I-NP O
was VBD B-VP O
seen VBN I-VP O
by IN B-PP O
myself PRP B-NP O
and CC O O
Dr. NNP B-NP O
Hardin NNP I-NP B-DOCTOR
on IN B-PP O
01/31/2061 CD B-NP B-DATE
. . O O
I PRP O O
confirm VB B-VP O
I PRP B-NP O
interviewed VBD B-VP O
and CC O O
examined VBD B-VP O
the DT B-NP O
patient NN I-NP O
, , O O
reviewed VBN B-VP O
the DT B-UCP O
resident NN B-NP O
's POS B-NP O
documentation NN I-NP O
, , O O
and CC O O
discussed VBD B-VP O
the DT B-NP O
plan NN I-NP O
of IN B-PP O
care NN B-NP O
with IN B-PP O
the DT O O
patient NN B-NP O
. . O O
HISTORY NN B-NP O
OF IN B-PP O
PRESENT JJ B-NP O
ILLNESS NNS I-NP O
: : O O
This DT B-NP O
is VBZ B-VP O
a DT B-NP O
73 CD I-NP B-AGE
-year-old JJ I-NP O
gentleman NN I-NP O
who WP O O
has VBZ B-VP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
CAD NN B-NP O
status NN I-NP O
post NN I-NP O
stent NN I-NP O
in IN B-PP O
2060 CD B-NP B-DATE
, , O O
who WP B-NP O
developed VBD B-VP O
acute JJ B-NP O
chest NN I-NP O
discomfort NN I-NP O
, , O O
pressure NN B-VP O
like IN B-PRT O
, , O O
diaphoresis NN B-NP O
, , O O
and CC O O
weakness NN B-NP O
, , O O
while IN B-SBAR O
he PRP B-NP O
was VBD B-VP O
working VBG I-VP O
as IN B-PP O
a DT B-NP O
chiropractor NN I-NP B-PROFESSION
. . O O
He PRP B-NP O
says VBZ B-VP O
although IN B-SBAR O
this DT B-NP O
was VBD B-VP O
quite RB B-ADJP O
significant JJ I-ADJP O
, , O O
it PRP B-NP O
was VBD B-VP O
not RB B-ADVP O
like IN B-PP O
his PRP$ B-NP O
prior JJ I-NP O
MI NNP I-NP O
discomfort NN I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
radiation NN I-NP O
to TO B-PP O
his PRP$ B-NP O
back NN I-NP O
or CC O O
his PRP$ B-NP O
arm NN I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT O O
jaw NN B-NP O
pain NN I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
fever NN I-NP O
, , O O
chills NNS B-NP O
, , O O
or CC O O
sweats VBZ B-VP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT O O
vomiting NN B-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
headache NN I-NP O
or CC I-NP O
neck NN I-NP O
pain NN I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT O O
bowel NN B-NP O
or CC I-NP O
bladder NN I-NP O
changes NNS I-NP O
and CC O O
no DT B-NP O
lower JJR I-NP O
extremity NN I-NP O
edema NN I-NP O
. . O O
He PRP B-NP O
is VBZ B-LST O
taking VBG B-VP O
his PRP$ B-NP O
medicines NNS I-NP O
. . O O
He PRP B-NP O
also RB B-ADVP O
took VBD B-VP O
an DT B-NP O
aspirin NN I-NP O
, , O O
did VBD B-VP O
get VB I-VP O
some DT O O
nitroglycerin NN B-NP O
. . O O
PAST NN B-NP O
MEDICAL NNP I-NP O
HISTORY NNP I-NP O
: : O O
Diabetes NNP B-NP O
, , I-NP O
hypertension NN I-NP O
, , O O
hypercholesterolemia NN B-NP O
, , O O
and CC O O
CAD. NNP B-NP O
MEDICATIONS NNS B-NP O
: : O O
Cozaar NNP B-NP O
, , O O
aspirin NN B-NP O
, , O O
Altace NNP B-NP O
, , O O
metformin NN B-NP O
, , O O
and CC O O
Toprol NNP B-NP O
. . O O
ALLERGIES NNS B-NP O
: : O O
He PRP B-NP O
has VBZ B-VP O
no RB I-VP O
known VBN I-VP O
drug NN B-NP O
allergies NNS I-NP O
. . O O
SOCIAL JJ B-NP O
HISTORY NN I-NP O
: : O O
He PRP B-NP O
is VBZ B-VP O
a DT B-NP O
past JJ I-NP O
smoker NN I-NP O
, , O O
not RB O O
a DT B-NP O
drinker NN I-NP O
or CC I-NP O
drug NN I-NP O
user NN I-NP O
. . O O
He PRP B-NP O
lives VBZ B-VP O
with IN B-PP O
his PRP$ B-NP O
family NN I-NP O
. . O O
REVIEW NN B-NP O
OF IN B-PP O
SYSTEMS NNP B-NP O
: : O O
As IN B-SBAR O
noted VBN B-VP O
in IN B-PP O
the DT B-NP O
HPI NNP I-NP O
, , O O
otherwise RB B-ADVP O
negative JJ B-ADJP O
. . O O
PHYSICAL NNP B-NP O
EXAMINATION NN I-NP O
: : O O
He PRP B-NP O
is VBZ B-VP O
in IN B-PP O
no DT B-NP O
acute JJ I-NP O
distress NN I-NP O
at IN B-PP O
rest NN B-NP O
. . O O
He PRP O O
says VBZ B-VP O
his PRP$ B-NP O
chest NN I-NP O
pain NN I-NP O
is VBZ B-VP O
essentially RB I-VP O
gone VBN I-VP O
on IN B-PP O
oxygen NN B-NP O
. . O O
Vital JJ B-NP O
signs NNS I-NP O
are VBP B-VP O
as RB I-VP O
noted VBN I-VP O
. . O O
Head NNP O O
, , O O
eyes NNS B-NP O
, , O O
ears NNS B-NP O
, , O O
nose NN B-NP O
, , O O
and CC O O
throat NN B-NP O
: : O O
Normocephalic JJ O O
and CC O O
atraumatic JJ B-NP O
. . O O
Pupils NNS B-NP O
are VBP B-VP O
equal JJ B-ADJP O
and CC O O
reactive NN B-NP O
to TO B-PP O
light NN B-NP O
. . O O
Extraocular JJ B-NP O
motions NNS I-NP O
are VBP B-VP O
intact JJ B-ADJP O
. . O O
Oropharynx NNP B-NP O
is VBZ B-VP O
unremarkable JJ B-ADJP O
. . O O
Neck NNP B-NP O
is VBZ B-VP O
supple NN B-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
jugular JJ I-NP O
venous JJ I-NP O
distention NN I-NP O
. . O O
Chest NNP O O
is VBZ O O
clear JJ B-ADJP O
to TO B-PP O
auscultation NN B-NP O
. . O O
Heart NN B-NP O
is VBZ B-VP O
regular JJ B-NP O
rate NN I-NP O
and CC I-NP O
rhythm NN I-NP O
. . O O
His PRP$ O O
abdomen NN B-NP O
is VBZ B-VP O
soft JJ B-ADJP O
and CC I-ADJP O
nontender JJ I-ADJP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
hepatosplenomegaly NN I-NP O
. . O O
There EX B-NP O
are VBP B-VP O
no DT B-NP O
masses NNS I-NP O
. . O O
His PRP$ B-NP O
skin NN I-NP O
is VBZ B-VP O
warm JJ B-ADJP O
and CC I-ADJP O
dry JJ I-ADJP O
. . O O
There EX B-NP O
is VBZ B-VP O
no RB O O
lower JJR B-NP O
extremity NN I-NP O
edema NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
equal JJ B-NP O
pulses NNS I-NP O
. . O O
His PRP$ B-NP O
neuro NN I-NP O
exam NN I-NP O
is VBZ O O
alert JJ B-NP O
and CC I-NP O
oriented JJ I-NP O
to TO B-PP O
person NN B-NP O
, , I-NP O
place NN I-NP O
, , O O
and CC O O
time NN B-NP O
. . O O
His PRP$ B-NP O
cranial NN I-NP O
nerves NNS B-NP O
are VBP B-VP O
intact JJ B-ADJP O
. . O O
He PRP B-NP O
is VBZ B-VP O
grossly RB O O
nonfocal JJ B-ADJP O
. . O O
LABORATORY NNP B-NP O
DATA NNP I-NP O
: : O O
He PRP B-NP O
has VBZ B-VP O
a DT B-NP O
white JJ I-NP O
count NN I-NP O
of IN B-PP O
8 CD B-NP O
, , O O
hematocrit NN B-NP O
of IN B-PP O
46 CD B-NP O
, , O O
and CC O O
platelet NN B-NP O
count NN I-NP O
of IN B-PP O
200,000 CD B-NP O
. . O O
His PRP$ B-NP O
SMA-7 NNP I-NP O
is VBZ B-VP O
unremarkable JJ B-ADJP O
. . O O
CK-MB '' O O
and CC O O
troponin FW B-NP O
are VBP B-VP O
flat JJ B-ADJP O
and CC O O
INR NNP B-NP O
is VBZ B-VP O
1 CD B-NP O
. . O O
His PRP$ B-NP O
EKG NN I-NP O
shows VBZ B-VP O
less JJR B-NP O
than IN I-NP O
1 CD I-NP O
mm CD I-NP O
ST NNP B-NP O
depressions NNS I-NP O
in IN B-PP O
V2 NNP B-NP O
, , O O
without IN B-PP O
any DT B-NP O
reciprocal JJ I-NP O
or CC I-NP O
other JJ I-NP O
changes NNS I-NP O
. . O O
ASSESSMENT NNP B-NP O
: : O O
The DT B-NP O
patient NN I-NP O
with IN B-PP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
CAD NNP B-NP O
with IN B-PP O
concerning VBG B-NP O
symptoms NNS B-NP O
. . O O
He PRP B-NP O
did VBD B-VP O
have VB I-VP O
a DT B-NP O
fight NN I-NP O
earlier RBR B-ADVP O
in IN B-PP O
the DT B-NP O
day NN I-NP O
, , O O
although IN B-SBAR O
was VBD O O
not RB O O
under IN B-PP O
significant JJ B-NP O
stress NN I-NP O
at IN B-PP O
the DT B-NP O
time NN I-NP O
of IN B-PP O
this DT B-NP O
event NN I-NP O
. . O O
Given VBN O O
his PRP$ B-NP O
prior JJ I-NP O
CAD NN I-NP O
history NN I-NP O
, , O O
the DT B-NP O
patient NN I-NP O
was VBD B-VP O
given VBN I-VP O
Lopressor NNP B-NP O
. . I-NP O
Decision NNP I-NP O
was VBD B-VP O
made VBN I-VP O
to TO I-VP O
admit VB I-VP O
him PRP B-NP O
for IN B-PP O
rule NN B-NP O
out IN B-PP O
acute JJ B-NP O
coronary JJ I-NP O
syndrome NN I-NP O
. . O O
The DT O O
patient NN B-NP O
was VBD B-VP O
admitted VBN I-VP O
in IN B-PP O
stable JJ B-NP O
condition NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
had VBD B-LST O
already RB B-ADVP O
got VBD B-VP O
an DT B-NP O
aspirin NN I-NP O
and CC O O
the DT B-NP O
patient NN I-NP O
remained VBD B-VP O
in IN B-PP O
stable JJ B-NP O
condition NN B-NP O
until IN B-SBAR O
he PRP B-NP O
was VBD B-VP O
admitted VBN I-VP O
. . O O
DIAGNOSIS NNP B-NP O
: : O O
Rule NNP B-VP O
out IN B-PRT O
acute JJ B-NP O
coronary JJ I-NP O
syndrome NN I-NP O
. . O O
VELASQUEZ NN B-NP I-DOCTOR
, , O I-DOCTOR
WALTER NNP B-NP I-DOCTOR
M.D. NNP I-NP O
D NNP B-NP O
: : O O
01/31/61 CD O B-DATE
T NNP B-NP O
: : O O
02/01/61 CD O B-DATE
Dictated NNP B-NP O
By IN I-NP O
: : O O
VELASQUEZ NN B-NP I-DOCTOR
, , O I-DOCTOR
WALTER NNP B-NP I-DOCTOR
eScription NN B-NP O
document NN I-NP O
: : O O
9-1137686 CD B-NP B-IDNUM
BFFocus NN I-NP O
******** NN B-NP O
Not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Physician JJ B-NP O
******** NNS I-NP O
