Record NNP B-NP O
date NN I-NP O
: : O O
2070-08-13 CD O B-DATE
Ridgewood NNP B-NP B-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
Intern NNP I-NP O
Admission NNP I-NP O
Note NN I-NP O
CC NNP B-NP O
Chest NNP I-NP O
pain NN I-NP O
HPI . O O
78 CD B-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
with IN B-PP O
PMHx NNP B-NP O
sig NN I-NP O
for IN B-PP O
CHF NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
atrial JJ B-NP O
fibrillation NN I-NP O
( -LRB- I-NP O
cardioverted VBD B-VP O
2/68 CD B-NP B-DATE
, , O O
now RB B-ADVP O
on IN B-PP O
amiodarone JJ B-NP O
) -RRB- I-NP O
, , O O
and CC O O
DM NNP B-NP O
p/w VBD B-VP O
increased VBN I-VP O
SOB NNP B-NP O
and CC I-NP O
chest NN I-NP O
pain NN I-NP O
over IN B-PP O
1 CD B-NP O
weeks NNS I-NP O
time NN I-NP O
. . B-NP O
Symptoms NNS I-NP O
not RB B-VP O
related VBN I-VP O
to TO B-PP O
exertion NN B-NP O
and CC O O
reports VBZ B-VP O
sternal JJ B-NP O
area NN I-NP O
is VBZ B-VP O
the DT B-NP O
location NN I-NP O
of IN B-PP O
pain NN B-NP O
. . O O
Occurs '' O O
at IN B-PP O
rest NN B-NP O
. . O O
Feels NNS B-VP O
like IN B-PP O
pressure NN B-NP O
and CC B-PP O
at IN B-PP O
times NNS B-NP O
sharp JJ B-NP O
pain NN I-NP O
, , O O
not RB B-VP O
related VBN I-VP O
to TO B-PP O
respiration NN B-NP O
. . O O
7/10 CD O O
when WRB B-ADVP O
maximal JJ B-NP O
intensity NN I-NP O
. . O O
Pain NNP B-NP O
is VBZ B-VP O
constant JJ B-ADJP O
in IN B-PP O
nature NN B-NP O
, , O O
patient JJ B-NP O
states NNS I-NP O
lasting VBG B-VP O
up RP B-PRT O
to TO B-PP O
hours NNS B-NP O
at IN B-PP O
a DT B-NP O
time NN I-NP O
. . O O
No DT B-NP O
specific JJ I-NP O
provocative NN I-NP O
or CC O O
palliative JJ B-NP O
factors NNS I-NP O
. . O O
Not RB B-VP O
related VBN I-VP O
to TO B-PP O
position NN B-NP O
. . O O
Reports NNPS B-NP O
that IN B-PP O
SOB NNP B-NP O
and CC I-NP O
chest NN I-NP O
pain NN I-NP O
are VBP B-VP O
chronic JJ B-NP O
problems NNS I-NP O
for IN B-PP O
her PRP B-NP O
and CC O O
the DT B-NP O
reason NN I-NP O
she PRP B-NP O
presented VBD B-VP O
to TO B-PP O
the DT B-NP O
ED NNP I-NP O
is VBZ B-VP O
because IN B-SBAR O
the DT B-NP O
symptoms NNS I-NP O
have VBP B-VP O
increased VBN I-VP O
over IN B-PP O
the DT B-NP O
past JJ I-NP O
week NN I-NP O
. . O O
No DT B-NP O
associated JJ I-NP O
symptoms NNS I-NP O
of IN B-PP O
N/V NNP B-NP O
or CC I-NP O
diaphoresis NN I-NP O
. . O O
Reports NNS B-VP O
occasional JJ B-NP O
palpitations NNS I-NP O
. . O O
Patient NNP B-NP O
also RB B-ADVP O
feels VBZ B-VP O
pain NN B-NP O
in IN B-PP O
her PRP$ B-NP O
back NN I-NP O
, , O O
shoulders NNS B-NP O
, , O O
and CC O O
arms NNS B-NP O
which WDT B-NP O
she PRP B-NP O
attributes VBZ B-VP O
to TO B-PP O
her PRP$ B-NP O
arthritis NN I-NP O
and CC O O
not RB B-NP O
radiation NN I-NP O
of IN B-PP O
the DT B-NP O
pain NN I-NP O
. . B-NP O
States NNPS I-NP O
that IN B-SBAR O
she PRP B-NP O
sleeps VBZ B-VP O
on IN B-NP O
4 CD I-NP O
pillows NNS I-NP O
and CC O O
this DT B-NP O
does VBZ B-VP O
represent VB I-VP O
on IN B-PP O
acute JJ B-NP O
change NN I-NP O
. . O O
Denies NNS B-NP O
fever/chills NNS I-NP O
. . O O
Reports NNS B-VP O
constipation NN B-NP O
at IN B-PP O
baseline NN B-NP O
( -LRB- I-NP O
BMs NNS I-NP O
do VBP B-VP O
not RB I-VP O
occur VB I-VP O
everyday JJ B-NP O
) -RRB- I-NP O
. . B-PP O
Patient NNP B-NP O
states NNS I-NP O
she PRP B-NP O
has VBZ B-VP O
frequent JJ B-ADJP O
sinus IN B-PP O
infections NNS B-NP O
. . O O
PMHx NN B-NP O
HTN NNP B-NP O
, , O O
CHF NNP B-NP O
( -LRB- I-NP O
good JJ I-NP O
systolic NN I-NP O
function NN I-NP O
though IN B-PP O
) -RRB- B-NP O
, , O O
Afib NNP B-NP O
( -LRB- I-NP O
past NN I-NP O
cardioversion NN I-NP O
Feb. NNP B-NP B-DATE
2068 CD I-NP I-DATE
) -RRB- I-NP O
, , O O
DM . O O
Pulmonary JJ B-NP O
embolism NN I-NP O
- : O O
bilateral NN B-NP O
, , O O
treated VBN B-VP O
at IN B-PP O
Buzan NNP B-NP B-HOSPITAL
County NNP I-NP I-HOSPITAL
Clinic NNP I-NP I-HOSPITAL
( -LRB- I-NP O
CT NN I-NP O
with IN B-PP O
multiple JJ B-NP O
filling NN I-NP O
defects NNS I-NP O
in IN B-PP O
LLL NNP B-NP O
, , O O
RUL NNP B-NP O
, , O O
RLL NNP B-NP O
c/w VBD B-VP O
PE) NNP B-NP O
, , O O
non-Q JJ B-NP O
wave NN I-NP O
MI NNP B-VP O
with IN B-PP O
inferolateral JJ B-NP O
apical JJ I-NP O
depressoins NNS I-NP O
at IN B-PP O
Buzan NNP B-NP B-HOSPITAL
County NNP I-NP I-HOSPITAL
Clinic NNP I-NP I-HOSPITAL
6/69 CD I-NP B-DATE
; : O O
RSH NNP B-NP B-HOSPITAL
admission NN I-NP O
5/17/70 IN B-PP B-DATE
with IN B-NP O
D-dimer=1976 CD I-NP O
, , O O
CT NNP B-NP O
negative JJ I-NP O
for IN B-PP O
PE NN B-NP O
and CC I-NP O
DVT NN I-NP O
Osteoarthritis NNP B-NP O
, , I-NP O
anxiety NN I-NP O
, , I-NP O
depression NN I-NP O
with IN B-PP O
psychotic JJ B-NP O
features NNS I-NP O
, , O O
lumbar NN B-NP O
disc NN I-NP O
disease NN I-NP O
( -LRB- I-NP O
s/p NN I-NP O
surgical JJ I-NP O
repairs NNS I-NP O
) -RRB- I-NP O
, , O O
Echo NNP B-NP O
: : O O
5/21/70 CD B-NP B-DATE
: : O O
The DT B-NP O
left JJ I-NP O
ventricular JJ I-NP O
systolic JJ I-NP O
function NN I-NP O
within IN B-PP O
normal JJ B-NP O
limits NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
segmental JJ B-NP O
left JJ I-NP O
ventricular JJ I-NP O
dysfunction NN I-NP O
which WDT B-NP O
involves VBZ B-VP O
the DT B-NP O
inferior JJ I-NP O
territory NN I-NP O
, , O O
this DT B-NP O
has VBZ B-VP O
deceased JJ B-NP O
sine FW I-NP O
12/68 CD I-NP B-DATE
study NN I-NP O
. . O O
The DT B-NP O
estimated VBN I-NP O
ejection NN I-NP O
fraction NN I-NP O
is VBZ B-VP O
57 CD B-NP O
% NN I-NP O
. . O O
Estimated VBN B-VP O
RV NN I-VP O
systolic JJ B-NP O
pressure NN I-NP O
is VBZ B-VP O
89 CD B-NP O
mmHg NN I-NP O
. . O O
Right RB B-ADVP O
ventricular VBD B-VP O
systolic JJ B-NP O
function NN I-NP O
is VBZ B-VP O
within IN B-PP O
normal JJ B-NP O
limits NNS I-NP O
. . O O
Stress NNP B-NP O
The DT B-NP O
ECG JJ I-NP O
response NN I-NP O
to TO B-PP O
pharmacological JJ B-NP O
stress NN I-NP O
was VBD B-VP O
uninterpretable JJ B-ADJP O
for IN B-PP O
ischemia NN B-NP O
. . O O
The DT B-NP O
myocardial JJ I-NP O
scans NNS I-NP O
are VBP B-VP O
within IN B-PP O
normal JJ B-NP O
limits NNS I-NP O
and CC O O
do VBP B-VP O
not RB I-VP O
demonstrate VB I-VP O
evidence NN B-NP O
of IN B-PP O
myocardial JJ B-NP O
ischemia NN I-NP O
or CC I-NP O
infarction NN I-NP O
. . O O
Region( NN B-NP O
s VBZ B-VP O
) -RRB- B-NP O
with IN B-PP O
apparent JJ B-NP O
reduction NN I-NP O
in IN B-PP O
tracer NN B-NP O
activity NN I-NP O
likely JJ B-NP O
reflect VBP B-VP O
soft JJ B-NP O
tissue NN I-NP O
attenuation NN I-NP O
, , O O
not RB O O
specific JJ B-ADJP O
for IN B-PP O
coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
. . O O
LVEF=64 CD B-NP O
% NN I-NP O
. . O O
PE NN B-NP O
protocol NN I-NP O
CT NNP B-NP O
5/70 CD I-NP B-DATE
: : O O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
pulmonary JJ B-NP O
embolism NN I-NP O
. . O O
Delayed DT B-NP O
venogram NN I-NP O
of IN B-PP O
the DT B-NP O
pelvis NNS I-NP O
and CC O O
lower JJR B-NP O
extremities NNS I-NP O
demonstrates VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
of IN I-PP O
DVT. NNP B-NP O
A DT B-NP O
2.2 CD I-NP O
x NN I-NP O
1.4 CD I-NP O
cm NN I-NP O
nodule NN I-NP O
is VBZ B-VP O
identified VBN I-VP O
on IN B-PP O
image NN B-NP O
112 CD I-NP O
in IN B-PP O
the DT B-NP O
right JJ I-NP O
upper JJ I-NP O
lobe NN I-NP O
. . O O
In IN B-PP O
addition NN B-NP O
, , O O
there EX B-NP O
is VBZ B-VP O
ground NN B-NP O
glass NN I-NP O
opacity NN I-NP O
involving VBG B-VP O
the DT B-NP O
bilateral JJ I-NP O
lungs NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
interstitial JJ B-NP O
pulmonary JJ I-NP O
edema NN I-NP O
and CC O O
a DT B-NP O
small JJ I-NP O
right JJ I-NP O
pleural JJ I-NP O
effusion NN I-NP O
. . O O
5/23 CD B-NP B-DATE
Chest NNP I-NP O
CT NNP I-NP O
: : O O
previously RB B-NP O
demonstrated VBN I-NP O
nodule NN I-NP O
in IN B-PP O
the DT B-NP O
right JJ I-NP O
upper JJ I-NP O
lung NN I-NP O
measuring VBG B-VP O
17 CD B-NP O
mm CD I-NP O
x NN I-NP O
11 CD I-NP O
mm CD I-NP O
has VBZ B-VP O
resolved VBN I-VP O
. . O O
MED NNS B-NP O
Amiodarone NNP B-NP O
200 CD I-NP O
qD NNP I-NP O
Premarin NNP I-NP O
0.625 CD I-NP O
qD . O O
ASA NNP B-NP O
81 CD I-NP O
qD NN I-NP O
Provera NNP B-NP O
2.5 CD I-NP O
mg NN I-NP O
qD NN I-NP O
Atenolol NNP B-NP O
25 CD I-NP O
qD NNS I-NP O
Tylenol NNP I-NP O
500 CD I-NP O
tid NN I-NP O
PRN NN I-NP O
Lasix NNP B-NP O
40 CD I-NP O
bid NN I-NP O
Ibuprofen IN B-PP O
600 CD B-NP O
q8 CD I-NP O
PRN NN I-NP O
Glucophage NNP B-NP O
500 CD I-NP O
bid NN I-NP O
Colace NNP B-NP O
100 CD I-NP O
tid JJ I-NP O
pRN NN I-NP O
Nexium NNP B-NP O
40 CD I-NP O
qD NN I-NP O
Neurontin NNP B-NP O
100 CD I-NP O
tid NN I-NP O
Celexa NNP B-NP O
40 CD I-NP O
qD NN I-NP O
ALL NNP B-NP O
Haldol NNP B-NP O
- : O O
unknown JJ B-NP O
reaction NN I-NP O
SHx NN B-NP O
Lives NNS B-NP O
alone RB B-ADVP O
, , O O
upstairs NN B-NP O
from IN B-PP O
her PRP$ B-NP O
nieces NNS I-NP O
( -LRB- B-VP O
Carpenter NNP B-NP B-PATIENT
815-009-5048 CD I-NP B-PHONE
) -RRB- I-NP O
. . O O
VNA NNP B-NP O
visits NNS I-NP O
2x/week VBP B-VP O
organizes NNS B-NP O
medications NNS B-PP O
which WDT B-NP O
patient NN I-NP O
then RB B-ADVP O
takes VBZ B-VP O
herself PRP B-NP O
. . O O
Receives NNPS O O
Community NNP B-NP B-ORGANIZATION
Means NNPS I-NP I-ORGANIZATION
and CC I-NP O
family NN I-NP O
helps VBZ B-VP O
with IN B-PP O
shopping NN B-NP O
. . O O
Receives NNPS O O
PT NNP B-NP O
at IN B-PP O
home NN B-NP O
. . O O
Ambulates NNS B-VP O
with IN B-PP O
a DT B-NP O
walker NN I-NP O
at IN B-PP O
baseline NN B-NP O
. . O O
Smoking VBG B-VP O
: : O O
denies VBZ O O
Alcohol NN B-NP O
: : O O
denies VBZ O O
IVDU NNP B-NP O
: : O O
none NN B-NP O
FHx NN B-NP O
Denies NNS B-NP O
In IN B-PP O
ED NNP B-NP O
, , I-NP O
T=98.6 CD I-NP O
, , I-NP O
HR=90 CD I-NP O
, , O O
BP=174/96 NNP B-NP O
, , O O
RR=18 CD B-NP O
, , O O
94 CD B-NP O
%RA NN I-NP O
96 CD B-NP O
%2L JJ I-NP O
; : O O
Received JJ B-NP O
Lasix NNP I-NP O
20 CD I-NP O
IV NNP I-NP O
, , I-NP O
ASA NNP I-NP O
, , I-NP O
Albuterol/Atrovent NNP I-NP O
Nebs NNP I-NP O
, , O O
Magnesium NNP B-NP O
2g CD I-NP O
x1 CD I-NP O
, , O O
and CC O O
Insulin NNP B-NP O
6 CD I-NP O
units NNS I-NP O
. . O O
PE NN B-NP O
VS NNP B-NP O
Temp NNP I-NP O
: : O O
97.8 CD B-NP O
BP NNP I-NP O
: : O O
140/8 CD B-NP O
2 CD I-NP O
HR NN I-NP O
: : O O
80 CD B-NP O
RR NN I-NP O
: : O O
26 CD B-NP O
Sat NNP I-NP O
:99 CD I-NP O
% NN I-NP O
2L . O O
GEN NNP B-NP O
NAD NNP I-NP O
, , O O
wearing VBG B-VP O
a DT B-NP O
hair NN I-NP O
piece NN I-NP O
HEENT NNP B-NP O
PERRL NNP I-NP O
, , O O
EOMI NNP B-NP O
, , O O
anicteric JJ B-ADJP O
, , O O
no DT B-NP O
erythema/exudates VBZ B-VP O
posterior JJ B-NP O
pharynx NN I-NP O
NECK NNP B-NP O
JVP NNP I-NP O
elevated VBD B-VP O
, , O O
no DT B-NP O
LAD NN I-NP O
CHEST NNP B-NP O
bilateral JJ I-NP O
crackles NNS I-NP O
1/3 IN B-PP O
of IN B-PP O
the DT B-NP O
way NN I-NP O
up IN B-PP O
the DT B-NP O
lung NN I-NP O
fields NNS I-NP O
, , O O
otherwise RB B-ADVP O
clear JJ B-ADJP O
, , O O
no DT B-NP O
wheezes NNS I-NP O
HEART NNP B-NP O
RRR NNP I-NP O
, , O O
no DT B-NP O
m/r/g NN I-NP O
ABD NNP B-NP O
+BS NNP I-NP O
, , O O
soft JJ B-ADJP O
, , O O
NTND NNP B-NP O
, , O O
no DT B-NP O
masses NNS I-NP O
EXT NNP B-NP O
1+ CD I-NP O
edema NN I-NP O
above IN B-PP O
the DT B-NP O
ankles NNS I-NP O
, , O O
pulses NNS B-NP O
equal JJ B-NP O
b/l NN I-NP O
SKIN JJ B-NP O
no DT I-NP O
rashes NNS I-NP O
or CC I-NP O
lesions NNS I-NP O
RECTAL NNP B-NP O
Guaiac NNP I-NP O
neg NN I-NP O
but CC O O
minimal JJ B-NP O
stool NN I-NP O
in IN B-PP O
vault NN B-NP O
, , O O
2mm JJ B-NP O
erosion NN I-NP O
on IN B-PP O
buttocks NNS B-NP O
NEURO NNP B-NP O
AAOx3 NNP I-NP O
, , O O
( -LRB- B-NP O
initially RB I-NP O
states NNS I-NP O
year NN I-NP O
is VBZ B-VP O
2087 CD B-NP B-DATE
, , O O
than IN B-PP O
corrects NNS B-NP O
, , O O
day/month NN B-NP O
accurate JJ I-NP O
No DT B-NP O
facial JJ I-NP O
droop NN I-NP O
, , O O
no DT B-NP O
tongue NN I-NP O
deviation NN I-NP O
, , O O
uvula NN B-NP O
elevated VBD B-VP O
midline NN B-NP O
Sensory NNP B-NP O
intact JJ I-NP O
Motor NNP B-NP O
strength NN I-NP O
5/5 VBD B-VP O
throughou VBN I-VP O
. . O O
LABS . O O
WBC NN B-NP O
8.8 CD I-NP O
4.5-11.0 CD I-NP O
th/cmm . O O
HCT NNP B-NP O
37.0 CD I-NP O
36.0-46.0 CD I-NP O
% NN I-NP O
HGB NNP B-NP O
12.1 CD I-NP O
12.0-16.0 CD I-NP O
gm/dl NN I-NP O
RBC NNP B-NP O
4.57 CD I-NP O
4.00-5.20 CD I-NP O
mil/cmm . O O
PLT NNP B-NP O
261 CD I-NP O
150-350 CD I-NP O
th/cumm . O O
MCV NNP B-NP O
81 CD I-NP O
80-100 CD I-NP O
fl NN I-NP O
MCH NNP B-NP O
26.5 CD I-NP O
26.0-34.0 CD I-NP O
pg/rbc NN I-NP O
MCHC NNP B-NP O
32.7 CD I-NP O
31.0-37.0 CD I-NP O
g/dl NN I-NP O
RDW NNP B-NP O
15.0 CD I-NP O
H NNP I-NP O
11.5-14.5 CD I-NP O
% NN I-NP O
Superstat NNP B-NP O
PT NNP I-NP O
13.6 CD I-NP O
H NNP I-NP O
11.1-13.1 CD I-NP O
sec NN I-NP O
Superstat NNP B-NP O
APTT NNP I-NP O
23.2 CD I-NP O
22.1-35.1 CD I-NP O
sec NN I-NP O
DIFFERENTIAL NNP B-NP O
REQUEST NNP I-NP O
RECEIVED NNP I-NP O
Diff JJ B-NP O
Method NNP I-NP O
Auto NN I-NP O
Poly NNP B-NP O
72 CD I-NP O
H NNP I-NP O
40-70 CD I-NP O
% NN I-NP O
Lymphs NNP B-NP O
20 CD I-NP O
L NNP I-NP O
22-44 CD I-NP O
% NN I-NP O
Monos NNP B-NP O
4 CD I-NP O
4-11 CD I-NP O
% NN I-NP O
EOS NNS B-NP O
3 CD B-NP O
0-8 CD I-NP O
% NN I-NP O
Basos NNS B-NP O
1 CD B-NP O
0-3 CD I-NP O
% NN I-NP O
Absolute JJ B-NP O
Neuts NNP I-NP O
6.40 CD I-NP O
1.8-7.7 CD I-NP O
th/cmm . O O
Absolute JJ B-NP O
Lymphs NNP I-NP O
1.79 CD I-NP O
1.0-4.8 CD I-NP O
th/cmm . O O
Absolute JJ B-NP O
Monos NNP I-NP O
0.32 CD I-NP O
0.2-0.4 CD I-NP O
th/cmm . O O
Absolute JJ B-NP O
EOS NNP I-NP O
0.22 CD I-NP O
0.1-0.3 CD I-NP O
th/cmm . O O
Absolute JJ B-NP O
Basos NNP I-NP O
0.06 CD I-NP O
0.0-0.3 CD I-NP O
th/cmm . O O
Aniso NNP B-NP O
None NN I-NP O
NORMAL NNP I-NP O
Hypo NNP B-NP O
2+ CD I-NP O
NORMAL NNP I-NP O
Macrocytes NNP B-NP O
None NN I-NP O
Microcytes NNS B-NP O
None NN I-NP O
Sodium NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
135 CD I-NP O
135-145 CD I-NP O
mmol/L . O O
Potassium NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- O O
4.6 CD B-NP O
3.4-4.8 CD I-NP O
mmol/L NN I-NP O
Result NN B-NP O
Text NNP I-NP O
: : O O
SLIGHTLY NNP B-NP O
HEMOLYZED NNP I-NP O
Chloride NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
104 CD I-NP O
100-108 CD I-NP O
mmol/L NNS I-NP O
CO2 NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
21.8 CD I-NP O
L NNP B-NP O
23.0-31.9 CD I-NP O
mmol/L . O O
BUN NNP B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
11 CD I-NP O
8-25 CD I-NP O
mg/dl NN I-NP O
Creatinine NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
1.0 CD I-NP O
0.6-1.5 CD I-NP O
mg/dl NN I-NP O
Glucose FW B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NN I-NP O
) -RRB- I-NP O
296 CD I-NP O
H NNP B-NP O
70-110 CD I-NP O
mg/dl . O O
Calcium NNP B-NP O
8.9 CD I-NP O
8.5-10.5 CD I-NP O
mg/dl NN I-NP O
Phosphorus NNP B-NP O
3.2 CD I-NP O
2.6-4.5 CD I-NP O
mg/dl NN I-NP O
Magnesium NNP B-NP O
1.3 CD I-NP O
L NNP B-NP O
1.4-2.0 CD I-NP O
meq/L . O O
Total JJ B-NP O
Protein NNP I-NP O
7.8 CD I-NP O
6.0-8.3 CD I-NP O
g/dl NN I-NP O
Albumin NNP B-NP O
3.0 CD I-NP O
L NNP I-NP O
3.3-5.0 CD I-NP O
g/dl NN I-NP O
Globulin NNP B-NP O
4.8 CD I-NP O
H NNP B-NP O
2.6-4.1 CD I-NP O
g/dl . O O
Direct JJ B-NP O
Bilirubin NNP I-NP O
<0.1 CD I-NP O
0-0.4 CD I-NP O
mg/dl NN I-NP O
Total JJ B-NP O
Bilirubin NNP I-NP O
0.5 CD I-NP O
0-1.0 CD I-NP O
mg/dl NN I-NP O
Alkaline NN B-NP O
Phosphatase NNP I-NP O
69 CD I-NP O
30-100 CD I-NP O
U/L . O O
Transaminase-SGPT NNP B-NP O
19 CD I-NP O
7-30 CD I-NP O
U/L . O O
Creatine JJ B-NP O
Kinase NNP I-NP O
Isoenz NNP I-NP O
2.2 CD I-NP O
0.0-6.9 CD I-NP O
ng/ml CC O O
CPK NNP B-NP O
Isoenzymes NNP I-NP O
Index NNP I-NP O
0.0-3.5 CD I-NP O
% NN I-NP O
Result NN B-NP O
Text NNP I-NP O
: : O O
CPK NNP B-NP O
and/or CC I-NP O
CKMB NNP I-NP O
too RB I-NP O
low JJ B-ADJP O
to TO B-VP O
calculate VB I-VP O
Relative NNP B-NP O
Index NNP I-NP O
. . O O
Troponin-T NNP B-NP O
REFUSED NNP I-NP O
0.00-0.09 CD I-NP O
ng/ml NN I-NP O
Result NN B-NP O
Text NNP I-NP O
: : O O
HEMOLYZED NNP B-NP O
SPECIMEN NNP I-NP O
Transaminase-SGOT NNP B-NP O
60 CD I-NP O
H NNP B-NP O
9-32 CD I-NP O
U/L . O O
Creatine NNP B-NP O
Kinase NNP I-NP O
62 CD I-NP O
40-150 CD I-NP O
U/L . O O
D-Dimer NN B-NP O
( -LRB- I-NP O
ELISA NNP I-NP O
) -RRB- I-NP O
2257 CD I-NP O
H NNP B-NP O
<500 CD I-NP O
ng/ml . O O
UA-Color NNP B-NP O
Yellow NNP I-NP O
YELLOW NNP I-NP O
UA-Turbidity NN B-NP O
CLOUDY NN I-NP O
CLEAR NN I-NP O
UA-Glucose JJ B-NP O
1+ CD I-NP O
NEG . O O
UA-Bili JJ B-NP O
NEGATIVE JJ I-NP O
NEG NN I-NP O
UA-Ketones NNP B-NP O
NEGATIVE JJ I-NP O
NEG NN I-NP O
UA-Specific JJ B-NP O
Gravity NNP I-NP O
1.024 CD I-NP O
1.001-1.035 CD O O
UA-Occult JJ B-NP O
Blood NN I-NP O
Trace NNP I-NP O
NEG NNP I-NP O
UA-pH NNP B-NP O
5.5 CD I-NP O
5.0-9.0 CD O O
UA-Albumin NNP B-NP O
3+ CD I-NP O
NEG . O O
UA-Urobilinogen JJ B-NP O
NEGATIVE JJ I-NP O
NEG NN I-NP O
UA-Nitrite JJ B-NP O
NEGATIVE JJ I-NP O
NEG NN I-NP O
UA-WBC NNP B-NP O
Screen NNP I-NP O
NEGATIVE NNP I-NP O
NEG NNP I-NP O
UA-SED-RBC NNP B-NP O
0-2 CD I-NP O
0-2 CD I-NP O
/hpf NN I-NP O
UA-SED-WBC NNP B-NP O
5-10 CD I-NP O
0-2 CD I-NP O
/hpf NN I-NP O
UA-SED-Bacteria NNP B-NP O
Few JJ I-NP O
NEG NNP I-NP O
/hpf NN I-NP O
Hyaline NNP B-NP O
Cast NNP I-NP O
0-2 CD I-NP O
0-5 CD I-NP O
/lpf NN I-NP O
Granular NNP B-NP O
Cast NNP I-NP O
0-2 CD I-NP O
NEG NNP I-NP O
/lpf NN I-NP O
Squamous NNP B-NP O
Cells NNP I-NP O
Moderate NNP I-NP O
NEG NNP I-NP O
/hpf NN I-NP O
Amorphous JJ B-NP O
Crystals NNS I-NP O
Few JJ B-NP O
NEG NNP I-NP O
/hpf NN I-NP O
Microscopic NNP B-NP O
Sediment NNP I-NP O
Completed NNP I-NP O
EKG NNP B-NP O
Sinus NNP I-NP O
tachycardia NN I-NP O
@110 CD B-NP O
, , O O
LBBB NNP B-NP O
( -LRB- I-NP O
present NN I-NP O
on IN B-PP O
old JJ B-NP O
EKG NN I-NP O
) -RRB- O O
CXR NNP B-NP O
Focal NNP I-NP O
vascular JJ I-NP O
redistribution NN I-NP O
and CC O O
some DT B-NP O
interstitial JJ I-NP O
opacities NNS I-NP O
; : O O
Mild NNP B-NP O
pulmonary , O O
edema NN B-NP O
similar JJ B-ADJP O
to TO B-PP O
prior JJ B-NP O
exam NN I-NP O
. . O O
CT NNP B-NP O
PE NN I-NP O
protocol NN I-NP O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
78 CD B-NP B-AGE
F NNP I-NP O
h/o NN I-NP O
CHF NNP I-NP O
( -LRB- I-NP O
diastolic JJ I-NP O
dysfunction NN I-NP O
) -RRB- I-NP O
, , O O
Afib NNP B-NP O
( -LRB- I-NP O
s/p NN I-NP O
cardioversion NN I-NP O
) -RRB- I-NP O
, , I-NP O
HTN NNP I-NP O
, , I-NP O
DM NNP I-NP O
, , I-NP O
past IN B-PP O
b/l JJ B-NP O
PE NN I-NP O
presents NNS I-NP O
with IN B-PP O
increased JJ B-NP O
CP CD I-NP O
and CC I-NP O
SOB NNP I-NP O
times NNS I-NP O
week NN I-NP O
. . O O
Differential JJ B-ADVP O
includes VBZ B-VP O
CHF NN B-NP O
exacerbation NN I-NP O
( -LRB- O O
? . O O
Setting NNP B-NP O
of IN B-PP O
med JJ B-NP O
noncompliance NN I-NP O
) -RRB- I-NP O
, , I-NP O
ACS NNP I-NP O
, , I-NP O
PE. . O O
1)PE VB B-VP O
- : O O
D-dimer NN B-NP O
is VBZ B-VP O
2257 CD B-NP O
; : O O
Heparin NNP B-NP O
6000 CD I-NP O
unit NN I-NP O
bolus JJ B-ADJP O
, , O O
1000 CD B-NP O
unit/hr NN I-NP O
with IN B-PP O
sliding VBG B-VP O
scale NN B-NP O
; : O O
PE NN B-NP O
protocol NN I-NP O
CT NNP I-NP O
; : O O
Continue NNP B-NP O
to TO B-VP O
hold VB I-VP O
Metformin NNP B-NP O
, , O O
received VBD B-VP O
600mg JJ B-NP O
Mucomyst NNP I-NP O
in IN B-PP O
preparation NN B-NP O
for IN B-PP O
dye JJ B-NP O
load NN I-NP O
and CC O O
continue VBP B-VP O
2 CD B-NP O
doses VBZ B-VP O
post NN B-NP O
scan NN I-NP O
; : O O
Preliminary NNP B-NP O
CT NNP I-NP O
read VBD B-VP O
: : O O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
PE NN B-NP O
although IN B-PP O
limited JJ B-NP O
by IN B-PP O
motion NN B-NP O
artifact NN I-NP O
; : O O
ground NN B-NP O
glass NN I-NP O
changes NNS I-NP O
c/w RB B-ADVP O
with IN B-PP O
CHF NNP B-NP O
; : O O
Continue NNP B-NP O
Heparin NNP I-NP O
as IN B-PP O
pt NN B-NP O
. . O O
with IN B-PP O
h/o NN B-NP O
PE NN I-NP O
and CC O O
awaiting VBG B-VP O
final JJ B-NP O
CT NNP I-NP O
read VBD B-VP O
. . O O
2 CD B-NP O
) -RRB- O O
r/o VB B-VP O
MI NNP B-NP O
- : O O
Enzymes NNS B-NP O
negative JJ B-NP O
x2 NN I-NP O
; : O O
ASA NNP B-NP O
, , O O
O2 NNP B-NP O
; : O O
B-blocker NNP B-NP O
continued VBD B-VP O
( -LRB- B-NP O
no DT I-NP O
evidence NN I-NP O
of IN B-PP O
systolic JJ B-NP O
dysfunction NN I-NP O
) -RRB- I-NP O
; : O O
Received JJ B-NP O
ACE NNP I-NP O
( -LRB- I-NP O
Zestril NN I-NP O
x1 NN I-NP O
) -RRB- I-NP O
, , O O
now RB B-ADVP O
hold VBP B-VP O
in IN B-PP O
setting NN B-NP O
of IN B-PP O
dye JJ B-NP O
load NN I-NP O
3 CD B-NP O
) -RRB- I-NP O
CHF NNP I-NP O
- : O O
strict JJ B-NP O
I&Os NNS I-NP O
, , O O
daily JJ B-NP O
weight NN I-NP O
, , O O
no DT B-NP O
salt NN I-NP O
diet NN I-NP O
; : O O
exam NN B-NP O
reveals VBZ B-VP O
slight JJ B-NP O
fluid NN I-NP O
overload RB B-ADVP O
, , O O
after IN B-PP O
initial JJ B-NP O
diuresis NN I-NP O
( -LRB- I-NP O
Lasix NNP I-NP O
20 CD I-NP O
IV NNP I-NP O
x2 NN I-NP O
) -RRB- I-NP O
will MD B-VP O
hold VB I-VP O
in IN B-PP O
light NN B-NP O
of IN B-PP O
CT JJ B-NP O
w JJ I-NP O
contrast NN I-NP O
, , O O
monitor VBP B-VP O
fluid NN B-NP O
status NN I-NP O
, , O O
no DT B-NP O
IVF NN I-NP O
at IN B-PP O
this DT B-NP O
time NN I-NP O
4 CD B-NP O
) -RRB- I-NP O
DM NNPS I-NP O
- : O O
hold VBP B-VP O
Metformin NNP B-NP O
, , O O
on IN B-PP O
Insulin NNP B-NP O
SS NNP I-NP O
with IN B-PP O
bid NN B-NP O
coverage NN I-NP O
5 CD B-NP O
) -RRB- I-NP O
Urine NNP I-NP O
- : O O
negative JJ B-NP O
nitrite/WBC NN I-NP O
, , O O
sediment NN B-NP O
5-10 CD I-NP O
WBCs NNS I-NP O
, , O O
few JJ B-NP O
bacteria NNS I-NP O
; : O O
Likely JJ B-NP O
asymptomatic JJ I-NP O
bacteruria NNS I-NP O
in IN B-PP O
elderly JJ B-NP O
patient NN I-NP O
, , O O
afebrile JJ B-ADVP O
, , O O
no DT B-NP O
increased VBD B-VP O
WBC NNP B-NP O
, , O O
therefore RB B-ADVP O
no DT B-NP O
treatment NN I-NP O
at IN B-PP O
this DT B-NP O
time NN I-NP O
. . O O
Prophylaxis NNP B-NP O
: : O O
-- : O O
Nexium NNP B-NP O
Dispo NNP B-NP O
: : O O
-- : O O
Ambulate NNP B-NP O
, , O O
PT/OT NNP B-NP O
Code NNP B-NP O
: : O O
-- : O O
Unknown JJ O O
Yuri NNP B-NP B-DOCTOR
Poole NNP I-NP I-DOCTOR
, , O O
MD . O O
73130 CD O B-PHONE
