Record NNP B-NP O
date NN I-NP O
: : O O
2065-10-20 CD O B-DATE
GRANITE NNP B-NP B-HOSPITAL
EMERGENCY NNP I-NP O
DEPT NNP I-NP O
VISIT NNP I-NP O
BIRD,TERR NNP B-NP I-PATIENT
I PRP B-NP I-PATIENT
809-10-69-0 CD B-NP B-MEDICALRECORD
VISIT NNP I-NP O
DATE NNP I-NP O
: : O O
10/20/65 CD O B-DATE
PRESENTING JJ B-NP O
COMPLAINT NNP I-NP O
: : O O
HISTORY NN B-NP O
OF IN B-PP O
PRESENTING JJ B-NP O
COMPLAINT NN I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
a DT B-NP O
70 CD I-NP B-AGE
year NN I-NP O
old JJ I-NP O
female NN B-NP O
with IN B-PP O
long JJ B-NP O
past JJ I-NP O
medical JJ I-NP O
history NN I-NP O
of IN B-PP O
medical JJ B-NP O
problems NNS I-NP O
, , O O
including VBG B-PP O
abdominal JJ B-NP O
aortic JJ I-NP O
aneurysm NN I-NP O
repair NN I-NP O
, , O O
chronic JJ B-NP O
pneumonia NN I-NP O
, , O O
chronic NN B-NP O
wound NN I-NP O
infection NN I-NP O
, , O O
history NN B-NP O
of IN B-PP O
chronic JJ B-NP O
urinary JJ I-NP O
tract NN I-NP O
infections NNS B-NP O
, , O O
change NN B-NP O
in IN B-PP O
mental JJ B-NP O
status NN I-NP O
, , O O
peripheral JJ B-NP O
vascular JJ I-NP O
disease NN I-NP O
, , O O
hypertension NN B-NP O
, , O O
and CC O O
coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
was VBD B-VP O
in IN B-PP O
her PRP$ B-NP O
usual JJ B-NP O
state NN I-NP O
of IN B-PP O
poor JJ B-NP O
health NN I-NP O
when WRB B-ADVP O
she PRP B-NP O
was VBD B-VP O
noticed VBN I-VP O
by IN B-PP O
caregivers NNS B-NP O
to TO B-VP O
be VB I-VP O
confused VBN B-NP O
and CC I-NP O
lethargic JJ I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
was VBD B-VP O
transferred VBN I-VP O
to TO B-PP O
the DT B-NP O
emergency NN B-NP O
room NN I-NP O
department NN I-NP O
. . O O
REVIEW NN B-NP O
OF IN B-PP O
SYSTEMS NNP B-NP O
: : O O
PAST NN B-NP O
MEDICAL NNP I-NP O
HISTORY NNP I-NP O
: : O O
MEDICATIONS NNS B-NP O
: : O O
Unknown JJ B-NP O
medications NNS I-NP O
at IN B-PP O
this DT B-NP O
time NN I-NP O
. . O O
ALLERGIES NNS B-NP O
: : O O
Sulfa NNP B-NP O
and CC O O
penicillin VBG B-VP O
. . B-NP O
Aspirin NNP I-NP O
and CC O O
all DT B-NP O
cephalosporins NNS I-NP O
. . O O
SOCIAL JJ B-NP O
HISTORY NN I-NP O
AND CC O O
FAMILY JJ B-NP O
HISTORY NN I-NP O
: : O O
PHYSICAL NNP B-NP O
EXAMINATION NNP I-NP O
: : O O
Temperature NN B-NP O
101.6 CD I-NP O
degrees NNS I-NP O
, , O O
pulse NN B-NP O
90 CD I-NP O
, , O O
respiratory JJ B-NP O
rate NN I-NP O
18 CD I-NP O
, , O O
blood NN B-NP O
pressure NN I-NP O
114/60 CD B-NP O
, , O O
room NN B-NP O
air NN I-NP O
saturation NN I-NP O
91 CD B-NP O
% NN I-NP O
. . O O
HEENT NNP B-NP O
: : O O
Normocephalic NNP B-NP O
, , O O
atraumatic JJ B-ADJP O
. . B-NP O
Pupils NNS I-NP O
equal JJ B-ADJP O
, , O O
round RB B-ADVP O
, , O O
and CC O O
reactive NN B-NP O
to TO B-PP O
light NN B-NP O
and CC I-NP O
accommodation NN I-NP O
. . O O
Neck NNP B-NP O
supple NN I-NP O
and CC I-NP O
nontender NN I-NP O
. . O O
Chest NNP B-NP O
: : O O
Bibasilar JJ B-NP O
crackles NNS I-NP O
. . O O
Left VBD B-VP O
sided VBN I-VP O
rhonchi NNP B-NP O
. . I-NP O
Abdomen NNP I-NP O
: : O O
Obvious JJ O O
infected JJ B-NP O
wound NN I-NP O
. . O O
Minimally RB B-VP O
tender NN I-VP O
. . B-NP O
Extremities NNS I-NP O
: : O O
Negative JJ B-ADJP O
. . O O
Neurologic NNP B-NP O
: : O O
Symmetric NNP B-NP O
. . I-NP O
Alert NNP I-NP O
and CC O O
oriented VBN B-VP O
times NNS B-NP O
two CD B-NP O
. . I-NP O
Reflexes NNS I-NP O
normal JJ B-ADJP O
, , O O
strength NN B-NP O
normal JJ I-NP O
. . O O
LABORATORY NN B-NP O
EVALUATION NN I-NP O
: : O O
WBC NNP B-NP O
28 CD I-NP O
. . O O
THERAPY IN B-PP O
RENDERED/COURS NNP B-NP O
E NNP I-NP O
IN IN B-PP O
ED NNP B-NP O
: : O O
The DT B-NP O
patient NN I-NP O
was VBD B-VP O
given VBN I-VP O
IV NNP B-NP O
antibiotics NNS B-NP O
and CC O O
will MD B-VP O
be VB I-VP O
admitted VBN I-VP O
to TO B-PP O
the DT B-NP O
medical JJ I-NP O
service NN I-NP O
for IN B-PP O
workup NN B-NP O
. . O O
PROCEDURES NNS B-NP O
: : O O
CONSULTATIONS NNS B-NP O
( -LRB- O O
including VBG B-PP O
PCP) NNP B-NP O
: : O O
FINAL NNP B-NP O
DIAGNOSIS NNP I-NP O
: : O O
Urosepsis NNP B-NP O
. . O O
DISPOSITION NN B-NP O
( -LRB- I-NP O
including VBG I-NP O
condition NN I-NP O
upon IN B-PP O
discharge NN B-NP O
) -RRB- I-NP O
: : O O
She PRP B-NP O
was VBD B-VP O
admitted VBN I-VP O
in IN B-PP O
poor JJ B-NP O
condition NN I-NP O
. . O O
ZD548/6212 . O B-IDNUM
D NNP B-NP O
: : O O
10/21/65 CD O B-DATE
T NNP B-NP O
: : O O
10/21/65 CD O B-DATE
Dictated VBN B-VP O
by IN B-PP O
: : O O
RUBEN NNP B-NP B-DOCTOR
ZACARIAS NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
RZ1 . O B-USERNAME
******** NN B-NP O
Not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Physician JJ B-NP O
******** NNS I-NP O
