Record NNP B-NP O
date NN I-NP O
: : O O
2060-01-20 CD O B-DATE
Highland NNP B-NP B-HOSPITAL
Park NNP I-NP I-HOSPITAL
Care NNP I-NP I-HOSPITAL
Center NNP I-NP I-HOSPITAL
8827 CD B-NP B-STREET
Alice NNP I-NP I-STREET
Drive NNP I-NP I-STREET
KIMBROUGH NNP I-NP I-PATIENT
, , O I-PATIENT
AMELIA NNP B-NP I-PATIENT
Arvin NNP B-NP B-CITY
, , O O
SC NNP B-NP B-STATE
42993 CD I-NP B-ZIP
43471375 CD O B-MEDICALRECORD
( -LRB- B-NP I-PHONE
615 CD I-NP I-PHONE
) -RRB- I-NP I-PHONE
305-3068 CD I-NP I-PHONE
01/20/2060 CD O B-DATE
HISTORY NN B-NP O
OF IN B-PP O
PRESENT JJ B-NP O
ILLNESS NNS I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
a DT B-NP O
47 CD I-NP B-AGE
-year-old JJ I-NP O
female NN I-NP O
who WP B-NP O
returns VBZ B-VP O
to TO B-PP O
the DT B-NP O
clinic NN I-NP O
for IN B-PP O
a DT B-NP O
followup JJ I-NP O
visit NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
multiple JJ B-NP O
medical JJ I-NP O
problems NNS I-NP O
including VBG B-VP O
severe JJ B-NP O
and CC I-NP O
extreme JJ I-NP O
hypertension NN I-NP O
as RB B-ADVP O
well RB I-ADVP O
as IN B-PP O
high JJ B-NP O
blood NN I-NP O
pressure NN I-NP O
and CC I-NP O
chronic NN I-NP O
renal JJ I-NP O
failure NN I-NP O
for IN B-PP O
which WDT B-NP O
she PRP B-NP O
is VBZ B-VP O
currently RB I-VP O
attending VBG I-VP O
dialysis NN B-NP O
sessions NNS I-NP O
3 CD B-NP O
times NNS I-NP O
per IN B-PP O
week NN B-NP O
. . O O
The DT O O
patient NN B-NP O
also RB B-ADVP O
is VBZ B-VP O
currently RB I-VP O
being VBG I-VP O
treated VBN I-VP O
for IN B-PP O
hot JJ B-NP O
flashes NNS I-NP O
with IN B-PP O
Prempro NNP B-NP O
. . O O
The DT B-NP O
patient NN I-NP O
states NNS I-NP O
that WDT B-NP O
she PRP B-NP O
ran VBD B-VP O
out IN B-PP O
of IN B-PP O
her PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
medications NNS I-NP O
including VBG B-PP O
the DT B-NP O
patch NN I-NP O
2 CD B-NP O
days NNS I-NP O
ago RB B-ADVP O
. . O O
She PRP B-NP O
also RB B-ADVP O
complains VBZ B-VP O
of IN B-PP O
frequent JJ B-NP O
popping VBG I-NP O
and CC I-NP O
loss NN I-NP O
of IN B-PP O
hearing NN B-NP O
in IN B-PP O
her PRP$ B-NP O
right JJ I-NP O
ear NN I-NP O
. . O O
PHYSICAL NNP B-NP O
EXAMINATION NN I-NP O
: : O O
A DT B-NP O
middle-aged JJ I-NP O
female NN I-NP O
in IN B-PP O
no DT B-NP O
acute JJ I-NP O
distress NN I-NP O
. . O O
Blood NN B-NP O
pressure NN I-NP O
is VBZ B-VP O
182/94 CD B-NP O
, , O O
weight NN B-NP O
is VBZ B-VP O
211 CD B-NP O
pounds NNS I-NP O
, , O O
and CC O O
pulse NN B-NP O
is VBZ B-VP O
76 CD B-NP O
. . O O
Chest NNP B-NP O
is VBZ B-VP O
clear JJ B-ADJP O
bilaterally RB B-ADVP O
. . O O
Heart VB B-VP O
, , O O
regular JJ B-NP O
rate NN I-NP O
and CC I-NP O
rhythm NN I-NP O
, , O O
positive JJ B-NP O
S1 NNP I-NP O
, , O O
S2 NNP B-NP O
. . I-NP O
Negative NNP I-NP O
S3 NNP I-NP O
, , O O
S4 NNP B-NP O
, , O O
no DT B-NP O
murmur NN I-NP O
. . O O
Abdomen '' O O
is VBZ B-VP O
soft JJ B-ADJP O
, , O O
nontender NN B-NP O
, , O O
positive JJ B-NP O
bowel NN I-NP O
sounds NNS I-NP O
. . O O
Lower NNP B-NP O
extremities NNS I-NP O
, , O O
no DT B-NP O
edema NN I-NP O
, , I-NP O
nontender NN I-NP O
. . O O
IMPRESSION NN B-NP O
AND CC I-NP O
PLAN NN I-NP O
: : O O
1 LS O O
. . B-NP O
Chronic NNP I-NP O
renal JJ I-NP O
failure NN I-NP O
, , O O
on IN B-PP O
dialysis NN B-NP O
. . O O
The DT B-NP O
patient NN I-NP O
appears VBZ B-VP O
to TO I-VP O
be VB I-VP O
doing VBG I-VP O
much RB B-ADVP O
better JJR I-ADVP O
and CC O O
has VBZ B-VP O
stabilized VBN I-VP O
on IN B-PP O
her PRP$ B-NP O
regular JJ I-NP O
dialysis NN I-NP O
sessions NNS I-NP O
. . O O
She PRP B-NP O
is VBZ B-VP O
still RB I-VP O
waiting VBG I-VP O
for IN B-PP O
donor NN B-NP O
for IN B-PP O
a DT B-NP O
renal JJ I-NP O
transplant NN I-NP O
. . O O
She PRP B-NP O
will MD B-VP O
follow VB I-VP O
up RP B-PRT O
with IN B-NP O
nephrology NN I-NP O
as IN B-PP O
scheduled VBN B-NP O
. . O O
She PRP B-NP O
is VBZ B-VP O
currently RB I-VP O
being VBG I-VP O
immunized VBN I-VP O
for IN B-PP O
her PRP$ B-NP O
transplant NN I-NP O
and CC O O
will MD B-VP O
receive VB I-VP O
her PRP$ B-NP O
third JJ I-NP O
hepatitis NN I-NP O
B NNP I-NP O
shot NN I-NP O
as RB B-ADVP O
well RB I-ADVP O
as IN B-PP O
her PRP$ B-NP O
second JJ I-NP O
hepatitis NN I-NP O
A DT B-NP O
shot NN I-NP O
today NN B-NP O
. . O O
2. PRP B-NP O
Right RB B-ADVP O
ear NN B-NP O
problem NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
wax NN B-NP O
buildup NN I-NP O
in IN B-PP O
her PRP$ B-NP O
right JJ I-NP O
ear NN I-NP O
and CC O O
I PRP B-NP O
recommended VBD B-VP O
that IN B-SBAR O
she PRP B-NP O
use VBP B-VP O
olive JJ B-NP O
oil NN I-NP O
on IN B-PP O
a DT B-NP O
nightly RB I-NP O
basis NN I-NP O
to TO B-VP O
resolve VB I-VP O
the DT B-NP O
earwax NN I-NP O
. . O O
3. DT B-NP O
Diabetes NNP I-NP O
mellitus NN I-NP O
. . O O
Control NNP B-NP O
is VBZ B-VP O
much RB B-ADVP O
better JJR I-ADVP O
. . O O
There EX B-NP O
is VBZ B-VP O
a DT B-NP O
recent JJ I-NP O
hemoglobin NN I-NP O
A1c IN B-PP O
of IN B-PP O
6.3 CD B-NP O
. . O O
4 CD B-LST O
. . O O
Severe NNP B-NP O
hyperlipidemia NN I-NP O
, , O O
which WDT B-NP O
has VBZ B-VP O
improved VBN I-VP O
after IN B-PP O
the DT B-NP O
patient NN I-NP O
was VBD B-VP O
started VBN I-VP O
on IN B-PP O
dialysis NN B-NP O
. . O O
Of IN B-PP O
note NN B-NP O
, , O O
was VBD B-VP O
also RB B-ADVP O
a DT B-NP O
very RB I-NP O
high JJ I-NP O
HDL. . O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
currently RB B-ADVP O
on IN B-PP O
no DT B-NP O
hypolipemic JJ I-NP O
medication NN I-NP O
. . O O
We PRP B-NP O
will MD B-VP O
check VB I-VP O
a DT B-NP O
fasting JJ I-NP O
lipid JJ I-NP O
profile NN I-NP O
at IN B-PP O
this DT B-NP O
point NN I-NP O
. . O O
5 CD B-NP O
. . O O
Severe NNP B-NP O
hypertension NN I-NP O
. . O O
Prescriptions NNPS O O
for IN B-PP O
nifedipine NN B-NP O
and CC O O
the DT B-NP O
clonidine JJ I-NP O
patch NN I-NP O
were VBD B-VP O
refilled VBN I-VP O
. . O O
6 CD B-NP O
. . O O
Hyperparathyroidism NNP O O
. . O O
We PRP B-NP O
will MD B-VP O
check VB I-VP O
a DT B-NP O
PTH NNP I-NP O
level NN I-NP O
today NN B-NP O
. . O O
Odell NNP B-NP B-DOCTOR
Jorgenson NNP I-NP I-DOCTOR
, , O O
MD . O O
eScription NN B-NP O
document NN I-NP O
: : O O
3-4524040 CD B-NP B-IDNUM
HFFocus NN I-NP O
DD NNP B-NP O
: : O O
01/20/60 CD O B-DATE
DT NNP B-NP O
: : O O
01/20/60 CD O B-DATE
DV NNP B-NP O
: : O O
01/20/60 CD O B-DATE
