Record NNP B-NP O
date NN I-NP O
: : O O
2094-05-01 CD O B-DATE
CC NNP B-NP O
: : O O
Annual JJ B-NP O
exam NN I-NP O
, , O O
Diabetes NNP B-NP O
, , O O
obesity NN B-NP O
. . O O
HPI NNP B-NP O
: : O O
58 CD B-NP B-AGE
M NNP I-NP O
with IN B-PP O
HTN NNP B-NP O
, , O O
Diabetes NNP B-NP O
, , O O
obesity NN B-NP O
presenting VBG I-NP O
for IN B-PP O
annual JJ B-NP O
exam NN I-NP O
. . O O
Has VBZ B-VP O
not RB I-VP O
been VBN I-VP O
able JJ B-ADJP O
to TO B-VP O
lose VB I-VP O
weight NN B-NP O
despite IN B-PP O
aggressive JJ B-NP O
diet NN I-NP O
changes NNS I-NP O
. . O O
Stopped NNP O O
seeing VBG B-VP O
nutritionist NN B-NP O
because IN B-SBAR O
it PRP B-NP O
was VBD B-VP O
n't RB I-VP O
resulting VBG I-VP O
in IN B-PP O
weight NN B-NP O
loss NN I-NP O
. . O O
Problems NNS B-NP O
HTN . O O
HYPERCHOL . O O
H/O NNP B-NP O
GOUT NNP I-NP O
DM . O O
Skull NNP B-NP O
lesion NN I-NP O
? . B-NP O
migraines NNS I-NP O
Medications NNS B-NP O
Elavil NNP B-NP O
( -LRB- I-NP O
AMITRIPTYLINE NNP I-NP O
HCL NNP I-NP O
) -RRB- I-NP O
10MG VBP I-NP O
TABLET NNP I-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QHS . O O
Ecasa NNP B-NP O
( -LRB- I-NP O
ASPIRIN NNP I-NP O
ENTERIC NNP I-NP O
COATED NNP I-NP O
) -RRB- I-NP O
325 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
325MG JJ I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
Atenolol NNP B-NP O
50 CD I-NP O
MG NNP I-NP O
PO NNP I-NP O
BID NNP I-NP O
Lisinopril NNP B-NP O
40 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
40MG JJ I-NP O
TABLET NN I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
Pravachol NNP B-NP O
( -LRB- I-NP O
PRAVASTATIN NN I-NP O
) -RRB- I-NP O
40MG . I-NP O
TABLET NNP I-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QHS . O O
Lantus NNP B-NP O
( -LRB- I-NP O
INSULIN NN I-NP O
GLARGINE NNP B-NP O
) -RRB- I-NP O
40 CD I-NP O
UNITS NNP I-NP O
SC NNP I-NP O
QHS . O O
Golytely RB B-NP O
4000 CD I-NP O
ML NNP I-NP O
PO NNP I-NP O
x1 VBD B-VP O
, , O O
take VB B-VP O
as RB I-VP O
directed VBN I-VP O
prior RB B-ADVP O
to TO B-VP O
colonoscopy VB I-VP O
Plavix NNP B-NP O
( -LRB- I-NP O
CLOPIDOGREL NN I-NP O
) -RRB- I-NP O
75 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
75MG NNP I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
Allopurinol NNP B-NP O
300 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
300MG NNP I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
Allergies . O O
NONE VB B-VP O
- : O O
NONE VB O O
ROS NNP B-NP O
: : O O
Const NNP B-NP O
: : O O
no DT B-NP O
weight NN I-NP O
loss NN I-NP O
, , O O
no DT B-NP O
fevers NNS I-NP O
or CC I-NP O
chills NNS I-NP O
Endo NNP B-NP O
: : O O
no DT B-NP O
polyuria NN I-NP O
, , O O
polydipsia NN B-NP O
GI NNP B-NP O
: : O O
no DT B-NP O
nausea NN I-NP O
, , O O
vomiting VBG B-VP O
, , O O
diarrhea NN B-NP O
, , O O
melena NN B-NP O
, , O O
BRBPR NNP B-NP O
, , O O
heartburn NN B-NP O
, , O O
abd NN B-NP O
pain NN I-NP O
GU NNP B-NP O
: : O O
no DT B-NP O
hesitancy NN I-NP O
, , O O
dribbling VBG B-VP O
, , O O
double JJ B-NP O
voiding NN I-NP O
, , O O
dysuria NN B-NP O
Derm NNP B-NP O
: : O O
no DT B-NP O
rashes NNS I-NP O
or CC I-NP O
moles NNS I-NP O
. . O O
all DT B-NP O
other JJ I-NP O
systems NNS I-NP O
negative JJ O O
FH NNP B-NP O
: : O O
mother NN B-NP O
and CC I-NP O
sister NN I-NP O
were VBD B-VP O
on IN B-PP O
dialysis NN B-NP O
for IN B-PP O
kidney NN B-NP O
failure NN I-NP O
Health NNP B-NP O
Maintenance NNP I-NP O
Influenza NNP B-NP O
Vaccine NNP I-NP O
12/04/2093 CD O B-DATE
Cholesterol NNP B-NP O
09/12/2093 CD I-NP B-DATE
159 CD I-NP O
TOTAL NNP I-NP O
CHOLESTEROL NNP I-NP O
REFERENCE NNP I-NP O
INTERVALS NNP I-NP O
<200 CD I-NP O
mg/dL NN I-NP O
Desirable NNP B-NP O
200-239 CD I-NP O
mg/dL NN I-NP O
Borderline NNP I-NP O
High NNP I-NP O
>=240 CD I-NP O
mg/dL NNS I-NP O
High RB O O
M-alb/creat JJ B-NP O
ratio NN I-NP O
09/12/2093 VBD B-VP B-DATE
22 CD O O
Stool NNP B-NP O
Guaiac NNP I-NP O
12/03/88 CD I-NP B-DATE
Other JJ I-NP O
cards NNS I-NP O
given VBN O O
Pneumovax NNP B-NP O
06/10/2092 CD I-NP B-DATE
PER NN I-NP O
MD NNP I-NP O
ORDER NNP I-NP O
, , O O
WRITTEN NNP B-NP O
INSTRUCTIONS NNP I-NP O
GIVEN . O O
Smoking VBG B-NP O
status NN I-NP O
01/11/88 IN B-PP B-DATE
NEVER NNP B-NP O
A NNP I-NP O
SMOKER NNP I-NP O
Sigmoidoscopy NNP B-NP O
12/03/88 CD I-NP B-DATE
discussed VBD B-VP O
, , O O
pt RB B-NP O
reluctant JJ I-NP O
UA-Protein NNP B-NP O
10/25/2093 CD I-NP B-DATE
NEG . O O
Colonoscopy NNP B-NP O
05/01/2094 CD I-NP B-DATE
referred VBD B-VP O
again RB O O
Hep PRP B-NP O
B NNP B-NP O
Vaccine NNP I-NP O
01/05/8 VBD B-VP I-DATE
2 CD O I-DATE
Ophthal NNP B-NP O
Exam NNP I-NP O
09/18/2093 VBD B-VP B-DATE
Done/scheduled VBN I-VP O
Nutrition NNP B-NP O
Referral NNP I-NP O
09/01/2092 CD O B-DATE
Podiatry NNP B-NP O
exam NN I-NP O
08/31/2092 CD B-NP B-DATE
see VBP B-VP O
below IN B-NP O
Saw VBD B-VP O
Dr. NNP B-NP O
Quadri NNP I-NP B-DOCTOR
at IN B-PP O
Mediquik NNP B-NP B-HOSPITAL
. . I-NP O
Report NNP I-NP O
states NNS I-NP O
" `` O O
My PRP$ B-NP O
assessment NN I-NP O
at IN B-PP O
this DT B-NP O
time NN I-NP O
is VBZ B-VP O
diabetes NNS B-NP O
and CC O O
ingrown JJ B-NP O
left JJ I-NP O
hallux NN I-NP O
nail NN I-NP O
. . O O
Podiatric JJ B-NP O
treatment NN I-NP O
today NN I-NP O
cosisted VBN B-VP O
of IN B-PP O
debridement NN B-NP O
of IN B-PP O
the DT B-NP O
medial JJ I-NP O
borders NNS I-NP O
of IN B-PP O
the DT B-NP O
left JJ I-NP O
big JJ I-NP O
toe NN I-NP O
, , O O
which WDT B-NP O
provided VBD B-VP O
Mr NNP B-NP O
Hooper NNP I-NP B-PATIENT
with IN B-PP O
relief NN B-NP O
. . O O
I PRP B-NP O
also RB B-ADVP O
reviewed VBN B-VP O
diabetic JJ B-NP O
foot NN I-NP O
care NN I-NP O
with IN B-PP O
him PRP B-NP O
and CC O O
stressed VBD B-VP O
its PRP$ B-NP O
importance NN I-NP O
to TO B-PP O
him PRP B-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
to TO I-VP O
follow VB I-VP O
up RP B-PRT O
in IN B-NP O
three CD I-NP O
months NNS I-NP O
time NN I-NP O
. . O O
HCV NNP B-NP O
10/25/2093 CD I-NP B-DATE
NEGATIVE CD O O
Td DT B-NP O
Booster NNP I-NP O
06/10/2092 CD I-NP B-DATE
PER NN I-NP O
MD NNP I-NP O
ORDEDR,WRITTEN NNP I-NP O
INSTRUCTIONS NNP I-NP O
GIVEN . O O
Triglycerides NNS B-NP O
09/12/2093 CD B-NP B-DATE
267 CD I-NP O
TRIGLYCERIDES NNP I-NP O
REFERENCE NNP I-NP O
INTERVALS NNP I-NP O
<150 CD I-NP O
mg/dL NN I-NP O
Normal JJ I-NP O
150-199 JJ I-NP O
mg/dL NN I-NP O
Borderline NNP I-NP O
High NNP I-NP O
200-499 CD I-NP O
mg/dL NN I-NP O
High NNP B-NP O
>=500 CD I-NP O
mg/dL NNS I-NP O
Very RB B-ADVP O
High RB I-ADVP O
Cholesterol-LDL NNP B-NP O
09/12/2093 CD I-NP B-DATE
85 CD I-NP O
LDL NNP I-NP O
CHOLESTEROL NNP I-NP O
REFERENCE NNP I-NP O
INTERVALS NNP I-NP O
< VBD B-VP O
100 CD B-NP O
mg/dL JJ I-NP O
Optimal NNP I-NP O
100-129 CD I-NP O
mg/dL NN I-NP O
Near IN B-PP O
optimal JJ B-NP O
130-159 CD I-NP O
mg/dL NN I-NP O
Borderline NNP I-NP O
High NNP I-NP O
160-189 CD I-NP O
mg/dL NN I-NP O
High NNP B-NP O
>=190 CD I-NP O
mg/dL NNS I-NP O
Very RB B-ADVP O
High RB I-ADVP O
Microalbumin NNP B-NP O
05/16/2092 CD I-NP B-DATE
6.3 CD O O
Hct NNP B-NP O
( -LRB- I-NP O
Hematocrit NN I-NP O
) -RRB- I-NP O
06/03/2092 CD I-NP B-DATE
39.9 CD I-NP O
VERIFIED . O O
HBsAG NNP B-NP O
10/25/2093 CD I-NP B-DATE
NEGATIVE CD O O
Home NNP B-NP O
glucose NN I-NP O
monitoring VBG B-VP O
07/04/2092 CD B-NP B-DATE
Positve JJ I-NP O
Patient JJ I-NP O
tests NNS I-NP O
BID. . O O
Is VBZ B-VP O
proficient NN B-NP O
in IN B-PP O
use NN B-NP O
of IN B-PP O
his PRP$ B-NP O
One CD I-NP O
Touch NNP I-NP O
Ultra NNP I-NP O
glucometer NN I-NP O
Hypoglycemia NNP B-NP O
Assessment/Counseling NNP I-NP O
07/04/2092 CD I-NP B-DATE
Positive NNP I-NP O
Patient NNP I-NP O
verbalizes VBZ B-VP O
s/s NNS B-NP O
of IN B-PP O
hypoglycemia NN B-NP O
. . O O
Keeps NNS B-VP O
flyer NN B-NP O
on IN B-PP O
his PRP$ B-NP O
refridgerator NN I-NP O
at IN B-PP O
home NN B-NP O
in IN B-PP O
case NN B-NP O
of IN B-PP O
emergency NN B-NP O
Complete JJ B-NP O
Physical JJ I-NP O
Exam NNP I-NP O
05/01/2094 CD O B-DATE
Cholesterol-HDL NNP B-NP O
09/12/2093 CD I-NP B-DATE
21 CD O O
Hgb NNP B-NP O
( -LRB- I-NP O
Hemoglobin NNP I-NP O
) -RRB- I-NP O
06/03/2092 CD I-NP B-DATE
14.5 CD O O
HbA1c JJ B-NP O
04/24/2094 NN I-NP B-DATE
5.5 CD O O
PE NN B-NP O
: : O O
120/72 CD B-NP O
P NNP I-NP O
72 CD I-NP O
Wgt NNP I-NP O
262 CD O O
General NNP B-NP O
: : O O
obese JJ B-NP O
man NN I-NP O
in IN B-PP O
NAD NN B-NP O
HEENT NNP B-NP O
: : O O
PERRL NN B-NP O
, , O O
EOMI NNP B-NP O
, , O O
OP NNP B-NP O
clear JJ I-NP O
, , O O
ear NN B-NP O
canals NNS I-NP O
and CC O O
TM NNP B-NP O
's POS B-NP O
clear JJ I-NP O
Neck NNP B-NP O
: : O O
Supple NNP B-NP O
, , O O
no DT B-NP O
TM NNP I-NP O
or CC I-NP O
LAN NNP I-NP O
CV NNP B-NP O
: : O O
RRR NNP B-NP O
; : O O
normal JJ B-NP O
s1 NN I-NP O
, , O O
s2 NN B-NP O
; : O O
no DT B-NP O
murmurs NNS I-NP O
rubs NNS I-NP O
or CC O O
gallops NNS B-NP O
Pulm NNP B-NP O
: : O O
Clear NNP B-NP O
to TO B-PP O
auscultation NN B-NP O
and CC I-NP O
percussion NN I-NP O
bilaterally RB O O
Back RB B-ADVP O
: : O O
No DT B-NP O
CVA NNP I-NP O
tenderness NN I-NP O
, , O O
no DT B-NP O
vertebral JJ I-NP O
tenderness NN I-NP O
Abd NNP B-NP O
: : O O
soft JJ B-NP O
, , I-NP O
nontender JJ I-NP O
, , I-NP O
nondistended JJ I-NP O
, , O O
no DT B-NP O
hepatomegaly NN I-NP O
or CC O O
splenomegaly RB B-ADVP O
, , O O
+BS . O O
Extr NNP B-NP O
: : O O
No DT B-NP O
CCE NNP I-NP O
, , O O
2+ CD B-NP O
DP/PT NNP I-NP O
pulses NNS I-NP O
bilaterally RB B-ADVP O
. . O O
No DT B-NP O
inguinal NN I-NP O
LAN. . O O
Skin NNP B-NP O
: : O O
mild JJ B-NP O
onychomycosis NN I-NP O
. . O O
no DT B-NP O
lesions NNS I-NP O
on IN B-PP O
inspection NN B-NP O
or CC I-NP O
palpation NN I-NP O
A/P NNP B-NP O
: : O O
1.Obesity NNP B-NP O
: : O O
discussed VBD B-VP O
options NNS B-NP O
including VBG B-VP O
repeat NN B-NP O
nutritionist NN I-NP O
consult VB B-VP O
or CC I-VP O
medication NN I-VP O
. . O O
Gave NNP O O
him PRP B-NP O
rx NNP O O
for IN B-PP O
Meridia NNP B-NP O
10 CD I-NP O
mg NN I-NP O
a DT B-NP O
day NN I-NP O
along IN B-PP O
with IN B-PP O
information NN B-NP O
on IN B-PP O
the DT B-NP O
med JJ I-NP O
. . O O
F/u '' O O
one CD B-NP O
month NN I-NP O
to TO B-VP O
assess VB I-VP O
progress NN B-NP O
. . O O
2. DT B-NP O
Diabetes NNP I-NP O
: : O O
continue VB B-VP O
NPH JJ B-NP O
insulin NN I-NP O
. . O O
Excellent '' O O
A1C. NNP B-NP O
Malb NNP I-NP O
today NN B-NP O
. . O O
3. DT B-NP O
HTN NNP I-NP O
: : O O
improved VBN B-VP O
. . B-NP O
Continue NNP I-NP O
current JJ I-NP O
regimen NNS I-NP O
. . O O
Chem NN B-NP O
7 CD I-NP O
today NN B-NP O
. . O O
4 CD B-LST O
. . O O
H/o NNP B-NP O
gout NN I-NP O
, , O O
no DT B-NP O
active JJ I-NP O
gout NN I-NP O
. . O O
continue VB B-VP O
allopurinol DT B-NP O
. . I-NP O
Reviewed NNP I-NP O
Urate NNP I-NP O
which WDT B-NP O
was VBD B-VP O
excellent JJ B-ADJP O
at IN B-PP O
4.9 CD B-NP O
. . O O
5 CD B-NP O
. . O O
HM NNP B-NP O
: : O O
referred VBD B-VP O
again RB B-ADVP O
for IN B-PP O
colo NN B-NP O
. . O O
Lipid NNP B-NP O
panel NN I-NP O
, , O O
ALT NNP B-NP O
today NN I-NP O
. . O O
6 CD B-LST O
. . O O
f/u IN B-PP O
one CD B-NP O
month NN I-NP O
and CC I-NP O
prn NN I-NP O
. . O O
Daniel NNP B-NP B-DOCTOR
C. NNP I-NP I-DOCTOR
Quillen NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
