Record NNP B-NP O
date NN I-NP O
: : O O
2096-06-06 CD O B-DATE
Patient NNP B-NP O
Name NNP I-NP O
: : O O
HOLDEN,MATIAS NNP B-NP B-PATIENT
[ NNP I-NP O
MRN NNP I-NP O
: : O O
97198841 CD B-NP B-MEDICALRECORD
PGH NNP I-NP B-HOSPITAL
] SYM O O
Date NNP B-NP O
of IN B-PP O
Visit NNP B-NP O
: : O O
06/06/2096 CD O B-DATE
Reason NN B-NP O
for IN B-PP O
Visit NNP B-NP O
Return VB B-VP O
visit NN B-NP O
for IN B-PP O
this DT B-NP O
41 CD I-NP B-AGE
m NN I-NP O
with IN B-PP O
hx JJ B-NP O
HCV NNP I-NP O
, , O O
poorly RB B-VP O
controlled VBN I-VP O
DM NNP B-NP O
who WP B-NP O
comes VBZ B-VP O
after IN B-PP O
recent JJ B-NP O
job NN I-NP O
loss NN I-NP O
, , O O
depression NN B-NP O
. . O O
History NN B-NP O
of IN B-PP O
Present NNP B-NP O
Illness NNP I-NP O
doing VBG B-VP O
about IN B-NP O
the DT I-NP O
same JJ I-NP O
, , I-NP O
fluoxetine NN I-NP O
has VBZ B-VP O
n't RB I-VP O
helped VBN I-VP O
much RB B-ADVP O
, , O O
perhaps RB B-NP O
a DT I-NP O
little JJ I-NP O
. . O O
&nbsp;has VBD B-VP O
been VBN I-VP O
on IN B-PP O
it PRP B-NP O
since IN B-PP O
our PRP$ B-NP O
last JJ I-NP O
visit NN I-NP O
. . O O
has VBZ B-VP O
n't RB I-VP O
yet RB I-VP O
been VBN I-VP O
able JJ B-ADJP O
to TO B-VP O
fill VB I-VP O
ativan DT B-NP O
rx NN I-NP O
from IN B-PP O
dr NN B-NP O
oliveira JJ I-NP B-DOCTOR
bc NN I-NP O
of IN B-PP O
holiday NN B-NP O
w/e NN I-NP O
, , O O
but CC O O
will MD B-VP O
p/u VB I-VP O
today NN B-NP O
. . O O
&nbsp;was VBD B-VP O
glad JJ B-ADJP O
to TO B-VP O
see VB I-VP O
dr NN B-NP O
oliveira JJ I-NP B-DOCTOR
, , I-NP O
helpful JJ I-NP O
.<BR>saw NN I-NP O
a DT B-NP O
lawyer NN I-NP O
who WP B-NP O
agrees VBZ B-VP O
that IN O O
his PRP$ B-NP O
work NN I-NP O
termination NN I-NP O
likely RB B-ADVP O
is VBZ B-VP O
a DT B-NP O
violation NN I-NP O
of IN B-PP O
his PRP$ B-NP O
rights NNS I-NP O
, , O O
and CC O O
atty NN B-NP O
is VBZ B-VP O
planning VBG I-VP O
to TO I-VP O
pursue VB I-VP O
the DT B-NP O
case NN I-NP O
.<BR>brings IN B-PP O
bs NNS B-NP O
log VBP B-VP O
, , O O
has VBZ B-VP O
kept VBN I-VP O
perfect JJ B-NP O
records NNS I-NP O
for IN B-PP O
past NN B-NP O
3 CD I-NP O
wks NNS I-NP O
since IN B-PP O
dr NN B-NP O
kenny JJ B-NP B-DOCTOR
visit NN I-NP O
: : O O
&nbsp;FBS NNP B-NP O
8am IN B-PP O
130-190 CD B-NP O
, , O O
outliers NNS B-NP O
of IN B-PP O
101 CD B-NP O
and CC I-NP O
340 CD I-NP O
which WDT B-NP O
was VBD B-VP O
after IN B-PP O
big JJ B-NP O
amt NN I-NP O
rice NN I-NP O
the DT B-NP O
night NN I-NP O
before IN B-PP O
. . O O
&nbsp;HS NNP B-NP O
bs VBZ B-VP O
10pm IN B-PP O
120-180 CD B-NP O
x NN I-NP O
one CD B-NP O
outlier NN I-NP O
235 CD B-PP O
the DT B-NP O
first JJ I-NP O
day NN I-NP O
. . O O
these DT B-NP O
are VBP B-VP O
the DT B-NP O
best JJS I-NP O
his PRP$ B-NP O
bs NNS I-NP O
has VBZ B-VP O
been VBN I-VP O
in IN B-PP O
many JJ B-NP O
months NNS I-NP O
. . O O
&nbsp;understands NNS B-NP O
target NN I-NP O
a1c IN B-PP O
values NNS B-NP O
.<BR>apparently RB B-ADVP O
on IN B-PP O
40mg CD B-NP O
pravachol NN I-NP O
, , O O
rather RB B-PP O
than IN I-PP O
80 CD B-NP O
as IN B-SBAR O
i PRP B-NP O
had VBD B-VP O
thought VBN I-VP O
. . O O
&nbsp;has VBD B-VP O
been VBN I-VP O
taking VBG I-VP O
40 CD B-NP O
mg NN I-NP O
for IN B-PP O
several JJ B-NP O
mos NN I-NP O
, , O O
at IN B-ADVP O
least JJS I-ADVP O
since IN B-PP O
feb NN B-NP B-DATE
.<BR>c/o IN B-PP O
occ JJ B-NP O
pain NN I-NP O
in IN B-PP O
LUQ NNP B-NP O
, , O O
feels VBZ B-VP O
like IN B-PP O
a DT B-NP O
muscle NN I-NP O
cramp NN I-NP O
, , O O
occurs VBZ B-VP O
when WRB B-ADVP O
at IN B-PP O
rest NN B-NP O
, , O O
sitting VBG B-VP O
watching VBG B-NP O
tv--> NN I-NP O
will MD B-VP O
feel VB I-VP O
pain NN B-NP O
on IN B-PP O
getting VBG B-VP O
up RP B-PRT O
from IN B-PP O
chair NN B-NP O
, , O O
sore JJ B-ADJP O
to TO B-PP O
the DT B-NP O
touch NN I-NP O
, , O O
goes VBZ B-VP O
away RB B-ADVP O
on IN B-PP O
own JJ B-NP O
after IN B-PP O
5-10min JJ B-NP O
. . O O
&nbsp;has VBD B-VP O
been VBN I-VP O
happening VBG I-VP O
off RB B-ADVP O
and CC O O
on IN B-PP O
for IN B-PP O
5mos NNS B-NP O
. . O O
&nbsp;no NN B-NP O
HB. NNP I-NP O
&nbsp;no NNP I-NP O
relation NN I-NP O
to TO B-PP O
food NN B-NP O
. . O O
&nbsp;no '' O O
other JJ B-NP O
gi NNS I-NP O
sxs NNS I-NP O
. . O O
Problems NNS B-NP O
DM . O O
H/O NNP B-NP O
NEPHROLITHIASIS NNPS I-NP O
ANKLE NNP B-NP O
FRACTURE NNP I-NP O
H/O NNP B-NP O
DRUG NNP I-NP O
ABUSE NNP I-NP O
TOBACCO NN B-NP O
WORK NNP B-NP O
# # I-NP O
310-7911 CD I-NP B-PHONE
EXT NNP I-NP O
5 CD I-NP B-PHONE
ROSACEA NN B-NP O
Elevated VBN B-NP O
lipids NNS I-NP O
Microalbuminuria NNP B-NP O
? . O O
migraine . O O
New NNP B-NP O
Phone NNP I-NP O
3/11/94 VBD B-VP B-DATE
: : O O
124-607-0785 CD B-NP B-PHONE
, , O O
work NN B-NP O
485-914-7948 CC O B-PHONE
HCV . O O
ETT NNP B-NP O
SAC NNP I-NP B-HOSPITAL
12/94 CD I-NP B-DATE
neg NN I-NP O
Allergies . O O
NKA . O O
Medications NNS B-NP O
ECASA NNP B-NP O
( -LRB- I-NP O
ASPIRIN NNP I-NP O
ENTERIC NNP I-NP O
COATED NNP I-NP O
) -RRB- I-NP O
( -LRB- I-NP O
81MG CC O O
TABLET VB B-VP O
EC NNP B-NP O
take VBP B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
) -RRB- I-NP O
PO NNP I-NP O
QD . O O
FLUOXETINE NNP B-NP O
HCL NNP I-NP O
20 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
20MG JJ I-NP O
CAPSULE NN I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
* JJ B-NP O
GLUCOSE NNP I-NP O
TEST NNP I-NP O
STRIPS NNP I-NP O
TOPICAL NNP I-NP O
( -LRB- O O
take VB B-VP O
) -RRB- B-NP O
TOP NNP I-NP O
DAILY NNP I-NP O
USE NNP I-NP O
HUMALOG NNP B-NP O
INSULIN NNP I-NP O
( -LRB- I-NP O
INSULIN NN I-NP O
LISPRO NNP I-NP O
) -RRB- I-NP O
30 CD I-NP O
UNITS NNS I-NP O
( -LRB- I-NP O
100 CD I-NP O
U/ML NNP I-NP O
VIAL NNP I-NP O
take VBP B-VP O
ML) NNP B-NP O
SC NNP I-NP O
before IN B-PP O
dinner NN B-NP O
INSULIN NNP B-NP O
SYRINGES NNP I-NP O
FOR IN B-PP O
( -LRB- B-NP O
take NN I-NP O
) -RRB- I-NP O
TP NNP I-NP O
bid NN I-NP O
and CC O O
prn NN B-NP O
* JJ B-NP O
LANCETS NNS I-NP O
Topical JJ B-NP O
( -LRB- B-VP O
take VB I-VP O
) -RRB- B-VP O
TOP RB I-VP O
daily RB I-VP O
use VB I-VP O
LISINOPRIL NNP B-NP O
20 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
20MG JJ I-NP O
TABLET NN I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QD . O O
LORAZEPAM NNP B-NP O
1 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
1MG JJ I-NP O
TABLET NN I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
TID NN I-NP O
x NN I-NP O
15 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
METFORMIN NNP B-NP O
1000 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
1000MG JJ I-NP O
TABLET NN I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
BID . O O
NPH NNP B-NP O
HUMULIN NNP I-NP O
INSULIN NNP I-NP O
70 CD I-NP O
UNITS NNP I-NP O
IN IN B-PP O
THE DT B-NP O
AM NNP I-NP O
, , O O
50 CD B-NP O
UNITS NNS I-NP O
AT WDT B-NP O
HS NNP B-NP O
( -LRB- B-VP O
100 CD B-NP O
U/ML NNP I-NP O
VIAL NNP I-NP O
take VBP B-VP O
ML) NNP B-NP O
SC NNP I-NP O
bid NN I-NP O
before IN B-PP O
breakfast NN B-NP O
and CC B-PP O
before IN B-PP O
HS NNS B-NP O
PRAVASTATIN NNP B-NP O
80 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
80MG NN I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
QHS . O O
TRIAMCINOLONE NNP B-NP O
ACETONIDE NNP I-NP O
0.1 CD I-NP O
% NN I-NP O
( -LRB- I-NP O
0.1 CD I-NP O
% NN I-NP O
CREAM IN B-PP O
take NN B-NP O
1 CD I-NP O
) -RRB- I-NP O
TOP . O O
BID . O O
Social NNP B-NP O
History NNP I-NP O
Smoking VBG B-VP O
: : O O
5 CD B-NP O
cigs/d NN I-NP O
. . O O
Trying VBG B-VP O
to TO I-VP O
quit VB I-VP O
. . O O
Did VBD B-VP O
manage VB I-VP O
to TO I-VP O
stop VB I-VP O
for IN B-PP O
1 CD B-NP O
year NN I-NP O
, , O O
started VBD B-VP O
again RB B-ADVP O
due JJ B-ADJP O
to TO B-PP O
pressure/anxiety NN B-NP O
.<BR>Alcohol NN I-NP O
: : O O
none NN B-NP O
.<BR>Just RB B-ADVP O
lost VBN B-VP O
his PRP$ B-NP O
job NN I-NP O
as IN B-PP O
a DT B-NP O
veterinary JJ I-NP B-PROFESSION
aide NN I-NP I-PROFESSION
- : O O
pt NN B-NP O
feels VBZ I-NP O
this DT B-NP O
was VBD B-VP O
due JJ B-ADJP O
to TO B-PP O
his PRP$ B-NP O
elevated JJ I-NP O
BG NNP I-NP O
, , O O
has VBZ B-VP O
called VBN I-VP O
in IN B-PP O
sick JJ B-NP O
a DT I-NP O
few JJ I-NP O
times NNS I-NP O
, , O O
sometimes RB B-ADVP O
very RB B-NP O
sleepy JJ I-NP O
.<BR>Lives NNS I-NP O
alone RB B-ADVP O
.<BR> . O O
Review NNP B-NP O
of IN I-NP O
Systems NNPS O O
No DT B-NP O
chest NN I-NP O
pain NN I-NP O
. . O O
&nbsp;No NN B-VP O
sob NNS B-NP O
. . O O
&nbsp;Occ NN B-VP O
diarrhea NN B-NP O
with IN B-PP O
metformin NN B-NP O
, , O O
manageable NN B-NP O
. . O O
&nbsp;No '' O O
abd NN B-NP O
pain NN I-NP O
x NN I-NP O
as IN B-PP O
per IN B-PP O
hpi NN B-NP O
, , O O
no DT B-NP O
n/v NN I-NP O
, , O O
brbpr NN B-NP O
, , O O
melena NN B-NP O
. . O O
&nbsp;No DT B-NP O
constipation NN I-NP O
. . O O
Wt '' O O
down RB B-ADVP O
6lb CD B-NP O
. . O O
&nbsp;Poor NNP O O
sleep. VBD B-VP O
&nbsp;Anhedonia NNP B-NP O
, , O O
no DT B-NP O
SI/HI. NNP I-NP O
&nbsp;Poor NNP I-NP O
motivation NN I-NP O
, , O O
but CC O O
trying VBG B-VP O
to TO I-VP O
make VB I-VP O
himself PRP B-NP O
take VB B-VP O
his PRP$ B-NP O
insulin NN I-NP O
, , O O
etc FW B-NP O
. . O O
&nbsp;nO NNP B-NP O
HYPOGLYCEMIC NNP I-NP O
SXS. . O O
Vital JJ B-NP O
Signs NNS I-NP O
Blood NN B-NP O
Pressure NN I-NP O
: : O O
110/61 CD B-NP O
Left VBN I-NP O
Arm NN I-NP O
Pulse NNP B-NP O
: : O O
61 CD B-NP O
Regular NNP I-NP O
Weight NNP B-NP O
: : O O
220 CD B-NP O
Pounds NNS I-NP O
Physical NNP B-NP O
Exam NNP I-NP O
Gen NNP B-NP O
: : O O
well RB B-ADVP O
appearing VBG B-VP O
, , O O
NAD NNP B-NP O
, , O O
good JJ B-NP O
spirits NNS I-NP O
. . B-PP O
&nbsp;HEENT NN B-NP O
: : O O
&nbsp;PERRL. NNP B-NP O
EOMI NNP I-NP O
. . I-NP O
OP NNP I-NP O
benign JJ I-NP O
w/mmm NN I-NP O
, , O O
no DT B-NP O
lesions NNS I-NP O
. . B-PP O
&nbsp;Neck NN B-NP O
: : O O
supple NN B-NP O
, , O O
full JJ B-NP O
ROM NNP I-NP O
, , O O
no DT B-NP O
LAN. NNP I-NP O
&nbsp;JVP NNP I-NP O
flat JJ I-NP O
. . O O
&nbsp;Carotids NNS B-VP O
2+ . B-NP O
b/l NN I-NP O
without IN B-PP O
bruits NNS B-NP O
. . B-NP O
&nbsp;Chest NN I-NP O
: : O O
&nbsp;Lungs NNP B-NP O
CTAB NNP I-NP O
, , O O
no DT B-NP O
wheezes NNS I-NP O
or CC I-NP O
rales NNS I-NP O
. . B-NP O
&nbsp;CV NN I-NP O
: : O O
&nbsp;RRR NN B-NP O
, , O O
nl JJ B-NP O
s1 NN I-NP O
, , O O
s2 NN B-NP O
, , O O
no DT B-NP O
m/r/g NN I-NP O
. . O O
&nbsp;Abd '' O O
: : O O
&nbsp;NABS NNP B-NP O
, , I-NP O
soft JJ I-NP O
, , I-NP O
NT/ND NNP I-NP O
, , O O
no DT B-NP O
HSM NNP I-NP O
, , O O
no DT B-NP O
guarding VBG I-NP O
. . I-NP O
&nbsp;Ext NNP I-NP O
: : O O
wwp NN B-NP O
, , O O
no DT B-NP O
edema NN I-NP O
, , I-NP O
clubbing VBG I-NP O
or CC I-NP O
cyanosis NN I-NP O
. . O O
&nbsp;DP '' O O
2+ CD B-NP O
b/l NN I-NP O
. . O O
&nbsp;Neuro '' O O
: : O O
nonfocal JJ B-NP O
exam NN I-NP O
. . O O
&nbsp; '' O O
Laboratory NNP B-NP O
Data NNPS I-NP O
bs NNS B-NP O
283 CD B-NP O
Impression NN B-NP O
41 CD B-NP B-AGE
m NN I-NP O
with IN B-PP O
poorly RB B-NP O
controlled VBN I-NP O
DM NNP I-NP O
, , O O
albuminuria NN B-NP O
, , O O
HCV NNP B-NP O
, , O O
hyperlipidemia NN B-NP O
, , O O
depressive JJ B-NP O
sxs NNS I-NP O
who WP B-NP O
comes VBZ B-VP O
for IN B-PP O
further JJ B-NP O
mgmt NN I-NP O
dm NN I-NP O
, , O O
depression NN B-NP O
after IN B-PP O
recent JJ B-NP O
job NN I-NP O
loss NN I-NP O
. . O O
Plan NN B-NP O
Depression NN B-NP O
: : O O
situational JJ B-NP O
. . O O
&nbsp;no NNP B-NP O
si/hi VBD B-VP O
.<BR>-inc JJ B-NP O
fluoxetine NN I-NP O
to TO B-PP O
40 CD B-NP O
qd NN I-NP O
, , O O
new JJ B-NP O
rx NNP I-NP O
given<BR>-fill NNP I-NP O
meds VBZ B-VP O
& CC I-VP O
f/u VBZ I-VP O
dr NN B-NP O
oliveira JJ I-NP B-DOCTOR
as IN B-PP O
planned<BR>-cont JJ B-NP O
work NN I-NP O
with IN B-PP O
legal JJ B-NP O
advocate NN I-NP O
and CC I-NP O
financial JJ I-NP O
counselor NN I-NP O
here RB B-ADVP O
to TO B-VP O
help VB I-VP O
with IN B-PP O
loss NN B-NP O
of IN B-PP O
job/insurance NN B-NP O
; : O O
disability NN B-NP O
forms NNS I-NP O
in IN B-PP O
process NN B-NP O
as IN B-PP O
well<BR>-support JJ B-NP O
offered<BR><BR>DM NN I-NP O
: : O O
a1c NN B-NP O
had VBD B-VP O
come VBN I-VP O
down RB B-ADVP O
from IN B-PP O
11.8-->9.9 CD B-NP O
, , O O
but CC O O
up RB B-ADVP O
to TO B-PP O
11.1 CD B-NP O
1/96 CD I-NP B-DATE
. . O O
&nbsp;no IN B-PP O
appreciable JJ B-NP O
improvemt NN I-NP O
in IN B-PP O
bs NNS B-NP O
with IN B-PP O
dietary JJ B-NP O
changes NNS I-NP O
and CC O O
some DT B-NP O
symptomatic JJ I-NP O
hyperglycemia NN I-NP O
, , O O
now RB B-ADVP O
better JJR B-NP O
since IN B-PP O
change NN B-NP O
in IN B-PP O
regimen<BR>--saw JJ B-NP O
dr NN I-NP O
. . O O
kenny NN B-NP B-DOCTOR
for IN B-PP O
additional JJ B-NP O
help/consultation NN I-NP O
, , O O
doing VBG B-VP O
substantially RB B-ADVP O
better RBR I-ADVP O
on IN B-PP O
nph JJ B-NP O
70/50 CD I-NP O
am/pm NN I-NP O
, , O O
humalog NN B-NP O
pre NN I-NP O
dinner<BR>--inc NN I-NP O
pm NN I-NP O
NPH NNP I-NP O
to TO B-PP O
55 CD B-NP O
units<BR>--cont NN I-NP O
metformin NN I-NP O
1000 CD B-NP O
bid NN I-NP O
( -LRB- O O
had VBD B-VP O
been VBN I-VP O
taking VBG I-VP O
tid NN B-NP O
by IN B-PP O
mistake NN B-NP O
; : O O
written VBN B-NP O
instructions NNS I-NP O
given VBN B-VP O
to TO B-PP O
dec JJ B-NP O
to TO B-VP O
bid VB I-VP O
)<BR>-- NNP B-NP O
had VBD B-VP O
f/u VBN I-VP O
ophtho RB I-VP O
scheduled VBN I-VP O
4/96 CD B-NP B-DATE
; : O O
will MD B-VP O
check VB I-VP O
to TO I-VP O
see VB I-VP O
if IN B-SBAR O
this DT B-NP O
occurred<BR>--malb NN I-NP O
elevated VBD B-VP O
200 CD B-NP O
11/94 CD I-NP B-DATE
; : O O
on IN B-PP O
acei--> JJ B-NP O
dec NN I-NP O
to TO B-PP O
35 CD B-NP O
in IN B-PP O
6/95 CD B-NP B-DATE
on IN B-PP O
inc NN B-NP O
dose NN I-NP O
acei NNS I-NP O
20 CD B-NP O
qd JJ I-NP O
lisinopril NN I-NP O
, , O O
recheck NN B-NP O
today<BR>--taking NN I-NP O
asa NN I-NP O
qd NN I-NP O
. . O O
&nbsp;<BR>--had '' O O
pneumovax NN B-NP O
2090 CD I-NP B-DATE
. . O O
&nbsp;<BR>--foot NNP B-NP O
exam NN I-NP O
nl NN I-NP O
12/93 CD I-NP B-DATE
.<BR>--flu NN I-NP O
shot NN I-NP O
done VBN B-VP O
at IN B-PP O
work NN B-NP O
2095 CD I-NP B-DATE
<BR>--bp NN I-NP O
at IN B-PP O
target NN B-NP O
on IN B-PP O
acei<BR><BR> JJ B-NP O
?OSA NNP I-NP O
: : O O
sxs NN B-VP O
suggestive<BR>-sleep NN B-NP O
study NN I-NP O
referral NN I-NP O
made VBD B-VP O
, , O O
appt VB B-VP O
sched VBN B-NP O
5/96 CD I-NP B-DATE
, , O O
unclear JJ B-ADJP O
if IN B-PP O
this DT B-NP O
happened VBD I-NP O
, , O O
will MD B-VP O
need VB I-VP O
to TO B-PP O
review<BR><BR>Albuminuria NNP B-NP O
: : O O
improved VBN B-VP O
on IN B-PP O
inc NN B-NP O
dose NN I-NP O
acei NNS I-NP O
. . O O
&nbsp;200s NNS B-NP O
11/94 . O B-DATE
--> NN B-NP O
36 CD I-NP O
in IN B-PP O
6/95 CD B-NP B-DATE
<BR>-na/k/cr JJ I-NP O
nl JJ I-NP O
1/96 CD I-NP B-DATE
<BR><BR>HCV NN I-NP O
: : O O
hiv NN B-NP O
was VBD B-VP O
neg JJ B-ADJP O
. . O O
&nbsp;hbv NN B-VP O
immune JJ B-NP O
( -LRB- I-NP O
hbv NN I-NP O
vax NN I-NP O
thru NN I-NP O
work NN I-NP O
) -RRB- B-VP O
. . B-NP O
&nbsp;hav NNP I-NP O
immune JJ I-NP O
. . O O
&nbsp;he PRP B-NP O
had VBD B-VP O
a DT B-NP O
needle NN I-NP O
stick NN I-NP O
around IN B-PP O
june NN B-NP B-DATE
2092 CD I-NP I-DATE
at IN B-PP O
work NN B-NP O
, , O O
was VBD B-VP O
n't RB I-VP O
tested VBN I-VP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
for IN B-PP O
hcv/hiv NN B-NP O
, , O O
but CC O O
had VBD B-VP O
f/u NN B-NP O
test NN I-NP O
( -LRB- I-NP O
for IN B-PP O
hiv NN B-NP O
only JJ I-NP O
apparently RB B-ADVP O
) -RRB- B-VP O
w/dr NN B-NP O
. . B-NP O
roberson NN I-NP B-DOCTOR
, , O O
neg NN B-NP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
. . B-NP O
hcv NN I-NP O
may MD B-VP O
well RB I-VP O
have VB I-VP O
been VBN I-VP O
from IN B-PP O
needle NN B-NP O
stick NN I-NP O
. . O O
&nbsp;ruq NN B-NP O
u/s NN I-NP O
was VBD B-VP O
nl RB B-ADVP O
, , O O
hcv NN B-NP O
genotype NN I-NP O
1a VBD B-VP O
. . B-NP O
&nbsp;lfts NNS I-NP O
have VBP B-VP O
been VBN I-VP O
consistently RB B-ADVP O
virtually RB I-ADVP O
nl RB I-ADVP O
, , O O
last JJ B-NP O
nl NN I-NP O
1/96 VBD B-VP B-DATE
<BR>-bx JJ B-ADJP O
with IN B-PP O
fibrosis<BR>-have JJ B-NP O
tried VBD B-VP O
to TO I-VP O
help VB I-VP O
him PRP B-NP O
get VB B-VP O
ifn NN B-NP O
at IN B-PP O
reduced JJ B-NP O
cost NN I-NP O
; : O O
see VB B-VP O
letters NNS B-NP O
to TO B-VP O
pt VB I-VP O
since IN B-PP O
1/95 CD B-NP B-DATE
; : O O
not RB B-NP O
discussed VBN I-NP O
today NN I-NP O
given VBN I-NP O
DM NNP I-NP O
priority NN I-NP O
issue<BR>-ast/alt NN I-NP O
today<BR><BR>Atypical JJ I-NP O
nevus NN I-NP O
: : O O
dnka NN B-NP O
appt NN I-NP O
w/derm NN I-NP O
for IN B-PP O
eval NN B-NP O
in IN B-PP O
3/94 CD B-NP B-DATE
. . O O
&nbsp;will NNP B-NP O
rerefer NN I-NP O
at IN B-PP O
future JJ B-NP O
visit NN I-NP O
. . O O
&nbsp;copays VBZ B-VP O
$ $ B-NP O
35 CD I-NP O
for IN B-PP O
nonpcp JJ B-NP O
visit NN I-NP O
- : O O
difficult JJ B-NP O
for IN B-PP O
him PRP B-NP O
. . O O
&nbsp;await VB B-VP O
clarification NN B-NP O
of IN B-PP O
insurance NN B-NP O
status NN I-NP O
( -LRB- B-VP O
hopefully RB B-ADVP O
will MD B-VP O
obtain VB I-VP O
free JJ B-NP O
care NN I-NP O
) -RRB- I-NP O
, , O O
and CC O O
can MD B-VP O
then RB I-VP O
rerefer<BR><BR>Hyperlipidemia VB I-VP O
: : O O
low JJ B-NP O
hdl JJ I-NP O
30 CD I-NP O
, , O O
ldl JJ B-ADJP O
141 CD B-NP O
on IN B-PP O
pravachol NN B-NP O
3/96 CD I-NP B-DATE
; : O O
per IN B-SBAR O
LMR NNP B-NP O
was VBD B-VP O
on IN B-PP O
40qd JJ B-NP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
, , O O
but CC O O
he PRP B-NP O
believes VBZ B-VP O
he PRP B-NP O
was VBD B-VP O
only RB I-VP O
taking VBG I-VP O
20qd JJ B-ADJP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
; : O O
confirms VBZ B-VP O
that IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
now RB I-VP O
been VBN I-VP O
on IN B-PP O
40 CD B-NP O
qd NN I-NP O
for IN B-PP O
at IN B-NP O
least JJS I-NP O
several JJ I-NP O
mos NNPS I-NP O
, , O O
however<BR>-recheck RB B-ADVP O
today NN B-NP O
on IN B-PP O
40 CD B-NP O
qd<BR>-lfts NNS I-NP O
nl JJ B-ADJP O
1/96 CD B-NP B-DATE
, , O O
recheck<BR><BR>ED VBD B-VP O
: : O O
suspect VB B-VP O
in IN B-PP O
part NN B-NP O
related VBN B-VP O
to TO B-PP O
DM NNP B-NP O
, , O O
had VBD B-VP O
good JJ B-NP O
response NN I-NP O
to TO B-PP O
small JJ B-NP O
dose NN I-NP O
viagra NN I-NP O
. . O O
&nbsp;mood NN B-NP O
issues NNS I-NP O
may MD B-VP O
contribute VB I-VP O
as RB B-ADVP O
well RB I-ADVP O
. . O O
&nbsp;improved VBD B-VP O
off RP B-PRT O
celexa DT B-NP O
.<BR>-has JJ I-NP O
prn NN I-NP O
rx NN I-NP O
for IN B-PP O
viagra NN B-NP O
, , O O
not RB O O
using VBG B-VP O
recently RB B-ADVP O
, , O O
not RB B-VP O
discussed VBN I-VP O
today<BR><BR>HM VBN I-VP O
: : O O
lipids NNS B-NP O
as IN B-PP O
above JJ B-NP O
. . O O
&nbsp;<BR>had NNP B-NP O
Td NNP I-NP O
booster NN I-NP O
2089 CD B-NP B-DATE
. . O O
&nbsp;<BR>re NNP B-NP O
: : O O
tob NN B-NP O
cessation/cutting VBG B-VP O
down IN B-PP O
- : O O
he PRP B-NP O
has VBZ B-VP O
made VBN I-VP O
sig JJ B-NP O
progress NN I-NP O
, , O O
not RB B-VP O
discussed VBN I-VP O
today NN B-NP O
. . O O
&nbsp;tried VBD B-VP O
wellbutrin RB B-ADVP O
in IN B-PP O
past JJ B-NP O
w/no NN I-NP O
effect NN I-NP O
. . O O
&nbsp;<BR>pneumovax NN B-NP O
utd NN I-NP O
. . O O
<BR>flu NN B-VP O
done VBN I-VP O
qyr<BR><BR>rtc JJ B-NP O
3-6 CD I-NP O
wks NNS I-NP O
depr JJ B-ADJP O
, , O O
DM NNP B-NP O
, , O O
?saw VBD B-VP O
ophtho/sleep NN B-NP O
study NN I-NP O
Kari NNP B-NP B-DOCTOR
Marlene NNP I-NP I-DOCTOR
Pryor NNP I-NP I-DOCTOR
, , O O
MD NNP B-NP O
