Record NNP B-NP O
date NN I-NP O
: : O O
2077-01-14 CD O B-DATE
HALE NNP B-NP B-HOSPITAL
MEMORIAL NNP I-NP I-HOSPITAL
HOSPITAL NNP I-NP I-HOSPITAL
Internal NNP B-NP O
Medicine NNP I-NP O
65 CD B-NP B-STREET
Dearborn NNP I-NP I-STREET
Street NNP I-NP I-STREET
Geiger NNP I-NP I-PATIENT
, , O I-PATIENT
Xian NNP B-NP I-PATIENT
Rayne NNP B-NP B-CITY
, , O O
MI NNP B-NP B-STATE
82978 CD I-NP B-ZIP
01729440 CD O B-MEDICALRECORD
01-14-77 CD O B-DATE
Mr. NNP B-NP O
Geiger NNP I-NP B-PATIENT
is VBZ B-VP O
a DT B-NP O
74 CD I-NP B-AGE
year NN I-NP O
old JJ I-NP O
man NN I-NP O
who WP B-NP O
comes VBZ B-VP O
in IN B-PP O
today NN B-NP O
for IN B-PP O
follow VB B-NP O
up IN B-PP O
of IN B-PP O
his PRP$ B-NP O
blood NN B-NP O
pressure NN I-NP O
medication NN I-NP O
as RB B-ADVP O
well RB I-ADVP O
as IN B-PP O
his PRP$ B-NP O
cholesterol NN I-NP O
level NN I-NP O
. . O O
I PRP B-NP O
have VBP B-VP O
been VBN I-VP O
readjusting VBG B-VP O
Mr. NNP B-NP O
Geiger NNP I-NP I-PATIENT
's POS B-NP I-PATIENT
blood NN I-NP O
pressure NN I-NP O
regimen VBN B-VP O
since IN B-SBAR O
he PRP B-NP O
left VBD B-VP O
Hale NNP B-NP B-HOSPITAL
Memorial NNP I-NP I-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
for IN B-PP O
an DT B-NP O
episode NN I-NP O
of IN B-PP O
gastroenteritis NN B-NP O
and CC I-NP O
hypovolemia NN I-NP O
several JJ B-NP O
months NNS I-NP O
ago RB B-ADVP O
. . O O
His PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
regimen VBN B-VP O
currently RB B-ADVP O
is VBZ B-VP O
HCTZ NNP B-NP O
25mg CD I-NP O
q.d. VBN B-VP O
, , O O
lisinopril NN B-NP O
, , O O
20mg JJ B-NP O
q.d NN I-NP O
. . O O
and CC O O
atenolol JJ B-NP O
25mg JJ I-NP O
q.d NN I-NP O
. . O O
He PRP B-NP O
apparently RB B-ADVP O
went VBD B-SBAR O
to TO B-PP O
an DT B-NP O
office NN I-NP O
visit NN I-NP O
at IN B-PP O
Dr. NNP B-NP O
Mueller NNP I-NP B-DOCTOR
office NN I-NP O
a DT B-NP O
week NN I-NP O
ago RB B-ADVP O
and CC O O
was VBD B-VP O
noted VBN I-VP O
there RB O O
to TO B-VP O
have VB I-VP O
high JJ B-NP O
blood NN I-NP O
pressure NN I-NP O
. . O O
She PRP B-NP O
prescribed VBD B-VP O
an DT B-NP O
increase NN I-NP O
in IN B-PP O
his PRP$ B-NP O
atenolol NN I-NP O
from IN B-PP O
25mg CD B-NP O
to TO B-PP O
50mg CD B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
not RB I-VP O
yet RB I-VP O
completed VBN I-VP O
that IN B-PP O
prescription NN B-NP O
. . O O
Mr. NNP O O
Geiger NNP B-NP I-PATIENT
's POS B-NP I-PATIENT
blood NN I-NP O
pressure NN I-NP O
today NN I-NP O
is VBZ B-VP O
180/80 CD B-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
any DT B-NP O
recent JJ I-NP O
chest NN I-NP O
pain NN B-NP O
, , O O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
, , I-NP O
lightheadedness NN I-NP O
or CC I-NP O
other JJ I-NP O
symptoms NNS I-NP O
. . O O
Mr. NNP B-NP O
Geiger NNP I-NP I-PATIENT
's POS B-NP I-PATIENT
cholesterol NN I-NP O
was VBD B-VP O
checked VBN I-VP O
by IN B-PP O
me PRP B-NP O
last JJ B-NP O
visit NN I-NP O
due RB B-ADVP O
to TO B-PP O
a DT B-NP O
modestly RB I-NP O
elevated VBN B-NP O
cholesterol NN I-NP O
one CD B-NP O
year NN I-NP O
ago IN B-PP O
which WDT B-NP O
had VBD B-VP O
not RB I-VP O
been VBN I-VP O
treated VBN I-VP O
. . O O
His PRP$ O O
current JJ B-NP O
cholesterol NN I-NP O
level NN I-NP O
was VBD B-VP O
total JJ B-ADJP O
283 JJ I-ADJP O
, , O O
HDL NNP B-NP O
54 CD I-NP O
, , O O
LDL NNP B-NP O
196 CD I-NP O
. . O O
REVIEW NN B-NP O
OF IN B-PP O
SYSTEMS NNP B-NP O
: : O O
Mr. NNP B-NP O
Geiger NNP I-NP B-PATIENT
denies VBZ B-VP O
any DT B-NP O
recent JJ I-NP O
fever NN I-NP O
, , O O
chills NNS B-NP O
, , O O
headache NN B-NP O
, , O O
chest NN B-NP O
pain NN I-NP O
, , O O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
, , I-NP O
cough NN I-NP O
, , I-NP O
nausea NN I-NP O
, , I-NP O
vomiting NN I-NP O
, , O O
diarrhea NN B-NP O
, , I-NP O
dysuria NN I-NP O
. . O O
PHYSICAL NNP B-NP O
EXAMINATION NNP I-NP O
: : O O
His PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
is VBZ B-VP O
180/80 CD B-NP O
. . O O
His PRP$ B-NP O
weight NN I-NP O
is VBZ B-VP O
184 CD B-NP O
. . O O
His PRP$ B-NP O
heart NN I-NP O
rate NN I-NP O
is VBZ B-VP O
80 CD B-NP O
. . O O
Lung NNP B-NP O
exam NN I-NP O
is VBZ B-VP O
clear JJ B-ADJP O
to TO B-PP O
auscultation NN B-NP O
bilaterally RB B-ADVP O
. . O O
The DT B-NP O
cardiac JJ I-NP O
exam NN I-NP O
shows VBZ B-VP O
a DT B-NP O
regular JJ I-NP O
rate NN I-NP O
and CC I-NP O
rhythm NN I-NP O
with IN B-PP O
normal JJ B-NP O
S1 NNP I-NP O
, , O O
S2 NNP B-NP O
, , O O
no UH O O
murmurs NNS B-NP O
. . B-VP O
Abdominal NNP B-NP O
exam NN I-NP O
is VBZ B-VP O
benign JJ B-ADJP O
. . O O
Extremities NNS B-NP O
show VBP B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-SBAR O
edema NN B-NP O
. . O O
Recent JJ B-NP O
laboratories NNS I-NP O
show VBP B-VP O
a DT B-NP O
chem NN I-NP O
7 CD I-NP O
panel NN I-NP O
of IN B-PP O
sodium NN B-NP O
141 CD I-NP O
, , O O
potassium NN B-NP O
4.5 CD I-NP O
, , O O
chloride NN B-NP O
101 CD I-NP O
, , O O
bicarb NN B-NP O
29 CD I-NP O
, , O O
BUN NNP B-NP O
11 CD I-NP O
, , I-NP O
creatinine CD I-NP O
1.1 CD I-NP O
, , O O
glucose JJ B-NP O
124 CD I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
a DT O O
normal JJ B-NP O
liver NN I-NP O
function NN I-NP O
test NN I-NP O
and CC O O
normal JJ B-NP O
calcium NN I-NP O
and CC I-NP O
magnesium NN I-NP O
. . O O
His PRP$ B-NP O
T4 NN I-NP O
is VBZ B-LST O
normal JJ B-NP O
at IN B-PP O
10.3 CD B-NP O
. . O O
His PRP$ B-NP O
THBR NN I-NP O
is VBZ B-VP O
normal JJ B-ADJP O
at IN B-PP O
0.98. CD B-NP O
ASSESSMENT NNP B-NP O
AND CC I-NP O
PLAN NNP I-NP O
: : O O
1 LS O O
. . B-NP O
Hypertension NNP I-NP O
. . O O
Mr. NNP B-NP O
Geiger NNP I-NP I-PATIENT
's POS B-NP I-PATIENT
blood NN I-NP O
pressure NN I-NP O
continues VBZ B-VP O
to TO I-VP O
be VB I-VP O
elevated VBN I-VP O
despite IN B-PP O
his PRP$ B-NP O
current JJ I-NP O
regimen NNS I-NP O
of IN B-PP O
HCTZ NNP B-NP O
and CC I-NP O
lisinopril NN I-NP O
and CC I-NP O
atenolol NN I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
recently RB I-VP O
given VBN I-VP O
an DT B-NP O
increased VBN I-NP O
atenolol NN I-NP O
dose NN I-NP O
from IN B-PP O
Dr. NNP B-NP O
Mueller NNP I-NP B-DOCTOR
. . O O
I PRP B-NP O
agree VBP B-VP O
with IN B-PP O
this DT B-NP O
decision NN I-NP O
and CC O O
will MD B-VP O
wait VB I-VP O
for IN B-PP O
him PRP B-NP O
to TO B-VP O
fill VB I-VP O
his PRP$ B-NP O
prescription NN B-NP O
and CC O O
begin VB B-VP O
this DT B-NP O
new JJ I-NP O
regimen NN I-NP O
before IN B-SBAR O
he PRP B-NP O
follows VBZ B-VP O
up RP B-PRT O
in IN B-NP O
a DT O O
few JJ B-NP O
weeks NNS I-NP O
for IN B-PP O
blood NN B-NP O
pressure NN I-NP O
check NN I-NP O
. . O O
2. DT B-NP O
Cholesterol NNP I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
's POS B-NP O
cholesterol NN I-NP O
is VBZ B-VP O
significantly RB I-VP O
elevated VBN I-VP O
. . O O
Given VBN B-VP O
his PRP$ B-NP O
comorbidities NNS I-NP O
, , O O
I PRP B-NP O
would MD B-VP O
aim VB I-VP O
for IN B-PP O
an DT B-NP O
LDL NNP I-NP O
level NN I-NP O
less JJR B-ADVP O
than IN B-PP O
130 CD B-NP O
. . O O
Thus RB B-ADVP O
, , O O
I PRP B-NP O
will MD B-VP O
begin VB I-VP O
a DT B-NP O
course NN I-NP O
of IN B-PP O
atorvastatin NN B-NP O
. . O O
His PRP$ B-NP O
current JJ I-NP O
liver NN B-NP O
function NN I-NP O
tests NNS I-NP O
are VBP B-VP O
normal JJ B-ADJP O
. . O O
HALE NNP B-NP B-HOSPITAL
MEMORIAL NNP I-NP I-HOSPITAL
HOSPITAL NNP I-NP I-HOSPITAL
Internal NNP B-NP O
Medicine NNP I-NP O
35 CD B-NP B-STREET
Dearborn NNP I-NP I-STREET
Street NNP I-NP I-STREET
Geiger NNP I-NP I-PATIENT
, , O I-PATIENT
Xian NNP B-NP I-PATIENT
Rayne NNP B-NP B-CITY
, , O O
MI NNP B-NP B-STATE
82978 CD I-NP B-ZIP
01729440 CD O B-MEDICALRECORD
01-14-77 CD O B-DATE
Page NNP B-NP O
2 CD I-NP O
3. VBG B-VP O
Health NNP B-NP O
maintenance NN I-NP O
. . O O
I PRP B-NP O
have VBP B-VP O
recommended VBN I-VP O
to TO B-PP O
him PRP B-NP O
losing VBG B-VP O
some DT B-NP O
weight NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
gained VBN I-VP O
6 CD B-NP O
pounds NNS I-NP O
since IN B-PP O
his PRP$ B-NP O
visits NNS I-NP O
last JJ B-NP O
month NN I-NP O
. . O O
He PRP B-NP O
attributes NNS B-LST O
this DT B-NP O
to TO B-PP O
his PRP$ B-NP O
holiday NN I-NP O
eating NN I-NP O
, , O O
but CC O O
he PRP B-NP O
says VBZ B-VP O
that IN B-SBAR O
he PRP B-NP O
gets VBZ B-VP O
a DT B-NP O
good JJ I-NP O
deal NN I-NP O
of IN B-PP O
exercise NN B-NP O
. . O O
I PRP B-NP O
will MD B-VP O
continue VB I-VP O
to TO I-VP O
recommend VB I-VP O
diet NN B-NP O
and CC I-NP O
exercise NN I-NP O
for IN B-PP O
him PRP B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
most RBS I-VP O
recently RB I-VP O
competed VBN I-VP O
a DT B-NP O
Pneumovax NN I-NP O
and CC O O
a DT B-NP O
flu NN I-NP O
vaccine NN I-NP O
last JJ O O
week NN B-NP O
. . O O
Nicholas NNP B-NP B-DOCTOR
Whaley NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
BS NNP B-NP B-DOCTOR
: : O O
HB1008 CD B-NP B-IDNUM
; : O O
DD NNP B-NP O
: : O O
01-14-77 CD B-NP B-DATE
; : O O
DT NNP B-NP O
: : O O
01-14-77 CD B-NP B-DATE
; : O O
DV NNP B-NP O
: : O O
01-14-77 CD O B-DATE
