Record NNP B-NP O
date NN I-NP O
: : O O
2121-08-10 CD O B-DATE
SMHFC NNP B-NP B-HOSPITAL
7 CD I-NP O
Intern NNP I-NP O
Admission NNP I-NP O
Note NN I-NP O
Patient NNP B-NP O
Name NNP I-NP O
: : O O
Uribe NNP B-NP I-PATIENT
, , O I-PATIENT
Walter NNP B-NP I-PATIENT
MRN NNP B-NP O
: : O O
4067033 CD O B-MEDICALRECORD
Date NNP B-NP O
of IN B-PP O
Admission NNP B-NP O
: : O O
8/09/2121 CD O B-DATE
Attending VBG B-VP O
: : O O
Thomas NNP B-NP B-DOCTOR
Wyatt NNP I-NP I-DOCTOR
PCP NNP B-NP O
: : O O
Ulisses NNP B-NP B-DOCTOR
Xuan NNP I-NP I-DOCTOR
( -LRB- O O
Santa NNP B-NP B-HOSPITAL
Barbara NNP I-NP I-HOSPITAL
General NNP I-NP I-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
) -RRB- O O
Source NN B-NP O
of IN B-PP O
History NNP B-NP O
: : O O
Patient NNP B-NP O
and CC O O
medical JJ B-NP O
record NN I-NP O
CC/RFA NNP B-NP O
: : O O
SOB NNP B-NP O
, , O O
extremity NN B-NP O
edema NN I-NP O
, , O O
abdominal JJ B-NP O
discomfort NN I-NP O
HPI NNP B-NP O
: : O O
This DT B-NP O
53 CD I-NP B-AGE
yoM NNP I-NP O
with IN B-PP O
a DT B-NP O
hx NN I-NP O
of IN B-PP O
morbid NN B-NP O
obesity NN I-NP O
, , O O
CHF NNP B-NP O
, , O O
COPD NNP B-NP O
, , O O
Diabetes NNP B-NP O
and CC O O
OSA NNP B-NP O
reports VBZ B-VP O
a DT B-NP O
increase NN I-NP O
in IN B-PP O
his PRP$ B-NP O
weight NN I-NP O
from IN B-PP O
395 CD B-NP O
lb NN I-NP O
to TO B-PP O
450 CD B-NP O
lb NN I-NP O
over IN B-PP O
the DT B-NP O
last JJ I-NP O
2-4 JJ I-NP O
weeks NNS I-NP O
. . O O
This DT O O
occurred VBD B-VP O
despite IN B-PP O
his PRP$ B-NP O
efforts NNS I-NP O
to TO B-VP O
lose VB I-VP O
weight NN B-NP O
and CC O O
his PRP$ B-NP O
active JJ I-NP O
participation NN I-NP O
in IN B-PP O
a DT B-NP O
weight NN I-NP O
watchers NNS I-NP O
weight NN I-NP O
reduction NN I-NP O
program NN I-NP O
. . O O
The DT B-NP O
weight NN I-NP O
gain NN I-NP O
was VBD B-VP O
accompanied VBN I-VP O
by IN B-PP O
abdominal JJ B-NP O
distension NN I-NP O
and CC I-NP O
bloating NN I-NP O
, , O O
increased VBD B-VP O
leg NN B-NP O
swelling VBG B-VP O
and CC I-VP O
increasing VBG I-VP O
SOB. NNP B-NP O
He PRP B-NP O
also RB B-ADVP O
reports VBZ B-VP O
severe JJ B-NP O
DoE NNP I-NP O
, , O O
with IN B-PP O
a DT B-NP O
maximal JJ I-NP O
walking NN I-NP O
distance NN I-NP O
of IN B-PP O
5-6 CD B-NP O
steps NNS I-NP O
, , O O
as RB B-CONJP O
well RB I-CONJP O
as IN I-CONJP O
a DT B-NP O
deteriorating VBG I-NP O
a DT B-NP O
scrotal NN I-NP O
edema NN I-NP O
with IN B-PP O
some DT B-NP O
dysuria NN I-NP O
, , O O
and CC O O
rectal JJ B-NP O
incontinence NN I-NP O
. . O O
Since IN B-PP O
the DT B-NP O
recent JJ I-NP O
weight NN I-NP O
gain NN I-NP O
, , O O
he PRP B-NP O
also RB B-ADVP O
developed VBD B-VP O
an DT B-NP O
extensive JJ I-NP O
itchy NN I-NP O
erythema NN I-NP O
in IN B-PP O
his PRP$ B-NP O
groins NNS I-NP O
. . O O
He PRP B-NP O
denies VBZ B-VP O
CP CD B-NP O
, , O O
diarrhea NN B-NP O
, , O O
HA NNP B-NP O
, , O O
fever NN B-NP O
, , O O
chills NNS B-NP O
, , O O
cough NN B-NP O
. . O O
His PRP$ B-NP O
PCP NNP I-NP O
prescribed VBN I-NP O
metoclopramid NN I-NP O
and CC I-NP O
protonix NN I-NP O
for IN B-PP O
his PRP$ B-NP O
abdominal JJ I-NP O
complaints NNS I-NP O
; : O O
however RB B-ADVP O
, , O O
the DT B-NP O
patient NN I-NP O
felt VBD B-VP O
dizzy JJ B-ADJP O
and CC I-ADJP O
dehydrated VBN I-ADJP O
after IN B-PP O
taking VBG B-VP O
these DT B-NP O
medications NNS I-NP O
and CC O O
decided VBD B-VP O
to TO I-VP O
discontinue VB I-VP O
those DT B-NP O
. . O O
He PRP B-NP O
also RB B-ADVP O
stopped VBD B-VP O
taking VBG I-VP O
his PRP$ B-NP O
regular JJ I-NP O
lasix NN I-NP O
medication NN I-NP O
about IN B-PP O
a DT B-NP O
week NN I-NP O
ago RB B-ADVP O
. . O O
Because IN B-PP O
of IN I-PP O
his PRP$ B-NP O
increasing VBG I-NP O
SOB NN I-NP O
, , O O
he PRP B-NP O
called VBD B-VP O
EMS NNP B-NP O
, , O O
who WP B-NP O
found VBD B-VP O
him PRP B-NP O
cyanotic JJ B-ADJP O
in IN B-PP O
his PRP$ B-NP O
apartment NN I-NP O
with IN B-PP O
an DT B-NP O
Sa02 NNP I-NP O
of IN B-PP O
73 CD B-NP O
% NN I-NP O
on IN B-PP O
RA. NNP B-NP O
ED VBN B-NP O
Course NNP I-NP O
: : O O
On IN B-PP O
arrival NN B-NP O
in IN B-PP O
the DT B-NP O
ED NNP I-NP O
, , O O
his PRP$ B-NP O
VS NNP I-NP O
were VBD B-VP O
: : O O
T98 CD B-NP O
, , I-NP O
BP108/65 CD I-NP O
, , O O
RR24 NNP B-NP O
, , O O
HR100 CD B-NP O
, , O O
O2Sa NNP B-NP O
92 CD I-NP O
% NN I-NP O
on IN B-PP O
4L JJ B-NP O
02 CD I-NP O
. . O O
He PRP B-NP O
received VBD B-VP O
one CD B-NP O
dose NN I-NP O
of IN B-PP O
lasix NN B-NP O
80mg CD I-NP O
iv NN I-NP O
, , O O
urine JJ B-NP O
output NN I-NP O
unrecorded JJ I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
transferred VBN I-VP O
to TO B-PP O
Internal NNP B-NP O
Medicine NNP I-NP O
for IN B-PP O
further JJ B-NP O
management NN I-NP O
. . O O
PMH/PSH NNP B-NP O
: : O O
Obstructive JJ B-NP O
sleep NN I-NP O
apnea NN I-NP O
COPD NN B-NP O
CHF NNP B-NP O
( -LRB- I-NP O
EF NN I-NP O
in IN B-PP O
2117 CD B-NP B-DATE
: : O O
53 CD B-NP O
% NN I-NP O
) -RRB- O O
Hyperlipidemia NNP B-NP O
Pulmonary NNP B-NP O
hypertension NN I-NP O
HTN . O O
NIDDM . O O
Venous JJ B-NP O
stasis NN I-NP O
with IN B-PP O
chronic JJ B-NP O
leg NN I-NP O
ulcers NNS I-NP O
Morbid NNP B-NP O
obesity NN I-NP O
Peripheral NNP B-NP O
neuropathy NN I-NP O
S/p NNP B-NP O
PNAx2 CD I-NP O
Medications NNS B-NP O
: : O O
Aspirin NNP B-NP O
325 CD I-NP O
QD . O O
Verapamil NNP B-NP O
60mg CD I-NP O
TID NN I-NP O
Glybyride NNP B-NP O
5mg CD I-NP O
QD . O O
Lasix NNP B-NP O
80mg CD I-NP O
QD . O O
Protonix NNP B-NP O
40mg CD I-NP O
QD . O O
Metoclopramide NNP B-NP O
5mg CD I-NP O
QD . O O
Family NNP B-NP O
Hx NNP I-NP O
: : O O
Mother NNP B-NP O
: : O O
Diabetes NNP B-NP O
, , O O
Father/son NNP B-NP O
: : O O
bipolar JJ B-NP O
disorder NN I-NP O
. . O O
Social NNP B-NP O
Hx NNP I-NP O
: : O O
Married NNP B-NP O
, , O O
two CD B-NP O
children NNS I-NP O
, , O O
used VBN B-VP O
to TO I-VP O
work VB I-VP O
as IN B-ADVP O
die VBP B-VP B-PROFESSION
setter NN B-NP I-PROFESSION
for IN B-PP O
25 CD B-NP O
years NNS I-NP O
, , O O
has VBZ B-VP O
not RB I-VP O
worked VBN I-VP O
for IN B-PP O
last JJ B-NP O
5 CD I-NP O
years NNS I-NP O
. . O O
Quite RB B-VP O
smoking VBG I-VP O
6 CD B-NP O
years NNS I-NP O
ago RB B-ADVP O
, , O O
total JJ B-NP O
ca MD B-VP O
. . B-NP O
30-40 CD I-NP O
py NN I-NP O
. . O O
Denies NNS B-VP O
EtOH NNP B-NP O
, , O O
illicit JJ B-NP O
drugs NNS I-NP O
. . O O
Allergies NNP B-NP O
: : O O
NKDA NNP O O
Physical JJ B-NP O
Exam NNP I-NP O
: : O O
VS NNP B-NP O
: : O O
T97.9 CD B-NP O
, , I-NP O
P101 CD I-NP O
, , O O
BP NNP B-NP O
117/55 CD I-NP O
, , O O
RR20 NNP B-NP O
, , O O
Sa02 NNP B-NP O
85 CD I-NP O
% NN I-NP O
on IN B-PP O
RA NNP B-NP O
, , O O
92 CD B-NP O
% NN I-NP O
on IN B-PP O
3l JJ B-NP O
02 CD I-NP O
General NNP B-NP O
: : O O
interactive JJ B-NP O
, , I-NP O
mild JJ I-NP O
respiratory JJ I-NP O
distress NN I-NP O
, , O O
HEENT NNP B-NP O
: : O O
EOMI NNP B-NP O
, , O O
PERRLA NNP B-NP O
, , O O
AT WDT O O
Neck NNP B-NP O
: : O O
no DT B-NP O
LAN NN I-NP O
CV NNP B-NP O
: : O O
basal NN B-NP O
crackles NNS I-NP O
bilaterally RB B-LST O
Chest NNP B-NP O
: : O O
S1 NNP B-NP O
S2 NNP I-NP O
, , O O
RRR NNP B-NP O
, , O O
Abd NNP B-NP O
: : O O
morbid NN B-NP O
obesity NN I-NP O
, , O O
BS+ NNP B-NP O
, , O O
mild JJ B-NP O
diffuse JJ I-NP O
tenderness NN I-NP O
in IN B-PP O
r NN B-NP O
lower JJR I-NP O
abdomen NN I-NP O
, , O O
large JJ B-NP O
itching NN I-NP O
erythema NN I-NP O
in IN B-PP O
groins NNS B-NP O
bilaterally RB B-ADVP O
. . O O
3+ JJ B-NP O
Scrotal NNP I-NP O
edema NN I-NP O
Back RB B-ADVP O
: : O O
diffuse NN B-NP O
tenderness NN I-NP O
in IN B-PP O
R NN B-NP O
flank NN I-NP O
Ext JJ B-NP O
: : O O
2+ JJ B-NP O
edema NN I-NP O
. . O O
Peripheral JJ B-NP O
pulses+ NN I-NP O
, , O O
LE JJ B-NP O
cool JJ I-NP O
. . O O
Neuro NNP B-NP O
: : O O
alert JJ B-NP O
, , I-NP O
oriented JJ I-NP O
x3 NN I-NP O
, , O O
CN NNP B-NP O
II-XII NNP I-NP O
ok NN I-NP O
, , O O
no DT B-NP O
sensation NN I-NP O
defects NNS I-NP O
Skin NNP B-NP O
: : O O
granulated JJ B-NP O
leg NN I-NP O
ulcer NN I-NP O
on IN B-PP O
R NN B-NP O
LE JJ I-NP O
, , I-NP O
bilateral JJ I-NP O
mal-odorous JJ I-NP O
groin NN I-NP O
erythemas NNS I-NP O
Labs NNS B-NP O
: : O O
WBC NNP B-NP O
7.3 CD I-NP O
( -LRB- I-NP O
4.5-11.0) JJ I-NP O
th/cmm NN I-NP O
HCT NN B-NP O
43.1 CD I-NP O
( -LRB- O O
41.0-53.0) CD B-NP O
% NN I-NP O
HGB NN B-NP O
14.9 CD I-NP O
( -LRB- I-NP O
13.5-17.5 CD I-NP O
) -RRB- I-NP O
gm/dl . O O
RBC NNP B-NP O
4.69 CD I-NP O
( -LRB- I-NP O
4.50-5.90 CD I-NP O
) -RRB- I-NP O
mil/cmm . O O
PLT NNP B-NP O
186 CD I-NP O
( -LRB- I-NP O
150-350 CD I-NP O
) -RRB- I-NP O
th/cumm . O O
MCV JJ B-NP O
92 CD I-NP O
( -LRB- I-NP O
80-100 CD B-PP O
) -RRB- B-NP O
fl NN I-NP O
MCH NNP B-NP O
31.8 CD I-NP O
( -LRB- I-NP O
26.0-34.0) JJ I-NP O
pg/rbc NN I-NP O
MCHC NNP B-NP O
34.6 CD I-NP O
( -LRB- O O
31.0-37.0) CD B-NP O
g/dl NN I-NP O
RDW NNP B-NP O
16.1 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
11.5-14.5 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Superstat NNP B-NP O
PT NNP I-NP O
15.2 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
11.1-13.6 CD B-PP O
) -RRB- B-NP O
sec NN I-NP O
Superstat NNP B-NP O
PT-INR NNP I-NP O
1.3 CD O O
Superstat NNP B-NP O
APTT NNP I-NP O
29.0 CD I-NP O
( -LRB- O O
22.1-34.0) CD B-NP O
sec NN I-NP O
Diff JJ B-NP O
Method NNP I-NP O
Auto NN I-NP O
Poly NNP B-NP O
76 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
40-70 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Lymphs NNP B-NP O
16 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
22-44 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Monos NNP B-NP O
5 CD I-NP O
( -LRB- I-NP O
4-11 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
EOS NNP B-NP O
2 CD I-NP O
(0-8 CD I-NP O
) -RRB- O O
% NN O O
Basos NNS B-NP O
1 CD B-NP O
(0-3 JJ I-NP O
) -RRB- I-NP O
% NN I-NP O
Absolute JJ B-NP O
Neuts NNP I-NP O
5.61 CD I-NP O
( -LRB- I-NP O
1.8-7.7 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Lymphs NNP I-NP O
1.13 CD I-NP O
( -LRB- I-NP O
1.0-4.8 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Monos NNP I-NP O
0.36 CD I-NP O
( -LRB- I-NP O
0.2-0.4 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
EOS NNP I-NP O
0.15 CD I-NP O
( -LRB- I-NP O
0.1-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Basos NNP I-NP O
0.06 CD I-NP O
( -LRB- I-NP O
0.0-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Aniso NNP B-NP O
1+ CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Hypo NNP B-NP O
1+ CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Macrocytes NNP B-NP O
None NN I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Calcium NNP B-NP O
7.1 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
8.5-10.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Phosphorus JJ B-NP O
3.5 CD I-NP O
( -LRB- I-NP O
2.6-4.5 CD B-NP O
) -RRB- I-NP O
mg/dl . O O
Magnesium NNP B-NP O
1.2 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
1.4-2.0) CD I-NP O
meq/L NN I-NP O
Total JJ B-NP O
Protein NNP I-NP O
6.4 CD I-NP O
( -LRB- I-NP O
6.0-8.3 CD I-NP O
) -RRB- I-NP O
g/dl . O O
Albumin NNP B-NP O
2.8 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
3.3-5.0) JJ I-NP O
g/dl NN I-NP O
Globulin NNP B-NP O
3.6 CD I-NP O
( -LRB- I-NP O
2.6-4.1 CD I-NP O
) -RRB- I-NP O
g/dl . O O
Direct NNP B-NP O
Bilirubin NNP I-NP O
0.4 CD I-NP O
(0-0.4 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Total JJ B-NP O
Bilirubin NNP I-NP O
0.7 CD I-NP O
( -LRB- O O
0.0-1.0) CD B-NP O
mg/dl NN I-NP O
Alkaline NNP B-NP O
Phosphatase NNP I-NP O
87 CD I-NP O
( -LRB- I-NP O
45-115 CD I-NP O
) -RRB- I-NP O
U/L . O O
Transaminase-SGPT NN B-NP O
42 CD I-NP O
( -LRB- I-NP O
10-55 CD I-NP O
) -RRB- I-NP O
U/L . O O
Amylase NNP B-NP O
24 CD I-NP O
(3-100 CD I-NP O
) -RRB- O O
units/L NN O O
Lipase NN B-NP O
3.2 CD I-NP O
( -LRB- O O
1.3-6.0) CD B-NP O
U/dl NN I-NP O
NT-proBNP NNP B-NP O
1326 CD I-NP O
H NNP B-NP O
(0-900 CD I-NP O
) -RRB- I-NP O
pg/ml . O O
Transaminase-SGOT NNP B-NP O
42 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
10-40 CD I-NP O
) -RRB- I-NP O
U/L . O O
Sodium NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
137 CD I-NP O
( -LRB- I-NP O
135-145 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Potassium NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
4.1 CD I-NP O
( -LRB- I-NP O
3.4-4.8 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Chloride NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
102 CD I-NP O
( -LRB- I-NP O
100-108 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
CO2 NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
33.3 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
23.0-31.9 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
BUN NNP B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
22 CD I-NP O
(8-25 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Creatinine NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NN I-NP O
) -RRB- B-VP O
0.9 CD B-NP O
( -LRB- I-NP O
0.6-1.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Glucose FW B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
159 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
70-110 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Creatine JJ B-NP O
Kinase NNP I-NP O
Isoenzymes NNP I-NP O
NEGATIVE NNP I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
Troponin-I JJ B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Specific JJ B-NP O
Gravity NNP I-NP O
1.015 CD I-NP O
( -LRB- I-NP O
1.001-1.035 CD I-NP O
) -RRB- O O
UA-pH NNP B-NP O
5.0 CD I-NP O
( -LRB- I-NP O
5.0-9.0) CD O O
UA-WBC NNP B-NP O
Screen NNP I-NP O
NEGATIVE NNP I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Nitrite JJ B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Albumin NN B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Glucose JJ B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Ketones NNP B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Occult JJ B-NP O
Blood NN I-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
EKG NNP B-NP O
: : O O
SR NNP B-NP O
@90 CD I-NP O
BPM NNP I-NP O
, , I-NP O
low JJ I-NP O
voltage NN I-NP O
, , O O
1 CD B-NP O
. . O O
degree NN B-VP O
heart NN B-NP O
block NN I-NP O
, , O O
right JJ B-NP O
axis NN I-NP O
deviation NN I-NP O
Radiology NNP B-NP O
: : O O
CXR NN B-NP O
( -LRB- B-VP O
portable JJ B-NP O
) -RRB- I-NP O
: : O O
Low JJ B-NP O
lung NN I-NP O
volumes NNS I-NP O
. . O O
Pulmonary NNP B-NP O
vascular JJ I-NP O
redistribution NN I-NP O
cannot MD B-VP O
be VB I-VP O
excluded VBN I-VP O
on IN B-PP O
this DT B-NP O
semi NN I-NP O
upright RB B-NP O
film NN I-NP O
. . O O
CXR NN B-NP O
( -LRB- I-NP O
pa/lat NN I-NP O
) -RRB- I-NP O
: : O O
Mild JJ B-NP O
pulmonary JJ I-NP O
congestion NN I-NP O
with IN B-PP O
cardiomegaly JJ B-NP O
. . O O
Small JJ B-NP O
right JJ I-NP O
pleural JJ I-NP O
effusion NN I-NP O
. . O O
Stable NNP B-NP O
elevated VBD B-VP O
right JJ B-NP O
hemidiaphragm NN I-NP O
. . O O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
: : O O
53 CD B-NP B-AGE
yoM NNP I-NP O
with IN B-PP O
hx NN B-NP O
of IN B-PP O
morbid NN B-NP O
obesity NN I-NP O
, , O O
CHF NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
COPD NNP B-NP O
, , O O
DM NNP B-NP O
type NN I-NP O
2 CD B-NP O
, , O O
OSA NNP B-NP O
, , O O
p/w RB B-VP O
increasing VBG I-VP O
SOB NNP B-NP O
and CC O O
abdominal JJ B-NP O
discomfort NN I-NP O
. . O O
SOB NNP B-NP O
: : O O
Most RBS B-NP O
likely JJ I-NP O
related VBN B-VP O
to TO B-PP O
a DT B-NP O
combination NN I-NP O
of IN B-PP O
CHF NNP B-NP O
flare NN I-NP O
( -LRB- B-VP O
due JJ B-ADJP O
to TO B-VP O
lasix VB I-VP O
discontinuation NN B-NP O
, , O O
BNP JJ B-NP O
1326 CD I-NP O
) -RRB- I-NP O
and CC O O
COPD NNP B-NP O
( -LRB- I-NP O
PFT NN I-NP O
in IN B-PP O
2120 CD B-NP B-DATE
indicated VBD B-VP O
severe JJ B-NP O
obstructive JJ I-NP O
and CC I-NP O
restrictive JJ I-NP O
deficit NN I-NP O
) -RRB- I-NP O
. . O O
CXR NNP B-NP O
showing VBG B-VP O
cardiomegaly JJ B-NP O
and CC I-NP O
right-sided JJ I-NP O
pleural JJ I-NP O
effusion NN I-NP O
, , O O
consistent JJ B-ADJP O
with IN B-PP O
CHF. NNP B-NP O
Started NNP I-NP O
on IN B-PP O
oxygen NN B-NP O
, , O O
lasix NN B-NP O
, , O O
combivent NN B-NP O
nebs NNS I-NP O
. . O O
Will NNP B-NP O
reevaluate JJ I-NP O
cardiac JJ I-NP O
function NN I-NP O
with IN B-PP O
TTE. NNP B-NP O
In IN B-PP O
the DT B-NP O
absence NN I-NP O
of IN B-PP O
CP CD B-NP O
, , O O
PE NN B-NP O
unlikely JJ I-NP O
. . O O
Cardiac NNP B-NP O
enzymes VBZ B-VP O
negative JJ B-ADJP O
. . O O
CHF NNP B-NP O
: : O O
Currently RB B-NP O
treated VBN I-NP O
with RP I-NP O
Verapamil NNP I-NP O
for IN B-PP O
afterload JJ B-NP O
reduction NN I-NP O
. . O O
Will MD B-VP O
consider VB I-VP O
to TO I-VP O
switch VB I-VP O
Verapamil NNP B-NP O
to TO B-PP O
ACEI. NNP B-NP O
Reinitiated NNP I-NP O
Lasix NNP I-NP O
. . O O
HTN NNP B-NP O
: : O O
patient NN B-NP O
here RB B-ADVP O
normotensive JJ B-ADJP O
. . O O
Currently RB O O
taking VBG B-VP O
verapamil RP B-NP O
, , O O
however RB B-ADVP O
, , O O
1 CD B-NP O
. . O O
degree NN B-VP O
heart NN B-NP O
block NN I-NP O
. . O O
Will MD B-VP O
consider VB I-VP O
switching VBG I-VP O
to TO B-PP O
ACEI. NNP B-NP O
OSA NNP B-NP O
: : O O
Patient NNP B-NP O
on IN B-PP O
home NN B-NP O
oxygen NN I-NP O
. . O O
Will MD B-VP O
suggest VB I-VP O
CPAP/BiPAP NNP B-NP O
Diabetes NNP B-NP O
: : O O
Currently RB B-VP O
taking VBG I-VP O
Glybyride NNP B-NP O
, , O O
will MD B-VP O
obtain VB I-VP O
HBA1c NNP B-NP O
here RB B-ADVP O
, , O O
keep VB B-VP O
on IN B-PP O
RISS NNP B-NP O
while IN B-LST O
inpatient NN B-NP O
. . O O
Abdominal JJ B-NP O
discomfort/bloating NN I-NP O
: : O O
Most RBS B-NP O
likely JJ I-NP O
related VBN B-VP O
to TO B-PP O
recent JJ B-NP O
weight NN I-NP O
gain NN I-NP O
of IN B-PP O
30 CD B-NP O
lbs NNS I-NP O
, , O O
diabetic JJ B-NP O
gastroparesis NN I-NP O
might MD B-VP O
also RB I-VP O
be VB I-VP O
contributing VBG I-VP O
. . B-NP O
Patient NNP I-NP O
unable JJ B-ADJP O
to TO B-VP O
tolerate VB I-VP O
metoclopramide NN B-NP O
. . O O
Discussed VBN B-VP O
possibility NN B-NP O
of IN B-PP O
gastric JJ B-NP O
bypass NN I-NP O
, , O O
patient JJ B-NP O
rejects NNS I-NP O
. . O O
Rectal NNP B-NP O
incontinence NN I-NP O
: : O O
Might MD B-VP O
be VB I-VP O
related VBN I-VP O
to TO B-PP O
diabetic JJ B-NP O
neuropathy NN I-NP O
. . O O
Patient NNP B-NP O
also RB B-ADVP O
unable JJ B-ADJP O
to TO B-VP O
perform VB I-VP O
anal JJ B-NP O
hygiene NN I-NP O
because IN B-PP O
of IN I-PP O
obesity NN B-NP O
. . O O
Groin NNP B-NP O
erythema NN I-NP O
: : O O
Suggestive NNP B-NP O
of IN B-PP O
fungal JJ B-NP O
infection NN I-NP O
. . O O
Will MD B-VP O
treat VB I-VP O
symptomatically RB B-ADVP O
with IN B-PP O
miconazole NN B-NP O
and CC O O
obtain VB B-VP O
dermatology NN B-NP O
consult VB B-VP O
. . O O
RLE JJ B-NP O
ulcer NN I-NP O
: : O O
Granulating NNP B-NP O
leg NN I-NP O
ulcer NN I-NP O
, , O O
Will MD B-VP O
continue VB I-VP O
topical JJ B-NP O
care NN I-NP O
. . O O
Prophylaxis NNP B-NP O
: : O O
Fragmin NNP B-NP O
SQ NNP I-NP O
, , O O
Nexium NNP B-NP O
Code NNP B-NP O
Status NNP I-NP O
: : O O
Full NNP B-NP O
Matthew NNP B-NP B-DOCTOR
Jackman NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
, , O O
Ph NNP B-NP O
. . O O
D. NNP O O
PGY-1 NN B-NP O
, , O O
# # B-NP O
37714 CD I-NP B-PHONE
