Record NNP B-NP O
date NN I-NP O
: : O O
2077-07-06 CD O B-DATE
SDU NNP B-NP O
JAR NNP I-NP O
Admit NNP I-NP O
Note NN I-NP O
Patient NNP B-NP O
: : O O
Horne NNP B-NP I-PATIENT
, , O I-PATIENT
Milton NNP B-NP I-PATIENT
GMH NNP B-NP B-HOSPITAL
Unit NN I-NP O
Number NN I-NP O
: : O O
2177024 CD O B-MEDICALRECORD
Date NNP B-NP O
of IN B-PP O
Admission NNP B-NP O
: : O O
7/06/77 CD O B-DATE
Attending VBG B-VP O
Physician JJ B-ADJP O
: : O O
Dang VBG B-UCP B-DOCTOR
PCP NNP B-NP O
: : O O
Nathan NNP B-NP B-DOCTOR
Whitley NNP I-NP I-DOCTOR
Code NNP B-NP O
Status NNP I-NP O
: : O O
Full NNP B-NP O
Chief NNP B-NP O
Complaint NNP I-NP O
: : O O
Chest NNP B-NP O
pain NN I-NP O
. . O O
HPI NNP B-NP O
: : O O
63 CD B-NP B-AGE
yo NNP I-NP O
M NNP I-NP O
p/w VBD B-VP O
acute JJ B-NP O
onset NN I-NP O
SOB NNP I-NP O
and CC I-NP O
chest NN I-NP O
pain NN I-NP O
around IN B-PP O
11 CD B-NP O
AM VBP B-VP O
on IN B-PP O
7/05 CD B-NP B-DATE
. . O O
Patient NNP B-NP O
awoke VBD B-VP O
this DT B-NP O
AM VBP B-VP O
with IN B-PP O
indigestion NN B-NP O
and CC O O
increased VBD B-NP O
amount NN I-NP O
of IN B-PP O
burping VBG B-NP O
. . O O
Pain NNP B-NP O
persisted VBD B-VP O
despite IN B-PP O
taking VBG B-VP O
Nexium JJ B-NP O
x2 NN I-NP O
, , O O
and CC O O
increased VBD B-VP O
in IN B-PP O
intes NNS B-NP O
nsity NN I-NP O
. . O O
Some DT B-NP O
R NN I-NP O
( -LRB- I-NP O
not RB I-NP O
L) JJ I-NP O
hand NN I-NP O
tingling VBG B-VP O
. . B-NP O
Denies NNS I-NP O
Jaw/shoulder/L . O O
arm NN B-NP O
pain NN I-NP O
. . O O
( -LRB- O O
Did VBD B-VP O
have VB I-VP O
left VBN B-NP O
elbow NN I-NP O
tenderness NN I-NP O
2 CD B-NP O
days NNS I-NP O
prior RB B-ADVP O
) -RRB- B-VP O
. . O O
Some DT B-NP O
diaphroesis NN I-NP O
but CC O O
no DT B-NP O
N/V NN I-NP O
. . O O
Called VBN B-VP O
PCP NNP B-NP O
office NN I-NP O
, , O O
who WP B-NP O
instructed VBD B-VP O
him PRP B-NP O
to TO B-VP O
go VB I-VP O
to TO B-PP O
to TO B-NP O
the DT B-NP O
ER NNP I-NP O
. . I-NP O
Patient NNP I-NP O
called VBD B-VP O
EMS&gt NNP B-NP O
; : O O
Given VBN B-VP O
ASA NNP B-NP O
by IN B-PP O
EMS. NNP B-NP O
In IN B-PP O
the DT B-NP O
ED NNP I-NP O
, , O O
HR NNP B-NP O
85 CD I-NP O
, , O O
BP NNP B-NP O
158/88 CD I-NP O
, , O O
RR NNP B-NP O
16 CD I-NP O
and CC O O
sating VBG B-VP O
96 CD B-NP O
% NN I-NP O
on IN B-PP O
RA. NNP B-NP O
CP CD I-NP O
4/10 CD I-NP O
, , O O
not RB B-VP O
relieved VBN I-VP O
with IN B-PP O
Nitro NNP B-NP O
x3 CD I-NP O
. . O O
Pain NNP B-NP O
was VBD B-VP O
relieved VBN I-VP O
by IN B-PP O
Morphine NNP B-NP O
(4 NNP I-NP O
, , O O
4 CD B-NP O
, , O O
2 CD B-NP O
mg NN I-NP O
) -RRB- I-NP O
. . O O
Started VBN B-VP O
on IN B-PP O
heparin NN B-NP O
gtt NN I-NP O
. . O O
Given VBN B-VP O
lopressor JJ B-NP O
25 CD I-NP O
mg NN I-NP O
po NN I-NP O
x1 NN I-NP O
, , O O
zantac NN B-NP O
150 CD I-NP O
mg NN I-NP O
po NN I-NP O
x1 NN I-NP O
, , O O
and CC O O
Maalox NNP B-NP O
. . O O
Did VBD B-VP O
not RB I-VP O
receive VB I-VP O
integrillin NN B-NP O
nor CC O O
a DT B-NP O
statin NN I-NP O
. . O O
No DT B-NP O
EKG NN I-NP O
changes NNS I-NP O
. . O O
Initial JJ B-NP O
CE NNP I-NP O
were VBD B-VP O
negative JJ B-ADJP O
. . O O
Started VBN B-VP O
on IN B-PP O
heparin NN B-NP O
given VBN I-NP O
clinical JJ I-NP O
story NN I-NP O
. . O O
2nd CD B-NP O
set NN I-NP O
of IN B-PP O
enzymes NNS B-NP O
notable JJ B-ADJP O
for IN B-PP O
CKMB NN B-NP O
of IN B-PP O
26 CD B-NP O
and CC I-NP O
troponin FW I-NP O
of IN B-PP O
0.4 CD B-NP O
. . O O
Cardiology NNP B-NP O
was VBD B-VP O
notified VBN I-VP O
. . O O
Hemodynamically '' O O
stable JJ B-ADJP O
throughout IN B-PP O
ED VBN B-NP O
stay NN I-NP O
; : O O
not RB B-NP O
given VBN I-NP O
any DT B-NP O
fluids NNS I-NP O
. . O O
ROS NNP B-NP O
: : O O
See VB B-VP O
HPI. NNP B-NP O
Denies NNP I-NP O
HA/LH. NNP I-NP O
No NNP I-NP O
F/C/NS. NNP I-NP O
No DT B-NP O
SOB/DOE NNP I-NP O
, , I-NP O
cough NN I-NP O
. . O O
No DT B-NP O
orthopnea/LE NN I-NP O
swelling VBG B-VP O
. . B-NP O
On IN B-PP O
CPAP NNP B-NP O
at IN B-PP O
night NN B-NP O
for IN B-PP O
OSA NNP B-NP O
( -LRB- I-NP O
does VBZ B-VP O
not RB I-VP O
know VB I-VP O
settings NNS B-NP O
) -RRB- B-VP O
. . B-NP O
Denies NNS I-NP O
N/V/D/C. . O O
Chronic NNP B-NP O
umbilical JJ I-NP O
hernia CC I-NP O
x15+ JJ I-NP O
years NNS I-NP O
; : O O
no DT B-NP O
issues NNS I-NP O
. . O O
Occasional NNP B-NP O
indigestion NN I-NP O
. . O O
Nocturia NNP B-NP O
x2 NNP I-NP O
. . O O
No DT B-NP O
dysuria/hematuria NN I-NP O
. . B-PP O
No DT B-NP O
neurological JJ I-NP O
deficits NNS I-NP O
. . O O
No DT B-NP O
hot/cold JJ I-NP O
intolerance NN I-NP O
. . O O
No DT B-NP O
recent JJ I-NP O
exposures NNS I-NP O
or CC I-NP O
travel NN I-NP O
. . O O
ROS NNS B-NP O
is VBZ B-VP O
otherwise RB B-ADJP O
unremarkable JJ I-ADJP O
. . O O
Past JJ B-NP O
medical JJ I-NP O
history NN I-NP O
: : O O
- : O O
OSA NNS B-NP O
; : O O
needs NNS B-NP O
CPAP NNP I-NP O
titration NN I-NP O
. . O O
- : O O
Restless JJ B-NP O
legs NNS I-NP O
syndrome NN I-NP O
. . O O
- : O O
BPH NNS B-NP O
; : O O
followed VBN B-VP O
by IN B-PP O
Dr. NNP B-NP O
Landers NNP I-NP B-DOCTOR
, , O O
On IN B-PP O
Proscar NNP B-NP O
and CC I-NP O
Uroxatral NNP I-NP O
- : O O
GERD NNP B-NP O
on IN B-PP O
PPI NNP B-NP O
- : O O
Umbilical JJ B-NP O
hernia NN I-NP O
; : O O
present JJ B-NP O
&gt NN I-NP O
; : O O
15 CD B-NP O
years NNS I-NP O
. . O O
- : O O
Hx NN B-NP O
of IN B-PP O
Basal NNP B-NP O
cell NN I-NP O
carcinoma NN I-NP O
; : O O
s/p JJ B-NP O
multiple JJ I-NP O
excisios NNS I-NP O
. . O O
- : O O
s/p NN B-NP O
burn VBP B-VP O
injury NN B-NP O
to TO B-PP O
L NNP B-NP O
foot NN I-NP O
. . O O
Allergies NNP B-NP O
: : O O
NKDA NNP O O
Medications NNS B-NP O
on IN B-PP O
Admission NNP B-NP O
: : O O
- : O O
Nexium NNP B-NP O
40 CD B-NP O
mg NN I-NP O
PO NN I-NP O
daily RB O O
- : O O
Uroxatral NNP B-NP O
1 CD B-NP O
mg NN I-NP O
PO NN I-NP O
daily RB O O
- : O O
Finasteride NNP B-NP O
5 CD B-NP O
mg NN I-NP O
PO NN I-NP O
daily RB O O
- : O O
Beconase JJ B-NP O
1-2 JJ I-NP O
sprays NNS I-NP O
PO . O O
daily NN O O
- : O O
Aspirin NN B-NP O
81 CD B-NP O
mg NN I-NP O
PO NN I-NP O
daily RB B-ADVP O
. . O O
Family NNP B-NP O
history NN I-NP O
: : O O
- : B-NP O
Brother NNP I-NP O
: : O O
MI NNP B-NP O
at IN B-PP O
68 CD B-NP B-AGE
yo NNP I-NP O
( -LRB- I-NP O
2 CD B-NP O
weeks NNS I-NP O
ago RB B-ADVP O
) -RRB- O O
- : B-NP O
Father NN I-NP O
: : O O
MI NNP B-NP O
in IN B-PP O
60s NNS B-NP B-AGE
, , O O
CABG NNP B-NP O
- : B-NP O
Mother NN I-NP O
: : O O
No DT B-NP O
CAD NN I-NP O
Social/substance NN B-NP O
history NN I-NP O
: : O O
- : O O
Single NNP B-NP O
, , O O
never RB B-VP O
married VBN I-VP O
, , O O
no DT B-NP O
children NNS I-NP O
. . O O
- : O O
Never RB B-VP O
smoked VBN I-VP O
and CC O O
he PRP B-NP O
drinks VBZ B-VP O
1-2 JJ B-NP O
drinks NNS I-NP O
a DT B-NP O
week NN I-NP O
. . O O
Denies NNS B-NP O
illicits NNS I-NP O
. . O O
- : B-NP O
Recruitment NNP I-NP B-PROFESSION
Officer NNP I-NP I-PROFESSION
Physical JJ B-NP O
examination NN I-NP O
: : O O
Vitals NNS B-NP O
: : O O
T NNP B-NP O
98 CD I-NP O
HR NNP I-NP O
75 CD I-NP O
BP NNP I-NP O
137/92 CD I-NP O
2L IN B-PP O
98 CD B-NP O
% NN I-NP O
. . O O
Gen NNP B-NP O
: : O O
NAD NN B-NP O
HEENT NNP B-NP O
: : O O
EOMI/PERRL. NNP B-NP O
Sclera NNP I-NP O
anicteric JJ I-NP O
. . O O
OP NNP O O
clear JJ B-ADJP O
. . O O
MMM. NNP B-NP O
Thyroid NNP I-NP O
normal JJ O O
Neck NNP B-NP O
: : O O
Carotids NNP B-NP O
2+ CD I-NP O
without IN B-PP O
bruits NNS B-NP O
. . O O
JVP NNP B-NP O
4 CD I-NP O
cm NN I-NP O
. . O O
Chest NNP B-NP O
: : O O
CTAB NN B-NP O
CV NNP B-NP O
: : O O
RRR NNP B-NP O
S1/S2 NNP I-NP O
. . I-NP O
Heart NNP I-NP O
sounds VBZ B-VP O
distant JJ B-ADJP O
. . O O
No DT B-NP O
M/G/R NNP I-NP O
appreciated VBD B-VP O
. . B-NP O
PMI NNP I-NP O
non-displaced JJ I-NP O
. . O O
Abd NNP B-NP O
: : O O
Soft NNP B-NP O
. . I-NP O
Normal NNP I-NP O
BS. NNP I-NP O
No DT B-NP O
HSM. NNP I-NP O
Reducible NNP I-NP O
ventral NN I-NP O
hernia NN I-NP O
. . O O
Ext NNP B-NP O
: : O O
No DT B-NP O
cyanosis NN I-NP O
, , O O
clubbing VBG B-VP O
. . B-NP O
Trace NNP I-NP O
pedal NN I-NP O
edema NN I-NP O
. . O O
2+ JJ B-NP O
DP NNP I-NP O
bilat NN I-NP O
. . O O
WWP. '' O O
Neuro NNP B-NP O
: : O O
A&amp;O NNP B-NP O
x3 CD I-NP O
. . O O
Non-focal JJ B-ADJP O
. . O O
Labs/Studies NNS B-NP O
Lytes/Renal/Glucose NN B-NP O
Sodium NNP B-NP O
137 CD I-NP O
135-145 CD I-NP O
mmol/L NN I-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
Potassium NNP B-NP O
3.8 CD I-NP O
3.4-4.8 CD I-NP O
mmol/L NN I-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
Chloride NNP B-NP O
102 CD I-NP O
100-108 CD I-NP O
mmol/L NN I-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
Carbon NN B-NP O
Dioxide NNP I-NP O
24.0 CD I-NP O
23.0-31.9 CD I-NP O
mmol/L NN I-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
BUN NNP B-NP O
15 CD I-NP O
8-25 CD I-NP O
mg/dl NN I-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
Creatinine NNP B-NP O
0.88 CD I-NP O
0.60-1.50 CD I-NP O
mg/dl NN I-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
GFR JJ B-NP O
(estimated JJ I-NP O
) -RRB- I-NP O
&gt NN I-NP O
;60 VBD B-VP O
mL/min/1.73m2 CD B-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
Glucose DT B-NP O
145H CD I-NP O
70-110 CD I-NP O
mg/dl NN I-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
Anion NNP B-NP O
Gap NNP I-NP O
11 CD I-NP O
3-15 CD I-NP O
mmol/L NN I-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
General NNP B-NP O
Chemistries NNPS I-NP O
Calcium NNP B-NP O
9.5 CD I-NP O
8.5-10.5 CD I-NP O
mg/dl VBD B-VP O
07/05/77 CD B-NP B-DATE
16 CD I-NP O
:07 . O O
Phosphorus NNP B-NP O
2.6 CD I-NP O
2.6-4.5 CD I-NP O
mg/dl NN I-NP O
07/05/77 CD I-NP B-DATE
16 CD I-NP O
:07 . O O
Magnesium NNP B-NP O
2.0 CD I-NP O
1.4-2.0 CD I-NP O
meq/L NNS I-NP O
07/05/77 VBD B-VP B-DATE
16 CD B-NP O
:07 CD I-NP O
Bilirubin NNP B-NP O
( -LRB- I-NP O
To... NNP I-NP O
0.9 CD I-NP O
0.0-1.0 CD I-NP O
mg/dl JJ I-NP O
09/04/75 CD I-NP B-DATE
17 CD I-NP O
:44 . O O
Total JJ B-NP O
Protein NNP I-NP O
7.1 CD I-NP O
6.0-8.3 CD I-NP O
g/dl NN I-NP O
09/04/75 CD B-NP B-DATE
17 CD I-NP O
:44 . O O
Albumin NNP B-NP O
4.4 CD I-NP O
3.3-5.0 CD I-NP O
g/dl JJ I-NP O
09/04/75 CD I-NP B-DATE
17 CD I-NP O
:44 . O O
Globulin NNP B-NP O
2.7 CD I-NP O
2.6-4.1 CD I-NP O
g/dl VBD B-VP O
09/04/75 CD B-NP B-DATE
17 CD I-NP O
:44 . O O
Cardiac NNP B-NP O
Tests NNS I-NP O
CK NNP B-NP O
300 CD I-NP O
60-400 CD I-NP O
U/L NNP I-NP O
07/05/77 CD I-NP B-DATE
22:16 CD O O
CK-MB NNP B-NP O
26.4H CD I-NP O
0.0-6.9 CD I-NP O
ng/ml JJ I-NP O
07/05/77 CD I-NP B-DATE
22:16 CD O O
CRP NNP B-NP O
, , O O
High NNP B-NP O
Sen... NNP I-NP O
1.1 CD I-NP O
mg/L NN I-NP O
10/24/74 CD B-NP B-DATE
09:56 CD I-NP O
LDH NNP B-NP O
226H CD I-NP O
110-210 CD I-NP O
U/L NNP I-NP O
06/10/65 CD I-NP B-DATE
14:31 CD O O
Troponin-I NNP B-NP O
NEGATIVE JJ I-NP O
NEG NN I-NP O
07/05/77 VBD B-VP B-DATE
16 CD B-NP O
:17 CD I-NP O
Troponin-T NNP B-NP O
0.42H CD I-NP O
0.00-0.09 CD I-NP O
ng/ml JJ I-NP O
07/05/77 CD I-NP B-DATE
22:16 CD O O
Lipid NNP B-NP O
Tests NNS I-NP O
Cholesterol NNP B-NP O
190 CD I-NP O
0-200 CD I-NP O
mg/dl NN I-NP O
01/28/77 CD I-NP B-DATE
16 CD I-NP O
:53 . O O
Triglycerides NNS B-NP O
127 CD B-NP O
40-160 CD I-NP O
mg/dl NN I-NP O
01/28/77 CD I-NP B-DATE
16 CD I-NP O
:53 . O O
HDL NNP B-NP O
Cholesterol NNP I-NP O
47 CD I-NP O
29-67 CD I-NP O
mg/dl NN I-NP O
01/28/77 CD I-NP B-DATE
16 CD I-NP O
:53 . O O
LDL NNP B-NP O
Cholesterol NNP I-NP O
118 CD I-NP O
0-130 CD I-NP O
mg/dl NN I-NP O
01/28/77 CD I-NP B-DATE
16 CD I-NP O
:53 . O O
Chol/HDL NNP B-NP O
Ratio NNP I-NP O
4.04 CD I-NP O
0-9.55 CD I-NP O
01/28/77 IN B-PP B-DATE
16 CD B-NP O
:53 CD I-NP O
Hematology NNP B-NP O
WBC NNP B-NP O
6.8 CD I-NP O
4.5-11.0 CD I-NP O
th/cmm NN I-NP O
07/05/77 CD I-NP B-DATE
15 CD I-NP O
:56 . O O
Hgb NNP B-NP O
17.6H CD I-NP O
13.5-17.5 CD I-NP O
gm/dl NN I-NP O
07/05/77 CD I-NP B-DATE
15 CD I-NP O
:56 . O O
HCT NNP B-NP O
50.1 CD I-NP O
41.0-53.0 CD I-NP O
% NN I-NP O
07/05/77 CD I-NP B-DATE
15 CD I-NP O
:56 . O O
PLT NNP B-NP O
205 CD I-NP O
150-400 CD I-NP O
th/cumm IN B-PP O
07/05/77 CD B-NP B-DATE
15 CD I-NP O
:56 . O O
Neutrophils NNS B-NP O
56 CD B-NP O
40-70 CD I-NP O
% NN I-NP O
07/05/77 CD I-NP B-DATE
15 CD I-NP O
:56 . O O
Lymphs NNS B-NP O
34 CD B-NP O
22-44 CD I-NP O
% NN I-NP O
07/05/77 CD I-NP B-DATE
15 CD I-NP O
:56 . O O
Monos NNP B-NP O
6 CD I-NP O
4-11 CD I-NP O
% NN I-NP O
07/05/77 CD I-NP B-DATE
15 CD I-NP O
:56 . O O
Eos NNS B-NP O
4 CD B-NP O
0-8 CD I-NP O
% NN I-NP O
07/05/77 CD I-NP B-DATE
15 CD I-NP O
:56 . O O
Basos NNS B-NP O
0 CD B-NP O
0-3 CD I-NP O
% NN I-NP O
07/05/77 CD I-NP B-DATE
15 CD I-NP O
:56 . O O
Routine NNP B-NP O
Coagulation NNP I-NP O
PT NNP B-NP O
12.9 CD I-NP O
10.3-13.2 CD I-NP O
sec NN I-NP O
07/05/77 CD I-NP B-DATE
22:19 CD O O
PT-INR JJ B-NP O
1.1 CD I-NP O
07/05/77 CD I-NP B-DATE
22:19 CD O O
PTT NNP B-NP O
58.7H CD I-NP O
22.1-34.0 CD I-NP O
sec NN I-NP O
07/05/77 CD I-NP B-DATE
22:19 CD O O
Urinalysis NN B-NP O
Color NNP B-NP O
- : O O
UA NN B-VP O
Yellow JJ B-NP O
YELLOW NNP I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
Appearance NNP B-NP O
- : O O
UA NNP B-NP O
Clear NNP I-NP O
CLEAR NN I-NP O
07/05/77 CD B-NP B-DATE
22:30 CD I-NP O
GLUC NNP B-NP O
- : O O
UA NN B-VP O
NEGATIVE JJ B-NP O
NEG NNP I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
Bilirubin NNP B-NP O
- : O O
UA NN B-VP O
NEGATIVE JJ B-NP O
NEG NNP I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
Ketones NNP B-NP O
- : O O
UA NN B-VP O
NEGATIVE JJ B-NP O
NEG NNP I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
Specific JJ B-NP O
Grav... NNP I-NP O
1.020 CD I-NP O
1.001-1.035 CD I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
Blood NN B-NP O
- : O O
UA NN B-VP O
NEGATIVE JJ B-NP O
NEG NNP I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
pH VB B-VP O
- : O O
UA NNP B-NP O
6.5 CD B-NP O
5.0-9.0 CD I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
Protein NNP B-NP O
- : O O
UA NN B-VP O
NEGATIVE JJ B-NP O
NEG NNP I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
Urobilinogen NN B-NP O
... : O O
Trace NNP B-NP O
NEG NNP I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
Nitrites NNPS O O
- : O O
UA NN B-VP O
NEGATIVE JJ B-NP O
NEG NNP I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
WBC NNP B-NP O
Screen NNP I-NP O
- : O O
UA NN B-VP O
NEGATIVE JJ B-NP O
NEG NNP I-NP O
07/05/77 CD I-NP B-DATE
22:30 CD O O
- : O O
ETT NNP B-NP O
1/77 CD B-NP B-DATE
: : O O
CONCLUSION NN B-NP O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
normal JJ B-NP O
exercise NN I-NP O
capacity NN I-NP O
( -LRB- I-NP O
7 CD I-NP O
METS NNS I-NP O
) -RRB- I-NP O
. . O O
The DT B-NP O
ECG NNP I-NP O
is VBZ B-VP O
negative JJ B-ADJP O
for IN B-PP O
ischemia NN B-NP O
. . O O
- : O O
EKG RB B-NP O
1/77 CD I-NP B-DATE
as IN B-PP O
per IN B-PP O
prior JJ B-NP O
note NN I-NP O
: : O O
Showed NNP B-NP O
probable JJ I-NP O
evidence NN I-NP O
of IN B-PP O
a DT B-NP O
past JJ I-NP O
inferior JJ I-NP O
MI NNP I-NP O
. . I-NP O
RBBB NNP I-NP O
, , O O
both DT B-NP O
new JJ I-NP O
from IN I-NP O
7 CD I-NP O
years NNS I-NP O
ago RB B-ADVP O
. . O O
- : O O
EKG NNP B-NP O
7/06/77 CD B-NP B-DATE
: : O O
NSR NNP B-NP O
at IN B-PP O
75 CD B-NP O
. . O O
Left VBD B-VP O
axis DT B-NP O
deviation NN I-NP O
. . B-NP O
RBBB NN I-NP O
. . O O
No DT B-NP O
Sgarbossa NNP I-NP O
criteria NNS I-NP O
. . O O
No DT B-NP O
changes NNS I-NP O
from IN B-PP O
prior RB B-NP O
. . O O
A/P NNP B-NP O
: : O O
63 CD B-NP B-AGE
yo NNP I-NP O
M NNP I-NP O
p/w VBD B-VP O
NSTEMI NNP B-NP O
. . I-NP O
Hemodynamically NNP I-NP O
stable NN I-NP O
. . O O
Currently RB B-ADVP O
CP CD B-NP O
free JJ I-NP O
without IN B-PP O
EKG JJ B-NP O
changes NNS I-NP O
. . O O
CAD/Ischemia NNP B-NP O
: : O O
Cont NNP B-NP O
. . I-NP O
Heparin NNP I-NP O
. . I-NP O
NPO NNP I-NP O
for IN B-PP O
cath NN B-NP O
in IN B-PP O
AM. NNP B-NP O
Cont NNP I-NP O
. . O O
to TO B-PP O
cycle NN B-NP O
enzymes NNS I-NP O
to TO B-VP O
peak VB I-VP O
. . O O
- : O O
cont NN B-NP O
BB/ASA NNP B-NP O
, , O O
start NN B-NP O
Statin NNP I-NP O
- : O O
Will MD B-VP O
need VB I-VP O
integrilin NN B-NP O
on IN B-PP O
call NN B-NP O
to TO B-PP O
PCI. NNP B-NP O
; : O O
NPO NNP B-NP O
for IN B-PP O
cath NN B-NP O
in IN B-PP O
AM NNP B-NP O
- : O O
TTE NN B-NP O
in IN B-PP O
AM NNP B-NP O
- : O O
Fasting NN B-NP O
lipids NNS I-NP O
, , O O
A1C NNP B-NP O
in IN B-LST O
AM VBP O O
CV NNP B-NP O
Pump NNP I-NP O
: : O O
Appears NNP B-NP O
euvolemic , O O
. . B-NP O
Cont NNP I-NP O
BB NNP I-NP O
. . O O
Start VB B-VP O
acei CC I-VP O
as IN B-PP O
tolerated VBN B-NP O
. . O O
CV NNP B-NP O
Rhythm NNP I-NP O
: : O O
Sinus NNP B-NP O
. . I-NP O
Tele NNP I-NP O
. . O O
OSA NNP B-NP O
: : O O
Cont NNP B-VP O
CPAP NNP B-NP O
at IN B-PP O
night NN B-NP O
. . O O
Gerd NNP B-NP O
: : O O
Cont NNP B-NP O
. . I-NP O
PPI. NNP I-NP O
PPx NNP B-NP O
: : O O
Heparin NNP B-NP O
, , O O
ASA NNP B-NP O
. . I-NP O
PPI. NNP I-NP O
FEN NNS B-NP O
: : O O
Cardiac. NNP B-NP O
Julian NNP B-NP B-DOCTOR
I. NNP I-NP I-DOCTOR
Judkins NNP I-NP I-DOCTOR
MD NNP I-NP O
, , O O
PhD NNP B-NP O
PGY-2 NNP B-NP O
, , O O
Internal NNP B-NP O
Medicine NNP I-NP O
Pager NNP B-NP O
# # I-NP O
46002 CD O B-PHONE
