Record NNP B-NP O
date NN I-NP O
: : O O
2089-06-17 CD O B-DATE
FORT JJ B-NP B-HOSPITAL
WASHINGTON NNP I-NP I-HOSPITAL
HOSPITAL NNP I-NP I-HOSPITAL
June NNP B-NP B-DATE
17 CD I-NP I-DATE
, , I-NP I-DATE
2089 CD O I-DATE
RE RB B-ADVP O
: : O O
Francis NNP B-NP I-PATIENT
, , O I-PATIENT
Lydia NNP B-NP I-PATIENT
PAH NNP B-NP B-HOSPITAL
# # I-NP O
: : O O
981-82-02 CD O B-MEDICALRECORD
SUBJECTIVE JJ B-NP O
: : O O
Lydia NNP B-NP B-PATIENT
has VBZ B-VP O
been VBN I-VP O
doing VBG I-VP O
well RB B-ADVP O
since IN B-PP O
her PRP$ B-NP O
right JJ I-NP O
total NN I-NP O
hip NN B-NP O
arthroplasty NN I-NP O
in IN B-PP O
January NNP B-NP B-DATE
of IN B-PP I-DATE
2089 CD B-NP I-DATE
. . O O
She PRP B-NP O
still RB B-ADVP O
has VBZ B-VP O
pain NN B-NP O
in IN B-PP O
the DT B-NP O
right JJ I-NP O
hip NN I-NP O
and CC O O
the DT B-NP O
left JJ I-NP O
hip NN I-NP O
, , O O
which WDT B-NP O
is VBZ B-VP O
likely JJ B-NP O
due JJ I-NP O
to TO B-LST O
osteoarthritis NN B-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
taking VBG I-VP O
Percocet NNP B-NP O
for IN B-PP O
pain NN B-NP O
control NN B-NP O
. . O O
Fortunately RB B-ADVP O
, , O O
she PRP B-NP O
is VBZ B-VP O
not RB I-VP O
having VBG I-VP O
problems NNS B-NP O
with IN B-PP O
constipation NN B-NP O
, , O O
as IN B-SBAR O
she PRP B-NP O
is VBZ B-VP O
taking VBG I-VP O
a DT B-NP O
stool NN I-NP O
softener NN I-NP O
. . O O
She PRP B-NP O
is VBZ B-LST O
taking VBG B-VP O
calcitonin NN B-NP O
and CC I-NP O
Evista NNP I-NP O
for IN B-PP O
her PRP$ B-NP O
osteoporosis NN I-NP O
. . O O
In IN O O
addition NN B-NP O
, , O O
she PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
right JJ B-NP O
tibial NN I-NP O
osteomyelitis NN B-NP O
and CC O O
is VBZ B-VP O
taking VBG I-VP O
prophylactic JJ B-NP O
Levaquin NNP I-NP O
, , O O
without IN B-PP O
evidence NN B-NP O
of IN B-PP O
GI NNP B-NP O
upset JJ I-NP O
or CC I-NP O
antibiotic-associated JJ I-NP O
diarrhea NN I-NP O
. . O O
She PRP O O
is VBZ B-VP O
taking VBG I-VP O
Cozaar NNP B-NP O
for IN B-PP O
her PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
control NN I-NP O
, , O O
and CC O O
is VBZ B-VP O
also RB I-VP O
taking VBG B-VP O
Neurontin NNP B-NP O
for IN B-PP O
pain NN B-NP O
control NN I-NP O
. . O O
At IN B-PP O
home NN B-NP O
, , O O
she PRP B-NP O
is VBZ B-VP O
wearing VBG I-VP O
a DT B-NP O
firm NN I-NP O
brace NN I-NP O
that IN B-PP O
Dr. NNP B-NP O
Younce NNP I-NP B-DOCTOR
has VBZ B-VP O
prescribed VBN I-VP O
. . O O
In IN B-PP O
addition NN B-NP O
, , O O
she PRP B-NP O
is VBZ B-VP O
using VBG I-VP O
a DT B-NP O
walker NN I-NP O
for IN B-PP O
ambulation NN B-NP O
when WRB B-ADVP O
outside IN B-PP O
the DT B-NP O
house NN I-NP O
and CC O O
a DT B-NP O
cane NN I-NP O
when WRB B-ADVP O
inside RB B-NP O
the DT I-NP O
house NN I-NP O
. . O O
She PRP B-NP O
comes VBZ B-VP O
today NN B-NP O
for IN B-PP O
her PRP$ B-NP O
appointment NN B-NP O
with IN B-PP O
her PRP$ B-NP O
son NN I-NP O
. . O O
She PRP B-NP O
arrived VBD B-VP O
in IN B-PP O
a DT B-NP O
wheelchair NN I-NP O
. . O O
On IN B-PP O
examination NN B-NP O
, , O O
her PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
today NN I-NP O
is VBZ B-VP O
138/8 CD B-NP O
0 CD I-NP O
with IN B-PP O
a DT O O
pulse NN B-NP O
of IN B-PP O
80 CD B-NP O
and CC O O
a DT B-NP O
respiratory JJ I-NP O
rate NN I-NP O
of IN B-PP O
16 CD B-NP O
. . O O
She PRP B-NP O
is VBZ B-VP O
afebrile JJ B-ADJP O
. . O O
Cardiac NNP B-NP O
exam NN I-NP O
is VBZ B-VP O
a DT B-NP O
regular JJ I-NP O
rate NN I-NP O
and CC I-NP O
rhythm NN I-NP O
, , O O
S1 NNP B-NP O
, , O O
S2 NNP B-NP O
, , O O
without IN B-PP O
murmurs NNS B-NP O
. . B-VP O
Her PRP$ B-NP O
neck NN I-NP O
is VBZ B-VP O
supple NN B-NP O
, , O O
although IN B-SBAR O
she PRP B-NP O
does VBZ B-VP O
have VB I-VP O
paracervical JJ B-NP O
pain NN I-NP O
to TO B-PP O
palpation NN B-NP O
. . O O
Her PRP$ B-NP O
lungs NNS I-NP O
are VBP B-VP O
clear JJ B-ADJP O
to TO O O
auscultation NN B-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
pain NN B-NP O
throughout IN B-PP O
the DT B-NP O
paraspinal NN I-NP O
muscles NNS B-NP O
in IN B-PP O
the DT B-NP O
thoracic JJ I-NP O
and CC I-NP O
lumbosacral JJ I-NP O
area NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
some DT O O
pain NN B-NP O
with IN B-PP O
flexion NN B-NP O
at IN B-PP O
the DT B-NP O
hip NN I-NP O
, , O O
with IN B-PP O
limited JJ B-NP O
motion NN I-NP O
at IN B-PP O
both DT O O
hips NNS B-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
lower JJR B-NP O
extremity NN I-NP O
erythema NN I-NP O
or CC O O
edema NN B-NP O
. . B-VP O
Her PRP$ B-NP O
peripheral JJ I-NP O
pulses NNS I-NP O
are VBP B-VP O
intact JJ B-ADJP O
. . O O
Her PRP B-NP O
patellar NN B-NP O
reflexes NNS B-NP O
are VBP B-VP O
absent JJ B-ADJP O
. . O O
She PRP B-NP O
has VBZ B-VP O
good JJ B-NP O
pedal NN I-NP O
pulses NNS I-NP O
. . O O
She PRP B-NP O
denies VBZ B-LST O
depression NN B-NP O
and CC I-NP O
overall JJ I-NP O
is VBZ B-VP O
encouraged VBN I-VP O
. . O O
She PRP B-NP O
plans VBZ B-VP O
a DT B-NP O
trip NN I-NP O
to TO O O
Peru NNP B-NP B-COUNTRY
soon RB B-ADVP O
. . O O
Medications NNS B-NP O
are VBP B-VP O
updated VBN I-VP O
in IN B-PP O
LMR. NNP B-NP O
DISPOSITION NN B-NP O
: : O O
She PRP B-NP O
will MD B-VP O
follow VB I-VP O
up RP B-PRT O
with IN B-PP O
me PRP B-NP O
for IN B-PP O
a DT B-NP O
complete JJ I-NP O
physical JJ B-NP O
examination NN I-NP O
in IN B-PP O
November NNP B-NP B-DATE
of IN B-PP O
this DT B-NP O
year NN I-NP O
, , O O
and CC O O
she PRP B-NP O
will MD O O
be VB B-VP O
fasting VBG I-VP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
. . O O
Yonathan NNP B-NP B-DOCTOR
Turk NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Fort NNP B-NP B-HOSPITAL
Washington NNP I-NP I-HOSPITAL
Hospital NN I-NP I-HOSPITAL
KV:MD:9637 DT B-NP B-IDNUM
/ JJ I-NP O
DD NNP I-NP O
: : O O
6-17-89 CD B-NP B-DATE
/ NN I-NP O
DT NNP I-NP O
: : O O
6-23-89 CD O B-DATE
