Record NNP B-NP O
date NN I-NP O
: : O O
2070-03-16 CD O B-DATE
NAME NNP B-NP O
: : O O
Vines NNP B-NP I-PATIENT
, , O I-PATIENT
Stephen NNP B-NP I-PATIENT
MRN NNP B-NP O
: : O O
1672569 CD O B-MEDICALRECORD
Stephen NNP B-NP B-PATIENT
comes VBZ B-VP O
in IN B-PP O
today NN B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
feeling VBG I-VP O
pretty RB B-ADVP O
well RB I-ADVP O
. . O O
Really RB B-ADVP O
has VBZ B-VP O
no DT B-NP O
new JJ I-NP O
complaints NNS B-NP O
. . O O
He PRP B-NP O
still RB B-ADVP O
has VBZ B-VP O
5 CD B-NP O
block NN I-NP O
claudication NN I-NP O
in IN B-PP O
his PRP$ B-NP O
calves NNS I-NP O
and CC O O
he PRP B-NP O
continues VBZ B-VP O
to TO I-VP O
smoke VB I-VP O
a DT B-NP O
half NN I-NP O
pack NN I-NP O
per IN B-PP O
day NN B-NP O
. . O O
His PRP$ B-NP O
neuropathy NN I-NP O
is VBZ B-VP O
stabilized VBN I-VP O
and CC O O
his PRP$ B-NP O
sugars NNS I-NP O
have VBP B-VP O
been VBN I-VP O
good JJ B-ADJP O
for IN B-PP O
the DT B-NP O
most JJS I-NP O
part NN I-NP O
in IN B-PP O
the DT B-NP O
140-150 CD I-NP O
range NN I-NP O
on IN B-PP O
insulin NN B-NP O
. . O O
His PRP$ B-NP O
weight NN I-NP O
has VBZ B-VP O
been VBN I-VP O
stable JJ B-ADJP O
. . O O
He PRP B-ADJP O
has VBZ O O
had VBD B-VP O
no DT B-NP O
shortness NN I-NP O
of IN B-PP O
breath NN B-NP O
or CC I-NP O
chest NN I-NP O
pain NN I-NP O
and CC O O
his PRP$ B-NP O
review NN I-NP O
of IN B-PP O
systems NNS B-NP O
is VBZ B-VP O
otherwise RB O O
negative JJ B-ADJP O
. . O O
HABITS NNS B-NP O
: : O O
Smokes NNS B-NP O
about IN B-PP O
a DT B-NP O
half NN I-NP O
pack NN I-NP O
per IN B-PP O
day NN B-NP O
. . O O
Does VBZ B-VP O
not RB I-VP O
drink VB I-VP O
, , O O
not RB O O
really RB B-VP O
getting VBG I-VP O
much RB B-PRT O
exercise NN B-NP O
. . O O
His PRP$ B-NP O
legs NNS I-NP O
hurt VBP B-VP O
only RB B-NP O
when WRB B-ADVP O
he PRP B-NP O
walks VBZ B-VP O
over IN B-NP O
5 CD I-NP O
blocks NNS I-NP O
. . O O
It PRP B-NP O
does VBZ B-VP O
n't RB I-VP O
hurt VB I-VP O
when WRB B-ADVP O
he PRP B-NP O
is VBZ B-VP O
working VBG B-VP O
in IN B-PP O
the DT B-NP O
McCormick NNP I-NP B-ORGANIZATION
Company NNP I-NP I-ORGANIZATION
. . O O
PHYSICAL NNP B-NP O
EXAM NNPS I-NP O
: : O O
He PRP B-NP O
looks VBZ B-VP O
well RB B-PP O
. . O O
His PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
is VBZ B-VP O
142/80 CD B-NP O
. . O O
His PRP$ B-NP O
pulse NN I-NP O
is VBZ B-VP O
74 CD I-VP O
and CC O O
regular JJ B-NP O
. . O O
Respirations NNS B-NP O
are VBP B-VP O
16 CD B-NP O
. . I-NP O
Lungs NNP I-NP O
are VBP B-VP O
clear JJ B-ADJP O
. . O O
No DT B-NP O
worrisome JJ I-NP O
skin NN I-NP O
lesions NNS I-NP O
. . O O
No NN O O
bruits NNS B-NP O
. . B-VP O
1+ CD B-NP O
carotids NNS I-NP O
. . O O
Abdomen NNP B-NP O
is VBZ B-VP O
soft JJ B-ADJP O
and CC O O
nontender NN B-NP O
, , O O
no DT B-NP O
hepatosplenomegaly NN I-NP O
, , O O
no UH O O
pulsatile NN B-NP O
masses NNS I-NP O
, , O O
no DT B-NP O
bruits NNS I-NP O
. . O O
Decreased DT B-NP O
pulses NNS I-NP O
in IN B-PP O
the DT B-NP O
feet NNS I-NP O
and CC O O
decreased VBD B-VP O
capillary NN B-NP O
refill NN I-NP O
and CC O O
decreased VBD B-NP O
sensation NN I-NP O
of IN B-PP O
vibration NN B-NP O
and CC O O
fine JJ B-NP O
touch NN I-NP O
. . O O
ASSESSMENT NNP B-NP O
AND CC I-NP O
PLAN NNP I-NP O
: : O O
( -LRB- B-NP O
1 CD I-NP O
) -RRB- I-NP O
Diabetes NNP I-NP O
. . I-NP O
Will NNP I-NP O
check VB B-VP O
his PRP$ B-NP O
hemoglobin NN I-NP O
A1c . O O
to TO B-VP O
see VB I-VP O
where WRB B-ADVP O
we PRP B-NP O
stand VBP B-VP O
. . O O
Continue NNP O O
on IN B-PP O
his PRP$ B-NP O
current JJ I-NP O
regimen NNS I-NP O
. . O O
Encouraged VBN B-VP O
him PRP B-NP O
to TO B-VP O
increase VB I-VP O
his PRP$ B-NP O
exercise NN I-NP O
and CC O O
watch VB B-VP O
his PRP$ B-NP O
diet NN B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
an DT B-NP O
eye NN I-NP O
exam NN I-NP O
scheduled VBN B-VP O
. . O O
His PRP$ B-NP O
feet NNS I-NP O
look VBP B-VP O
okay UH B-ADJP O
, , O O
though IN B-SBAR O
we PRP B-NP O
will MD B-VP O
have VB I-VP O
to TO B-VP O
be VB I-VP O
careful JJ B-NP O
given VBN B-VP O
his PRP$ B-NP O
neuropathy NN I-NP O
and CC I-NP O
peripheral JJ I-NP O
vascular JJ I-NP O
disease NN I-NP O
. . O O
( -LRB- B-NP O
2 CD I-NP O
) -RRB- I-NP O
Claudication NN I-NP O
. . O O
Once RB O O
again RB B-ADVP O
, , O O
talked VBD B-VP O
to TO B-PP O
Mr. NNP B-NP O
Vines NNP I-NP B-PATIENT
about IN B-PP O
the DT B-NP O
absolute JJ I-NP O
importance NN B-NP O
of IN B-PP O
quitting VBG B-NP O
smoking NN I-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
going VBG I-VP O
to TO I-VP O
try VB I-VP O
using VBG I-VP O
the DT B-NP O
Wellbutrin NNP I-NP O
. . O O
Gave '' O O
him PRP B-NP O
a DT B-NP O
prescription NN I-NP O
for IN B-PP O
#60 DT B-NP O
. . O O
He PRP B-NP O
will MD B-VP O
take VB I-VP O
one CD B-NP O
a DT B-NP O
day NN I-NP O
for IN B-PP O
3-4 CD B-NP O
days NNS I-NP O
and CC O O
then RB B-VP O
go VB I-VP O
up IN B-NP O
to TO I-NP O
1 CD I-NP O
p.o NN I-NP O
. . O O
b.i.d '' O O
. . O O
He PRP B-NP O
has VBZ B-VP O
no DT B-NP O
contraindications NNS I-NP O
. . O O
I PRP B-NP O
also RB B-ADVP O
encouraged VBD B-VP O
him PRP B-NP O
to TO B-VP O
use VB I-VP O
the DT B-NP O
patch NN I-NP O
. . O O
Hopefully RB B-ADVP O
, , O O
we PRP B-NP O
will MD B-VP O
be VB I-VP O
able JJ B-ADJP O
to TO B-VP O
get VB I-VP O
him PRP B-NP O
off IN B-PP O
the DT B-NP O
cigarettes NNS I-NP O
. . O O
I PRP B-NP O
also RB B-LST O
encouraged VBD B-VP O
him PRP B-NP O
to TO B-VP O
walk VB I-VP O
until IN B-SBAR O
it PRP B-NP O
hurts VBZ B-VP O
at IN B-NP O
least JJS I-NP O
3-4 CD I-NP O
x NN I-NP O
a DT B-NP O
day NN I-NP O
to TO B-VP O
try VB I-VP O
and CC I-VP O
train VB I-VP O
his PRP$ O O
legs NNS B-NP O
. . O O
( -LRB- B-NP O
3 CD I-NP O
) -RRB- I-NP O
Hypertension NN I-NP O
. . O O
Our PRP$ B-NP O
goal NN I-NP O
is VBZ B-VP O
to TO B-VP O
get VB I-VP O
his PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
down IN B-PP O
about IN B-NP O
130 CD I-NP O
. . O O
Will MD O O
increase VB B-VP O
the DT B-NP O
Mavik NNP I-NP O
to TO B-VP O
twice RB B-NP O
a DT I-NP O
day NN I-NP O
. . O O
( -LRB- B-NP O
4 CD I-NP O
) -RRB- I-NP O
Hyperlipidemia NNP I-NP O
. . B-VP O
Well RB I-VP O
controlled VBN I-VP O
on IN B-PP O
Lipitor NNP B-NP O
. . O O
Recheck VB B-VP O
his PRP$ B-NP O
lipids NNS I-NP O
. . O O
( -LRB- B-NP O
5 CD I-NP O
) -RRB- I-NP O
Neuropathy RB I-NP O
. . O O
Stable JJ B-ADJP O
. . O O
He PRP B-NP O
does VBZ B-VP O
n't RB I-VP O
feel VB I-VP O
the DT B-NP O
need NN I-NP O
for IN B-PP O
any DT B-NP O
medication NN I-NP O
for IN B-PP O
it PRP B-NP O
. . O O
( -LRB- B-NP O
6 CD I-NP O
) -RRB- I-NP O
HPDP. NNP I-NP O
Will MD B-VP O
check VB I-VP O
his PRP$ B-NP O
guaiac JJ I-NP O
cards NNS I-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
not RB I-VP O
interested VBN I-VP O
in IN B-PP O
a DT B-NP O
sigmoidoscopy NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
a DT B-NP O
Pneumovax NNP I-NP O
. . I-NP O
Patient NNP I-NP O
will MD B-VP O
follow VB I-VP O
up RP B-PRT O
with IN B-PP O
me PRP B-NP O
in IN B-PP O
3 CD B-NP O
months NNS I-NP O
. . O O
Scott NNP B-NP B-DOCTOR
Phipps NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
SP NNP B-NP B-DOCTOR
/ NN I-NP O
irons NNS I-NP B-DOCTOR
/ . O O
quang NN O B-DOCTOR
