Record NNP B-NP O
date NN I-NP O
: : O O
2077-03-12 CD O B-DATE
March NNP B-NP B-DATE
12 CD I-NP I-DATE
, , I-NP I-DATE
2077 CD O I-DATE
Urijah NNP B-NP B-DOCTOR
Whaley NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
266 CD B-NP B-STREET
Bungalow NNP I-NP I-STREET
Ave NNP I-NP I-STREET
Crystal NNP B-NP B-CITY
Springs NNP I-NP I-CITY
, , O O
MO VBZ B-VP B-STATE
37319 CD I-VP B-ZIP
RE RB B-ADVP O
: : O O
Otis NNP B-NP B-PATIENT
Narvaez NNP I-NP I-PATIENT
MR NNP B-NP O
# # I-NP O
045-61-32-6 CD O B-MEDICALRECORD
Dear NNP B-NP O
Uddin NNP I-NP B-DOCTOR
: : O O
Otis NNP B-NP B-PATIENT
Narvaez NNP I-NP I-PATIENT
is VBZ B-VP O
a DT B-NP O
67 CD I-NP B-AGE
year NN I-NP O
old JJ I-NP O
man NN I-NP O
who WP B-NP O
returned VBD B-VP O
to TO B-PP O
the DT B-NP O
office NN I-NP O
today NN I-NP O
for IN B-PP O
follow-up NN B-NP O
after IN B-PP O
having VBG B-NP O
undergone IN B-PP O
an DT B-NP O
Adenosine NNP I-NP O
PET NNP I-NP O
scan NN I-NP O
on IN B-PP O
March NNP B-NP B-DATE
04 CD I-NP I-DATE
, , I-NP I-DATE
2077 CD I-NP I-DATE
. . B-PP O
His PRP$ B-NP O
previous JJ I-NP O
visit NN I-NP O
with IN B-PP O
me PRP B-NP O
occurred VBD B-VP O
on IN B-PP O
February NNP B-NP B-DATE
19 CD I-NP I-DATE
, , I-NP I-DATE
2077 CD I-NP I-DATE
, , O O
where WRB B-ADVP O
his PRP$ B-NP O
acute JJ I-NP O
complaint NN I-NP O
was VBD B-VP O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
with IN B-PP O
any DT B-NP O
activity NN I-NP O
. . O O
He PRP O O
denied VBD O O
chest NN B-NP O
pain NN I-NP O
, , O O
but CC O O
did VBD B-VP O
admit VB I-VP O
to TO B-PP O
a DT B-NP O
"tight JJ I-NP O
" `` I-NP O
feeling VBG B-VP O
down IN B-PP O
his PRP$ B-NP O
left JJ I-NP O
arm NN I-NP O
on IN B-PP O
occasion NN B-NP O
. . O O
This DT O O
was VBD B-VP O
not RB O O
associated VBN B-VP O
with IN B-PP O
activity NN B-NP O
. . O O
He PRP B-NP O
admits VBZ B-VP O
to TO B-PP O
being VBG B-VP O
a DT B-NP O
very RB I-NP O
sedentary JJ I-NP O
person NN I-NP O
. . O O
The DT B-NP O
results NNS I-NP O
of IN B-PP O
his PRP$ B-NP O
Adenosine NNP I-NP O
MIBI NNP I-NP O
were VBD B-VP O
abnormal JJ B-ADJP O
, , O O
with IN B-PP O
abnormal JJ B-NP O
myocardial JJ I-NP O
perfusion NN I-NP O
, , O O
global JJ O O
LV NNP B-NP O
function NN I-NP O
, , O O
and CC O O
CT NNP B-NP O
coronary JJ I-NP O
angiography NN I-NP O
. . O O
There EX B-NP O
were VBD B-VP O
no DT B-NP O
significant JJ I-NP O
findings NNS I-NP O
on IN B-PP O
the DT B-NP O
clinical JJ I-NP O
evaluation NN B-NP O
. . O O
The DT B-NP O
response NN I-NP O
was VBD B-VP O
non-ischemic JJ B-ADJP O
, , O O
and CC O O
there EX B-NP O
were VBD B-VP O
no DT B-NP O
EKG JJ I-NP O
changes NNS I-NP O
during IN B-PP O
infusion NN B-NP O
. . O O
The DT B-NP O
results NNS I-NP O
revealed VBD B-VP O
a DT B-NP O
small JJ I-NP O
calcified JJ I-NP O
plaque NN I-NP O
in IN B-PP O
the DT B-NP O
proximal JJ I-NP O
LAD NN I-NP O
coronary JJ I-NP O
artery NN I-NP O
without IN B-PP O
flow NN B-NP O
- : O O
limiting VBG B-VP O
stenosis NN B-NP O
. . O O
There EX B-NP O
was VBD B-VP O
a DT B-NP O
more RBR I-NP O
heavily RB I-NP O
calcified VBN I-NP O
plaque NN I-NP O
visualized VBN B-VP O
in IN B-PP O
the DT B-NP O
distal JJ I-NP O
RCA NN I-NP O
which WDT O O
was VBD B-VP O
flow-limiting JJ B-ADJP O
, , O O
and CC O O
there EX B-NP O
was VBD B-VP O
a DT B-NP O
moderate JJ I-NP O
amount NN I-NP O
of IN B-PP O
stress-induced JJ B-NP O
ischemia NN I-NP O
on IN B-PP O
imaging NN B-NP O
. . O O
There EX B-NP O
was VBD B-VP O
severe JJ B-NP O
left JJ I-NP O
ventricular JJ I-NP O
systolic JJ I-NP O
dysfunction NN I-NP O
with IN B-PP O
an DT B-NP O
ejection NN I-NP O
fraction NN I-NP O
of IN B-PP O
32 CD B-NP O
% NN I-NP O
. . O O
The DT O O
narrowing VBG B-VP O
in IN B-PP O
the DT B-NP O
distal JJ I-NP O
segment NN I-NP O
of IN B-PP O
the DT B-NP O
RCA NNP I-NP O
was VBD B-VP O
greater JJR B-NP O
than IN I-NP O
70 CD I-NP O
% NN I-NP O
. . O O
A DT B-NP O
lipid JJ I-NP O
profile NN I-NP O
performed VBN B-VP O
following VBG I-VP O
his PRP$ B-NP O
office NN I-NP O
visit NN I-NP O
on IN B-PP O
February NNP B-NP B-DATE
19 CD I-NP I-DATE
, , I-NP I-DATE
2077 CD I-NP I-DATE
revealed VBD B-VP O
a DT B-NP O
total NN I-NP O
cholesterol NN B-NP O
of IN B-PP O
182 CD B-NP O
mg/dl NN I-NP O
, , O O
an DT B-NP O
HDL NNP I-NP O
of IN B-PP O
43 CD B-NP O
mg/dl NN I-NP O
, , O O
an DT B-NP O
LDL NNP I-NP O
of IN B-PP O
71 CD B-NP O
mg/dl NN I-NP O
, , O O
and CC O O
a DT B-NP O
triglyceride NN I-NP O
level NN I-NP O
of IN B-PP O
342 CD B-NP O
mg/dl NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
not RB I-VP O
been VBN I-VP O
on IN B-PP O
any DT B-NP O
cholesterol-lowering NN I-NP O
medications NNS I-NP O
. . O O
He PRP B-NP O
had VBD B-VP O
undergone VBN I-VP O
previous JJ B-NP O
cardiac NN I-NP O
catheterization NN I-NP O
in IN B-PP O
November NNP B-NP B-DATE
2072 CD I-NP I-DATE
, , O O
which WDT B-NP O
demonstrated VBD B-LST O
insignificant JJ B-NP O
coronary JJ I-NP O
artery NN I-NP O
disease NN I-NP O
, , O O
with IN B-PP O
an DT B-NP O
ejection NN I-NP O
fraction NN I-NP O
of IN B-PP O
63 CD B-NP O
% NN I-NP O
. . O O
Since IN B-PP O
his PRP$ B-NP O
last JJ I-NP O
office NN I-NP O
visit NN I-NP O
, , O O
he PRP B-NP O
continues VBZ B-VP O
to TO I-VP O
be VB I-VP O
significantly RB B-ADJP O
short JJ I-ADJP O
of IN B-PP O
breath NN B-NP O
with IN B-PP O
any DT B-NP O
activity NN I-NP O
. . O O
He PRP O O
denies VBZ O O
any DT B-NP O
chest NN I-NP O
pain NN I-NP O
or CC O O
left JJ B-NP O
arm NN I-NP O
discomfort NN I-NP O
. . O O
His PRP$ B-NP O
current JJ I-NP O
medications NNS I-NP O
include VBP B-VP O
Ritalin NNP B-NP O
20 CD I-NP O
mg NN I-NP O
five CD B-NP O
times NNS I-NP O
daily RB B-ADVP O
, , O O
Ambien NNP B-NP O
10 CD I-NP O
mg NN I-NP O
at IN B-PP O
hour NN B-NP O
of IN B-PP O
sleep NN B-NP O
, , O O
Neurontin NNP B-NP O
900 CD I-NP O
mg NN I-NP O
three CD B-NP O
times NNS I-NP O
daily RB B-ADVP O
, , O O
Lasix NNP B-NP O
20 CD I-NP O
mg NN I-NP O
every DT B-NP O
other JJ I-NP O
day NN I-NP O
, , O O
Lisinopril NNP B-NP O
60 CD I-NP O
mg NN I-NP O
once RB B-ADVP O
daily RB I-ADVP O
, , O O
Otis NNP B-NP B-PATIENT
Narvaez NNP I-NP I-PATIENT
MR NNP B-NP O
# # I-NP O
045-61-32-6 CD O B-MEDICALRECORD
Page NNP B-NP O
2 CD I-NP O
March NNP B-NP B-DATE
12 CD I-NP I-DATE
, , I-NP I-DATE
2077 CD O I-DATE
aspirin NN B-NP O
325 CD I-NP O
mg NN I-NP O
with IN B-PP O
Oxycodone NNP B-NP O
as IN B-PP O
needed VBN B-NP O
. . O O
He PRP B-NP O
usually RB B-ADVP O
takes VBZ B-VP O
these DT B-NP O
once RB I-NP O
every DT I-NP O
other JJ I-NP O
day NN I-NP O
. . O O
He PRP B-NP O
is VBZ B-LST O
now RB B-ADVP O
on IN B-PP O
20 CD B-NP O
units NNS I-NP O
of IN B-PP O
an DT B-NP O
insulin NN I-NP O
preparation NN I-NP O
that IN B-SBAR O
he PRP B-NP O
cannot MD B-VP O
identify VB I-VP O
. . O O
He PRP B-NP O
takes VBZ B-VP O
this DT B-NP O
at IN B-PP O
bedtime NN B-NP O
. . O O
Review NNP B-NP O
of IN B-PP O
systems NNS B-NP O
reveals VBZ B-VP O
that IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
chronic JJ B-NP O
peripheral JJ I-NP O
neuropathy NN I-NP O
in IN B-PP O
his PRP$ B-NP O
feet NNS I-NP O
. . O O
This DT B-NP O
causes VBZ B-VP O
him PRP I-VP O
to TO B-VP O
feel VB I-VP O
imbalanced VBN I-VP O
, , O O
and CC O O
it PRP B-NP O
is VBZ B-VP O
necessary JJ B-ADJP O
for IN B-SBAR O
him PRP B-NP O
to TO B-VP O
walk VB I-VP O
with IN B-PP O
a DT B-NP O
cane NN I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
diagnosed VBN I-VP O
with IN B-PP O
diabetes NNS B-NP O
in IN B-PP O
2068 CD B-NP B-DATE
and CC O O
hypertension NN B-NP O
in IN B-PP O
2067 CD B-NP B-DATE
. . O O
He PRP B-NP O
also RB B-ADVP O
has VBZ B-VP O
chronic NN B-NP O
low JJ I-NP O
back RB B-ADVP O
pain NN B-NP O
due JJ B-ADJP O
to TO B-VP O
degenerative VB I-VP O
joint JJ B-NP O
disease NN I-NP O
, , O O
as RB B-CONJP O
well RB I-CONJP O
as IN I-CONJP O
lumbar NN B-NP O
disc NN I-NP O
disease NN I-NP O
. . O O
He PRP B-NP O
also RB B-ADVP O
has VBZ B-LST O
degenerative JJ B-NP O
joint JJ I-NP O
disease NN I-NP O
in IN B-PP O
his PRP$ B-NP O
knees NNS I-NP O
. . O O
He PRP B-NP O
receives VBZ B-VP O
psychiatric JJ B-NP O
follow-up NN I-NP O
for IN B-PP O
his PRP$ B-NP O
diagnosis NN I-NP O
of IN B-PP O
depression NN B-NP O
. . O O
He PRP B-NP O
underwent VBD B-VP O
a DT B-NP O
gastric JJ I-NP O
bypass NN I-NP O
procedure NN I-NP O
at IN B-PP O
Harmon NNP B-NP B-HOSPITAL
Medical NNP I-NP I-HOSPITAL
Rehabilitation NNP I-NP I-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
in IN B-PP O
2068 CD B-NP B-DATE
. . O O
On IN B-PP O
January NNP B-NP B-DATE
20 CD I-NP I-DATE
, , I-NP I-DATE
2073 CD I-NP I-DATE
, , O O
he PRP B-NP O
underwent VBD B-VP O
a DT B-NP O
left JJ I-NP O
lingular-sparing NN I-NP O
upper JJ I-NP O
lobectomy NN I-NP O
for IN B-PP O
a DT B-NP O
T1 NNP I-NP O
squamous . O O
cell NN B-NP O
carcinoma NN I-NP O
. . O O
On IN B-PP O
physical JJ B-NP O
examination NN I-NP O
, , O O
he PRP B-NP O
appears VBZ B-VP O
healthy JJ B-ADJP O
, , O O
albeit IN B-PP O
overweight NN B-NP O
, , O O
with IN B-PP O
a DT B-NP O
normal JJ I-NP O
affect VBP I-NP O
. . O O
His PRP$ O O
weight NN B-NP O
is VBZ B-VP O
208 CD B-NP O
lbs NNS I-NP O
, , O O
the DT B-NP O
heart NN I-NP O
rate NN I-NP O
is VBZ B-VP O
84 CD B-NP O
beats NNS I-NP O
per IN B-PP O
minute NN B-NP O
, , O O
the DT B-NP O
respiratory NN I-NP O
rate NN I-NP O
is VBZ B-VP O
16 CD B-NP O
per IN B-PP O
minute NN B-NP O
, , O O
and CC O O
the DT B-NP O
blood NN I-NP O
pressure NN I-NP O
is VBZ B-VP O
140/62 CD B-NP O
mm/Hg NN I-NP O
. . O O
Examination NN B-NP O
of IN B-PP O
the DT B-NP O
head NN I-NP O
, , O O
eyes NNS B-NP O
, , O O
ears NNS B-NP O
, , O O
nose NN B-NP O
, , O O
and CC O O
throat NN B-NP O
reveals VBZ O O
upper JJ B-NP O
dentures NNS I-NP O
in IN B-PP O
place NN B-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
jugular JJ I-NP O
vein NN I-NP O
distention NN I-NP O
, , O O
and CC O O
the DT B-NP O
lungs NNS I-NP O
are VBP B-VP O
clear JJ B-ADJP O
. . O O
There EX B-NP O
is VBZ B-VP O
increased VBN I-VP O
AP NNP B-NP O
diameter NN I-NP O
with IN B-PP O
bilateral JJ B-NP O
gynecomastia NN I-NP O
. . O O
On IN B-PP O
cardiac JJ B-NP O
examination NN I-NP O
, , O O
the DT B-NP O
heart NN I-NP O
sounds NNS B-NP O
are VBP B-VP O
distant JJ B-ADJP O
, , O O
and CC O O
there EX B-NP O
is VBZ B-VP O
a DT B-NP O
regular JJ I-NP O
rhythm NN I-NP O
, , O O
a DT B-NP O
normal JJ I-NP O
S1 NN I-NP O
, , O O
a DT B-NP O
single JJ I-NP O
S2 NN I-NP O
, , O O
and CC O O
no DT B-NP O
murmurs NNS I-NP O
, , O O
rubs NNS B-NP O
, , O O
or CC O O
gallops NNS B-NP O
. . O O
The DT O O
lower JJR B-NP O
extremity NN I-NP O
examination NN I-NP O
reveals VBZ B-VP O
a DT B-NP O
2 CD I-NP O
cm JJ I-NP O
tender NN I-NP O
superficial JJ I-NP O
area NN I-NP O
on IN B-PP O
the DT B-NP O
distal JJ B-NP O
right JJ I-NP O
calf NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
edema NN I-NP O
noted VBD B-VP O
. . O O
I PRP B-NP O
discussed VBD B-VP O
with IN B-PP O
Otis NNP B-NP B-PATIENT
Narvaez NNP I-NP I-PATIENT
and CC O O
his PRP$ B-NP O
wife NN I-NP O
, , O O
Santiago NNP B-NP B-PATIENT
, , O O
my PRP$ B-NP O
recommendations NNS I-NP O
for IN B-PP O
a DT B-NP O
cardiac NN I-NP O
catheterization NN B-NP O
followed VBN B-VP O
by IN B-PP O
stent JJ B-NP O
placement NN I-NP O
, , O O
as IN B-SBAR O
indicated VBN B-VP O
. . O O
He PRP B-NP O
has VBZ B-VP O
agreed VBN I-VP O
to TO B-PP O
this DT B-NP O
, , O O
and CC O O
Dr. NNP B-NP O
Yaziel NNP I-NP B-DOCTOR
Kraft NNP B-NP I-DOCTOR
will MD B-VP O
perform VB I-VP O
the DT B-NP O
procedure NN I-NP O
. . B-PP O
His PRP$ B-NP O
office NN I-NP O
will MD B-VP O
call VB I-VP O
Mr. NNP B-NP O
Narvaez NNP I-NP B-PATIENT
to TO B-VP O
schedule VB I-VP O
the DT O O
catheterization NN B-NP O
. . O O
After IN B-PP O
leaving VBG B-VP O
the DT B-NP O
office NN I-NP O
today NN I-NP O
, , O O
he PRP B-NP O
will MD B-VP O
have VB I-VP O
a DT B-NP O
CBC NNP I-NP O
, , O O
a DT B-NP O
PT NNP I-NP O
, , O O
a DT B-NP O
PTT NNP I-NP O
, , O O
and CC O O
a DT B-NP O
comprehensive JJ B-NP O
metabolic JJ I-NP O
profile NN I-NP O
performed VBN B-VP O
. . O O
He PRP B-NP O
will MD B-VP O
return VB I-VP O
to TO I-VP O
see VB I-VP O
me PRP B-NP O
in IN B-PP O
the DT B-NP O
office NN I-NP O
again RB B-ADVP O
in IN B-PP O
one CD B-NP O
month NN B-NP O
. . O O
Best JJS B-NP O
personal JJ I-NP O
regards NNS I-NP O
. . O O
Sincerely RB B-ADVP O
, , O O
Kenneth NNP B-NP B-DOCTOR
Z. NNP I-NP I-DOCTOR
Sellers NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
/ NN B-NP O
huff NN I-NP B-DOCTOR
Charlene NNP B-NP B-DOCTOR
B. NNP I-NP I-DOCTOR
Bates NNP I-NP I-DOCTOR
, , O O
RN NNP B-NP O
, , O O
BSN NNP B-NP O
Scribe NNP B-NP O
for IN B-PP O
Kenneth NNP B-NP B-DOCTOR
Z. NNP I-NP I-DOCTOR
Sellers NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
