Record NNP B-NP O
date NN I-NP O
: : O O
2085-04-22 CD O B-DATE
This DT B-NP O
patient NN I-NP O
wants VBZ B-VP O
to TO I-VP O
transfer VB I-VP O
his PRP$ B-NP O
care NN I-NP O
from IN B-PP O
the DT B-NP O
McCook NNP I-NP B-HOSPITAL
Erie NNP I-NP I-HOSPITAL
Clinic NNP I-NP I-HOSPITAL
to TO B-PP O
me PRP B-NP O
. . O O
He PRP O O
got VBN O O
my PRP$ B-NP O
name NN I-NP O
from IN B-PP O
a DT B-NP O
nurse NN I-NP O
who WP B-NP O
works VBZ B-VP O
in IN B-PP O
the DT B-NP O
hospital NN I-NP O
. . B-NP O
HE PRP B-NP O
is VBZ B-VP O
a DT B-NP O
58 CD I-NP B-AGE
year NN I-NP O
old JJ I-NP O
white JJ O O
male NN B-NP O
retired VBD B-VP O
Transportation NNP B-NP B-PROFESSION
Manager NNP I-NP I-PROFESSION
with IN B-PP O
a DT B-NP O
number NN I-NP O
of IN B-PP O
issues NNS B-NP O
. . O O
1 CD B-NP O
) -RRB- O O
He PRP B-NP O
had VBD B-VP O
a DT B-NP O
cyst NN I-NP O
or CC O O
a DT B-NP O
mass NN I-NP O
enlarge VB B-VP O
in IN B-PP O
his PRP$ B-NP O
R NN I-NP O
submental JJ I-NP O
region NN I-NP O
which WDT B-NP O
was VBD B-VP O
excised VBN O O
at IN B-PP O
the DT B-NP O
McCook NNP I-NP B-HOSPITAL
Erie NNP I-NP I-HOSPITAL
Clinic NNP I-NP I-HOSPITAL
. . O O
Note VB B-VP O
from IN B-PP O
his PRP$ B-NP O
surgeon NN I-NP O
there RB B-ADVP O
said VBD B-VP O
the DT B-NP O
path NN I-NP O
showed VBN O O
nonkaziating JJ B-NP O
granuloma NN I-NP O
. . O O
I PRP B-NP O
hope VBP B-VP O
cultures NNS B-NP O
are VBP B-VP O
pending VBG I-VP O
. . O O
The DT B-NP O
patient NN I-NP O
does VBZ B-LST O
volunteer NN B-NP O
at IN B-PP O
a DT B-NP O
homeless JJ I-NP O
shelter NN I-NP O
so RB B-ADVP O
could MD B-VP O
certainly RB I-VP O
be VB I-VP O
exposed VBN I-VP O
to TO B-PP O
TB NNP B-NP O
or CC O O
atypical JJ B-NP O
mycobacteria NNS I-NP O
. . O O
2 LS B-NP O
) -RRB- I-NP O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
know VB I-VP O
mitral JJ B-NP O
valve NN I-NP O
prolapse NN I-NP O
, , O O
mitral JJ B-NP O
regurgitation NN I-NP O
followed VBN O O
at IN B-PP O
the DT B-NP O
MEC NNP I-NP B-HOSPITAL
by IN B-PP O
a DT B-NP O
cardiologist NN I-NP O
. . O O
He PRP B-NP O
had VBD B-VP O
a DT B-NP O
stress NN I-NP O
test NN I-NP O
in IN B-PP O
the DT B-NP O
last JJ I-NP O
year NN I-NP O
that WDT B-NP O
was VBD B-VP O
benign JJ B-NP O
. . O O
Never RB B-VP O
had VBD I-VP O
CHF NNP B-NP O
or CC I-NP O
endocarditis NN I-NP O
. . O O
3 CD B-NP O
) -RRB- I-NP O
Social NNP I-NP O
situation NN I-NP O
. . B-PP O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
a DT B-NP O
sober JJ I-NP O
alcoholic JJ I-NP O
and CC I-NP O
sober JJ I-NP O
for IN B-PP O
the DT B-NP O
last JJ O O
2 CD B-NP O
years NNS I-NP O
however RB B-ADVP O
he PRP B-NP O
went VBD B-VP O
through IN B-PP O
divorce NN B-NP O
probably RB B-ADVP O
because IN B-PP O
of IN I-PP O
his PRP$ B-NP O
alcoholism NN I-NP O
10 CD B-NP O
years NNS I-NP O
ago RB B-ADVP O
and CC O O
took VBD B-VP O
early JJ B-NP O
retirement NN I-NP O
from IN B-PP O
Brookdale NNP B-NP B-ORGANIZATION
Metro NNP I-NP I-ORGANIZATION
Systems NNP I-NP I-ORGANIZATION
because IN O O
of IN B-PP O
his PRP$ B-NP O
alcoholism NN I-NP O
. . O O
He PRP B-NP O
stays VBZ B-VP O
sober JJ B-ADJP O
by IN B-PP O
going VBG B-VP O
to TO B-PP O
meetings NNS B-NP O
and CC O O
also RB O O
volunteering NN B-NP O
at IN B-PP O
the DT B-NP O
McCook NNP I-NP B-HOSPITAL
Clinic NNP I-NP I-HOSPITAL
. . O O
He PRP B-NP O
lives VBZ B-VP O
with IN B-PP O
a DT B-NP O
woman NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
good JJ B-LST O
relations NNS B-NP O
with IN B-PP O
his PRP$ B-NP O
grown JJ I-NP O
children NNS I-NP O
and CC O O
his PRP$ B-NP O
grand JJ I-NP O
children NNS I-NP O
. . O O
His PRP$ B-NP O
woman NN I-NP O
friend NN I-NP O
is VBZ B-VP O
very RB B-ADJP O
supportive JJ I-ADJP O
and CC O O
the DT B-NP O
patient NN I-NP O
is VBZ B-VP O
now RB I-VP O
feeling VBG I-VP O
good JJ B-ADJP O
enough RB B-ADVP O
about IN B-SBAR O
himself PRP B-NP O
that IN B-SBAR O
he PRP B-NP O
is VBZ B-VP O
ready JJ B-ADJP O
to TO B-VP O
try VB I-VP O
and CC I-VP O
get VB I-VP O
work NN B-NP O
full JJ I-NP O
time NN I-NP O
. . B-NP O
Previous JJ I-NP O
attempts NNS I-NP O
to TO B-VP O
do VB I-VP O
so RB O O
have VBP B-VP O
resulted VBN I-VP O
in IN B-PP O
failure NN B-NP O
because IN B-PP O
of IN I-PP O
his PRP$ B-NP O
Hx NN I-NP O
of IN B-PP O
alcoholism NN B-NP O
and CC O O
his PRP$ B-NP O
premature JJ I-NP O
retirement NN B-NP O
. . O O
Family NNP B-NP O
Hx NNP I-NP O
. . I-NP O
Father NNP I-NP O
died VBD B-VP O
at IN B-PP O
age NN B-NP O
79 CD I-NP B-AGE
of IN B-PP O
Altzheimers NNP B-NP O
and CC O O
some DT B-NP O
kind NN I-NP O
of IN B-PP O
cancer NN B-NP O
? . O O
throat NN B-NP O
cancer NN I-NP O
. . O O
His PRP$ B-NP O
mother NN I-NP O
had VBD B-VP O
diabetes NN B-NP O
and CC O O
coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
and CC O O
she PRP B-NP O
died VBD O O
of IN B-PP O
colon NN B-NP O
cancer NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
himself PRP B-NP O
had VBD B-VP O
a DT B-NP O
colonoscopy NN I-NP O
within IN B-PP O
the DT B-NP O
last JJ I-NP O
year NN B-NP O
and CC O O
it PRP B-NP O
was VBD B-VP O
normal JJ B-ADJP O
. . O O
One CD B-NP O
brother NN I-NP O
and CC O O
2 CD B-NP O
sisters NNS I-NP O
, , O O
one CD B-NP O
of IN B-PP O
the DT B-NP O
sisters NNS I-NP O
also RB B-LST O
has VBZ O O
mitral JJ B-NP O
valve NN I-NP O
disease NN I-NP O
. . O O
Past NNP B-NP O
medical JJ I-NP O
Hx IN B-PP O
the DT B-NP O
alcoholism NN I-NP O
and CC O O
he PRP B-NP O
was VBD B-VP O
stabbed VBN I-VP O
in IN B-PP O
the DT B-NP O
L NNP I-NP O
hand NN I-NP O
I PRP B-NP O
think VBP B-VP O
in IN B-PP O
2059 CD B-NP B-DATE
and CC O O
that DT B-NP O
was VBD B-VP O
repaired VBN I-VP O
. . O O
He PRP B-NP O
also RB B-ADVP O
had VBD B-VP O
a DT B-NP O
TNA NNP I-NP O
in IN B-PP O
childhood NN B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
no DT B-NP O
known VBN I-NP O
allergies NNS I-NP O
to TO B-PP O
medications NNS B-NP O
. . O O
The DT B-NP O
only JJ I-NP O
medication NN I-NP O
he PRP B-NP O
takes VBZ B-VP O
is VBZ B-VP O
Lisinopril NNP B-NP O
5 CD I-NP O
mg NN I-NP O
for IN B-PP O
blood NN B-NP O
pressure NN I-NP O
. . O O
He PRP B-NP O
was VBD B-LST O
only RB B-ADVP O
started VBD B-VP O
on IN B-PP O
this DT B-NP O
in IN B-PP O
the DT B-NP O
last JJ I-NP O
year NN I-NP O
. . O O
He PRP B-NP O
also RB B-ADVP O
takes VBZ B-VP O
a DT B-NP O
vitamin NN I-NP O
a DT B-NP O
day NN I-NP O
. . O O
His PRP$ B-NP O
other JJ I-NP O
significant JJ I-NP O
medical JJ I-NP O
complaint NN I-NP O
is VBZ B-VP O
erectile IN B-PP O
dysfunction NN B-NP O
. . O O
He PRP B-NP O
has VBZ B-LST O
normal JJ B-NP O
libido NN I-NP O
and CC O O
good JJ B-NP O
sexual JJ I-NP O
drive NN I-NP O
however RB B-ADVP O
he PRP B-NP O
tends VBZ B-VP O
to TO I-VP O
lose VB I-VP O
erection NN B-NP O
after IN B-PP O
he PRP O O
has VBZ B-VP O
gone VBN I-VP O
for IN B-PP O
a DT B-NP O
few JJ I-NP O
minutes NNS I-NP O
. . O O
He PRP B-NP O
can MD B-VP O
achieve VB I-VP O
vaginal JJ B-NP O
penetration NN I-NP O
. . O O
His PRP$ B-VP O
live VBP I-VP O
in IN B-PP O
lover NN B-NP O
has VBZ B-VP O
been VBN I-VP O
supportive JJ B-ADJP O
but CC O O
she PRP B-NP O
would MD B-VP O
like VB I-VP O
him PRP B-NP O
to TO B-VP O
have VB I-VP O
better JJR B-NP O
performance NN I-NP O
and CC O O
so RB B-ADVP O
would MD B-VP O
he PRP B-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
wake VB I-VP O
up RP B-PRT O
in IN B-PP O
the DT B-NP O
morning NN I-NP O
frequently RB B-ADVP O
with IN B-PP O
erections NNS B-NP O
. . O O
He PRP O O
has VBZ B-VP O
no DT B-NP O
known VBN I-NP O
Hx NN I-NP O
of IN B-PP O
diabetes NNS B-NP O
. . O O
No DT B-NP O
prolonged VBN I-NP O
hypertension NN I-NP O
or CC I-NP O
vascular JJ I-NP O
disease NN I-NP O
. . O O
Social NNP B-NP O
Hx NNP I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
eats VBZ B-VP O
fairly RB B-ADVP O
well RB I-ADVP O
. . O O
He PRP B-NP O
walks VBZ B-VP O
usually RB B-ADVP O
a DT B-NP O
mile NN I-NP O
or CC I-NP O
so RB I-NP O
a DT I-NP O
day NN B-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
not RB I-VP O
do VB I-VP O
any DT B-NP O
aerobic JJ I-NP O
activity NN I-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
smoke NN B-NP O
to TO B-PP O
a DT B-NP O
pack NN I-NP O
a DT B-NP O
day NN I-NP O
and CC O O
has VBZ O O
for IN B-PP O
many JJ B-NP O
, , I-NP O
many JJ I-NP O
years NNS I-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
wear VB I-VP O
seat NN B-NP O
belts NNS I-NP O
when WRB B-ADVP O
he PRP B-NP O
drives VBZ B-VP O
and CC I-VP O
does VBZ I-VP O
not RB O O
do VB O O
any DT B-NP O
elicit NN I-NP O
drugs NNS I-NP O
. . O O
On IN B-PP O
system NN B-NP O
review NN I-NP O
: : O O
Weight NNP B-NP O
stable NN I-NP O
. . O O
No DT B-NP O
change NN I-NP O
in IN B-PP O
skin NN B-NP O
. . O O
He PRP O O
always RB B-ADVP O
had VBD B-VP O
a DT B-NP O
very RB I-NP O
gravelly JJ I-NP O
voice NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
no DT B-NP O
change NN I-NP O
in IN B-PP O
his PRP$ B-NP O
vision NN I-NP O
. . O O
He PRP B-NP O
is VBZ B-LST O
very RB B-ADJP O
deaf JJ I-ADJP O
in IN B-PP O
the DT B-NP O
L NNP I-NP O
ear NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
a DT B-NP O
morning NN I-NP O
cough NN B-VP O
no DT B-NP O
hemoptysis NN I-NP O
. . O O
Cough '' O O
is VBZ O O
about IN O O
a DT B-NP O
teaspoon NN I-NP O
of IN B-PP O
white/gray JJ B-NP O
sputum NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
no DT B-NP O
dyspnea NN I-NP O
on IN B-PP O
exertion NN B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
no RB O O
angina NN B-NP O
. . B-VP O
No DT O O
palpitations NNPS B-NP O
. . O O
No DT B-NP O
presyncope NN I-NP O
or CC I-NP O
syncope NN I-NP O
. . O O
NO DT B-NP O
claudication NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-LST O
no DT B-NP O
dysphagia NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
no DT B-NP O
epigastric JJ I-NP O
discomfort NN I-NP O
. . O O
No DT B-NP O
change NN I-NP O
in IN B-PP O
his PRP$ B-NP O
bowel NN I-NP O
movements NNS B-NP O
and CC O O
no DT B-NP O
rectal JJ I-NP O
bleeding NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
no DT B-NP O
claudication NN I-NP O
. . O O
No DT B-NP O
edema NN I-NP O
and CC O O
no NN B-NP O
joint NN B-NP O
pains NNS I-NP O
. . O O
No DT B-NP O
headaches NNS I-NP O
and CC O O
no DT B-NP O
low JJ I-NP O
back RB I-NP O
pain NN I-NP O
. . O O
No DT B-NP O
long JJ I-NP O
bone NN I-NP O
pain NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-LST O
no UH O O
heat NN B-NP O
or CC I-NP O
cold JJ I-NP O
intolerance NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
no DT B-NP O
easy JJ I-NP O
bruisability NN I-NP O
. . O O
PE NN B-NP O
: : O O
shows NNS B-NP O
him PRP B-NP O
to TO B-VP O
5'7" VB I-VP O
. . B-NP O
155 CD I-NP O
lbs NNS I-NP O
. . O O
Skin NNP B-NP O
benign JJ I-NP O
. . O O
Nails NNPS B-NP O
do VBP B-VP O
show VB I-VP O
some DT B-NP O
early JJ I-NP O
clubbing VBG B-VP O
. . O O
No DT B-NP O
cyanosis NN I-NP O
. . O O
Normal '' O O
no DT B-NP O
AV NNP I-NP O
knicking NN I-NP O
. . O O
Flat NNP B-NP O
disks NNS I-NP O
. . B-NP O
Pupils NNS I-NP O
equally RB O O
round NN B-NP O
and CC I-NP O
reactive NN I-NP O
to TO B-PP O
light NN B-NP O
and CC I-NP O
accommodation NN I-NP O
at IN B-PP O
3 CD B-NP O
mm CD I-NP O
. . B-NP O
Nares NNP I-NP O
normal JJ I-NP O
. . O O
TMs '' O O
normal JJ B-NP O
. . B-NP O
Hearing NNP I-NP O
is VBZ B-VP O
markedly RB I-VP O
diminished VBN I-VP O
in IN B-PP O
the DT B-NP O
L NNP I-NP O
ear NN I-NP O
. . O O
Head NN B-NP O
is VBZ B-VP O
normal JJ B-NP O
cephalic NN I-NP O
. . O O
Thyroid NNP B-NP O
not RB B-ADVP O
enlarged VBD B-VP O
. . O O
There EX B-NP O
is VBZ B-VP O
the DT B-NP O
scar NN I-NP O
at IN B-PP O
the DT B-NP O
site NN I-NP O
of IN B-PP O
his PRP$ B-NP O
excision NN I-NP O
under IN B-PP O
the DT O O
mandible JJ B-NP O
. . O O
No DT B-NP O
associated VBN I-NP O
adenopathy NN I-NP O
on IN B-PP O
either DT B-NP O
R NN I-NP O
or CC I-NP O
L NNP I-NP O
neck NN I-NP O
or CC I-NP O
axilla NN I-NP O
or CC O O
the DT B-NP O
supraclavicular JJ B-NP O
region NN I-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
hyperesonant JJ B-NP O
to TO B-PP O
percussion NN B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
distant JJ B-LST O
breath NN B-NP O
sounds NNS I-NP O
. . O O
No DT B-NP O
rales NNS I-NP O
, , O O
rhonchi NNP B-NP O
or CC I-NP O
wheezes NNS I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
normal JJ B-NP O
S1 NNS I-NP O
. . O O
Normal NNP B-NP O
S2 NNP I-NP O
and CC O O
holosystolic VB B-VP O
blowing VBG B-NP O
2-3/6 CD I-NP O
mid JJ I-NP O
systolic JJ I-NP O
murmur NN I-NP O
radiates NNS I-NP O
best RB B-ADVP O
to TO B-PP O
the DT B-NP O
axilla NN I-NP O
. . O O
No UH B-INTJ O
radiation NN B-NP O
to TO B-PP O
the DT B-NP O
clavicles NNS I-NP O
. . O O
No DT B-NP O
carotid NN I-NP O
bruits NNS I-NP O
. . O O
Jugular NNP B-NP O
venous JJ I-NP O
pulsation NN I-NP O
to TO B-PP O
7 CD B-NP O
sonometers NNS B-NP O
. . O O
Abdomen NNP B-NP O
is VBZ B-VP O
soft JJ B-ADJP O
and CC O O
non JJ B-NP O
tender NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
enlargement NN I-NP O
of IN B-PP O
the DT O O
liver NN B-NP O
. . B-VP O
No DT B-NP O
adeventitious JJ I-NP O
masses NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
a DT B-NP O
L NNP I-NP O
inguinal JJ I-NP O
weakness NN I-NP O
without IN B-PP O
frank JJ B-NP O
hernia NN B-NP O
. . O O
Phallus NN B-NP O
uncircumsized JJ I-NP O
. . B-NP O
Testes NNP I-NP O
normal JJ I-NP O
. . O O
Prostate NNP B-NP O
is VBZ B-VP O
a DT B-NP O
little JJ I-NP O
difficult JJ I-NP O
feel NN B-NP O
because IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
a DT B-NP O
band NN I-NP O
around IN B-PP O
the DT B-NP O
anal NN I-NP O
sphincter NN I-NP O
which WDT B-NP O
makes VBZ B-VP O
it PRP B-NP O
difficult JJ O O
for IN B-SBAR O
me PRP B-NP O
to TO B-VP O
get VB I-VP O
beyond IN B-ADVP O
but CC O O
I PRP B-NP O
felt VBD B-VP O
probably RB B-NP O
half NN I-NP O
of IN B-PP O
his PRP$ B-NP O
prostate NN I-NP O
and CC O O
it PRP B-NP O
was VBD B-VP O
normal JJ B-NP O
and CC I-NP O
smooth JJ I-NP O
. . O O
Stool NNP B-NP O
was VBD B-VP O
guac VBN I-VP O
negative JJ B-ADJP O
. . O O
Reflexes NNP B-NP O
3+ NNP I-NP O
and CC O O
equal JJ B-ADJP O
throughout IN B-PP O
and CC O O
normal JJ B-NP O
vibratory JJ I-NP O
sense NN I-NP O
and CC I-NP O
touch NN I-NP O
. . O O
Normal JJ B-NP O
gait NN I-NP O
and CC I-NP O
station NN I-NP O
. . O O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
: : O O
1 CD B-NP O
) -RRB- I-NP O
Recent JJ I-NP O
rapidly RB B-VP O
growing VBG I-VP O
mass NN B-NP O
under IN B-PP O
the DT B-NP O
R NN I-NP O
mandible JJ I-NP O
showing NN I-NP O
nonkaziating VBG I-NP O
granuloma NN B-NP O
. . O O
Culture NN B-NP O
is VBZ B-VP O
pending VBG I-VP O
and CC O O
we PRP B-NP O
will MD B-VP O
plant VB I-VP O
a DT B-NP O
PPD NNP I-NP O
and CC I-NP O
control NN I-NP O
early RB O O
next JJ B-NP O
week NN I-NP O
. . O O
I PRP B-NP O
will MD B-VP O
have VB I-VP O
him PRP B-NP O
tracked VBN B-VP O
down IN B-PP O
the DT B-NP O
report NN I-NP O
of IN B-PP O
this DT B-NP O
from IN B-PP O
the DT B-NP O
MEC NNP I-NP B-HOSPITAL
and CC O O
get VB B-NP O
culture NN I-NP O
reports NNS I-NP O
and CC O O
will MD B-VP O
get VB I-VP O
chest NN B-NP O
x-ray NN I-NP O
today NN I-NP O
both CC O O
for IN B-PP O
his PRP$ B-NP O
COPD NN I-NP O
to TO O O
rule NN B-NP O
out IN B-PP O
a DT B-NP O
cavitary JJ I-NP O
lesion NN I-NP O
. . O O
2 CD B-NP O
) -RRB- I-NP O
Alcoholism NN I-NP O
now RB B-ADJP O
sober JJ I-ADJP O
. . O O
3 CD B-NP O
) -RRB- O O
Erectile RB B-VP O
dysfunction RB I-VP O
try VB I-VP O
Viagra NNP B-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
given VBN I-VP O
appropriate JJ B-NP O
warnings NNS I-NP O
and CC O O
instructions NNS B-NP O
. . O O
I PRP B-NP O
gave VBD B-VP O
him PRP B-NP O
100 CD B-NP O
mg JJ I-NP O
# # I-NP O
7. CD O O
4 CD B-NP O
) -RRB- I-NP O
Mitral NNP I-NP O
valve NN I-NP O
prolapse NN I-NP O
by IN B-PP O
auscultation NN B-NP O
followed VBN B-VP O
by IN B-PP O
cardiologist NN B-NP O
at IN B-PP O
the DT B-NP O
MEC NNP I-NP B-HOSPITAL
. . O O
5 CD B-NP O
) -RRB- O O
We PRP B-NP O
spent VBD B-VP O
a DT B-NP O
long JJ I-NP O
time NN I-NP O
talking VBG B-VP O
about IN B-PP O
smoking VBG B-NP O
cessation NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
some DT O O
Wellbutrin NNP B-NP O
at IN B-PP O
home NN B-NP O
from IN B-PP O
when WRB B-ADVP O
he PRP B-NP O
was VBD B-VP O
depressed VBN I-VP O
while IN B-PP O
getting VBG B-VP O
sober JJ B-NP O
and CC I-NP O
I PRP I-NP O
encouraged VBD B-VP O
him PRP B-NP O
to TO B-VP O
take VB I-VP O
150 CD B-NP O
b.i.d NN I-NP O
. . O O
and CC O O
we PRP B-NP O
made VBD B-VP O
a DT B-NP O
plan NN I-NP O
for IN B-PP O
him PRP B-NP O
to TO B-VP O
try VB I-VP O
and CC O O
quit VB B-VP O
. . O O
I PRP B-NP O
will MD B-VP O
see VB I-VP O
patient NN B-NP O
again RB B-ADVP O
next JJ B-NP O
week NN I-NP O
to TO B-VP O
plant VB I-VP O
a DT B-NP O
PPD NNP I-NP O
and CC O O
then RB O O
see VB B-VP O
him PRP B-NP O
again RB B-ADVP O
in IN B-PP O
about IN B-NP O
a DT I-NP O
month NN I-NP O
to TO B-VP O
see VB I-VP O
how WRB B-ADVP O
he PRP B-NP O
is VBZ B-VP O
doing VBG I-VP O
. . O O
We PRP B-NP O
will MD B-VP O
certainly RB I-VP O
check VB I-VP O
the DT O O
chest NN B-NP O
x-ray NN I-NP O
to TO B-VP O
make VB I-VP O
sure JJ B-ADJP O
he PRP B-NP O
did VBD B-VP O
not RB I-VP O
have VB I-VP O
active JJ B-NP O
cavitary JJ I-NP O
disease NN I-NP O
. . O O
Leroy NNP B-NP B-DOCTOR
X NNP I-NP I-DOCTOR
. . I-NP I-DOCTOR
Oshea NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
******** NN B-NP O
Not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Physician JJ B-NP O
******** NNS I-NP O
