Record NNP B-NP O
date NN I-NP O
: : O O
2085-09-02 CD O B-DATE
September NNP B-NP B-DATE
03 CD I-NP I-DATE
, , I-NP I-DATE
2085 CD O I-DATE
Bill NNP B-NP B-DOCTOR
X NNP I-NP I-DOCTOR
. . I-NP I-DOCTOR
Stafford NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Chief NNP B-NP O
, , O O
Transplant NNP B-NP O
Divistion NNP I-NP O
Department NNP B-NP O
of IN B-PP O
Surgery NNP B-NP O
Family NNP B-NP B-HOSPITAL
Practice NNP I-NP I-HOSPITAL
Missoula NNP I-NP I-HOSPITAL
Re NNP B-NP O
: : O O
Peggy NNP B-NP B-PATIENT
Tinsley NNP I-NP I-PATIENT
FPM NNP B-NP B-HOSPITAL
# # I-NP O
: : O O
236-67-03-3 CD O B-MEDICALRECORD
Dear NNP B-NP O
Dr. NNP I-NP O
Stafford NNP I-NP B-DOCTOR
: : O O
I PRP B-NP O
was VBD B-VP O
asked VBN I-VP O
to TO B-VP O
provide VB I-VP O
a DT B-NP O
cardiologic NN I-NP O
evaluation NN I-NP O
on IN B-PP O
Mrs. NNP B-NP O
Tinsley NNP B-NP B-PATIENT
with IN B-PP O
a DT B-NP O
concentration NN I-NP O
on IN B-PP O
her PRP$ B-NP O
appropriateness NN I-NP O
to TO B-VP O
be VB I-VP O
listed VBN I-VP O
as IN B-PP O
a DT B-NP O
recipient NN I-NP O
for IN B-PP O
a DT B-NP O
cadaver NN I-NP O
renal JJ I-NP O
transplant NN I-NP O
. . O O
In IN B-PP O
summary NN B-NP O
, , O O
she PRP B-NP O
is VBZ B-VP O
a DT B-NP O
46 CD I-NP B-AGE
year NN I-NP O
old JJ I-NP O
woman NN I-NP O
who WP B-NP O
has VBZ B-VP O
been VBN I-VP O
an DT B-NP O
insulin NN I-NP O
dependent JJ I-NP O
diabetic NN I-NP O
since IN B-PP O
the DT B-NP O
age NN I-NP O
of IN B-PP O
29 CD B-NP B-AGE
and CC O O
has VBZ B-VP O
been VBN I-VP O
on IN B-PP O
hemodialysis NN B-NP O
since IN B-PP O
2083 CD B-NP B-DATE
. . O O
By IN O O
report NN B-NP O
, , O O
her PRP$ B-NP O
other JJ I-NP O
complications NNS I-NP O
for IN B-PP O
diabetes NNS B-NP O
include VBP B-VP O
retinopathy NN B-NP O
, , O O
peripheral JJ B-NP O
neuropathy NN I-NP O
, , O O
and CC O O
peripheral JJ B-NP O
vascular JJ I-NP O
disease NN I-NP O
. . O O
In IN B-PP O
viewing VBG B-UCP O
her PRP$ B-NP O
present JJ I-NP O
history NN I-NP O
, , O O
she PRP B-NP O
works VBZ B-VP O
in IN B-PP O
the DT B-NP O
Houghton NNP I-NP B-ORGANIZATION
Mifflin NNP I-NP I-ORGANIZATION
Harcourt NNP I-NP I-ORGANIZATION
learning VBG B-VP I-ORGANIZATION
technology NN B-NP I-ORGANIZATION
department NN I-NP I-ORGANIZATION
. . O O
Her PRP$ O O
three CD B-NP O
times NNS I-NP O
a DT B-NP O
week NN I-NP O
hemodialyses NNS I-NP O
are VBP B-VP O
uncomplicated JJ B-ADJP O
. . O O
She PRP B-NP O
does VBZ B-VP O
, , O O
however RB B-ADVP O
, , O O
experience VB B-VP O
occasional JJ B-NP O
chest NN I-NP O
pressure NN I-NP O
with IN B-PP O
activities NNS B-NP O
and CC O O
on IN B-PP O
rare JJ B-NP O
occasions NNS I-NP O
has VBZ B-VP O
had VBN I-VP O
nocturnal JJ B-NP O
angina NN I-NP O
. . O O
These DT B-NP O
episodes NNS I-NP O
are VBP B-LST O
relieved VBN B-VP O
by IN B-PP O
nitroglycerin NN B-NP O
. . O O
Mrs. NNP B-NP O
Tinsley NNP I-NP B-PATIENT
has VBZ B-VP O
also RB I-VP O
noted VBN I-VP O
that IN B-PP O
with IN O O
walking VBG B-VP O
she PRP B-NP O
will MD B-VP O
occasionally RB I-VP O
get VB I-VP O
short JJ B-ADJP O
of IN B-PP O
breath NN B-NP O
which WDT B-NP O
is VBZ B-VP O
relieved VBN I-VP O
by IN B-PP O
slowing VBG B-VP O
down RP B-PRT O
. . O O
In IN B-PP O
addition NN B-NP O
to TO B-PP O
diabetes NNS B-NP O
and CC O O
hypertension NN B-NP O
which WDT B-NP O
was VBD B-VP O
present JJ I-VP O
only RB B-ADVP O
pre-dialysis NN B-NP O
, , O O
she PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
and CC O O
continues VBZ B-VP O
to TO I-VP O
be VB I-VP O
a DT B-NP O
smoker NN I-NP O
. . O O
Her PRP$ O O
cholesterol NN B-NP O
by IN B-PP O
one CD B-NP O
report NN I-NP O
was VBD B-VP O
228 CD B-NP O
mg/dl NN I-NP O
. . O O
I PRP B-NP O
do VBP B-VP O
n't RB I-VP O
have VB I-VP O
fractionations NNS B-NP O
and CC O O
her PRP$ B-NP O
family NN I-NP O
history NN I-NP O
is VBZ B-VP O
unknown JJ B-ADJP O
. . O O
A DT B-NP O
report NN I-NP O
of IN B-PP O
an DT B-NP O
echocardiogram NN I-NP O
from IN B-PP O
April NNP B-NP B-DATE
of IN B-PP I-DATE
2083 CD B-NP I-DATE
, , O O
shows VBZ B-VP O
mild JJ O O
ventricular JJ B-NP O
hypertrophy NN I-NP O
in IN B-PP O
the DT B-NP O
presence NN I-NP O
of IN B-PP O
mitral JJ B-NP O
insufficiency NN I-NP O
, , O O
preserved VBN B-VP O
LV NNP B-NP O
size NN I-NP O
and CC I-NP O
function NN I-NP O
. . O O
She PRP B-NP O
had VBD B-VP O
an DT B-NP O
exercise NN I-NP O
tolerance NN I-NP O
test NN I-NP O
in IN B-PP O
February NNP B-NP B-DATE
of IN B-PP I-DATE
2085 CD B-NP I-DATE
. . O O
On IN B-PP O
a DT B-NP O
modified VBN I-NP O
protocol NN I-NP O
, , O O
she PRP B-NP O
went VBD B-VP O
for IN B-PP O
less RBR B-NP O
than IN B-PP O
4 CD B-NP O
1/2 CD I-NP O
minutes NNS I-NP O
. . O O
This DT B-NP O
is VBZ B-VP O
equivalent JJ B-ADJP O
to TO B-VP O
not RB I-VP O
even RB I-VP O
completing VBG I-VP O
stage NN B-NP O
1 CD I-NP O
of IN B-PP O
the DT B-NP O
standard NN I-NP O
Bruce NNP B-NP O
. . O O
With IN B-PP O
that DT B-NP O
, , O O
she PRP B-NP O
did VBD B-VP O
develop VB I-VP O
chest NN B-NP O
pain NN B-NP O
and CC I-NP O
had VBD B-VP O
2 CD B-NP O
mm CD I-NP O
of IN B-PP O
ST NNP B-NP O
depression NN I-NP O
. . O O
That DT B-NP O
study NN I-NP O
was VBD B-VP O
accompanied VBN I-VP O
by IN B-PP O
both DT B-NP O
fixed JJ I-NP O
and CC I-NP O
reversible JJ I-NP O
isotopic NN I-NP O
perfusion NN I-NP O
changes NNS I-NP O
in IN B-PP O
the DT B-NP O
septum NN I-NP O
consistent JJ B-ADJP O
with IN B-PP O
prior JJ B-NP O
non-transmural JJ I-NP O
infarct NN I-NP O
with IN B-PP O
exercise NN B-NP O
induced VBN O O
ischemia NN B-NP O
. . O O
As IN O O
was VBD B-VP O
apparent JJ B-ADJP O
to TO B-PP O
those DT B-NP O
involved VBN B-VP O
, , O O
even RB B-NP O
the DT I-NP O
non-isotope NN I-NP O
portion NN B-NP O
alone RB B-ADVP O
was VBD B-VP O
worrisome JJ B-ADJP O
for IN B-PP O
high JJ B-NP O
grade NN I-NP O
coronary JJ I-NP O
disease NN I-NP O
and CC O O
led VBN B-NP O
to TO B-PP O
the DT B-NP O
recommendation NN I-NP O
for IN B-PP O
a DT B-NP O
cardiac JJ I-NP O
catheterization NN I-NP O
. . O O
That DT B-NP O
study NN I-NP O
was VBD B-VP O
done VBN I-VP O
in IN B-PP O
Macdonald NNP B-NP B-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
and CC B-PP O
at IN B-PP O
this DT B-NP O
time NN I-NP O
, , O O
I PRP B-NP O
only RB B-ADVP O
have VBP B-VP O
the DT B-NP O
report NN I-NP O
. . O O
However RB B-ADVP O
, , O O
from IN B-PP O
this DT B-NP O
report NN I-NP O
, , O O
there EX B-NP O
was VBD B-VP O
preserved VBD O O
LV NNP B-NP O
function NN I-NP O
with IN B-PP O
anterior JJ B-NP O
lateral JJ I-NP O
hypokinesis NN I-NP O
and CC O O
trace NN B-NP O
MR NNP B-NP O
that DT B-NP O
is VBZ B-VP O
consistent JJ B-ADJP O
with IN B-PP O
the DT B-NP O
echo NN I-NP O
and CC O O
the DT B-NP O
thallium NN I-NP O
studies NNS I-NP O
. . O O
Coronary JJ B-NP O
angiography NN I-NP O
showed VBD B-VP O
by IN B-PP O
report NN B-NP O
, , O O
diffuse JJ B-NP O
involvement NN I-NP O
of IN B-PP O
proximal JJ B-NP O
mid-LAD NN I-NP O
without IN B-PP O
specific JJ B-NP O
focal JJ I-NP O
stenosis NN I-NP O
until IN B-PP O
an DT B-NP O
80 CD I-NP O
% NN I-NP O
mid JJ B-ADJP O
- : O O
LAD. NNP B-NP O
The DT B-NP O
circumflex NN I-NP O
was VBD B-VP O
also RB B-ADVP O
diffusely JJ B-ADJP O
diseased JJ I-ADJP O
and CC O O
there EX B-NP O
was VBD B-VP O
a DT O O
discrete JJ B-NP O
stenosis NN I-NP O
in IN B-PP O
the DT B-NP O
mid JJ I-NP O
section NN I-NP O
of IN B-PP O
a DT B-NP O
large JJ I-NP O
marginal JJ I-NP O
. . O O
The DT O O
right JJ B-NP O
coronary JJ I-NP O
artery NN I-NP O
was VBD B-VP O
diffusely JJ B-ADJP O
diseased JJ I-ADJP O
with IN B-PP O
a DT B-NP O
discrete NN I-NP O
stenosis NN B-NP O
. . B-VP O
At IN B-PP O
that DT B-NP O
time NN I-NP O
, , O O
the DT B-NP O
recommendation NN I-NP O
was VBD B-VP O
to TO I-VP O
continue VB I-VP O
medical JJ O O
therapy NN B-NP O
. . O O
Her PRP$ B-NP O
medical JJ I-NP O
therapy NN I-NP O
at IN B-PP O
this DT B-NP O
time NN I-NP O
is VBZ B-VP O
estrogen NN B-NP O
replacement NN I-NP O
with IN B-PP O
prempro NN B-NP O
2.5 CD I-NP O
mg NN I-NP O
once IN B-PP O
a DT B-NP O
day NN I-NP O
, , O O
tenormin NN B-NP O
25 CD I-NP O
mg NN I-NP O
qd NN I-NP O
, , O O
aspirin VBG B-VP O
one CD B-NP O
every DT O O
other JJ B-NP O
day NN I-NP O
in IN B-PP O
addition NN B-NP O
to TO B-PP O
her PRP$ B-NP O
supplemental JJ I-NP O
vitamins NNS I-NP O
, , O O
iron NN B-NP O
and CC O O
twice RB O O
daily JJ B-NP O
insulin NN I-NP O
therapy NN I-NP O
. . O O
In IN B-PP O
rounding VBG B-VP O
out RP B-PRT O
her PRP$ B-NP O
medical JJ I-NP O
history NN I-NP O
, , O O
her PRP$ B-NP O
surgical JJ I-NP O
procedures NNS I-NP O
have VBP B-VP O
involved VBN I-VP O
the DT B-NP O
hemodialysis NN I-NP O
access NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
one CD B-NP O
pregnancy NN I-NP O
28 CD B-NP O
years NNS I-NP O
ago RB B-ADVP O
without IN B-PP O
complications NNS B-NP O
. . O O
I PRP B-NP O
also RB B-ADVP O
elicited VBD B-VP O
a DT B-NP O
history NN I-NP O
of IN B-PP O
some DT B-NP O
focal JJ I-NP O
arm NN I-NP O
weakness NN I-NP O
and CC O O
occasional JJ B-NP O
slurring VBG I-NP O
of IN B-PP O
speech NN B-NP O
. . O O
This DT O O
was VBD B-VP O
difficult JJ B-ADJP O
to TO B-VP O
pin VB I-VP O
down RP B-PRT O
, , O O
but CC O O
is VBZ B-VP O
of IN B-PP O
some DT B-NP O
concern NN I-NP O
. . O O
On IN B-PP O
exam NN B-NP O
, , O O
her PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
was VBD B-VP O
150/8 CD B-NP O
0 CD I-NP O
mm CD I-NP O
Hg NNP I-NP O
, , O O
pulse NN B-NP O
90 CD I-NP O
regular JJ B-ADJP O
, , O O
her PRP$ B-NP O
weight NN I-NP O
95 CD B-NP O
lbs NNS I-NP O
. . O O
Her PRP$ B-NP O
hemodialysis NN I-NP O
shunt NN I-NP O
is VBZ B-VP O
on IN B-PP O
the DT B-NP O
left NN I-NP O
arm NN B-NP O
. . O O
There EX B-NP O
was VBD B-VP O
a DT B-NP O
right JJ I-NP O
carotid NN I-NP O
bruit NN I-NP O
, , O O
neck NN B-NP O
veins NNS I-NP O
were VBD B-VP O
not RB O O
distended VBN B-VP O
. . B-NP O
Lungs NNP I-NP O
were VBD B-VP O
clear JJ B-ADJP O
, , O O
PMI NNP B-NP O
was VBD B-VP O
displaced VBN I-VP O
and CC O O
sustained VBN B-VP O
. . O O
There EX B-NP O
was VBD B-VP O
an DT B-NP O
S4 NNP I-NP O
, , O O
no DT B-NP O
S3 NN I-NP O
and CC O O
there EX B-NP O
was VBD B-VP O
a DT B-NP O
holo NN I-NP O
systolic JJ I-NP O
murmur NN I-NP O
at IN B-PP O
the DT O O
apex NN B-NP O
. . O O
Abdomen '' O O
was VBD B-VP O
benign JJ B-ADJP O
, , O O
femoral JJ B-NP O
pulses NNS I-NP O
were VBD B-VP O
intact JJ B-ADJP O
, , O O
extremities NNS B-NP O
were VBD B-VP O
without IN B-PP O
edema NN B-NP O
. . O O
The DT B-NP O
electrocardiogram NN I-NP O
showed VBD B-VP O
sinus IN B-PP O
rhythm NN B-NP O
, , O O
diffuse JJ B-NP O
STT NNP I-NP O
changes NNS I-NP O
. . O O
There EX B-NP O
were VBD B-VP O
no DT B-NP O
pathologic NN I-NP O
Q NN I-NP O
waves NNS I-NP O
. . O O
Although IN B-SBAR O
the DT B-NP O
focus NN I-NP O
of IN B-PP O
this DT B-NP O
evaluation NN I-NP O
was VBD B-VP O
originally RB B-ADVP O
for IN B-PP O
transplant NN B-NP O
candidacy NN I-NP O
, , O O
I PRP B-NP O
am VBP B-VP O
concerned VBN B-ADJP O
about IN B-PP O
her PRP$ B-NP O
current JJ I-NP O
cardiac NN I-NP O
status NN B-NP O
. . O O
She PRP B-NP O
is VBZ B-VP O
a DT B-NP O
young JJ I-NP O
diabetic JJ I-NP O
woman NN I-NP O
, , O O
symptomatic JJ B-ADJP O
of IN B-PP O
both DT O O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
and CC I-NP O
chest NN I-NP O
pain NN I-NP O
and CC O O
on IN B-PP O
exercise NN B-NP O
test NN I-NP O
, , O O
has VBZ O O
limited JJ B-NP O
functional JJ I-NP O
capacity NN I-NP O
. . O O
The DT B-NP O
coronary JJ I-NP O
angiography NN I-NP O
reveals VBZ B-VP O
a DT O O
presence NN B-NP O
of IN B-PP O
multi-vessel JJ B-NP O
disease NN I-NP O
. . B-PP O
Even RB B-ADVP O
without IN B-PP O
seeing VBG B-VP O
the DT B-NP O
primary JJ I-NP O
data NNS B-NP O
which WDT O O
I PRP B-NP O
hope VBP B-VP O
to TO I-VP O
do VB I-VP O
in IN B-PP O
the DT B-NP O
next JJ I-NP O
week NN I-NP O
, , O O
it PRP B-NP O
would MD B-VP O
be VB I-VP O
unlikely JJ B-ADJP O
that IN B-SBAR O
she PRP B-NP O
would MD B-VP O
be VB I-VP O
an DT B-NP O
angioplasty JJ I-NP O
candidate NN I-NP O
, , O O
given VBN B-PP O
the DT B-NP O
poor JJ I-NP O
results NNS I-NP O
in IN B-PP O
diabetics NNS B-NP O
. . O O
Therefore RB B-ADVP O
, , O O
coronary JJ B-NP O
revascularization NN I-NP O
for IN B-PP O
her PRP B-NP O
would MD B-VP O
be VB I-VP O
coronary JJ B-NP O
artery NN I-NP O
bypass NN B-NP O
surgery NN I-NP O
. . O O
Obviously RB B-ADVP O
, , O O
I PRP B-NP O
would MD B-VP O
like VB I-VP O
to TO I-VP O
review VB I-VP O
the DT B-NP O
films NNS I-NP O
first RB B-ADVP O
, , O O
and CC O O
speak VB B-UCP O
with IN B-PP O
Dr. NNP B-NP O
Upson NNP I-NP B-DOCTOR
regarding VBG B-VP O
augmentation NN B-NP O
of IN B-PP O
her PRP$ B-NP O
anti-anginals NNS I-NP O
. . O O
I NN O O
would MD O O
also RB B-ADVP O
like VB B-VP O
to TO I-VP O
add VB I-VP O
pravastatin NN B-NP O
at IN B-PP O
this DT B-NP O
time NN I-NP O
, , O O
starting VBG B-VP O
with IN B-SBAR O
only RB O O
10 CD B-NP O
mg NN I-NP O
and CC O O
obtain VB B-VP O
non-invasive JJ B-NP O
studies NNS I-NP O
of IN B-PP O
the DT B-NP O
carotids NNS I-NP O
. . O O
As IN O O
indicated VBN B-VP O
, , O O
although IN B-SBAR O
the DT B-NP O
focus NN I-NP O
of IN B-PP O
this DT B-NP O
evaluation NN I-NP O
was VBD B-VP O
her PRP$ I-VP O
suitability NN B-NP O
for IN B-PP O
transplantation NN B-NP O
, , O O
the DT B-NP O
issue NN I-NP O
of IN B-PP O
controlling VBG O O
symptomatic JJ B-NP O
coronary JJ I-NP O
artery NN I-NP O
disease NN I-NP O
in IN B-PP O
this DT B-NP O
young JJ I-NP O
woman NN I-NP O
became VBD B-VP O
more RBR B-PRT O
pressing VBG B-VP O
. . O O
I PRP B-NP O
look VBP B-VP O
forward RB B-ADVP O
to TO B-PP O
working VBG B-VP O
with IN B-PP O
you PRP B-NP O
and CC O O
the DT B-NP O
other JJ I-NP O
physicians NNS I-NP O
in IN B-PP O
her PRP$ B-NP O
care NN I-NP O
. . O O
Sincerely RB B-ADVP O
, , O O
Quentin NNP B-NP B-DOCTOR
U. NNP I-NP I-DOCTOR
Johnson NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
, , O O
Ph.D. NNP B-NP O
Quentin NNP B-NP B-DOCTOR
U. NNP I-NP I-DOCTOR
Johnson NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
, , O O
Ph.D. NNP B-NP O
DD NNP B-NP O
: : O O
9/03/8 CD B-NP I-DATE
5 CD I-NP I-DATE
DT NNP B-NP O
: : O O
9/03/8 CD B-NP I-DATE
5 CD I-NP I-DATE
DV NNP B-NP O
: : O O
9/02/8 CD B-NP I-DATE
5 CD I-NP I-DATE
QUJ NN B-NP B-DOCTOR
: : O O
jarrell NN B-NP B-DOCTOR
cc NN B-NP O
: : O O
Verlon NNP B-NP B-DOCTOR
Ventura NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
, , O O
6593 CD B-NP B-STREET
Edmatteric NNP I-NP I-STREET
Drive NNP I-NP I-STREET
, , O O
Cheney NNP B-NP B-CITY
, , O O
TX RB O B-STATE
37523 CD O B-ZIP
Archie NNP B-NP B-DOCTOR
Oreilly NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
, , O O
Family NNP B-NP B-HOSPITAL
Practice NNP I-NP I-HOSPITAL
Missoula NNP I-NP I-HOSPITAL
Ivan NNP B-NP B-DOCTOR
Upson NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
, , O O
Radford NNP B-NP B-HOSPITAL
Community NNP I-NP I-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
, , O O
0808 CD B-NP B-STREET
O’neil’s NNP I-NP I-STREET
Court NNP I-NP I-STREET
, , O O
Effingham NNP B-NP B-CITY
, , O O
TX NNP B-NP B-STATE
38866 CD I-NP B-ZIP
Bill NNP B-NP B-DOCTOR
R. NNP I-NP I-DOCTOR
Joe NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
, , O O
Macdonald NNP B-NP B-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
, , O O
726 CD B-NP B-STREET
Kehoe NNP I-NP I-STREET
Avenue NNP I-NP I-STREET
, , O O
Cheney NNP B-NP B-CITY
, , O O
TX NNP B-NP B-STATE
37523 CD I-NP B-ZIP
******** NN B-NP O
Approved NNP I-NP O
but CC O O
not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Provider NNP B-NP O
******** . O O
