Record NNP B-NP O
date NN I-NP O
: : O O
2074-04-02 CD O B-DATE
Patient NNP B-NP O
Name NNP I-NP O
: : O O
LOUIS,ROBERT NNP B-NP B-PATIENT
[ NNP I-NP O
MRN NNP I-NP O
: : O O
85588852 CD B-NP B-MEDICALRECORD
LGH NNP I-NP B-HOSPITAL
] SYM O O
Date NNP B-NP O
of IN B-PP O
Visit NNP B-NP O
: : O O
04/02/2074 CD O B-DATE
History NN B-NP O
of IN B-PP O
Present NNP B-NP O
Illness NNP I-NP O
*H&P NN B-NP O
conducted VBN B-VP O
with IN B-PP O
interpreter NN B-NP O
present NN I-NP O
. . O O
70 CD B-NP B-AGE
M NNP I-NP O
DM NNP I-NP O
, , O O
HTN NNP B-NP O
, , O O
CAD NNP B-NP O
, , O O
CHF NNP B-NP O
( -LRB- I-NP O
CAD NN I-NP O
vs JJ B-NP O
EtOH) NNP I-NP O
, , O O
COPD NNP B-NP O
, , O O
elevated VBD B-VP O
PSA NNP B-NP O
, , O O
here RB B-ADVP O
for IN B-PP O
routine JJ B-NP O
follow-up JJ I-NP O
appointment NN I-NP O
. . O O
1 CD B-NP O
) -RRB- I-NP O
R>L IN B-PP O
groin/testicular/buttock JJR B-NP O
pain NN I-NP O
x1mo NN I-NP O
. . O O
No DT B-NP O
F/C/N/V/D/melena/hematochezia/dysuria/hematuria NNP I-NP O
. . I-NP O
Seen NNP I-NP O
in IN B-PP O
ED NNP B-NP O
3/17/74 CD I-NP B-DATE
, , O O
found VBD B-VP O
to TO I-VP O
have VB I-VP O
very RB B-NP O
small JJ I-NP O
reducible JJ I-NP O
hernia NN I-NP O
and CC O O
exophytic JJ B-NP O
bladder NN I-NP O
mass NN I-NP O
by IN B-PP O
U/S NNP B-NP O
( -LRB- I-NP O
3.6x2.7x2.4cm NN I-NP O
, , O O
indenting JJ B-NP O
base NN I-NP O
of IN B-PP O
bladder NN B-NP O
, , O O
bladder NN B-NP O
vs JJ I-NP O
prostate NN I-NP O
) -RRB- I-NP O
. . O O
Pt NNP B-NP O
has VBZ B-VP O
multiple JJ B-NP O
RF NN I-NP O
's POS I-NP O
for IN B-PP O
bladder NN B-NP O
ca MD B-VP O
: : I-VP O
smoking NN B-NP O
, , O O
EtOH. NNP B-NP O
Also RB B-ADVP O
had VBD B-VP O
had VBN I-VP O
h/o VBN I-VP O
BPH NNP B-NP O
, , O O
elevated VBD B-VP O
PSA NNP B-NP O
, , O O
with IN B-PP O
failure NN B-NP O
to TO B-PP O
F/U NNP B-NP O
to TO B-VP O
urology VB I-VP O
appts NNS B-NP O
. . B-NP O
PSA NN I-NP O
: : O O
4/73 CD B-NP B-DATE
=4.8 CD I-NP O
, , I-NP O
3/72 CD I-NP B-DATE
=4.1 CD I-NP O
, , O O
10/70 CD B-NP B-DATE
=5.0, JJ I-NP O
2/70 CD I-NP B-DATE
=9.4 CD I-NP O
, , I-NP O
11/67 CD I-NP B-DATE
=5.9 CD I-NP O
, , I-NP O
8/65 CD I-NP B-DATE
=5.9 CD I-NP O
, , I-NP O
7/63 CD I-NP B-DATE
=4.2 CD I-NP O
. . O O
Pt NNP B-NP O
states NNS I-NP O
he PRP B-NP O
had VBD B-VP O
prostate NN B-NP O
biopsy NN I-NP O
at IN B-PP O
EDUCARE-FARGO NNP B-NP B-HOSPITAL
7yrs NNP I-NP O
ago RB B-ADVP O
, , O O
which WDT B-NP O
was VBD B-VP O
apparently RB B-ADVP O
negative JJ B-ADJP O
. . O O
Have VBP B-VP O
asked VBD I-VP O
pt VB I-VP O
to TO I-VP O
obtain VB I-VP O
these DT B-NP O
records NNS I-NP O
on IN B-PP O
multiple JJ B-NP O
occasions NNS I-NP O
, , O O
but CC O O
he PRP B-NP O
has VBZ B-VP O
not RB I-VP O
. . O O
Saw VBD B-VP O
urology NN B-NP O
for IN B-PP O
initial JJ B-NP O
visit NN I-NP O
5/73 CD I-NP B-DATE
; : O O
since IN B-NP O
then RB B-ADVP O
has VBZ B-VP O
missed VBN I-VP O
3 CD B-NP O
follow-up JJ I-NP O
appointments NNS I-NP O
for IN B-PP O
prostate NN B-NP O
biopsy NN I-NP O
. . O O
2 CD B-NP O
) -RRB- I-NP O
HTN. . O O
Pt NNP B-NP O
hypertensive JJ I-NP O
today NN B-NP O
. . O O
Pt NNP B-NP O
admitted VBD B-VP O
upon IN B-PP O
hospitalization NN B-NP O
11/73 CD I-NP B-DATE
that IN B-SBAR O
he PRP B-NP O
had VBD B-VP O
not RB I-VP O
been VBN I-VP O
taking VBG I-VP O
his PRP$ B-NP O
meds NNS I-NP O
, , O O
states NNS B-NP O
he PRP B-NP O
is VBZ B-VP O
taking VBG I-VP O
them PRP B-NP O
now RB B-ADVP O
. . O O
3 CD B-NP O
) -RRB- I-NP O
CAD. NNP I-NP O
Cardiac NNP I-NP O
RF NNP I-NP O
's POS B-NP O
: : O O
DM NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
smoking NN B-NP O
, , O O
age NN B-NP O
. . O O
Denies NNS B-NP O
: : O O
CP CD B-NP O
, , O O
SOB NNP B-NP O
, , O O
LE JJ B-NP O
edema NN I-NP O
, , O O
orthopnea NN B-NP O
, , O O
PND. NNP B-NP O
Followed NNP I-NP O
by IN B-PP O
Dr NNP B-NP O
Ferraro NNP I-NP B-DOCTOR
( -LRB- I-NP O
Cardiology NN I-NP O
) -RRB- I-NP O
. . O O
Mibi NNP B-NP O
1/72 CD I-NP B-DATE
: : O O
23 CD B-NP O
% NN I-NP O
, , O O
5 CD B-NP O
mets NNS I-NP O
, , I-NP O
neg NN I-NP O
. . O O
NQWMI NNP B-NP O
10/70 CD I-NP B-DATE
. . O O
Cath NNP B-NP O
10/70 CD I-NP B-DATE
: : O O
30 CD B-NP O
% NN I-NP O
RCA NN I-NP O
. . O O
NEG '' O O
ETT NNP B-NP O
'68 CD I-NP B-DATE
. . O O
4 CD B-NP O
) -RRB- I-NP O
CHF. NNP I-NP O
Hospitalized NNP I-NP O
11/73 CD I-NP B-DATE
for IN B-PP O
CHF. NNP B-NP O
Denies NNS I-NP O
: : O O
CP CD B-NP O
, , O O
SOB NNP B-NP O
, , O O
LE JJ B-NP O
edema NN I-NP O
, , O O
orthopnea NN B-NP O
, , O O
PND NNP B-NP O
since IN B-PP O
D/C NNP B-NP O
home NN I-NP O
. . B-NP O
11/73 CD I-NP B-DATE
: : O O
EF NNP B-NP O
30-35 CD I-NP O
% NN I-NP O
, , O O
global JJ B-NP O
hk NN I-NP O
, , O O
trace NN B-NP O
AI NNP I-NP O
, , O O
trace NN B-NP O
MR NNP I-NP O
, , O O
trace NN B-NP O
TR NN I-NP O
, , O O
RVH. NNP B-NP O
CXR NNP I-NP O
6/73 CD I-NP B-DATE
: : O O
"pulmonary JJ B-NP O
vascular JJ I-NP O
engorgment NN I-NP O
without IN B-PP O
overt JJ B-NP O
pulmonary JJ I-NP O
edema NN I-NP O
, , O O
?scarring VBG B-VP O
LUL" NNP B-NP O
PFT NNP I-NP O
's POS B-NP O
5/73 CD I-NP B-DATE
: : O O
poor-quality JJ B-NP O
study NN I-NP O
, , O O
FEV1=1.36 NNP B-NP O
( -LRB- I-NP O
58 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
, , I-NP O
FVC=1.93 FW I-NP O
( -LRB- I-NP O
66 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
, , O O
FEV1/FVC=91 NNP B-NP O
% NN I-NP O
. . O O
5 CD B-NP O
) -RRB- I-NP O
DM. NNP I-NP O
FS=114 NNP I-NP O
in IN B-PP O
clinic NN B-NP O
today NN B-NP O
. . O O
Given VBN B-VP O
CHF NNP B-NP O
and CC O O
increasing VBG B-VP O
Cr NNP B-NP O
, , O O
D/C NNP B-NP O
Metformin NNP I-NP O
at IN B-PP O
last JJ B-NP O
visit NN I-NP O
, , O O
pt NN B-VP O
currently RB B-ADVP O
only RB I-ADVP O
on IN B-PP O
Glyburide NNP B-NP O
5mg CD I-NP O
QD. NNP I-NP O
Fasting NNP I-NP O
am VBP B-VP O
FS NNS B-NP O
110-124 CD B-NP O
, , O O
has VBZ B-VP O
not RB I-VP O
been VBN I-VP O
checking VBG B-ADJP O
post-prandial JJ I-ADJP O
FS. . O O
6 CD B-NP O
) -RRB- I-NP O
EtOH. NNP I-NP O
Pt NNP I-NP O
states NNS I-NP O
he PRP B-NP O
is VBZ B-VP O
drinking VBG I-VP O
1/2 CD B-NP O
pint NN I-NP O
of IN B-PP O
rum NN B-NP O
Qwk NN I-NP O
. . O O
Recommended VBN B-VP O
that IN B-SBAR O
he PRP B-NP O
decrease VB B-VP O
this DT B-NP O
amount NN I-NP O
. . O O
Discussed VBN B-VP O
my PRP$ B-NP O
concern NN I-NP O
that IN B-PP O
his PRP$ B-NP O
EtOH NNP I-NP O
was VBD B-VP O
contributing VBG I-VP O
to TO B-PP O
his PRP$ B-NP O
heart NN I-NP O
disease NN I-NP O
. . O O
Problems NNS B-NP O
Diabetes NNP B-NP O
mellitus NN I-NP O
Hypertension NN B-NP O
CAD NN B-NP O
NQWMI . O O
Congestive NNP B-NP O
heart NN I-NP O
failure NN I-NP O
EtOH . O O
COPD NN B-NP O
Smoking VBG O O
BPH NNP B-NP O
, , O O
Elevated NNP B-NP O
PSA NNP I-NP O
Prostatic JJ B-NP O
nodule NN I-NP O
Diverticula NN B-NP O
OA NN B-NP O
of IN B-PP O
lumbar NN B-NP O
spine NN I-NP O
Bladder NNP B-NP O
mass NN I-NP O
Health NNP B-NP O
Maintenance NNP I-NP O
Cholesterol NNP B-NP O
04/04/2073 CD I-NP B-DATE
129 CD I-NP O
( -LRB- B-PP O
Desirable NNP B-NP O
<200 CD I-NP O
, , O O
High JJ B-NP O
>240 CD I-NP O
) -RRB- O O
Cholesterol-HDL NNP B-NP O
04/04/2073 CD I-NP B-DATE
43 CD O O
Cholesterol-LDL NNP B-NP O
04/04/2073 CD I-NP B-DATE
70 CD O O
Colonoscopy NNP B-NP O
11/14/2073 CD I-NP B-DATE
Pt NNP I-NP O
refused VBN I-NP O
Complete JJ B-NP O
Physical JJ I-NP O
Exam NNP I-NP O
04/02/2074 CD O B-DATE
Creatinine NNP B-NP O
03/19/2074 CD I-NP B-DATE
0.9 CD O O
EKG NNP B-NP O
02/13/2069 CD I-NP B-DATE
SMMC NNP I-NP B-HOSPITAL
Final NNP I-NP O
HBA1C JJ B-NP O
04/04/2073 CD I-NP B-DATE
6.5 CD I-NP O
Hct NNP B-NP O
( -LRB- I-NP O
Hematocrit NN I-NP O
) -RRB- I-NP O
03/19/2074 CD I-NP B-DATE
43.5 CD O O
Hgb NNP B-NP O
( -LRB- I-NP O
Hemoglobin NNP I-NP O
) -RRB- I-NP O
03/19/2074 CD I-NP B-DATE
14.3 CD O O
Home NNP B-NP O
glucose NN I-NP O
monitoring NN I-NP O
04/02/2074 VBD B-VP B-DATE
Fasting VBG I-VP O
am VBP I-VP O
: : O O
110-124 CD O O
Hypoglycemia NNP B-NP O
Assessment/Counseling NNP I-NP O
04/02/2074 CD I-NP B-DATE
Denies NNS I-NP O
Influenza NNP B-NP O
Vaccine NNP I-NP O
11/15/2073 CD I-NP B-DATE
PT NNP I-NP O
RECEIVED NNP I-NP O
FLU NNP I-NP O
VACCINE NNP I-NP O
PER NNP I-NP O
PCP. NNP I-NP O
LO NNP I-NP O
T# NNP I-NP O
340211 CD I-NP B-IDNUM
-EXP. NNP B-NP O
7/03/74 CD I-NP B-DATE
. . O O
M-alb/creat JJ B-NP O
ratio NN I-NP O
05/16/2073 IN B-PP B-DATE
24.6 CD B-NP O
Units NNS I-NP O
= SYM O O
mg JJ B-NP O
Alb/g NNP I-NP O
Cre NNP I-NP O
Mammogram NNP B-NP O
03/27/2070 CD I-NP B-DATE
Mammography NNP I-NP O
Bilateral NNP I-NP O
Microalbumin NNP B-NP O
05/16/2073 CD I-NP B-DATE
3.0 CD O O
Ophthal NNP B-NP O
Exam NNP I-NP O
04/02/2074 CD I-NP B-DATE
appt NN I-NP O
4/74 CD I-NP B-DATE
Done/scheduled VBN O O
Pneumovax NNP B-NP O
11/02/2070 CD I-NP B-DATE
PNEUMOCOCCAL NNP I-NP O
VACCINE NNP I-NP O
IM NNP I-NP O
IN IN B-PP O
L NNP B-NP O
DELTOID. NNP I-NP O
PNEUMOVAX NNP I-NP O
23 CD I-NP O
. . O O
LOT NNP B-NP O
4050 CD I-NP B-IDNUM
. . O O
EXP NNP B-NP O
30Aug71 NNP I-NP B-DATE
. . O O
Podiatry NNP B-NP O
exam NN I-NP O
07/12/2072 NN I-NP B-DATE
WNL . O O
Sigmoidoscopy NNP B-NP O
09/05/2068 CD I-NP B-DATE
*See NNP I-NP O
Report NNP I-NP O
Smoking VBG B-NP O
status NN I-NP O
05/16/2073 IN B-PP B-DATE
1/2PPD DT B-NP O
x50yrs NNS I-NP O
Current JJ I-NP O
smoker NN I-NP O
Counsel NN I-NP O
: : O O
05/16/2073 CD O B-DATE
Stool NN B-NP O
Guaiac NNP I-NP O
02/22/2069 CD I-NP B-DATE
STOOL NNP I-NP O
GUAIAC NNP I-NP O
NEG. NNP I-NP O
X NNP I-NP O
3 CD I-NP O
CARDS . O O
Triglycerides NNS B-NP O
04/04/2073 CD B-NP B-DATE
82 CD I-NP O
UA-Protein NNP B-NP O
03/19/2074 CD I-NP B-DATE
NEG . O O
Medications NNS B-NP O
ALBUTEROL NNP B-NP O
( -LRB- I-NP O
INHALER NN I-NP O
) -RRB- I-NP O
2PUFF IN B-PP O
INH NNP B-NP O
QID . O O
AMLODIPINE NNP B-NP O
10MG VBD B-VP O
PO NNP B-NP O
QD . O O
ATENOLOL NNP B-NP O
50MG VBD B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
ATROVENT NNP B-NP O
INHALER NNP I-NP O
( -LRB- I-NP O
IPRATROPIUM NN I-NP O
INHALER NN I-NP O
) -RRB- I-NP O
2PUFF IN B-PP O
INH NNP B-NP O
QID . O O
ECASA NNP B-NP O
( -LRB- I-NP O
ASPIRIN NNP I-NP O
ENTERIC NNP I-NP O
COATED NNP I-NP O
) -RRB- I-NP O
325MG JJ I-NP O
PO NN I-NP O
QD . O O
FOLATE NN B-NP O
( -LRB- I-NP O
FOLIC NN I-NP O
ACID NNP I-NP O
) -RRB- I-NP O
1MG . I-NP O
PO NNP I-NP O
QD . O O
GLYBURIDE NNP B-NP O
5MG VBD B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
LISINOPRIL NNP B-NP O
40MG VBD B-VP O
PO NNP B-NP O
QD . O O
MVI NNP B-NP O
( -LRB- I-NP O
MULTIVITAMINS NNS I-NP O
) -RRB- I-NP O
1CAPSULE JJ I-NP O
PO NN I-NP O
QD . O O
THIAMINE NNP B-NP O
HCL NNP I-NP O
100MG . I-NP O
PO NNP I-NP O
QD . O O
TORSEMIDE NNP B-NP O
20MG VBD B-VP O
2 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Allergies . O O
NKDA NNP B-NP O
NONE NNP I-NP O
Vital JJ B-NP O
Signs NNS I-NP O
Blood NN B-NP O
Pressure NN I-NP O
: : O O
142/8 CD B-NP O
4 CD I-NP O
Left VBN B-VP O
Arm NN O O
Weight NNP B-NP O
: : O O
178 CD B-NP O
Pounds NNS I-NP O
Physical NNP B-NP O
Exam NNP I-NP O
General NNP B-NP O
Appearance NNP I-NP O
NAD. . O O
Skin NNP B-NP O
Peri-anal JJ B-NP O
area NN I-NP O
: : O O
dry JJ B-NP O
skin NN I-NP O
, , O O
no DT B-NP O
blisters/lesions NNS I-NP O
. . O O
Abdomen . O O
Soft NNP B-NP O
, , O O
NT NNP B-NP O
, , O O
ND NNP B-NP O
, , O O
NABS NNP B-NP O
, , O O
no DT B-NP O
HSM. NNP I-NP O
Extremity NN B-NP O
2+ JJ B-NP O
DP/PT NNP I-NP O
pulses NNS I-NP O
. . B-NP O
No NN I-NP O
C/C/E. . O O
Genito-Urinary JJ O O
Very RB B-NP O
small JJ I-NP O
R NN I-NP O
inguinal JJ I-NP O
hernia NN I-NP O
. . O O
Mild NNP B-NP O
tenderness NN I-NP O
on IN B-PP O
balotting NN B-NP O
of IN B-PP O
L NNP B-NP O
testicle NN I-NP O
, , O O
epididymis VBD B-VP O
not RB I-VP O
inflamed VBN I-VP O
. . O O
Plan NN B-NP O
*H&P NN B-NP O
conducted VBN B-VP O
with IN B-PP O
interpreter NN B-NP O
present NN I-NP O
. . O O
70 CD B-NP B-AGE
M NNP I-NP O
DM NNP I-NP O
, , O O
HTN NNP B-NP O
, , O O
CAD NNP B-NP O
, , O O
CHF NNP B-NP O
( -LRB- I-NP O
CAD NN I-NP O
vs JJ B-NP O
EtOH) NNP I-NP O
, , O O
COPD NNP B-NP O
, , O O
elevated VBD B-VP O
PSA NNP B-NP O
, , O O
here RB B-ADVP O
for IN B-PP O
routine JJ B-NP O
follow-up JJ I-NP O
appointment NN I-NP O
. . O O
1 CD B-NP O
) -RRB- I-NP O
R>L IN B-PP O
groin/testicular/buttock JJR B-NP O
pain NN I-NP O
x1mo NN I-NP O
. . O O
No DT B-NP O
F/C/N/V/D/melena/hematochezia/dysuria/hematuria NNP I-NP O
. . I-NP O
Seen NNP I-NP O
in IN B-PP O
ED NNP B-NP O
3/17/74 CD I-NP B-DATE
, , O O
found VBD B-VP O
to TO I-VP O
have VB I-VP O
very RB B-NP O
small JJ I-NP O
reducible JJ I-NP O
hernia NN I-NP O
and CC O O
exophytic JJ B-NP O
bladder NN I-NP O
mass NN I-NP O
by IN B-PP O
U/S NNP B-NP O
( -LRB- I-NP O
3.6x2.7x2.4cm NN I-NP O
, , O O
indenting JJ B-NP O
base NN I-NP O
of IN B-PP O
bladder NN B-NP O
, , O O
bladder NN B-NP O
vs JJ I-NP O
prostate NN I-NP O
) -RRB- I-NP O
. . O O
Pt NNP B-NP O
has VBZ B-VP O
multiple JJ B-NP O
RF NN I-NP O
's POS I-NP O
for IN B-PP O
bladder NN B-NP O
ca MD B-VP O
: : I-VP O
smoking NN B-NP O
, , O O
EtOH. NNP B-NP O
Also RB B-ADVP O
had VBD B-VP O
had VBN I-VP O
h/o VBN I-VP O
BPH NNP B-NP O
, , O O
elevated VBD B-VP O
PSA NNP B-NP O
, , O O
with IN B-PP O
failure NN B-NP O
to TO B-PP O
F/U NNP B-NP O
to TO B-VP O
urology VB I-VP O
appts NNS B-NP O
. . B-NP O
PSA NN I-NP O
: : O O
4/73 CD B-NP B-DATE
=4.8 CD I-NP O
, , I-NP O
3/72 CD I-NP B-DATE
=4.1 CD I-NP O
, , O O
10/70 CD B-NP B-DATE
=5.0, JJ I-NP O
2/70 CD I-NP B-DATE
=9.4 CD I-NP O
, , I-NP O
11/67 CD I-NP B-DATE
=5.9 CD I-NP O
, , I-NP O
8/65 CD I-NP B-DATE
=5.9 CD I-NP O
, , I-NP O
7/63 CD I-NP B-DATE
=4.2 CD I-NP O
. . O O
Pt NNP B-NP O
states NNS I-NP O
he PRP B-NP O
had VBD B-VP O
prostate NN B-NP O
biopsy NN I-NP O
at IN B-PP O
OKMH NNP B-NP B-HOSPITAL
7yrs NNP I-NP O
ago RB B-ADVP O
, , O O
which WDT B-NP O
was VBD B-VP O
apparently RB B-ADVP O
negative JJ B-ADJP O
. . O O
Have VBP B-VP O
asked VBD I-VP O
pt VB I-VP O
to TO I-VP O
obtain VB I-VP O
these DT B-NP O
records NNS I-NP O
on IN B-PP O
multiple JJ B-NP O
occasions NNS I-NP O
, , O O
but CC O O
he PRP B-NP O
has VBZ B-VP O
not RB I-VP O
. . O O
Saw VBD B-VP O
urology NN B-NP O
for IN B-PP O
initial JJ B-NP O
visit NN I-NP O
5/73 CD I-NP B-DATE
; : O O
since IN B-NP O
then RB B-ADVP O
has VBZ B-VP O
missed VBN I-VP O
3 CD B-NP O
follow-up JJ I-NP O
appointments NNS I-NP O
for IN B-PP O
prostate NN B-NP O
biopsy NN I-NP O
. . O O
Urgent JJ B-NP O
referral NN I-NP O
to TO B-VP O
urology VB I-VP O
for IN B-PP O
cystoscopy NN B-NP O
, , O O
?prostate NN B-NP O
bx NN I-NP O
. . O O
2 CD B-NP O
) -RRB- I-NP O
HTN. . O O
Pt NNP B-NP O
hypertensive JJ I-NP O
today NN B-NP O
. . O O
Pt NNP B-NP O
admitted VBD B-VP O
upon IN B-PP O
hospitalization NN B-NP O
11/73 CD I-NP B-DATE
that IN B-SBAR O
he PRP B-NP O
had VBD B-VP O
not RB I-VP O
been VBN I-VP O
taking VBG I-VP O
his PRP$ B-NP O
meds NNS I-NP O
, , O O
states NNS B-NP O
he PRP B-NP O
is VBZ B-VP O
taking VBG I-VP O
them PRP B-NP O
now RB B-ADVP O
. . O O
Refill NN B-NP O
Atenolol/Lisinopril NNP I-NP O
, , O O
increase NN B-NP O
Amlodipine NNP I-NP O
to TO B-PP O
10mg CD B-NP O
QD. . O O
Check VB B-VP O
Chem7 NNP B-NP O
. . O O
3 CD B-NP O
) -RRB- I-NP O
CAD. NNP I-NP O
Cardiac NNP I-NP O
RF NNP I-NP O
's POS B-NP O
: : O O
DM NNP B-NP O
, , O O
HTN NNP B-NP O
, , O O
smoking NN B-NP O
, , O O
age NN B-NP O
. . O O
Denies NNS B-NP O
: : O O
CP CD B-NP O
, , O O
SOB NNP B-NP O
, , O O
LE JJ B-NP O
edema NN I-NP O
, , O O
orthopnea NN B-NP O
, , O O
PND. NNP B-NP O
Followed NNP I-NP O
by IN B-PP O
Dr NNP B-NP O
Ferraro NNP I-NP B-DOCTOR
( -LRB- I-NP O
Cardiology NN I-NP O
) -RRB- I-NP O
. . O O
Mibi NNP B-NP O
1/72 CD I-NP B-DATE
: : O O
23 CD B-NP O
% NN I-NP O
, , O O
5 CD B-NP O
mets NNS I-NP O
, , I-NP O
neg NN I-NP O
. . O O
NQWMI NNP B-NP O
10/70 CD I-NP B-DATE
. . O O
Cath NNP B-NP O
10/70 CD I-NP B-DATE
: : O O
30 CD B-NP O
% NN I-NP O
RCA NN I-NP O
. . O O
NEG '' O O
ETT NNP B-NP O
'68 CD I-NP B-DATE
. . O O
Refill NN B-VP O
ASA NNP B-NP O
, , O O
Atenolol NNP B-NP O
, , O O
Lisinopril NNP B-NP O
. . I-NP O
Fasting NNP I-NP O
lipids NNS I-NP O
WNL NNP I-NP O
4/73 CD I-NP B-DATE
( -LRB- I-NP O
LDL=70 NN I-NP O
) -RRB- I-NP O
, , O O
pt NN B-NP O
did VBD B-VP O
not RB I-VP O
check VB I-VP O
at IN B-PP O
last JJ B-NP O
visit NN I-NP O
, , O O
check VB B-VP O
this DT B-NP O
wk NN I-NP O
. . O O
4 CD B-NP O
) -RRB- I-NP O
CHF. NNP I-NP O
Hospitalized NNP I-NP O
11/73 CD I-NP B-DATE
for IN B-PP O
CHF. NNP B-NP O
Denies NNS I-NP O
: : O O
CP CD B-NP O
, , O O
SOB NNP B-NP O
, , O O
LE JJ B-NP O
edema NN I-NP O
, , O O
orthopnea NN B-NP O
, , O O
PND NNP B-NP O
since IN B-PP O
D/C NNP B-NP O
home NN I-NP O
. . O O
On IN B-PP O
PE NN B-NP O
, , O O
wt=178lb VBD B-VP O
(up JJ B-NP O
6lb NN I-NP O
) -RRB- I-NP O
, , O O
but CC O O
JVP NNP B-NP O
flat JJ I-NP O
, , O O
lungs NNS B-NP O
CTA IN B-PP O
B NNP B-NP O
, , O O
no RB B-NP O
LE JJ I-NP O
edema NN I-NP O
. . B-PP O
11/73 CD B-NP B-DATE
: : O O
EF NNP B-NP O
30-35 CD I-NP O
% NN I-NP O
, , O O
global JJ B-NP O
hk NN I-NP O
, , O O
trace NN B-NP O
AI NNP I-NP O
, , O O
trace NN B-NP O
MR NNP I-NP O
, , O O
trace NN B-NP O
TR NN I-NP O
, , O O
RVH. NNP B-NP O
CXR NNP I-NP O
6/73 CD I-NP B-DATE
: : O O
"pulmonary JJ B-NP O
vascular JJ I-NP O
engorgment NN I-NP O
without IN B-PP O
overt JJ B-NP O
pulmonary JJ I-NP O
edema NN I-NP O
, , O O
?scarring VBG B-VP O
LUL" NNP B-NP O
PFT NNP I-NP O
's POS B-NP O
5/73 CD I-NP B-DATE
: : O O
poor-quality JJ B-NP O
study NN I-NP O
, , O O
FEV1=1.36 NNP B-NP O
( -LRB- I-NP O
58 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
, , I-NP O
FVC=1.93 FW I-NP O
( -LRB- I-NP O
66 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
, , O O
FEV1/FVC=91 NNP B-NP O
% NN I-NP O
. . O O
Consider VB B-VP O
chest NN B-NP O
CT NNP I-NP O
, , O O
referral NN B-NP O
for IN B-PP O
cardiopulmonary JJ B-NP O
testing NN I-NP O
. . B-NP O
Refill NN I-NP O
Atenolol NNP I-NP O
, , I-NP O
Lisinopril NNP I-NP O
, , I-NP O
Torsemide NNP I-NP O
. . O O
5 CD B-NP O
) -RRB- I-NP O
DM. NNP I-NP O
FS=114 NNP I-NP O
in IN B-PP O
clinic NN B-NP O
today NN B-NP O
. . O O
Given VBN B-VP O
CHF NNP B-NP O
and CC O O
increasing VBG B-VP O
Cr NNP B-NP O
, , O O
D/C NNP B-NP O
Metformin NNP I-NP O
at IN B-PP O
last JJ B-NP O
visit NN I-NP O
, , O O
pt NN B-VP O
currently RB B-ADVP O
only RB I-ADVP O
on IN B-PP O
Glyburide NNP B-NP O
5mg CD I-NP O
QD. NNP I-NP O
Fasting NNP I-NP O
am VBP B-VP O
FS NNS B-NP O
110-124 CD B-NP O
, , O O
has VBZ B-VP O
not RB I-VP O
been VBN I-VP O
checking VBG I-VP O
post-prandial JJ B-NP O
FS-encouraged JJ I-NP O
him PRP B-NP O
to TO B-VP O
do VB I-VP O
this DT B-NP O
. . O O
Refill NN B-VP O
Glyburide NNP B-NP O
. . O O
Last JJ B-ADJP O
HgbA1C=6.5 CD B-NP O
in IN B-PP O
4/73 CD B-NP B-DATE
, , O O
pt NN B-NP O
did VBD B-VP O
not RB I-VP O
check VB I-VP O
at IN B-PP O
last JJ B-NP O
visit NN I-NP O
, , O O
check VB B-VP O
this DT B-NP O
wk NN I-NP O
. . O O
Urine '' O O
microalbumin NN B-NP O
<30 CD I-NP O
in IN B-PP O
5/73 CD B-NP B-DATE
, , O O
repeat NN B-NP O
at IN B-PP O
next JJ B-NP O
visit NN I-NP O
. . O O
Pt NNP B-NP O
has VBZ B-VP O
ophthalmology NN B-NP O
appt NN I-NP O
next JJ B-NP O
month NN I-NP O
. . O O
6 CD B-NP O
) -RRB- I-NP O
EtOH. NNP I-NP O
Pt NNP I-NP O
states NNS I-NP O
he PRP B-NP O
is VBZ B-VP O
drinking VBG I-VP O
1/2 CD B-NP O
pint NN I-NP O
of IN B-PP O
rum NN B-NP O
Qwk NN I-NP O
. . O O
Recommended VBN B-VP O
that IN B-SBAR O
he PRP B-NP O
decrease VB B-VP O
this DT B-NP O
amount NN I-NP O
. . O O
Discussed VBN B-VP O
my PRP$ B-NP O
concern NN I-NP O
that IN B-PP O
his PRP$ B-NP O
EtOH NNP I-NP O
was VBD B-VP O
contributing VBG I-VP O
to TO B-PP O
his PRP$ B-NP O
heart NN I-NP O
disease NN I-NP O
. . O O
Continue VB B-VP O
to TO I-VP O
follow VB I-VP O
. . O O
Refill NNP B-NP O
Thiamine NNP I-NP O
, , O O
Folate NNP B-NP O
, , O O
MVit NNP B-NP O
. . O O
7 CD B-NP O
) -RRB- I-NP O
Health NNP I-NP O
maintenance NN I-NP O
. . O O
Pt '' O O
again RB B-ADVP O
refused VBD B-VP O
colonoscopy NN B-NP O
, , O O
forgot VBD B-VP O
to TO I-VP O
do VB I-VP O
stool NN B-NP O
cards NNS I-NP O
after IN B-PP O
last JJ B-NP O
visit NN I-NP O
, , O O
send VB B-VP O
pt NN B-NP O
home NN I-NP O
again RB B-ADVP O
with IN B-PP O
stool NN B-NP O
cardsx3 NNS I-NP O
. . O O
Flu NN B-NP O
shot VBD B-VP O
given VBN I-VP O
this DT B-NP O
season NN I-NP O
. . O O
8 CD B-NP O
) -RRB- I-NP O
RTC NNP I-NP O
in IN B-PP O
1-2 JJ B-NP O
months NNS I-NP O
for IN B-PP O
visit NN B-NP O
. . O O
Bailey NNP B-NP B-DOCTOR
Bray NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
