Record NNP B-NP O
date NN I-NP O
: : O O
2078-05-10 CD O B-DATE
Vital JJ B-NP O
signs NNS I-NP O
BP NNP B-NP O
140/88 CD I-NP O
, , O O
P NNP B-NP O
68 CD I-NP O
, , O O
Wt NNP B-NP O
172 CD I-NP O
lb NN I-NP O
69 CD B-NP B-AGE
year NN I-NP O
old JJ I-NP O
male JJ I-NP O
returns NNS I-NP O
with IN B-PP O
daughter NN B-NP O
and CC I-NP O
grandson NN I-NP O
for IN B-PP O
follow-up NN B-NP O
of IN B-PP O
diabetes NNS B-NP O
and CC I-NP O
hypertension NN I-NP O
. . O O
he PRP B-NP O
was VBD B-VP O
seen VBN I-VP O
here RB B-NP O
several JJ I-NP O
weeks NNS I-NP O
ago RB B-ADVP O
after IN B-PP O
a DT B-NP O
4 CD I-NP O
month NN I-NP O
absence NN I-NP O
when WRB B-ADVP O
he PRP B-NP O
was VBD B-VP O
in IN B-PP O
the DT B-NP B-COUNTRY
UK NNP I-NP I-COUNTRY
. . O O
hgba1c '' O O
and CC O O
creatinine VB B-NP O
were VBD B-VP O
checked VBN I-VP O
at IN B-PP O
the DT B-NP O
time NN I-NP O
, , O O
and CC O O
bp NN B-NP O
was VBD B-VP O
to TO I-VP O
be VB I-VP O
rechecked VBN I-VP O
as IN B-SBAR O
it PRP B-NP O
was VBD B-VP O
not RB I-VP O
optimally RB I-VP O
controlled VBN I-VP O
. . O O
the DT B-NP O
patient JJ I-NP O
returns NNS I-NP O
feeling VBG B-VP O
well RB B-ADVP O
, , O O
denies VBZ B-VP O
chest NN B-NP O
pain NN I-NP O
, , O O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
, , O O
PND NNP B-NP O
, , O O
orthopnea NN B-NP O
, , O O
change NN B-NP O
in IN B-PP O
exercise NN B-NP O
tolerance NN I-NP O
. . O O
he PRP B-NP O
is VBZ B-VP O
taking VBG I-VP O
medications NNS B-NP O
as IN B-PP O
directed VBN B-NP O
. . O O
daughter NN B-NP O
states VBZ B-VP O
that IN B-SBAR O
he PRP B-NP O
saw VBD B-VP O
an DT B-NP O
eye NN I-NP O
doctor NN I-NP O
in IN B-PP O
Anchorage NNP B-NP B-CITY
Northeast NNP I-NP I-CITY
in IN B-PP O
11/77 CD B-NP B-DATE
, , O O
had VBD B-VP O
his PRP$ B-NP O
pupils NNS I-NP O
dilated VBD B-VP O
, , O O
was VBD B-VP O
checked VBN I-VP O
for IN B-PP O
DM NNP B-NP O
, , O O
was VBD B-VP O
told VBN I-VP O
everything NN B-NP O
was VBD B-VP O
fine JJ B-ADJP O
and CC O O
he PRP B-NP O
should MD B-VP O
return VB I-VP O
in IN B-PP O
1 CD B-NP O
year NN I-NP O
VS NNP B-NP O
as IN I-NP O
noted VBN O O
chest NN B-NP O
clear JJ I-NP O
to TO B-PP O
ausc JJ B-NP O
. . O O
RR NNP O O
12 CD O O
cardiac JJ B-NP O
normal JJ I-NP O
s1/s2 NN I-NP O
no DT B-NP O
m/s3/s4 NNS I-NP O
HR IN B-PP O
58 CD B-NP O
reg NN I-NP O
no DT B-NP O
peripheral JJ I-NP O
edema NN I-NP O
hgba1c JJ B-NP O
6.5 CD I-NP O
( -LRB- I-NP O
decreased VBN B-VP O
from IN B-PP O
8.9 CD B-NP O
in IN B-PP O
11/77 CD B-NP B-DATE
) -RRB- I-NP O
creatinine VBP B-VP O
stable JJ B-ADJP O
at IN B-PP O
1.4 CD B-NP O
Assessment NNP B-NP O
- : O O
improved VBD B-VP O
diabetic JJ B-NP O
control NN I-NP O
. . O O
renal JJ B-NP O
function NN I-NP O
stable JJ I-NP O
. . O O
suboptimal JJ O O
bp NN B-NP O
control NN I-NP O
for IN B-PP O
diabetic NN B-NP O
with IN B-PP O
history NN B-NP O
of IN B-PP O
CAD NN B-NP O
; : O O
already RB B-ADJP O
bradycardic JJ I-ADJP O
on IN B-PP O
atenolol NN B-NP O
50 CD I-NP O
mg NN I-NP O
qd NN I-NP O
Plan NNP B-NP O
- : O O
continue VBP B-VP O
current JJ B-NP O
regimen NNS I-NP O
with IN B-PP O
the DT B-NP O
exception NN I-NP O
of IN B-PP O
lisinopril NN B-NP O
- : O O
will MD B-VP O
increase VB I-VP O
to TO B-PP O
20mg CD B-NP O
qd NN I-NP O
. . O O
pt NN B-NP O
has VBZ B-VP O
PE NN B-NP O
scheduled VBN I-NP O
5/31/78 CD I-NP B-DATE
. . O O
bp IN B-PP O
recheck NN B-NP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
no DT B-NP O
ophthalmology NN I-NP O
referral NN I-NP O
was VBD B-VP O
made VBN I-VP O
as IN B-SBAR O
he PRP B-NP O
appears VBZ B-VP O
to TO I-VP O
be VB I-VP O
up IN B-PRT O
to TO B-PP O
date NN B-NP O
with IN B-PP O
eye NN B-NP O
care NN I-NP O
N. NNP B-NP B-DOCTOR
levine NN I-NP I-DOCTOR
, , O O
MD . O O
