Record NNP B-NP O
date NN I-NP O
: : O O
2098-02-22 CD O B-DATE
Kekela NNP B-NP B-HOSPITAL
Team NNP I-NP O
3 CD I-NP O
Intern NNP I-NP O
Admission NNP I-NP O
Name NN B-NP O
: : O O
Danny NNP B-NP B-PATIENT
Nielson NNP I-NP I-PATIENT
MR# NNP B-NP O
: : O O
9156593 CD O B-MEDICALRECORD
Admit NNP B-NP O
Date NNP I-NP O
: : O O
February NNP B-NP B-DATE
21 CD I-NP I-DATE
, , I-NP I-DATE
2098 CD O I-DATE
Onc IN B-PP O
Attending VBG B-VP O
: : O O
Dr. NNP B-NP O
Quadri NNP I-NP B-DOCTOR
Onc IN B-PP O
PA NNP B-NP O
: : O O
Edward NNP B-NP B-DOCTOR
Quiambao NNP I-NP I-DOCTOR
PCP NNP B-NP O
: : O O
Ulises NNP B-NP B-DOCTOR
Lopez NNP I-NP I-DOCTOR
Admitting NNP B-NP O
intern NN I-NP O
: : O O
Ulyssa NNP B-NP B-DOCTOR
Neff NNP I-NP I-DOCTOR
Code NNP B-NP O
: : O O
FULL . O O
Source NN B-NP O
: : O O
Patient NNP B-NP O
Chief NNP B-NP O
Complaint NNP I-NP O
: : O O
diarrhea NN B-NP O
History NN B-NP O
of IN B-PP O
Present NNP B-NP O
Illness NNP I-NP O
: : O O
77 CD B-NP B-AGE
-year-old JJ I-NP O
gentleman NN I-NP O
with IN B-PP O
Stage NNP B-NP O
IIIB NNP I-NP O
diffuse VBP B-VP O
large JJ B-NP O
B-cell JJ I-NP O
lymphoma NN I-NP O
s/p NN I-NP O
4 CD B-NP O
cycles NNS I-NP O
of IN B-PP O
CHOP-R JJ B-NP O
with IN B-PP O
increased VBN B-NP O
PET NN I-NP O
avidity NN I-NP O
of IN B-PP O
left JJ B-NP O
groin NN I-NP O
nodal NN I-NP O
mass NN I-NP O
and CC I-NP O
biopsy NN I-NP O
c/w NN I-NP O
DLBCL NNP I-NP O
then RB B-ADVP O
s/p VBD B-VP O
R-ICE NNP B-NP O
cycle NN I-NP O
# # I-NP O
2 CD I-NP O
. . O O
Now RB B-ADVP O
s/p RB B-NP O
40 CD I-NP O
gray JJ I-NP O
XRT NN I-NP O
to TO B-PP O
limited JJ B-NP O
recurrence NN I-NP O
site NN I-NP O
in IN B-PP O
left JJ B-NP O
groin NN I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
hospitalized VBN I-VP O
recently RB B-ADVP O
for IN B-PP O
neutropenia NN B-NP O
and CC I-NP O
fevers NNS I-NP O
, , O O
received VBD B-VP O
cefepime NN B-NP O
and CC I-NP O
vancomycin NN I-NP O
, , O O
and CC O O
was VBD B-VP O
discharged VBN I-VP O
on IN B-PP O
2/2/2098 CD B-NP B-DATE
. . O O
As IN B-PP O
per IN B-PP O
d/c NN B-NP O
summary NN I-NP O
, , O O
he PRP B-NP O
received VBD B-VP O
cefepime NN B-NP O
for IN B-PP O
E. NNP B-NP O
coli NNS I-NP O
and CC O O
VRE NNP B-NP O
UTI NNP I-NP O
( -LRB- O O
though IN B-SBAR O
this DT B-NP O
is VBZ B-VP O
a DT B-NP O
little JJ I-NP O
confusing JJ B-ADJP O
since IN B-PP O
urine JJ B-NP O
culture NN I-NP O
negative JJ I-NP O
that IN B-PP O
admission NN B-NP O
, , O O
and CC O O
positive JJ B-ADJP O
for IN B-PP O
these DT B-NP O
organisms NNS I-NP O
in IN B-PP O
11/2097 CD B-NP B-DATE
) -RRB- I-NP O
. . O O
During IN B-PP O
most RBS B-NP O
recent JJ I-NP O
admission NN I-NP O
he PRP B-NP O
was VBD B-VP O
found VBN I-VP O
to TO I-VP O
be VB I-VP O
C. NNP B-NP O
diff JJ I-NP O
positive JJ I-NP O
, , O O
but CC O O
appears VBZ B-VP O
to TO I-VP O
have VB I-VP O
had VBD I-VP O
incomplete JJ B-NP O
course NN I-NP O
of IN B-PP O
Flagyl NNP B-NP O
. . O O
Since IN B-PP O
discharge NN B-NP O
, , O O
patient JJ B-NP O
reports NNS I-NP O
not RB B-VP O
feeling VBG I-VP O
the DT B-NP O
same JJ I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
crampy JJ B-NP O
abdominal JJ I-NP O
pain NN I-NP O
, , O O
diarrhea NN B-NP O
, , O O
and CC O O
experienced VBD B-VP O
some DT B-NP O
lightheadedness NN I-NP O
this DT B-NP O
morning NN I-NP O
. . O O
ROS NNP B-NP O
: : O O
Denies NNS B-NP O
fevers NNS I-NP O
, , O O
sweats VBZ B-VP O
, , O O
chills NNS B-NP O
. . O O
Denies NNS B-VP O
HA NNP B-NP O
. . O O
Denies NNS B-NP O
CP CD B-NP O
, , O O
respiratory JJ B-NP O
sx NN I-NP O
, , O O
urinary JJ B-NP O
difficulty NN I-NP O
, , O O
N/V NNP B-NP O
. . O O
Past NNP B-NP O
Medical NNP I-NP O
History NNP I-NP O
: : O O
1 LS O O
. . O O
Wegener NNP B-NP O
's POS B-NP O
granulomatosis NN I-NP O
2. VBG B-VP O
bilateral JJ B-NP O
knee NN I-NP O
repair NN I-NP O
12 CD B-NP O
years NNS I-NP O
ago IN B-PP O
3. DT B-NP O
right-sided JJ I-NP O
hip NN I-NP O
repair NN I-NP O
4 CD B-LST O
. . O O
diabetes NN B-VP O
mellitus JJ B-NP O
type NN I-NP O
II NNP I-NP O
5 CD B-LST O
. . O O
hiatal NN B-NP O
hernia . O O
6 CD B-LST O
. . O O
coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
a DT B-NP O
. . I-NP O
Cath NNP I-NP O
from IN B-PP O
11/2097 CD B-NP B-DATE
: : O O
Severe NNP B-NP O
left VBD B-VP O
main JJ B-NP O
(60 CD I-NP O
% NN I-NP O
ostial JJ I-NP O
) -RRB- I-NP O
, , O O
mid JJ B-ADJP O
LAD NNP B-NP O
(60 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
, , O O
and CC O O
RCA NNP B-NP O
( -LRB- I-NP O
100 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
, , I-NP O
patent NN I-NP O
LIMA NNP I-NP O
7. DT B-NP O
renal JJ I-NP O
transplant NN I-NP O
donor NN I-NP O
in IN B-PP O
the DT B-NP O
2060s CD I-NP B-DATE
8. DT B-NP O
aortic JJ I-NP O
stenosis NN I-NP O
with IN B-PP O
(valve JJ B-NP O
area NN I-NP O
1 CD B-NP O
peak NN I-NP O
trans NNS I-NP O
AV DT B-NP O
gradient NN I-NP O
is VBZ B-VP O
37 CD B-NP O
mmHg NN I-NP O
) -RRB- O O
9 CD B-NP O
. . O O
CHF NNP O O
( -LRB- O O
EF NNP B-NP O
36 CD I-NP O
% NN I-NP O
) -RRB- O O
10 CD B-LST O
. . O O
atrial '' B-VP O
flutter NN B-NP O
s/p NN I-NP O
cardioversion NN I-NP O
11 CD B-LST O
. . O O
diffuse IN B-PP O
large JJ B-NP O
B-cell NN I-NP O
lymphoma NN I-NP O
ONC IN B-PP O
history NN B-NP O
- : O O
as IN B-PP O
per IN B-PP O
prior JJ B-NP O
notes NNS I-NP O
3/97 CD B-NP B-DATE
: : O O
Mr. NNP B-NP O
Nielson NNP I-NP B-PATIENT
was VBD B-VP O
in IN B-PP O
his PRP$ B-NP O
usual JJ I-NP O
state NN I-NP O
of IN B-PP O
health NN B-NP O
until IN B-SBAR O
he PRP B-NP O
presented VBD B-VP O
with IN B-PP O
LLE JJ B-NP O
edema NN I-NP O
and CC O O
bilateral JJ B-NP O
groin NN I-NP O
swelling VBG I-NP O
, , O O
left>right JJ B-ADJP O
. . O O
4/97 CD B-NP B-DATE
: : O O
CT NNP B-NP O
scan NN I-NP O
of IN B-PP O
the DT B-NP O
abdomen NN I-NP O
revealed VBD B-VP O
retroperitoneal JJ B-ADJP O
adenopathy RB B-ADVP O
. . O O
CT JJ B-NP O
scan NN I-NP O
of IN B-PP O
the DT B-NP O
pelvis NNS I-NP O
revealed VBD B-VP O
a DT B-NP O
chain NN I-NP O
of IN B-PP O
retrocrural JJ B-NP O
nodes NNS I-NP O
in IN B-PP O
front NN B-NP O
of IN B-PP O
the DT B-NP O
aorta NN I-NP O
and CC I-NP O
vena NN I-NP O
cava NN I-NP O
as RB B-ADVP O
well RB I-ADVP O
as IN B-PP O
bulky JJ B-NP O
adenopathy NN I-NP O
in IN B-PP O
the DT B-NP O
external JJ I-NP O
iliac NN I-NP O
chain NN I-NP O
with IN B-PP O
an DT B-NP O
iliac JJ I-NP O
mass NN I-NP O
measuring VBG B-VP O
3.0 CD B-NP O
to TO B-PP O
3.5 CD B-NP O
cm NN I-NP O
in IN B-PP O
diameter NN B-NP O
on IN B-PP O
the DT B-NP O
left JJ I-NP O
side NN I-NP O
. . O O
The DT B-NP O
largest JJS I-NP O
node NN I-NP O
in IN B-PP O
the DT B-NP O
inguinal JJ I-NP O
area NN I-NP O
measured VBD B-VP O
approximately RB B-NP O
6.0 CD I-NP O
cm NN I-NP O
. . O O
4/18/97 CD B-NP B-DATE
: : O O
biopsy NN B-NP O
of IN B-PP O
left JJ B-NP O
groin NN I-NP O
mass NN I-NP O
c/w NN I-NP O
DLBCL. NNP I-NP O
CD20+ NNP I-NP O
, , O O
CD NNP B-NP O
79a+ CD I-NP O
, , O O
Pax5+ NNP B-NP O
, , O O
CD30-, NNP B-NP O
CD15 NNP I-NP O
- : O O
4/97 CD B-NP B-DATE
: : O O
PET NN B-NP O
: : O O
Increased VBN B-VP O
FDG NNP B-NP O
uptake NN I-NP O
throughout IN B-PP O
the DT B-NP O
retroperitoneum NN I-NP O
, , O O
left VBD B-VP O
pelvis NNS B-NP O
and CC O O
proximal NN B-NP O
left VBD B-VP O
lower JJR B-NP O
extremity NN I-NP O
which WDT B-NP O
corresponds VBZ B-VP O
with IN B-PP O
extensive JJ B-NP O
lymphadenopathy NN I-NP O
. . O O
4/24/97 CD B-NP B-DATE
: : O O
Bone NNP B-NP O
Marrow NNP I-NP O
Biopsy NNP I-NP O
: : O O
without IN B-PP O
evidence NN B-NP O
of IN B-PP O
involvement NN B-NP O
5/01/97 CD B-NP B-DATE
Cycle NNP I-NP O
# # I-NP O
1 CD I-NP O
of IN B-PP O
CHOP-R NNP B-NP O
at IN B-PP O
75 CD B-NP O
% NN I-NP O
Adria NNP I-NP O
and CC I-NP O
Cytoxan NNP I-NP O
dose NN I-NP O
5/22/97 CD B-NP B-DATE
Cycle NNP I-NP O
# # I-NP O
2 CD I-NP O
of IN B-PP O
CHOP-R NNP B-NP O
at IN B-PP O
100 CD B-NP O
% NN I-NP O
Adria NNP I-NP O
and CC I-NP O
Cytoxan NNP I-NP O
dose NN I-NP O
- : O O
Neulasta NN B-NP O
6/5/97 CD B-NP B-DATE
: : O O
PET NN B-NP O
: : O O
Interval NNP B-NP O
enlargement NN I-NP O
of IN B-PP O
left JJ B-NP O
groin NN I-NP O
mass NN I-NP O
but CC O O
less JJR B-NP O
intense JJ I-NP O
FDG NNP I-NP O
uptake NN I-NP O
. . B-NP O
Enlargement NN I-NP O
in IN B-PP O
size NN B-NP O
may MD B-VP O
represent VB I-VP O
necrosis NN B-NP O
from IN B-PP O
treatment NN B-NP O
effect NN I-NP O
. . O O
Improvement NN B-NP O
in IN B-PP O
left JJ B-NP O
iliac JJ I-NP O
adenopathy NN I-NP O
and CC I-NP O
resolution NN I-NP O
of IN B-PP O
retroperitoneal JJ B-NP O
lymphadenopathy NN I-NP O
. . O O
Small JJ B-NP O
pancreatic JJ I-NP O
body NN I-NP O
cystic JJ I-NP O
lesion NN I-NP O
- : O O
may MD B-VP O
be VB I-VP O
IPMT. . O O
6/12/97 CD B-NP B-DATE
: : O O
Cycle NNP B-NP O
# # I-NP O
3 CD I-NP O
of IN B-PP O
CHOP-R NNP B-NP O
at IN B-PP O
100 CD B-NP O
% NN I-NP O
Adria NNP I-NP O
and CC I-NP O
Cytoxan NNP I-NP O
dose NN I-NP O
- : O O
Neulasta NN B-NP O
7/4/97 CD B-NP B-DATE
: : O O
Cycle NNP B-NP O
# # I-NP O
4 CD I-NP O
of IN B-PP O
CHOP-R JJ B-NP O
at IN B-PP O
100 CD B-NP O
% NN I-NP O
Adria NNP I-NP O
and CC I-NP O
75 CD I-NP O
% NN I-NP O
Cytoxan JJ I-NP O
dose NN I-NP O
- : O O
Neulasta NN B-NP O
7/6/97 CD B-NP B-DATE
: : O O
PET NNP B-NP O
: : O O
No DT B-NP O
signficant JJ I-NP O
change NN I-NP O
in IN B-PP O
left JJ B-NP O
external JJ I-NP O
iliac NN I-NP O
and CC O O
left VBD B-VP O
inguinal JJ B-NP O
hypermatabolic JJ I-NP O
lymphadenopathy NN I-NP O
, , O O
likely RB B-ADVP O
right RB I-ADVP O
greater JJR B-NP O
trochanteric NN I-NP O
bursitis NN I-NP O
7/97 CD B-NP B-DATE
: : O O
Re NNP B-NP O
biopsy NN I-NP O
left VBD B-VP O
groin NN B-NP O
: : O O
DIFFUSE NNP B-NP O
LARGE NNP I-NP O
B-CELL NNP I-NP O
LYMPHOMA. NNP I-NP O
AREAS NNP I-NP O
OF IN B-PP O
FIBROSIS NNPS B-NP O
AND CC I-NP O
CHRONIC NNP I-NP O
INFLAMMATION NN I-NP O
8/1/97 CD B-NP B-DATE
Cycle NNP I-NP O
# # I-NP O
1 CD I-NP O
of IN B-PP O
R-ICE NNP B-NP O
with IN B-PP O
dose-reduced JJ B-NP O
Ifos NNS I-NP O
and CC I-NP O
carboplatin NN I-NP O
because IN B-PP O
of IN I-PP O
nephrectomy NN B-NP O
. . O O
8/31/97 CD B-NP B-DATE
Cycle NNP I-NP O
# # I-NP O
2 CD I-NP O
of IN B-PP O
R-ICE NNP B-NP O
with IN B-PP O
dose-reduced JJ B-NP O
Ifos NNS I-NP O
and CC O O
carboplatin NN B-NP O
9/20/97 CD B-NP B-DATE
- : O O
11/8 CD B-NP I-DATE
/97 CD I-NP I-DATE
- : O O
40 CD B-NP O
gray JJ I-NP O
XRT NNP I-NP O
to TO B-PP O
left VBN B-NP O
groin NN I-NP O
1/23/98 CD B-NP B-DATE
- : O O
PET/CT NN B-VP O
with IN B-PP O
slight JJ B-NP O
local JJ I-NP O
progression NN I-NP O
of IN B-PP O
left JJ B-NP O
thigh NN I-NP O
lesion NN I-NP O
by IN B-PP O
CT NNP B-NP O
Allergies NNP B-NP O
: : O O
NKDA NNP O O
Medications NNS B-NP O
(upon NN I-NP O
admission NN I-NP O
) -RRB- O O
Micronase NNP B-NP O
10 CD I-NP O
mg NN I-NP O
po NN I-NP O
q NNP I-NP O
day NN I-NP O
Lipitor NNP B-NP O
10 CD I-NP O
mg NN I-NP O
po NN I-NP O
q NNP I-NP O
day NN I-NP O
Lasix NNP B-NP O
40 CD I-NP O
mg NN I-NP O
po NN I-NP O
q NNP I-NP O
day NN I-NP O
Multivitamin NN B-NP O
Prednisone NN B-NP O
5 CD I-NP O
mg NN I-NP O
po NN I-NP O
q NNP I-NP O
day NN I-NP O
ASA NNP B-NP O
325 CD I-NP O
mg/d . O O
Amiodarone NNP B-NP O
200 CD I-NP O
mg/d NN I-NP O
Carvedilol NNP B-NP O
3.125 CD I-NP O
mg NN I-NP O
BID . O O
Flomax NNP B-NP O
0.4 CD I-NP O
mg/d NN I-NP O
Warfarin NNP B-NP O
5 CD I-NP O
mg NN I-NP O
on IN B-PP O
odd JJ B-NP O
days NNS I-NP O
and CC O O
2.5 CD B-NP O
mg NN I-NP O
on IN B-PP O
even JJ B-NP O
days NNS I-NP O
Social NNP B-NP O
History NNP I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
lives VBZ B-VP O
at IN B-PP O
home NN B-NP O
in IN B-PP O
Port NNP B-NP B-CITY
Arthur NNP I-NP I-CITY
, , O O
Indiana NNP B-NP B-STATE
. . O O
His PRP$ B-NP O
wife NN I-NP O
is VBZ B-VP O
now RB B-ADVP O
at IN B-PP O
home NN B-NP O
with IN B-PP O
24 CD B-NP O
hour NN I-NP O
care NN I-NP O
because IN B-PP O
of IN I-PP O
heart NN B-NP O
disease NN I-NP O
. . O O
Formerly RB B-VP O
ran VBD I-VP O
Cisco NNP B-NP I-ORGANIZATION
's POS B-NP I-ORGANIZATION
Security NNP I-NP I-ORGANIZATION
Department NNP I-NP I-ORGANIZATION
in IN B-PP O
Crossville NNP B-NP B-CITY
. . O O
He PRP B-NP O
has VBZ B-VP O
four CD B-NP O
sons NNS I-NP O
and CC O O
two CD B-NP O
daughters NNS I-NP O
; : O O
one CD B-NP O
of IN B-PP O
son NN B-NP O
's POS B-NP O
currently RB B-VP O
running VBG I-VP O
security NN B-NP O
. . O O
He PRP B-NP O
lost VBD B-VP O
one CD B-NP O
son NN I-NP O
to TO B-PP O
ARF NNP B-NP O
and CC O O
it PRP B-NP O
was VBD B-VP O
to TO B-PP O
this DT B-NP O
son NN I-NP O
that IN B-SBAR O
he PRP B-NP O
donated VBD B-VP O
a DT B-NP O
kidney NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
grandchildren NNS B-NP O
, , O O
four CD B-NP O
boys NNS I-NP O
and CC O O
four CD B-NP O
girls NNS I-NP O
. . O O
Tobacco NNP B-NP O
: : O O
1ppd JJ B-NP O
from IN B-PP O
14-50 CD B-NP O
, , O O
quit VBD B-VP O
26 CD B-NP O
years NNS I-NP O
ago RB B-ADVP O
. . O O
Significant JJ O O
EtOH NNP B-NP O
in IN B-PP O
past JJ B-NP O
, , O O
none NN B-NP O
current JJ I-NP O
. . O O
Family NNP B-NP O
History NN I-NP O
: : O O
Father NNP B-NP O
: : O O
Died VBN B-VP O
of IN B-PP O
colon NN B-NP O
cancer NN I-NP O
at IN B-PP O
87 CD B-NP B-AGE
yo . O O
Mother NN B-NP O
: : O O
Died VBN B-VP O
of IN B-PP O
breast NN B-NP O
cancer NN I-NP O
at IN B-PP O
90 CD B-NP B-AGE
yo . O O
Exam NNP B-NP O
: : O O
Vitals NNS B-NP O
: : O O
BP NNP B-NP O
118/82 CD I-NP O
, , O O
HR NNP B-NP O
100 CD I-NP O
; : O O
RR NNP B-NP O
20 CD I-NP O
T NNP I-NP O
97.3 CD I-NP O
O2 IN I-NP O
sat VBD B-VP O
98 CD B-NP O
% NN I-NP O
on IN B-PP O
2L CD B-NP O
Gen NNP B-NP O
: : O O
Obese NNP B-NP O
, , O O
chronically RB B-NP O
ill-appearing JJ I-NP O
older JJR I-NP O
gentleman NN I-NP O
lying VBG B-VP O
in IN B-PP O
bed NN B-NP O
, , O O
easily RB B-ADVP O
arousable IN B-PP O
, , O O
good JJ B-NP O
sense NN I-NP O
of IN B-PP O
humor NN B-NP O
. . O O
HEENT NNP B-NP O
: : O O
PERRL NN B-NP O
, , O O
OP NNP B-NP O
without IN B-PP O
erythema NN B-NP O
, , O O
exudates VBZ B-VP O
; : O O
mucous JJ B-NP O
membranes NNS I-NP O
dry JJ B-ADJP O
; : O O
no DT B-NP O
scleral JJ I-NP O
icterus NN I-NP O
Pulm NNP B-NP O
: : O O
CTA NNP B-VP O
with IN B-PP O
good JJ B-NP O
air NN I-NP O
movement NN I-NP O
bilaterally RB B-ADVP O
, , O O
coarse JJ B-NP O
breath NN I-NP O
sounds VBZ B-VP O
at IN B-PP O
bases NNS B-NP O
, , O O
but CC O O
no DT B-NP O
appreciable JJ I-NP O
crackles NNS I-NP O
. . O O
Cor/Cardiac NNP B-NP O
: : O O
irreg/irreg NN B-NP O
, , O O
SEM NNP B-NP O
IV/V NNP I-NP O
I PRP B-NP O
murmur VBD B-VP O
heard VBN I-VP O
throughout IN B-PP O
precordium NN B-NP O
, , O O
neck NN B-NP O
veins NNS I-NP O
flat JJ O O
Abdomen NNP B-NP O
: : O O
S/ND NNP B-NP O
, , O O
+BS NNP B-NP O
throughout IN I-NP O
, , O O
very RB B-ADVP O
mild JJ B-NP O
tenderness NN I-NP O
to TO B-PP O
palpation NN B-NP O
, , I-NP O
negative JJ I-NP O
Murphy NNP I-NP O
's POS B-NP O
, , O O
no DT B-NP O
rebound NN I-NP O
; : O O
no DT B-NP O
HSM NNP I-NP O
, , I-NP O
palpable/pulsatile JJ I-NP O
masses NNS I-NP O
Extremity NN B-NP O
: : O O
1+ CD B-NP O
pitting NN I-NP O
edema NN I-NP O
bilaterally RB B-ADVP O
, , O O
distal JJ B-NP O
pulses NNS I-NP O
2+ VBP B-VP O
bilaterally RB O O
Neurological JJ B-NP O
: : O O
CN NNP B-NP O
II-XII NNP I-NP O
grossly RB I-NP O
intact JJ I-NP O
, , O O
though IN B-SBAR O
tongue NN B-NP O
c NNS I-NP O
mild JJ B-NP O
deviation NN I-NP O
to TO B-PP O
right NN B-NP O
; : O O
strength NN B-NP O
5/5 IN B-PP O
all DT B-NP O
major JJ I-NP O
muscle NN I-NP O
groups NNS I-NP O
; : O O
DTR NNP B-NP O
's POS B-NP O
2+ JJ I-NP O
bilat NN I-NP O
. . O O
UE/LE NNP B-NP O
, , O O
downgoing VBG B-VP O
toes NNS B-NP O
bilaterally RB B-ADVP O
. . O O
Laboratory NN B-NP O
Hematology NNP B-NP O
Hematology NNP B-NP O
Detail NNP I-NP O
for IN B-PP O
NIELSON NNP B-NP I-PATIENT
, , O I-PATIENT
DANNY NNP B-NP I-PATIENT
W NNP I-NP I-PATIENT
MAH NNP B-NP B-HOSPITAL
YC NNP I-NP O
LAB NNP I-NP O
21-Feb-2098 . O B-DATE
10:12 CD O O
Accession NNP B-NP O
# # I-NP O
5541E69701 CD O B-MEDICALRECORD
Test NNP B-NP O
Description NNP I-NP O
Result NNP I-NP O
Flags NNP I-NP O
Ref NNP I-NP O
. . I-NP O
Range NNP I-NP O
Units . O O
WBC NNP B-NP O
3.4 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
4.5-11.0) JJ I-NP O
th/cmm NN I-NP O
HCT NNP B-NP O
29.6 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
41.0-53.0) CD I-NP O
% NN I-NP O
HGB NNP B-NP O
9.7 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
13.5-17.5 CD I-NP O
) -RRB- I-NP O
gm/dl . O O
RBC NNP B-NP O
3.80 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
4.50-5.90 CD I-NP O
) -RRB- I-NP O
mil/cmm . O O
PLT NNP B-NP O
69 CD I-NP O
L NNP B-NP O
( -LRB- I-NP O
150-350 CD I-NP O
) -RRB- I-NP O
th/cumm . O O
MCV NNP B-NP O
78 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
80-100 CD B-PP O
) -RRB- B-NP O
fl NN I-NP O
MCH NNP B-NP O
25.5 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
26.0-34.0) JJ I-NP O
pg/rbc NN I-NP O
MCHC NNP B-NP O
32.7 CD I-NP O
( -LRB- O O
31.0-37.0) CD B-NP O
g/dl NN I-NP O
RDW NNP B-NP O
21.0 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
11.5-14.5 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
DIFFERENTIAL NNP B-NP O
REQUEST NNP I-NP O
RECEIVED NNP I-NP O
Diff JJ B-NP O
Method NNP I-NP O
Auto NN I-NP O
Poly NNP B-NP O
83 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
40-70 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Lymphs NNS B-NP O
14 CD B-NP O
L NNP I-NP O
( -LRB- I-NP O
22-44 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Monos NNP B-NP O
3 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
4-11 NN I-NP O
) -RRB- B-NP O
% NN I-NP O
EOS NNS B-NP O
0 CD B-NP O
(0-8 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Basos NNS B-NP O
0 CD B-NP O
(0-3 JJ I-NP O
) -RRB- I-NP O
% NN I-NP O
Absolute JJ B-NP O
Neuts NNP I-NP O
2.83 CD I-NP O
( -LRB- I-NP O
1.8-7.7 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Lymphs NNP I-NP O
0.48 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
1.0-4.8 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Monos NNP I-NP O
0.11 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
0.2-0.4 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
EOS NNP I-NP O
0.01 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
0.1-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Basos NNP I-NP O
0.00 CD I-NP O
( -LRB- I-NP O
0.0-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Aniso NNP B-NP O
2+ CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Hypo NNP B-NP O
2+ CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Macrocytes NNP B-NP O
None NN I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Microcytes NNP B-NP O
3+ CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
None NN I-NP O
) -RRB- O O
Confidential NNP B-NP O
Material NNP I-NP O
Please VB B-VP O
Handle VB I-VP O
Appropriately RB B-ADVP O
. . O O
Chemistry NN B-NP O
Chemistry NNP B-NP O
Detail NNP I-NP O
for IN B-PP O
NIELSON NNP B-NP I-PATIENT
, , O I-PATIENT
DANNY NNP B-NP I-PATIENT
W NNP I-NP I-PATIENT
MAH NNP B-NP B-HOSPITAL
YC NNP I-NP O
LAB NNP I-NP O
21-Feb-2098 . O B-DATE
10:12 CD O O
Accession NNP B-NP O
# # I-NP O
5541E69701 CD O B-MEDICALRECORD
Test NNP B-NP O
Description NNP I-NP O
Result NNP I-NP O
Flags NNP I-NP O
Ref NNP I-NP O
. . I-NP O
Range NNP I-NP O
Units . O O
Plasma NNP B-NP O
Sodium NNP I-NP O
135 CD I-NP O
( -LRB- I-NP O
135-145 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Plasma NNP B-NP O
Potassium NNP I-NP O
3.0 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
3.4-4.8 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Plasma NNP B-NP O
Chloride NNP I-NP O
99 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
100-108 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Plasma NNP B-NP O
Carbon NNP I-NP O
Dioxide NNP I-NP O
26.1 CD I-NP O
( -LRB- I-NP O
23.0-31.9 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Calcium NNP B-NP O
8.3 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
8.5-10.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Plasma NNP B-NP O
Urea NNP I-NP O
Nitrogen NNP I-NP O
27 CD I-NP O
H NNP B-NP O
(8-25 . O O
) -RRB- O O
mg/dl . O O
Plasma NNP B-NP O
Creatinine NNP I-NP O
1.6 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.6-1.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Plasma NNP B-NP O
Glucose NNP I-NP O
169 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
70-110 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Total JJ B-NP O
Protein NNP I-NP O
5.0 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
6.0-8.3 CD I-NP O
) -RRB- I-NP O
g/dl . O O
Albumin NNP B-NP O
2.4 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
3.3-5.0) JJ I-NP O
g/dl NN I-NP O
Globulin NNP B-NP O
2.6 CD I-NP O
( -LRB- I-NP O
2.6-4.1 CD I-NP O
) -RRB- I-NP O
g/dl . O O
Total JJ B-NP O
Bilirubin NNP I-NP O
0.6 CD I-NP O
( -LRB- O O
0.0-1.0) CD B-NP O
mg/dl NN I-NP O
Alkaline NNP B-NP O
Phosphatase NNP I-NP O
53 CD I-NP O
( -LRB- O O
45-115 CD B-NP O
) -RRB- I-NP O
U/L . O O
Transaminase-SGPT NN B-NP O
12 CD I-NP O
( -LRB- I-NP O
10-55 CD I-NP O
) -RRB- I-NP O
U/L . O O
Transaminase-SGOT NNP B-NP O
23 CD I-NP O
( -LRB- I-NP O
10-40 CD I-NP O
) -RRB- I-NP O
U/L . O O
Lactic NNP B-NP O
Dehydrogenase NNP I-NP O
266 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
110-210 CD I-NP O
) -RRB- I-NP O
U/L . O O
Confidential NNP B-NP O
Material NNP I-NP O
Please VB B-VP O
Handle VB I-VP O
Appropriately RB B-ADVP O
. . O O
EKG NNP B-NP O
NSR NNP I-NP O
at IN B-PP O
90 CD B-NP O
, , O O
left JJ B-NP O
axis NN I-NP O
, , O O
1st JJ B-NP O
degree NN I-NP O
AVB. NNP I-NP O
RBBB NNP I-NP O
pattern NN I-NP O
, , O O
unchanged JJ B-ADJP O
from IN B-PP O
prior RB B-NP O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
: : O O
77 CD B-NP B-AGE
-year-old JJ I-NP O
gentleman NN I-NP O
with IN B-PP O
Stage NNP B-NP O
IIIB NNP I-NP O
diffuse VBP B-VP O
large JJ B-NP O
B-cell JJ I-NP O
lymphoma NN I-NP O
s/p NN I-NP O
4 CD B-NP O
cycles NNS I-NP O
of IN B-PP O
CHOP-R NNP B-NP O
, , O O
s/p NN B-NP O
2 CD I-NP O
cycles NNS I-NP O
R-ICE NNP I-NP O
, , O O
s/p NN B-NP O
XRT NNP I-NP O
and CC I-NP O
refractory JJ I-NP O
disease NN I-NP O
in IN B-PP O
L NNP B-NP O
groin NN I-NP O
, , O O
presents NNS B-NP O
with IN B-PP O
several JJ B-NP O
weeks NNS I-NP O
of IN B-PP O
diarrhea NN B-NP O
and CC O O
crampy JJ B-NP O
abdominal JJ I-NP O
pain NN I-NP O
and CC O O
recent JJ B-NP O
evidence NN I-NP O
of IN B-PP O
C. NNP B-NP O
difficile JJ I-NP O
positivity NN I-NP O
, , O O
and CC O O
possible JJ B-NP O
incomplete JJ I-NP O
duration NN I-NP O
of IN B-PP O
therapy NN B-NP O
. . O O
1 LS O O
. . B-NP O
Diarrhea NNP I-NP O
, , O O
crampy JJ B-NP O
abdominal JJ I-NP O
pain NN I-NP O
. . O O
a DT B-NP O
. . I-NP O
Check NNP I-NP O
C. NNP I-NP O
diff NN I-NP O
, , O O
stool NN B-NP O
cultures NNS I-NP O
b NN B-NP O
. . B-NP O
IVF NN I-NP O
, , O O
follow VBP B-VP O
O2 IN B-PP O
sats NNS B-NP O
given VBN B-VP O
low JJ B-NP O
EF NN I-NP O
c. NN B-NP O
Follow NNP I-NP O
abdominal NN I-NP O
exam NN I-NP O
d VBN B-VP O
. . B-NP O
Treat NNP I-NP O
with IN B-PP O
flagyl NN B-NP O
500mg CD I-NP O
PO NNP I-NP O
q8h . O O
2. DT B-NP O
Acute NNP I-NP O
on IN B-PP O
chronic JJ B-NP O
RF NN I-NP O
: : O O
( -LRB- O O
Cr NNP B-NP O
to TO B-PP O
1.6 CD B-NP O
from IN B-PP O
1.5 CD B-NP O
and CC I-NP O
slightly RB I-NP O
elevated JJ I-NP O
BUN) NNP I-NP O
, , O O
likely JJ B-NP O
2/2 CD I-NP O
dehydration NN I-NP O
, , O O
recent JJ B-NP O
renal JJ I-NP O
U/S NNP I-NP O
normal JJ I-NP O
. . O O
a DT B-NP O
. . O O
Will MD B-VP O
follow VB I-VP O
Cr NNP B-NP O
closely RB B-ADVP O
, , O O
hope NN B-NP O
for IN B-PP O
improvement NN B-NP O
post-hydration NN I-NP O
3. . B-NP O
DLBCL NNP I-NP O
a DT B-NP O
. . I-NP O
Pancytopenic NNP I-NP O
. . O O
Cont NNP O O
to TO B-VP O
monitor VB I-VP O
, , O O
will MD B-VP O
reconsider VB I-VP O
restarting VBG I-VP O
Neupogen NN B-NP O
depending VBG I-NP O
on IN B-PP O
trend NN B-NP O
. . O O
b NN B-NP O
. . O O
Groin NNP B-NP O
mass NN I-NP O
, , O O
long-term JJ B-NP O
plan NN I-NP O
for IN B-PP O
resection NN B-NP O
; : O O
eval NN B-NP O
scheduled VBN B-VP O
for IN B-PP O
2/26 CD B-NP B-DATE
. . O O
4 CD B-LST O
. . O O
DM '' O O
a DT B-NP O
. . I-NP O
Continue NNP I-NP O
outpatient NNP I-NP O
regimen NNS I-NP O
of IN B-PP O
micronase NN B-NP O
10mg CD B-NP O
qd NN I-NP O
; : O O
monitor NN B-NP O
FS NNS I-NP O
and CC O O
cover NN B-NP O
with IN B-PP O
RISS NNP B-NP O
prn NN I-NP O
5 CD B-NP O
. . O O
Cardiac NNP O O
a DT B-NP O
. . I-NP O
Pump NNP I-NP O
: : O O
EF NNP B-NP O
36 CD B-NP O
% NN I-NP O
i NN B-NP O
. . O O
Carvedilol NN O O
ii NNS B-NP O
. . B-VP O
Hold VB I-VP O
lasix NN B-NP O
for IN B-PP O
now RB B-NP O
, , O O
given VBN B-NP O
dehydration NN I-NP O
b NN B-NP O
. . B-NP O
Rhythm NN I-NP O
: : O O
afib NN B-NP O
i FW O O
. . B-NP O
Continue NNP I-NP O
amiodarone NN I-NP O
, , O O
carvedilol NN B-NP O
, , O O
coumadin NN B-NP O
c. NN B-NP O
Ischemia NNP I-NP O
: : O O
known VBN B-NP O
CAD NN I-NP O
i NN B-NP O
. . B-VP O
continue VB I-VP O
ASA NNP B-NP O
, , I-NP O
lipitor NN I-NP O
, , O O
carvedilol NN B-NP O
6 CD B-NP O
. . O O
Wegener NNP B-NP O
's POS B-LST O
a DT B-NP O
. . I-NP O
Continue NNP I-NP O
prednisone NN I-NP O
5mg IN B-PP O
PO NNP B-NP O
qd CC O O
7. . B-NP O
Prophylaxis NNP I-NP O
a DT B-NP O
. . B-VP O
On IN B-PP O
coumadin NN B-NP O
, , O O
encourage VBP B-VP O
OOB NNP B-NP O
, , O O
nexium JJ B-ADJP O
. . O O
8. JJS B-NP O
Code NNP I-NP O
status NN I-NP O
: : O O
Full VB O O
Ulyssa NNP B-NP B-DOCTOR
Neff NNP I-NP I-DOCTOR
, , O O
MD . O O
Team NN B-NP O
3 CD I-NP O
intern NN I-NP O
# # B-NP O
50260 CD I-NP B-PHONE
