Record NNP B-NP O
date NN I-NP O
: : O O
2070-01-20 CD O B-DATE
Sheboygan NNP B-NP B-HOSPITAL
Memorial NNP I-NP I-HOSPITAL
Medical NNP I-NP I-HOSPITAL
Center NNP I-NP I-HOSPITAL
69 CD B-NP B-STREET
Aston NNP I-NP I-STREET
Street NNP I-NP I-STREET
SCHWARTZ NNP I-NP I-PATIENT
, , O I-PATIENT
XAVIER NNP B-NP I-PATIENT
Helena NNP B-NP B-CITY
, , O O
MD NNP B-NP B-STATE
97756 CD I-NP B-ZIP
49921666 CD O B-MEDICALRECORD
(871 CD B-NP I-PHONE
) -RRB- I-NP I-PHONE
720-9439 CD I-NP I-PHONE
01/20/70 CD O B-DATE
HISTORY NN B-NP O
OF IN B-PP O
PRESENT JJ B-NP O
ILLNESS NNS I-NP O
: : O O
This DT B-NP O
is VBZ B-VP O
an DT B-NP O
elderly JJ I-NP O
patient NN I-NP O
, , O O
82 CD B-NP B-AGE
, , O O
with IN B-PP O
known VBN B-NP O
diabetes NNS I-NP O
and CC O O
coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
, , O O
which WDT B-NP O
has VBZ B-VP O
required VBN I-VP O
placement NN B-NP O
of IN B-PP O
a DT B-NP O
pacemaker NN I-NP O
. . O O
I PRP B-NP O
last RB B-ADVP O
saw VBD B-VP O
his PRP$ B-NP O
blood NN I-NP O
sugar NN I-NP O
and CC O O
it PRP B-NP O
was VBD B-VP O
276 CD B-NP O
and CC O O
his PRP$ B-NP O
A1c NNP I-NP O
in IN B-PP O
October NNP B-NP B-DATE
was VBD B-VP O
7. CD B-NP O
So RB B-ADVP O
, , O O
I PRP B-NP O
had VBD B-VP O
him PRP B-NP O
back RB B-ADVP O
today RB B-ADVP O
to TO B-VP O
discuss VB I-VP O
diabetic JJ B-NP O
management NN I-NP O
and CC O O
also RB B-ADVP O
review VB B-VP O
his PRP$ B-NP O
general JJ I-NP O
health NN I-NP O
in IN B-PP O
terms NNS B-NP O
of IN B-PP O
his PRP$ B-NP O
diabetes NN I-NP O
and CC O O
his PRP$ B-NP O
other JJ I-NP O
medications NNS I-NP O
. . O O
We PRP B-NP O
went VBD B-VP O
over IN B-PP O
his PRP$ B-NP O
medications NNS I-NP O
to TO B-VP O
start VB I-VP O
with IN B-ADVP O
and CC O O
he PRP B-NP O
is VBZ B-VP O
taking VBG I-VP O
them PRP B-NP O
exactly RB B-ADVP O
as IN B-SBAR O
it PRP B-NP O
was VBD B-VP O
shown VBN I-VP O
in IN B-PP O
the DT B-NP O
computer NN I-NP O
. . O O
These DT O O
include VBP B-VP O
atenolol DT B-NP O
25 CD I-NP O
, , O O
Glucotrol NNP B-NP O
10 CD I-NP O
twice RB I-NP O
a DT B-NP O
day NN I-NP O
, , O O
Actos NNP B-NP O
45 CD I-NP O
, , O O
Lipitor NNP B-NP O
40 CD I-NP O
a DT B-NP O
day NN I-NP O
, , O O
Lasix NNP B-NP O
40 CD I-NP O
a DT B-NP O
day NN I-NP O
, , O O
and CC O O
Procardia NNP B-NP O
XL NNP I-NP O
60 CD I-NP O
mg NN I-NP O
q.d. NN I-NP O
, , O O
and CC O O
Coumadin NNP B-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
followed VBN I-VP O
by IN B-PP O
Dr. NNP B-NP O
Itzel NNP I-NP B-DOCTOR
Jaimes NNP I-NP I-DOCTOR
for IN B-PP O
his PRP$ B-NP O
cardiac NN I-NP O
problems NNS I-NP O
and CC O O
by IN B-PP O
a DT B-NP O
diabetologist NN I-NP O
at IN B-PP O
the DT B-NP O
Claiborne NNP I-NP B-HOSPITAL
for IN B-PP O
managing VBG B-VP O
his PRP$ B-NP O
diabetes NN I-NP O
. . O O
He PRP B-NP O
had VBD B-VP O
no DT B-NP O
other JJ I-NP O
complaints NNS I-NP O
. . O O
His PRP$ B-NP O
bowel NN I-NP O
movements NNS I-NP O
are VBP B-VP O
regular JJ B-ADJP O
. . O O
He PRP B-NP O
still RB B-ADVP O
has VBZ B-VP O
nocturia DT B-NP O
x3 NN I-NP O
and CC O O
was VBD B-VP O
recently RB I-VP O
seen VBN I-VP O
by IN B-PP O
a DT B-NP O
urologist NN I-NP O
who WP B-NP O
felt VBD B-VP O
there EX B-NP O
was VBD B-VP O
no DT B-NP O
need NN I-NP O
for IN B-SBAR O
any DT B-NP O
intervention NN I-NP O
. . O O
He PRP B-NP O
otherwise RB B-ADVP O
was VBD B-VP O
in IN B-PP O
good JJ B-NP O
spirits NNS I-NP O
and CC O O
has VBZ B-VP O
no DT B-NP O
immediate JJ I-NP O
complaints NNS I-NP O
. . O O
His PRP$ B-NP O
social JJ I-NP O
situation NN I-NP O
, , O O
his PRP$ B-NP O
allergies NNS I-NP O
and CC O O
and CC O O
his PRP$ B-NP O
family NN I-NP O
history NN I-NP O
and CC O O
past JJ B-NP O
medical JJ I-NP O
history NN I-NP O
, , O O
are VBP B-VP O
overall JJ B-ADJP O
as IN B-SBAR O
previously RB B-ADVP O
recorded VBN B-VP O
. . O O
There EX B-NP O
are VBP B-VP O
no DT B-NP O
other JJ I-NP O
pertinent JJ I-NP O
findings NNS I-NP O
in IN B-PP O
the DT B-NP O
review NN I-NP O
of IN B-PP O
systems NNS B-NP O
. . O O
PHYSICAL NNP B-NP O
EXAMINATION NNP I-NP O
: : O O
His PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
was VBD B-VP O
140/60 CD B-NP O
. . O O
He PRP B-NP O
looks VBZ B-VP O
well RB B-ADVP O
. . O O
I PRP B-NP O
did VBD B-VP O
not RB I-VP O
measure VB I-VP O
his PRP$ B-NP O
weight NN I-NP O
. . O O
His PRP$ B-NP O
heart NN I-NP O
rate NN I-NP O
was VBD B-VP O
around IN B-PP O
64-68 CD B-NP O
. . O O
His PRP$ B-NP O
pupils NNS I-NP O
are VBP B-VP O
equal JJ B-ADJP O
and CC O O
reactive NN B-NP O
to TO B-PP O
light NN B-NP O
and CC I-NP O
extraocular JJ I-NP O
movements NNS I-NP O
were VBD B-VP O
full JJ B-ADJP O
. . O O
Mucous JJ B-NP O
membranes NNS I-NP O
of IN B-PP O
the DT B-NP O
mouth NN I-NP O
and CC I-NP O
tongue NN I-NP O
were VBD B-VP O
normal JJ B-ADJP O
. . O O
Lungs NNP B-NP O
were VBD B-VP O
clear JJ B-ADJP O
to TO B-PP O
percussion NN B-NP O
and CC I-NP O
auscultation NN I-NP O
. . O O
Cardiac NNP B-NP O
exam NN I-NP O
showed VBD B-VP O
regular JJ B-ADJP O
sinus IN B-PP O
rhythm NN B-NP O
, , O O
a DT B-NP O
normal JJ I-NP O
S2 NN I-NP O
and CC O O
no DT B-NP O
significant JJ I-NP O
murmurs NNS I-NP O
. . O O
Liver NN B-NP O
and CC I-NP O
spleen NN I-NP O
were VBD B-VP O
not RB O O
palpable JJ B-ADJP O
. . O O
He PRP B-NP O
had VBD B-VP O
only RB B-NP O
1+ CD I-NP O
peripheral JJ I-NP O
edema NN I-NP O
which WDT B-NP O
is VBZ B-VP O
less JJR B-ADJP O
than IN B-PP O
usual JJ B-ADJP O
. . O O
ASSESSMENT NNP B-NP O
AND CC I-NP O
PLAN NNP I-NP O
: : O O
He PRP B-NP O
seems VBZ B-VP O
stable JJ B-ADJP O
, , O O
I PRP B-NP O
think VBP B-VP O
the DT B-NP O
biggest JJS I-NP O
problem NN I-NP O
is VBZ B-VP O
regulation NN B-NP O
of IN B-PP O
diabetes NN B-NP O
and CC O O
I PRP B-NP O
have VBP B-VP O
asked VBN I-VP O
him PRP B-NP O
to TO B-VP O
get VB I-VP O
a DT B-NP O
hemoglobin NN I-NP O
A1c JJ I-NP O
and CC O O
to TO B-VP O
measure VB I-VP O
his PRP$ B-NP O
blood NN I-NP O
sugar NN I-NP O
when WRB B-ADVP O
he PRP B-NP O
gets VBZ B-VP O
up RP I-VP O
in IN B-PP O
the DT B-NP O
morning NN I-NP O
and CC B-PP O
in IN B-PP O
the DT B-NP O
afternoon NN I-NP O
before IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
supper NN B-NP O
. . O O
He PRP B-NP O
will MD B-VP O
come VB I-VP O
back RB B-ADVP O
to TO B-VP O
see VB I-VP O
me PRP B-NP O
in IN B-PP O
about IN B-NP O
a DT I-NP O
month NN I-NP O
's POS B-NP O
time NN I-NP O
to TO B-VP O
follow VB I-VP O
up RP B-PRT O
on IN B-PP O
these DT B-NP O
issues NNS I-NP O
. . O O
CAD NN B-NP O
is VBZ B-VP O
stable JJ B-ADJP O
with IN B-PP O
pacemaker NN B-NP O
HGB NNP B-NP O
A1c NNP I-NP O
is VBZ B-VP O
7.0, CD B-NP O
Hct NN I-NP O
is VBZ B-VP O
down RB B-ADVP O
to TO B-PP O
31.6 CD B-NP O
, , O O
epo NN B-NP O
37 CD I-NP O
, , O O
creatinine VBP B-VP O
stable JJ B-ADJP O
at IN B-PP O
1.6 CD B-NP O
, , O O
MCV NNP B-NP O
93.3 CD I-NP O
. . B-NP O
Most RBS I-NP O
likely JJ I-NP O
anemia NN I-NP O
of IN B-PP O
chronic JJ B-NP O
illness NN I-NP O
but CC I-NP O
need NN I-NP O
to TO B-VP O
check VB I-VP O
smear NN B-NP O
and CC I-NP O
stools NNS I-NP O
Xenia NNP B-NP B-DOCTOR
Bridges NNP I-NP I-DOCTOR
, , O O
MD . O O
Plan NNP B-NP O
send VB B-VP O
stool NN B-NP O
cards NNS I-NP O
, , O O
check VB B-VP O
iron NN B-NP O
if IN B-PP O
not RB B-NP O
done VBN I-NP O
recently RB B-ADVP O
, , O O
reviedw JJ B-NP O
smear NN I-NP O
. . O O
Dictated NNP B-NP O
By IN I-NP O
: : O O
Xenia NNP B-NP B-DOCTOR
Bridges NNPS I-NP I-DOCTOR
eScription NN B-NP O
document NN I-NP O
: : O O
6-0750267 CD B-NP B-IDNUM
EMSSten NNP I-NP O
Tel NNP I-NP O
DD NNP B-NP O
: : O O
01/20/70 CD O B-DATE
DT NNP B-NP O
: : O O
01/20/70 CD O B-DATE
DV NNP B-NP O
: : O O
01/20/70 CD O B-DATE
