Record NNP B-NP O
date NN I-NP O
: : O O
2093-06-30 CD O B-DATE
NAME NNP B-NP O
: : O O
Oliver NNP B-NP I-PATIENT
, , O I-PATIENT
Uriah NNP B-NP I-PATIENT
MRN NNP B-NP O
: : O O
7916007 CD O B-MEDICALRECORD
Primary JJ B-NP O
Care NNP I-NP O
Provider NNP I-NP O
: : O O
Dr. NNP B-NP O
Patterson NNP I-NP B-DOCTOR
Mr. NNP B-NP O
Oliver NNP I-NP B-PATIENT
returns VBZ B-VP O
for IN B-PP O
follow-up JJ B-NP O
of IN B-PP O
several JJ B-NP O
issues NNS I-NP O
. . O O
Weight NNP B-NP O
175 CD I-NP O
. . O O
Blood NNP B-NP O
pressure NN I-NP O
130/80 CD I-NP O
. . O O
MEDICATIONS NNS B-NP O
: : O O
He PRP B-NP O
finished VBD B-VP O
Flagyl NNP B-NP O
last JJ B-NP O
night NN I-NP O
, , O O
and CC O O
he PRP B-NP O
took VBD B-VP O
his PRP$ B-NP O
last JJ I-NP O
dose NN I-NP O
of IN B-PP O
levoflox NN B-NP O
today NN B-NP O
. . O O
Glyburide NNP B-NP O
is VBZ B-VP O
on IN B-PP O
hold NN B-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
taking VBG I-VP O
hydrochlorothiazide JJ B-NP O
25 CD I-NP O
mg NN I-NP O
q.d. VBN B-VP O
, , O O
Lovastatin NNP B-NP O
20 CD B-NP O
mg JJ I-NP O
q.d. NN I-NP O
, , O O
fosinopril JJ B-NP O
40 CD I-NP O
mg NN I-NP O
q.d. VBN B-VP O
, , O O
verapamil JJ B-ADJP O
SR NNP B-NP O
240 CD I-NP O
mg NN I-NP O
q.d. VBN B-VP O
, , O O
ASA NNP B-NP O
1 CD I-NP O
q.d. NNP I-NP O
, , O O
metoprolol NN B-NP O
75 CD B-NP O
mg NN I-NP O
three CD B-NP O
times NNS I-NP O
a DT B-NP O
day NN I-NP O
and CC O O
Glucophage NNP B-NP O
1000 CD I-NP O
mg NN I-NP O
b.i.d NN I-NP O
. . O O
( -LRB- B-NP O
1 CD I-NP O
) -RRB- I-NP O
Diverticulitis NN I-NP O
and CC I-NP O
history NN I-NP O
of IN B-PP O
colon NN B-NP O
cancer NN I-NP O
. . O O
S NNP B-NP O
: : O O
His PRP$ B-NP O
pain NN I-NP O
is VBZ B-VP O
gone VBN I-VP O
although IN B-SBAR O
he PRP B-NP O
continues VBZ B-VP O
to TO I-VP O
have VB I-VP O
a DT B-NP O
bad JJ I-NP O
taste NN I-NP O
in IN B-PP O
his PRP$ B-NP O
mouth NN I-NP O
since IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
on IN B-PP O
antibiotics NNS B-NP O
. . O O
O UH B-ADVP O
: : O O
His PRP$ B-NP O
abdomen NN I-NP O
is VBZ B-VP O
soft JJ B-ADJP O
with IN B-PP O
normal JJ B-NP O
bowel NN I-NP O
sounds NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
tenderness NN I-NP O
today NN B-NP O
. . O O
P NNP B-NP O
: : O O
He PRP B-NP O
will MD B-VP O
need VB I-VP O
colonoscopy NN B-NP O
at IN B-PP O
the DT B-NP O
Atlantic NNP I-NP B-HOSPITAL
North NNP I-NP I-HOSPITAL
in IN B-PP O
a DT B-NP O
month NN I-NP O
or CC I-NP O
so RB I-NP O
. . O O
( -LRB- B-NP O
2 CD I-NP O
) -RRB- I-NP O
Diarrhea NNP I-NP O
. . O O
S NNP B-NP O
: : O O
He PRP B-NP O
has VBZ B-VP O
continued VBN I-VP O
to TO I-VP O
have VB I-VP O
several JJ B-NP O
soft JJ I-NP O
, , I-NP O
dark JJ I-NP O
bowel NN I-NP O
movements NNS I-NP O
a DT B-NP O
day NN I-NP O
while IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
taking VBG I-VP O
the DT B-NP O
antibiotic JJ I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
not RB I-VP O
seen VBN I-VP O
any DT B-NP O
bright JJ I-NP O
red NN I-NP O
blood NN B-NP O
per IN B-PP O
rectum NN B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
using VBG I-VP O
Equal NNP B-NP O
and CC O O
eating VBG B-VP O
ice NN B-NP O
cream NN I-NP O
. . O O
O UH B-ADVP O
: : O O
Stool NNP B-NP O
for IN B-PP O
C. NNP B-NP O
diff NN I-NP O
. . O O
and CC O O
stool NN B-NP O
C&S NNS I-NP O
were VBD B-VP O
both DT B-NP O
negative JJ I-NP O
. . O O
P NNP B-NP O
: : O O
I PRP B-NP O
asked VBD B-VP O
him PRP B-NP O
to TO B-VP O
discontinue VB I-VP O
artificial JJ B-NP O
sweeteners NNS I-NP O
and CC I-NP O
milk NN I-NP O
products NNS I-NP O
, , O O
except IN B-PP O
for IN B-PP O
yogurt NN B-NP O
, , O O
for IN B-PP O
3 CD B-NP O
days NNS I-NP O
. . O O
He PRP B-NP O
will MD B-VP O
call VB I-VP O
if IN B-PP O
the DT B-NP O
diarrhea NN I-NP O
persists NNS I-NP O
off IN B-PP O
the DT O O
antibiotic JJ B-ADJP O
. . O O
( -LRB- B-NP O
3 CD I-NP O
) -RRB- I-NP O
Guaiac-positive JJ I-NP O
stool NN I-NP O
on IN B-PP O
examination NN B-NP O
last JJ B-NP O
week NN I-NP O
. . O O
O UH B-ADVP O
: : O O
His PRP$ B-NP O
hematocrit NN I-NP O
had VBD B-VP O
increased VBN I-VP O
to TO B-PP O
35.7 CD B-NP O
last JJ I-NP O
week NN I-NP O
. . O O
P NNP B-NP O
: : O O
Recheck VB B-VP O
CBC JJ B-ADJP O
. . O O
He PRP B-NP O
will MD B-VP O
bring VB I-VP O
me PRP B-NP O
the DT B-NP O
name NN I-NP O
of IN B-PP O
his PRP$ B-NP O
GI JJ I-NP O
physician NN I-NP O
at IN B-PP O
the DT O O
Atlantic NNP B-NP B-HOSPITAL
North NNP I-NP I-HOSPITAL
so RB B-ADVP O
that IN B-SBAR O
I PRP B-NP O
can MD B-VP O
communicate VB I-VP O
with IN B-PP O
him PRP B-NP O
about IN B-PP O
the DT B-NP O
recent JJ I-NP O
events NNS I-NP O
and CC O O
arrange VB B-VP O
for IN B-PP O
follow-up JJ B-NP O
colonoscopy NN I-NP O
. . O O
( -LRB- B-NP O
4 CD I-NP O
) -RRB- I-NP O
Dizziness NN I-NP O
. . O O
S NNP B-NP O
: : O O
This DT B-NP O
has VBZ B-VP O
resolved VBN I-VP O
. . O O
( -LRB- B-NP O
5 CD I-NP O
) -RRB- I-NP O
Diabetes NNP I-NP O
. . O O
S NNP B-NP O
: : O O
He PRP B-NP O
stopped VBD B-VP O
glyburide RB B-ADVP O
as IN B-PP O
directed VBN B-NP O
last JJ I-NP O
week NN I-NP O
when WRB B-ADVP O
his PRP$ B-NP O
4 CD I-NP O
p.m. RB I-NP O
blood NN I-NP O
sugar NN I-NP O
was VBD B-VP O
44 CD B-NP O
. . B-PP O
His PRP$ B-NP O
fingerstick NN I-NP O
blood NN I-NP O
sugar NN I-NP O
was VBD B-VP O
192 CD B-NP O
this DT B-NP O
morning NN I-NP O
. . O O
He PRP B-NP O
reports NNS B-LST O
that IN B-SBAR O
he PRP B-NP O
is VBZ B-VP O
eating VBG I-VP O
much RB B-ADVP O
better JJR I-ADVP O
. . O O
P NNP B-NP O
: : O O
He PRP B-NP O
will MD B-VP O
restart VB I-VP O
glyburide NN B-NP O
5 CD I-NP O
mg NN I-NP O
q.d NN I-NP O
. . O O
when WRB B-ADVP O
his PRP$ B-NP O
blood NN I-NP O
sugar NN I-NP O
is VBZ B-VP O
greater JJR B-ADJP O
than IN B-SBAR O
200 CD B-LST O
. . O O
( -LRB- B-NP O
6 CD I-NP O
) -RRB- I-NP O
Systolic NNP I-NP O
murmur NN I-NP O
and CC I-NP O
right JJ I-NP O
bundle NN I-NP O
branch NN I-NP O
block NN I-NP O
. . O O
P NNP B-NP O
: : O O
His PRP$ B-NP O
echocardiogram NN I-NP O
has VBZ B-VP O
been VBN I-VP O
requested VBN I-VP O
but CC O O
he PRP B-NP O
has VBZ B-VP O
not RB I-VP O
yet RB I-VP O
received VBN I-VP O
the DT O O
appointment NN B-NP O
. . O O
( -LRB- B-NP O
7 CD I-NP O
) -RRB- I-NP O
Coronary NNPS I-NP O
artery NN I-NP O
disease NN I-NP O
. . O O
S NNP B-NP O
: : O O
He PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
no DT B-NP O
chest NN I-NP O
pain NN I-NP O
. . O O
He PRP B-NP O
apparently RB B-ADVP O
had VBD B-VP O
an DT B-NP O
appointment NN I-NP O
last JJ B-NP O
week NN I-NP O
for IN B-PP O
an DT B-NP O
exercise NN I-NP O
tolerance NN I-NP O
test NN I-NP O
at IN B-PP O
the DT B-NP O
Atlantic NNP I-NP B-HOSPITAL
North NNP I-NP I-HOSPITAL
but CC O O
the DT B-NP O
technician NN I-NP O
was VBD B-LST O
not RB O O
there EX B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
another DT B-NP O
appointment NN I-NP O
later RB B-NP O
this DT I-NP O
week NN I-NP O
with IN B-PP O
the DT B-NP O
doctor NN I-NP O
at IN B-PP O
the DT B-NP O
Atlantic NNP I-NP B-HOSPITAL
North NNP I-NP I-HOSPITAL
. . O O
P NNP B-NP O
: : O O
I PRP B-NP O
gave VBD B-VP O
him PRP B-NP O
a DT B-NP O
copy NN I-NP O
of IN B-PP O
the DT B-NP O
final JJ I-NP O
NYSH NNP I-NP B-HOSPITAL
discharge NN I-NP O
summary NN I-NP O
from IN B-PP O
his PRP$ B-NP O
recent JJ I-NP O
hospitalization NN B-NP O
as RB B-CONJP O
well RB I-CONJP O
as IN I-CONJP O
copies NNS B-NP O
of IN B-PP O
the DT B-NP O
EKGs NNP I-NP O
done VBN B-VP O
during IN B-PP O
the DT B-NP O
hospitalization NN B-NP O
and CC O O
a DT B-NP O
copy NN I-NP O
of IN B-PP O
the DT B-NP O
abdominal JJ I-NP O
CT NNP I-NP O
report NN I-NP O
to TO B-VP O
take VB I-VP O
to TO B-PP O
his PRP$ B-NP O
doctor NN B-NP O
at IN B-PP O
the DT B-NP O
Atlantic NNP I-NP B-HOSPITAL
North NNP I-NP I-HOSPITAL
. . O O
( -LRB- B-NP O
8 CD I-NP O
) -RRB- I-NP O
Proteinuria NNP I-NP O
during IN B-PP O
the DT B-NP O
hospitalization NN I-NP O
. . O O
O UH B-ADVP O
: : O O
His PRP$ B-NP O
serum NN I-NP O
creatinine NN I-NP O
was VBD B-VP O
1.5 CD B-NP O
( -LRB- I-NP O
likely JJ I-NP O
elevated VBD B-VP O
given VBN I-VP O
his PRP$ B-NP O
age NN I-NP O
) -RRB- I-NP O
. . O O
Repeat NN O O
urinalysis NN B-NP O
showed VBD B-VP O
1+ JJ B-NP O
albumin NN I-NP O
with IN B-PP O
no DT B-NP O
other JJ I-NP O
significant JJ I-NP O
abnormalities NNS I-NP O
. . O O
P NNP B-NP O
: : O O
Check VB B-VP O
24-hour JJ B-NP O
urine NN I-NP O
for IN B-PP O
protein NN B-NP O
and CC I-NP O
creatinine NN I-NP O
. . O O
Check VB B-VP O
serum JJ B-NP O
protein NN I-NP O
electrophoresis NN B-NP O
and CC I-NP O
urine NN I-NP O
immunoelectrophoresis NN I-NP O
. . O O
( -LRB- B-NP O
9 CD I-NP O
) -RRB- I-NP O
Chronic NNP I-NP O
anemia NN I-NP O
. . O O
O UH B-ADVP O
: : O O
He PRP B-NP O
had VBD B-VP O
normal JJ B-NP O
iron NN I-NP O
studies NNS I-NP O
, , O O
B12 NNP B-NP O
and CC O O
folate JJ B-NP O
several JJ I-NP O
months NNS I-NP O
ago RB B-ADVP O
. . O O
His PRP$ O O
hematocrit NN B-NP O
was VBD B-VP O
stable JJ B-ADJP O
as IN B-PP O
of IN B-PP O
last JJ B-NP O
week NN I-NP O
. . O O
P NNP B-NP O
: : O O
Check VB B-VP O
serum JJ B-NP O
protein NN I-NP O
electrophoresis NN I-NP O
and CC I-NP O
urine NN I-NP O
immunoelectrophoresis NN I-NP O
. . O O
( -LRB- B-NP O
10 CD I-NP O
) -RRB- I-NP O
Decreased . O O
HDL. . O O
A: JJ O O
We PRP B-NP O
could MD B-VP O
either RB I-VP O
add VB I-VP O
niacin JJ B-ADVP O
or CC O O
change VB B-VP O
his PRP$ B-NP O
statin NN I-NP O
from IN B-PP O
Mevacor NNP B-NP O
to TO B-PP O
Lipitor NNP B-NP O
to TO B-VP O
increase VB I-VP O
the DT B-NP O
HDL. NNP I-NP O
P NNP B-NP O
: : O O
I PRP B-NP O
have VBP B-VP O
deferred VBN I-VP O
this DT B-NP O
issue NN I-NP O
to TO B-PP O
his PRP$ B-NP O
primary JJ I-NP O
care NN I-NP O
physician NN I-NP O
. . O O
He PRP B-NP O
will MD B-VP O
return VB I-VP O
for IN B-PP O
follow-up JJ B-NP O
in IN B-PP O
2 CD B-NP O
weeks NNS I-NP O
so RB B-SBAR O
that IN I-SBAR O
we PRP B-NP O
can MD B-VP O
make VB I-VP O
final JJ B-NP O
arrangements NNS I-NP O
for IN B-PP O
the DT B-NP O
colonoscopy NN I-NP O
and CC O O
to TO B-VP O
check VB I-VP O
progress NN B-NP O
with IN B-PP O
his PRP$ B-NP O
diabetes NNS I-NP O
. . O O
Ciara NNP B-NP B-DOCTOR
J. NNP I-NP I-DOCTOR
Goldberg NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
CG JJ B-NP B-DOCTOR
/ JJ I-NP O
nation NN I-NP B-DOCTOR
/ NN I-NP O
olivo IN B-PP B-DOCTOR
