Record NNP B-NP O
date NN I-NP O
: : O O
2071-07-30 CD O B-DATE
EDUCARE-FARGO NNP B-NP B-HOSPITAL
Cardiovascular NNP I-NP O
Division NNP I-NP O
CVD NNP B-NP O
ER2 . O O
21 CD B-NP B-STREET
Aberdeen NNP I-NP I-STREET
Lane NNP I-NP I-STREET
JOSHI NNP I-NP I-PATIENT
, , O I-PATIENT
PETER NN B-NP I-PATIENT
Etowah NNP B-NP B-CITY
, , O O
CA NNP B-NP B-STATE
62884 CD I-NP B-ZIP
45339844 CD O B-MEDICALRECORD
( -LRB- B-NP I-PHONE
297 CD I-NP I-PHONE
) -RRB- I-NP I-PHONE
823-0872 CD I-NP I-PHONE
07/30/71 CD O B-DATE
Leon NNP B-NP B-DOCTOR
F NNP I-NP I-DOCTOR
Craft NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
135 CD B-NP B-STREET
Tamworth NNP I-NP I-STREET
Place NNP I-NP I-STREET
Garnett NNP B-NP B-CITY
, , O O
CA NNP B-NP B-STATE
47749 CD I-NP B-ZIP
Dear NNP B-NP O
Dr. NNP I-NP O
Craft NNP I-NP B-DOCTOR
, , O O
I PRP B-NP O
had VBD B-VP O
the DT B-NP O
pleasure NN I-NP O
of IN B-PP O
seeing VBG B-VP O
Peter NNP B-NP B-PATIENT
Joshi NNP I-NP I-PATIENT
in IN B-PP O
the DT B-NP O
Cardiovascular NNP I-NP O
Division NNP I-NP O
on IN B-PP O
Tuesday NNP B-NP B-DATE
. . O O
This DT B-NP O
lovely JJ I-NP O
gentleman NN I-NP O
with IN B-PP O
coronary JJ B-NP O
artery NN I-NP O
disease NN B-NP O
requiring VBG B-VP O
previous JJ B-NP O
stenting NN I-NP O
and CC O O
mild JJ B-NP O
systolic JJ I-NP O
dysfunction NN I-NP O
notes NNS B-NP O
that IN B-SBAR O
he PRP B-NP O
had VBD B-VP O
to TO I-VP O
participate VB I-VP O
in IN B-PP O
the DT B-NP O
resuscitation NN I-NP O
of IN B-PP O
his PRP$ B-NP O
son NN I-NP O
, , O O
who WP B-NP O
remains VBZ B-VP O
in IN B-PP O
the DT B-NP O
Beechwood NNP I-NP B-HOSPITAL
ICU NNP I-NP O
last JJ B-NP O
night NN I-NP O
. . O O
Despite IN B-ADVP O
this DT I-ADVP O
intense JJ B-NP O
stress NN I-NP O
, , O O
he PRP B-NP O
has VBZ B-VP O
no DT B-NP O
clear JJ I-NP O
dyspnea NN I-NP O
on IN B-PP O
exertion NN B-NP O
, , O O
palpitations NNS B-NP O
, , I-NP O
lightheadedness NN I-NP O
, , I-NP O
or CC I-NP O
chest NN I-NP O
discomfort NN I-NP O
at IN B-PP O
the DT B-NP O
present NN I-NP O
time NN B-NP O
. . O O
He PRP B-NP O
continues VBZ B-VP O
on IN B-PP O
aspirin NN B-NP O
, , O O
Lasix NNP B-NP O
60 CD I-NP O
mg NN I-NP O
a DT B-NP O
day NN I-NP O
, , O O
Isordil NNP B-NP O
40 CD I-NP O
mg NN I-NP O
p.o NN B-NP O
. . O O
t.i.d. '' O O
, , O O
Zestril NNP B-NP O
40 CD I-NP O
mg NN I-NP O
a DT B-NP O
day NN I-NP O
, , O O
Lopressor NNP B-NP O
100 CD I-NP O
mg NN I-NP O
b.i.d. VBN B-VP O
, , O O
simvastatin RB B-NP O
20 CD I-NP O
mg CD I-NP O
a DT B-NP O
day NN I-NP O
, , O O
Norvasc NNP B-NP O
5 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
b.i.d. '' O O
, , O O
Prevacid NNP B-NP O
, , O O
multivitamins NNS B-NP O
, , O O
and CC O O
K-Dur NNP B-NP O
in IN B-PP O
addition NN B-NP O
to TO B-PP O
his PRP$ B-NP O
insulin NN I-NP O
. . O O
On IN B-PP O
physical JJ B-NP O
exam NN I-NP O
today NN I-NP O
, , O O
his PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
is VBZ B-VP O
180/75 CD B-NP O
. . O O
His PRP$ B-NP O
heart NN I-NP O
rate NN B-NP O
is VBZ B-VP O
54 CD B-NP O
and CC I-NP O
regular JJ I-NP O
. . O O
Respiratory JJ B-NP O
rate NN I-NP O
is VBZ B-VP O
10 CD B-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no RB O O
increase NN B-NP O
in IN B-PP O
jugular JJ B-NP O
venous JJ I-NP O
pressure NN I-NP O
. . O O
Carotids NNPS B-NP O
are VBP B-VP O
without IN B-PP O
bruits NNS B-NP O
. . O O
Lungs NNS B-NP O
are VBP B-VP O
clear JJ B-ADJP O
to TO B-PP O
auscultation NN B-NP O
throughout IN I-NP O
. . O O
Cardiovascular NNP B-NP O
exam NN I-NP O
is VBZ B-VP O
notable JJ B-ADJP O
for IN B-PP O
lateral JJ B-NP O
PMI NNP I-NP O
, , O O
S4 NNP B-NP O
, , O O
S1 NNP B-NP O
, , O O
and CC O O
physiologically RB B-ADVP O
split VBD B-VP O
S2 NNP B-NP O
. . O O
His PRP$ B-NP O
abdomen NN I-NP O
is VBZ B-VP O
soft JJ B-ADJP O
and CC I-ADJP O
nontender JJ I-ADJP O
. . O O
He PRP O O
has VBZ B-VP O
no DT B-NP O
bruits NNS I-NP O
. . O O
His PRP$ B-NP O
extremities NNS I-NP O
are VBP B-VP O
warm JJ B-ADJP O
with IN B-PP O
strong JJ B-NP O
symmetric JJ I-NP O
pulses NNS B-NP O
and CC I-NP O
motor NN I-NP O
strength NN I-NP O
throughout IN B-PP O
. . B-NP O
He PRP B-NP O
has VBZ B-VP O
no DT B-NP O
peripheral JJ I-NP O
edema NN I-NP O
at IN B-PP O
the DT B-NP O
present JJ I-NP O
time NN I-NP O
. . O O
His PRP$ B-NP O
electrocardiogram NN I-NP O
is VBZ B-VP O
notable JJ B-ADJP O
for IN B-PP O
sinus NN B-NP O
bradycardia NN B-NP O
, , O O
evidence NN B-NP O
of IN B-PP O
prior JJ B-NP O
inferior JJ I-NP O
myocardial JJ I-NP O
infarction NN I-NP O
, , O O
and CC O O
lateral JJ B-NP O
downsloping NN I-NP O
S-T NNP I-NP O
, , O O
which WDT B-NP O
are VBP B-VP O
unchanged JJ B-ADJP O
from IN B-PP O
his PRP$ B-NP O
prior JJ I-NP O
electrocardiograms NNS B-NP O
. . O O
Mr. NNP B-NP O
Joshi NNP I-NP B-PATIENT
presents VBZ B-VP O
today NN B-NP O
with IN B-PP O
a DT B-NP O
euvolemic JJ I-NP O
volume NN I-NP O
status NN I-NP O
, , O O
but CC O O
a DT B-NP O
concerning VBG B-VP O
blood NN B-NP O
pressure NN I-NP O
. . O O
At IN B-PP O
this DT B-NP O
point NN I-NP O
, , O O
he PRP B-NP O
notes VBZ B-VP O
that IN B-SBAR O
he PRP B-NP O
is VBZ B-VP O
actually RB B-ADVP O
taking VBG B-VP O
his PRP$ B-NP O
Isordil NNP I-NP O
b.i.d. NN I-NP O
, , O O
and CC O O
I PRP B-NP O
will MD B-VP O
let VB I-VP O
him PRP B-NP O
continue VB O O
to TO B-VP O
do VB I-VP O
that DT B-NP O
. . O O
We PRP B-NP O
will MD B-VP O
increase VB I-VP O
his PRP$ B-NP O
Norvasc NNP I-NP O
to TO I-NP O
10 CD I-NP O
mg NN I-NP O
, , O O
and CC O O
he PRP B-NP O
will MD O O
be VB B-VP O
following VBG I-VP O
up RP B-PRT O
with IN B-PP O
you PRP B-NP O
within IN B-PP O
the DT B-NP O
next JJ I-NP O
few JJ I-NP O
weeks NNS I-NP O
. . O O
If IN B-SBAR O
there EX B-NP O
are VBP O O
any DT B-NP O
other JJ I-NP O
thoughts NNS I-NP O
in IN B-PP O
the DT B-NP O
care NN I-NP O
of IN B-PP O
this DT B-NP O
gentleman NN I-NP O
, , O O
please VB B-VP O
give VB I-VP O
me PRP B-NP O
a DT B-NP O
call NN I-NP O
. . O O
Sincerely RB B-ADVP O
, , O O
Dictated NNP B-NP O
By IN I-NP O
: : O O
Corrine NNP B-NP B-DOCTOR
James-Wagner NNP I-NP I-DOCTOR
Corrine NNP B-NP B-DOCTOR
James-Wagner NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
eScription NN B-NP O
document NN I-NP O
: : O O
0-5098538 CD B-NP B-IDNUM
TFFocus NN I-NP O
DD NNP B-NP O
: : O O
08/12/71 CD O B-DATE
DT NNP B-NP O
: : O O
08/12/71 CD O B-DATE
DV NNP B-NP O
: : O O
08/12/71 CD O B-DATE
******** NN B-NP O
Not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Physician JJ B-NP O
******** NNS I-NP O
