Record NNP B-NP O
date NN I-NP O
: : O O
2095-12-13 CD O B-DATE
TEAM NNP B-NP O
2 CD I-NP O
ACCEPT NNP I-NP O
NOTE NN I-NP O
Patient NNP B-NP O
's POS B-NP O
name NN I-NP O
: : O O
Frank NNP B-NP B-PATIENT
Keatering NNP I-NP I-PATIENT
MRN NNP B-NP O
: : O O
4832978 CD O B-MEDICALRECORD
Date NNP B-NP O
of IN B-PP O
Admission NNP B-NP O
to TO B-PP O
MICU NNP B-NP O
: : O O
12/11/95 CD O B-DATE
Date NNP B-NP O
of IN B-PP O
transfer NN B-NP O
to TO B-PP O
Internal NNP B-NP O
Medicine NNP I-NP O
: : O O
12/13/95 CD O B-DATE
ID/CC NNP B-NP O
: : O O
acute JJ B-NP O
loss NN I-NP O
of IN B-PP O
motor/sensation NN B-NP O
at IN B-PP O
level NN B-NP O
of IN B-PP O
T8 CD B-NP O
History NN B-NP O
Obtained VBD B-VP O
From IN B-PP O
: : O O
Pt NNP B-NP O
, , O O
old JJ B-NP O
charts NNS I-NP O
, , O O
transfer NN B-NP O
note NN I-NP O
. . O O
History NN B-NP O
of IN B-PP O
Present NNP B-NP O
Illness NNP I-NP O
: : O O
74 CD B-NP B-AGE
y/o CD I-NP O
man NN I-NP O
with IN B-PP O
h/o NN B-NP O
paraplegia NN I-NP O
2/2 CD I-NP O
compression NN I-NP O
fracture NN I-NP O
and CC I-NP O
wheelchair NN I-NP O
bound VBN B-VP O
, , O O
vascular JJ B-NP O
dz NN I-NP O
, , O O
with IN B-PP O
recent JJ B-NP O
bilateral JJ I-NP O
ileofemoral JJ I-NP O
and CC I-NP O
renal JJ I-NP O
artery NN I-NP O
stent NN I-NP O
( -LRB- I-NP O
11/24/95 CD I-NP B-DATE
) -RRB- I-NP O
and CC I-NP O
recent JJ I-NP O
cardiac NN I-NP O
cath NN I-NP O
stent NN I-NP O
to TO B-PP O
the DT B-NP O
circumflex NN I-NP O
( -LRB- I-NP O
11/28/95 CD I-NP B-DATE
) -RRB- I-NP O
. . O O
Pt NNP B-NP O
presented VBD B-VP O
to TO B-PP O
OSH NNP B-NP O
12/10 CD I-NP B-DATE
with IN B-PP O
c/o NN B-NP O
abdominal JJ I-NP O
pain NN I-NP O
onset IN B-PP O
the DT B-NP O
PM NNP I-NP O
prior RB B-ADVP O
to TO B-PP O
admission NN B-NP O
, , O O
diffuse NN B-NP O
in IN B-PP O
nature NN B-NP O
, , O O
localized VBN B-VP O
in IN B-PP O
the DT B-NP O
mid-epigastric JJ I-NP O
region NN I-NP O
, , O O
RUQ NNP B-NP O
, , O O
and CC O O
LUQ NNP B-NP O
with IN B-PP O
a DT B-NP O
pain NN I-NP O
scale NN I-NP O
of IN B-PP O
8-10/10 CD B-NP O
pain NN I-NP O
. . O O
Per IN B-PP O
charts NNS B-NP O
he PRP B-NP O
reported VBD B-VP O
decreased VBN B-NP O
pain NN I-NP O
in IN B-PP O
the DT B-NP O
am VBP B-VP O
with IN B-PP O
ability NN B-NP O
to TO B-VP O
tolerate VB I-VP O
PO NNP B-NP O
's POS B-NP O
and CC O O
then RB O O
increasing VBG B-VP O
pain NN B-NP O
that IN B-PP O
afternoon NN B-NP O
. . B-VP O
Also RB I-VP O
associated VBN I-VP O
with IN B-PP O
diaphoresis NN B-NP O
, , O O
+ NNP B-NP O
nausea NN I-NP O
, , O O
no DT B-NP O
vomiting NN I-NP O
, , O O
no DT B-NP O
sob NNS I-NP O
. . O O
During IN B-PP O
placement NN B-NP O
of IN B-PP O
a DT B-NP O
central JJ I-NP O
line NN I-NP O
at IN B-PP O
OSH NNP B-NP O
ED NNP I-NP O
, , O O
pt JJ B-NP O
experienced JJ I-NP O
shaking NN I-NP O
during IN B-PP O
procedure NN B-NP O
and CC O O
had VBD B-VP O
acute JJ B-NP O
loss NN I-NP O
of IN B-PP O
motor NN B-NP O
and CC O O
sensory JJ B-NP O
strength NN I-NP O
in IN B-PP O
the DT B-NP O
LE NNP I-NP O
's POS B-NP O
. . I-NP O
Per NNP I-NP O
Nursing NNP I-NP O
chart NN I-NP O
at IN B-PP O
OSH NNS B-NP O
ED VBN B-VP O
, , O O
pt VBD B-VP O
given VBN I-VP O
Morphine NNP B-NP O
for IN B-PP O
abd NN B-NP O
pain NN I-NP O
(around JJ I-NP O
4p-8p JJ I-NP O
) -RRB- I-NP O
with IN B-PP O
coffee NN B-NP O
ground NN I-NP O
emesis NN I-NP O
at IN B-PP O
8pm JJ B-NP O
with IN B-PP O
subsequent JJ B-NP O
decrease NN I-NP O
in IN B-PP O
BP NNP B-NP O
to TO B-VP O
76/49 VB I-VP O
and CC O O
started VBD B-VP O
on IN B-PP O
dopamine NN B-NP O
for IN B-PP O
pressure NN B-NP O
support NN I-NP O
. . O O
At IN B-PP O
the DT B-NP O
same JJ I-NP O
time NN I-NP O
, , O O
pt JJ B-NP O
c/o NN I-NP O
numbness NN I-NP O
in IN B-PP O
feet NNS B-NP O
. . O O
Per IN B-PP O
charts NNS B-NP O
he PRP B-NP O
was VBD B-VP O
reported VBN I-VP O
to TO I-VP O
be VB I-VP O
bending VBG I-VP O
forward RB B-ADVP O
coughing NN B-NP O
and CC I-NP O
vomiting NN I-NP O
and CC O O
experienced VBD B-VP O
acute JJ B-NP O
loss NN I-NP O
of IN B-PP O
sensation/motor NN B-NP O
function NN I-NP O
in IN B-PP O
the DT B-NP O
abdomen NN I-NP O
and CC O O
lower JJR B-NP O
extremities NNS I-NP O
. . O O
Course NNP B-NP O
at IN B-PP O
the DT B-NP O
outside JJ I-NP O
hospital NN I-NP O
- : O O
1.Neuro- DT B-NP O
acute JJ I-NP O
loss NN I-NP O
of IN B-PP O
sensation/motor NN B-NP O
at IN B-PP O
the DT B-NP O
level NN I-NP O
of IN B-PP O
T8 CD B-NP O
. . O O
Per IN B-PP O
Neurology NNP B-NP O
, , O O
had VBD B-VP O
paraplegic JJ B-NP O
legs NNS I-NP O
, , O O
no DT B-NP O
sphincter NN I-NP O
tone NN I-NP O
, , O O
no DT B-NP O
anal JJ I-NP O
wink NN I-NP O
, , O O
Sx NNP B-NP O
were VBD B-VP O
concerning VBG I-VP O
for IN B-PP O
aortic JJ B-NP O
dissection NN I-NP O
. . O O
Abd '' O O
US PRP B-NP O
unrevealing VBG B-VP O
but CC O O
was VBD B-VP O
reported VBN I-VP O
as IN B-PP O
a DT B-NP O
poor JJ I-NP O
study NN I-NP O
. . O O
CT NNP O O
of IN B-PP O
T8-T10 NNP B-NP O
did VBD B-VP O
not RB I-VP O
show VB I-VP O
gross JJ B-NP O
deviations NNS I-NP O
of IN B-PP O
spine NN B-NP O
, , O O
no DT B-NP O
soft JJ I-NP O
tissue NN I-NP O
masses NNS I-NP O
or CC O O
disk NN B-NP O
bulging NN I-NP O
. . O O
2.GI- DT B-NP O
Coffee NNP I-NP O
ground NN I-NP O
emesis NN I-NP O
at IN B-PP O
OSH NNP B-NP O
, , O O
with IN B-PP O
no DT B-NP O
fresh JJ I-NP O
blood NN I-NP O
- : O O
with IN B-PP O
dropping VBG B-NP O
HCT NNP I-NP O
44-40-35 CD I-NP O
and CC O O
transfused VBD B-VP O
1 CD B-NP O
U NNP I-NP O
pRBC NN I-NP O
on IN B-PP O
12/11 CD B-NP B-DATE
. . O O
Also RB B-ADVP O
guiac JJ B-NP O
+ NNS I-NP O
. . B-NP O
Etiology NN I-NP O
thought VBD B-VP O
to TO I-VP O
be VB I-VP O
2/2 CD B-NP O
ASA NNP I-NP O
and CC I-NP O
plavix NN I-NP O
. . O O
No DT B-NP O
egd NN I-NP O
was VBD B-VP O
performed VBN I-VP O
and CC O O
amlyase NN B-NP O
and CC I-NP O
lipase NN I-NP O
, , O O
and CC O O
LFTs NNP B-NP O
were VBD B-VP O
nl RB B-ADVP O
per IN B-PP O
report NN B-NP O
. . O O
3.ID- DT B-NP O
Pt NNP I-NP O
was VBD B-VP O
hypotensive JJ B-ADJP O
with IN B-PP O
SBP NNP B-NP O
in IN B-PP O
the DT B-NP O
70 CD I-NP O
's VBZ B-VP O
on IN B-PP O
presentation NN B-NP O
with IN B-PP O
good JJ B-NP O
response NN I-NP O
to TO B-PP O
fluids NNS B-NP O
, , O O
In IN B-PP O
setting NN B-NP O
of IN B-PP O
elevated JJ B-NP O
WBC NNP I-NP O
to TO B-PP O
22 CD B-NP O
pt NN I-NP O
was VBD B-VP O
empirically RB I-VP O
treated VBN I-VP O
with IN B-PP O
Abx NNP B-NP O
(zosyn NNP I-NP O
, , O O
flagyl NN B-NP O
and CC I-NP O
vanc NN I-NP O
) -RRB- I-NP O
. . O O
BCx NNP B-NP O
were VBD B-VP O
sent VBN I-VP O
and CC O O
CXR NNP B-NP O
appeared VBD B-VP O
clear JJ B-ADJP O
. . O O
4.CARDIAC JJ B-NP O
- : O O
Cardiac NNP B-NP O
enzymes NNS I-NP O
were VBD B-VP O
followed VBN I-VP O
with IN B-PP O
increasing VBG B-NP O
Troponins NNP I-NP O
: : O O
0.04 CD B-NP O
0.07 CD I-NP O
0.08 CD I-NP O
0.09 CD I-NP O
, , O O
CK NNP B-NP O
index NN I-NP O
: : O O
3.0 CD B-NP O
3.7 CD I-NP O
. . O O
No DT B-NP O
complaints NNS I-NP O
of IN B-PP O
chest NN B-NP O
pain NN I-NP O
during IN B-PP O
his PRP$ B-NP O
stay NN I-NP O
. . O O
And CC O O
no DT B-NP O
report NN I-NP O
of IN B-PP O
signifigant JJ B-NP O
EKG JJ I-NP O
changes NNS I-NP O
. . O O
5.Renal- DT B-NP O
Creatinine NNP I-NP O
increase NN I-NP O
from IN B-PP O
2.6 CD B-NP O
to TO B-PP O
3.1 CD B-NP O
thought NN I-NP O
to TO B-VP O
be VB I-VP O
2/2 CD B-NP O
Acute NNP I-NP O
on IN B-PP O
chronic NN B-NP O
RF. . O O
Pt NNP B-NP O
transferred VBD B-VP O
to TO B-PP O
HOB NNP B-NP B-HOSPITAL
for IN B-PP O
further JJ B-NP O
eval NN I-NP O
of IN B-PP O
r/o NNP B-NP O
dissection NN I-NP O
, , O O
r/o NN B-NP O
cord NN I-NP O
compression NN I-NP O
, , O O
GIB NNP B-NP O
, , O O
poss JJ B-NP O
abd NN I-NP O
ischemia NN I-NP O
, , O O
ARI/CRI NNP B-NP O
Review NNP B-NP O
of IN B-PP O
System NNP B-NP O
on IN B-PP O
admission NN B-NP O
: : O O
CV NN B-NP O
: : O O
no DT B-NP O
orthopnea NN I-NP O
, , O O
no DT B-NP O
PND NN I-NP O
Resp NN B-NP O
: : O O
sob NNS B-NP O
, , O O
no DT B-NP O
cough NN I-NP O
, , O O
no DT B-NP O
sputum NN I-NP O
production NN I-NP O
GI NNP B-NP O
: : O O
abdominal JJ B-NP O
pain NN I-NP O
as IN B-PP O
above JJ B-NP O
, , O O
no DT B-NP O
melena NN I-NP O
, , O O
no DT B-NP O
BRBPR NN I-NP O
, , O O
able JJ B-ADJP O
to TO B-VP O
have VB I-VP O
BM NNP B-NP O
GU NNP B-NP O
: : O O
per IN B-PP O
OSH NNP B-NP O
ED NNP I-NP O
report NN I-NP O
of IN B-PP O
dark JJ B-NP O
urine NN I-NP O
in IN B-PP O
ileostomy NN B-NP O
bag NN I-NP O
x2d VBD B-VP O
with IN B-PP O
decreased VBN B-NP O
UOP . O O
Musculoskeletal NNP B-NP O
: : O O
baseline NN B-NP O
decreased VBD B-VP O
to TO B-PP O
minimal JJ B-NP O
movement NN I-NP O
in IN B-PP O
the DT B-NP O
LLE NNP I-NP O
, , I-NP O
min-mod JJ I-NP O
movement NN I-NP O
in IN B-PP O
right JJ B-NP O
leg NN I-NP O
, , O O
able JJ B-ADJP O
to TO B-VP O
transfer VB I-VP O
to TO B-NP O
and CC O O
from IN B-PP O
wheelchair NN B-NP O
Neuro/Psych RB B-ADVP O
: : O O
alert JJ B-NP O
and CC I-NP O
oriented JJ I-NP O
x3 NNS I-NP O
. . O O
MICU NNP B-NP O
Course NNP I-NP O
: : O O
1.Paraplegia CD B-NP O
: : O O
Has VBZ B-VP O
baseline JJ B-NP O
deficits NNS I-NP O
( -LRB- I-NP O
wheelchair NN I-NP O
bound VBN B-VP O
) -RRB- B-NP O
, , O O
but CC O O
unclear JJ B-ADJP O
how WRB B-ADVP O
they PRP B-NP O
compare VBP B-VP O
to TO B-PP O
current JJ B-NP O
exam--> NN I-NP O
level NN I-NP O
at IN B-PP O
T5/T6 NNP B-NP O
. . O O
- : O O
first JJ B-NP O
MRI NNP I-NP O
showed VBD B-VP O
low JJ B-NP O
T2 NN I-NP O
signal NN I-NP O
collections NNS I-NP O
from IN B-PP O
T6--> JJ B-NP O
L1 NNP I-NP O
with IN B-PP O
displacement NN B-NP O
of IN B-PP O
thoracic JJ B-NP O
cord NN I-NP O
anteriorly RB B-ADVP O
from IN B-PP O
T7-T10 CD B-NP O
. . O O
-no NN B-NP O
cord NN I-NP O
compression NN I-NP O
on IN B-PP O
repeat NN B-NP O
study NN I-NP O
, , O O
however RB B-ADVP O
ddx , O O
still RB B-ADVP O
includes VBZ B-VP O
cord NN B-NP O
infarction NN I-NP O
vs IN B-PP O
demyelinating VBG B-VP O
disease NN B-NP O
-neurosurg NN B-NP O
, , O O
neuro NN B-VP O
consulted VBN I-VP O
, , O O
following VBG B-PP O
2.Respiratory JJ B-NP O
status NN I-NP O
: : O O
Acute NNP B-NP O
desaturation NN I-NP O
2/2 CD B-NP O
methemoglobinemia NN I-NP O
as IN B-PP O
consequence NN B-NP O
of IN B-PP O
topical JJ B-NP O
anesthetic CC I-NP O
- : O O
s/p NN B-VP O
methylene NN B-NP O
blue NN I-NP O
( -LRB- O O
80 CD B-NP O
mg JJ I-NP O
x NN I-NP O
1 CD I-NP O
, , I-NP O
40 CD I-NP O
mg NN I-NP O
x NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
with IN B-PP O
resolution NN B-NP O
of IN B-PP O
methemoglobin NN B-NP O
from IN B-PP O
35 CD B-NP O
% NN I-NP O
to TO B-PP O
1 CD B-NP O
% NN I-NP O
. . O O
3.Renal JJ B-NP O
failure NN I-NP O
: : O O
Possibilities NNS B-NP O
raised VBN B-VP O
include VBP B-VP O
cholesterol NN B-NP O
emboli NNS I-NP O
from IN B-PP O
recent JJ B-NP O
interventions NNS I-NP O
, , O O
relative JJ B-NP O
hypoperfusion NN I-NP O
with IN B-PP O
normalization NN B-NP O
of IN B-PP O
blood NN B-NP O
pressure NN I-NP O
. . O O
- : O O
urine NN B-NP O
eos NNS I-NP O
negative JJ O O
- : O O
Cr NNP B-NP O
2.9-->2.5 CD B-NP O
today NN I-NP O
4.Abdominal JJ B-NP O
pain NN I-NP O
: : O O
mild-moderate JJ B-NP O
stenosis NN I-NP O
just RB B-ADVP O
beyond IN B-PP O
origin NN B-NP O
of IN B-PP O
SMA NNP B-NP O
seen VBN B-VP O
on IN B-PP O
MRA NNP B-NP O
; : O O
considered VBN B-NP O
mesenteric JJ I-NP O
ischemia NN I-NP O
a/w RB B-NP O
low JJ I-NP O
flow NN I-NP O
state NN I-NP O
. . O O
However RB B-ADVP O
, , O O
lactic JJ B-NP O
acid NN I-NP O
1.3 CD I-NP O
, , O O
and CC O O
pH VB B-VP O
wnl NN B-NP O
- : O O
have VBP B-VP O
liberalized VBN I-VP O
bp JJ B-NP O
parameters NNS I-NP O
now RB B-ADVP O
that IN B-SBAR O
dissection NN B-NP O
ruled VBD B-VP O
out IN B-SBAR O
5.GI JJ B-NP O
bleed NN I-NP O
: : O O
coffee NN B-NP O
ground NN I-NP O
emesis-- , O O
unclear JJ B-ADJP O
if IN B-SBAR O
this DT B-NP O
reflects VBZ B-VP O
enteric JJ B-NP O
ischemia NN I-NP O
vs. IN B-PP O
sentinel NN B-NP O
bleeding VBG I-NP O
-GI JJ B-NP O
team NN I-NP O
consulted VBN O O
6.Coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
: : O O
- : O O
troponin FW B-NP O
0.14 CD I-NP O
on IN B-PP O
admission NN B-NP O
, , O O
but CC O O
subsequently RB B-ADVP O
all DT B-NP O
wnl NN I-NP O
, , O O
likely JJ B-NP O
troponin FW I-NP O
leak FW I-NP O
in IN B-PP O
setting VBG B-VP O
of IN B-PP O
GIB NNP B-NP O
prior RB B-ADVP O
to TO B-PP O
admission NN B-NP O
- : O O
taken VBN B-VP O
off RP B-NP O
ASA NNP I-NP O
, , O O
plavix NN B-NP O
in IN B-PP O
context NN B-NP O
of IN B-PP O
suspected JJ B-NP O
UGIB NNP I-NP O
- : O O
cont NN B-NP O
lopressor NN I-NP O
- : O O
hydral JJ B-NP O
, , I-NP O
isordil JJ I-NP O
, , I-NP O
goal NN I-NP O
SBP NNP I-NP O
140-150 CD O O
7.Hemodynamics NNS B-NP O
: : O O
- : O O
TEE NN B-NP O
with IN B-PP O
no DT B-NP O
dissection NN I-NP O
- : O O
TTE NN B-NP O
with IN B-PP O
EF NNP B-NP O
54 CD I-NP O
% NN I-NP O
, , O O
no DT B-NP O
SWMA NNP I-NP O
, , O O
no DT B-NP O
tamponade NN I-NP O
- : O O
metoprolol NN B-VP O
+/ NN B-NP O
- : O O
isordil/hydral NN B-NP O
8.Diabetes . B-NP O
mellitus NN I-NP O
- : O O
on IN B-PP O
MICU JJ B-NP O
insulin NN I-NP O
protocol NN I-NP O
, , O O
will MD B-VP O
switch VB I-VP O
to TO B-PP O
sliding VBG B-NP O
scale NN I-NP O
Past NNP B-NP O
Medical NNP I-NP O
History NNP I-NP O
: : O O
1 LS O O
. . B-NP O
Paraplegia NNP I-NP O
secondary JJ I-NP O
to TO B-PP O
Compression NNP B-NP O
fracture NN I-NP O
in IN B-PP O
Amusement NNP B-NP O
Park NNP I-NP O
accident NN I-NP O
in IN B-PP O
2066 CD B-NP B-DATE
2. DT B-NP O
cervical JJ I-NP O
spondylosis NN I-NP O
3. DT B-NP O
COPD NNP I-NP O
uses VBZ B-VP O
prn JJ B-NP O
Albuterol NNP I-NP O
MDI . O O
4 CD B-LST O
. . O O
CAD NNP B-NP O
S/P NNP I-NP O
CABG NNP I-NP O
X3 NNP I-NP O
in IN B-PP O
2087 CD B-NP B-DATE
catheterization NN I-NP O
done VBN B-VP O
in IN B-PP O
March NNP B-NP B-DATE
2090 CD I-NP I-DATE
: : O O
patent NN B-NP O
SVG NN I-NP O
to TO B-PP O
RCA NNP B-NP O
, , O O
patent NN B-NP O
LIMA NNP I-NP O
to TO B-PP O
LAD NNP B-NP O
, , O O
occluded VBD B-VP O
SVG NNP B-NP O
to TO B-PP O
Circ NNP B-NP O
; : O O
stress NN B-NP O
5/94 CD I-NP B-DATE
/o NN I-NP O
ischemia NN I-NP O
; : O O
Cath NNP B-NP O
with IN B-PP O
stent NN B-NP O
in IN B-PP O
circumflex NN B-NP O
11/28/95 CD I-NP B-DATE
5 CD B-NP O
. . O O
Ileoloop NNP B-NP O
complicated VBN B-VP O
by IN B-PP O
pyelo JJ B-NP O
X7 CD I-NP O
2079 CD I-NP B-DATE
- : O O
2082 CD B-NP B-DATE
+ NN I-NP O
neurogenic JJ I-NP O
bladder NN I-NP O
( -LRB- I-NP O
ostomy NN I-NP O
for IN B-PP O
urine NN B-NP O
) -RRB- O O
6 CD B-NP O
. . O O
TIA NNP B-NP O
's POS B-NP O
, , O O
s/p JJ B-NP O
bilateral JJ I-NP O
Carotid NNP I-NP O
endarterectomies NNS I-NP O
7. . B-NP O
Hypercholesterolemia NNP I-NP O
8. . O O
IDDM . O O
9 CD B-NP O
. . O O
Disc NNP B-NP O
Herniation NNP I-NP O
L4-5 . O O
L5 . O O
S1 . O O
10 CD B-NP O
Decreased JJ I-NP O
hearing NN I-NP O
and CC O O
tinnitus NN B-NP O
11 CD B-NP O
. . O O
UGI NNP B-NP O
bleed VBD B-VP O
in IN B-PP O
2089 CD B-NP B-DATE
( -LRB- I-NP O
2 CD I-NP O
unit NN I-NP O
PRBC NN I-NP O
's POS B-NP O
) -RRB- I-NP O
negative JJ I-NP O
endoscopy NN I-NP O
in IN B-PP O
9/92 CD B-NP B-DATE
12 CD B-LST O
. . O O
Hemorrhoids '' O O
13 CD B-NP O
. . O O
Candida NNP B-NP O
Infection NNP I-NP O
Ileal NNP I-NP O
Conduit NNP I-NP O
2/92 . O B-DATE
14 CD B-NP O
. . O O
Fx NNP O O
. . O O
left VBD B-VP O
Tibia NNP B-NP O
c NN I-NP O
rod NN I-NP O
placement NN I-NP O
in IN B-PP O
2/92 CD B-NP B-DATE
15 CD B-NP O
. . O O
Acute NNP B-NP O
depression NN I-NP O
: : O O
after IN B-PP O
his PRP$ B-NP O
injury NN I-NP O
he PRP B-NP O
was VBD B-VP O
very RB B-ADJP O
depressed JJ I-ADJP O
and CC O O
self NN B-NP O
destructive JJ I-NP O
sought VBD I-NP O
counseling NN I-NP O
and CC O O
was VBD B-VP O
hospitalized VBN I-VP O
after IN B-PP O
cutting VBG B-VP O
his PRP$ B-NP O
wrists NNS I-NP O
and CC O O
trying VBG B-VP O
to TO I-VP O
inhale VB I-VP O
gas NN B-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
on IN B-PP O
various JJ B-NP O
antidepressants NNS I-NP O
and CC O O
currently RB B-VP O
lives VBZ I-VP O
with IN B-PP O
his PRP$ B-NP O
wife NN I-NP O
on IN B-PP O
no DT B-NP O
medication NN I-NP O
. . O O
His PRP$ B-NP O
sx NN I-NP O
's POS B-NP O
have VBP B-VP O
improved VBN I-VP O
since IN B-PP O
becoming VBG B-VP O
sober JJ B-ADJP O
in IN B-PP O
2087 CD B-NP B-DATE
. . O O
16 CD B-NP O
. . O O
Bilateral NNP B-NP O
ileo-femoral JJ I-NP O
bypass NN I-NP O
, , O O
renal JJ B-NP O
artery NN I-NP O
stent NN I-NP O
11/24/95 CD O B-DATE
17 CD B-NP O
. . O O
Known NNP B-NP O
discrepancy NN I-NP O
of IN B-PP O
30 CD B-NP O
mmHg NN I-NP O
in IN B-PP O
BP NNP B-NP O
between IN B-PP O
L, DT B-NP O
R NN I-NP O
arms NNS I-NP O
Medications NNS B-NP O
: : O O
prior RB B-ADVP O
to TO B-PP O
admission NN B-NP O
at IN B-SBAR O
OSH NNP B-NP O
ASA NNP B-NP O
325 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
Plavix NNP B-NP O
75 CD I-NP O
mg NN I-NP O
Lopressor NNP B-NP O
50 CD I-NP O
mg JJ I-NP O
po NN I-NP O
bid NN I-NP O
Losartan NNP B-NP O
50 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
Furosemide NNP B-NP O
40 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
NTG NNP B-NP O
SL NNP I-NP O
prn NN I-NP O
Fluvastatin NNP B-NP O
40 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
APAP NNP B-NP O
500 CD I-NP O
mg NN I-NP O
po NN I-NP O
2 CD I-NP O
tid NN I-NP O
prn NN I-NP O
Glyburide NNP B-NP O
5 CD I-NP O
mg NN I-NP O
qam NN I-NP O
,qpm . O O
NPH NNP B-NP O
insulin NN I-NP O
12U IN B-PP O
qam NNP B-NP O
, , O O
18 CD B-NP O
U NNP I-NP O
qpm NN I-NP O
Lortisone NNP B-NP O
cream NN I-NP O
to TO B-PP O
stoma NN B-NP O
tid NN I-NP O
prn NN I-NP O
Atrovent NNP B-NP O
MDI NNP I-NP O
2 CD I-NP O
puffs NNS I-NP O
bid NN O O
Pulmicort NNP B-NP O
MID NNP I-NP O
2 CD I-NP O
puffs NNS I-NP O
bid NN O O
Albuterol NNP B-NP O
MDI NNP I-NP O
2 CD I-NP O
puffs NNS I-NP O
prn VBP B-VP O
up RP B-PRT O
to TO B-VP O
qid VB I-VP O
Allergies NNP B-NP O
: : O O
hurricane NN B-VP O
spray NN B-NP O
methemoglobinemia NN I-NP O
Family NNP B-NP O
History NN I-NP O
: : O O
Non FW B-NP O
contributory NN I-NP O
Social JJ B-NP O
history NN I-NP O
: : O O
Smoking VBG B-VP O
: : O O
discontinued VBN B-VP O
in IN B-PP O
2087 CD B-NP B-DATE
after IN B-PP O
smoking VBG B-VP O
2PPD CD B-NP O
for IN B-PP O
50 CD B-NP O
years NNS I-NP O
Alcohol NNP B-NP O
Use NNP I-NP O
: : O O
quit VB B-VP O
all DT B-NP O
alcohol NN I-NP O
in IN B-PP O
2087 CD B-NP B-DATE
Exercise NN B-NP O
: : O O
wheelchair NN B-NP O
bound VBN O O
Occupation NNP B-NP O
: : O O
retired VBN B-NP O
Family NNP B-NP O
: : O O
Married NNP B-NP O
, , O O
daughter NN B-NP O
nearby RB I-NP O
, , O O
son NN B-NP O
(estranged VBD B-VP O
) -RRB- B-NP O
in IN B-PP O
GA NNP B-NP B-STATE
Physical JJ B-NP O
Exam NNP I-NP O
: : O O
VITALS NNS B-NP O
: : O O
T=97.3 CD B-NP O
BP=166/58 CD I-NP O
HR=84 IN B-PP O
RR=28 CD B-NP O
O2=95 CD I-NP O
%4L . O O
GEN NNP B-NP O
: : O O
Lying VBG B-VP O
in IN B-PP O
bed NN B-NP O
in IN B-PP O
NAD NNP B-NP O
slouched VBD B-VP O
over IN B-PP O
eating VBG B-VP O
ice NN B-NP O
cream NN I-NP O
HEENT NNP B-NP O
: : O O
nasal JJ B-NP O
cannula NNS I-NP O
in IN B-PP O
place NN B-NP O
NECK NNP B-NP O
: : O O
supple NN B-NP O
, , O O
JVP NNP B-NP O
< NNP I-NP O
8cm CC I-NP O
; : O O
carotid NN B-NP O
bruit NN I-NP O
on IN B-PP O
R NN B-NP O
CHEST NNP B-NP O
: : O O
slight JJ B-NP O
crackles NNS I-NP O
at IN B-PP O
R NN B-NP O
base NN I-NP O
, , O O
otherwise RB B-ADVP O
CTAB NNP B-NP O
w/good VBD B-VP O
air NN B-NP O
mvt NN I-NP O
CV NNP B-NP O
: : O O
RRR NNP B-NP O
, , O O
nlS1S2 NN B-NP O
, , O O
2/6 CD B-NP O
SEM NNP I-NP O
LUSB NNP I-NP O
ABD NNP B-NP O
: : O O
ostomy NN B-NP O
intact JJ I-NP O
; : O O
soft JJ B-ADJP O
, , O O
ND NNP B-NP O
, , O O
NT NNP B-NP O
EXT NNP B-NP O
: : O O
warm JJ B-NP O
, , O O
no DT B-NP O
edema NN I-NP O
NEURO NNP B-NP O
: : O O
alert JJ B-ADJP O
, , O O
oriented VBN B-VP O
to TO B-PP O
person NN B-NP O
, , O O
HOB NNP B-NP B-HOSPITAL
, , O O
late- RB B-ADVP O
Nov NNP B-NP I-DATE
, , O I-DATE
2095 CD B-NP I-DATE
; : O O
remembers VBZ B-PP O
most RBS B-NP O
of IN B-PP O
events NNS B-NP O
of IN B-PP O
past JJ B-NP O
2 CD I-NP O
wks NNS I-NP O
; : O O
CN NNP B-NP O
II-XII NNP I-NP O
intact JJ I-NP O
; : O O
mass NN B-NP O
, , O O
tone NN B-NP O
in IN B-PP O
UE JJ B-NP O
nl JJ I-NP O
bilat NN I-NP O
, , O O
LE JJ B-NP O
atrophied JJ I-NP O
bilat NN I-NP O
; : O O
strength NN B-NP O
4/5 CD I-NP O
bilat NN I-NP O
in IN B-PP O
UE NNP B-NP O
, , O O
0/5 CD B-NP O
LE JJ I-NP O
; : O O
1+ CD B-NP O
DTRs NNS I-NP O
UE NNP I-NP O
, , O O
0 CD B-NP O
DTRs NNS I-NP O
LE JJ B-ADJP O
; : O O
sensation NN B-NP O
grossly RB I-NP O
intact JJ I-NP O
UE NNP I-NP O
, , O O
absent JJ B-ADJP O
in IN B-PP O
LE NNP B-NP O
's POS B-NP O
below IN B-PP O
umbilicus NN B-NP O
. . O O
Labs NNS B-NP O
: : O O
HOB NNP B-NP B-HOSPITAL
BLOOD NNP I-NP O
13-Dec-2095 . O B-DATE
04 CD B-NP O
:45 CD I-NP O
Accession NNP B-NP O
# # I-NP O
3084A07688 CD O B-MEDICALRECORD
Sodium NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
144 CD I-NP O
( -LRB- I-NP O
135-145 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Potassium NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
4.0 CD I-NP O
( -LRB- I-NP O
3.4-4.8 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Chloride NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
119 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
100-108 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
CO2 NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
19.7 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
23.0-31.9 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
BUN NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
51 CD I-NP O
H NNP B-NP O
(8-25 . O O
) -RRB- O O
mg/dl . O O
Creatinine NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NN I-NP O
) -RRB- I-NP O
2.5 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.6-1.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Glucose FW B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
165 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
70-110 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Calcium NNP B-NP O
7.9 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
8.5-10.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Phosphorus NNP B-NP O
2.4 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
2.6-4.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Magnesium JJ B-NP O
1.9 CD I-NP O
( -LRB- O O
1.4-2.0) CD B-NP O
meq/L NN I-NP O
Total JJ B-NP O
Protein NNP I-NP O
5.8 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
6.0-8.3 CD I-NP O
) -RRB- I-NP O
g/dl . O O
Albumin NNP B-NP O
2.7 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
3.3-5.0) JJ I-NP O
g/dl NN I-NP O
Globulin NNP B-NP O
3.1 CD I-NP O
( -LRB- I-NP O
2.6-4.1 CD I-NP O
) -RRB- I-NP O
g/dl . O O
Direct JJ B-NP O
Bilirubin NNP I-NP O
0.2 CD I-NP O
(0-0.4 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Total JJ B-NP O
Bilirubin NNP I-NP O
0.3 CD I-NP O
(0-1.0) JJ I-NP O
mg/dl NN I-NP O
Alkaline NNP B-NP O
Phosphatase NNP I-NP O
53 CD I-NP O
( -LRB- O O
45-115 CD B-NP O
) -RRB- I-NP O
U/L . O O
Transaminase-SGPT NN B-NP O
10 CD I-NP O
( -LRB- I-NP O
10-55 CD I-NP O
) -RRB- I-NP O
U/L . O O
Amylase JJ B-NP O
44 CD I-NP O
(3-100 CD I-NP O
) -RRB- O O
units/L NN O O
Lipase NN B-NP O
2.2 CD I-NP O
( -LRB- O O
1.3-6.0) CD B-NP O
U/dl NN I-NP O
Creatine JJ B-NP O
Kinase NNP I-NP O
Isoenz NNP I-NP O
4.1 CD I-NP O
( -LRB- I-NP O
0.0-6.9 CD I-NP O
) -RRB- I-NP O
ng/ml . O O
CPK NNP B-NP O
Isoenzymes NNP I-NP O
Index NNP I-NP O
( -LRB- B-VP O
0.0-3.5 CD B-PP O
) -RRB- B-NP O
% NN I-NP O
CPK NNP B-NP O
and/or CC I-NP O
CKMB NNP I-NP O
too RB I-NP O
low JJ B-ADJP O
to TO B-VP O
calculate VB I-VP O
Relative NNP B-NP O
Index NNP I-NP O
. . O O
Troponin-T NNP B-NP O
0.07 CD I-NP O
( -LRB- I-NP O
0.00-0.09 CD I-NP O
) -RRB- I-NP O
ng/ml . O O
Transaminase-SGOT JJ B-NP O
13 CD I-NP O
( -LRB- I-NP O
10-40 CD I-NP O
) -RRB- I-NP O
U/L . O O
Creatine JJ B-NP O
Kinase NNP I-NP O
313 CD I-NP O
(60-400 NN I-NP O
) -RRB- I-NP O
U/L . O O
Vancomycin, NNP B-NP O
Unspecified NNP I-NP O
12.0 CD I-NP O
mcg/ml NN I-NP O
PEAK NN B-NP O
: : O O
15.0-35.0 CD O O
TROUGH NNP B-NP O
: : O O
0-10.0 CD O O
HOB NNP B-NP B-HOSPITAL
BLOOD NNP I-NP O
13-Dec-2095 . O B-DATE
05 CD B-NP O
:07 CD I-NP O
Accession NNP B-NP O
# # I-NP O
8446G98130 CD O B-MEDICALRECORD
WBC NNP B-NP O
14.6 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
4.5-11.0) JJ I-NP O
th/cmm NN I-NP O
HCT NNP B-NP O
28.1 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
41.0-53.0) CD I-NP O
% NN I-NP O
HGB NNP B-NP O
9.6 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
13.5-17.5 CD I-NP O
) -RRB- I-NP O
gm/dl . O O
RBC NNP B-NP O
3.14 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
4.50-5.90 CD I-NP O
) -RRB- I-NP O
mil/cmm . O O
PLT NNP B-NP O
320 CD I-NP O
( -LRB- I-NP O
150-350 CD I-NP O
) -RRB- I-NP O
th/cumm . O O
MCV NNP B-NP O
90 CD I-NP O
( -LRB- I-NP O
80-100 CD B-PP O
) -RRB- B-NP O
fl NN I-NP O
MCH NNP B-NP O
30.7 CD I-NP O
( -LRB- I-NP O
26.0-34.0) JJ I-NP O
pg/rbc NN I-NP O
MCHC NNP B-NP O
34.3 CD I-NP O
( -LRB- O O
31.0-37.0) CD B-NP O
g/dl NN I-NP O
RDW NNP B-NP O
14.2 CD I-NP O
( -LRB- I-NP O
11.5-14.5 CD B-PP O
) -RRB- B-NP O
% NN I-NP O
PT NNP B-NP O
14.0 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
11.1-13.1 CD B-PP O
) -RRB- B-NP O
sec NN I-NP O
PT-INR NN B-NP O
1.3 CD I-NP O
PT-INR JJ B-NP O
values NNS I-NP O
are VBP B-VP O
valid JJ B-ADJP O
only RB I-ADJP O
for IN B-PP O
WARFARIN NNP B-NP O
ANTI-COAG NNP I-NP O
THERAPY NNP I-NP O
. . O O
APTT NNP B-NP O
19.9 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
22.1-35.1 CD B-PP O
) -RRB- B-NP O
sec NN I-NP O
DIFFERENTIAL NNP B-NP O
REQUEST NNP I-NP O
RECEIVED NNP I-NP O
Diff JJ B-NP O
Method NNP I-NP O
Auto NN I-NP O
Poly NNP B-NP O
82 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
40-70 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Lymphs NNP B-NP O
10 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
22-44 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Monos NNP B-NP O
3 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
4-11 NN I-NP O
) -RRB- B-NP O
% NN I-NP O
EOS NNP B-NP O
5 CD I-NP O
(0-8 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Basos NNS B-NP O
0 CD B-NP O
(0-3 JJ I-NP O
) -RRB- I-NP O
% NN I-NP O
Absolute JJ B-NP O
Neuts NNP I-NP O
11.98 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
1.8-7.7 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Lymphs NNP I-NP O
1.46 CD I-NP O
( -LRB- I-NP O
1.0-4.8 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Monos NNP I-NP O
0.41 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.2-0.4 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
EOS NNP I-NP O
0.70 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.1-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Basos NNP I-NP O
0.03 CD I-NP O
( -LRB- I-NP O
0.0-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Aniso NNP B-NP O
None NN I-NP O
( -LRB- I-NP O
NORMAL NNP I-NP O
) -RRB- O O
Hypo NNP B-NP O
None NN I-NP O
( -LRB- I-NP O
NORMAL NNP I-NP O
) -RRB- O O
Macrocytes NNP B-NP O
None NN I-NP O
Microcytes NNS B-NP O
None NN I-NP O
MICRO NNP B-NP O
: : O O
Urine NNP B-NP O
, , O O
blood NN B-NP O
cx NN I-NP O
x NN I-NP O
2 CD I-NP O
NGTD NN I-NP O
at IN B-PP O
HOB NNP B-NP B-HOSPITAL
; : O O
VRE NNP B-NP O
neg NN I-NP O
x1 NN I-NP O
; : O O
MRSA NNP B-NP O
nasal NN I-NP O
swab NN I-NP O
neg NN I-NP O
x1 . O O
EKG NNP B-NP O
: : O O
NSR NNP B-NP O
at IN B-PP O
80 CD B-NP O
, , O O
nl JJ B-NP O
axis NN I-NP O
, , O O
old JJ B-NP O
ST NNP I-NP O
depressions NNS I-NP O
in IN B-PP O
V4-5 CD B-NP O
CXR NN B-NP O
( -LRB- I-NP O
12/13 CD I-NP B-DATE
) -RRB- I-NP O
: : O O
Stable JJ B-NP O
chest NN I-NP O
without IN B-PP O
new JJ B-NP O
or CC I-NP O
enlarging JJ I-NP O
infiltrates NNS I-NP O
or CC I-NP O
pneumonias NNS I-NP O
. . O O
Cardiac NNP B-NP O
size NN I-NP O
normal JJ I-NP O
, , O O
no DT B-NP O
signs NNS I-NP O
of IN B-PP O
edema NN B-NP O
or CC I-NP O
decompensation NN I-NP O
. . O O
Operative NN B-NP O
changes NNS I-NP O
as IN B-PP O
before IN B-NP O
and CC I-NP O
right JJ I-NP O
subclavian JJ I-NP O
central JJ I-NP O
line NN I-NP O
as IN B-PP O
before IN B-PP O
without IN B-PP O
apparent JJ B-NP O
pneumothorax NN I-NP O
or CC I-NP O
complication NN I-NP O
. . O O
MRI NNP B-NP O
( -LRB- I-NP O
12/12 CD I-NP B-DATE
) -RRB- I-NP O
: : O O
EXAMINATION NN B-NP O
: : O O
MRI NNP B-NP O
of IN B-PP O
the DT B-NP O
cervical JJ I-NP O
, , I-NP O
thoracic JJ I-NP O
, , I-NP O
lumbar JJ I-NP O
spine NN I-NP O
. . O O
EXAMINATION NN B-NP O
DATE NNP I-NP O
: : O O
12/12/95 CD B-NP B-DATE
. . O O
Comparison NNP B-NP O
films NNS I-NP O
: : O O
The DT B-NP O
prior JJ I-NP O
films NNS I-NP O
are VBP B-VP O
available JJ B-ADJP O
for IN B-PP O
comparison NN B-NP O
to TO B-PP O
due JJ B-NP O
PACS NNP I-NP O
technical JJ I-NP O
difficulties NNS I-NP O
. . O O
Comparison NN B-NP O
is VBZ B-VP O
made VBN I-VP O
with IN B-PP O
the DT O O
report NN B-NP O
of IN B-PP O
prior JJ B-NP O
C-spine NN I-NP O
CT NN I-NP O
from IN B-PP O
January NNP B-NP B-DATE
2095 CD I-NP I-DATE
. . O O
History NN B-NP O
: : O O
72 CD B-NP B-AGE
year NN I-NP O
old JJ I-NP O
man NN I-NP O
with IN B-PP O
history NN B-NP O
of IN B-PP O
paraplegia NN B-NP O
from IN B-PP O
traumatic JJ B-NP O
injury NN B-NP O
in IN B-PP O
2066 CD B-NP B-DATE
with IN B-PP O
new JJ B-NP O
sensation NN I-NP O
loss NN I-NP O
and CC I-NP O
motor NN I-NP O
loss NN I-NP O
below IN B-PP O
T8 CD B-NP O
. . O O
Technique NNP B-NP O
:Sagittal NNP I-NP O
T2 NNP I-NP O
images NNS I-NP O
were VBD B-VP O
obtained VBN I-VP O
of IN B-PP O
the DT B-NP O
cervical JJ I-NP O
, , O O
thoracic JJ B-NP O
, , I-NP O
lumbar JJ I-NP O
spine NN I-NP O
. . O O
The DT B-NP O
Axial NNP I-NP O
T2 NNP I-NP O
images NNS I-NP O
are VBP B-VP O
obtained VBN I-VP O
from IN B-PP O
T10 CD B-NP O
through IN B-PP O
L1 NNP B-NP O
. . O O
The DT B-NP O
images NNS I-NP O
are VBP B-VP O
moderately RB B-NP O
motion NN I-NP O
degraded VBD B-VP O
in IN B-PP O
the DT O O
thoracic JJ B-NP O
and CC I-NP O
lumbar JJ I-NP O
spine NN I-NP O
. . O O
The DT B-NP O
cervical JJ I-NP O
spine NN I-NP O
MRI NNP I-NP O
was VBD B-VP O
repeated VBN I-VP O
three CD B-NP O
times NNS I-NP O
due JJ B-ADJP O
to TO B-PP O
motion NN B-NP O
. . O O
No DT B-NP O
contrast NN I-NP O
was VBD B-VP O
used VBN I-VP O
. . O O
Findings NNS B-NP O
: : O O
CERVICAL NNP B-NP O
SPINE NNP I-NP O
: : O O
Straightening VBG B-VP O
of IN B-PP O
the DT B-NP O
cervical JJ I-NP O
lordosis NN I-NP O
is VBZ B-VP O
noted VBN I-VP O
from IN B-PP O
C2 NNP B-NP O
through IN B-PP O
C6 NNS B-NP O
. . O O
Bone NN B-VP O
marrow NN B-NP O
signal NN I-NP O
demonstrates VBZ B-VP O
patchy JJ B-NP O
areas NNS I-NP O
of IN B-PP O
T2 DT B-NP O
high JJ I-NP O
signal NN I-NP O
within IN B-PP O
the DT B-NP O
C4 NNP I-NP O
and CC O O
C5 DT B-NP O
vertebral JJ I-NP O
body NN I-NP O
. . O O
Posterior NNP B-NP O
disc NN I-NP O
osteophyte NN I-NP O
complexes NNS B-NP O
are VBP B-VP O
present JJ B-ADJP O
at IN B-PP O
C2/C3 NNP B-NP O
, , O O
C3/C4 NNP B-NP O
, , O O
C4/C5 NNP B-NP O
, , O O
C5/C6 NNP B-NP O
, , O O
C6/C7 NNP B-NP O
. . O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
status NN B-NP O
post NN I-NP O
posterior NN I-NP O
laminectomy NN I-NP O
and CC I-NP O
fusion NN I-NP O
which WDT O O
causes VBZ O O
susceptibility NN B-NP O
artifact NN I-NP O
. . O O
The DT B-NP O
laminectomy NN I-NP O
from IN B-PP O
C3 NNP B-NP O
through IN B-PP O
C7 NNS B-NP O
, , O O
previously RB B-VP O
noted VBN I-VP O
, , O O
is VBZ B-VP O
not RB I-VP O
well RB I-VP O
visualized VBN I-VP O
due JJ B-ADJP O
to TO B-PP O
motion NN B-NP O
artifact NN B-NP O
and CC I-NP O
susceptibility NN I-NP O
. . O O
THORACIC NNP B-NP O
SPINE NNP I-NP O
: : O O
There EX B-NP O
is VBZ B-VP O
partial JJ B-NP O
fusion NN I-NP O
of IN B-PP O
T4 NNP B-NP O
to TO B-VP O
T5 VB I-VP O
with IN B-PP O
loss NN B-NP O
of IN B-PP O
height NN B-NP O
of IN B-PP O
T4 NNP B-NP O
and CC O O
focal JJ B-NP O
kyphosis NN I-NP O
at IN B-PP O
this DT B-NP O
area NN I-NP O
. . O O
Myelomalacia NNP B-NP O
is VBZ B-VP O
noted VBN I-VP O
from IN B-PP O
T1 NNP B-NP O
through IN B-PP O
T5 CD B-LST O
. . O O
There EX B-NP O
is VBZ B-VP O
focal JJ B-NP O
T2 DT I-NP O
high JJ I-NP O
signal NN I-NP O
within IN B-PP O
the DT B-NP O
cord NN I-NP O
substance NN I-NP O
at IN B-PP O
the DT O O
T4 DT B-NP O
level NN I-NP O
. . O O
T2 DT B-NP O
low JJ I-NP O
signal NN I-NP O
collections NNS I-NP O
are VBP B-VP O
noted VBN I-VP O
posterior JJ B-ADJP O
to TO B-PP O
the DT B-NP O
cord NN I-NP O
at IN B-PP O
T6 CD B-NP O
through IN B-PP O
T12 NN B-NP O
. . O O
A DT B-NP O
high JJ I-NP O
signal NN I-NP O
septation NN I-NP O
is VBZ B-VP O
present JJ B-ADJP O
through IN B-PP O
this DT B-NP O
collection NN B-NP O
at IN B-PP O
T7 NNP B-NP O
and CC O O
extending VBG B-VP O
from IN B-PP O
T11 CD B-NP O
through IN B-PP O
L1 NNP B-NP O
. . O O
This DT B-NP O
low JJ I-NP O
T2 NN I-NP O
signal NN B-NP O
collection NN I-NP O
displaces VBZ B-VP O
the DT B-NP O
cord NN I-NP O
anteriorly RB B-ADVP O
from IN B-PP O
T7 CD B-NP O
through IN B-PP O
T10 CD B-LST O
. . O O
The DT B-NP O
cord NN I-NP O
is VBZ B-VP O
small JJ B-ADJP O
from IN B-PP O
T7 CD B-NP O
through IN B-PP O
T10 DT B-NP O
consistent JJ I-NP O
with IN B-PP O
myelomalacia PRP$ B-NP O
and CC O O
high JJ B-NP O
T2 JJ I-NP O
signal NN I-NP O
. . O O
High NNP B-NP O
signal NN I-NP O
is VBZ B-VP O
also RB B-ADVP O
present JJ B-ADJP O
in IN B-PP O
the DT B-NP O
cord NN I-NP O
substance NN I-NP O
of IN B-PP O
the DT B-NP O
distal NN I-NP O
thoracic JJ B-NP O
cord NN I-NP O
and CC B-PP O
at IN B-PP O
the DT B-NP O
conus NN I-NP O
. . O O
Small JJ B-NP O
amount NN I-NP O
of IN B-PP O
T2 DT B-NP O
high JJ I-NP O
signal NN I-NP O
is VBZ B-VP O
noted VBN I-VP O
in IN B-PP O
encircling VBG B-VP O
the DT B-NP O
distal NN I-NP O
thoracic JJ B-NP O
cord NN I-NP O
and CC O O
the DT B-NP O
spinal JJ I-NP O
roots NNS I-NP O
. . O O
LUMBAR NN B-NP O
SPINE NNP I-NP O
: : O O
Straightening VBG B-VP O
of IN B-PP O
the DT B-NP O
lumbar NN I-NP O
spine NN I-NP O
is VBZ B-VP O
noted VBN I-VP O
with IN B-PP O
grade NN B-NP O
1 CD I-NP O
retrolisthesis NN B-NP O
of IN B-PP O
L4 NNP B-NP O
on IN B-PP O
L5 NNP B-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
a DT B-NP O
levoscoliosis NN I-NP O
with IN B-PP O
apex NN B-NP O
at IN B-PP O
L4/L5 CD B-LST O
. . O O
Disc NNP B-NP O
demonstrates VBZ B-VP O
T2 IN B-PP O
shortening VBG B-VP O
within IN B-PP O
several JJ B-NP O
lumbar NN I-NP O
discs NNS I-NP O
and CC O O
disc JJ B-NP O
height NN I-NP O
loss NN I-NP O
at IN B-PP O
L4/L5 CD B-NP O
, , O O
L5/S1 NNP B-NP O
. . O O
T2 DT B-NP O
high JJ I-NP O
signal NN I-NP O
at IN B-PP O
the DT B-NP O
endplates NNS I-NP O
are VBP B-VP O
noted VBN I-VP O
around IN B-PP O
the DT B-NP O
L4/L5 NNP I-NP O
and CC O O
L5/S1 JJ B-NP O
disc NN I-NP O
levels NNS I-NP O
. . O O
Moderate NNP O O
to TO B-PP O
severe JJ B-NP O
stenosis NN I-NP O
of IN B-PP O
the DT B-NP O
bilateral NN I-NP O
neural JJ B-NP O
foramen NNS I-NP O
at IN B-PP O
L5/S1 NNP B-NP O
facet NN I-NP O
osteoarthritis NN I-NP O
and CC O O
disc JJ B-NP O
height NN I-NP O
loss NN I-NP O
of IN B-SBAR O
L5/S1 NNP B-NP O
is VBZ B-VP O
noted VBN I-VP O
. . O O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
had VBN I-VP O
prior RB B-NP O
surgery NN I-NP O
of IN B-PP O
the DT O O
spinous JJ B-NP O
processes NNS I-NP O
of IN B-PP O
L4 NNP B-NP O
and CC I-NP O
L5 NNP I-NP O
. . O O
The DT B-NP O
conus NN I-NP O
terminates NNS I-NP O
at IN B-PP O
L1/L2 NNP B-NP O
. . O O
The DT B-NP O
spinal JJ I-NP O
roots NNS I-NP O
appear VBP B-VP O
clumped VBN I-VP O
centrally RB B-ADVP O
and CC O O
there EX B-NP O
is VBZ B-VP O
T2 DT B-NP O
high JJ I-NP O
signal NN I-NP O
around IN B-PP O
the DT B-NP O
upper JJ I-NP O
spinal NN I-NP O
roots NNS B-NP O
. . O O
T2 NN B-VP O
high JJ B-NP O
signal NN I-NP O
is VBZ B-VP O
noted VBN I-VP O
at IN B-PP O
the DT B-NP O
distal JJ I-NP O
aspect NN I-NP O
of IN B-PP O
the DT B-NP O
thecal NN I-NP O
sac. . O O
IMPRESSION NN B-NP O
: : O O
1 CD B-NP O
. . O O
Low NNP B-NP O
T2 NNP I-NP O
signal NN I-NP O
collections NNS I-NP O
from IN B-PP O
T6 NNP B-NP O
through IN B-PP O
L1 NNP B-NP O
with IN B-PP O
displacement NN B-NP O
of IN B-PP O
the DT B-NP O
thoracic JJ I-NP O
cord NN I-NP O
anteriorly RB B-ADVP O
from IN B-PP O
T7 CD B-NP O
through IN B-PP O
T10 CD B-NP O
. . O O
The DT B-NP O
differential JJ I-NP O
diagnosis NN I-NP O
for IN B-PP O
this DT B-NP O
collection NN I-NP O
includes VBZ B-VP O
unusual JJ O O
flow NN B-NP O
artifact NN I-NP O
or CC O O
multiloculated JJ B-NP O
septations NNS I-NP O
or CC O O
epidural NN B-NP O
collections NNS B-NP O
. . O O
Recommend NN B-VP O
dedicated VBN I-VP O
thoracic JJ B-NP O
and CC I-NP O
lumbar JJ I-NP O
spine NN I-NP O
MRI . O O
with IN B-PP O
contrast NN B-NP O
and CC I-NP O
T2 NN I-NP O
axials NNS I-NP O
through IN B-PP O
the DT B-NP O
L NNP I-NP O
spine NN I-NP O
and CC I-NP O
C NNP I-NP O
spine NN I-NP O
. . O O
If IN O O
clinically RB B-ADVP O
indicated VBD B-VP O
, , O O
consider VB B-VP O
repeat NN B-NP O
C NNP I-NP O
spine NN I-NP O
MRI NNP I-NP O
with IN B-PP O
contrast NN B-NP O
. . O O
Dr. NNP B-NP O
Winters NNP I-NP B-DOCTOR
was VBD B-VP O
informed VBN I-VP O
of IN B-PP O
this DT B-NP O
at IN B-PP O
2:15 CD B-NP O
PM NNP I-NP O
on IN B-PP O
12/12/95 CD B-NP B-DATE
. . O O
2. DT B-NP O
Myelomalacia NNP I-NP O
of IN B-PP O
the DT B-NP O
thoracic JJ I-NP O
cord NN I-NP O
from IN B-PP O
T4-T5 DT B-NP O
level NN I-NP O
and CC O O
at IN B-PP O
T7-10 NNP B-NP O
. . O O
3. `` O O
The DT B-NP O
spinal JJ I-NP O
roots NNS I-NP O
are VBP B-VP O
incompletely RB I-VP O
imaged VBN I-VP O
but CC O O
have VBP B-VP O
a DT B-NP O
clumped VBN B-VP O
in IN B-PP O
appearance NN B-NP O
suggesting VBG B-VP O
arachnoiditis NN B-NP O
. . O O
Repeat NN B-NP O
axial NN I-NP O
images NNS I-NP O
through IN B-PP O
the DT B-NP O
entire JJ I-NP O
spinal JJ I-NP O
roots NNS I-NP O
could MD B-VP O
better RB I-VP O
evaluate VB I-VP O
this DT B-NP O
. . O O
4 CD B-LST O
. . O O
Degenerative NNP B-NP O
disc NN I-NP O
disease NN I-NP O
of IN B-PP O
the DT B-NP O
lumbar NN I-NP O
spine NN I-NP O
at IN B-PP O
L4/L5 CD B-NP O
and CC O O
L5/S1 NNP B-NP O
. . O O
degenerative NN B-VP O
disc NN B-NP O
disease NN I-NP O
of IN B-PP O
the DT B-NP O
cervical JJ I-NP O
spine NN I-NP O
at IN B-PP O
C3/C4 PRP$ B-NP O
C4/C5 DT B-NP O
C5/C6 NNP I-NP O
. . O O
5 CD B-NP O
. . O O
Prior RB B-ADVP O
surgical JJ B-NP O
fusion NN I-NP O
of IN B-PP O
the DT B-NP O
cervical JJ I-NP O
spine NN I-NP O
and CC O O
laminectomies NNS B-NP O
are VBP B-VP O
incompletely RB I-VP O
evaluated VBN I-VP O
on IN B-PP O
the DT B-NP O
study NN I-NP O
due JJ B-ADJP O
to TO B-PP O
motion NN B-NP O
. . B-VP O
Please RB I-VP O
see VB I-VP O
prior JJ B-NP O
CT NNP I-NP O
report NN I-NP O
for IN B-PP O
the DT B-NP O
details NNS I-NP O
. . O O
6 CD B-NP O
. . O O
Mild NNP B-NP O
focal JJ I-NP O
kyphosis NN I-NP O
with IN B-PP O
height NN B-NP O
loss NN I-NP O
at IN B-PP O
T4 NNP B-NP O
appears VBZ B-VP O
subacute JJ O O
and CC O O
may MD B-VP O
be VB I-VP O
from IN B-PP O
prior JJ B-NP O
trauma NN I-NP O
. . O O
MRI NNP B-NP O
( -LRB- I-NP O
12/13 CD I-NP B-DATE
) -RRB- I-NP O
: : O O
MRI NNP B-NP O
THORACIC NNP I-NP O
AND CC O O
LUMBAR NNP B-NP O
SPINE NNP I-NP O
WITHOUT NNP I-NP O
AND CC O O
WITH NNP B-NP O
GADOLINIUM NNP I-NP O
History NN B-NP O
: : O O
History NN B-NP O
of IN B-PP O
previous JJ B-NP O
cord NN I-NP O
compression NN I-NP O
. . O O
Status NNPS B-VP O
post NN I-VP O
recent JJ O O
aorto-bifemoral JJ B-NP O
bypass NN I-NP O
. . O O
Now RB B-ADVP O
with IN B-PP O
sudden JJ B-NP O
onset NN I-NP O
of IN B-PP O
loss NN B-NP O
of IN B-PP O
lower RBR B-NP O
extremity NN B-NP O
motor NN I-NP O
function NN I-NP O
and CC I-NP O
sensation NN I-NP O
. . O O
Comparison NNP B-NP O
: : O O
MRI NNP B-NP O
spine NN I-NP O
dated VBN B-VP O
12/12/95 CD B-NP B-DATE
. . O O
Procedure NNP B-NP O
: : O O
Multiplanar NNP B-NP O
MR NNP I-NP O
imaging NN I-NP O
of IN B-PP O
the DT B-NP O
entire JJ I-NP O
spine NN I-NP O
was VBD I-NP O
performed VBN B-VP O
without IN B-PP O
and CC I-PP O
with IN B-PP O
Gadolinium NNP B-NP O
. . O O
Findings NNS B-NP O
: : O O
There EX B-NP O
is VBZ B-VP O
an DT B-NP O
old JJ I-NP O
compression NN I-NP O
fracture NN I-NP O
at IN B-PP O
T5 CD B-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
exaggeration NN B-NP O
of IN B-PP O
the DT B-NP O
normal JJ I-NP O
kyphosis NN I-NP O
at IN B-PP O
this DT B-NP O
level NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-SBAR O
marrow NN B-NP O
edema NN I-NP O
to TO B-VP O
suggest VB I-VP O
acute JJ B-NP O
fracture NN I-NP O
in IN B-PP O
the DT B-NP O
spine NN I-NP O
. . O O
There EX O O
is VBZ O O
straightening NN B-NP O
of IN B-PP O
the DT B-NP O
normal JJ I-NP O
lumbar NN I-NP O
lordosis NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
grade NN B-NP O
1 CD I-NP O
retrolisthesis NN B-NP O
of IN B-PP O
L4 NNP B-NP O
on IN B-PP O
L5 NNP B-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
degenerative JJ B-NP O
change NN I-NP O
in IN B-PP O
the DT O O
L4-5 . B-NP O
and CC I-NP O
L5-S1 JJ I-NP O
end NN I-NP O
plates NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
increased VBN I-VP O
T2 DT B-NP O
signal NN I-NP O
in IN B-PP O
the DT O O
L4-5 . B-NP O
and CC I-NP O
L5-S1 JJ I-NP O
discs NNS I-NP O
however RB B-ADVP O
the DT B-NP O
adjacent JJ I-NP O
endplates NNS I-NP O
are VBP B-VP O
well RB O O
preserved VBN B-VP O
, , O O
and CC O O
although IN B-SBAR O
infection NN B-NP O
cannot MD B-VP O
be VB I-VP O
completely RB B-ADJP O
excluded VBN I-ADJP O
, , O O
it PRP B-NP O
is VBZ B-VP O
considered VBN I-VP O
very RB B-ADJP O
unlikely JJ I-ADJP O
. . O O
There EX B-NP O
is VBZ B-VP O
a DT B-NP O
small JJ I-NP O
central JJ I-NP O
disc NN I-NP O
protrusion NN B-NP O
at IN B-PP O
T8-9. PRP$ B-NP O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
significant JJ B-NP O
canal NN I-NP O
stenosis NN I-NP O
in IN B-PP O
the DT B-NP O
thoracic NN I-NP O
or CC O O
lumbar NN B-NP O
spine NN I-NP O
. . O O
Examination NN B-NP O
of IN B-PP O
the DT B-NP O
cord NN I-NP O
demonstrates VBZ B-VP O
myelomalacia CD B-NP O
extending VBG B-VP O
from IN B-PP O
the DT B-NP O
T5 NNP I-NP O
level NN I-NP O
inferiorly RB B-ADVP O
. . O O
There EX B-NP O
is VBZ B-VP O
prominent JJ B-NP O
flow NN I-NP O
artifact NN I-NP O
in IN B-PP O
the DT O O
CSF NNP B-NP O
surrounding VBG B-VP O
the DT B-NP O
myelomalacic JJ I-NP O
cord NN I-NP O
. . O O
The DT B-NP O
conus NN I-NP O
is VBZ B-VP O
expanded VBN I-VP O
and CC O O
demonstrates VBZ O O
hyperintensity NN B-NP O
on IN B-PP O
T2 DT B-NP O
weighted JJ I-NP O
sequences NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no RB O O
associated VBN B-NP O
enhancement NN I-NP O
. . O O
No DT B-NP O
vascular JJ I-NP O
flow NN I-NP O
voids NNS I-NP O
are VBP B-VP O
identified VBN I-VP O
. . O O
There EX B-NP O
is VBZ B-VP O
a DT B-NP O
small JJ I-NP O
right JJ I-NP O
pleural JJ I-NP O
effusion NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
consolidation NN B-NP O
at IN B-PP O
the DT B-NP O
right JJ I-NP O
lung NN I-NP O
base NN I-NP O
. . O O
This DT B-NP O
may MD B-VP O
represent VB I-VP O
atelectasis NN B-NP O
or CC O O
infiltrate NN B-NP O
and CC I-NP O
correlation NN I-NP O
with IN B-PP O
chest NN B-NP O
x-ray NN I-NP O
is VBZ B-VP O
recommended VBN I-VP O
. . O O
IMPRESSION NN B-NP O
: : O O
Expansion NN B-NP O
and CC I-NP O
signal NN I-NP O
abnormality NN I-NP O
in IN B-PP O
the DT B-NP O
conus NN I-NP O
superimposed VBN B-VP O
on IN B-PP O
chronic JJ B-NP O
myelomalacia NN I-NP O
. . O O
The DT B-NP O
differential JJ I-NP O
diagnosis NN I-NP O
includes VBZ B-VP O
cord NN B-NP O
infarction NN B-NP O
, , O O
and CC O O
demyelinating VBG B-NP O
disease NN I-NP O
. . O O
Vascular JJ B-NP O
malformation NN I-NP O
and CC O O
neoplasm NN B-NP O
are VBP B-VP O
considered VBN I-VP O
less RBR B-ADJP O
likely JJ I-ADJP O
due JJ B-PP O
to TO I-PP O
the DT B-NP O
absence NN I-NP O
of IN B-PP O
vascular JJ B-NP O
flow NN B-NP O
voids NNS I-NP O
and CC O O
abnormal JJ B-NP O
enhancement NN I-NP O
. . O O
MRA NNP B-NP O
: : O O
MRA NNP B-NP O
of IN B-PP O
the DT B-NP O
aorta NN I-NP O
with IN B-PP O
runoff NN B-NP O
was VBD B-VP O
conducted VBN I-VP O
as IN B-PP O
per IN B-NP O
departmental NN I-NP O
protocol NN B-NP O
. . O O
FINDINGS NNS B-NP O
: : O O
Due JJ B-ADVP O
to TO B-PP O
the DT B-NP O
nature NN I-NP O
of IN B-PP O
MRI NNP B-NP O
imaging NN I-NP O
, , O O
dedicated VBN B-NP O
sequences NNS I-NP O
were VBD B-LST O
performed VBN B-VP O
to TO B-VP O
evaluate VB I-VP O
the DT B-NP O
vasculature NN I-NP O
. . O O
The DT B-NP O
remainder NN I-NP O
of IN B-PP O
the DT O O
abdominal JJ B-NP O
organs NNS I-NP O
are VBP B-VP O
not RB I-VP O
fully RB I-VP O
evaluated VBN I-VP O
and CC O O
if IN B-SBAR O
clinically RB O O
indicated VBD B-VP O
, , O O
directed VBD B-VP O
sequences NNS B-NP O
could MD B-VP O
be VB I-VP O
performed VBN I-VP O
. . O O
This DT B-NP O
was VBD B-VP O
a DT B-NP O
technically RB I-NP O
limited JJ I-NP O
study NN I-NP O
due JJ B-ADJP O
to TO B-PP O
suboptimal JJ B-NP O
contrast NN I-NP O
bolus NN B-NP O
and CC I-NP O
movement NN I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
was VBD B-VP O
agitated JJ B-ADJP O
and CC I-ADJP O
unable JJ I-ADJP O
to TO O O
cooperate VBP O O
. . O O
No DT B-NP O
evidence NN I-NP O
for IN B-PP O
an DT B-NP O
aortic JJ I-NP O
dissection NN I-NP O
is VBZ B-VP O
identified VBN I-VP O
. . O O
There EX B-NP O
is VBZ B-VP O
moderate JJ B-NP O
stenosis NN I-NP O
of IN B-PP O
the DT B-NP O
left JJ I-NP O
subclavian NN I-NP O
artery NN I-NP O
just RB O O
beyond IN B-PP O
its PRP$ B-NP O
origin NN I-NP O
. . O O
The DT B-NP O
celiac JJ I-NP O
trunk NN I-NP O
is VBZ B-VP O
patent NN B-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
mild/moderate JJ B-NP O
stenosis NN I-NP O
just RB B-ADVP O
beyond IN B-PP O
the DT B-NP O
origin NN I-NP O
of IN B-PP O
the DT O O
superior JJ B-NP O
mesenteric JJ I-NP O
artery NN I-NP O
. . O O
The DT B-NP O
renal JJ I-NP O
arteries NNS I-NP O
cannot MD B-VP O
be VB I-VP O
assessed VBN I-VP O
on IN B-PP O
this DT B-NP O
study NN I-NP O
. . O O
IMPRESSION NN B-NP O
: : O O
1 LS O O
. . B-NP O
Limited NNP I-NP O
study NN I-NP O
due JJ B-ADVP O
to TO B-PP O
technical JJ B-NP O
factors NNS I-NP O
and CC O O
patient JJ B-NP O
movement NN I-NP O
however RB B-ADVP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
an DT B-NP O
aortic JJ I-NP O
dissection NN I-NP O
is VBZ B-VP O
identified VBN I-VP O
. . O O
A DT O O
repeat NN B-NP O
MRI NNP I-NP O
with IN B-PP O
better JJR B-NP O
contrast NN I-NP O
bolus NN I-NP O
and CC I-NP O
sedation NN I-NP O
may MD B-VP O
be VB I-VP O
obtained VBN I-VP O
if IN B-SBAR O
clinically RB B-ADVP O
indicated VBN B-VP O
. . O O
2. . B-NP O
Moderate NNP I-NP O
stenosis NN I-NP O
is VBZ B-VP O
noted VBN I-VP O
just RB B-ADJP O
distal JJ I-ADJP O
to TO B-PP O
the DT B-NP O
origin NN I-NP O
of IN B-PP O
the DT O O
left VBN B-NP O
subclavian JJ I-NP O
artery NN I-NP O
. . O O
3. DT B-NP O
Mild/moderate NNP I-NP O
stenosis NN I-NP O
just RB B-ADVP O
beyond IN B-PP O
the DT B-NP O
origin NN I-NP O
of IN B-PP O
the DT B-NP O
SMA. NNP I-NP O
CT NN B-NP O
Spine NNP I-NP O
( -LRB- I-NP O
12/13 CD I-NP B-DATE
) -RRB- I-NP O
: : O O
report NN B-NP O
pending VBG I-NP O
Assessment/Plan NNP B-NP O
: : O O
74 CD B-NP B-AGE
y/o NN I-NP O
vasculopath IN B-PP O
presenting VBG B-VP O
with IN B-PP O
new JJ B-NP O
neurological JJ I-NP O
deficits NNS I-NP O
, , O O
abdominal JJ B-NP O
pain NN I-NP O
, , O O
UGI NNP B-NP O
bleed VBD B-VP O
, , O O
progressive JJ B-NP O
renal JJ I-NP O
failure NN I-NP O
, , O O
initially RB B-ADVP O
worrisome JJ B-ADJP O
for IN B-PP O
aortic JJ B-NP O
dissection NN I-NP O
. . O O
Unifying JJ B-NP O
diagnosis NN I-NP O
remains VBZ B-VP O
obscure JJ B-ADJP O
- : O O
? . B-VP O
occlusive JJ B-NP O
atheroemboli NNS I-NP O
vs IN B-PP O
epidural JJ B-NP O
hematoma NN I-NP O
. . O O
1.Paraplegia CD B-NP O
: : O O
Has VBZ B-VP O
baseline JJ B-NP O
deficits NNS I-NP O
( -LRB- I-NP O
wheelchair NN I-NP O
bound VBN B-VP O
) -RRB- B-NP O
, , O O
but CC O O
unclear JJ B-ADJP O
how WRB B-ADVP O
they PRP B-NP O
compare VBP B-VP O
to TO B-PP O
current JJ B-NP O
exam--> NN I-NP O
level NN I-NP O
at IN B-PP O
T5/T6 NNP B-NP O
. . I-NP O
First NNP I-NP O
MRI NNP I-NP O
showed VBD B-VP O
low JJ B-NP O
T2 NN I-NP O
signal NN I-NP O
collections NNS I-NP O
from IN B-PP O
T6--> JJ B-NP O
L1 NNP I-NP O
with IN B-PP O
displacement NN B-NP O
of IN B-PP O
thoracic JJ B-NP O
cord NN I-NP O
anteriorly RB B-ADVP O
from IN B-PP O
T7-T10 CD B-NP O
; : O O
no DT B-NP O
cord NN I-NP O
compression NN I-NP O
on IN B-PP O
repeat NN B-NP O
study NN I-NP O
, , O O
however RB B-ADVP O
ddx , O O
still RB B-ADVP O
includes VBZ B-VP O
cord NN B-NP O
infarction NN I-NP O
vs IN B-PP O
demyelinating VBG B-VP O
disease NN B-NP O
-neurology NN B-NP O
and CC I-NP O
neurosurgery NN I-NP O
following VBG I-NP O
-awaiting JJ B-NP O
spinal JJ I-NP O
CT NNP I-NP O
to TO B-VP O
evaluate VB I-VP O
for IN B-PP O
epidural JJ B-NP O
hematoma NN I-NP O
-in NN B-NP O
addition NN I-NP O
, , O O
neurology NN B-NP O
has VBZ B-VP O
asked VBN I-VP O
for IN B-PP O
MRI NNP B-NP O
with IN B-PP O
line NN B-NP O
diffusion NN I-NP O
and CC O O
MPGR NNP B-NP O
sequence NN I-NP O
to TO B-VP O
r/o VB I-VP O
infarction NN B-NP O
, , O O
which WDT B-NP O
has VBZ B-VP O
been VBN I-VP O
ordered VBN I-VP O
2.Respiratory JJ B-NP O
status NN I-NP O
: : O O
Acute NNP B-NP O
desaturation NN I-NP O
2/2 CD B-NP O
methemoglobinemia NN I-NP O
as IN B-PP O
consequence NN B-NP O
of IN B-PP O
topical JJ B-NP O
anesthetic JJ I-NP O
; : O O
s/p RP B-NP O
methylene NN I-NP O
blue JJ I-NP O
( -LRB- O O
80 CD B-NP O
mg JJ I-NP O
x NN I-NP O
1 CD I-NP O
, , I-NP O
40 CD I-NP O
mg NN I-NP O
x NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
with IN B-PP O
resolution NN B-NP O
of IN B-PP O
methemoglobin NN B-NP O
from IN B-PP O
35 CD B-NP O
% NN I-NP O
to TO B-PP O
1 CD B-NP O
% NN I-NP O
, , O O
now RB B-ADVP O
on IN B-PP O
4L JJ B-NP O
NC NNP I-NP O
sats NNS I-NP O
are VBP B-VP O
95 CD B-NP O
% NN I-NP O
. . O O
-cont JJ B-NP O
O2 NNP I-NP O
and CC I-NP O
wean JJ I-NP O
as IN I-NP O
tolerated VBN I-NP O
-enter JJ B-NP O
hurricane NN I-NP O
spray NN I-NP O
as RB B-ADVP O
allergy RB I-ADVP O
3.Renal JJ B-NP O
failure NN I-NP O
: : O O
Possibilities NNS B-NP O
raised VBN B-VP O
include VBP B-VP O
cholesterol NN B-NP O
emboli NNS I-NP O
from IN B-PP O
recent JJ B-NP O
interventions NNS I-NP O
, , O O
relative JJ B-NP O
hypoperfusion NN I-NP O
with IN B-PP O
normalization NN B-NP O
of IN B-PP O
blood NN B-NP O
pressure NN I-NP O
. . O O
No DT B-NP O
contrast NN I-NP O
at IN B-PP O
OSH NNP B-NP O
; : O O
urine JJ B-NP O
eos NNS I-NP O
negative JJ I-NP O
; : O O
FENa= NNP B-NP O
0.94 CD B-NP O
% NN I-NP O
; : O O
Cr NNP B-NP O
3.1 CD B-NP O
2.5 CD I-NP O
today NN I-NP O
-follow JJ B-NP O
Cr NNP I-NP O
4.Abdominal JJ B-NP O
pain NN I-NP O
: : O O
mild-moderate JJ B-NP O
stenosis NN I-NP O
just RB B-ADVP O
beyond IN B-PP O
origin NN B-NP O
of IN B-PP O
SMA NNP B-NP O
seen VBN B-VP O
on IN B-PP O
MRA NNP B-NP O
; : O O
considered VBN B-NP O
mesenteric JJ I-NP O
ischemia NN I-NP O
a/w RB B-NP O
low JJ I-NP O
flow NN I-NP O
state NN I-NP O
. . O O
However RB B-ADVP O
, , O O
lactic JJ B-NP O
acid NN I-NP O
1.3 CD I-NP O
, , O O
and CC O O
pH VB B-VP O
wnl NN B-NP O
- : O O
will MD B-VP O
follow VB I-VP O
acid/base NN B-NP O
status NN I-NP O
, , O O
lytes NNS B-NP O
, , O O
pain NN B-NP O
5.GI JJ B-NP O
bleed NN I-NP O
: : O O
coffee NN B-NP O
ground NN I-NP O
emesis-- , O O
unclear JJ B-ADJP O
if IN B-SBAR O
this DT B-NP O
reflects VBZ B-VP O
enteric JJ B-NP O
ischemia NN I-NP O
vs. IN B-PP O
ulcer NN B-NP O
in IN B-PP O
setting NN B-NP O
of IN B-PP O
plavix NN B-NP O
, , O O
ASA NNP B-NP O
-GI JJ B-NP O
team NN I-NP O
following VBG I-NP O
, , O O
planning VBG B-VP O
on IN B-PP O
probable JJ B-NP O
EGD NNP I-NP O
12/15 CD O B-DATE
-holding JJ B-NP O
ASA NNP I-NP O
, , O O
plavix NN B-NP O
for IN B-PP O
now RB B-NP O
6.Cards NNS B-NP O
- : O O
ISCHEMIA NNP B-NP O
: : O O
troponin FW B-NP O
0.14 CD I-NP O
on IN B-PP O
admission NN B-NP O
, , O O
but CC O O
subsequently RB B-ADVP O
all DT B-NP O
wnl NN I-NP O
, , O O
likely JJ B-NP O
troponin FW I-NP O
leak FW I-NP O
in IN B-PP O
setting VBG B-VP O
of IN B-PP O
GIB NNP B-NP O
prior RB B-ADVP O
to TO B-PP O
admission NN B-NP O
- : O O
off IN B-PP O
ASA NNP B-NP O
, , O O
plavix NN B-NP O
in IN B-PP O
context NN B-NP O
of IN B-PP O
suspected JJ B-NP O
UGIB NNP I-NP O
- : O O
maintain VBP B-VP O
Hct NNP B-NP O
> NNP I-NP O
30 CD O O
- : O O
cont NN B-NP O
lopressor NN I-NP O
PUMP NNP B-NP O
: : O O
TEE NN B-NP O
with IN B-PP O
no DT B-NP O
dissection NN I-NP O
; : O O
TTE NNP B-NP O
with IN B-PP O
EF NNP B-NP O
54 CD I-NP O
% NN I-NP O
, , O O
no DT B-NP O
SWMA NNP I-NP O
, , O O
no DT B-NP O
tamponade NN I-NP O
- : O O
metoprolol NN B-NP O
, , O O
isordil/hydral JJ B-NP O
goal NN I-NP O
SBP NNP B-NP O
140-150 CD I-NP O
RHYTHM NNP B-NP O
- : O O
NSR NN B-NP O
7.Diabetes VBZ B-VP O
mellitus JJ B-ADJP O
: : O O
sliding VBG B-VP O
scale NN B-NP O
QID . O O
- : O O
will MD B-VP O
convert VB I-VP O
to TO I-VP O
NPH VB I-VP O
once RB B-NP O
requirements NNS I-NP O
determined VBN O O
8.FEN NN B-NP O
: : O O
resume VB B-VP O
diet NN B-NP O
as IN B-PP O
EGD NNP B-NP O
likely JJ I-NP O
on IN B-PP O
Monday NNP B-NP B-DATE
9.Prophylaxis NNP B-NP O
: : O O
cont NN B-NP O
nexium JJ I-NP O
, , O O
holding VBG B-VP O
fragmin NN B-NP O
given VBN I-NP O
concern NN I-NP O
for IN B-PP O
bleeding VBG O O
10.Dispo CD B-NP O
: : O O
Will MD B-VP O
need VB I-VP O
rehab NN B-NP O
once RB B-ADJP O
stable JJ I-ADJP O
; : O O
PT/OT NNP O O
11.CODE CD B-NP O
: : O O
FULL NNP B-NP O
Karen NNP B-NP B-DOCTOR
V. NNP I-NP I-DOCTOR
Barajas NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Internal NNP B-NP O
Medicine NNP I-NP O
Intern NNP I-NP O
18412 CD O B-PHONE
