Record NNP B-NP O
date NN I-NP O
: : O O
2092-08-16 CD O B-DATE
Eye NNP B-NP B-HOSPITAL
Specialties NNP I-NP I-HOSPITAL
Intern NNP I-NP O
Admission NNP I-NP O
H NNP I-NP O
& CC I-NP O
P NNP I-NP O
Patient NNP B-NP O
Name NNP I-NP O
: : O O
Wood NNP B-NP I-PATIENT
, , O I-PATIENT
Cade NNP B-NP I-PATIENT
MR# NNP B-NP O
6691247 CD I-NP B-MEDICALRECORD
Location NN B-NP O
: : O O
BIG99 CD O O
PCP NNP B-NP O
: : O O
Dr. NNP B-NP O
Otto NNP I-NP B-DOCTOR
Suzanne NNP I-NP I-DOCTOR
Date NNP B-NP O
of IN B-PP O
Admission NNP B-NP O
: : O O
8/15/92 CD O B-DATE
ID/CC NNP B-NP O
: : O O
59 CD B-NP B-AGE
y NN I-NP O
.o NN I-NP O
. . B-NP O
male NN I-NP O
with IN B-PP O
SOB NNP B-NP O
during IN B-PP O
a DT B-NP O
CT NN I-NP O
on IN B-PP O
the DT B-NP O
day NN I-NP O
of IN B-PP O
admission NN B-NP O
HPI NNP B-NP O
: : O O
Pt NNP B-NP O
. . O O
is VBZ B-VP O
a DT B-NP O
59 CD I-NP B-AGE
y NN I-NP O
.o NN I-NP O
. . B-NP O
male NN I-NP O
with IN B-PP O
DLBCL NNP B-NP O
dx'ed VBD B-VP O
with IN B-PP O
stage NN B-NP O
4 CD I-NP O
DLBCL NN I-NP O
in IN B-PP O
11/07 CD B-NP B-DATE
, , O O
S/P NNP B-NP O
CHOP-R NNP I-NP O
( -LRB- I-NP O
finished VBD B-VP O
3/08 CD B-NP B-DATE
) -RRB- I-NP O
, , I-NP O
HTN NNP I-NP O
, , I-NP O
GERD NNP I-NP O
, , I-NP O
and CC I-NP O
anemia NN I-NP O
who WP B-NP O
p/w VBD B-VP O
acute JJ B-NP O
onset NN I-NP O
of IN B-PP O
SOB NNP B-NP O
while IN B-LST O
lying VBG B-VP O
down RP B-PRT O
during IN B-PP O
a DT B-NP O
f/u NN I-NP O
staging NN I-NP O
non-contrast JJ I-NP O
CT NN I-NP O
on IN B-PP O
the DT B-NP O
day NN I-NP O
of IN B-PP O
admission NN B-NP O
. . O O
Pt NNP O O
. . O O
notes NNS B-VP O
a DT B-NP O
5lbs JJ I-NP O
weight NN I-NP O
gain NN I-NP O
over IN B-PP O
the DT B-NP O
past JJ I-NP O
week NN I-NP O
. . O O
He PRP B-NP O
also RB B-ADVP O
reports VBZ B-VP O
a DT B-NP O
1-2 JJ I-NP O
week NN I-NP O
h/o IN B-PP O
increasing VBG B-VP O
DOE NNP B-NP O
when WRB B-ADVP O
he PRP B-NP O
performs VBZ B-VP O
his PRP$ B-NP O
household NN I-NP O
chores NNS I-NP O
or CC O O
working VBG B-VP O
in IN B-PP O
his PRP$ B-NP O
backyard NN I-NP O
. . O O
At IN B-PP O
his PRP$ B-NP O
baseline NN I-NP O
, , O O
can MD B-VP O
can VB I-VP O
walk VB I-VP O
of IN B-PP O
a DT B-NP O
mile NN I-NP O
w/o IN B-PP O
dyspnea NN B-NP O
or CC O O
CP. NNP B-NP O
4 CD I-NP O
days NNS I-NP O
PTA NNP I-NP O
, , O O
he PRP B-NP O
had VBD B-VP O
to TO I-VP O
take VB I-VP O
it PRP B-NP O
easy JJ B-ADJP O
during IN B-PP O
a DT B-NP O
picnic NN I-NP O
as IN B-SBAR O
he PRP B-NP O
would MD B-VP O
easily RB I-VP O
develop VB I-VP O
DOE VB I-VP O
with IN B-PP O
minimal JJ B-NP O
exertion NN I-NP O
. . O O
2days VBD B-VP O
PTA NNP B-NP O
, , O O
pt NN B-NP O
. . O O
experienced VBD B-VP O
coughing VBG I-VP O
bouts NNS B-NP O
when WRB B-ADVP O
he PRP B-NP O
tried VBD B-VP O
to TO I-VP O
lie VB I-VP O
down RP B-PRT O
for IN B-PP O
sleep. DT B-NP O
The DT B-NP O
patient NN I-NP O
acutely RB B-VP O
developed VBD I-VP O
SOB NNP B-NP O
after IN B-PP O
lying VBG B-VP O
down RP B-PRT O
for IN B-PP O
a DT B-NP O
few JJ I-NP O
minutes NNS I-NP O
during IN B-PP O
his PRP$ B-NP O
CT. NNP I-NP O
He PRP B-NP O
felt VBD B-VP O
1/10 CD B-NP O
CP CD I-NP O
during IN B-PP O
this DT B-NP O
episode NN I-NP O
located VBN B-VP O
in IN B-PP O
the DT B-NP O
R NN I-NP O
middle NN I-NP O
sub-sternum NN I-NP O
. . O O
The DT B-NP O
pain NN I-NP O
lasted VBD B-VP O
for IN B-PP O
approximately RB B-NP O
10 CD I-NP O
min NN I-NP O
, , O O
dull JJ B-ADJP O
in IN B-PP O
quality NN B-NP O
, , O O
did VBD B-VP O
not RB I-VP O
radiate NN I-VP O
, , O O
did VBD B-VP O
not RB I-VP O
change VB I-VP O
with IN B-PP O
position NN B-NP O
, , O O
relieved JJ B-ADJP O
after IN B-PP O
given VBN B-NP O
NTG NNP I-NP O
in IN B-PP O
the DT B-NP O
ED. NNP I-NP O
He PRP B-NP O
experienced VBD B-VP O
a DT B-NP O
similar JJ I-NP O
CP CD I-NP O
during IN B-PP O
an DT B-NP O
administration NN I-NP O
of IN B-PP O
his PRP$ B-NP O
chemo NN I-NP O
several JJ I-NP O
months NNS I-NP O
PTA. '' O O
This DT B-NP O
CP CD I-NP O
was VBD B-VP O
determined VBN I-VP O
not RB I-VP O
be VB I-VP O
be VB I-VP O
cardiogenic JJ B-ADJP O
. . O O
+ JJ B-NP O
diaphoresis NN I-NP O
, , O O
- : O O
N/V NN B-NP O
, , O O
- : O O
lightheadedness NN B-NP O
, , O O
- : O O
palpitations NNS B-NP O
. . O O
He PRP B-NP O
reports VBZ B-VP O
eating VBG I-VP O
a DT B-NP O
lot NN I-NP O
of IN B-PP O
salty NN B-NP O
foods NNS I-NP O
. . O O
- : O O
recent JJ B-NP O
URI/sick JJ I-NP O
contacts NNS I-NP O
. . O O
Onc NN B-NP O
Hx NN I-NP O
- : O O
59 CD B-NP B-AGE
yo CD I-NP O
man NN I-NP O
with IN B-PP O
h/o JJ B-NP O
1y JJ I-NP O
microcytic JJ I-NP O
anemia NN I-NP O
( -LRB- O O
low JJ B-NP O
Fe NNP I-NP O
, , O O
low JJ B-NP O
ferritin NN I-NP O
) -RRB- O O
Found NNP B-NP O
to TO B-VP O
have VB I-VP O
ascending VBG B-NP O
colon NN I-NP O
adenomatous JJ I-NP O
polyp NN I-NP O
persistent NN I-NP O
despite IN B-PP O
several JJ B-NP O
colonoscopic JJ I-NP O
resections NNS I-NP O
. . O O
Also RB B-VP O
noted VBD I-VP O
anorexia DT B-NP O
, , I-NP O
fatigue NN I-NP O
, , I-NP O
bloody JJ I-NP O
stools NNS I-NP O
. . O O
11/8 CD B-NP I-DATE
/91 CD I-NP I-DATE
admitted VBN B-VP O
to TO B-PP O
SMI NNP B-NP B-HOSPITAL
with IN B-PP O
sudden JJ B-NP O
RLQ JJ I-NP O
pain NN I-NP O
. . O O
Ab CD B-NP O
CT NNP I-NP O
notable JJ I-NP O
for IN B-PP O
large JJ B-NP O
mass NN I-NP O
arising VBG B-VP O
out IN B-PP O
of IN B-PP O
the DT B-NP O
small JJ I-NP O
bowel NN I-NP O
with IN B-PP O
liver NN B-NP O
lesions NNS I-NP O
. . O O
11/11/91 CD B-NP B-DATE
liver NN I-NP O
bx NN I-NP O
: : O O
DLBCL. . O O
11/16/91 CD B-NP B-DATE
seen VBN B-VP O
in IN B-PP O
clinic NN B-NP O
. . O O
Discussed VBD B-VP O
diagnosis NN B-NP O
. . O O
Arranged JJ B-NP O
staging NN I-NP O
. . O O
Anemic NNP B-NP O
. . O O
11/28/91 CD B-NP B-DATE
BM NNP I-NP O
bx , I-NP O
-> JJ I-NP O
negative JJ I-NP O
for IN B-PP O
BM NNP B-NP O
involvement NN I-NP O
, , O O
PAC NNP B-NP O
placement NN I-NP O
11/30/91 CD B-NP B-DATE
cycle NN I-NP O
# # I-NP O
1 CD I-NP O
CHOP-R. NNP I-NP O
Mild NNP I-NP O
transfusion NN I-NP O
reaction NN I-NP O
with IN B-PP O
PRBC NNP B-NP O
12/02/91 CD B-NP B-DATE
PRBC NNP I-NP O
successfully RB B-VP O
given VBN I-VP O
. . B-NP O
Neulasta NNP I-NP O
. . O O
12/7/91 CD B-NP B-DATE
In IN B-PP O
f/u NN B-NP O
, , O O
noted VBD B-VP O
to TO I-VP O
be VB I-VP O
neutropenic JJ B-ADJP O
despite IN B-PP O
Neulasta NNP B-NP O
and CC B-PP O
with IN B-PP O
oral JJ B-NP O
candidiasis NN I-NP O
. . O O
Tx DT B-NP O
diflucan JJ I-NP O
, , I-NP O
prophylactic JJ I-NP O
Levoquin NNP I-NP O
. . I-NP O
Anemic NNP I-NP O
-> NNP I-NP O
2U NNP I-NP O
PRBC NNP I-NP O
. . O O
12/21/91 CD B-NP B-DATE
cycle NN I-NP O
# # I-NP O
2 CD I-NP O
CHOP-R JJ I-NP O
, , I-NP O
c/b JJ I-NP O
episode NN I-NP O
non-cardiac JJ I-NP O
chest NN I-NP O
pain NN I-NP O
completed VBN B-NP O
CHOP/R NN I-NP O
x NN I-NP O
6 CD B-NP O
cycles NNS I-NP O
in IN B-PP O
3/08 CD B-NP B-DATE
ED VBN B-NP O
course NN I-NP O
: : O O
VS NNP B-NP O
: : O O
HR=78 CD B-NP O
BP=178/108 CD I-NP O
Tc-96.6 . O O
RR=28 IN B-PP O
SaO2=96 CD B-NP O
% NN I-NP O
RA NNP I-NP O
Given VBN B-VP O
ASA NNP B-NP O
325 CD I-NP O
mg NN I-NP O
, , O O
NTG NNP B-NP O
X1 NNP I-NP O
, , O O
Lasix NNP B-NP O
20mg CD I-NP O
IV NNP I-NP O
X1 NNP I-NP O
, , O O
500 CD B-NP O
ccNS. . O O
PMHx NNP B-NP O
: : O O
1 CD B-NP O
. . O O
Stage NNP B-NP O
IV NNP I-NP O
DLBCL NNP I-NP O
11/07 CD I-NP B-DATE
. . O O
Likely RB B-ADVP O
intestinal JJ B-NP O
origin NN I-NP O
Involvement NN I-NP O
of IN B-PP O
liver NN B-NP O
; : O O
no DT B-NP O
bone NN I-NP O
marrow NN I-NP O
or CC O O
thoracic JJ B-NP O
involvement NN I-NP O
. . O O
S/p '' O O
6 CD B-NP O
cycles NNS I-NP O
CHOP-R NNP B-NP O
chemotherapy NN I-NP O
. . O O
Last JJ B-NP O
cycle NN I-NP O
3/14/92 NN I-NP B-DATE
. . O O
Repeat NN B-VP O
CT NNP B-NP O
1/27/92 CD I-NP B-DATE
showed VBD B-VP O
RLQ JJ B-NP O
mass NN I-NP O
reduced VBN B-VP O
in IN B-PP O
size NN B-NP O
to TO B-PP O
9x5 CD B-NP O
cm NN I-NP O
. . O O
CT '' O O
4/04/92 CD B-NP B-DATE
showed VBD B-VP O
considerable JJ B-NP O
inflammatory NN I-NP O
reaction NN I-NP O
in IN B-PP O
the DT B-NP O
right NN I-NP O
lower JJR B-NP O
quadrant NN I-NP O
engulfing VBG I-NP O
loops NNS I-NP O
of IN B-PP O
small JJ B-NP O
bowel NN I-NP O
c/w VBD B-VP O
a DT B-NP O
focal JJ I-NP O
small JJ I-NP O
bowel NN I-NP O
perforation NN I-NP O
. . O O
2. DT B-NP O
Microcytic NNP I-NP O
anemia NN I-NP O
diagnosed VBD B-VP O
3/07 CD B-NP B-DATE
. . O O
3. . B-NP O
Diverticulosis NN I-NP O
4 CD B-LST O
. . O O
Colonic NNP B-NP O
polyps NNS I-NP O
- : O O
tubulovillous JJ B-NP O
adenoma NN I-NP O
resected VBN B-VP O
10/8 CD B-NP I-DATE
7 CD I-NP I-DATE
. . O O
Repeat NN B-VP O
excisions NNS B-NP O
06 CD I-NP B-DATE
, , I-NP O
12/06 CD I-NP B-DATE
. . O O
Cecal NNP B-NP O
polyp NN I-NP O
- : O O
tubular JJ B-NP O
adenoma NN I-NP O
resected VBD B-VP O
3/07 CD B-NP B-DATE
. . O O
Last JJ B-NP O
colonoscopy NN I-NP O
10/07 CD I-NP B-DATE
with IN B-PP O
resection NN B-NP O
of IN B-PP O
10x3 CD B-NP O
mm CD I-NP O
polyp NN I-NP O
in IN B-PP O
ascending VBG B-NP O
colon NN I-NP O
. . O O
5 CD B-NP O
. . O O
GERD NNP O O
- : O O
endoscopy VBP B-VP O
3/07 CD B-NP B-DATE
revealed VBD B-VP O
3 CD B-NP O
linear NN I-NP O
esophageal NN I-NP O
ulcerations NNS I-NP O
from IN B-PP O
30cm JJ B-NP O
to TO B-PP O
40 CD B-NP O
cm NN I-NP O
with IN B-PP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
gastric JJ B-NP O
or CC I-NP O
duodenal JJ I-NP O
ulceration NN I-NP O
. . O O
6 CD B-LST O
. . O O
HTN '' O O
7. . B-NP O
Hyperlipidemia-Lipitor NNP I-NP O
d/c'ed VBD B-VP O
prior RB B-ADVP O
to TO B-PP O
chemotherapy NN B-NP O
regimen NNS I-NP O
. . O O
Allergies NNP B-NP O
: : O O
Demerol NNP B-NP O
- : O O
syncope NN B-NP O
Fluconazole JJ O O
- : O O
GI NNS B-NP O
upset VBN O O
Medications NNS B-NP O
at IN B-PP O
home NN B-NP O
: : O O
Omeprazole NNP B-NP O
- : O O
20mg CD B-NP O
QHS NNS I-NP O
Lisinopril NNP B-NP O
40 CD I-NP O
mg NN I-NP O
PO NN I-NP O
QD . O O
Lopressor NN B-NP O
50 CD I-NP O
mg NN I-NP O
PO NNP I-NP O
BID NNP I-NP O
PSHx NNP B-NP O
: : O O
6/14/92 CD B-NP B-DATE
Resection NNP I-NP O
of IN B-PP O
the DT B-NP O
terminal NN I-NP O
ileum NN I-NP O
and CC O O
ascending VBG B-VP O
colon NN B-NP O
for IN B-PP O
partial JJ B-NP O
obstruction NN I-NP O
at IN B-PP O
the DT B-NP O
terminal NN I-NP O
ileum NN I-NP O
. . O O
Pathology NN B-NP O
showed VBD B-VP O
small JJ B-NP O
intestine NN I-NP O
with IN B-PP O
abscess NN B-NP O
formation NN I-NP O
, , O O
foreign JJ B-NP O
body NN I-NP O
giant NN I-NP O
cell NN I-NP O
reaction NN I-NP O
, , O O
marked VBD B-VP O
transmural JJ B-NP O
fibrosis NN I-NP O
with IN B-PP O
foamy JJ B-NP O
histiocytes NNS I-NP O
and CC O O
acute JJ B-NP O
and CC I-NP O
organized VBN I-NP O
serositis NN I-NP O
consistent JJ I-NP O
with IN B-PP O
perforated JJ B-NP O
viscus NN I-NP O
. . O O
There EX B-NP O
was VBD B-VP O
also RB B-NP O
tubular JJ I-NP O
adenoma NN I-NP O
measuring VBG B-VP O
0.4 CD B-NP O
cm NN I-NP O
in IN B-PP O
the DT B-NP O
ascending VBG I-NP O
colon NN I-NP O
- : O O
completely RB B-VP O
excised VBN I-VP O
. . B-NP O
, , O O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
malignancy NN B-NP O
. . O O
SHx NNP B-NP O
: : O O
Pt NNP B-NP O
. . O O
is VBZ B-VP O
single JJ B-ADJP O
, , O O
lives NNS B-NP O
by IN B-PP O
himself PRP B-NP O
. . O O
He PRP B-NP O
formerly RB B-ADVP O
worked VBD B-VP O
in IN B-PP O
goods NNS B-NP B-PROFESSION
production NN I-NP I-PROFESSION
but CC O O
was VBD B-VP O
laid VBN I-VP O
off RP B-NP O
1 CD I-NP O
yr NN I-NP O
. . O O
PTA. '' O O
He PRP B-NP O
has VBZ B-VP O
a DT B-NP O
supportive JJ I-NP O
network NN I-NP O
of IN B-PP O
family NN B-NP O
and CC I-NP O
friends NNS I-NP O
. . O O
He PRP B-NP O
does VBZ B-VP O
not RB I-VP O
smoke VB I-VP O
, , O O
has VBZ B-VP O
1 CD B-NP O
alcoholic JJ I-NP O
beverage NN I-NP O
every DT B-NP O
few JJ I-NP O
months NNS I-NP O
, , O O
and CC O O
denies VBZ B-VP O
illicit JJ B-NP O
drug NN I-NP O
use NN I-NP O
. . O O
FHx NNP B-NP O
: : O O
Father- NNP B-NP O
DM NNP I-NP O
, , O O
Alzheimer NNP B-NP O
's POS B-LST O
Mother NNP B-NP O
- : O O
DM NNP B-NP O
, , O O
HTN . O O
ROS NNP B-NP O
: : O O
No DT B-NP O
F/C/NS. NNP I-NP O
+ NNP I-NP O
5lbs VBZ B-VP O
weight NN B-NP O
gain NN I-NP O
in IN B-PP O
2 CD B-NP O
weeks NNS I-NP O
. . O O
No DT B-NP O
hemoptysis/wheezing/sore NN I-NP O
throat/rash NN I-NP O
. . O O
No DT B-NP O
N/V/D/hematochezia/melena NNP I-NP O
. . O O
No DT B-NP O
delta NN I-NP O
MS/LOC. . B-PP O
No DT B-NP O
slurring NN I-NP O
of IN B-PP O
speech NN B-NP O
, , O O
unilateral JJ B-NP O
weakness NN I-NP O
. . O O
No DT B-NP O
dysuria NN I-NP O
. . O O
- : O O
polyuria/polydypsia NN B-NP O
, , O O
heat/cold NN B-NP O
intolerance NN I-NP O
. . O O
Exam NNP B-NP O
: : O O
VS NNP B-NP O
: : O O
HR=65 CD B-NP O
BP=157/98 CD I-NP O
RR=20 IN B-PP O
SaO2=95 CD B-NP O
% NN I-NP O
RA NNP I-NP O
General NNP B-NP O
: : O O
NAD NN B-NP O
HEENT NNP B-NP O
: : O O
NC/AT NN B-NP O
, , O O
PERRL NNP B-NP O
, , O O
. . B-NP O
EOMI NNP I-NP O
, , O O
Neck NNP B-NP O
: : O O
Supple NN B-NP O
, , O O
full JJ B-NP O
ROM NNP I-NP O
, , O O
no DT B-NP O
LAD NN I-NP O
, , O O
no DT B-NP O
thyromegaly NN I-NP O
, , O O
Chest NNP B-NP O
: : O O
CTA&P NNP B-NP O
bilaterally RB B-ADVP O
, , O O
no DT B-NP O
wheezes NNS I-NP O
, , O O
crackles NNS B-NP O
, , O O
or CC O O
ronchi NN B-NP O
CVS NNP B-NP O
: : O O
RRR NNP B-NP O
nl , O O
S1 NNP B-NP O
S2 NNP I-NP O
, , O O
no DT B-NP O
m/r/g NN I-NP O
, , O O
JVP= NNP B-NP O
7 CD I-NP O
, , I-NP O
2+ CD I-NP O
brisk JJ I-NP O
carotids NNS I-NP O
w/o . O O
bruits NNS B-NP O
Abd NNP B-NP O
: : B-VP O
soft JJ B-ADJP O
, , O O
NT/ND NNP B-NP O
, , O O
nl JJ B-NP O
BS NNP I-NP O
, , O O
no DT B-NP O
HSM NNP I-NP O
Extr NNP B-NP O
: : O O
WWP NNP B-NP O
, , O O
no DT B-NP O
c/c/e NN I-NP O
2+ IN B-PP O
DP/PT NNP B-NP O
bilaterally . O O
Neuro NNP B-NP O
: : O O
A+OX3 NNP B-NP O
, , O O
MS NNP B-NP O
nl NN I-NP O
, , O O
CN NNP B-NP O
II NNP I-NP O
through IN B-PP O
XII NNP B-NP O
intact JJ I-NP O
, , O O
Motor NNP B-NP O
5/5 VBD B-VP O
UE NNP B-NP O
and CC I-NP O
LE JJ I-NP O
, , O O
Sensory NNP B-NP O
intact JJ I-NP O
. . O O
DTR NNP B-NP O
's POS B-NP O
2+ JJ I-NP O
and CC I-NP O
symmetric JJ I-NP O
in IN B-PP O
bilat JJ B-NP O
LE JJ I-NP O
and CC I-NP O
UE. NNP I-NP O
Toes . B-VP O
down RP I-VP O
bilaterally RB B-ADVP O
. . O O
F PRP B-ADJP O
to TO B-PP O
N NNP B-NP O
nl NN I-NP O
, , O O
RAM NNP B-NP O
nl NN I-NP O
. . O O
Skin NNP B-NP O
: : O O
-rash NN B-NP O
DATA NNP B-NP O
: : O O
08/15/92 CD O B-DATE
12:19 CD O O
NA NNP B-NP O
138 CD I-NP O
K NNP B-NP O
3.8 CD I-NP O
CL NN B-NP O
108 CD I-NP O
CO2 NN B-NP O
25.6 CD I-NP O
BUN NNP B-NP O
16 CD I-NP O
CRE NNP B-NP O
1.0 CD I-NP O
GLU NNP B-NP O
104 CD I-NP O
08/15/92 CD B-NP B-DATE
08/15/92 CD I-NP B-DATE
22:40 CD B-NP O
13 CD I-NP O
:09 . O O
CK NNP B-NP O
40( JJ I-NP O
L NNP I-NP O
) -RRB- O O
CK-MB JJ B-NP O
1.9 CD I-NP O
Negative JJ O O
CKMBRI NNP B-NP O
see VBP B-VP O
detail NN O O
TROP-I NN B-NP O
Negative JJ I-NP O
TROP-T NN B-NP O
<0.01 CD I-NP O
Lab NNP B-NP O
Results NNS I-NP O
for IN B-PP O
: : O O
WOOD NN B-NP I-PATIENT
, , O I-PATIENT
CADE NNP B-NP I-PATIENT
H NNP I-NP I-PATIENT
Test NNP B-NP O
Name NNP I-NP O
SMI NNP I-NP B-HOSPITAL
08/15/92 CD O B-DATE
12:13 CD O O
WBC NNP B-NP O
8.5 CD I-NP O
RBC NNP B-NP O
4.11( JJ I-NP O
L NNP I-NP O
) -RRB- O O
HGB NNP B-NP O
12.4( JJ I-NP O
L NNP I-NP O
) -RRB- O O
HCT NNP B-NP O
34.8( JJ I-NP O
L NNP I-NP O
) -RRB- O O
MCV NNP B-NP O
85 CD I-NP O
MCH NNP B-NP O
30.1 CD I-NP O
MCHC NNP B-NP O
35.5 CD I-NP O
PLT NNP B-NP O
185 CD I-NP O
RDW NNP B-NP O
14.3 CD I-NP O
DIFFR NNP B-NP O
Received NNPS I-NP O
METHOD NNS B-NP O
see VBP B-VP O
detail NN B-NP O
%NEUT NNP B-NP O
88( CD I-NP O
H) . O O
%LYMPH NNP B-NP O
6( JJ I-NP O
L NNP I-NP O
) -RRB- O O
%MONO NN B-NP O
4 CD I-NP O
%EOS NNS B-NP O
2 CD O O
%BASO NN B-NP O
0 CD I-NP O
CXR NN B-NP O
: : O O
New NNP B-NP O
mild JJ I-NP O
interstitial JJ I-NP O
pulmonary NN I-NP O
edema NN I-NP O
. . O O
EKG NNP B-NP O
: : O O
Nl NNP B-NP O
sinus NNPS I-NP O
rhythm NN I-NP O
, , O O
L NNP B-NP O
axis VBD B-VP O
deviation NN B-NP O
, , O O
nl NN B-NP O
intervals NNS I-NP O
, , O O
T NNP B-NP O
wave NN I-NP O
inversions NNS I-NP O
I PRP B-NP O
, , O O
aVL RB B-ADVP O
, , O O
T NNP B-NP O
wave NN I-NP O
flattening NN I-NP O
V3-V6 NNS I-NP O
, , O O
old JJ B-NP O
inferior JJ I-NP O
infarct NN I-NP O
. . O O
Echo NNP B-NP O
11/07 CD I-NP B-DATE
- : O O
There EX B-NP O
is VBZ B-VP O
symmetric JJ B-NP O
left JJ I-NP O
ventricular JJ I-NP O
hypertrophy NN I-NP O
. . O O
There EX B-NP O
are VBP B-VP O
no DT B-NP O
obvious JJ I-NP O
segmental JJ I-NP O
wall NN I-NP O
motion NN I-NP O
abnormalities NNS I-NP O
. . O O
Theestimated DT B-NP O
ejection NN I-NP O
fraction NN I-NP O
is VBZ B-VP O
73 CD B-NP O
% NN I-NP O
. . O O
Impression NN B-NP O
: : O O
Pt NNP B-NP O
. . O O
is VBZ B-VP O
a DT B-NP O
59 CD I-NP B-AGE
y NN I-NP O
.o NN I-NP O
. . B-NP O
male NN I-NP O
with IN B-PP O
DLBCL NNP B-NP O
dx'ed VBD B-VP O
11/07 CD B-NP B-DATE
s/p NN I-NP O
CHOP-R NNP I-NP O
, , I-NP O
HTN NNP I-NP O
, , I-NP O
hyperlipidemia NN I-NP O
, , O O
GERD NNP B-NP O
, , O O
and CC O O
anemia NN B-NP O
who WP B-NP O
p/w VBD B-VP O
acute JJ B-NP O
onset NN I-NP O
SOB NNP I-NP O
in IN B-PP O
the DT B-NP O
setting NN I-NP O
of IN B-PP O
a DT B-NP O
BP NNP I-NP O
= SYM B-VP O
178/108 CD B-NP O
likely JJ I-NP O
2/2 CD I-NP O
flash NN I-NP O
pulmonary JJ I-NP O
edema NN I-NP O
. . O O
Plan NNP B-NP O
: : O O
CHF NNP B-NP O
- : O O
pt NN B-NP O
. . B-NP O
's POS B-NP O
PE NN I-NP O
resolved VBD B-VP O
s/p RB B-NP O
20 CD I-NP O
mg JJ I-NP O
IV NNP I-NP O
lasix NN I-NP O
, , O O
administration NN B-NP O
of IN B-PP O
lopressor NN B-NP O
, , O O
and CC O O
NTG. NNP B-NP O
He PRP B-NP O
showed VBD B-VP O
no DT B-NP O
signs NNS I-NP O
of IN B-PP O
volume NN B-NP O
overload NN I-NP O
during IN B-PP O
the DT B-NP O
physical JJ I-NP O
exam NN I-NP O
. . O O
Chest NNP B-NP O
CT NNP I-NP O
showed VBD B-VP O
no DT B-NP O
acute JJ I-NP O
hemorrhage NN I-NP O
, , O O
PTX NNP B-NP O
, , O O
or CC O O
lymphangitic JJ B-NP O
spread NN I-NP O
( -LRB- O O
preliminary JJ B-NP O
read NN I-NP O
) -RRB- O O
. . B-NP O
Follow-up NNP I-NP O
official JJ I-NP O
CT NNP I-NP O
read VBD B-VP O
. . O O
No DT B-NP O
contrast NN I-NP O
was VBD B-VP O
given VBN I-VP O
, , O O
therefore RB B-ADVP O
, , O O
acute JJ B-NP O
SOB NNP I-NP O
could MD B-VP O
not RB I-VP O
be VB I-VP O
secondary JJ B-ADJP O
to TO B-VP O
contrast VB I-VP O
allergy PRP B-NP O
. . O O
This DT B-NP O
pt NN I-NP O
. . B-PP O
's POS B-NP O
salty NN I-NP O
diet NN I-NP O
and CC O O
uncontrolled JJ B-NP O
HTN NN I-NP O
most RBS B-NP O
likely JJ I-NP O
led VBN B-VP O
to TO B-PP O
the DT B-NP O
acute JJ I-NP O
decompensation NN I-NP O
. . O O
No DT B-NP O
evidence NN I-NP O
of IN B-PP O
infection NN B-NP O
. . O O
Pt NNP O O
. . O O
will MD B-VP O
receive VB I-VP O
an DT B-NP O
Echo NNP I-NP O
to TO B-VP O
evaluate VB I-VP O
for IN B-PP O
possible JJ B-NP O
worsening VBG I-NP O
LVEF NN I-NP O
s/p NN I-NP O
antrhacycline NN I-NP O
chemo NN I-NP O
vs. IN B-PP O
diastolic JJ B-NP O
dysfunction NN I-NP O
with IN B-PP O
LV NNP B-NP O
hypertrophy NN I-NP O
. . O O
F/U '' O O
BNP. NNP B-NP O
Will MD B-VP O
re-dose VB I-VP O
lasix RB B-ADVP O
only RB B-ADVP O
if IN B-SBAR O
necessitated VBN B-VP O
by IN B-PP O
clinical JJ B-NP O
signs NNS I-NP O
of IN B-PP O
volume NN B-NP O
overload NN I-NP O
. . O O
Angina NNP B-NP O
- : O O
This DT B-NP O
pt NN I-NP O
. . O O
has VBZ B-VP O
EKG RB I-VP O
changes NNS B-NP O
and CC I-NP O
pain NN I-NP O
that WDT B-NP O
is VBZ B-VP O
possibly RB B-ADJP O
cardiogenic JJ I-ADJP O
in IN B-PP O
origin NN B-NP O
. . O O
Will NNP O O
obtain VB B-VP O
serial JJ B-NP O
enzymes NNS I-NP O
to TO B-VP O
r/o VB I-VP O
MI NNP B-NP O
. . O O
Begin VB B-VP O
ASA NNP B-NP O
, , O O
increase NN B-NP O
lopressor NN I-NP O
to TO B-PP O
50 CD B-NP O
TID NN I-NP O
, , O O
captopril NN B-VP O
instead RB B-ADVP O
of IN B-PP O
lisinopril NN B-NP O
for IN B-PP O
easier JJR B-NP O
titration NN I-NP O
of IN B-PP O
BPs NNS B-NP O
, , O O
2LO2 IN B-PP O
via IN B-PP O
nasal JJ B-NP O
canula NN I-NP O
. . O O
Consider VB B-VP O
stress NN B-NP O
test NN I-NP O
before IN B-PP O
d/c NN B-NP O
. . O O
Prophylaxis NNP B-NP O
- : O O
fragmin NN B-NP O
5000 CD B-NP O
SC NNP I-NP O
QD. NNP I-NP O
SOB NNP I-NP O
resolved VBD B-VP O
after IN B-PP O
lasix NN B-NP O
+ NN I-NP O
lopressor NN I-NP O
. . O O
Unlikely RB O O
PE NN B-NP O
in IN B-PP O
this DT B-NP O
setting NN I-NP O
but CC I-NP O
pt NN I-NP O
. . O O
is VBZ B-VP O
hypercoagulable JJ B-NP O
given VBN I-NP O
malignancy NN I-NP O
. . O O
Low NNP B-NP O
threshold NN I-NP O
for IN B-PP O
CT NNP B-NP O
PE NN I-NP O
protocol NN I-NP O
. . O O
GERD-Omeprazole NNP B-NP O
. . O O
Onc IN B-PP O
- : O O
Will MD B-VP O
check VB I-VP O
uric JJ B-NP O
acid NN I-NP O
and CC O O
LDH NNP B-NP O
to TO B-VP O
eval VB I-VP O
. . B-NP O
for IN B-PP O
possible JJ B-NP O
TLS. NNP I-NP O
Unlikely RB B-NP O
given VBN I-NP O
normal JJ I-NP O
electrolytes NNS I-NP O
and CC O O
good JJ B-NP O
renal JJ I-NP O
function NN I-NP O
. . O O
CT NN B-NP O
shows VBZ B-VP O
no DT B-NP O
lymphangitic NN I-NP O
spread NN I-NP O
but CC O O
must MD B-VP O
f/u VB I-VP O
official JJ B-NP O
read VBN B-VP O
in IN B-PP O
the DT B-NP O
AM. NNP I-NP O
Henderson NNP B-NP B-DOCTOR
Xin NNP I-NP I-DOCTOR
, , O O
MD . O O
Team NN B-NP O
3 CD I-NP O
Intern NN I-NP O
Department NNP B-NP O
of IN B-PP O
Internal NNP B-NP O
Medicine NNP I-NP O
Saint NNP B-NP B-HOSPITAL
Marys NNPS I-NP I-HOSPITAL
Infirmary NNP I-NP I-HOSPITAL
Pager NNP B-NP O
# # I-NP O
44348 CD O B-PHONE
