Record NNP B-NP O
date NN I-NP O
: : O O
2077-02-01 CD O B-DATE
Critical JJ B-NP O
care NN I-NP O
TRANSPLANT NN B-NP O
FELLOW NNP I-NP O
ADMIT NNP I-NP O
NOTE NNP I-NP O
HPI NNP B-NP O
: : O O
42 CD B-NP B-AGE
year NN I-NP O
old JJ I-NP O
man NN I-NP O
s/p VBD B-VP O
bilateral JJ B-NP O
lung NN I-NP O
transplantation NN I-NP O
for IN B-PP O
bronchiectasis NN B-NP O
in IN B-PP O
7/73 CD B-NP B-DATE
transferred VBN B-VP O
from IN B-PP O
Burlington NNP B-NP B-HOSPITAL
Obstetrics NNP I-NP I-HOSPITAL
Gynecology NNP I-NP I-HOSPITAL
Center NNP I-NP I-HOSPITAL
for IN B-PP O
further JJ B-NP O
evaluation NN I-NP O
of IN B-PP O
N/V/D NN B-NP O
, , I-NP O
fever NN I-NP O
and CC I-NP O
hypoxia NN I-NP O
. . O O
Over IN B-PP O
the DT B-NP O
past JJ I-NP O
six CD I-NP O
weeks NNS I-NP O
he PRP B-NP O
had VBD B-VP O
reported VBN I-VP O
a DT B-NP O
slow JJ I-NP O
decline NN I-NP O
in IN B-PP O
respiratory JJ B-NP O
function NN I-NP O
prompting VBG B-VP O
a DT B-NP O
recent JJ I-NP O
admission NN I-NP O
here RB B-ADVP O
1/23 CD B-NP B-DATE
-25/77 . O I-DATE
for IN B-PP O
elective JJ B-NP O
bronchoscopy NN I-NP O
to TO B-VP O
rule VB I-VP O
out RP B-NP O
rejection NN I-NP O
. . O O
He PRP B-NP O
noted VBD B-VP O
a DT B-NP O
slight JJ I-NP O
spontaneous JJ I-NP O
improvement NN I-NP O
a DT B-NP O
few JJ I-NP O
days NNS I-NP O
before IN B-PP O
that DT B-NP O
admission NN I-NP O
. . O O
Bronchoscopy NNP B-NP O
showed VBD B-VP O
no DT B-NP O
rejection NN I-NP O
but CC I-NP O
washings NNS I-NP O
did VBD B-VP O
grow VB I-VP O
M. NNP B-NP O
catarrhalis NN I-NP O
-levaquin NN I-NP O
was VBD B-VP O
begun VBN I-VP O
on IN B-PP O
1/25/77 CD B-NP B-DATE
. . O O
Pt NNP B-NP O
reports NNS I-NP O
continued VBD B-VP O
slow JJ B-NP O
improvement NN I-NP O
in IN B-PP O
dyspnea NN B-NP O
following VBG I-NP O
discharge NN I-NP O
. . O O
Yesterday NN B-NP O
morning NN I-NP O
he PRP B-NP O
developed VBD B-VP O
watery NN B-NP O
diarrhea NN I-NP O
( -LRB- O O
no DT B-NP O
blood NN I-NP O
or CC I-NP O
mucus NN I-NP O
) -RRB- I-NP O
soon RB B-VP O
followed VBN I-VP O
by IN B-PP O
nausea NN B-NP O
and CC I-NP O
vomiting NN I-NP O
( -LRB- O O
no DT B-NP O
blood NN I-NP O
or CC I-NP O
coffee NN I-NP O
grounds NNS I-NP O
) -RRB- B-PP O
. . O O
He PRP B-NP O
went VBD B-VP O
to TO B-PP O
BOGC NNP B-NP B-HOSPITAL
and CC O O
describes VBZ B-VP O
feeling VBG I-VP O
increased VBN B-NP O
dyspnea NN I-NP O
. . O O
Found VBN B-VP O
to TO I-VP O
be VB I-VP O
febrile JJ B-ADJP O
to TO B-VP O
101F VB I-VP O
and CC O O
hypoxic JJ B-NP O
( -LRB- I-NP O
SpO2 IN B-PP O
94 CD B-NP O
% NN I-NP O
, , O O
PaO2 JJ B-NP O
53 CD I-NP O
) -RRB- I-NP O
and CC O O
started VBD B-VP O
on IN B-PP O
supplemental JJ B-NP O
oxygen NN I-NP O
. . O O
GI IN B-SBAR O
symptoms NNS B-NP O
have VBP B-VP O
since IN B-PP O
improved VBN B-NP O
and CC I-NP O
pt NN I-NP O
is VBZ B-VP O
tolerating VBG I-VP O
PO NNP B-NP O
. . O O
Denies NNS B-VP O
chest NN B-NP O
pain NN I-NP O
, , O O
palpitations NNS B-NP O
, , O O
cough NN B-NP O
, , O O
rash NN B-NP O
, , O O
HA NNP B-NP O
, , O O
rhinorrhea NN B-NP O
, , O O
sore JJ B-NP O
throat NN I-NP O
at IN B-PP O
any DT B-NP O
point NN I-NP O
during IN B-PP O
this DT B-NP O
illness NN I-NP O
. . O O
Currently RB O O
no DT B-NP O
dyspnea RP I-NP O
at IN B-PP O
rest NN B-NP O
. . O O
PMH: NNP B-NP O
OSA NNP I-NP O
, , O O
obesity NN B-NP O
, , O O
osteoporosis NN B-NP O
, , O O
gout NN B-NP O
, , O O
HTN NNP B-NP O
, , O O
CRI NNP B-NP O
, , O O
avascular JJ B-NP O
necrosis NN I-NP O
of IN B-PP O
R NN B-NP O
hip/knee NN I-NP O
, , O O
depression NN B-NP O
, , O O
psoriasis NN B-NP O
Current JJ B-NP O
Meds NNS I-NP O
: : O O
Imm NNP B-NP O
: : O O
neoral JJ B-NP O
125 CD I-NP O
mg JJ I-NP O
po NN I-NP O
bid NN I-NP O
, , O O
cellcept IN B-PP O
500 CD B-NP O
mg CD I-NP O
po NN I-NP O
bid NN I-NP O
, , O O
prednisone NN B-NP O
30 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
Abx NNP B-NP O
: : O O
levaquin NN B-NP O
500 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd NN I-NP O
( -LRB- I-NP O
1/25 CD I-NP B-DATE
) -RRB- I-NP O
, , I-NP O
bactrim JJ I-NP O
ss NN I-NP O
1 CD I-NP O
po NN I-NP O
tiw NN I-NP O
, , O O
acyclovir CC O O
200 CD B-NP O
mg JJ I-NP O
po NN I-NP O
tid NN I-NP O
Other JJ B-NP O
: : O O
atenolol DT B-NP O
25 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd NN I-NP O
, , O O
norvasc JJ B-NP O
5 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd NN I-NP O
, , O O
nexium JJ B-NP O
20 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd NN I-NP O
, , O O
MgGlu NNP B-NP O
500 CD I-NP O
mg NN I-NP O
po NN I-NP O
tid NN I-NP O
, , O O
Kdur NNP B-NP O
20 CD I-NP O
mEq NN I-NP O
po NN I-NP O
qd NN I-NP O
, , O O
lipitor NN B-NP O
40 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd NN I-NP O
, , O O
Ca MD B-VP O
citrate/vit VB I-VP O
D/MVI NN B-NP O
, , O O
lasix RB B-ADVP O
40 CD B-NP O
mg NN I-NP O
po NN I-NP O
qd NN I-NP O
, , O O
cozaar NN B-NP O
100 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
SH NNS B-NP O
: : O O
Lives NNS B-NP O
in IN B-PP O
Florida NNP B-NP B-STATE
with IN B-PP O
wife NN B-NP O
. . O O
Works NNP O O
at IN B-PP O
ion NN B-NP B-ORGANIZATION
media NNS I-NP I-ORGANIZATION
networks NNS I-NP I-ORGANIZATION
. . O O
FH NNP B-NP O
: : O O
noncontributory JJ O O
Objective JJ B-NP O
: : O O
Vitals NNS B-NP O
: : O O
Tm NNP B-NP O
96.5 CD I-NP O
HR NNP I-NP O
71 CD I-NP O
BP NNP I-NP O
145/91 CD I-NP O
RR NNP I-NP O
22 CD I-NP O
SpO2 NNP I-NP O
97 CD I-NP O
% NN I-NP O
on IN B-PP O
2L JJ B-NP O
NC NNP I-NP O
Gen NNP B-NP O
: : O O
NAD NNP B-NP O
, , O O
obese NN B-NP O
HEENT/neck NN B-NP O
: : O O
OP NNP B-NP O
clear JJ I-NP O
, , O O
MMM NNP B-NP O
Lungs/chest NN B-NP O
: : O O
CTA NNP B-NP O
bilat NN I-NP O
, , O O
reduced VBD B-VP O
breath NN B-NP O
sounds NNS I-NP O
Heart NNP B-NP O
: : O O
RRR NNP B-NP O
w/o VBD B-VP O
m/r/g VBG I-VP O
Abd NNP B-NP O
: : O O
SNTND NNP B-NP O
+BS NNP I-NP O
Extr NNP B-NP O
: : O O
no DT B-NP O
c/c/e NN I-NP O
, , O O
2+ CD B-NP O
pulses NNS I-NP O
Lab NNP B-NP O
: : O O
significant JJ B-NP O
for IN B-PP O
BUN NNP B-NP O
36 CD I-NP O
, , O O
Cr NNP B-NP O
2.1 CD I-NP O
WBC NNP B-NP O
3.4 CD I-NP O
, , O O
Hct NNP B-NP O
39 CD I-NP O
, , O O
Plt NNP B-NP O
115 CD I-NP O
Micro NNP B-NP O
: : O O
Nasal NNP B-NP O
swab VB B-VP O
1/31/77 CD B-NP B-DATE
- : O O
negative JJ B-NP O
viral JJ I-NP O
panel NN I-NP O
Lung NNP B-NP O
washings VBD B-VP O
1/23/77 CD B-NP B-DATE
- : O O
moderate JJ B-NP O
M. NNP I-NP O
catarrhalis NNS I-NP O
Path NNP B-NP O
: : O O
Transbrochial NNP B-NP O
biopsy VB B-VP O
1/23 CD B-NP B-DATE
- : O O
negative JJ B-ADJP O
for IN B-PP O
tissue NN B-NP O
rejection NN I-NP O
CXR NNP B-NP O
1/31 CD I-NP B-DATE
: : O O
Unremarkable JJ O O
Impression NN B-NP O
: : O O
42 CD B-NP B-AGE
year NN I-NP O
old JJ I-NP O
man NN I-NP O
s/p VBD B-VP O
bilateral JJ B-NP O
lung NN I-NP O
transplant NN I-NP O
7/73 CD I-NP B-DATE
for IN B-PP O
bronchiectasis NN B-NP O
developed VBN B-VP O
acute JJ B-NP O
GI JJ I-NP O
illness NN I-NP O
in IN B-PP O
setting NN B-NP O
of IN B-PP O
levaquin NN B-NP O
tx NN I-NP O
for IN B-PP O
recent JJ B-NP O
respiratory NN I-NP O
infection NN I-NP O
. . O O
Now RB B-ADVP O
afebrile JJ B-ADJP O
and CC O O
with IN B-PP O
resolution NN B-NP O
of IN B-PP O
GI NNP B-NP O
symptoms NNS I-NP O
. . O O
Remains NNS B-VP O
somewhat RB B-ADJP O
dyspneic JJ I-ADJP O
with IN B-PP O
normal JJ B-NP O
BP NNP I-NP O
and CC I-NP O
HR. NNP I-NP O
Azotemia NNP I-NP O
possibly RB I-NP O
attributable JJ B-ADJP O
to TO B-PP O
dehydration NN B-NP O
though IN B-PP O
concern NN B-NP O
for IN B-PP O
other JJ B-NP O
etiologies NNS I-NP O
as IN B-PP O
per IN B-PP O
Dr. NNP B-NP O
Reilly NNP I-NP B-DOCTOR
's POS B-NP O
note NN I-NP O
. . O O
WBCs NNPS O O
reduced VBD B-VP O
from IN B-PP O
recent JJ B-NP O
levels NNS I-NP O
. . O O
Recommendations NNS B-NP O
: : O O
GI JJ B-NP O
illness NN I-NP O
: : O O
Mostly RB B-ADJP O
asymptomatic JJ I-ADJP O
now RB B-ADVP O
though IN B-PP O
some DT B-NP O
concerning VBG I-NP O
abnormalities NNS I-NP O
remain VBP B-VP O
( -LRB- B-NP O
O2 NN I-NP O
requirement NN I-NP O
, , O O
low JJ B-NP O
plt NN I-NP O
, , O O
low JJ B-NP O
WBC NNP I-NP O
, , O O
high JJ B-NP O
Cr NNP I-NP O
) -RRB- I-NP O
. . B-NP O
Remains NNS I-NP O
hemodynamically RB B-ADJP O
stable JJ I-ADJP O
. . O O
Await JJ B-NP O
results NNS I-NP O
of IN B-PP O
panculture NN B-NP O
including VBG I-NP O
stool NN I-NP O
studies NNS I-NP O
( -LRB- O O
including VBG B-PP O
C NNP B-NP O
diff NN I-NP O
, , O O
E NNP B-NP O
coli NNS I-NP O
, , O O
Camphylobacter NNP B-NP O
) -RRB- B-VP O
when WRB B-ADJP O
available JJ I-ADJP O
. . O O
Transplant NNP B-NP O
: : O O
Continue JJ B-NP O
current JJ I-NP O
immunosuppression NN I-NP O
and CC O O
prophylactic JJ B-NP O
abx NN I-NP O
. . O O
Will MD B-VP O
consider VB I-VP O
holding VBG I-VP O
cellcept NN B-NP O
, , O O
valcyte NN B-NP O
if IN B-PP O
leukopenia NN B-NP O
persists/worsens NNS I-NP O
. . O O
Follow NN B-VP O
daily JJ B-NP O
cyclosporin NN I-NP O
troughs NNS I-NP O
. . O O
No DT B-NP O
evidence NN I-NP O
of IN B-PP O
rejection NN B-NP O
on IN B-PP O
recent JJ B-NP O
biopsy NN I-NP O
. . O O
Dyspnea NNP B-NP O
: : O O
Consider VB B-VP O
aspiration NN B-NP O
though IN B-PP O
CXR NNP B-NP O
negative JJ I-NP O
, , O O
will MD B-VP O
follow VB I-VP O
. . O O
Hold VB B-VP O
abx JJ B-ADJP O
for IN B-PP O
now RB B-NP O
. . O O
Renal NNP B-NP O
: : O O
Azotemia NNP B-NP O
of IN B-PP O
unclear JJ B-NP O
etiology NN I-NP O
, , O O
follow VB B-VP O
up RP B-PRT O
labs NNS B-NP O
pending VBG B-PP O
. . B-NP O
Renal NNP I-NP O
consult VB B-VP O
per IN B-SBAR O
Dr. NNP B-NP O
Reilly NNP I-NP B-DOCTOR
. . O O
Oscar NNP B-NP B-DOCTOR
B. NNP I-NP I-DOCTOR
Stanley NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Pulmonary NNP B-NP O
Fellow NNP I-NP O
Pager NNP B-NP O
: : O O
34348 CD O B-PHONE
