Record NNP B-NP O
date NN I-NP O
: : O O
2087-10-04 CD O B-DATE
Problems NNS B-NP O
Diabetes NNP B-NP O
mellitus NN I-NP O
: : O O
started VBN B-NP O
2082 CD I-NP B-DATE
Psoriasis NN B-NP O
Hysterectomy NN B-NP O
: : O O
due JJ B-NP O
to TO B-VP O
bleeding VBG I-VP O
Gastrectomy NN B-NP O
: : O O
partial JJ B-NP O
, , O O
PUD NNP B-NP O
2061 CD I-NP B-DATE
Hypertension NNP B-NP O
: : O O
did VBD B-VP O
not RB O O
tolerate JJ B-ADJP O
ACE-I . O O
Medications NNS B-NP O
Glyburide NNP B-NP O
5MG VBD B-VP O
, , O O
0.5 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Atenolol NNP B-NP O
50MG JJ I-NP O
, , O O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Diprolene NNP B-NP O
ointment NN I-NP O
63 CD B-NP B-AGE
yo NNP I-NP O
for IN B-PP O
f/u NN B-NP O
diabetes NNS I-NP O
, , O O
HTN. NNP B-NP O
Recently RB B-ADVP O
noticed VBD B-VP O
balack JJ B-NP O
and CC I-NP O
blue JJ I-NP O
marks NNS I-NP O
on IN B-PP O
forearms NNS B-NP O
. . O O
Glu NNP B-NP O
115 CD I-NP O
after IN B-PP O
coffee NN B-NP O
. . O O
Sugars NNS B-NP O
at IN B-PP O
home NN B-NP O
running VBG B-VP O
70-168 CD O O
PE NN B-NP O
wgt VBD B-VP O
170 CD B-NP O
BP142/8 CD I-NP O
0 CD I-NP O
HR NNP I-NP O
60 CD I-NP O
lungs NNS B-NP O
clear JJ I-NP O
cor NN B-NP O
RRR NN I-NP O
ext NN B-NP O
: : O O
some DT B-NP O
scattered JJ I-NP O
echhymosis NN I-NP O
forearms NNS I-NP O
+ JJ B-NP O
psoriasis NN I-NP O
( -LRB- I-NP O
thickened JJ I-NP O
skin NN I-NP O
) -RRB- O O
A. NN B-NP O
psoriasis NN I-NP O
HTN . O O
DM . O O
ecchymosis NN B-NP O
P. NNP B-NP O
fasting VBG I-NP O
lipids NNS I-NP O
, , O O
CBC NNP B-NP O
, , O O
platelets NNS B-NP O
, , O O
HgA1c NNP B-NP O
. . I-NP O
F/U NNP I-NP O
1 CD I-NP O
month NN I-NP O
. . O O
