Record NNP B-NP O
date NN I-NP O
: : O O
2088-10-18 CD O B-DATE
64 CD B-NP B-AGE
yo NNP I-NP O
for IN B-PP O
f/u NN B-NP O
of IN B-PP O
chest NN B-NP O
pain NN I-NP O
1 CD B-LST O
. . O O
chest NN B-VP O
pain- . O O
this DT B-NP O
occurs VBZ B-VP O
usually RB B-ADVP O
upon IN B-PP O
waking VBG B-VP O
, , O O
in IN B-PP O
upper JJ B-NP O
ant JJ I-NP O
. . B-NP O
chest NN I-NP O
, , O O
sometimes RB B-ADVP O
radiates VBZ B-VP O
to TO B-PP O
both DT B-NP O
shoulders NNS I-NP O
. . O O
Describes NNS B-VP O
it PRP B-NP O
as IN B-PP O
"pressure NN B-NP O
" '' O O
. . B-VP O
Not RB I-VP O
affected VBN I-VP O
by IN B-PP O
NTG NNP B-NP O
SL NNP I-NP O
but CC O O
is VBZ B-VP O
relieved VBN I-VP O
within IN B-PP O
30 CD B-NP O
minutes NNS I-NP O
of IN B-PP O
taking VBG B-NP O
omeprazole NN I-NP O
. . O O
Had VBD B-VP O
adenosine JJ B-NP O
stress NN I-NP O
test NN I-NP O
yesterday NN I-NP O
showing NN I-NP O
: : O O
mild JJ B-NP O
LV NNP I-NP O
dilatation NN I-NP O
following VBG I-NP O
stress NN I-NP O
, , O O
resolves VBZ B-VP O
on IN B-PP O
rest NN B-NP O
images NNS I-NP O
perfusion NN B-NP O
images NNS I-NP O
show VBP B-VP O
moderate JJ B-NP O
anteroseptal NN I-NP O
and CC O O
apical JJ B-NP O
ischemia NN I-NP O
2. VBG B-VP O
+ NNP B-NP O
H. NNP I-NP O
Pylori- NNP I-NP O
completed VBD B-VP O
treatment NN B-NP O
since IN B-PP O
last JJ B-NP O
visit NN I-NP O
and CC O O
no DT B-NP O
further JJ I-NP O
"heartburn"-burning NN I-NP O
sensation NN I-NP O
. . O O
3. CD B-NP O
R NN I-NP O
hip NN I-NP O
pain-DJD. . O O
Has VBZ B-VP O
appt NN B-NP O
to TO B-VP O
see VB I-VP O
Dr. NNP B-NP O
Becker NNP I-NP B-DOCTOR
in IN B-PP O
consultation NN B-NP O
. . O O
Will MD B-VP O
need VB I-VP O
cardiology NN B-NP O
clearance NN I-NP O
prior RB B-ADVP O
to TO B-PP O
any DT B-NP O
ortho NN I-NP O
surgery NN I-NP O
given VBN I-NP O
yesterday NN B-NP O
's POS B-NP O
ETT. NNP I-NP O
4 CD B-LST O
. . O O
DM- NNP B-NP O
does VBZ B-VP O
not RB I-VP O
take VB I-VP O
glyburide NN B-NP O
daily RB B-ADVP O
. . O O
If IN B-SBAR O
she PRP B-NP O
does VBZ B-VP O
not RB I-VP O
eat VB I-VP O
any DT B-NP O
" `` I-NP O
carbs NNS I-NP O
" '' O O
she PRP B-NP O
does VBZ B-VP O
n't RB I-VP O
take VB I-VP O
it PRP B-NP O
. . O O
Last JJ B-ADJP O
HgA1C NNP B-NP O
8.2. CD I-NP O
She PRP B-NP O
is VBZ B-VP O
sure JJ B-ADJP O
she PRP B-NP O
is VBZ B-VP O
losing VBG I-VP O
wgt NN B-NP O
since IN B-PP O
her PRP$ B-NP O
clothes NNS I-NP O
feel VBP B-VP O
big JJ B-ADJP O
but CC O O
her PRP$ B-NP O
wgt NN I-NP O
is VBZ B-VP O
unchanged JJ B-ADJP O
from IN B-PP O
August NNP B-NP B-DATE
Problems NNS B-NP O
Diabetes NNP B-NP O
mellitus NN I-NP O
: : O O
started VBN B-NP O
2082 CD I-NP B-DATE
Hypertension NNP B-NP O
: : O O
did VBD B-VP O
not RB O O
tolerate JJ B-ADJP O
ACE-I . O O
Psoriasis NN B-NP O
Hysterectomy NN B-NP O
: : O O
due JJ B-NP O
to TO B-VP O
bleeding VBG I-VP O
Gastrectomy NN B-NP O
: : O O
partial JJ B-NP O
, , O O
PUD NNP B-NP O
2061 CD I-NP B-DATE
Medications NNS B-NP O
GLYBURIDE NNP B-NP O
5MG VBD B-VP O
, , O O
0.5 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD NNP I-NP O
x NNP I-NP O
90 CD I-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Avapro FW B-NP O
( -LRB- I-NP O
IRBESARTAN NN I-NP O
) -RRB- I-NP O
150MG CD I-NP O
, , I-NP O
1 CD I-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NNP I-NP O
QD NNP I-NP O
x NN I-NP O
60 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
ATENOLOL NNP B-NP O
50MG CD I-NP O
, , O O
1.5 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NNP I-NP O
QD NNP I-NP O
x NN I-NP O
90 CD B-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Imdur NNP B-NP O
( -LRB- I-NP O
ISOSORBIDE NNP I-NP O
Mononitrate NNP I-NP O
( -LRB- I-NP O
SR) NN I-NP O
) -RRB- I-NP O
30MG NN I-NP O
, , O O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD NNP I-NP O
x NNP I-NP O
30 CD I-NP O
day( NN I-NP O
s VBZ B-VP O
) -RRB- O O
Ntg NN B-NP O
1/150 CD I-NP O
( -LRB- I-NP O
NITROGLYCERIN NN I-NP O
1/150 CD I-NP O
( -LRB- I-NP O
0.4 CD I-NP O
Mg) NN I-NP O
) -RRB- O O
1 CD B-NP O
TAB NNP I-NP O
SL NNP I-NP O
x1 . O O
Allergies . O O
Penicillins NNP B-NP O
- : O O
Unknown JJ B-NP O
: : O O
EDEMA NNP O O
* VB B-NP O
IODINE NNP I-NP O
- : O O
Unknown JJ O O
Zestril NNP B-NP O
( -LRB- I-NP O
LISINOPRIL NNP I-NP O
) -RRB- I-NP O
- : O O
cough NN B-NP O
PE NN B-NP O
wgt VBD B-VP O
160 CD B-NP O
BP NNP I-NP O
160/62 CD I-NP O
HR NNP I-NP O
66 CD I-NP O
lungs NNS B-NP O
: : O O
clear JJ B-ADJP O
to TO B-PP O
A&P NNP B-NP O
cor NN B-NP O
RRR NN I-NP O
ext NN B-NP O
: : O O
no DT B-NP O
edema NN I-NP O
A. NN B-NP O
HTN-needs NNS I-NP O
better JJR B-NP O
control NN I-NP O
DM- CC O O
not RB B-ADJP O
tightly RB I-ADJP O
controlled VBN I-ADJP O
atyp IN B-SBAR O
chest NN B-NP O
pain- NNS I-NP O
relieved VBN B-VP O
by IN B-PP O
omeprazole NNP B-NP O
, , O O
unclear JJ B-NP O
ti NNS I-NP O
f NN I-NP O
this DT B-NP O
is VBZ B-VP O
cardiac JJ B-ADJP O
or CC I-ADJP O
GI JJ I-ADJP O
CAD NN B-NP O
- : O O
suggested VBN B-VP O
by IN B-PP O
recent JJ B-NP O
stress NN I-NP O
test NN I-NP O
, , O O
EKG RB B-VP O
done VBN I-VP O
at IN B-PP O
August NNP B-NP B-DATE
visit NN I-NP O
showed VBD B-VP O
biphasic JJ B-NP O
T NNP I-NP O
waves NNS I-NP O
V1-3 NN I-NP O
, , O O
inverted VBN B-VP O
T NNP B-NP O
V4 NNP I-NP O
which WDT B-NP O
appear VBP B-VP O
resolved VBN I-VP O
at IN B-PP O
yesterday NN B-NP O
's POS B-NP O
ETT. NNP I-NP O
R NN B-NP O
hip NN I-NP O
pain/DJD- NNS I-NP O
to TO B-VP O
see VB I-VP O
Dr. NNP B-NP O
Becker NNP I-NP B-DOCTOR
. . O O
If IN B-SBAR O
surgery NN B-NP O
is VBZ B-VP O
recommended VBN I-VP O
will MD B-VP O
need VB I-VP O
cardiac JJ B-NP O
clearance NN I-NP O
first RB B-LST O
wpc SYM O O
- : O O
mammogram NN B-NP O
scheduled VBN O O
P. NNP B-NP O
cardiology NN I-NP O
referral NN I-NP O
-Dr. NNP I-NP O
Sargent NNP I-NP B-DOCTOR
if IN B-PP O
available JJ B-ADJP O
as RB B-ADVP O
soon RB I-ADVP O
as IN B-PP O
possible JJ B-ADJP O
. . O O
Add VB B-VP O
Norvasc NNP B-NP O
5 CD B-NP O
mg NN I-NP O
qd NN I-NP O
for IN B-PP O
better JJR B-NP O
BP NNP I-NP O
control NN I-NP O
. . O O
HgA1c '' O O
( -LRB- B-NP O
7.5 CD I-NP O
) -RRB- I-NP O
and CC I-NP O
lipids NNS I-NP O
today NN B-NP O
. . B-NP O
Encourage NN I-NP O
to TO B-VP O
take VB I-VP O
glyburide NN B-NP O
daily RB B-ADVP O
and CC O O
only RB B-VP O
skip VB I-VP O
it PRP B-NP O
if IN B-PP O
her PRP$ B-NP O
sugars NNS I-NP O
on IN B-PP O
testing NN B-NP O
at IN B-PP O
home NN B-NP O
are VBP B-VP O
less JJR B-NP O
than IN I-NP O
100 CD I-NP O
. . O O
F/U '' O O
one CD B-NP O
month NN I-NP O
. . O O
