Record NNP B-NP O
date NN I-NP O
: : O O
2133-08-02 CD O B-DATE
Stallworth NNP B-NP B-HOSPITAL
Rehabilitation NNP I-NP I-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
/ NN I-NP O
Newport NNP I-NP B-HOSPITAL
Bariatric NNP I-NP O
Surgery NNP I-NP O
Program NN I-NP O
Postop NNP B-NP O
Nutrition NNP I-NP O
Assessment NNP I-NP O
Patient NNP B-NP O
: : O O
Uriel NNP B-NP B-PATIENT
Jones NNP I-NP I-PATIENT
DOB NNP I-NP O
: : O O
1/7/74 CD O B-DATE
Date NNP B-NP O
: : O O
8/2/33 CD O B-DATE
Surgeon NNP B-NP O
: : O O
Dr. NNP B-NP O
Black NNP I-NP B-DOCTOR
Surgical NNP I-NP O
date NN I-NP O
: : O O
s/p NN B-NP O
gastric JJ I-NP O
bypass NN I-NP O
5/11/33 . O B-DATE
S NNP B-NP O
: : O O
Hx NNP B-NP O
: : O O
Pt NNP B-NP O
was VBD B-VP O
seen VBN I-VP O
by IN B-PP O
his PRP$ B-NP O
request NN I-NP O
with IN B-PP O
his PRP$ B-NP O
wife NN I-NP O
. . O O
Pt NNP B-NP O
is VBZ B-VP O
married VBN I-VP O
and CC O O
3 CD B-NP O
children NNS I-NP O
ages NNS I-NP O
27 CD I-NP B-AGE
, , I-NP O
22 CD I-NP B-AGE
, , O O
and CC O O
19 CD B-NP B-AGE
. . B-NP O
Pt NNP I-NP O
lives VBZ B-VP O
with IN B-PP O
wife NN B-NP O
and CC O O
2 CD B-NP O
children NNS I-NP O
. . O O
Pt NN B-NP O
work NN I-NP O
as IN B-PP O
Small NNP B-NP B-PROFESSION
Equipment NNP I-NP I-PROFESSION
Mechanic NNP I-NP I-PROFESSION
. . O O
Reported JJ B-NP O
diet NN I-NP O
stage NN I-NP O
: : O O
4 CD O O
Adjustments NNS B-NP O
: : O O
tried VBD B-VP O
soda NN B-NP O
Issues NNS B-NP O
with IN B-PP O
current JJ B-NP O
diet NN I-NP O
: : O O
chix NN B-NP O
, , O O
hamburger NN B-NP O
Food NNP B-NP O
intolerance NN I-NP O
: : O O
soda NN B-NP O
in RP O O
can MD O O
Nausea NN B-NP O
no UH O O
Vomiting VBG O O
yes UH B-ADVP O
, , O O
x1 CD B-NP O
pace NN I-NP O
, , O O
occ NN B-NP O
, , O O
with IN B-PP O
dry JJ B-NP O
chix NN I-NP O
Diarrhea NN B-NP O
occ JJ B-NP O
loose JJ I-NP O
stools NNS I-NP O
Constipation NNP B-NP O
occ NN I-NP O
needs VBZ B-VP O
more RBR I-VP O
Hydration NN B-NP O
needs NNS B-NP O
more RBR I-NP O
Other JJ B-NP O
: : O O
24-hour JJ B-NP O
dietary NN I-NP O
recall NN I-NP O
: : O O
B NNP B-NP O
: : O O
yogurt NN B-VP O
Yoplait PRP B-NP O
with IN B-PP O
fruit NN B-NP O
and CC I-NP O
pb NN I-NP O
and CC O O
some DT B-NP O
granola NN I-NP O
Sn NNP B-NP O
: : O O
L: . O O
chix NN B-NP O
, , O O
BBQ NNP B-NP O
small JJ I-NP O
thigh NN I-NP O
and CC O O
2 CD B-NP O
wings NNS I-NP O
, , O O
brown JJ B-NP O
rice NN I-NP O
Sn NNP B-NP O
: : B-VP O
oc FW B-NP O
carrots NNS I-NP O
of IN B-PP O
fruit NN B-NP O
D NNP B-NP O
: : O O
1-2 JJ B-NP O
eggs NNS I-NP O
with IN B-PP O
shrimp NN B-NP O
and CC I-NP O
toast NN I-NP O
with IN B-PP O
marg NN B-NP O
and CC I-NP O
jelly NN I-NP O
Sn NNP B-NP O
: : O O
none NN B-NP O
Beverages NNP B-NP O
: : O O
G2 VB B-VP O
on IN B-PP O
walk NN B-NP O
, , I-NP O
water NN I-NP O
, , I-NP O
iced JJ I-NP O
coffee NN I-NP O
with IN B-PP O
cream NN B-NP O
Supplements NNS B-NP O
: : O O
most RBS B-NP O
days NNS I-NP O
walk NN I-NP O
, , O O
3 CD B-NP O
miles NNS I-NP O
O UH B-NP O
: : O O
Age NNP B-NP O
: : O O
59 CD B-NP B-AGE
y NN I-NP O
Sex NN I-NP O
: : O O
male NN B-NP O
Ht NNP B-NP O
: : O O
5&#8217;7.5&#8221 CD B-NP O
; : O O
Wt NNP B-NP O
: : O O
255# CD O O
BMI NNP B-NP O
: : O O
39.4 CD O O
Previous JJ B-NP O
weight NN I-NP O
: : O O
273# CD B-NP O
6/20/33 CD I-NP B-DATE
/ NN I-NP O
295# CD I-NP O
5/24/33 CD O B-DATE
IBW NNP B-NP O
: : O O
138-168# CD B-NP O
Excess NNP I-NP O
Wt NNP I-NP O
: : O O
87-117# CD O O
Preoperative JJ B-NP O
weight NN I-NP O
: : O O
333# CD B-NP O
1/11/33 CD I-NP B-DATE
Cumulative JJ I-NP O
Wt NNP I-NP O
Change NNP I-NP O
: : O O
down RP B-NP O
78# CD I-NP O
PMH: . O O
edema NN B-NP O
, , O O
type NN B-NP O
2 CD I-NP O
DM NNP I-NP O
, , I-NP O
OSA NNP I-NP O
with IN B-PP O
CPAP NNP B-NP O
, , O O
hypercholesterolemia NN B-NP O
, , O O
HTN NNP B-NP O
, , O O
cardiac JJ B-NP O
myopathy NN I-NP O
, , O O
OA NN B-NP O
in IN B-PP O
knees NNS B-NP O
, , O O
open JJ B-NP O
chole NN I-NP O
Medications NNS B-NP O
: : O O
lantus NN B-NP O
, , O O
humalog NN B-NP O
sliding VBG I-NP O
scale NN I-NP O
, , O O
Coumadin NNP B-NP O
Current JJ B-NP O
meds NNS I-NP O
5/24/33 VBP B-VP B-DATE
: : O O
CPAP NNP B-NP O
, , I-NP O
coumadin NN I-NP O
, , O O
ASA NNP B-NP O
81 CD I-NP O
mg NN I-NP O
, , O O
K NNP B-NP O
citrate NN I-NP O
, , O O
furosemide NN B-NP O
, , I-NP O
fluoxitine NN I-NP O
, , I-NP O
cordarone NN I-NP O
, , I-NP O
metoprolol NN I-NP O
, , I-NP O
glucosamine NN I-NP O
and CC I-NP O
chondroitin NN I-NP O
, , I-NP O
lisinopril NN I-NP O
, , I-NP O
crestor NN I-NP O
, , I-NP O
norvasc NN I-NP O
, , O O
pepcid NN B-NP O
Current JJ B-NP O
meds NNS I-NP O
6/20/33 VBP B-VP B-DATE
: : O O
off RP B-NP O
lantus NN I-NP O
, , I-NP O
humalog NN I-NP O
, , O O
Current JJ B-NP O
meds NNS I-NP O
8/2/33 VBP B-VP B-DATE
: : O O
CPAP NNP B-NP O
, , I-NP O
coumadin NN I-NP O
, , O O
ASA NNP B-NP O
81 CD I-NP O
mg NN I-NP O
, , O O
K NNP B-NP O
citrate NN I-NP O
, , O O
furosemide NN B-NP O
, , O O
fluoxitine NN B-NP O
, , O O
cordarone NN B-NP O
, , O O
metoprolol NN B-NP O
, , O O
d/c JJ B-NP O
glucosamine NN I-NP O
and CC I-NP O
chondroitin NN I-NP O
, , I-NP O
lisinopril NN I-NP O
, , I-NP O
crestor NN I-NP O
, , I-NP O
norvasc NN I-NP O
, , O O
pepcid NN B-NP O
Labs NNS B-NP O
: : O O
to TO B-VP O
be VB I-VP O
evaluated VBN I-VP O
per IN B-PP O
surgeon NN B-NP O
, , O O
BS NNP B-NP O
110 CD I-NP O
am VBP I-NP O
Prescribed VBN B-NP O
diet NN I-NP O
: : O O
stage NN B-NP O
4 CD I-NP O
Patient JJ B-NP O
educational JJ I-NP O
material NN I-NP O
used VBN B-VP O
: : O O
Dietary NNP B-NP O
Guidelines NNP I-NP O
for IN B-PP O
Gastric NNP B-NP O
Bypass NNP I-NP O
, , O O
protein NN B-NP O
list NN I-NP O
A: . O O
59 CD B-NP B-AGE
y NN I-NP O
.o NN I-NP O
. . O O
male NN B-NP O
referred VBD B-VP O
to TO B-PP O
nutrition NN B-NP O
followup NN I-NP O
for IN B-PP O
gastric JJ B-NP O
bypass NN I-NP O
. . O O
Weight NNP B-NP O
Assessment NNP I-NP O
: : O O
Pt NNP B-NP O
weighs VBZ B-VP O
255 CD B-NP O
lbs NNS I-NP O
and CC O O
is VBZ B-VP O
68 CD B-NP O
inches NNS I-NP O
tall JJ B-ADJP O
with IN B-PP O
BMI NNP B-NP O
of IN B-PP O
39.4 CD B-NP O
. . O O
Obesity NNP B-NP O
Class NNP I-NP O
: : O O
3 LS O O
Est NNP B-NP O
. . I-NP O
Energy NNP I-NP O
Needs NNS I-NP O
: : O O
BMR NNP B-NP O
1940 CD I-NP O
kcal/day NN I-NP O
, , O O
~2700-3000 CD B-NP O
cal/day NN I-NP O
for IN B-PP O
weight NN B-NP O
maintenance NN I-NP O
. . O O
Dietary NNP B-NP O
Assessment NNP I-NP O
: : O O
Pt NNP B-NP O
presents VBZ B-VP O
with IN B-PP O
h/o NN B-NP O
edema NN I-NP O
, , O O
type NN B-NP O
2 CD I-NP O
DM NNP I-NP O
, , I-NP O
OSA NNP I-NP O
with IN B-PP O
CPAP NNP B-NP O
, , O O
hypercholesterolemia NN B-NP O
, , O O
HTN NNP B-NP O
, , O O
cardiac JJ B-NP O
myopathy NN I-NP O
, , O O
OA NN B-NP O
in IN B-PP O
knees NNS B-NP O
, , O O
open JJ B-NP O
chole NN I-NP O
and CC I-NP O
morbid NN I-NP O
obesity NN I-NP O
s/p NN I-NP O
gastric VBD B-VP O
bypass IN B-PP O
surgery NN B-NP O
x NN I-NP O
3 CD B-NP O
months NNS I-NP O
compliant JJ B-ADJP O
with IN B-PP O
fluid NN B-NP O
, , I-NP O
protein NN I-NP O
and CC I-NP O
vitamin NN I-NP O
and CC I-NP O
mineral NN I-NP O
supplementation NN I-NP O
recommendations NNS I-NP O
Pt NNP B-NP O
to TO B-VP O
cont VB I-VP O
on IN B-PP O
stage NN B-NP O
4 CD I-NP O
Issues NNS B-NP O
discussed VBN B-VP O
: : O O
x NN B-NP O
Diet NNP I-NP O
stage NN I-NP O
: : O O
4 CD B-NP O
x NN I-NP O
Protein NNP I-NP O
intake NN I-NP O
: : O O
60 CD B-NP O
grams/day NN I-NP O
x NN I-NP O
Fluid JJ I-NP O
intake NN I-NP O
: : O O
&gt NN B-NP O
;64 CD B-NP O
oz/day NN I-NP O
x NN B-NP O
Multivitamin/mineral NNP I-NP O
x NNP I-NP O
Calcium NNP I-NP O
w/Vit NN I-NP O
D NNP I-NP O
: : O O
1200-1500 CD B-NP O
mg NN I-NP O
calcium NN I-NP O
Vitamin NNP I-NP O
B12 . O O
x NN B-NP O
Slowly RB B-VP O
eating VBG I-VP O
and CC I-VP O
drinking VBG I-VP O
, , O O
small JJ B-NP O
portion NN I-NP O
sized VBD B-VP O
, , O O
healthful JJ B-NP O
food NN I-NP O
choices NNS I-NP O
x NN B-NP O
Protein NNP I-NP O
foods NNS I-NP O
, , O O
food NN B-NP O
preparation NN I-NP O
methods NNS I-NP O
x NN B-NP O
meal NN I-NP O
planning VBG B-LST O
P NNP B-NP O
: : O O
Recommendations NNS B-NP O
: : O O
Cont NNP B-NP O
diet NN I-NP O
stage NN I-NP O
: : O O
4 CD O O
Expected VBN B-NP O
adherence NN I-NP O
: : O O
good JJ O O
Goals NNS B-NP O
: : O O
&gt JJ B-NP O
;64 CD I-NP O
ounces NNS I-NP O
fluid/day NN I-NP O
, , O O
&gt CC O O
;60 CD B-NP O
grams NNS I-NP O
protein/day NN I-NP O
Cont NNP B-NP O
Multivitamin/mineral NNP I-NP O
daily RB B-ADVP O
, , O O
cont NN B-NP O
1200-1500 CD I-NP O
mg NN B-NP O
calcium NN I-NP O
with IN B-PP O
added JJ B-NP O
vitamin NN I-NP O
D NNP I-NP O
daily RB O O
Use VB B-NP O
protein NN I-NP O
list NN I-NP O
as IN B-PP O
guide NN B-NP O
Increase VB B-VP O
food NN B-NP O
variety NN I-NP O
and CC I-NP O
consistency NN I-NP O
slowly RB O O
Cont JJ B-NP O
current JJ I-NP O
activity NN I-NP O
, , O O
increase NN B-NP O
as IN B-PP O
able JJ B-NP O
Call VB B-VP O
or CC I-VP O
email VB I-VP O
with IN B-PP O
any DT B-NP O
questions NNS I-NP O
or CC I-NP O
problems NNS I-NP O
RTC NNP B-NP O
3 CD I-NP O
months NNS I-NP O
postop NN I-NP O
surg NN I-NP O
, , O O
RD NNP B-NP O
Sonja NNP B-NP B-DOCTOR
Bauer NNP I-NP I-DOCTOR
, , O O
MS NNP B-NP O
, , O O
RD NNP B-NP O
, , O O
LDN NNP B-NP O
8/2/33 CD O B-DATE
