Record NNP B-NP O
date NN I-NP O
: : O O
2089-03-09 CD O B-DATE
Reason NN B-NP O
for IN B-PP O
Visit NNP B-NP O
Annual JJ B-NP O
Physical NNP I-NP O
Exam NNP I-NP O
. . O O
Problems NNS B-NP O
Hypertensive NNP B-NP O
heart NN I-NP O
disease NN I-NP O
S NNP B-NP O
: : O O
Pt NNP B-NP O
. . O O
has VBZ B-VP O
been VBN I-VP O
treated VBN I-VP O
for IN B-PP O
hypertension NN B-NP O
since IN B-PP O
2064 CD B-NP B-DATE
. . O O
When WRB B-ADVP O
she PRP B-NP O
came VBD B-VP O
to TO B-PP O
me PRP B-NP O
in IN B-PP O
2084 CD B-NP B-DATE
she PRP B-NP O
'd MD B-VP O
been VBN I-VP O
on IN B-PP O
Accupril NNP B-NP O
5 CD I-NP O
mg NN I-NP O
. . O O
a DT B-NP O
day NN I-NP O
, , O O
but CC O O
her PRP$ B-NP O
BP NNP I-NP O
was VBD B-VP O
180/80 CD B-NP O
. . O O
Since IN B-PP O
that DT B-NP O
time NN I-NP O
, , O O
despite IN B-PP O
the DT B-NP O
administration NN I-NP O
of IN B-PP O
a DT B-NP O
variety NN I-NP O
of IN B-PP O
antihypertensives NNS B-NP O
, , O O
her PRP$ B-NP O
BP NNP I-NP O
has VBZ B-VP O
rarely RB I-VP O
been VBN I-VP O
normal JJ B-ADJP O
and CC O O
she PRP B-NP O
insists VBZ B-VP O
that IN B-PP O
her PRP$ B-NP O
BP NNP I-NP O
is VBZ B-VP O
a DT B-NP O
function NN I-NP O
of IN B-PP O
having VBG B-VP O
come VBN I-VP O
to TO B-PP O
the DT B-NP O
doctor NN I-NP O
. . O O
In IN B-PP O
Mar NNP B-NP I-DATE
. . O I-DATE
2087 CD O I-DATE
she PRP B-NP O
was VBD B-VP O
hospitlaized VBN I-VP O
with IN B-PP O
acute JJ B-NP O
congestive JJ I-NP O
heart NN I-NP O
failure NN I-NP O
and CC O O
Lasix NNP B-NP O
was VBD B-VP O
added VBN I-VP O
to TO B-PP O
her PRP$ B-NP O
regimen NNS I-NP O
that IN B-NP O
included VBD B-VP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
Norvasc NNP B-NP O
, , I-NP O
Atacand NNP I-NP O
and CC I-NP O
Atenolol NNP I-NP O
. . O O
Despite IN B-PP O
some DT B-NP O
peripheral JJ I-NP O
edema NN I-NP O
, , O O
she PRP B-NP O
continues VBZ B-VP O
on IN B-PP O
this DT B-NP O
regimen NN I-NP O
and CC O O
says VBZ B-VP O
that IN B-SBAR O
she PRP B-NP O
feels VBZ B-VP O
well RB B-PP O
. . O O
She PRP B-NP O
recently RB B-ADVP O
celebrated VBD B-VP O
her PRP$ B-NP O
81 CD I-NP B-AGE
st NN I-NP O
Birthday NNP I-NP O
surround NN I-NP O
by IN B-PP O
her PRP$ B-NP O
seven CD I-NP O
children NNS I-NP O
, , O O
and CC O O
multiple JJ B-NP O
grand JJ I-NP O
- : I-NP O
and CC I-NP O
great-grand JJ I-NP O
children NNS I-NP O
. . O O
O UH B-VP O
: : O O
BP NNP B-NP O
170/8 CD B-NP O
0 CD I-NP O
; : O O
Heart-- : O O
NSR NNP B-NP O
wiohtout IN B-PP O
murmurs NNS B-NP O
or CC I-NP O
gallopr NN I-NP O
. . O O
EKG NN B-NP O
shows VBZ B-VP O
no DT B-NP O
LVH NNP I-NP O
or CC O O
strain VB B-VP O
pattern NN B-NP O
. . O O
A: '' O O
Systolic NNP B-NP O
Hypertension NNP I-NP O
. . I-NP O
Patient NNP I-NP O
is VBZ B-VP O
reluctant JJ B-ADJP O
to TO B-VP O
increase VB I-VP O
or CC I-VP O
change VB I-VP O
her PRP$ B-NP O
meds NNS I-NP O
. . O O
P NNP B-NP O
: : O O
Continue NNP B-VP O
present VB B-VP O
meds NNS B-NP O
and CC O O
will MD B-VP O
try VB I-VP O
and CC I-VP O
increase VB I-VP O
her PRP$ B-NP O
medications NNS I-NP O
on IN B-PP O
her PRP$ B-NP O
next JJ I-NP O
visit NN I-NP O
, , O O
a DT B-NP O
month NN I-NP O
from IN B-PP O
now RB B-NP O
. . O O
Osteoarthritis NNP B-NP O
S NNP B-NP O
: : O O
Pt NNP B-NP O
. . O O
takes VBZ B-VP O
Indocin NNP B-NP O
intermittently RB B-ADVP O
for IN B-PP O
pain NN B-NP O
in IN B-PP O
her PRP$ B-NP O
hips NNS I-NP O
, , I-NP O
neck NN I-NP O
and CC I-NP O
hands NNS I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
a DT B-NP O
long JJ I-NP O
history NN I-NP O
of IN B-PP O
osteoarthritis NN B-NP O
. . O O
O UH B-NP O
: : O O
Degenerative JJ B-NP O
joint JJ I-NP O
disease NN I-NP O
, , O O
with IN B-PP O
changes NNS B-NP O
in IN B-PP O
hands NNS B-NP O
and CC I-NP O
legs NNS I-NP O
, , O O
and CC O O
some DT B-NP O
distortion NN I-NP O
of IN B-PP O
the DT B-NP O
knees NNS I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
swelling VBG I-VP O
of IN B-PP O
the DT B-NP O
joints NNS I-NP O
of IN B-PP O
the DT B-NP O
hands NNS I-NP O
, , O O
particularly RB B-ADVP O
both DT B-NP O
thumbs NNS I-NP O
, , O O
but CC O O
it PRP B-NP O
does VBZ B-VP O
not RB I-VP O
interfere VB I-VP O
with IN B-PP O
her PRP$ B-NP O
life NN I-NP O
.A NN I-NP O
: : O O
OA NN B-NP O
. . O O
P NNP B-NP O
: : O O
Will MD B-VP O
make VB I-VP O
no DT B-NP O
changes NNS I-NP O
at IN B-PP O
this DT B-NP O
time NN I-NP O
. . O O
breast NN B-NP O
carcinoma NN I-NP O
S NNP B-NP O
: : O O
The DT B-NP O
pt NN I-NP O
. . O O
is VBZ B-VP O
seven CD B-NP O
years NNS I-NP O
S/P RB B-ADVP O
modified VBN B-VP O
Left VBN I-VP O
radical JJ B-NP O
mastectomy NN I-NP O
, , O O
with IN B-PP O
3 CD B-NP O
of IN B-PP O
14 CD B-NP O
nodes NNS I-NP O
involved VBN B-VP O
, , O O
with IN B-PP O
a DT B-NP O
poorly RB I-NP O
differentiated JJ I-NP O
intra-ductal JJ I-NP O
carcinoma NN I-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
T2 DT B-NP O
M1 NNP I-NP O
N0 NNP I-NP O
. . O O
She PRP B-NP O
had VBD B-VP O
been VBN I-VP O
on IN B-PP O
Tamoxifen NNP B-NP O
10 CD I-NP O
mg NN I-NP O
. . B-NP O
b.i.d NN I-NP O
. . O O
for IN B-PP O
5 CD B-NP O
years NNS I-NP O
, , O O
but CC O O
this DT B-NP O
was VBD B-VP O
d/c JJ B-NP O
'd NNP I-NP O
in IN B-PP O
March NNP B-NP B-DATE
2086 CD I-NP I-DATE
by IN B-PP O
Dr. NNP B-NP O
Quy NNP I-NP B-DOCTOR
Cherry NNP I-NP I-DOCTOR
and CC O O
she PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
not RB B-NP O
sign NN I-NP O
of IN B-PP O
recurrence NN B-NP O
. . O O
She PRP B-NP O
does VBZ B-VP O
, , O O
however RB B-ADVP O
, , O O
have VBP B-VP O
a DT B-NP O
great JJ I-NP O
deal NN I-NP O
of IN B-PP O
anxiety NN B-NP O
about IN B-PP O
the DT B-NP O
return NN I-NP O
of IN B-PP O
her PRP$ B-NP O
malignancy NN I-NP O
and CC O O
when WRB B-ADVP O
her PRP B-NP O
daughter NN B-NP O
found VBD B-VP O
a DT B-NP O
"lump NN I-NP O
" '' O O
in IN B-PP O
her PRP$ B-NP O
back NN I-NP O
last JJ B-NP O
week NN I-NP O
in IN B-PP O
the DT B-NP O
course NN I-NP O
of IN B-PP O
giving VBG B-VP O
her PRP B-NP O
a DT B-NP O
massage NN I-NP O
, , O O
she PRP B-NP O
became VBD B-VP O
convinced VBN B-ADJP O
that IN B-PP O
her PRP$ B-NP O
cancer NN I-NP O
had VBD B-VP O
returned VBN I-VP O
.O NNP B-NP O
: : O O
Well-healed JJ B-NP O
L NNP I-NP O
modified VBN B-VP O
radical JJ B-NP O
mastectomy NN I-NP O
. . O O
No DT B-NP O
axillary NN I-NP O
notes NNS I-NP O
noted VBD B-VP O
. . O O
R NN B-NP O
breast NN I-NP O
appears VBZ B-VP O
normal JJ B-ADJP O
. . B-NP O
Pt NNP I-NP O
. . O O
gets VBZ B-VP O
routine JJ B-NP O
mammograms NNS I-NP O
on IN B-PP O
the DT B-NP O
R NN I-NP O
breast NN I-NP O
. . O O
No DT B-NP O
lumps NNPS I-NP O
or CC I-NP O
masses NNS I-NP O
were VBD B-VP O
found VBN I-VP O
in IN B-PP O
or CC I-PP O
on IN I-PP O
her PRP$ B-NP O
back NN I-NP O
. . O O
Chest NNP B-NP O
X-ray NN I-NP O
today NN I-NP O
shows VBZ B-VP O
no DT B-NP O
nodular JJ I-NP O
densities.A NNS I-NP O
: : O O
S/P NNP B-NP O
left VBD B-VP O
radical JJ B-NP O
mastectomy NN I-NP O
for IN B-PP O
ca MD B-NP O
. . O O
of IN B-PP O
the DT B-NP O
breast NN I-NP O
, , O O
with IN B-PP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
recurrence NN B-NP O
. . O O
P NNP B-NP O
: : O O
No DT B-NP O
further JJ I-NP O
therapy NN I-NP O
indicated VBD B-VP O
, , O O
but CC O O
Alk NNP B-NP O
. . I-NP O
Phos NNP I-NP O
. . O O
drawn VBN B-VP O
along IN B-PRT O
with IN B-PP O
routine JJ B-NP O
chemistries NNS I-NP O
. . O O
Review NNP B-NP O
of IN I-NP O
Systems NNPS O O
Patient NNP B-NP O
says VBZ B-VP O
that IN B-SBAR O
she PRP B-NP O
gets VBZ B-VP O
short JJ B-ADJP O
of IN B-PP O
breath NN B-NP O
while IN B-LST O
climbing VBG B-VP O
up IN B-PRT O
stairs NNS B-NP O
, , O O
and CC O O
cannot MD B-VP O
walk VB I-VP O
more JJR B-NP O
than IN B-PP O
a DT B-NP O
block NN I-NP O
or CC I-NP O
two CD I-NP O
without IN B-PP O
getting VBG B-VP O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
. . O O
She PRP B-NP O
always RB B-ADVP O
has VBZ B-VP O
edema NN B-NP O
in IN B-PP O
both DT B-NP O
legs NNS I-NP O
, , O O
except IN B-PP O
when WRB B-ADVP O
she PRP B-NP O
arises VBZ B-VP O
in IN B-PP O
the DT B-NP O
a.m. NN I-NP O
at IN B-PP O
which WDT B-NP O
time NN B-NP O
her PRP$ B-NP O
legs NNS I-NP O
are VBP B-VP O
free JJ B-ADJP O
of IN B-PP O
edema NN B-NP O
. . O O
At IN B-PP O
the DT B-NP O
same JJ I-NP O
time NN I-NP O
, , O O
she PRP B-NP O
denies VBZ B-VP O
PND NNP B-NP O
and CC O O
says VBZ B-VP O
that IN B-SBAR O
she PRP B-NP O
sleeps VBZ B-VP O
on IN B-PP O
only RB B-NP O
one CD I-NP O
pillow NN I-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
chest NN B-NP O
pain NN I-NP O
, , O O
says VBZ B-VP O
that IN B-SBAR O
she PRP B-NP O
eats VBZ B-VP O
well RB B-ADVP O
and CC O O
has VBZ B-VP O
regular JJ B-NP O
BMs. NNP I-NP O
Her PRP$ B-NP O
biggest JJS I-NP O
complaint NN I-NP O
now RB B-ADVP O
is VBZ B-VP O
urinary JJ B-NP O
pressure NN I-NP O
and CC I-NP O
urgency NN I-NP O
. . O O
She PRP B-NP O
had VBD B-VP O
been VBN I-VP O
using VBG I-VP O
a DT B-NP O
Pessary JJ I-NP O
for IN B-PP O
Uterine NNP B-NP O
decensus NN I-NP O
, , O O
but CC O O
it PRP B-NP O
was VBD B-VP O
removed VBN I-VP O
by IN B-PP O
Gyn NNP B-NP O
and CC O O
she PRP B-NP O
was VBD B-VP O
prescribed VBN I-VP O
local JJ B-NP O
Estrogen NN I-NP O
cream NN I-NP O
, , O O
which WDT B-NP O
has VBZ B-VP O
not RB I-VP O
yet RB I-VP O
helped VBN I-VP O
. . O O
She PRP B-NP O
was VBD B-VP O
advised VBN I-VP O
to TO I-VP O
call VB I-VP O
Gyn NNP B-NP O
for IN B-PP O
another DT B-NP O
visit NN I-NP O
, , O O
since IN B-SBAR O
she PRP B-NP O
was VBD B-VP O
scheduled VBN I-VP O
about IN B-PP O
6 CD B-NP O
weeks NNS I-NP O
from IN B-PP O
now RB B-NP O
. . O O
Medications NNS B-NP O
ATENOLOL NNP B-NP O
25MG VBD B-VP O
2 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QAM NN I-NP O
quinine CD B-NP O
260MG CD I-NP O
PO NNP I-NP O
x1 CD I-NP O
LASIX NNP B-NP O
( -LRB- I-NP O
FUROSEMIDE NNP I-NP O
) -RRB- I-NP O
40MG . B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
BID . O O
NORVASC NNP B-NP O
( -LRB- I-NP O
AMLODIPINE NNP I-NP O
) -RRB- I-NP O
5MG . B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
BID . O O
ATACAND NNP B-NP O
( -LRB- I-NP O
CANDESARTAN NNP I-NP O
) -RRB- I-NP O
32MG . I-NP O
PO NNP I-NP O
QD . O O
K-DUR NNP B-NP O
(KCL NNP I-NP O
SLOW NNP I-NP O
REL. NNP I-NP O
) -RRB- I-NP O
20MEQ . B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Vital JJ B-NP O
Signs NNS I-NP O
Pulse NNP B-NP O
: : O O
70 CD B-NP O
Regular NNP I-NP O
Height NN B-NP O
: : O O
57 CD B-NP O
Inches NNS I-NP O
Weight NNP B-NP O
: : O O
140 CD B-NP O
Pounds NNS I-NP O
Blood NN B-NP O
Pressure NN I-NP O
: : O O
170/8 CD B-NP O
0 CD I-NP O
Left VBN B-VP O
Arm NN O O
Physical NNP B-NP O
Exam NNP I-NP O
HEENT NN B-NP O
Pupils NNS B-NP O
react VBP B-VP O
= SYM B-NP O
to TO B-PP O
light JJ B-NP O
. . I-NP O
Conjunctivae NNP I-NP O
and CC O O
Sclerae NNP B-NP O
- : O O
clear JJ B-ADJP O
. . B-NP O
Fundi-normal JJ I-NP O
. . O O
She PRP B-NP O
is VBZ B-VP O
s/p RB O O
bilateral JJ B-NP O
lens NN I-NP O
implants VBZ B-VP O
.Ears-clear JJ B-ADJP O
. . O O
Pharynx-clear NNP O O
. . O O
Patient NNP B-NP O
is VBZ B-VP O
completely RB B-ADJP O
edentulous JJ I-ADJP O
with IN B-PP O
a DT B-NP O
well-fitting JJ I-NP O
set NN I-NP O
of IN B-PP O
dentures NNS B-NP O
. . O O
Neck NN B-NP O
No DT B-NP O
adenopathy NN I-NP O
or CC O O
thyromegaly RB B-ADVP O
. . B-VP O
No DT O O
Bruits NNPS B-NP O
. . O O
Breast NN B-NP O
R NN B-NP O
breast NN I-NP O
is VBZ B-VP O
free JJ B-ADJP O
of IN B-PP O
nodules NNS B-NP O
or CC I-NP O
nodes NNS I-NP O
. . O O
Axillae NNP B-NP O
free JJ I-NP O
of IN B-PP O
nodes NNS B-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
a DT B-NP O
L NNP I-NP O
modified VBN B-VP O
radical JJ B-NP O
mastectomy NN I-NP O
with IN B-PP O
well-healed JJ B-NP O
scar NN I-NP O
and CC O O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
skin NN B-NP O
mets NNS I-NP O
. . O O
Chest NNP B-NP O
Clear JJ B-ADJP O
to TO B-PP O
percussion NN B-NP O
and CC I-NP O
auscultation NN I-NP O
. . O O
Cor CC O O
Heart NNP B-NP O
is VBZ B-VP O
NSR NNP B-NP O
, , O O
without IN B-PP O
murmurs NNS B-NP O
, , O O
gallops NNS B-NP O
, , O O
clicks VBZ B-VP O
or CC I-VP O
ectopy NN I-VP O
, , O O
at IN B-PP O
70 CD B-NP O
per IN B-PP O
minute NN B-NP O
. . O O
Abdomen . O O
No DT B-NP O
liver NN I-NP O
, , O O
spleen VBN B-VP O
or CC I-VP O
other JJ B-NP O
organs NNS I-NP O
or CC I-NP O
masses NNS I-NP O
. . O O
No DT B-NP O
tenderness NN I-NP O
or CC O O
guarding VBG B-VP O
. . O O
Extremity NN B-NP O
Minimal NNP B-NP O
DJD NNP I-NP O
changes NNS I-NP O
in IN B-PP O
her PRP$ B-NP O
knees NNS I-NP O
, , O O
but CC O O
there EX B-NP O
are VBP B-VP O
more JJR B-NP O
marked JJ I-NP O
DJD NN I-NP O
changes NNS I-NP O
in IN B-PP O
her PRP$ B-NP O
hands NNS I-NP O
, , O O
particularly RB B-ADVP O
both DT B-NP O
thumbs NNS I-NP O
with IN B-PP O
some DT B-NP O
early JJ I-NP O
subluxation NN I-NP O
. . O O
Good JJ B-NP O
peripheral JJ I-NP O
pulses NNS I-NP O
. . O O
No DT B-NP O
cyanosis NN I-NP O
or CC I-NP O
clubbing NN I-NP O
, , O O
but CC O O
there EX B-NP O
is VBZ B-VP O
1+ JJ B-NP O
pitting NN I-NP O
edema NN I-NP O
of IN B-PP O
both DT B-NP O
ankles NNS I-NP O
and CC O O
the DT B-NP O
pre-tibial JJ I-NP O
areas NNS I-NP O
. . O O
Neurological JJ O O
Station-Gait NNP B-NP O
; : O O
Cranial NNP B-NP O
nerves NNS I-NP O
, , O O
DTR NNP B-NP O
's POS B-NP O
, , I-NP O
motor NN I-NP O
and CC I-NP O
sensory JJ I-NP O
exams NNS I-NP O
all DT B-NP O
WNL NNP I-NP O
. . O O
Disposition NN B-NP O
and CC I-NP O
Plans NNS I-NP O
Blood NN B-NP O
drawn VBN B-VP O
for IN B-PP O
CBC NNP B-NP O
, , O O
profile NN B-NP O
, , O O
Lipids NNP B-NP O
and CC O O
TSH NNP B-NP O
Urine NNP B-NP O
--N.A. : O O
EKG--Junctional JJ B-NP O
Rhythm NNP I-NP O
without IN B-PP O
LVH NNP B-NP O
or CC I-NP O
ectopy NN I-NP O
. . O O
Patient NNP B-NP O
sent VBD B-VP O
for IN B-PP O
chest NN B-NP O
X-ray NN I-NP O
and CC O O
to TO B-VP O
return VB I-VP O
in IN B-PP O
one CD B-NP O
month NN I-NP O
. . O O
