Record NNP B-NP O
date NN I-NP O
: : O O
2087-10-19 CD O B-DATE
LOVELAND NNP B-NP B-HOSPITAL
INTERNAL NNP I-NP O
MEDICINE NNP I-NP O
ASSOCIATES NNP I-NP O
Youngman NNP I-NP I-PATIENT
, , O I-PATIENT
Cody NNP B-NP I-PATIENT
06386371 CD O B-MEDICALRECORD
10-19-87 CD O B-DATE
HPI NNP B-NP O
: : O O
Ms. NNP B-NP O
Youngman NNP I-NP B-PATIENT
is VBZ B-VP O
a DT B-NP O
30 CD I-NP B-AGE
-year-old JJ I-NP O
woman NN I-NP O
with IN B-PP O
diabetes NN B-NP O
who WP B-NP O
comes VBZ B-VP O
in IN B-ADVP O
for IN B-PP O
a DT B-NP O
regular JJ B-NP O
follow-up NN I-NP O
. . O O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
: : O O
1 LS O O
. . B-NP O
Diabetes NNP I-NP O
. . O O
She PRP B-NP O
said VBD B-VP O
she PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
doing VBG I-VP O
well RB B-ADVP O
, , O O
sticking VBG B-VP O
to TO B-PP O
her PRP$ B-NP O
diet NN I-NP O
, , O O
has VBZ O O
had VBD B-VP O
no DT B-NP O
hypoglycemic JJ I-NP O
episodes NNS I-NP O
, , O O
and CC O O
that IN B-SBAR O
her PRP$ B-NP O
fingersticks NNS I-NP O
have VBP B-VP O
been VBN I-VP O
ranging VBG B-VP O
between IN B-PP O
120 CD B-NP O
and CC I-NP O
160 CD I-NP O
, , O O
never RB B-ADVP O
above IN B-PP O
and CC O O
never RB B-ADVP O
below RB I-ADVP O
. . O O
This DT B-NP O
is VBZ B-LST O
borne VBN B-VP O
out RP B-NP O
by IN B-PP O
her PRP$ B-NP O
last JJ I-NP O
hemoglobin NN I-NP O
A1C . O O
on IN B-PP O
6-04-87 CD B-NP B-DATE
which WDT B-NP O
was VBD B-VP O
4.9 CD B-NP O
. . O O
She PRP O O
definitely RB B-ADVP O
does VBZ B-VP O
have VB I-VP O
good JJ B-NP O
control NN I-NP O
, , O O
and CC O O
she PRP B-NP O
is VBZ B-VP O
working VBG I-VP O
hard RB B-ADVP O
as IN B-PP O
her PRP B-NP O
weight NN B-NP O
is VBZ B-VP O
down RB B-ADVP O
to TO B-PP O
236 CD B-NP O
lb NN I-NP O
from IN B-PP O
238.75 CD B-NP O
on IN B-PP O
6-29-87 CD B-NP B-DATE
. . O O
She PRP B-NP O
had VBD B-VP O
a DT B-NP O
recent JJ I-NP O
hemoglobin NN I-NP O
A1C . O O
and CC O O
urine JJ B-NP O
dip NN I-NP O
. . B-PP O
She PRP B-NP O
, , O O
however RB B-ADVP O
, , O O
is VBZ B-VP O
due JJ B-ADJP O
for IN B-PP O
an DT B-NP O
eye NN I-NP O
exam NN I-NP O
as IN B-SBAR O
she PRP B-NP O
has VBZ B-VP O
no RB I-VP O
had VBD I-VP O
one CD O O
for IN B-PP O
over IN B-NP O
a DT I-NP O
year NN I-NP O
and CC O O
is VBZ B-VP O
willing JJ B-ADJP O
to TO B-VP O
go VB I-VP O
, , O O
so RB O O
I PRP B-NP O
referred VBD B-VP O
her PRP B-NP O
. . O O
She PRP B-NP O
also RB B-ADVP O
needs VBZ B-LST O
to TO B-VP O
see VB I-VP O
a DT B-NP O
Podiatrist NN I-NP O
as IN B-SBAR O
she PRP B-NP O
has VBZ B-VP O
not RB I-VP O
seen VBN I-VP O
one NN B-NP O
; : O O
she PRP B-NP O
will MD B-VP O
go VB I-VP O
. . O O
2. VBG B-VP O
Health NNP B-NP O
maintenance NN I-NP O
. . O O
Patient NNP B-NP O
does VBZ B-VP O
not RB I-VP O
want VB I-VP O
a DT B-NP O
flu NN I-NP O
shot NN I-NP O
. . O O
Otherwise RB B-ADVP O
, , O O
she PRP B-NP O
is VBZ B-VP O
up IN B-ADVP O
to TO B-PP O
date NN B-NP O
except IN B-PP O
for IN B-PP O
a DT B-NP O
Pap NNP I-NP O
smear NN I-NP O
, , O O
but CC O O
she PRP B-NP O
had VBD B-VP O
her PRP B-NP O
daughter NN B-NP O
with IN B-PP O
her PRP$ B-NP O
so RB I-NP O
asked VBN B-VP O
if IN B-SBAR O
she PRP B-NP O
could MD B-VP O
have VB I-VP O
her PRP$ B-NP O
Pap NNP I-NP O
smear NN I-NP O
on IN B-PP O
her PRP$ B-NP O
next JJ I-NP O
visit NN I-NP O
. . O O
We PRP B-NP O
will MD B-VP O
do VB I-VP O
so RB B-ADVP O
. . O O
3. . B-NP O
Migraine NNP I-NP O
headaches NNS I-NP O
. . O O
She PRP B-NP O
said VBD B-VP O
she PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
one CD B-NP O
every DT B-NP O
day NN I-NP O
recently RB B-ADVP O
. . O O
This DT B-NP O
is VBZ B-VP O
worse JJR B-ADJP O
than IN B-PP O
her PRP$ B-NP O
usual JJ I-NP O
. . O O
The DT B-NP O
Motrin NNP I-NP O
was VBD B-VP O
not RB I-VP O
helping VBG I-VP O
. . O O
I PRP B-UCP O
therefore RB B-ADVP O
prescribed VBN B-VP O
Midrin NNP B-NP O
and CC O O
explained VBD B-VP O
to TO B-PP O
her PRP B-NP O
expressly RB B-VP O
how WRB B-ADVP O
to TO O O
use NN B-NP O
. . O O
Should MD O O
this DT B-NP O
not RB B-VP O
help VB I-VP O
, , O O
she PRP B-NP O
will MD B-VP O
page NN I-VP O
me PRP B-NP O
as IN B-SBAR O
she PRP B-NP O
knows VBZ B-VP O
how WRB B-ADVP O
to TO B-VP O
do VB I-VP O
. . O O
I PRP B-NP O
will MD B-VP O
see VB I-VP O
her PRP B-NP O
back RB B-ADVP O
soon RB B-ADVP O
to TO B-VP O
make VB I-VP O
sure JJ B-ADJP O
this DT B-NP O
is VBZ B-VP O
getting VBG I-VP O
better JJR B-ADJP O
. . O O
4 CD B-LST O
. . O O
Ankle NNP B-NP O
pain NN I-NP O
. . O O
Patient NNP B-NP O
has VBZ B-VP O
chronic JJ B-NP O
ankle NN I-NP O
pain NN I-NP O
. . O O
She PRP B-NP O
went VBD B-VP O
to TO B-PP O
an DT B-NP O
Orthopedist NNP B-NP O
who WP B-NP O
told VBD B-VP O
her PRP B-NP O
a DT B-NP O
while NN I-NP O
back RB B-ADVP O
to TO B-PP O
lose VB B-NP O
weight NN I-NP O
and CC O O
see VB B-VP O
if IN B-SBAR O
it PRP B-NP O
got VBD B-VP O
better RB B-ADVP O
. . O O
She PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
slowly RB I-VP O
losing VBG I-VP O
weight NN B-NP O
with IN B-PP O
no DT B-NP O
improvement NN I-NP O
and CC O O
would MD B-VP O
like VB I-VP O
to TO I-VP O
go VB I-VP O
back RB B-ADVP O
to TO B-PP O
the DT B-NP O
Orthopedist NNP I-NP O
. . O O
I PRP B-NP O
therefore RB B-ADVP O
referred VBD B-LST O
her PRP B-NP O
at IN B-PP O
her PRP$ B-NP O
request NN I-NP O
. . O O
Xitlali NNP B-NP B-DOCTOR
Crane NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
FS:XI:4842 . O B-IDNUM
DD NNP B-NP O
: : O O
10-19-87 CD O B-DATE
DT NNP B-NP O
: : O O
10-20-87 CD O B-DATE
DV NNP B-NP O
: : O O
10-19-87 CD O B-DATE
******** NN B-NP O
Approved NNP I-NP O
but CC O O
not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Provider NNP B-NP O
******** . O O
