Record NNP B-NP O
date NN I-NP O
: : O O
2092-02-14 CD O B-DATE
Name NN B-NP O
: : O O
Jennifer NNP B-NP B-PATIENT
Neill NNP I-NP I-PATIENT
MRN NNP B-NP O
: : O O
4634248 CD O B-MEDICALRECORD
CHIEF JJ B-NP O
COMPLAINT NNP I-NP O
: : O O
Followup NN B-NP O
of IN B-PP O
diabetes NNS B-NP O
. . O O
SUBJECTIVE JJ B-NP O
: : O O
Jennifer NNP B-NP B-PATIENT
states NNS I-NP O
that IN B-PP O
at IN B-PP O
home NN B-NP O
her PRP B-NP O
blood NN B-VP O
sugars NNS B-NP O
by IN B-PP O
fingerstick NN B-NP O
typically RB B-ADVP O
went VBD B-VP O
around IN B-PP O
170 CD B-NP O
. . O O
She PRP B-ADVP O
feels VBZ B-VP O
well RB B-PP O
. . O O
She PRP B-NP O
is VBZ B-VP O
not RB I-VP O
having VBG I-VP O
any DT B-NP O
chest NN I-NP O
pains NNS I-NP O
or CC O O
palpitations NNS B-NP O
. . O O
She PRP B-NP O
is VBZ B-VP O
followed VBN I-VP O
by IN B-PP O
cardiology NN B-NP O
at IN B-PP O
PMC NNP B-NP B-HOSPITAL
, , O O
Dr. NNP B-NP O
Samantha NNP I-NP B-DOCTOR
Noland NNP I-NP I-DOCTOR
. . O O
Her PRP$ O O
current JJ B-NP O
medications NNS I-NP O
include VBP B-VP O
atenolol DT B-NP O
25 CD I-NP O
mg JJ I-NP O
p.o NN I-NP O
. . B-NP O
q.d NN I-NP O
. . O O
and CC O O
Zestril NNP B-NP O
20 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d '' O O
. . O O
along IN B-PP O
with IN B-PP O
Glucovance NNP B-NP O
. . O O
She PRP B-NP O
feels VBZ B-VP O
that IN B-SBAR O
the DT B-NP O
atenolol NN I-NP O
is VBZ B-VP O
causing VBG I-VP O
some DT B-NP O
side NN I-NP O
effects NNS I-NP O
. . O O
OBJECTIVE CD B-NP O
: : O O
Appears NNP B-NP O
healthy JJ I-NP O
. . O O
Blood NNP B-NP O
pressure NN I-NP O
132/68 CD B-NP O
. . O O
No DT B-NP O
acute JJ I-NP O
distress NN I-NP O
. . O O
Normal JJ B-NP O
JVP. NNP I-NP O
Lungs NNP I-NP O
clear JJ I-NP O
. . O O
Unremarkable JJ B-NP O
heart NN I-NP O
sounds VBZ B-VP O
. . O O
No DT B-NP O
peripheral JJ I-NP O
edema NN I-NP O
. . O O
ASSESSMENT NNP B-NP O
: : O O
1 LS O O
. . O O
Diabetes NNP O O
with IN B-PP O
suboptimal JJ B-NP O
control NN I-NP O
. . O O
2. DT B-NP O
Hypertension NNP I-NP O
with IN B-PP O
good JJ B-NP O
control NN I-NP O
. . O O
3. DT B-NP O
Possible JJ I-NP O
side NN I-NP O
effects NNS I-NP O
on IN B-PP O
atenolol NN B-NP O
. . O O
PLAN NNP B-NP O
: : O O
1 CD B-NP O
. . O O
Discontinue NNP B-NP O
atenolol VBD B-VP O
. . O O
2. DT B-NP O
Begin NNP I-NP O
Lopressor NNP I-NP O
25 CD I-NP O
mg NN I-NP O
extended VBN I-NP O
release NN I-NP O
1 CD B-NP O
p.o NN I-NP O
. . O O
q.d '' O O
. . O O
3. DT B-NP O
Check NNP I-NP O
glucose NN I-NP O
and CC I-NP O
glycohemoglobin NN I-NP O
and CC O O
adjust VBP B-VP O
medications NNS B-NP O
as IN B-PP O
needed VBN B-NP O
. . O O
William NNP B-NP B-DOCTOR
K. NNP I-NP I-DOCTOR
Joslin NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
, , O O
M.P.H. NNP B-NP O
WKJ NNP B-NP B-DOCTOR
/ NNP I-NP O
3454 CD O B-IDNUM
FI CD B-NP O
: : O O
813458 CD O B-IDNUM
DD NNP B-NP O
: : O O
02/14/92 CD O B-DATE
DT NNP B-NP O
: : O O
02/15/92 CD O B-DATE
