Record NNP B-NP O
date NN I-NP O
: : O O
2096-04-10 CD O B-DATE
GLENN NNP B-NP B-HOSPITAL
HELEN NNP I-NP I-HOSPITAL
EMERGENCY NNP I-NP O
DEPT NNP I-NP O
VISIT NNP I-NP O
VINCENT,ROBERTA NNP B-NP B-PATIENT
J. NNP I-NP I-PATIENT
380-18-32-2 CD O B-MEDICALRECORD
HISTORY NN B-NP O
OF IN B-PP O
PRESENTING JJ B-NP O
COMPLAINT NN I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
a DT B-NP O
59 CD I-NP B-AGE
-year-old NN I-NP O
female NN B-NP O
who WP B-NP O
is VBZ B-VP O
status NN B-NP O
post NN I-NP O
renal NN I-NP O
transplant NN I-NP O
with IN B-PP O
history NN B-NP O
of IN B-PP O
hypertension NN B-NP O
and CC I-NP O
diabetes NN I-NP O
who WP B-NP O
presents VBZ B-VP O
complaining VBG I-VP O
of IN B-PP O
recurrent JJ B-NP O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
. . O O
She PRP B-NP O
had VBD B-VP O
a DT B-NP O
renal JJ I-NP O
transplant NN I-NP O
in IN B-PP O
2093 CD B-NP B-DATE
with IN B-PP O
history NN B-NP O
of IN B-PP O
chronic JJ B-NP O
renal JJ I-NP O
insufficiency NN I-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
last JJ B-NP O
admitted VBN I-NP O
here RB B-LST O
on IN B-PP O
February NNP B-NP B-DATE
23 CD I-NP I-DATE
for IN B-PP O
shortness NN B-NP O
of IN B-PP O
breath NN B-NP O
. . O O
The DT B-NP O
patient NN I-NP O
has VBZ B-VP O
had VBN I-VP O
sore JJ O O
throat NN B-NP O
and CC I-NP O
URI NNP I-NP O
symptoms NNS I-NP O
now RB B-ADVP O
for IN B-PP O
a DT B-NP O
few JJ I-NP O
days NNS I-NP O
. . O O
No DT B-NP O
nausea NN I-NP O
and CC O O
vomiting NN B-NP O
. . O O
No DT B-NP O
sweating NN I-NP O
. . B-PP O
No DT B-NP O
chest NN I-NP O
pain NN I-NP O
or CC I-NP O
dizziness NN I-NP O
. . O O
PAST NN B-NP O
MEDICAL NNP I-NP O
HISTORY NNP I-NP O
: : O O
Complicated VBN B-VP O
by IN B-PP O
hypertension NN B-NP O
, , O O
diabetes NNS B-NP O
, , O O
pedal NN B-NP O
neuropathy NN B-NP O
, , I-NP O
hernia NN I-NP O
, , O O
and CC O O
hysterectomy NN B-NP O
. . O O
MEDICATIONS NNS B-NP O
: : O O
Premarin NNP B-NP O
, , O O
insulin NN B-NP O
, , O O
Prilosec NNP B-NP O
, , O O
prednisone NN B-NP O
, , O O
and CC O O
sodium NN B-NP O
bicarbonate NN B-NP O
. . O O
She PRP B-NP O
is VBZ B-VP O
also RB B-ADVP O
on IN B-PP O
Lasix NNP B-NP O
, , O O
hydralazine NN B-NP O
, , O O
and CC O O
Talwin NNP B-NP O
. . O O
PHYSICAL NNP B-NP O
EXAMINATION NNP I-NP O
: : O O
She PRP B-NP O
is VBZ B-VP O
afebrile JJ B-ADJP O
. . O O
Vital JJ B-NP O
signs NNS I-NP O
are VBP B-VP O
normal JJ B-ADJP O
. . O O
Oxygen NNP B-NP O
saturation NN I-NP O
97 CD B-NP O
% NN I-NP O
. . O O
Initial JJ O O
blood NN B-NP O
pressure NN I-NP O
is VBZ B-VP O
214/118 CD B-NP O
. . O O
The DT O O
second JJ B-NP O
blood NN I-NP O
pressure NN I-NP O
is VBZ B-VP O
188/100 CD B-NP O
. . O O
HEENT NNP B-NP O
: : O O
Normal JJ B-NP O
. . I-NP O
Cardiac NNP I-NP O
: : O O
No UH O O
murmurs NNS B-NP O
or CC I-NP O
rubs NNS I-NP O
. . O O
Lungs NNP B-NP O
: : O O
Crackles NNP B-NP O
bilaterally RB B-ADVP O
, , O O
but CC O O
no DT B-NP O
wheezing NN I-NP O
. . O O
Abdomen NNP B-NP O
: : O O
Soft NNP B-NP O
and CC I-NP O
nontender NN I-NP O
with IN B-PP O
good JJ B-NP O
bowel NN I-NP O
sounds NNS I-NP O
. . O O
Extremities NNS B-NP O
: : O O
Trace NNP B-NP O
pedal NN I-NP O
edema NN I-NP O
1+ VBD B-VP O
throughout IN B-PP O
. . B-NP O
Neuro NNP I-NP O
: : O O
Intact NN B-NP O
. . O O
LABORATORY NNP B-NP O
EVALUATION NNP I-NP O
: : O O
Electrolytes NNP B-NP O
here RB B-ADVP O
are VBP B-VP O
normal JJ B-ADJP O
. . O O
Creatinine '' O O
is VBZ B-VP O
pretty RB B-ADJP O
good JJ I-ADJP O
. . O O
She PRP B-NP O
was VBD B-VP O
4.4 CD B-NP O
on IN B-PP O
February NNP B-NP B-DATE
26 CD I-NP I-DATE
. . O O
She PRP B-NP O
is VBZ B-VP O
3.3 CD B-NP O
now RB B-ADVP O
, , O O
so RB O O
she PRP B-NP O
has VBZ B-VP O
improved VBN I-VP O
in IN B-PP O
creatinine CD B-NP O
. . O O
White NNP B-NP O
count VBP I-NP O
is VBZ B-VP O
12.9 CD B-NP O
and CC O O
hematocrit NN B-NP O
of IN B-PP O
36 CD B-NP O
. . O O
EKG NNP B-NP O
showed VBD B-VP O
sinus IN B-PP O
rhythm NN B-NP O
at IN B-PP O
97 CD B-NP O
, , O O
old JJ B-NP O
left NN I-NP O
ventricular NN I-NP O
hypertrophy NN B-NP O
, , O O
and CC O O
no DT B-NP O
acute JJ I-NP O
changes NNS I-NP O
. . O O
Chest NNP B-NP O
x-ray NN I-NP O
shows VBZ B-VP O
increased VBN I-VP O
chronic NN B-NP O
pulmonary NN I-NP O
edema NN I-NP O
and CC O O
old JJ B-NP O
small JJ I-NP O
right JJ I-NP O
pleural JJ I-NP O
fluid NN I-NP O
seen VBN B-VP O
. . O O
CONSULTATIONS NNS B-NP O
( -LRB- B-VP O
including VBG B-NP O
PCP) NNP I-NP O
: : O O
The DT B-NP O
Renal NNP I-NP O
fellow NN I-NP O
is VBZ B-VP O
here RB B-ADVP O
. . O O
The DT B-NP O
case NN I-NP O
has VBZ B-VP O
been VBN I-VP O
discussed VBN I-VP O
with IN B-PP O
the DT B-NP O
Renal NNP I-NP O
fellow NN I-NP O
. . O O
ADMITTING NNP B-NP O
DIAGNOSIS NNP I-NP O
: : O O
Congestive NNP B-NP O
heart NN I-NP O
failure NN I-NP O
and CC I-NP O
hypertension NN I-NP O
. . O O
DISPOSITION NN B-NP O
( -LRB- I-NP O
including VBG I-NP O
condition NN I-NP O
upon IN B-PP O
discharge NN B-NP O
) -RRB- I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
is VBZ B-LST O
going VBG B-VP O
to TO I-VP O
be VB I-VP O
admitted VBN I-VP O
to TO B-PP O
the DT B-NP O
Renal NNP I-NP O
Service NNP I-NP O
, , O O
admitted VBD B-VP O
to TO B-PP O
Dr. NNP B-NP O
Elias NNP I-NP B-DOCTOR
Mercado NNP B-NP I-DOCTOR
. . I-NP O
Admitted NNP I-NP O
in IN B-PP O
stable JJ B-NP O
condition NN I-NP O
. . O O
VC341/8846 CD O B-IDNUM
DEXTER NNP B-NP B-DOCTOR
N. NNP I-NP I-DOCTOR
JOHNSON NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
DJ50 NNP I-NP B-USERNAME
D NNP I-NP O
: : O O
04/10/96 CD O B-DATE
T NNP B-NP O
: : O O
04/10/96 CD O B-DATE
Dictated VBN B-VP O
by IN B-PP O
: : O O
DEXTER NNP B-NP B-DOCTOR
N. NNP I-NP I-DOCTOR
JOHNSON NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
DJ50 . O B-USERNAME
******** NN B-NP O
Not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Physician JJ B-NP O
******** NNS I-NP O
