Record NNP B-NP O
date NN I-NP O
: : O O
2067-01-28 CD O B-DATE
INTERNAL NNP B-NP O
MEDICINE NNP I-NP O
ASSOCIATES NNPS I-NP O
OCHILTREE NN B-NP B-HOSPITAL
GENERAL NNP I-NP I-HOSPITAL
HOSPITAL NNP I-NP I-HOSPITAL
Reason NN B-NP O
for IN B-PP O
visit NN B-NP O
URI . O O
History NN B-NP O
of IN B-PP O
present JJ B-NP O
illness NN I-NP O
Pt NNP I-NP O
has VBZ B-VP O
URI NNP B-NP O
with IN B-PP O
cough NN B-NP O
for IN B-PP O
several JJ B-NP O
weeks NNS I-NP O
. . O O
The DT B-NP O
majority NN I-NP O
of IN B-PP O
this DT B-NP O
25 CD I-NP O
minute JJ I-NP O
visit NN I-NP O
was VBD B-VP O
spent VBN I-VP O
in IN B-PP O
counseling VBG B-VP O
about IN B-PP O
hid VBN B-NP O
drinking NN I-NP O
. . O O
Major NNP B-NP O
Problems NNS I-NP O
Diabetes NNP B-NP O
mellitus NN I-NP O
(adult NN I-NP O
onset NN I-NP O
) -RRB- O O
No DT B-NP O
sx NN I-NP O
. . O O
HB NNP B-NP O
A1c NNP I-NP O
was VBD B-VP O
good JJ B-NP O
last JJ I-NP O
month NN I-NP O
. . O O
Hyperlipidemia NNP B-NP O
has VBZ O O
started VBN B-NP O
lipitor NN I-NP O
without IN B-PP O
problem NN B-NP O
about IN B-PP O
a DT B-NP O
month NN I-NP O
ago RB B-ADVP O
. . O O
Not RB B-VP O
fasting VBG I-VP O
today NN B-NP O
. . O O
Other JJ B-NP O
Problems NNS I-NP O
Cough IN O O
Pt NNP B-NP O
had VBD B-VP O
uri VBN I-VP O
about IN B-PP O
a DT B-NP O
month NN I-NP O
ago RB B-ADVP O
. . O O
He PRP B-NP O
has VBZ B-VP O
continued VBN I-VP O
to TO I-VP O
have VB I-VP O
disturbing JJ B-NP O
cough NN I-NP O
after IN B-PP O
acute JJ B-NP O
symptoms NNS I-NP O
resolved VBD B-VP O
. . O O
He PRP B-NP O
describes VBZ B-VP O
cough NN B-NP O
worse JJR B-ADJP O
in IN B-PP O
cold JJ B-NP O
air NN I-NP O
, , O O
starting VBG B-VP O
after IN B-SBAR O
he PRP B-NP O
gets VBZ B-VP O
into IN B-PP O
the DT B-NP O
weather NN I-NP O
. . O O
No DT B-NP O
scarf NN I-NP O
. . O O
No DT B-NP O
history NN I-NP O
of IN B-PP O
asthma NN B-NP O
. . O O
No DT B-NP O
supine NN I-NP O
sx NN I-NP O
. . O O
Exam NNP B-NP O
neg NN I-NP O
. . O O
Offered VBD B-VP O
alupent DT B-NP O
inhaler NN I-NP O
and CC O O
instructed VBD B-VP O
to TO I-VP O
use VB I-VP O
muffler NN B-NP O
for IN B-PP O
probable JJ B-NP O
dx NN I-NP O
of IN B-PP O
cold JJ B-NP O
induced VBN I-NP O
asthma NN I-NP O
. . O O
Depression NN B-NP O
Subject NNP B-NP O
came VBD B-VP O
up RP B-PRT O
re RB B-ADVP O
asking VBG B-VP O
about IN B-PP O
drinking NN B-NP O
( -LRB- I-NP O
potential JJ I-NP O
relation NN I-NP O
to TO B-PP O
cough NN B-NP O
) -RRB- I-NP O
. . O O
He PRP B-NP O
drank VBD B-VP O
heavily RB B-ADVP O
after IN B-PP O
Korea NNP B-NP B-COUNTRY
( -LRB- I-NP O
field NN I-NP B-PROFESSION
nurse NN I-NP I-PROFESSION
) -RRB- I-NP O
and CC O O
had VBD B-VP O
depression NN B-NP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
. . O O
He PRP B-NP O
had VBD B-VP O
SI NNP B-NP O
about IN B-PP O
18 CD B-NP O
months NNS I-NP O
ago RB B-ADVP O
. . O O
Now RB B-VP O
seeing VBG I-VP O
Navarro NNP B-NP B-DOCTOR
( -LRB- I-NP O
rx NN I-NP O
) -RRB- I-NP O
and CC I-NP O
Lacey JJ I-NP B-DOCTOR
Frost NNP I-NP I-DOCTOR
( -LRB- I-NP O
Tx NN I-NP O
) -RRB- I-NP O
ans NNS I-NP O
is VBZ B-VP O
on IN B-NP O
two CD I-NP O
drugs NNS I-NP O
paxil NN B-ADVP O
and CC O O
another DT B-NP O
. . B-NP O
States NNS I-NP O
they PRP B-NP O
reliably RB B-VP O
cause VB I-VP O
him PRP B-NP O
to TO B-VP O
vomit VB I-VP O
if IN B-SBAR O
he PRP B-NP O
drinks VBZ B-VP O
. . B-NP O
States NNP I-NP O
drinks VBZ B-VP O
two CD B-NP O
rums NNS I-NP O
and CC I-NP O
diet NN I-NP O
coke NN I-NP O
a DT B-NP O
night NN I-NP O
. . O O
Thinks NNS B-VP O
he PRP B-NP O
should MD B-VP O
stop VB I-VP O
; : I-VP O
discussed VBN I-VP O
; : O O
needs NNS B-NP O
to TO B-VP O
bring VB I-VP O
this DT B-NP O
up RP I-NP O
with IN B-PP O
his PRP$ B-NP O
tx NN I-NP O
. . O O
Not RB B-VP O
si FW I-VP O
now RB B-ADVP O
, , O O
states NNS B-NP O
mood NN I-NP O
stable JJ I-NP O
. . O O
Change NNP B-NP O
in IN B-PP O
therapies NNS B-NP O
and CC I-NP O
Renewals NNS I-NP O
Proventil JJ B-NP O
two CD I-NP O
puffs NNS I-NP O
inhaled VBD B-VP O
qid VBN I-VP O
QTY NNP B-NP O
:1 CD I-NP O
cannister NN I-NP O
Refills NNP B-NP O
:3 CD I-NP O
Start NNP I-NP O
: : O O
01/28/2067 CD B-NP B-DATE
prn NN I-NP O
Habits PRP$ O O
Alcohol NNP B-NP O
use NN I-NP O
status NN I-NP O
: : O O
major JJ O O
Physical JJ B-NP O
examination NN I-NP O
Pulse NNP B-NP O
70 CD I-NP O
Blood NN B-NP O
pressure NN I-NP O
160/90 CD O O
Weight NNP B-NP O
210 CD I-NP O
216 CD I-NP O
pounds NNS I-NP O
General NNP B-NP O
appearance NN I-NP O
Well RB B-VP O
developed VBN I-VP O
, , O O
well RB B-ADVP O
nourished JJ B-ADJP O
, , O O
in IN B-PP O
no DT B-NP O
acute JJ I-NP O
distress NN I-NP O
Skin NNP B-NP O
Clear NNP I-NP O
Heent NNP B-NP O
Eyes NNP I-NP O
, , O O
nonicteric JJ B-NP O
. . O O
Nose DT O O
clear JJ B-ADJP O
. . O O
Pharynx NNP O O
normal JJ O O
. . B-NP O
Ears NNS I-NP O
normal JJ O O
Neck NNP B-NP O
No DT I-NP O
masses NNS I-NP O
Chest NNP B-NP O
Lungs NNP I-NP O
are VBP B-VP O
clear JJ I-VP O
Cor NNP B-NP O
Regular NNP I-NP O
rhythm NN I-NP O
. . O O
S1 . O O
and CC O O
S2 JJ B-NP O
normal JJ I-NP O
. . O O
No DT B-NP O
murmur NN I-NP O
, , O O
S3 NNP B-NP O
, , O O
or CC O O
S4 CD O O
temperature NN B-NP O
98.0 CD I-NP O
Disposition NN B-NP O
return NN B-NP O
in IN B-PP O
two CD B-NP O
months NNS I-NP O
; : O O
obtain VB B-VP O
fasting JJ B-NP O
lipids NNS I-NP O
before IN B-PP O
then RB B-NP O
. . O O
Signed VBN B-VP O
electronically RB B-ADVP O
by IN B-PP O
Miranda NNP B-NP I-DOCTOR
, , O I-DOCTOR
James NNP B-NP I-DOCTOR
R NN I-NP I-DOCTOR
on IN B-PP O
Jan NNP B-NP B-DATE
29 CD I-NP I-DATE
, , I-NP I-DATE
2067 CD O I-DATE
