Record NNP B-NP O
date NN I-NP O
: : O O
2072-07-27 CD O B-DATE
Narrative JJ B-NP O
History NN I-NP O
Patient NNP B-NP O
presents NNS I-NP O
for IN B-PP O
an DT B-NP O
annual JJ I-NP O
exam NN I-NP O
. . O O
Not RB B-VP O
seen VBN I-VP O
for IN B-PP O
almost RB B-NP O
2 CD I-NP O
years NNS I-NP O
. . O O
State NNP B-NP O
she PRP B-NP O
's VBZ B-VP O
had VBD I-VP O
a DT B-NP O
very RB I-NP O
difficult JJ I-NP O
time NN I-NP O
with IN B-PP O
her PRP$ B-NP O
husband NN I-NP O
's POS B-NP O
death NN I-NP O
2070 CD I-NP B-DATE
. . O O
Angry NNP B-NP O
and CC O O
sad JJ B-NP O
and CC I-NP O
guilty JJ I-NP O
feelings NNS I-NP O
. . O O
Had VBD B-VP O
been VBN I-VP O
staying VBG I-VP O
at IN B-PP O
home NN B-NP O
a DT B-NP O
lot NN I-NP O
, , O O
missing VBG B-VP O
a DT B-NP O
fair JJ I-NP O
amount NN I-NP O
of IN B-PP O
work NN B-NP O
. . O O
Did VBD B-VP O
have VB I-VP O
a DT B-NP O
lot NN I-NP O
of IN B-PP O
support NN B-NP O
from IN B-PP O
her PRP$ B-NP O
neighbors NNS I-NP O
and CC I-NP O
coworkers NNS I-NP O
. . O O
Also RB O O
does VBZ B-VP O
live VB I-VP O
with IN B-PP O
her PRP$ B-NP O
son NN I-NP O
. . O O
Just RB O O
seems VBZ B-VP O
to TO I-VP O
be VB I-VP O
coming VBG I-VP O
out IN B-ADVP O
of IN B-PP O
it PRP B-NP O
now RB B-ADVP O
. . O O
GYN NNP B-NP O
- : O O
no DT B-NP O
vaginal JJ I-NP O
bleeding NN I-NP O
, , O O
not RB O O
sexually RB B-ADJP O
active JJ I-ADJP O
. . O O
Exercise NNP B-NP O
- : O O
none NN B-NP O
, , O O
Problems NNS B-NP O
FH NNP B-NP O
breast NN I-NP O
cancer NN I-NP O
: : O O
37 CD B-NP B-AGE
yo PRP B-ADVP O
s VBZ B-VP O
-died JJ B-NP O
41 CD I-NP B-AGE
FH NNP B-NP O
myocardial JJ I-NP O
infarction NN I-NP O
: : O O
mother NN B-NP O
died VBD B-VP O
66 CD B-NP B-AGE
yo CD I-NP O
Hypertension NNP B-NP O
-borderline NN I-NP O
today NN I-NP O
- : O O
check NN B-NP O
chem NN I-NP O
7 CD B-NP O
, , O O
refilled VBN B-VP O
all DT B-NP O
her PRP$ I-NP O
medications NNS I-NP O
. . O O
Will MD B-VP O
start VB I-VP O
doing VBG I-VP O
some DT B-NP O
exercise NN I-NP O
and CC O O
trying VBG B-VP O
to TO I-VP O
lose VB I-VP O
weight NN B-NP O
. . O O
Uterine NNP B-NP O
fibroids NNS I-NP O
: : O O
u/s NNS B-NP O
2062 VBP B-VP B-DATE
-not RB I-VP O
seen VBN I-VP O
Dr NNP B-NP O
Foust NNP I-NP B-DOCTOR
since IN B-PP O
2066 CD B-NP B-DATE
when WRB B-ADVP O
difficult JJ B-ADJP O
to TO B-VP O
obtain VB I-VP O
her PRP$ B-NP O
Pap NNP I-NP O
smear NN I-NP O
. . O O
Smoking VBG B-VP O
: : O O
quit VB B-VP O
2/67 PRP B-NP B-DATE
s/p VB B-VP O
MI NNP B-NP O
- : O O
still RB B-VP O
not RB I-VP O
smoking NN I-VP O
! . O O
borderline NN B-NP O
diabetes VBZ B-VP O
mellitus JJ B-ADJP O
: : O O
4/63 CD B-NP B-DATE
125 CD I-NP O
, , O O
follow VB B-VP O
hgbaic NN B-NP O
- : O O
was VBD B-VP O
6.5/131 CD B-NP O
in IN B-PP O
12/70 CD B-NP B-DATE
, , O O
gradually RB B-ADVP O
rising VBG B-NP O
, , O O
recheck VB B-VP O
glc NN B-NP O
and CC O O
a1c JJ B-NP O
today NN I-NP O
VPB NNP B-NP O
: : O O
2065 CD B-NP B-DATE
- : O O
ETT NNP B-NP O
showed VBD B-VP O
freq JJ B-NP O
PVC's NNP I-NP O
, , I-NP O
bigeminy JJ I-NP O
and CC I-NP O
couplets NNS I-NP O
, , O O
nondx JJ B-ADJP O
for IN B-PP O
ischemia NN B-NP O
- : O O
denies VBZ B-VP O
palp NN B-NP O
or CC I-NP O
dizziness NN I-NP O
. . O O
Does VBZ B-VP O
occasionally RB I-VP O
feel VB I-VP O
a DT B-NP O
split JJ I-NP O
second JJ I-NP O
palpitation NN I-NP O
. . O O
Takes VBZ B-VP O
a DT B-NP O
deep JJ I-NP O
breath NN I-NP O
and CC O O
it PRP B-NP O
goes VBZ B-VP O
away RB B-ADVP O
. . O O
No DT B-NP O
associated VBN I-NP O
symptoms NNS I-NP O
. . O O
Perhaps RB B-VP O
feels VBZ I-VP O
it PRP B-NP O
twice RB B-PP O
a DT B-NP O
month NN I-NP O
. . O O
Will MD B-VP O
check VB I-VP O
electrolytes NNS B-NP O
and CC O O
TSH. NNP B-NP O
Coronary JJ B-NP O
artery NN I-NP O
disease NN I-NP O
: : O O
s/p JJ B-NP O
ant JJ I-NP O
SEMI NNP I-NP O
+ NNP I-NP O
stent NN I-NP O
LAD NN I-NP O
2/67 CD B-NP B-DATE
, , O O
Dr NNP B-NP O
Oakley NNP I-NP B-DOCTOR
, , O O
ETT NNP B-NP O
Clarkfield NNP I-NP B-HOSPITAL
3/67 CD I-NP B-DATE
- : O O
neg NN B-VP O
scan NN B-NP O
for IN B-PP O
ischemia NN B-NP O
. . O O
No DT O O
CP NNP B-NP O
's POS B-NP O
, , I-NP O
palp NN I-NP O
. . O O
Not RB B-VP O
seen VBN I-VP O
cardiology NN B-NP O
for IN B-PP O
two CD B-NP O
to TO I-NP O
3 CD I-NP O
years NNS I-NP O
. . O O
Will MD B-VP O
make VB I-VP O
follow-up JJ B-ADJP O
with IN B-PP O
cardiology NN B-NP O
now RB B-ADVP O
that IN B-PP O
Dr NNP B-NP O
Oakley NNP I-NP B-DOCTOR
gone VBN O O
thyroid JJ B-NP O
nodule NN I-NP O
: : O O
2065 CD B-NP B-DATE
, , O O
hot JJ B-ADVP O
, , O O
follow VBP B-VP O
TSH. NNP B-NP O
TReated NNP I-NP O
with IN B-PP O
RAI NNP B-NP O
February NNP I-NP B-DATE
2071 CD I-NP I-DATE
. . O O
Last JJ B-NP O
TSH NNP I-NP O
checked VBD B-VP O
12/71 CD B-NP B-DATE
and CC O O
was VBD B-VP O
in IN B-PP O
the DT B-NP O
normal JJ I-NP O
range NN I-NP O
. . O O
To TO B-VP O
see VB I-VP O
Dr. NNP B-NP O
Dolan NNP I-NP B-DOCTOR
q NNP I-NP O
. . B-NP O
year NN I-NP O
. . O O
Hyperlipidemia NNP B-NP O
: : O O
CRF NNP B-NP O
mild JJ I-NP O
chol NN I-NP O
, , O O
cigs NNS B-NP O
, , O O
HTN NNP B-NP O
, , O O
Fhx NNP B-NP O
and CC O O
known VBN B-VP O
hx NN B-NP O
CAD NN I-NP O
in IN B-PP O
pt NN B-NP O
. . O O
in IN B-PP O
January NNP B-NP B-DATE
2071 CD I-NP I-DATE
she PRP B-NP O
was VBD B-VP O
written VBN I-VP O
to TO I-VP O
increase VB I-VP O
her PRP$ B-NP O
Lipitor NN I-NP O
to TO B-PP O
40 CD B-NP O
mg NN I-NP O
and CC O O
then RB B-ADVP O
to TO B-PP O
follow-up JJ B-NP O
in IN B-PP O
March NNP B-NP B-DATE
. . O O
She PRP B-NP O
never RB B-ADVP O
did VBD B-VP O
increase VB I-VP O
the DT B-NP O
dose NN I-NP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
. . O O
Check VB B-VP O
lfts NNS B-NP O
and CC O O
cholesterol NN B-NP O
fasting NN I-NP O
next JJ B-NP O
week NN I-NP O
, , O O
and CC O O
then RB B-ADVP O
can MD B-VP O
decide VB I-VP O
if IN B-SBAR O
we PRP B-NP O
need VBP B-VP O
to TO I-VP O
increase VB I-VP O
the DT B-NP O
Lipitor NNP I-NP O
. . I-NP O
Will NNP I-NP O
aim NN I-NP O
for IN B-PP O
LDL NNP B-NP O
less JJR I-NP O
than IN I-NP O
100 CD I-NP O
Medications NNS B-NP O
Asa NNP B-NP O
(ACETYLSALICYLIC NN I-NP O
ACID NNP I-NP O
) -RRB- I-NP O
325MG JJ I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Nitroglycerin NNP B-NP O
1/150 CD I-NP O
( -LRB- I-NP O
0.4 CD I-NP O
MG) NN I-NP O
1 CD I-NP O
TAB NNP I-NP O
SL NNP I-NP O
x1 NNP I-NP O
PRN NNP I-NP O
prn NN I-NP O
CP CD O O
Norvasc NNP B-NP O
( -LRB- I-NP O
AMLODIPINE NNP I-NP O
) -RRB- I-NP O
5MG VBP I-NP O
TABLET NNP I-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Triamcinolone NN B-NP O
CREAM NNP I-NP O
0.5 CD I-NP O
% NN I-NP O
( -LRB- I-NP O
TRIAMCINOLONE NNP I-NP O
ACETONIDE NNP I-NP O
0.5 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
TOP NNP I-NP O
BID NNP I-NP O
PRN NNP I-NP O
Lipitor NNP B-NP O
( -LRB- I-NP O
ATORVASTATIN NNP I-NP O
) -RRB- I-NP O
20MG . I-NP O
TABLET NNP I-NP O
PO NNP I-NP O
QD . O O
Zestril NNP B-NP O
( -LRB- I-NP O
LISINOPRIL NNP I-NP O
) -RRB- I-NP O
40MG VBP I-NP O
TABLET NNP I-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Atenolol NNP B-NP O
50MG VBD B-VP O
TABLET NNP B-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Hctz NNP B-NP O
( -LRB- I-NP O
HYDROCHLOROTHIAZIDE NNP I-NP O
) -RRB- I-NP O
25MG . I-NP O
TABLET NNP I-NP O
take VB B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
Ativan NNP B-NP O
( -LRB- I-NP O
LORAZEPAM NNP I-NP O
) -RRB- I-NP O
1 CD I-NP O
MG NNP I-NP O
( -LRB- I-NP O
1MG JJ I-NP O
TABLET NNP I-NP O
take NN I-NP O
1 CD B-NP O
) -RRB- I-NP O
PO NN I-NP O
qhs NNS I-NP O
PRN NNP I-NP O
, , O O
dea# NN B-NP O
pf NN I-NP B-IDNUM
0760305 CD O I-IDNUM
Allergies . O O
CEFACLOR JJ O O
- : O O
Rash NN B-NP O
, , O O
Family NNP B-NP O
History NN I-NP O
father NN B-NP O
-HTN NNP I-NP O
, , O O
85 CD B-NP B-AGE
now RB I-NP O
mother-HTN NN B-NP O
, , O O
MI NNP B-NP O
at IN B-PP O
58 CD B-NP B-AGE
and CC I-NP O
62 CD I-NP B-AGE
- : O O
died VBD B-VP O
then RB O O
siblings-sister NN B-NP O
finally RB B-VP O
died VBD I-VP O
from IN B-PP O
breast NN B-NP O
CA NNP I-NP O
after IN B-PP O
4 CD B-NP O
year NN I-NP O
battle NN I-NP O
, , O O
dx NN B-NP O
age NN I-NP O
37 CD I-NP B-AGE
. . O O
7 CD B-NP O
sisters NNS I-NP O
- : O O
one CD B-NP O
with IN B-PP O
DM,and NNP B-NP O
2 CD I-NP O
brothers NNS I-NP O
- : O O
ok NN B-NP O
No DT B-NP O
change NN I-NP O
since IN B-PP O
previous JJ B-NP O
annual JJ I-NP O
. . O O
Social NNP B-NP O
History NNP I-NP O
working VBG B-VP O
for IN B-PP O
Convergys NNP B-NP B-ORGANIZATION
as IN B-PP O
Sculptor NNP B-NP B-PROFESSION
, , O O
widowed VBD B-VP O
2070 CD B-NP B-DATE
, , O O
one CD B-NP O
son NN I-NP O
- : O O
29 CD B-NP B-AGE
yo PRP B-NP O
who WP B-NP O
lives VBZ B-VP O
with IN B-PP O
her PRP$ B-NP O
- : O O
Specialized NNP B-NP B-PROFESSION
Livestock NNP I-NP I-PROFESSION
Worker NNP I-NP I-PROFESSION
Review NNP B-NP O
of IN I-NP O
Systems NNPS O O
The DT B-NP O
following VBG I-NP O
systems NNS I-NP O
were VBD B-VP O
reviewed VBN I-VP O
today NN B-NP O
and CC O O
were VBD B-VP O
negative JJ B-ADJP O
unless IN B-SBAR O
indicated VBN B-VP O
otherwise RB B-ADVP O
in IN B-PP O
the DT B-NP O
history NN I-NP O
noted VBD B-VP O
above IN B-ADVP O
: : O O
Constitutional NNP B-NP O
, , O O
HEENT NNP B-NP O
, , O O
Breast,CVS NNP B-NP O
, , O O
GI NNP B-NP O
, , O O
GYN NNP B-NP O
, , O O
Skin NNP B-NP O
, , O O
Musculoskeletal NNP B-NP O
, , O O
Neuro NNP B-NP O
, , O O
Psych NNP B-NP O
, , O O
Respiratory NNP B-NP O
, , O O
and CC O O
Allergic NNP B-NP O
Physical NNP B-NP O
Exam NNP I-NP O
Vital JJ B-NP O
Signs NNS I-NP O
BLOOD NN B-NP O
PRESSURE JJ I-NP O
148/76 CD O O
PULSE NNP B-NP O
60 CD I-NP O
HEIGHT NNP B-NP O
65 CD I-NP O
in IN O O
WEIGHT NNP B-NP O
217.5 CD I-NP O
lb NN I-NP O
BMI NNP B-NP O
36.3 CD I-NP O
up IN B-PP O
3 CD B-NP O
lbs NNS I-NP O
General NNP B-NP O
: : O O
appears VBZ B-VP O
well RB O O
HEENT NNP B-NP O
: : O O
EOMI NNP B-NP O
, , O O
PERRL NNP B-NP O
, , O O
OP NNP B-NP O
normal JJ I-NP O
Skin NNP B-NP O
: : O O
no DT B-NP O
suspicious JJ I-NP O
lesions NNS I-NP O
Neck NNP B-NP O
: : O O
no DT B-NP O
thyromegaly NN I-NP O
, , O O
no DT B-NP O
bruits NNS I-NP O
Nodes NNP B-NP O
: : O O
no DT B-NP O
cervical JJ I-NP O
, , I-NP O
axillary NN I-NP O
, , I-NP O
or CC I-NP O
supraclavicular JJ I-NP O
lymphadenopathy NN I-NP O
Breasts NNS B-NP O
- : O O
no DT B-NP O
nipple NN I-NP O
discharge NN I-NP O
or CC I-NP O
retraction NN I-NP O
, , O O
no DT B-NP O
dominant JJ I-NP O
masses NNS I-NP O
Chest NNP B-NP O
: : O O
clear JJ B-ADJP O
to TO B-PP O
auscultation NN B-NP O
, , O O
no DT B-NP O
rhonchi NN I-NP O
or CC I-NP O
wheeze NN I-NP O
COR JJ B-NP O
: : O O
regular JJ B-NP O
S1 NNP I-NP O
, , O O
S2 NNP B-NP O
, , O O
no DT B-NP O
murmurs NNS I-NP O
, , I-NP O
rubs NNS I-NP O
or CC I-NP O
gallops NNS I-NP O
Abd NNP B-NP O
: : B-VP O
soft JJ B-ADJP O
, , O O
NT NNP B-NP O
, , O O
no DT B-NP O
HSM NNP I-NP O
or CC I-NP O
masses NNS I-NP O
Musculoskeletal NNP B-NP O
: : O O
no DT B-NP O
erythema NN I-NP O
, , O O
swelling VBG B-VP O
, , O O
or CC O O
tenderness NN B-NP O
Ext JJ B-NP O
: : O O
no DT B-NP O
CCE NNP I-NP O
, , O O
Neuro NNP B-NP O
: : O O
grossly RB B-ADJP O
non-focal JJ I-ADJP O
Health NNP B-NP O
Maintenance NNP I-NP O
Influenza NNP B-NP O
Vaccine NNP I-NP O
11/29/2067 CD O B-DATE
Cholesterol NNP B-NP O
12/16/2070 CD I-NP B-DATE
172 CD O O
Mammogram NNP B-NP O
03/01/64 MD B-VP B-DATE
see VB I-VP O
report NN B-NP O
in IN B-PP O
Results NNS B-NP O
Pap NNP B-NP O
Smear NNP I-NP O
12/16/2070 CD I-NP B-DATE
see VBP B-VP O
report NN B-NP O
in IN B-PP O
Results NNS B-NP O
UA-Protein NNP B-NP O
03/12/2066 CD I-NP B-DATE
NEGATIVE CD O O
Colonoscopy NNP B-NP O
06/04/2071 CD I-NP B-DATE
see VBP B-VP O
report NN B-NP O
in IN B-PP O
Results NNS B-NP O
Urine NNP B-NP O
Culture NNP I-NP O
03/12/2066 JJS I-NP B-DATE
see VBP B-VP O
report NN B-NP O
in IN B-PP O
Results NNS B-NP O
Td NNP B-NP O
Booster NNP I-NP O
12/16/2070 CD O B-DATE
Triglycerides NNS B-NP O
12/16/2070 CD B-NP B-DATE
83 CD I-NP O
Cholesterol-LDL NNP B-NP O
12/16/2070 CD I-NP B-DATE
108 CD O O
Hct NNP B-NP O
( -LRB- I-NP O
Hematocrit NN I-NP O
) -RRB- I-NP O
04/27/2072 CD I-NP B-DATE
40.7 CD O O
Cholesterol-HDL NNP B-NP O
12/16/2070 CD I-NP B-DATE
47 CD O O
Hgb NNP B-NP O
( -LRB- I-NP O
Hemoglobin NNP I-NP O
) -RRB- I-NP O
04/27/2072 CD I-NP B-DATE
13.1 CD O O
HbA1c JJ B-NP O
12/16/2070 CD I-NP B-DATE
6.50 CD O O
Chlamydia NNP B-NP O
03/09/62 CD I-NP B-DATE
NEGATIVE. . O O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
1 LS O O
. . B-NP O
Health NNP I-NP O
Maintenance NNP I-NP O
- : O O
Pap NN B-VP O
smear NN B-NP O
-will NN I-NP O
do VBP B-VP O
every DT B-NP O
two CD I-NP O
to TO I-NP O
3 CD I-NP O
years NNS I-NP O
. . B-PP O
mammo NN B-NP O
-still : O O
very RB B-ADJP O
overdue JJ I-ADJP O
- : O O
stressed VBD B-VP O
needs NNS B-NP O
to TO B-VP O
do VB I-VP O
this DT B-NP O
again RB I-NP O
and CC O O
promises VBZ B-VP O
, , O O
colonoscopy NN B-NP O
fine JJ I-NP O
2071 CD I-NP B-DATE
. . O O
To TO B-VP O
increase VB I-VP O
exercise NN B-NP O
. . O O
2. DT B-NP O
Menopause NNP I-NP O
- : O O
calcium NN B-NP O
, , O O
consider VBP B-VP O
BD VBN I-VP O
when WRB B-ADVP O
not RB I-ADVP O
overwhelmed VBN B-VP O
with IN B-PP O
everything NN B-NP O
else RB I-NP O
3. DT B-NP O
Sleep NN I-NP O
, , O O
stress NN B-NP O
- : O O
seems VBZ B-VP O
to TO I-VP O
be VB I-VP O
doing VBG I-VP O
generally RB B-ADVP O
better JJR I-ADVP O
now RB B-ADVP O
. . B-VP O
Discussed VBN I-VP O
this DT B-NP O
for IN I-NP O
most JJS B-ADVP O
of IN B-PP O
her PRP$ B-NP O
45 CD I-NP O
minute NN I-NP O
appointment NN I-NP O
. . O O
Starting VBG B-VP O
to TO I-VP O
get VB I-VP O
out RP B-PRT O
now RB B-ADVP O
and CC O O
socialize VB B-VP O
. . O O
To TO B-VP O
work VB I-VP O
quite RB B-ADVP O
regularly RB I-ADVP O
now RB I-ADVP O
. . B-VP O
Not RB I-VP O
interested VBN I-VP O
in IN B-PP O
further JJ B-NP O
counseling NN I-NP O
or CC I-NP O
medications NNS I-NP O
. . O O
4 CD B-LST O
. . O O
sinus IN B-PP O
congestion NN B-NP O
states NNS I-NP O
she PRP B-NP O
wakes VBZ B-VP O
up RB B-ADVP O
and CC O O
feels VBZ B-VP O
her PRP$ B-NP O
sinuses NNS I-NP O
are VBP B-VP O
clogged VBN I-VP O
her PRP$ B-NP O
eyes NNS I-NP O
are VBP B-VP O
puffy JJ B-ADJP O
and CC O O
sneezing VBG B-VP O
. . B-NP O
No DT I-NP O
help NN I-NP O
with IN B-PP O
Claritin NNP B-NP O
. . I-NP O
Will NNP I-NP O
try VBP B-VP O
Flonase NNP B-NP O
for IN B-PP O
two CD B-NP O
to TO I-NP O
3 CD I-NP O
weeks NNS I-NP O
to TO B-VP O
see VB I-VP O
if IN B-SBAR O
it PRP B-NP O
helps VBZ B-VP O
. . O O
Rest NNP B-NP O
of IN B-PP O
issues NNS B-NP O
- : O O
see VBP B-VP O
above IN B-NP O
. . O O
follow-up JJ B-NP O
3 CD I-NP O
months NNS I-NP O
Beverly NNP B-NP B-DOCTOR
Thiel NNP I-NP I-DOCTOR
