Record NNP B-NP O
date NN I-NP O
: : O O
2089-10-07 CD O B-DATE
Medications NNS B-NP O
: : O O
Prilosec NNP B-NP O
20 CD I-NP O
- : O O
2 CD O O
Atenolol NNP B-NP O
50 CD I-NP O
Cozaar NNP B-NP O
50 CD I-NP O
Lipitor NNP B-NP O
10 CD I-NP O
Valium NNP B-NP O
2 CD I-NP O
- : O O
Advair NNP B-NP O
2i CD I-NP O
puff NN I-NP O
bid NN I-NP O
Alupent NNP B-NP O
prn NN I-NP O
Problem NNP B-NP O
# # I-NP O
1 CD I-NP O
: : O O
GERD NNP O O
No DT B-NP O
heart NN I-NP O
burn VB B-VP O
on IN B-PP O
Prilosec. NNP B-NP O
He PRP B-NP O
does VBZ B-VP O
note NN B-NP O
attacks NNS I-NP O
of IN B-PP O
ss NN B-NP O
chest NN I-NP O
pain NN I-NP O
radiating VBG B-VP O
to TO B-PP O
L NNP B-NP O
arm NN I-NP O
relieved VBN B-VP O
by IN B-PP O
valium NN B-NP O
and CC I-NP O
Gaviscon NNP I-NP O
and CC O O
attributed VBN B-VP O
by IN B-PP O
Y NNP B-NP I-DOCTOR
. . I-NP I-DOCTOR
Ullrich NNP I-NP I-DOCTOR
to TO B-VP O
reflux VB I-VP O
( -LRB- B-NP O
Ted NNP I-NP B-PATIENT
says VBZ B-VP O
) -RRB- B-NP O
. . O O
No DT B-NP O
exertional JJ I-NP O
trigger NN I-NP O
to TO B-PP O
these DT B-NP O
. . O O
Problem NNP B-NP O
# # I-NP O
2 CD I-NP O
: : O O
CAD NN B-NP O
No DT B-NP O
exertional JJ I-NP O
chest NN I-NP O
pain NN I-NP O
, , O O
dizzy JJ B-NP O
spells NNS I-NP O
or CC I-NP O
episodes NNS I-NP O
of IN B-PP O
dizziness NN B-NP O
. . O O
Thallium NNPS B-VP O
stress NN I-VP O
last JJ B-NP O
year NN I-NP O
to TO B-PP O
METS NNS B-NP O
13 CD B-NP O
showed VBD B-VP O
normal JJ B-NP O
ECG NN I-NP O
but CC O O
a DT B-NP O
small JJ I-NP O
anteroseptal JJ I-NP O
zone NN I-NP O
of IN B-PP O
ischemia NN B-NP O
with IN B-PP O
reperfusion NN B-NP O
. . O O
Has VBZ B-VP O
not RB I-VP O
really RB I-VP O
engaged VBN I-VP O
in IN B-PP O
fitness NN B-NP O
program NN I-NP O
as IN B-SBAR O
recommended VBN B-VP O
by IN B-PP O
Y NNP B-NP B-DOCTOR
Ullrich . O I-DOCTOR
Problem NNP B-NP O
# # I-NP O
3 CD I-NP O
.HT . O O
BP NNP B-NP O
's POS B-NP O
150/8 CD I-NP O
0 CD I-NP O
range NN I-NP O
at IN B-PP O
home NN B-NP O
Problem NNP B-NP O
# # I-NP O
4 CD I-NP O
Hyperlipidemia NNP I-NP O
Last JJ B-NP O
chol169 CD I-NP O
TG NNP I-NP O
270 CD I-NP O
HDL NNP I-NP O
35 CD I-NP O
LDL NNP I-NP O
79 CD I-NP O
( -LRB- I-NP O
9/88 CD I-NP B-DATE
) -RRB- O O
Problem NNP B-NP O
# # I-NP O
5 CD I-NP O
Asthma NN I-NP O
Intensifies NNP B-NP O
seasonally RB B-ADVP O
( -LRB- B-VP O
now RB I-VP O
) -RRB- I-VP O
controlled VBN I-VP O
with IN B-PP O
inhalants NNS B-NP O
Problem NNP B-NP O
# # I-NP O
6 CD I-NP O
Recurrent NNP I-NP O
sinusitis NN I-NP O
He PRP B-NP O
describes VBZ B-VP O
stuffiness NN B-NP O
of IN B-PP O
sinuses NNS B-NP O
, , O O
at IN B-PP O
times NNS B-NP O
has VBZ B-VP O
been VBN I-VP O
treated VBN I-VP O
by IN B-PP O
his PRP$ B-NP O
ENT JJ I-NP O
physician NN I-NP O
with IN B-PP O
cipro NN B-NP O
. . O O
May MD B-VP O
need VB I-VP O
drainage NN B-NP O
surgery NN I-NP O
Social NNP B-NP O
History NNP I-NP O
Unchanged . O O
ROS NNS B-NP O
HEENT NNP B-NP O
: : O O
No DT B-NP O
hearing NN I-NP O
or CC I-NP O
visual JJ I-NP O
problems NNS I-NP O
. . O O
Resp NN B-NP O
: : O O
See VB B-VP O
above IN O O
CV NNP B-NP O
: : O O
See VB B-VP O
above IN O O
Abd NNP B-NP O
: : O O
No DT B-NP O
nausea NN I-NP O
, , O O
vomiting NN B-NP O
, , O O
pain NN B-NP O
, , O O
bowel NN B-NP O
disturbance NN I-NP O
, , O O
hematochezia NN B-NP O
, , O O
melena NN B-NP O
GU NNP B-NP O
: : O O
No DT B-NP O
dysuria NN I-NP O
, , O O
hematuria NN B-NP O
, , O O
flank JJ B-NP O
pain NN I-NP O
. . O O
NM NNP B-NP O
: : O O
No DT B-NP O
sensory JJ I-NP O
, , I-NP O
gait NN I-NP O
, , I-NP O
strength NN I-NP O
deficits NNS I-NP O
. . O O
No DT B-NP O
syncope NN I-NP O
, , O O
seizures NNS B-NP O
. . O O
Endoc NNP B-NP O
: : O O
No DT B-NP O
polyuria NN I-NP O
, , O O
polydipsia NN B-NP O
, , I-NP O
heat NN I-NP O
or CC I-NP O
cold JJ I-NP O
intolerance NN I-NP O
. . O O
BMJ: NNP B-NP O
No DT B-NP O
myalgias NNS I-NP O
, , O O
arthralgias NNS B-NP O
. . O O
Other JJ B-NP O
: : O O
No DT B-NP O
wt NN I-NP O
loss NN I-NP O
, , O O
fever NN B-NP O
, , O O
fatigue NN B-NP O
, , O O
sleep NN B-NP O
difficulty NN I-NP O
. . O O
Physical JJ B-NP O
Examination NN I-NP O
BP NNP B-NP O
170/70 CD I-NP O
( -LRB- I-NP O
! . O O
) -RRB- O O
P NNP B-NP O
56 CD B-NP O
RSR NN I-NP O
HEENT NNP B-NP O
PERLA NNP I-NP O
. . I-NP O
Pharynx NNP I-NP O
benign JJ O O
Neck NNP B-NP O
: : O O
Supple NNP B-NP O
. . I-NP O
Thyroid NNP I-NP O
not RB B-ADVP O
enlarged VBD B-VP O
. . O O
No DT B-NP O
carotid NN I-NP O
bruit NN I-NP O
LN'S NNP B-NP O
: : O O
No DT B-NP O
lymphadenopathy NN I-NP O
Lungs NNP B-NP O
: : O O
Clear NNP B-NP O
to TO B-PP O
percussion NN B-NP O
and CC I-NP O
auscultation NN I-NP O
Heart NNP B-NP O
: : O O
Not RB B-VP O
enlarged VBN I-VP O
. . O O
No DT B-NP O
murmurs NNS I-NP O
Abdomen NNP B-NP O
: : O O
Soft NNP B-NP O
. . O O
No DT B-NP O
organomegaly NN I-NP O
, , O O
masses NNS B-NP O
. . B-VP O
tenderness NN B-NP O
. . O O
Rectal NNP B-NP O
: : O O
Prostate NNP B-NP O
2x CD I-NP O
enlarged VBD B-VP O
, , O O
symm UH B-NP O
, , O O
no DT B-NP O
masses NNS I-NP O
Extremities NNS B-NP O
: : O O
Full NNP B-NP O
ROM. NNP I-NP O
No DT B-NP O
edema NN I-NP O
. . O O
Pedal NNP B-NP O
pulses VBZ B-VP O
intact JJ O O
Neurological JJ B-NP O
: : O O
Grossly RB B-ADJP O
normal JJ I-ADJP O
Impression NN B-NP O
and CC I-NP O
plan NN I-NP O
: : O O
GERD NNP B-NP O
- : O O
same JJ B-NP O
program NN I-NP O
CAD NN B-NP O
- : O O
Repeat NN B-NP O
lipids NNS I-NP O
; : O O
make VB B-VP O
appt NN B-NP O
to TO B-VP O
see VB I-VP O
Y PRP B-NP B-DOCTOR
Ullrich . O I-DOCTOR
HT NNP B-NP O
Add VB I-NP O
dyazide NN I-NP O
1 CD I-NP O
qd NN I-NP O
to TO B-PP O
program NN B-NP O
Hyperlipidemia NNP B-NP O
- : O O
consider VBP B-VP O
doubling VBG I-VP O
Lipitor NNP B-NP O
- : O O
as IN B-PP O
per IN B-PP O
Yosef NNP B-NP B-DOCTOR
Ullrich NNP I-NP I-DOCTOR
Forty CD B-NP O
minutes NNS I-NP O
spent VBN B-VP O
with IN B-PP O
patient NN B-NP O
in IN B-PP O
counsselling VBG B-NP O
and CC I-NP O
coordinating VBG I-NP O
care NN I-NP O
. . O O
Ulysses NNP B-NP B-DOCTOR
Gilbert NNP I-NP I-DOCTOR
