Record NNP B-NP O
date NN I-NP O
: : O O
2070-10-01 CD O B-DATE
IMS VBZ B-VP B-HOSPITAL
Cardiovascular NNP B-NP O
Division NNP I-NP O
CVD NNP B-NP O
TR7 CD I-NP O
33 CD B-NP B-STREET
Auburn NNP I-NP I-STREET
Street NNP I-NP I-STREET
JOSHI NNP I-NP I-PATIENT
, , O I-PATIENT
KATHY . O I-PATIENT
Rehoboth NNP B-NP B-CITY
, , O O
NM NNP B-NP B-STATE
42761 CD I-NP B-ZIP
15842112 CD O B-MEDICALRECORD
( -LRB- B-NP I-PHONE
326 CD I-NP I-PHONE
) -RRB- I-NP I-PHONE
176-2429 CD I-NP I-PHONE
10/01/70 CD O B-DATE
Benjamin NNP B-NP B-DOCTOR
Taylor NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
Illini NNP B-NP B-HOSPITAL
Community NNP I-NP I-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
94 CD B-NP B-STREET
Cardinal NNP I-NP I-STREET
Circle NNP I-NP I-STREET
Three CD B-NP B-CITY
Rivers NNS I-NP I-CITY
, , O O
NM NNP B-NP B-STATE
11424 CD I-NP B-ZIP
. . O O
Dear NNP B-NP O
Dr. NNP I-NP O
Taylor NNP I-NP B-DOCTOR
: : O O
Mrs. NNP B-NP O
Joshi NNP I-NP B-PATIENT
returns VBZ B-VP O
for IN B-PP O
followup NN B-NP O
. . O O
Currently RB B-ADVP O
, , O O
she PRP B-NP O
complains VBZ B-VP O
of IN B-PP O
exertional JJ B-NP O
fatigue NN I-NP O
, , O O
exertional JJ B-NP O
dyspnea NN I-NP O
, , O O
and CC O O
mild JJ B-NP O
peripheral NN I-NP O
edema NN B-NP O
. . O O
Since IN O O
last JJ B-NP O
seen VBN I-NP O
, , O O
she PRP B-NP O
has VBZ B-VP O
continued VBN I-VP O
to TO I-VP O
find VB I-VP O
it PRP B-NP O
quite RB B-ADVP O
difficult JJ B-ADJP O
to TO B-VP O
lose VB I-VP O
weight NN B-NP O
, , O O
and CC O O
has VBZ B-VP O
thus RB I-VP O
far RB I-VP O
declined VBN I-VP O
seeing VBG I-VP O
members NNS B-NP O
of IN B-PP O
our PRP$ B-NP O
obesity NN I-NP O
clinic NN I-NP O
. . O O
As IN B-SBAR O
you PRP B-NP O
know VBP B-VP O
, , O O
in IN B-PP O
the DT B-NP O
past NN I-NP O
, , O O
she PRP B-NP O
also RB B-ADVP O
has VBZ B-VP O
declined VBN I-VP O
any DT B-NP O
consideration NN I-NP O
of IN B-PP O
attempted VBN B-NP O
cardioversion NN I-NP O
or CC O O
other JJ B-NP O
invasive JJ I-NP O
studies NNS I-NP O
. . O O
Presently RB B-ADVP O
, , O O
she PRP B-NP O
remains VBZ B-VP O
on IN B-PP O
a DT B-NP O
regimen NN I-NP O
of IN B-PP O
enteric-coated JJ B-NP O
aspirin NN I-NP O
325 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
simvastatin RB B-ADVP O
20 CD B-NP O
mg JJ I-NP O
p.o NN I-NP O
. . O O
q.d. VBN B-VP O
, , O O
metoprolol NN B-NP O
50 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
b.i.d. '' O O
, , O O
isosorbide VBP B-VP O
nitrate JJ B-NP O
60 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. VBN B-VP O
, , O O
Avapro NNP B-NP O
150 CD I-NP O
mg JJ I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
Actos NNP B-NP O
45 CD I-NP O
mg NN I-NP O
p.o RB B-ADVP O
. . O O
q.d. '' O O
, , O O
potassium NN B-NP O
, , O O
10 CD B-NP O
mEq JJ I-NP O
p.o NN I-NP O
. . O O
q.d '' O O
. . B-VP O
Pumex NNP B-NP O
2 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
Coumadin NNP B-NP O
, , O O
magnesium NN B-NP O
oxide NN I-NP O
, , O O
Humulin NNP B-NP O
insulin NN I-NP O
20 CD B-NP O
units NNS I-NP O
subcutaneous JJ B-NP O
q NN I-NP O
. . O O
a.m. RB B-ADVP O
along RB I-ADVP O
with IN B-PP O
50 CD B-NP O
units NNS I-NP O
subcutaneous JJ B-NP O
q RB I-NP O
. . O O
p.m. RB B-ADVP O
, , O O
and CC O O
Humalog NNP B-NP O
26 CD I-NP O
units NNS I-NP O
subcutaneous JJ B-NP O
q NN I-NP O
. . O O
a.m. RB O O
Physical JJ B-NP O
examination NN I-NP O
reveals VBZ B-VP O
a DT B-NP O
markedly RB I-NP O
overweight JJ I-NP O
woman NN I-NP O
in IN B-PP O
no NN B-NP O
acute JJ B-NP O
distress NN I-NP O
. . O O
Blood NN B-NP O
pressure NN I-NP O
right JJ I-NP O
arm NN I-NP O
sitting VBG B-VP O
at IN B-PP O
106/62 CD B-NP O
, , O O
heart NN B-NP O
rate NN I-NP O
65 CD B-NP O
and CC I-NP O
irregularly RB I-NP O
regular JJ I-NP O
, , I-NP O
respirations NNS I-NP O
16 CD I-NP O
and CC O O
unlabored JJ B-ADJP O
, , O O
weight NN B-NP O
306 CD I-NP O
lbs NNS I-NP O
, , O O
which WDT B-NP O
is VBZ B-VP O
6 CD B-NP O
lbs NNS I-NP O
above IN B-PP O
her PRP$ B-NP O
weight NN I-NP O
10 CD O O
months NNS B-NP O
ago RB B-ADVP O
. . O O
The DT B-NP O
neck NN I-NP O
is VBZ B-VP O
soft JJ B-ADJP O
. . O O
JVP NNP B-NP O
is VBZ B-VP O
flat JJ B-ADJP O
. . O O
Carotids NNP O O
without IN B-PP O
significant JJ B-NP O
bruits NNS I-NP O
. . O O
Chest NNP B-NP O
is VBZ B-VP O
clear JJ B-ADJP O
. . O O
Cardiac NNP B-NP O
exam NN I-NP O
reveals VBZ B-VP O
a DT O O
normal JJ B-NP O
S1 NNP I-NP O
, , O O
a DT B-NP O
physiologically RB I-NP O
split VBN I-NP O
S2 NNP I-NP O
, , O O
with IN B-PP O
a1-2/6 DT B-NP O
systolic NN I-NP O
murmur VB B-VP O
radiating VBG I-VP O
from IN B-PP O
apex NN B-NP O
to TO B-PP O
the DT B-NP O
base NN I-NP O
. . O O
No DT B-NP O
significant JJ I-NP O
diastolic NN I-NP O
murmur VB B-VP O
or CC I-VP O
rub VB I-VP O
. . O O
The DT B-NP O
abdomen NN I-NP O
is VBZ B-VP O
obese JJ B-ADJP O
, , O O
but CC O O
otherwise RB B-ADJP O
benign JJ I-ADJP O
. . O O
Extremities NNS B-NP O
reveal VBP B-VP O
1-2+ JJ B-NP O
bipedal NN I-NP O
edema NN I-NP O
, , O O
peripheral JJ B-NP O
pulses NNS I-NP O
are VBP B-LST O
intact JJ B-ADJP O
albeit IN B-PP O
mildly RB B-NP O
diminished VBN I-NP O
. . O O
Electrocardiogram NNP B-NP O
shows VBZ B-VP O
atrial JJ B-NP O
fibrillation NN I-NP O
with IN B-PP O
a DT B-NP O
variable JJ I-NP O
QRS NNS I-NP O
response NN B-NP O
. . O O
The DT B-NP O
P NNP I-NP O
waves NNS I-NP O
are VBP B-VP O
more RBR B-ADJP O
organized VBN I-ADJP O
than IN B-PP O
one NN B-NP O
might MD B-VP O
usually RB I-VP O
see VB B-VP O
, , O O
suggesting VBG B-VP O
the DT B-NP O
possibility NN I-NP O
of IN B-PP O
fibrillation/flutter NN B-NP O
as RB B-ADVP O
well RB I-ADVP O
. . O O
QRS NNP B-NP O
0.11 CD I-NP O
, , O O
QT NNP B-NP O
0.38 CD I-NP O
, , O O
axis NN B-NP O
90 CD I-NP O
degrees NNS I-NP O
, , O O
there EX B-NP O
is VBZ B-VP O
evidence NN B-NP O
of IN B-PP O
a DT B-NP O
prior JJ I-NP O
inferior JJ B-NP O
myocardial JJ I-NP O
infarction NN I-NP O
. . O O
Compared VBN B-VP O
with IN B-PP O
his PRP$ B-NP O
last JJ I-NP O
electrocardiogram NN B-NP O
, , O O
there EX B-NP O
is VBZ B-VP O
no DT B-NP O
significant JJ I-NP O
change NN I-NP O
. . O O
Impression NN B-NP O
: : O O
Mrs. NNP B-NP O
Joshy NNP I-NP B-PATIENT
continues VBZ B-VP O
to TO I-VP O
suffer VB I-VP O
from IN B-PP O
morbid NN B-NP O
obesity NN I-NP O
, , O O
and CC O O
I PRP B-NP O
had VBD B-VP O
a DT B-NP O
long JJ I-NP O
discussion NN I-NP O
with IN B-PP O
her PRP B-NP O
and CC O O
her PRP$ B-NP O
daughter NN I-NP O
regarding VBG B-LST O
the DT B-NP O
essential JJ I-NP O
nature NN I-NP O
of IN B-PP O
her PRP$ B-NP O
engaging VBG I-NP O
in IN B-PP O
an DT B-NP O
aggressive JJ I-NP O
weigh VBP B-LST O
reduction NN B-NP O
program NN I-NP O
. . O O
I PRP B-NP O
once RB B-ADVP O
again RB B-ADVP O
have VBP B-VP O
strongly RB I-VP O
encouraged VBN I-VP O
her PRP B-NP O
to TO B-VP O
make VB B-VP O
an DT B-NP O
appointment NN I-NP O
with IN B-PP O
our PRP$ B-NP O
obesity NN I-NP O
clinic NN I-NP O
to TO B-VP O
assist VB I-VP O
in IN B-PP O
extensive JJ B-NP O
weight NN I-NP O
reduction NN I-NP O
. . O O
I PRP B-NP O
also RB B-ADVP O
discussed VBD B-VP O
with IN B-PP O
her PRP B-NP O
my PRP$ O O
concerns NNS B-NP O
regarding VBG B-VP O
her PRP$ B-NP O
symptoms NNS I-NP O
of IN B-PP O
slowly RB B-NP O
progressive JJ I-NP O
peripheral NN I-NP O
edema NN B-NP O
, , O O
particularly RB B-ADVP O
as IN B-SBAR O
it PRP B-NP O
pertains VBZ B-VP O
both DT B-ADJP O
to TO B-PP O
her PRP$ B-NP O
weight NN I-NP O
, , O O
and CC O O
atrial NN B-NP O
or CC O O
tachyarrhythmias NNS B-NP O
. . O O
As IN B-PP O
in IN B-PP O
the DT B-NP O
past NN I-NP O
, , O O
she PRP B-NP O
told VBD B-VP O
me PRP B-NP O
that IN B-SBAR O
she PRP B-NP O
would MD O O
refuse VB B-VP O
any DT B-NP O
consideration NN I-NP O
for IN B-PP O
attempted VBN B-NP O
cardioversion NN I-NP O
or CC I-NP O
other JJ I-NP O
studies NNS B-NP O
. . O O
She PRP B-NP O
did VBD B-VP O
, , O O
however RB B-ADVP O
, , O O
agree VBP B-VP O
to TO I-VP O
continue VB I-VP O
with IN B-PP O
her PRP$ B-NP O
current JJ I-NP O
medical JJ B-NP O
regimen NNS I-NP O
. . O O
I PRP B-NP O
obtained VBD B-VP O
routine JJ B-NP O
blood NN I-NP O
studies NNS I-NP O
today NN I-NP O
to TO O O
verify VB B-VP O
the DT B-NP O
adequacy NN I-NP O
of IN B-PP O
her PRP$ B-NP O
lipid JJ I-NP O
control NN I-NP O
and CC O O
diabetes NN B-NP O
management NN I-NP O
. . O O
I PRP B-NP O
have VBP B-VP O
introduced VBN I-VP O
her PRP$ B-NP O
to TO B-PP O
Hayden NNP B-NP B-DOCTOR
Nutter NNP I-NP I-DOCTOR
, , O O
her PRP$ B-NP O
nurse NN I-NP O
practitioner NN I-NP O
, , O O
who WP B-NP O
will MD B-VP O
assist VB I-VP O
in IN B-PP O
trying VBG B-VP O
to TO I-VP O
achieve VB I-VP O
a DT B-NP O
little JJ I-NP O
more JJR I-NP O
diuresis NN I-NP O
overt IN B-SBAR O
he PRP B-NP O
next JJ B-NP O
few JJ I-NP O
weeks NNS I-NP O
. . O O
We PRP B-NP O
have VBP B-VP O
given VBN I-VP O
her PRP B-NP O
a DT B-NP O
prescription NN I-NP O
for IN B-PP O
Zaroxylyn NNP B-NP O
to TO B-VP O
begin VB I-VP O
at IN B-PP O
2.5 CD B-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
which WDT B-NP O
will MD B-VP O
help VB I-VP O
result VB I-VP O
in IN B-PP O
some DT O O
degree NN B-NP O
of IN B-PP O
mild JJ B-NP O
diuresis NN I-NP O
. . O O
Nonetheless RB B-ADVP O
, , O O
she PRP B-NP O
understands VBZ B-VP O
that IN B-SBAR O
significant JJ B-NP O
weight NN I-NP O
loss NN I-NP O
can MD B-VP O
only RB I-VP O
occur VB I-VP O
through IN B-PP O
a DT B-NP O
weight NN I-NP O
reduction NN I-NP O
program NN B-NP O
. . O O
I PRP B-NP O
have VBP B-VP O
of IN B-PP O
course NN B-NP O
explained VBD B-VP O
to TO B-PP O
her PRP$ B-NP O
the DT I-NP O
increased VBN I-NP O
cardiac NN I-NP O
morbidity NN B-NP O
associated VBN B-VP O
with IN B-PP O
her PRP$ B-NP O
current JJ I-NP O
lifestyle NN I-NP O
. . O O
Beyond IN B-PP O
this DT B-NP O
, , O O
I PRP B-NP O
have VBP B-NP O
not RB B-VP O
altered VBN I-VP O
her PRP$ B-NP O
current JJ I-NP O
medical JJ I-NP O
regimen NNS I-NP O
. . O O
Of IN B-PP O
course NN B-NP O
, , O O
I PRP B-NP O
thank VBP B-VP O
you PRP B-NP O
for IN B-PP O
allowing VBG B-VP O
me PRP B-NP O
to TO B-VP O
assist VB I-VP O
in IN B-PP O
his PRP$ B-NP O
care NN I-NP O
. . O O
Sincerely RB B-ADVP O
yours PRP B-NP O
, , O O
Dictated NNP B-NP O
By IN I-NP O
: : O O
Brandon NNP B-NP B-DOCTOR
Neilson NNP I-NP I-DOCTOR
Brandon NNP B-NP B-DOCTOR
Neilson NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
eScription NN B-NP O
document NN I-NP O
: : O O
8-5334486 CD B-NP B-IDNUM
AFFocus NN I-NP O
DD NNP B-NP O
: : O O
10/01/70 CD O B-DATE
DT NNP B-NP O
: : O O
10/02/70 CD O B-DATE
DV NNP B-NP O
: : O O
10/01/70 CD O B-DATE
******** NN B-NP O
Not RB B-VP O
reviewed VBN I-VP O
by IN B-PP O
Attending VBG B-VP O
Physician JJ B-NP O
******** NNS I-NP O
