Record NNP B-NP O
date NN I-NP O
: : O O
2093-01-13 CD O B-DATE
Team NNP B-NP O
X NNP I-NP O
Intern NNP I-NP O
Admission NNP I-NP O
Note NN I-NP O
Name VB B-VP O
: : O O
Hendrickson NNP B-NP I-PATIENT
, , O I-PATIENT
Ora NNP B-NP I-PATIENT
MR# NNP B-NP O
7194334 CD I-NP B-MEDICALRECORD
Date NNP B-NP O
: : O O
01/13/93 CD O B-DATE
PCP NNP B-NP O
: : O O
Oliveira NNP B-NP I-DOCTOR
, , O I-DOCTOR
Keith NNP B-NP I-DOCTOR
MD . O O
CC/RFA NNP B-NP O
: : O O
SOB. NNP O O
HPI NNP B-NP O
: : O O
Pt NNP B-NP O
is VBZ B-VP O
a DT B-NP O
76 CD I-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
with IN B-PP O
a DT B-NP O
h/o NN I-NP O
CAD NN I-NP O
, , O O
HTN NNP B-NP O
, , O O
hypercholesterolemia NN B-NP O
, , O O
COPD NNP B-NP O
, , O O
CHF NNP B-NP O
who WP B-NP O
developed VBD B-VP O
acute JJ B-NP O
SOB NNP I-NP O
while IN B-ADVP O
at IN B-PP O
home NN B-NP O
PM NNP I-NP O
of IN B-PP O
admission NN B-NP O
. . O O
Pt NNP B-NP O
reports VBZ B-VP O
no DT B-NP O
dietary NN I-NP O
discretions NNS I-NP O
and CC O O
excellent JJ B-NP O
adherence NN I-NP O
to TO B-PP O
medications NNS B-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
out IN B-PP O
evening NN B-NP O
of IN B-PP O
admission NN B-NP O
at IN B-PP O
a DT B-NP O
social JJ I-NP O
gathering NN I-NP O
and CC O O
noticed VBD B-VP O
symptoms NNS B-NP O
when WRB B-ADVP O
she PRP B-NP O
returned VBD B-VP O
home NN B-NP O
and CC O O
had VBD B-VP O
difficulty NN B-NP O
climbing VBG B-VP O
an DT B-NP O
internal JJ I-NP O
staircase NN I-NP O
in IN B-PP O
her PRP$ B-NP O
home NN I-NP O
She PRP B-NP O
ascended VBD B-VP O
the DT B-NP O
staircase NN I-NP O
and CC O O
was VBD B-VP O
unable JJ B-ADJP O
to TO B-VP O
regain VB I-VP O
her PRP$ B-NP O
breath NN I-NP O
. . O O
She PRP B-NP O
reports VBZ B-VP O
she PRP B-NP O
developed VBD B-VP O
profound JJ B-NP O
dyspnea NN I-NP O
and CC I-NP O
tachycardia NN I-NP O
. . O O
She PRP B-NP O
denies VBZ B-VP O
chest NN B-NP O
pain NN I-NP O
, , O O
diaphoresis NN B-NP O
, , I-NP O
dizziness NN I-NP O
or CC I-NP O
LOC. NNP I-NP O
She PRP B-NP O
has VBZ B-VP O
had VBD I-VP O
a DT B-NP O
cough NN I-NP O
productive JJ I-NP O
of IN B-PP O
clear JJ B-NP O
sputum NN I-NP O
x NN I-NP O
1 CD B-NP O
week NN I-NP O
with IN B-PP O
no DT B-NP O
fever NN I-NP O
, , O O
night NN B-NP O
sweats VBZ B-VP O
, , O O
rigors NNS B-NP O
or CC O O
chills NNS B-NP O
during IN B-PP O
this DT B-NP O
time NN I-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
had VBN I-VP O
no DT B-NP O
vomiting NN I-NP O
or CC I-NP O
diarrhea NN I-NP O
. . O O
She PRP B-NP O
does VBZ B-VP O
not RB I-VP O
recall VB I-VP O
wheezing VBG I-VP O
, , O O
and CC O O
asserts VBZ B-VP O
the DT B-NP O
only JJ I-NP O
symptoms NNS I-NP O
during IN B-PP O
the DT B-NP O
episode NN I-NP O
consisted VBD B-VP O
in IN B-PP O
SOB NNP B-NP O
and CC I-NP O
tachypnea NN I-NP O
. . O O
Of IN B-PP O
note NN B-NP O
, , O O
pt NN B-NP O
had VBD B-VP O
2 CD B-NP O
vessel NN I-NP O
CABG NN I-NP O
in IN B-PP O
11/92 CD B-NP B-DATE
. . O O
Catheterization NNP B-NP O
on IN B-PP O
11/18/92 CD B-NP B-DATE
revealed VBD B-VP O
100 CD B-NP O
% NN I-NP O
obstruction NN I-NP O
of IN B-PP O
the DT B-NP O
left JJ I-NP O
proximal JJ I-NP O
circ NN I-NP O
, , O O
70 CD B-NP O
% NN I-NP O
proximal JJ I-NP O
LAD NN I-NP O
obstruction NN I-NP O
, , O O
and CC O O
100 CD B-NP O
% NN I-NP O
obstruction NN I-NP O
of IN B-PP O
the DT B-NP O
mid JJ I-NP O
RCA NN I-NP O
. . O O
Course NNP B-NP O
in IN B-PP O
ED NNP B-NP O
: : O O
En NNP B-NP O
route NN I-NP O
to TO B-PP O
BBH NNP B-NP B-HOSPITAL
pt NN I-NP O
received VBD B-VP O
Lasix NNP B-NP O
40 CD I-NP O
mg NN I-NP O
, , O O
TNG NNP B-NP O
x NN I-NP O
3. VBD B-VP O
She PRP B-NP O
was VBD B-VP O
described VBN I-VP O
as IN B-PP O
pale JJ B-NP O
, , I-NP O
cool JJ I-NP O
, , I-NP O
and CC I-NP O
diaphoretic JJ I-NP O
. . O O
She PRP B-NP O
was VBD B-VP O
unable JJ B-ADJP O
to TO B-VP O
complete VB I-VP O
full JJ B-NP O
sentences NNS I-NP O
. . O O
She PRP B-NP O
received VBD B-VP O
Lasix NNP B-NP O
40 CD I-NP O
mg NN I-NP O
IV NNP B-NP O
and CC O O
20 CD B-NP O
mg NN I-NP O
IV NNP B-NP O
2 CD I-NP O
hours NNS I-NP O
later RB B-ADVP O
, , O O
ASA NNP B-NP O
325 CD I-NP O
x NN I-NP O
1 CD I-NP O
, , O O
Zofran NNP B-NP O
8 CD I-NP O
mg NN I-NP O
IV NNP I-NP O
, , O O
and CC O O
0.5 CD B-NP O
nitropaste NN I-NP O
. . O O
Initial JJ B-NP O
vitals NNS I-NP O
were VBD B-VP O
T NNP B-NP O
98 CD I-NP O
P NNP I-NP O
93 CD I-NP O
BP NNP I-NP O
148/67 CD I-NP O
RR NNP I-NP O
24 CD I-NP O
93 CD I-NP O
% NN I-NP O
on IN B-PP O
6 CD B-NP O
L NNP I-NP O
and CC I-NP O
100 CD I-NP O
% NN I-NP O
on IN B-PP O
BiPap NNP B-NP O
( -LRB- I-NP O
brief NN I-NP O
) -RRB- I-NP O
. . O O
PMHx NNP B-NP O
: : O O
1 CD B-LST O
. . O O
HTN '' O O
2. . B-NP O
CAD NNP I-NP O
[old VBD B-VP O
MI NNP B-NP O
by IN B-PP O
EKG/imaging VBG B-VP O
] NNS B-NP O
3. CD B-NP O
COPD NN I-NP O
4 CD B-NP O
. . O O
Hypercholesterolemia NNP O O
5 CD B-NP O
. . O O
DM NNP B-NP O
, , O O
type NN B-NP O
II NNP I-NP O
6 CD B-NP O
. . O O
Recurrent NNP B-NP O
UTIs NNP I-NP O
[cystocele/recurrent NN I-NP O
UTI] . O O
7. . B-NP O
Chronic NNP I-NP O
LE JJ I-NP O
edema NN I-NP O
[ IN B-PP O
Doppler NNP B-NP O
NEG] . O O
8. . B-NP O
Anxiety NNP I-NP O
9 CD B-NP O
. . O O
GERD NNP O O
ALLERGIES NNS B-NP O
: : O O
Penicillin/Cephalosporins NNP B-NP O
- : O O
hives NNS B-NP O
MEDS NNS B-NP O
: : O O
Atenolol NNP B-NP O
100 CD I-NP O
mg NN I-NP O
PO NN I-NP O
qd . O O
Lipitor NNP B-NP O
10 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
Cozaar NNP B-NP O
50 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
Furosemide NNP B-NP O
20 CD I-NP O
mg NN I-NP O
po NN I-NP O
qde NN I-NP O
Prilosec NNP B-NP O
20 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
ECASA NNP B-NP O
325 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
Nifedipine NNP B-NP O
XL NNP I-NP O
60 CD I-NP O
mg NN I-NP O
po NN I-NP O
bid NN I-NP O
Klonazepam NNP B-NP O
0.5 CD I-NP O
mg JJ I-NP O
po NN I-NP O
bid NN I-NP O
SHx NNP B-NP O
: : O O
lives NNS B-NP O
alone RB B-ADVP O
, , O O
independent JJ B-ADJP O
with IN B-PP O
ADLs NNP B-NP O
PTA NNP I-NP O
FHx NNP B-NP O
: : O O
no DT B-NP O
CAD NN I-NP O
, , O O
DM NNP B-NP O
, , O O
stroke NN B-NP O
PHYSICAL NNP B-NP O
EXAM NNP I-NP O
: : O O
Gen NNP B-NP O
: : O O
Supine NNP B-NP O
, , O O
c/o NN B-NP O
nausea NN I-NP O
. . O O
Vitals NNS B-NP O
: : O O
T NNP B-NP O
96.8 CD I-NP O
P NNP I-NP O
87 CD I-NP O
BP NNP I-NP O
132/64 CD I-NP O
RR NNP I-NP O
20 CD I-NP O
SaO2 NNP I-NP O
93 CD I-NP O
% NN I-NP O
6 CD B-NP O
L NNP I-NP O
NC. NNP I-NP O
HEENT NNP B-NP O
: : O O
PERRL. NNP B-NP O
Sclerae NNP I-NP O
anicteric JJ I-NP O
, , I-NP O
conj JJ I-NP O
pale JJ I-NP O
. . I-NP O
MMM NNP I-NP O
, , O O
no DT B-NP O
exudates NNS I-NP O
. . O O
JVP NN O O
7 CD B-NP O
cm NN I-NP O
. . O O
Chest NNP B-NP O
: : O O
Fine JJ B-NP O
inspiratory NN I-NP O
crackles VBZ B-VP O
inf NN B-NP O
of IN B-PP O
lung NN B-NP O
field NN I-NP O
; : O O
anterior JJ B-NP O
end-expiratory JJ I-NP O
wheeze NN I-NP O
. . O O
Heart NNP B-NP O
: : O O
RRR NNP B-NP O
. . I-NP O
Nl NNP I-NP O
S1/S2 NNP I-NP O
, , O O
I/V NNP B-NP O
I PRP B-NP O
SM. NNP B-NP O
Carotid NNP I-NP O
bruit NN I-NP O
on IN B-PP O
left NN B-NP O
, , O O
right RB B-ADJP O
clear JJ I-ADJP O
. . O O
Left VBD B-VP O
pedal JJ B-NP O
pulses NNS I-NP O
1 CD B-NP O
+ NN I-NP O
uniformly RB B-ADVP O
; : O O
right RB B-ADJP O
not RB I-ADJP O
palpable JJ I-ADJP O
. . O O
Abd NNP B-NP O
: : O O
NABS NNP B-NP O
, , O O
obese NN B-NP O
, , O O
NT NNP B-NP O
, , O O
no DT B-NP O
organomegaly NN I-NP O
. . O O
Extr NNP B-NP O
: : O O
Trace NNP B-NP O
pretib NN I-NP O
edema NN I-NP O
. . O O
DJD NNP B-NP O
hands NNS I-NP O
. . O O
Skin NNP B-NP O
: : O O
No DT B-NP O
lesions NNS I-NP O
. . O O
Neuro NNP B-NP O
: : O O
No DT B-NP O
gross JJ I-NP O
deficits NNS I-NP O
. . O O
LABS NNP B-NP O
: : O O
Calcium NNP B-NP O
9.0 CD I-NP O
8.5-10.5 CD I-NP O
mg/dl NN I-NP O
Phosphorus NNP B-NP O
3.7 CD I-NP O
2.6-4.5 CD I-NP O
mg/dl NN I-NP O
Magnesium NNP B-NP O
1.6 CD I-NP O
1.4-2.0 CD I-NP O
meq/L NNS I-NP O
Total JJ B-NP O
Protein NNP I-NP O
7.9 CD I-NP O
6.0-8.0 CD I-NP O
g/dl NN I-NP O
Albumin NNP B-NP O
3.1 CD I-NP O
3.1-4.3 CD I-NP O
g/dl NN I-NP O
Globulin NNP B-NP O
4.8 CD I-NP O
H NNP B-NP O
2.6-4.1 CD I-NP O
g/dl . O O
Direct JJ B-NP O
Bilirubin NNP I-NP O
0.1 CD I-NP O
0-0.4 CD I-NP O
mg/dl NN I-NP O
Total JJ B-NP O
Bilirubin NNP I-NP O
0.4 CD I-NP O
0-1.0 CD I-NP O
mg/dl NN I-NP O
Alkaline NNP B-NP O
Phosphatase NNP I-NP O
293 CD I-NP O
H NNP B-NP O
30-100 CD I-NP O
U/L . O O
Transaminase-SGPT NNP B-NP O
17 CD I-NP O
7-30 CD I-NP O
U/L . O O
Amylase NNP B-NP O
29 CD I-NP O
3-100 CD I-NP O
units/L NN I-NP O
Lipase NNP B-NP O
1.8 CD I-NP O
1.3-6.0 CD I-NP O
U/dl . O O
Creatine JJ B-NP O
Kinase NNP I-NP O
Isoenzy NNP I-NP O
2.4 CD I-NP O
0.0-6.9 CD I-NP O
ng/ml . O O
CPK NNP B-NP O
Isoenzymes NNP I-NP O
Index NNP I-NP O
0.0-3.5 CD I-NP O
% NN I-NP O
Result NN B-NP O
Text NNP I-NP O
: : O O
CPK NNP B-NP O
and/or CC I-NP O
CKMB NNP I-NP O
too RB I-NP O
low JJ B-ADJP O
to TO B-VP O
calculate VB I-VP O
Relative NNP B-NP O
Index NNP I-NP O
. . O O
Troponin-T NNP B-NP O
0.01 CD I-NP O
0.00-0.09 CD I-NP O
ng/ml NN I-NP O
Transaminase-SGOT NNP B-NP O
33 CD I-NP O
H NNP B-NP O
9-25 CD I-NP O
U/L . O O
Creatine JJ B-NP O
Kinase NNP I-NP O
40 CD I-NP O
40-150 CD I-NP O
U/L . O O
Sodium NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
138 CD I-NP O
135-145 CD I-NP O
mmol/L . O O
Potassium NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NN I-NP O
) -RRB- I-NP O
3.8 CD I-NP O
3.4-4.8 CD I-NP O
mmol/L NN I-NP O
Chloride NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
109 CD I-NP O
H NNP B-NP O
100-108 CD I-NP O
mmol/L . O O
CO2 NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
25.0 CD I-NP O
24.0-30.0 CD I-NP O
mmol/L . O O
BUN NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- B-VP O
14 CD B-NP O
8-25 CD I-NP O
mg/dl NN I-NP O
Creatinine NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
0.8 CD I-NP O
0.6-1.5 CD I-NP O
mg/dl NN I-NP O
Glucose FW B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
222 CD I-NP O
H NNP B-NP O
70-110 CD I-NP O
mg/dl . O O
WBC NNP B-NP O
11.1 CD I-NP O
H NNP B-NP O
4.5-11.0 CD I-NP O
th/cmm . O O
HCT NNP B-NP O
36.7 CD I-NP O
36.0-46.0 CD I-NP O
% NN I-NP O
HGB NNP B-NP O
11.2 CD I-NP O
L NNP I-NP O
12.0-16.0 CD I-NP O
gm/dl NN I-NP O
RBC NNP B-NP O
4.68 CD I-NP O
4.00-5.20 CD I-NP O
mil/cmm . O O
PLT NNP B-NP O
313 CD I-NP O
150-350 CD I-NP O
th/cumm . O O
MCV NNP B-NP O
78 CD I-NP O
L NNP I-NP O
80-100 CD I-NP O
fl NN I-NP O
MCH NNP B-NP O
23.8 CD I-NP O
L NNP I-NP O
26.0-34.0 CD I-NP O
pg/rbc NN I-NP O
MCHC NNP B-NP O
30.4 CD I-NP O
L NNP I-NP O
31.0-37.0 CD I-NP O
g/dl NN I-NP O
RDW NNP B-NP O
15.8 CD I-NP O
H NNP I-NP O
11.5-14.5 CD I-NP O
% NN I-NP O
Superstat NNP B-NP O
PT NNP I-NP O
12.6 CD I-NP O
11.1-13.1 CD I-NP O
sec NN I-NP O
Superstat NNP B-NP O
APTT NNP I-NP O
29.4 CD I-NP O
22.1-35.1 CD I-NP O
sec NN I-NP O
DIFFERENTIAL NNP B-NP O
REQUEST NNP I-NP O
RECEIVED NNP I-NP O
Diff JJ B-NP O
Method NNP I-NP O
Auto NN I-NP O
Poly NNP B-NP O
73 CD I-NP O
H NNP I-NP O
40-70 CD I-NP O
% NN I-NP O
Lymphs NNP B-NP O
23 CD I-NP O
22-44 CD I-NP O
% NN I-NP O
Monos NNP B-NP O
2 CD I-NP O
L NNP I-NP O
4-11 CD I-NP O
% NN I-NP O
EOS NNS B-NP O
1 CD B-NP O
0-8 CD I-NP O
% NN I-NP O
Basos NNS B-NP O
1 CD B-NP O
0-3 CD I-NP O
% NN I-NP O
Absolute JJ B-NP O
Neuts NNP I-NP O
8.19 CD I-NP O
H NNP B-NP O
1.8-7.7 CD I-NP O
th/cmm . O O
Absolute JJ B-NP O
Lymphs NNP I-NP O
2.48 CD I-NP O
1.0-4.8 CD I-NP O
th/cmm . O O
Absolute JJ B-NP O
Monos NNP I-NP O
0.26 CD I-NP O
0.2-0.4 CD I-NP O
th/cmm . O O
Absolute JJ B-NP O
EOS NNP I-NP O
0.09 CD I-NP O
L NNP B-NP O
0.1-0.3 CD I-NP O
th/cmm . O O
Absolute JJ B-NP O
Basos NNP I-NP O
0.06 CD I-NP O
0.0-0.3 CD I-NP O
th/cmm . O O
Aniso NNP B-NP O
None NN I-NP O
NORMAL NNP I-NP O
Hypo NNP B-NP O
3+ CD I-NP O
NORMAL NNP I-NP O
Macrocytes NNP B-NP O
None NN I-NP O
Microcytes NNP B-NP O
1+ CD I-NP O
CXR NN B-NP O
: : O O
Bilateral NNP B-NP O
effusions NNS I-NP O
, , O O
left VBD B-VP O
> RB B-ADJP O
right JJ I-ADJP O
. . B-NP O
Pulmonary NNP I-NP O
edema NN I-NP O
. . O O
Cardiac NNP B-NP O
US NNP I-NP O
: : O O
11/17/92 CD O B-DATE
ANATOMIC NNP B-NP O
REGION NNP I-NP O
STATUS NNP I-NP O
ROUTINE NNP I-NP O
DIMENSIONS NNP I-NP O
REGIONAL NNP I-NP O
WALL NNP I-NP O
MOTION NN I-NP O
( -LRB- B-NP O
normal JJ I-NP O
) -RRB- B-NP O
( -LRB- B-VP O
completed VBN I-VP O
only RB B-ADVP O
if IN B-PP O
abn JJ B-ADJP O
. . O O
) -RRB- O O
MITRAL NNP B-NP O
VALVE NNP I-NP O
ABN NNP I-NP O
SEGMENT NNP I-NP O
BASE NNP I-NP O
MID NNP I-NP O
APEX NNP I-NP O
LEFT NNP B-NP O
ATRIUM NNP I-NP O
ABN NNP I-NP O
LA NNP I-NP O
39 CD I-NP O
( -LRB- I-NP O
25-38mm JJ I-NP O
) -RRB- O O
AV. NNP B-NP O
A0 NNP I-NP O
. . I-NP O
LVOT NNP I-NP O
ABN NNP I-NP O
AO NNP I-NP O
33 CD I-NP O
( -LRB- I-NP O
24-39mm JJ I-NP O
) -RRB- I-NP O
anterior CC O O
LEFT NNP B-NP O
VENT. NNP I-NP O
ABN NNP I-NP O
LVIDd NN I-NP O
50 CD B-NP O
( -LRB- I-NP O
37-53mm JJ I-NP O
) -RRB- I-NP O
ant JJ I-NP O
.sep. . O O
TV NN B-NP O
. . O O
RA. '' O O
VC. NNP B-NP O
NORM NNP I-NP O
LVIDs NNP I-NP O
39 CD I-NP O
mid JJ I-NP O
.sep. NNP I-NP O
H NNP I-NP O
PV. NNP B-NP O
INF. NNP I-NP O
PA. NNP I-NP O
NORM NNP I-NP O
PWT NNP I-NP O
13 CD I-NP O
( -LRB- O O
7-11mm UH O O
) -RRB- B-NP O
inf IN B-PP O
.sep. NNP B-NP O
H NNP I-NP O
H NNP I-NP O
RIGHT NNP B-NP O
VENT. NNP I-NP O
NORM NNP I-NP O
IVS NNP I-NP O
13 CD I-NP O
( -LRB- O O
7-11mm UH B-VP O
) -RRB- B-NP O
inferior JJ I-NP O
A DT I-NP O
A DT I-NP O
A NN I-NP O
IAS. NNP B-NP O
IVS. NNP I-NP O
ABN NNP I-NP O
inf.pos NN I-NP O
. . O O
A DT B-NP O
A NNP I-NP O
COMPLEX NNP B-NP O
CHD NNP I-NP O
NORM NNP I-NP O
EF NNP I-NP O
33 CD I-NP O
% NN I-NP O
( -LRB- O O
>50 CD B-NP O
% NN I-NP O
) -RRB- I-NP O
pos NNS I-NP O
.lat , O O
. . O O
H NNP O O
CORONARIES NNS B-NP O
UV NN I-NP O
lateral JJ O O
PERICARDIUM NNP B-NP O
ABN NNP I-NP O
Wall NNP B-NP O
Motion NNP I-NP O
Abbreviations NNP I-NP O
: : O O
N=Normal JJ B-NP O
H=Hypokinetic JJ I-NP O
A=Akinetic JJ I-NP O
D=Dyskinetic JJ I-NP O
MITRAL NNP B-NP O
VALVE CD I-NP O
There EX B-NP O
is VBZ B-VP O
calcification NN B-NP O
of IN B-PP O
the DT B-NP O
posterior JJ I-NP O
mitral JJ I-NP O
annulus NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
mitral JJ B-NP O
valve NN I-NP O
prolapse NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
mild JJ B-NP O
mitral JJ I-NP O
regurgitation NN I-NP O
by IN B-PP O
color NN B-NP O
and CC O O
spectral JJ B-NP O
Doppler NNP I-NP O
. . O O
LEFT NNP B-NP O
ATRIUM NNP I-NP O
The DT B-NP O
left JJ I-NP O
atrium NN I-NP O
is VBZ B-VP O
dilated VBN I-VP O
. . O O
AORTIC NNP B-NP O
VALVE NNP I-NP O
, , O O
AORTA NNP B-NP O
, , O O
LVOT NNP B-NP O
There EX B-NP O
is VBZ B-VP O
thickening NN B-NP O
of IN B-PP O
the DT B-NP O
bases NNS I-NP O
of IN B-PP O
multiple JJ B-NP O
aortic JJ I-NP O
leaflets NNS I-NP O
. . O O
The DT B-NP O
aortic NN I-NP O
valve NN B-NP O
is VBZ B-VP O
tricuspid JJ B-ADJP O
. . O O
There EX B-NP O
is VBZ B-VP O
no DT B-NP O
evidence NN I-NP O
of IN B-PP O
aortic JJ B-NP O
insufficiency NN I-NP O
by IN B-PP O
color NN B-NP O
or CC O O
spectral JJ B-NP O
Doppler NNP I-NP O
. . O O
There EX B-NP O
are VBP B-VP O
irregular JJ B-NP O
echoes NNS I-NP O
along IN B-PP O
the DT B-NP O
aortic JJ I-NP O
wall NN I-NP O
c/w . O O
atheroma NN B-NP O
. . O O
LEFT NNP B-NP O
VENTRICLE NNP I-NP O
The DT B-NP O
left VBD B-VP O
ventricular JJ B-NP O
cavity NN I-NP O
size NN I-NP O
is VBZ B-VP O
normal JJ B-ADJP O
. . O O
The DT O O
left VBD B-VP O
ventricular JJ B-NP O
systolic NN I-NP O
function NN B-NP O
is VBZ B-VP O
impaired VBN I-VP O
. . O O
There EX B-NP O
is VBZ B-VP O
symmetric JJ B-NP O
left JJ I-NP O
ventricular JJ I-NP O
hypertrophy NN I-NP O
. . O O
There EX O O
is VBZ B-VP O
segmental JJ B-NP O
left JJ I-NP O
ventricular JJ I-NP O
dysfunction NN I-NP O
( -LRB- B-VP O
see VB I-VP O
wall NN B-NP O
motion NN I-NP O
plot NN I-NP O
) -RRB- I-NP O
. . O O
This DT O O
involves VBZ B-VP O
the DT B-NP O
lateral JJ I-NP O
,inferior NN I-NP O
and CC O O
apical JJ B-NP O
territory NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
a DT B-NP O
false JJ I-NP O
tendon NN I-NP O
within IN B-PP O
the DT B-NP O
LV NNP I-NP O
cavity NN I-NP O
which WDT B-NP O
is VBZ B-VP O
a DT B-NP O
normal JJ I-NP O
variant NN I-NP O
. . O O
The DT B-NP O
estimated VBN I-NP O
ejection NN I-NP O
fraction NN B-NP O
is VBZ B-VP O
33 CD B-NP O
% NN I-NP O
. . O O
TRICUSPID NNP B-NP O
VALVE NNP I-NP O
- : O O
IVC NNP B-NP O
, , O O
SVC NNP B-NP O
There EX B-NP O
is VBZ B-VP O
color NN B-NP O
and CC O O
spectral JJ B-NP O
Doppler NNP I-NP O
evidence NN I-NP O
of IN B-PP O
trace NN B-NP O
tricuspid JJ I-NP O
insufficiency NN I-NP O
. . O O
PULMONARY NNP B-NP O
VALVE NNP I-NP O
, , O O
INFUND. NNP B-NP O
, , O O
P.A. . O O
There EX B-NP O
is VBZ B-VP O
evidence NN B-NP O
of IN B-PP O
trace NN B-NP O
pulmonary NN I-NP O
insufficiency NN I-NP O
by IN B-PP O
color NN B-NP O
and CC I-NP O
spectral NN I-NP O
Doppler NNP B-NP O
. . O O
RIGHT NNP B-NP O
VENTRICLE NNP I-NP O
The DT B-NP O
right JJ I-NP O
ventricle NN I-NP O
is VBZ B-VP O
not RB I-VP O
dilated VBN I-VP O
. . O O
The DT B-NP O
right NN I-NP O
ventricular VBD B-VP O
systolic JJ B-NP O
function NN I-NP O
is VBZ B-NP O
within IN B-PP O
normal JJ B-NP O
limits NNS I-NP O
. . O O
PERICARDIAL NNP B-NP O
DISEASE NN I-NP O
AND CC I-NP O
EXTRACARDIAC NNPS I-NP O
MASSES NNS I-NP O
There EX B-NP O
is VBZ B-VP O
a DT B-NP O
small JJ I-NP O
circumferential JJ I-NP O
pericardial JJ I-NP O
effusion NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
increased VBN I-VP O
intrapericardial JJ B-NP O
pressure NN I-NP O
without IN B-PP O
evidence NN B-NP O
of IN B-PP O
frank JJ B-NP O
tamponade NN I-NP O
. . O O
There EX O O
is VBZ O O
diffuse JJ B-NP O
fibrin NNS I-NP O
deposition NN I-NP O
on IN B-PP O
the DT B-NP O
visceral JJ I-NP O
pericardium NN I-NP O
. . O O
There EX B-NP O
is VBZ B-VP O
evidence NN B-NP O
of IN B-PP O
a DT B-NP O
pleural JJ B-NP O
effusion NN I-NP O
. . O O
CONCLUSIONS NNS B-NP O
Compared VBN B-VP O
to TO B-PP O
the DT B-NP O
report NN I-NP O
of IN B-PP O
6/5/2089 CD B-NP B-DATE
,the , O O
left VBD B-VP O
ventricular JJ B-NP O
systolic JJ I-NP O
function NN I-NP O
is VBZ B-SBAR O
impaired VBN B-PP O
with IN B-PP O
new JJ B-NP O
wall NN I-NP O
motion NN I-NP O
abnormalities NNS I-NP O
. . O O
Also RB O O
a DT B-NP O
new JJ I-NP O
pericardial JJ I-NP O
effusion NN I-NP O
is VBZ B-VP O
visualized VBN I-VP O
. . O O
EKG NNP B-NP O
: : O O
NSR NNP B-NP O
, , O O
90 CD B-NP O
bpm NN I-NP O
. . B-NP O
ST JJS I-NP O
elevations NNS I-NP O
V1-V6 '' O O
. . O O
ASSESSMENT NNP B-NP O
AND CC I-NP O
PLAN NNP I-NP O
: : O O
76 CD B-NP B-AGE
yo NNP I-NP O
F NNP I-NP O
with IN B-PP O
PVD NNP B-NP O
, , O O
CAD NNP B-NP O
, , O O
s/p NN B-NP O
CABG NNP I-NP O
, , I-NP O
CHF NNP I-NP O
, , I-NP O
with IN B-PP O
acute JJ B-NP O
onset NN I-NP O
SOB NNP I-NP O
, , O O
likely JJ B-NP O
CHF NNP I-NP O
exacerbation NN I-NP O
. . O O
CV NN B-NP O
: : O O
Pt NNP B-NP O
has VBZ B-VP O
diffuse JJ B-NP O
CAD NN I-NP O
with IN B-PP O
propensity NN B-NP O
for IN B-PP O
failure NN B-NP O
, , O O
most RBS B-NP O
likely JJ I-NP O
etiology NN I-NP O
for IN B-PP O
SOB NNP B-NP O
being VBG B-VP O
CHF. . O O
Pump NNP B-NP O
33 CD I-NP O
% NN I-NP O
. . O O
Continue DT O O
beta NN B-NP O
blocker NN I-NP O
, , O O
CCB. . O O
Daily NNP B-NP O
weights NNS I-NP O
, , O O
Is VBZ B-VP O
and CC I-VP O
Os NNS B-NP O
, , O O
diurese JJ B-ADJP O
with IN B-PP O
goal NN B-NP O
of IN B-PP O
-0.5 DT B-NP O
liters NNS I-NP O
QD. . O O
PT/OT NNP B-NP O
for IN B-PP O
chronic JJ B-NP O
deconditioning NN I-NP O
2/2 CD B-NP O
failure NN I-NP O
. . O O
Ischemia NNP B-NP O
. . I-NP O
H/o NNP I-NP O
CABG NNP I-NP O
, , O O
PVD. NNP B-NP O
Cont NNP I-NP O
ASA NNP I-NP O
, , O O
statin NN B-NP O
. . O O
Cycle NNP B-NP O
enzymes NNS I-NP O
. . O O
Serial JJ B-NP O
EKGs NNS I-NP O
. . O O
AdenoMIBI NNP B-NP O
to TO B-VP O
identify VB I-VP O
ischemia NN B-NP O
, , O O
assess VBP B-VP O
CABG NNP B-NP O
grafts NNS I-NP O
, , O O
risk NN B-NP O
for IN B-PP O
failure NN B-NP O
. . O O
Rhythm NN B-NP O
: : O O
sinus NN B-NP O
. . O O
Place NNP B-NP O
pt NN I-NP O
on IN B-PP O
monitor NN B-NP O
given VBN I-NP O
hx NN I-NP O
. . O O
DM NNP B-NP O
: : O O
Sliding VBG B-VP O
scale NN B-NP O
insulin NN I-NP O
. . O O
HTN NNP B-NP O
: : O O
Beta NN B-NP O
blockade NN I-NP O
. . O O
Anxiety NNP B-NP O
: : O O
Uses NNP B-NP O
Klonopin NNP I-NP O
0.5 CD I-NP O
mg NN I-NP O
BID. . O O
GERD NNP B-NP O
: : O O
Prilosec. . O O
FEN NNS B-NP O
: : O O
Cardiac NNP B-NP O
diet NN I-NP O
; : O O
follow VB B-NP O
electrolytes NNS I-NP O
given VBN B-VP O
active JJ B-NP O
diuresis NN I-NP O
. . O O
