Record NNP B-NP O
date NN I-NP O
: : O O
2079-05-14 CD O B-DATE
MEDICINE NNP B-NP O
TEAM NNP I-NP O
4 CD I-NP O
ADMIT NNP I-NP O
NOTE NNP I-NP O
Name NN B-NP O
: : O O
Albert NNP B-NP I-PATIENT
, , O I-PATIENT
Bobbie NNP B-NP I-PATIENT
MRN NNP B-NP O
: : O O
7000963 CD O B-MEDICALRECORD
Date NNP B-NP O
of IN B-PP O
Admission NNP B-NP O
: : O O
5/14/79 CD O B-DATE
Attending VBG B-VP O
: : O O
Dr. NNP B-NP O
Benjamin NNP I-NP B-DOCTOR
Earnest NNP I-NP I-DOCTOR
CC/ID NNP B-NP O
: : O O
pneumonia NN B-NP O
HPI NNP B-NP O
: : O O
44 CD B-NP B-AGE
M NNP I-NP O
s/p NN I-NP O
double JJ I-NP O
lung NN I-NP O
transplant NN I-NP O
in IN B-PP O
2073 CD B-NP B-DATE
for IN B-PP O
bronchiectasis NN B-NP O
( -LRB- I-NP O
on IN B-PP O
2L JJ B-NP O
home NN I-NP O
O2 IN B-PP O
) -RRB- B-NP O
, , O O
HTN NNP B-NP O
, , O O
and CC O O
CKD NNP B-NP O
, , O O
who WP B-NP O
is VBZ B-VP O
directly RB I-VP O
admitted VBN I-VP O
to TO I-VP O
team VB I-VP O
4 CD B-NP O
for IN B-PP O
PNA NNP B-NP O
. . I-NP O
Pt NNP I-NP O
. . O O
was VBD B-VP O
in IN B-PP O
USOH NNP B-NP O
until IN B-PP O
about IN B-NP O
3 CD I-NP O
weeks NNS I-NP O
ago RB B-ADVP O
when WRB B-ADVP O
he PRP B-NP O
first RB B-ADVP O
noted VBD B-VP O
a DT B-NP O
sore JJ I-NP O
throat NN I-NP O
. . O O
He PRP B-NP O
had VBD B-VP O
a DT B-NP O
sick JJ I-NP O
contact NN I-NP O
at IN B-PP O
work NN B-NP O
. . O O
Pt NNP O O
. . O O
saw VBD B-VP O
his PRP$ B-NP O
PCP NNP I-NP O
, , O O
who WP B-NP O
prescribed VBD B-VP O
10 CD B-NP O
days NNS I-NP O
of IN B-PP O
Levaquin NNP B-NP O
. . O O
Although IN B-PP O
the DT B-NP O
sore JJ I-NP O
throat NN I-NP O
resolved VBN B-VP O
after IN B-PP O
about IN B-NP O
one CD I-NP O
week NN I-NP O
, , O O
pt NN B-NP O
. . O O
developed VBD B-VP O
a DT B-NP O
cough NN I-NP O
producing VBG B-VP O
yellowish JJ B-NP O
sputum NN I-NP O
and CC I-NP O
chest NN I-NP O
congestion NN I-NP O
. . O O
Pt NNP B-NP O
. . O O
called VBD B-VP O
his PRP$ B-NP O
pulmonologist NN I-NP O
s PRP B-NP O
office NN B-NP O
( -LRB- O O
Dr. NNP B-NP O
Earnest NNP I-NP B-DOCTOR
) -RRB- I-NP O
and CC O O
was VBD B-VP O
advised VBN I-VP O
to TO I-VP O
have VB I-VP O
a DT B-NP O
sputum NN I-NP O
sample NN I-NP O
sent VBD B-VP O
to TO B-PP O
a DT B-NP O
lab NN I-NP O
in IN B-PP O
Florida NNP B-NP B-STATE
, , O O
where WRB B-ADVP O
pt NN B-NP O
. . B-VP O
lives NNS B-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
also RB I-VP O
advised VBN I-VP O
to TO I-VP O
complete VB I-VP O
his PRP$ B-NP O
Levaquin NNP I-NP O
course NN I-NP O
, , O O
which WDT B-NP O
ended VBD B-VP O
on IN B-PP O
5/10 CD B-NP B-DATE
. . O O
Despite IN B-PP O
completing VBG B-VP O
levaquin JJ B-NP O
course NN I-NP O
, , O O
cough NN B-NP O
, , O O
congestion NN B-NP O
, , O O
and CC O O
mild JJ B-NP O
DOE NNP I-NP O
(occasionally RB B-ADVP O
had VBD B-VP O
to TO I-VP O
increase VB I-VP O
home NN B-NP O
O2 NNS I-NP O
from IN B-PP O
2L JJ B-ADJP O
to TO B-VP O
3L VB I-VP O
) -RRB- B-NP O
persisted VBD B-VP O
. . O O
He PRP B-NP O
noted VBD B-VP O
a DT B-NP O
temperature NN I-NP O
to TO B-PP O
100 CD B-NP O
on IN B-PP O
5/8 CD B-NP B-DATE
, , O O
no DT B-NP O
chills NNS I-NP O
, , O O
no DT B-NP O
chest NN I-NP O
pain NN I-NP O
. . O O
Pt NNP B-NP O
. . O O
again RB B-VP O
called VBN I-VP O
Dr. NNP B-NP O
Earnest NNP I-NP B-DOCTOR
, , O O
who WP B-NP O
ordered VBD B-VP O
chest NN B-NP O
CT NNP I-NP O
, , I-NP O
PFTs NNP I-NP O
, , I-NP O
and CC O O
obtain VB B-VP O
sputum JJ B-NP O
culture NN I-NP O
results NNS I-NP O
from IN B-PP O
lab NN B-NP O
in IN B-PP O
Florida NNP B-NP B-STATE
, , O O
which WDT B-NP O
revealed VBD B-VP O
a DT B-NP O
pathogen NN I-NP O
resistant JJ B-ADJP O
to TO B-PP O
cipro NN B-NP O
( -LRB- I-NP O
did VBD B-VP O
not RB I-VP O
test NN I-VP O
susceptibility NN B-NP O
to TO B-PP O
levoflox NN B-NP O
) -RRB- I-NP O
and CC O O
susceptible JJ B-ADJP O
to TO B-VP O
zosyn VB I-VP O
and CC I-VP O
cefepime VB I-VP O
. . B-NP O
Pt NNP I-NP O
. . O O
is VBZ B-VP O
admitted VBN I-VP O
for IN B-PP O
IV NNP B-NP O
antibiotics NNS I-NP O
. . O O
ROS NNP B-NP O
: : O O
Negative JJ B-ADJP O
in IN B-PP O
detail NN B-NP O
, , O O
including VBG B-PP O
no DT B-NP O
recent JJ I-NP O
unintentional JJ I-NP O
weight NN I-NP O
changes NNS I-NP O
, , O O
HA NNP B-NP O
, , O O
neck NN B-NP O
pain/stiffness NN I-NP O
, , O O
change NN B-NP O
in IN B-PP O
vision NN B-NP O
, , O O
palpitations NNS B-NP O
, , O O
abd NN B-NP O
pain NN I-NP O
, , O O
N/V/D/C NNP B-NP O
, , O O
blood NN B-NP O
in IN B-PP O
stool NN B-NP O
, , I-NP O
dysuria NN I-NP O
, , I-NP O
hematuria NN I-NP O
, , I-NP O
joint/muscle NN I-NP O
pain NN I-NP O
, , O O
numbness NN B-NP O
, , O O
or CC O O
weakness NN B-NP O
. . O O
PMH: . O O
S/p NN B-NP O
double JJ I-NP O
lung NN I-NP O
transplant NN I-NP O
( -LRB- I-NP O
7/73 CD I-NP B-DATE
) -RRB- I-NP O
for IN B-PP O
bronchiectasis NN B-NP O
Hypertension NN B-NP O
CKD NNP B-NP O
( -LRB- I-NP O
baseline NN I-NP O
Cr JJ I-NP O
1.8-2.4 CD I-NP O
) -RRB- O O
OSA . O O
Obesity NN B-NP O
Osteoporosis NN B-NP O
Avascular JJ B-NP O
necrosis NN I-NP O
of IN B-PP O
R NN B-NP O
hip/knee NN I-NP O
Depression NN B-NP O
Psoriasis NN B-NP O
Meds NNS B-NP O
on IN B-PP O
Admit NNP B-NP O
: : O O
acyclovir NN B-NP O
200mg CD I-NP O
po NN I-NP O
TID NN I-NP O
albuterol NN B-NP O
inhaler NN I-NP O
90mcg/spray IN B-PP O
inh JJ B-NP O
q4-6h JJ I-NP O
PRN NN I-NP O
Albuterol NNP B-NP O
Nebulizer NN I-NP O
3ml NN I-NP O
( -LRB- I-NP O
0.083 CD I-NP O
% NN I-NP O
) -RRB- I-NP O
neb NN I-NP O
q4h NN I-NP O
PRN . O O
azithromycin JJ B-NP O
250mg JJ I-NP O
tab NN I-NP O
po NN I-NP O
MWF . O O
Bactrim NNP B-NP O
single JJ I-NP O
strength NN I-NP O
1 CD I-NP O
tab NN I-NP O
po NN I-NP O
MWF . O O
calcium NN B-NP O
citrate NN I-NP O
600 CD B-NP O
mg JJ I-NP O
po NN I-NP O
bid NN I-NP O
Cellcept IN B-PP O
500mg JJ B-NP O
po NN I-NP O
bid NN I-NP O
colistin NN B-NP O
150 CD I-NP O
mg NN I-NP O
inhaled VBN B-VP O
qd . O O
Cozaar NNP B-NP O
100mg CD I-NP O
po NN I-NP O
qd NN I-NP O
doxycycline NN B-NP O
100mg CD I-NP O
po NN I-NP O
bid NN I-NP O
Lasix NNP B-NP O
40 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
Lipitor NNP B-NP O
40mg CD I-NP O
po NN I-NP O
qd NN I-NP O
magnesium NN B-NP O
gluconate JJ I-NP O
1000mg CD I-NP O
po NN I-NP O
tid NN I-NP O
multivitamins NNS B-NP O
1 CD B-NP O
tab NN I-NP O
po NN I-NP O
qd . O O
Nexium NNP B-NP O
20mg CD I-NP O
po NN I-NP O
qd NN I-NP O
Norvasc NNP B-NP O
5 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
pamidronate JJ B-NP O
60mg JJ I-NP O
iv NN I-NP O
q RB B-ADVP O
6 CD B-NP O
months NNS I-NP O
potassium NN B-NP O
chloride NN I-NP O
20mEq IN B-PP O
po NN B-NP O
bid NN I-NP O
prednisone NN B-NP O
15mg CD I-NP O
po NN I-NP O
qd NN I-NP O
Prograf NN B-NP O
1mg CD I-NP O
6 CD I-NP O
caps NNS I-NP O
po NN I-NP O
bid NN I-NP O
Reglan NNP B-NP O
5mg CD I-NP O
po NN I-NP O
qac NN I-NP O
, , O O
qhs NNS B-NP O
Toprol NNP B-NP O
XL NNP I-NP O
50 CD I-NP O
mg NN I-NP O
po NN I-NP O
qd . O O
vitamin NN B-NP O
d VBD B-VP O
50,000 CD B-NP O
IU NNP I-NP O
po NN I-NP O
q NN I-NP O
week NN I-NP O
Allergies NNP B-NP O
: : O O
NKDA NNP B-NP O
Family NNP B-NP O
Hx NNP I-NP O
: : O O
Breast NN B-NP O
cancer NN I-NP O
- : O O
relatives NNS B-NP O
Social NNP B-NP O
Hx NNP I-NP O
: : O O
Lives NNS B-NP O
in IN B-PP O
Florida NNP B-NP B-STATE
w/ JJ I-NP O
wife NN I-NP O
. . O O
Never RB O O
smoked VBD B-VP O
. . O O
No UH O O
EtOH. . O O
PE NN B-NP O
Floor NNP B-NP O
vitals NNS I-NP O
: : O O
T NNP B-NP O
97.9 CD I-NP O
, , O O
HR NNP B-NP O
77 CD I-NP O
, , O O
BP NNP B-NP O
127/67 CD I-NP O
, , O O
RR NNP B-NP O
20 CD I-NP O
, , O O
Sat NNP B-NP O
93 CD I-NP O
% NN I-NP O
on IN B-PP O
2L CD B-NP O
Gen NNP B-NP O
: : B-VP O
alert JJ B-ADJP O
, , O O
in IN B-PP O
NAD NNP B-NP O
HEENT NNP B-NP O
: : O O
NCAT NNP B-NP O
, , O O
PERRLA NNP B-NP O
, , O O
EOMI NNP B-NP O
, , O O
MMM NNP B-NP O
, , O O
OP NNP B-NP O
clear JJ I-NP O
Neck NNP B-NP O
: : O O
Supple NNP B-NP O
, , O O
no DT B-NP O
cervical JJ I-NP O
or CC I-NP O
supraclavicular JJ I-NP O
LAN NNP I-NP O
, , O O
2+ JJ B-NP O
carotids NNS I-NP O
, , O O
no DT B-NP O
bruits NNS I-NP O
, , O O
no DT B-NP O
appreciable JJ I-NP O
JVD NN I-NP O
Chest NNP B-NP O
: : O O
scattered VBN B-VP O
course NN B-NP O
BS NNP I-NP O
, , O O
expiratory NN B-NP O
wheezes NNS I-NP O
Cor NNP B-NP O
: : O O
RRR NNP B-NP O
, , O O
distant JJ B-NP O
heart NN I-NP O
sounds VBZ B-VP O
, , O O
no DT B-NP O
m/r/g NN I-NP O
Abd NNP B-NP O
: : B-VP O
soft JJ B-ADJP O
, , O O
NT NNP B-NP O
, , O O
ND NNP B-NP O
, , O O
BS+ CC O O
Extrem NNP B-NP O
: : O O
trace NN B-NP O
LE JJ I-NP O
edema NN I-NP O
, , O O
2+ JJ B-NP O
PT NNP I-NP O
pulses NNS I-NP O
bilat NN I-NP O
. . O O
Neuro NNP B-NP O
: : O O
alert JJ B-NP O
and CC I-NP O
oriented JJ I-NP O
x3 NNS I-NP O
, , O O
CN NNP B-NP O
2-12 CD I-NP O
intact JJ I-NP O
, , I-NP O
5/5 IN B-PP O
motor NN B-NP O
strength NN I-NP O
and CC I-NP O
nl NN I-NP O
. . O O
sensation NN B-ADJP O
to TO B-PP O
light JJ B-NP O
touch NN I-NP O
in IN B-PP O
all DT B-NP O
extremities NNS I-NP O
Data NNP B-NP O
Test JJ B-NP O
Name NN I-NP O
MARY NN I-NP B-HOSPITAL
05/14/79 CD O B-DATE
08:18 CD O O
NA NNP B-NP O
144 CD I-NP O
K NNP B-NP O
4.4 CD I-NP O
CL NN B-NP O
106 CD I-NP O
CO2 NN B-NP O
28.3 CD I-NP O
BUN NNP B-NP O
36( CD I-NP O
H) . O O
CRE NNP B-NP O
2.5( CD I-NP O
H) . O O
GLU NNP B-NP O
80 CD I-NP O
Test JJ B-NP O
Name NN I-NP O
MARY NN I-NP B-HOSPITAL
05/14/79 CD O B-DATE
08:18 CD O O
CA NNP B-NP O
9.9 CD I-NP O
TBILI RB B-NP O
0.3 CD I-NP O
TP NNP B-NP O
7.1 CD I-NP O
ALB NNP B-NP O
4.0 CD I-NP O
GLOB NNP B-NP O
3.1 CD I-NP O
Test JJ B-NP O
Name NN I-NP O
MARY NN I-NP B-HOSPITAL
05/14/79 CD O B-DATE
08:18 CD O O
ALT/SGPT NNP B-NP O
13 CD I-NP O
AST/SGOT NNP B-NP O
10 CD I-NP O
ALKP NNP B-NP O
88 CD I-NP O
TBILI RB B-NP O
0.3 CD I-NP O
Test JJ B-NP O
Name NN I-NP O
MARY NN I-NP B-HOSPITAL
05/14/79 CD O B-DATE
08:18 CD O O
CHOL NNP B-NP O
115( JJ I-NP O
T NNP I-NP O
) -RRB- O O
TRIG NN B-NP O
89 CD I-NP O
HDL NNP B-NP O
51 CD I-NP O
LDL NNP B-NP O
46( JJ I-NP O
T NNP I-NP O
) -RRB- O O
CHOL/HDL NNP B-NP O
2.3( JJ I-NP O
T NNP I-NP O
) -RRB- O O
Test JJ B-NP O
Name NN I-NP O
MARY NN I-NP B-HOSPITAL
05/14/79 CD O B-DATE
08:18 CD O O
WBC NNP B-NP O
10.9 CD I-NP O
RBC NNP B-NP O
4.36( JJ I-NP O
L NNP I-NP O
) -RRB- O O
HGB NNP B-NP O
13.9 CD I-NP O
HCT NNP B-NP O
40.7( JJ I-NP O
L NNP I-NP O
) -RRB- O O
MCV NNP B-NP O
94 CD I-NP O
MCH NNP B-NP O
31.9 CD I-NP O
MCHC NNP B-NP O
34.1 CD I-NP O
PLT NNP B-NP O
159 CD I-NP O
RDW NNP B-NP O
15.7( CD I-NP O
H) . O O
DIFFR NNP B-NP O
Received NNPS I-NP O
METHOD NNP B-NP O
Auto NN I-NP O
%NEUT NNP B-NP O
79( CD I-NP O
H) . O O
%LYMPH NNP B-NP O
11( JJ I-NP O
L NNP I-NP O
) -RRB- O O
%MONO NN B-NP O
7 CD I-NP O
%EOS NNS B-NP O
3 CD I-NP O
%BASO NN B-NP O
0 CD I-NP O
ANEUT NNP B-NP O
8.63( CD I-NP O
H) . O O
ALYMP NNP B-NP O
1.20 CD I-NP O
AMONS NNP B-NP O
0.71( CD I-NP O
H) . O O
AEOSN NNP B-NP O
0.33( CD I-NP O
H) . O O
ABASOP NNP B-NP O
0.04 CD I-NP O
ANISO NNP B-NP O
None NN I-NP O
HYPO NNP B-NP O
None NN I-NP O
MACRO NNP B-NP O
None NN I-NP O
MICRO NNP B-NP O
None NN I-NP O
Test JJ B-NP O
Name NN I-NP O
MARY NN I-NP B-HOSPITAL
05/14/79 CD O B-DATE
08:18 CD O O
TACRO NNP B-NP O
11 CD I-NP O
Chest NNP B-NP O
CT NNP I-NP O
: : O O
pending VBG B-NP O
PFTs NNS B-NP O
: : O O
FEV1 NNP B-NP O
, , I-NP O
FVC NNP I-NP O
and CC I-NP O
FEV1/FVC NNP I-NP O
are VBP B-VP O
reduced VBN I-VP O
. . O O
TLC NNP B-NP O
is VBZ B-VP O
normal JJ B-ADJP O
. . O O
FRC NNP B-NP O
is VBZ B-VP O
normal JJ B-ADJP O
. . B-NP O
RV NN I-NP O
is VBZ B-LST O
increased VBN B-VP O
. . B-NP O
RV/TLC NNP I-NP O
ratio NN I-NP O
is VBZ B-VP O
increased VBN I-VP O
. . O O
Resistance NN B-NP O
is VBZ B-VP O
increased VBN I-VP O
; : O O
specific JJ O O
conductance NN B-NP O
is VBZ B-VP O
decreased VBN I-VP O
. . B-NP O
Single NNP I-NP O
breath NN I-NP O
diffusion NN I-NP O
capacity NN I-NP O
is VBZ B-VP O
reduced VBN I-VP O
. . O O
Floor NNP B-NP O
EKG NNP I-NP O
: : O O
sinus NN B-NP O
at IN B-PP O
75 CD B-NP O
bpm NN I-NP O
, , O O
nl JJ B-NP O
. . I-NP O
Axis NNP I-NP O
, , O O
nl NN B-NP O
. . O O
Intervals NNS B-NP O
, , O O
no DT B-NP O
significant JJ I-NP O
ST-T NNP I-NP O
abnormalities NNS I-NP O
Assessment/Plan NNP B-NP O
: : O O
44 CD B-NP B-AGE
M NNP I-NP O
s/p NN I-NP O
double JJ I-NP O
lung NN I-NP O
transplant NN I-NP O
in IN B-PP O
2073 CD B-NP B-DATE
for IN B-PP O
bronchiectasis NN B-NP O
, , O O
HTN NNP B-NP O
, , O O
CKD NNP B-NP O
, , O O
admitted VBD B-VP O
w/ NNS B-NP O
PNA NNP I-NP O
. . O O
PNA . O O
Tx NNP B-NP O
w/ VBD B-VP O
Cefepime NNP B-NP O
and CC I-NP O
Zosyn NNP I-NP O
given VBN I-NP O
susceptibilities NNS I-NP O
from IN B-PP O
OSH NNP B-NP O
sputum NN I-NP O
cx NN I-NP O
Cont NNP B-NP O
. . B-VP O
colistin NN B-NP O
nebs NNS I-NP O
, , O O
albuterol NN B-NP O
nebs NNS I-NP O
F/u NNP B-NP O
chest NN I-NP O
CT . O O
s/p NN B-NP O
Lung NNP I-NP O
Transplant NNP I-NP O
Cont NNP B-NP O
. . I-NP O
Cellcept NNP I-NP O
, , O O
tacrolimus NN B-NP O
, , O O
prednisone NN B-NP O
Cont NNP B-NP O
. . I-NP O
bactrim NN I-NP O
, , O O
doxycycline NN B-NP O
, , O O
acyclovir NN B-NP O
, , O O
azithromycin . O O
CV NN B-NP O
Cont NNP B-NP O
. . B-VP O
cozaar NN B-NP O
, , I-NP O
lasix NN I-NP O
, , I-NP O
lipitor NN I-NP O
, , I-NP O
norvasc NN I-NP O
, , O O
Toprol NNP B-NP O
CKD NN B-NP O
Creatinine NNP B-NP O
appears VBZ B-VP O
to TO I-VP O
be VB I-VP O
at IN B-PP O
baseline NN B-NP O
, , O O
will MD B-VP O
follow VB I-VP O
. . O O
OSA . O O
CPAP NNP B-NP O
at IN B-PP O
night NN B-NP O
Prophy NN B-NP O
Heparin NNP B-NP O
sc NN I-NP O
Omeprazole . O O
Garrett NNP B-NP B-DOCTOR
Albert NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
PGY-3 NN B-NP O
# # B-NP O
54644 CD I-NP B-PHONE
