Record NNP B-NP O
date NN I-NP O
: : O O
2061-08-26 CD O B-DATE
MICU NNP B-NP O
Intern NNP I-NP O
Admit NNP I-NP O
Note NNP I-NP O
, , O O
Internal NNP B-NP O
Medicine NNP I-NP O
name NN B-NP O
: : O O
Goins NNP B-NP I-PATIENT
, , O I-PATIENT
Jacob NNP B-NP I-PATIENT
MR# NNP B-NP O
: : O O
Transfer NN B-NP O
from IN B-PP O
Linden NNP B-NP B-HOSPITAL
Health NNP I-NP I-HOSPITAL
Care NNP I-NP I-HOSPITAL
Center NNP I-NP I-HOSPITAL
Date NNP B-NP O
of IN B-PP O
Admission NNP B-NP O
: : O O
08/25/61 CD O B-DATE
Full NNP B-NP O
code NN I-NP O
Contact JJ B-NP O
information NN I-NP O
: : O O
CC/HPI NNP B-NP O
: : O O
27 CD B-NP B-AGE
yo NNP I-NP O
male NN I-NP O
from IN B-PP O
Cedar NNP B-NP B-CITY
Hill NNP I-NP I-CITY
Lakes NNP I-NP I-CITY
, , O O
Nevada NNP B-NP B-STATE
w/ VBD B-VP O
history NN B-NP O
of IN B-PP O
insulin-requiring JJ B-NP O
DM NNP I-NP O
previously RB B-ADVP O
followed VBD B-VP O
at IN B-PP O
Cottage NNP B-NP B-HOSPITAL
Sanatorium NNP I-NP I-HOSPITAL
, , O O
admitted VBN B-VP O
to TO B-PP O
Linden NNP B-NP B-HOSPITAL
Health NNP I-NP I-HOSPITAL
Care NNP I-NP I-HOSPITAL
Center NNP I-NP I-HOSPITAL
after IN B-PP O
becoming VBG B-VP O
unresponsive JJ B-ADJP O
during IN B-PP O
a DT B-NP O
visit NN I-NP O
to TO B-PP O
his PRP$ B-NP O
sister NN I-NP O
in IN B-PP O
Maryland NNP B-NP B-STATE
. . O O
By IN B-PP O
report NN B-NP O
, , O O
patient NN B-NP O
was VBD B-VP O
sitting VBG I-VP O
on IN B-PP O
the DT B-NP O
couch NN I-NP O
at IN B-PP O
his PRP$ B-NP O
sister NN I-NP O
's POS B-NP O
house NN I-NP O
, , O O
slumped VBD B-VP O
to TO B-PP O
the DT B-NP O
floor NN I-NP O
and CC O O
had VBD B-VP O
seizure NN B-NP O
activity NN I-NP O
x NN I-NP O
45seconds VBD B-VP O
that DT B-NP O
was VBD B-VP O
witnessed VBN I-VP O
by IN B-PP O
EMS NNP B-NP O
sevices NNS I-NP O
. . O O
Accu-checks NNS B-NP O
done VBN B-VP O
at IN B-PP O
that DT B-NP O
time NN I-NP O
were VBD B-VP O
>500 CD B-NP O
and CC I-NP O
attempts NNS I-NP O
at IN B-PP O
intubation NN B-NP O
were VBD B-VP O
unsuccessful JJ B-ADJP O
. . O O
He PRP B-NP O
was VBD B-VP O
transported VBN I-VP O
to TO B-PP O
ER NNP B-NP O
, , O O
where WRB B-ADVP O
additional JJ B-NP O
attempts NNS I-NP O
to TO B-VP O
secure VB I-VP O
his PRP$ B-NP O
airway NN I-NP O
were VBD B-VP O
also RB B-ADJP O
unsuccessful JJ I-ADJP O
, , O O
by IN B-PP O
2 CD B-NP O
physicians NNS I-NP O
. . O O
There EX O O
appeared VBD B-VP O
to TO I-VP O
be VB I-VP O
some DT B-NP O
sot NN I-NP O
of IN B-PP O
stricture NN B-NP O
in IN B-PP O
the DT B-NP O
upper JJ I-NP O
airway NN I-NP O
( -LRB- I-NP O
not RB I-NP O
obvious JJ I-NP O
on IN B-PP O
CT JJ B-NP O
scan NN I-NP O
) -RRB- I-NP O
. . O O
However RB B-ADVP O
, , O O
pt NN B-NP O
had VBD B-VP O
witnessed VBN I-VP O
emesis NN B-NP O
, , O O
and CC O O
was VBD B-VP O
placed VBN I-VP O
on IN B-PP O
100 CD B-NP O
% NN I-NP O
nonrebreather JJ I-NP O
mask NN I-NP O
, , O O
with IN B-PP O
Versed NNP B-NP O
and CC I-NP O
propofol NN I-NP O
for IN B-PP O
sedation NN B-NP O
with IN B-PP O
adequate JJ B-NP O
O2 NNP I-NP O
saturation NN I-NP O
. . O O
A DT B-NP O
x-ray NN I-NP O
confirmed VBD B-VP O
dependent JJ B-NP O
lung NN I-NP O
infiltrates VBZ B-VP O
consistent JJ B-ADJP O
with IN B-PP O
aspiration NN B-NP O
pneumonia NN I-NP O
, , O O
and CC O O
pt NN B-NP O
was VBD B-VP O
started VBN I-VP O
on IN B-PP O
Clindamycin NNP B-NP O
. . O O
On IN B-SBAR O
arrival NN B-NP O
to TO B-PP O
the DT B-NP O
ER NNP I-NP O
, , O O
patient NN B-NP O
was VBD B-VP O
also RB I-VP O
found VBN I-VP O
to TO I-VP O
have VB I-VP O
a DT B-NP O
blood NN I-NP O
pressure NN I-NP O
of IN B-PP O
248/146 CD B-NP O
. . O O
He PRP B-NP O
received VBD B-VP O
50mg JJ B-NP O
dose NN I-NP O
of IN B-PP O
labetolol NN B-NP O
in IN B-PP O
the DT B-NP O
ER NNP I-NP O
as RB B-ADVP O
well RB I-ADVP O
as IN B-PP O
several JJ B-NP O
additional JJ I-NP O
doses NNS I-NP O
in IN B-PP O
the DT B-NP O
ICU. NNP I-NP O
In IN B-PP O
the DT B-NP O
ICU NNP I-NP O
, , O O
patient NN B-NP O
did VBD B-VP O
not RB I-VP O
have VB I-VP O
any DT B-NP O
further JJ I-NP O
witnessed VBN I-NP O
seizure NN I-NP O
activity NN I-NP O
. . O O
A DT B-NP O
Head NNP I-NP O
CT NNP I-NP O
demonstrated VBD B-VP O
no DT B-NP O
focal JJ I-NP O
lesion NN I-NP O
, , O O
IC NN B-NP O
hemorrhage NN I-NP O
or CC I-NP O
other JJ I-NP O
abnormality NN I-NP O
. . O O
Pt NN B-NP O
was VBD B-VP O
treated VBN I-VP O
with IN B-PP O
dilantin NN B-NP O
and CC I-NP O
IV NNP I-NP O
insulin NN I-NP O
infusion NN I-NP O
. . O O
Serum NN B-NP O
ketones NNS I-NP O
were VBD B-VP O
negative JJ B-ADJP O
. . O O
Additional JJ B-NP O
workup NN I-NP O
revealed VBD B-VP O
LVH NNP B-NP O
by IN B-PP O
EKG NNP B-NP O
criteria NNS I-NP O
, , O O
as RB B-CONJP O
well RB I-CONJP O
as IN I-CONJP O
renal JJ B-NP O
insufficiency NN I-NP O
Cr NNP B-NP O
2.6. . I-NP O
Urine NNP I-NP O
tox NN I-NP O
was VBD B-VP O
positive JJ B-ADJP O
for IN B-PP O
benzos NNS B-NP O
, , O O
but CC O O
was VBD B-VP O
otherwise RB B-ADVP O
negative JJ B-ADJP O
. . O O
Patient NNP B-NP O
also RB B-ADVP O
developed VBD B-VP O
leukoytosis NN B-NP O
( -LRB- I-NP O
WBC JJ I-NP O
? . O O
) -RRB- O O
with IN B-PP O
temp NN B-NP O
of IN B-PP O
102 CD B-NP O
degrees NNS I-NP O
. . O O
Although IN B-SBAR O
he PRP B-NP O
had VBD B-VP O
minimal JJ B-NP O
neck NN I-NP O
stiffness NN I-NP O
by IN B-PP O
neurology NN B-NP O
consult VB B-VP O
exam NN B-NP O
, , O O
he PRP B-NP O
underwent VBD B-VP O
a DT B-NP O
lumbar NN I-NP O
puncture NN I-NP O
that WDT B-NP O
demonstrated VBD B-VP O
a DT B-NP O
colorless JJ I-NP O
clear JJ I-NP O
fluid NN I-NP O
, , O O
with IN B-PP O
glucose NN B-NP O
of IN B-PP O
108 CD B-NP O
, , O O
TP NNP B-NP O
44 CD I-NP O
. . O O
Grams NNP B-NP O
stain NN I-NP O
was VBD B-VP O
negative JJ B-ADJP O
. . O O
Tube NNP O O
# # B-NP O
4 CD I-NP O
contained VBD B-VP O
21RBCs JJ B-NP O
and CC I-NP O
7 CD I-NP O
WBCs NNS I-NP O
with IN B-PP O
a DT B-NP O
diff NN I-NP O
of IN B-PP O
96 CD B-NP O
% NN I-NP O
PMNs NNP I-NP O
and CC O O
4 CD B-NP O
% NN I-NP O
lymphs NNS I-NP O
. . O O
CSF NNP B-NP O
cultures NNS I-NP O
and CC O O
blood NN B-NP O
cultures NNS I-NP O
were VBD B-VP O
also RB I-VP O
done VBN I-VP O
, , O O
and CC O O
are VBP B-VP O
pending VBG I-VP O
. . O O
During IN B-PP O
his PRP$ B-NP O
hospital NN I-NP O
course NN I-NP O
, , O O
patient NN B-NP O
maintained VBD B-VP O
adequate JJ B-NP O
oxygenation NN I-NP O
with IN B-PP O
nasal JJ B-NP O
trumpet NN I-NP O
in IN B-PP O
place NN B-NP O
. . O O
ABG '' O O
on IN B-PP O
08/25/61 CD B-NP B-DATE
am RB B-ADVP O
was VBD B-VP O
7.36/PCO2 CD B-NP O
45/ CD I-NP O
PO2 NNP B-NP O
366 CD I-NP O
, , O O
with IN B-PP O
bicarb NN B-NP O
of IN B-PP O
25 CD B-NP O
and CC I-NP O
100 CD I-NP O
% NN I-NP O
sats NNS I-NP O
. . B-PP O
His PRP$ B-NP O
FIO2 NNP I-NP O
was VBD B-VP O
subsequently RB I-VP O
weaned VBN I-VP O
. . O O
He PRP B-NP O
remained VBD B-VP O
hemodynamically RB B-ADJP O
stable JJ I-ADJP O
with IN B-PP O
BP NNP B-NP O
184/88 CD I-NP O
( -LRB- O O
MAP NNP B-NP O
114 CD I-NP O
) -RRB- I-NP O
HR100 CD I-NP O
, , I-NP O
RR23 CD I-NP O
, , I-NP O
97 CD I-NP O
% NN I-NP O
on IN B-PP O
cannula NNS B-NP O
. . O O
Cardiac NNP B-NP O
enzymes NNS I-NP O
were VBD B-VP O
negative JJ B-ADJP O
. . O O
After IN B-PP O
patient NN B-NP O
's POS B-NP O
mother NN I-NP O
arrived VBD B-VP O
from IN B-PP O
Georgia NNP B-NP B-STATE
, , O O
she PRP B-NP O
requested VBD B-VP O
transfer NN B-NP O
to TO B-PP O
BMH NNP B-NP B-HOSPITAL
. . O O
Had VBD B-VP O
no DT B-NP O
reported VBN I-NP O
history NN I-NP O
of IN B-PP O
hypertension NN B-NP O
or CC I-NP O
seizure NN I-NP O
disorders NNS I-NP O
. . O O
Mother NN B-NP O
reports VBZ B-VP O
patient NN B-NP O
having VBG B-VP O
occasional JJ B-NP O
spells NNS I-NP O
in IN B-PP O
the DT B-NP O
past JJ I-NP O
, , O O
lasting VBG B-VP O
5-10minutes NNS B-NP O
where WRB B-ADVP O
patient NN B-NP O
would MD B-VP O
become VB I-VP O
non JJ B-ADJP O
communicative JJ I-ADJP O
, , O O
associated VBN B-VP O
with IN B-PP O
elevated JJ B-NP O
glucose NN I-NP O
. . O O
PMH: . O O
1 LS O O
. . B-NP O
Insulin NNP I-NP O
dependent JJ I-NP O
DM NNP I-NP O
, , O O
diagnosed VBD B-VP O
age NN B-NP O
12 CD I-NP B-AGE
. . O O
Was VBD B-VP O
followed VBN I-VP O
at IN B-PP O
Cottage NNP B-NP B-HOSPITAL
Sanatorium NNP I-NP I-HOSPITAL
but CC O O
has VBZ B-VP O
not RB I-VP O
had VBN I-VP O
PCP NNS B-NP O
or CC O O
regular JJ B-NP O
care NN I-NP O
for IN B-PP O
some DT B-NP O
time NN I-NP O
. . O O
Medications NNPS B-NP O
On IN B-PP O
Admission NNP B-NP O
: : O O
1 CD B-NP O
. . O O
Labetolol NNP O O
20mg CD B-NP O
IV NNP I-NP O
q1hr NNP I-NP O
PRN NNP I-NP O
MAP>120 . O O
2. . B-NP O
Ativan NNP I-NP O
1-2mg JJ I-NP O
IV NNP I-NP O
q1h NNP I-NP O
PRN NNP I-NP O
3. DT B-NP O
Insulin NNP I-NP O
gtt NN I-NP O
( -LRB- I-NP O
currently RB B-ADVP O
4u/hr VBP B-VP O
) -RRB- O O
4 CD B-LST O
. . O O
Clindamycin NNP B-NP O
600mg CD I-NP O
IV NNP I-NP O
q6h NN I-NP O
for IN B-PP O
aspiration NN B-NP O
pneumonitis NN I-NP O
5 CD B-NP O
. . O O
Pepcid NNP B-NP O
20mg CD I-NP O
IV NNP I-NP O
QD NNP I-NP O
6 CD B-NP O
. . O O
Dilantin NNP B-NP O
100mg CD I-NP O
IV NNP I-NP O
q8h . O O
7. DT B-NP O
IV NNP I-NP O
NTG NNP I-NP O
5mcg/min CD I-NP O
during IN B-PP O
transfer NN B-NP O
Allergies NNP B-NP O
: : O O
NKDA NNP B-NP O
per IN B-PP O
OSH NNP B-NP O
Soc NNP B-NP O
Hx NNP I-NP O
: : O O
Lives NNS B-NP O
with IN B-PP O
Mother NNP B-NP O
in IN B-PP O
Waycross NNP B-NP B-CITY
, , O O
and CC O O
works NNS B-NP O
in IN B-PP O
a DT B-NP O
store NN I-NP O
(unclear JJ I-NP O
type NN I-NP O
) -RRB- I-NP O
. . O O
He PRP B-NP O
leaves VBZ B-VP O
home NN B-NP O
for IN B-SBAR O
He PRP B-NP O
does VBZ B-VP O
not RB I-VP O
smoke VB I-VP O
, , O O
but CC O O
does VBZ B-VP O
have VB I-VP O
drinking NN B-NP O
binges NNS I-NP O
reported VBN B-VP O
by IN B-PP O
his PRP$ B-NP O
mother NN I-NP O
when WRB B-ADVP O
he PRP B-NP O
associates NNS B-VP O
with IN B-PP O
several JJ B-NP O
groups NNS I-NP O
of IN B-PP O
friends NNS B-NP O
. . O O
Mother NN B-NP O
is VBZ B-VP O
not RB O O
aware JJ B-ADJP O
of IN B-PP O
drug NN B-NP O
use NN I-NP O
, , O O
but CC O O
also RB B-ADVP O
cannot MD B-VP O
rule VB I-VP O
it PRP B-NP O
out RP B-VP O
. . O O
FH NNP B-NP O
: : O O
HTN NNP B-NP O
mother NN I-NP O
and CC I-NP O
father NN I-NP O
Exam NNP B-NP O
: : O O
VS NNP B-NP O
: : O O
T NNP B-NP O
99 CD I-NP O
HR NNP I-NP O
92 CD I-NP O
BP NNP I-NP O
182/8 CD I-NP O
0 CD I-NP O
RR NNP I-NP O
20 CD I-NP O
O2sat NNP B-NP O
95-98 CD I-NP O
%FIO2 . O O
RA NNP O O
General NNP B-NP O
: : O O
Responds NNS B-NP O
/localizes VBZ B-VP O
pain NN B-NP O
, , O O
moving VBG B-VP O
all DT B-NP O
extremities NNS I-NP O
. . O O
HEENT NNP B-NP O
: : O O
NCAT NN B-NP O
, , O O
pupils NNS B-NP O
small JJ B-ADJP O
but CC I-ADJP O
reactive JJ I-ADJP O
, , O O
eyes NNS B-NP O
conjugate NN I-NP O
Chest NNP B-NP O
: : O O
CTA NNP B-NP O
B NNP I-NP O
CVS NNP B-NP O
: : O O
S1 NNP B-NP O
S2 NNP I-NP O
+S3 NNP I-NP O
, , O O
no DT B-NP O
murmurs NNS I-NP O
. . O O
Abd NNP B-NP O
: : O O
+BS NNP B-NP O
, , I-NP O
soft JJ I-NP O
, , I-NP O
non-tender JJ I-NP O
, , I-NP O
non-distended JJ I-NP O
. . B-NP O
Subcutaneous JJ I-NP O
indurated VBN I-NP O
tissue NN I-NP O
mid NN I-NP O
Left VBD B-VP O
upper JJ B-NP O
abdomen NN I-NP O
, , O O
4x5cm UH B-NP O
. . O O
Extr NNP B-NP O
: : O O
Normal JJ B-NP O
bulk/tone NN I-NP O
. . O O
Multiple VB B-VP O
round RB B-NP O
dark JJ I-NP O
lesions NNS I-NP O
right JJ B-NP O
arm NN I-NP O
; : O O
indurated VBN B-NP O
3x4cm IN B-PP O
subcutaneous JJ B-NP O
areas NNS I-NP O
on IN B-PP O
bilateral JJ B-NP O
thighs NNS I-NP O
anteriorly RB B-ADVP O
. . O O
No DT B-NP O
edema NN I-NP O
BLE NN I-NP O
; : O O
2+DP. . O O
DATA NNP B-NP O
( -LRB- I-NP O
08/25/61 NN I-NP B-DATE
) -RRB- I-NP O
: : O O
Unspecified NNP B-NP O
pH NN I-NP O
7.42 CD B-NP O
( -LRB- I-NP O
7.32-7.45 CD I-NP O
) -RRB- O O
Unspecified NNP B-NP O
PCO2 NN I-NP O
35 CD B-NP O
( -LRB- I-NP O
35-50 CD I-NP O
) -RRB- I-NP O
mm/Hg . O O
Unspecified NNP B-NP O
PO2 CD I-NP O
74 CD I-NP O
( -LRB- I-NP O
40-90 CD I-NP O
) -RRB- I-NP O
mm/Hg . O O
WBC NNP B-NP O
22.6 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
4.5-11.0) JJ I-NP O
th/cmm NN I-NP O
HCT NN B-NP O
42.1 CD I-NP O
( -LRB- O O
41.0-53.0) CD B-NP O
% NN I-NP O
HGB NN B-NP O
14.0 CD I-NP O
( -LRB- I-NP O
13.5-17.5 CD I-NP O
) -RRB- I-NP O
gm/dl . O O
RBC NNP B-NP O
5.03 CD I-NP O
( -LRB- I-NP O
4.50-5.90 CD I-NP O
) -RRB- I-NP O
mil/cmm . O O
PLT NNP B-NP O
677 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
150-350 CD I-NP O
) -RRB- I-NP O
th/cumm . O O
MCV NN B-NP O
84 CD I-NP O
( -LRB- I-NP O
80-100 CD B-PP O
) -RRB- B-NP O
fl NN I-NP O
MCH NNP B-NP O
27.8 CD I-NP O
( -LRB- I-NP O
26.0-34.0) JJ I-NP O
pg/rbc NN I-NP O
MCHC NNP B-NP O
33.3 CD I-NP O
( -LRB- O O
31.0-37.0) CD B-NP O
g/dl NN I-NP O
RDW NNP B-NP O
12.2 CD I-NP O
( -LRB- I-NP O
11.5-14.5 CD B-PP O
) -RRB- B-NP O
% NN I-NP O
PT NNP B-NP O
13.4 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
11.3-13.3 CD B-PP O
) -RRB- B-NP O
sec NN I-NP O
APTT NNP B-NP O
26.1 CD I-NP O
( -LRB- I-NP O
22.1-35.1 CD B-PP O
) -RRB- B-NP O
sec NN I-NP O
Poly NNP B-NP O
82 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
40-70 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Lymphs NNP B-NP O
10 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
22-44 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
Monos NN B-NP O
7 CD I-NP O
( -LRB- I-NP O
4-11 CD I-NP O
) -RRB- B-NP O
% NN I-NP O
EOS NNS B-NP O
1 CD B-NP O
(0-8 CD I-NP O
) -RRB- O O
% NN O O
Basos NNS B-NP O
0 CD B-NP O
(0-3 JJ I-NP O
) -RRB- I-NP O
% NN I-NP O
Absolute JJ B-NP O
Neuts NNP I-NP O
18.54 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
1.8-7.7 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Lymphs NNP I-NP O
2.31 CD I-NP O
( -LRB- I-NP O
1.0-4.8 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Monos NNP I-NP O
1.56 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.2-0.4 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
EOS NNP I-NP O
0.12 CD I-NP O
( -LRB- I-NP O
0.1-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Absolute JJ B-NP O
Basos NNP I-NP O
0.07 CD I-NP O
( -LRB- I-NP O
0.0-0.3 CD I-NP O
) -RRB- I-NP O
th/cmm . O O
Aniso NNP B-NP O
None NN I-NP O
( -LRB- I-NP O
NORMAL NNP I-NP O
) -RRB- O O
Hypo NNP B-NP O
None NN I-NP O
( -LRB- I-NP O
NORMAL NNP I-NP O
) -RRB- O O
Macrocytes NNP B-NP O
None NN I-NP O
Microcytes NNS B-NP O
None NN I-NP O
Sodium NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
145 CD I-NP O
( -LRB- I-NP O
135-145 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Potassium NNP B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
3.2 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
3.4-4.8 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Chloride NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
117 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
100-108 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
CO2 NN B-NP O
( -LRB- I-NP O
Stat NNP I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
25.5 CD I-NP O
( -LRB- I-NP O
23.0-31.9 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
BUN NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
21 CD I-NP O
(8-25 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Creatinine NNP B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NN I-NP O
) -RRB- I-NP O
2.5 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.6-1.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Glucose FW B-NP O
( -LRB- I-NP O
Stat NN I-NP O
Lab NNP I-NP O
) -RRB- I-NP O
233 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
70-110 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Calcium NNP B-NP O
8.9 CD I-NP O
( -LRB- I-NP O
8.5-10.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Phosphorus NNP B-NP O
1.8 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
2.6-4.5 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Plasma NNP B-NP O
Lactic NNP I-NP O
Acid NNP I-NP O
2.5 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.5-2.2 CD I-NP O
) -RRB- I-NP O
mmol/L . O O
Magnesium NNP B-NP O
2.1 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
1.4-2.0) CD I-NP O
meq/L NN I-NP O
Total JJ B-NP O
Protein NNP I-NP O
7.0 CD I-NP O
( -LRB- I-NP O
6.0-8.3 CD I-NP O
) -RRB- I-NP O
g/dl . O O
Albumin NNP B-NP O
2.7 CD I-NP O
L NNP I-NP O
( -LRB- I-NP O
3.3-5.0) JJ I-NP O
g/dl NN I-NP O
Globulin NNP B-NP O
4.3 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
2.6-4.1 CD I-NP O
) -RRB- I-NP O
g/dl . O O
Direct JJ B-NP O
Bilirubin NNP I-NP O
0.2 CD I-NP O
(0-0.4 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Total JJ B-NP O
Bilirubin NNP I-NP O
1.1 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
0.0-1.0) JJ I-NP O
mg/dl NN I-NP O
Triglycerides NNS B-NP O
118 CD B-NP O
( -LRB- I-NP O
40-150 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Cholesterol NNP B-NP O
307 CD I-NP O
mg/dl NN I-NP O
High NNP B-NP O
Density NNP I-NP O
Lipoprotein NNP I-NP O
85 CD I-NP O
( -LRB- I-NP O
35-100 CD I-NP O
) -RRB- I-NP O
mg/dl . O O
Alkaline NNP B-NP O
Phosphatase NNP I-NP O
81 CD I-NP O
( -LRB- I-NP O
45-115 CD I-NP O
) -RRB- I-NP O
U/L . O O
Transaminase-SGPT NNP B-NP O
27 CD I-NP O
( -LRB- I-NP O
10-55 CD I-NP O
) -RRB- I-NP O
U/L . O O
Amylase NNP B-NP O
222 CD I-NP O
H NNP B-NP O
(3-100 CD I-NP O
) -RRB- O O
units/L NN O O
Lipase NN B-NP O
1.4 CD I-NP O
( -LRB- O O
1.3-6.0) CD B-NP O
U/dl NN I-NP O
Creatine JJ B-NP O
Kinase NNP I-NP O
Isoenzymes NNP I-NP O
6.0 CD I-NP O
( -LRB- I-NP O
0.0-6.9 CD I-NP O
) -RRB- I-NP O
ng/ml . O O
CPK NNP B-NP O
Isoenzymes NNP I-NP O
Index NNP I-NP O
0.1 CD I-NP O
( -LRB- I-NP O
0.0-3.5 CD B-PP O
) -RRB- B-NP O
% NN I-NP O
Troponin-T NNP B-NP O
0.04 CD I-NP O
( -LRB- I-NP O
0.00-0.09 CD I-NP O
) -RRB- I-NP O
ng/ml . O O
Transaminase-SGOT NNP B-NP O
81 CD I-NP O
H NNP I-NP O
( -LRB- I-NP O
10-40 CD I-NP O
) -RRB- I-NP O
U/L . O O
Creatine JJ B-NP O
Kinase NNP I-NP O
7511 CD I-NP O
H NNP B-NP O
(60-400 CD I-NP O
) -RRB- I-NP O
U/L . O O
Phenytoin NNP B-NP O
( -LRB- I-NP O
Dilantin NNP I-NP O
) -RRB- I-NP O
9.1 CD I-NP O
( -LRB- I-NP O
5.0-20.0) JJ I-NP O
mcg/ml NN I-NP O
UA-Color NN B-NP O
AMBER NNP I-NP O
( -LRB- O O
YELLOW) NN O O
UA-Turbidity NN B-NP O
TURBID NNP I-NP O
( -LRB- I-NP O
CLEAR NN I-NP O
) -RRB- O O
UA-Glucose JJ B-NP O
3+ CD I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Bili JJ B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Ketones NNP B-NP O
Trace NNP I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Specific JJ B-NP O
Gravity NNP I-NP O
1.027 CD I-NP O
( -LRB- I-NP O
1.001-1.035 CD I-NP O
) -RRB- O O
UA-Occult JJ B-NP O
Blood NN I-NP O
3+ IN B-PP O
( -LRB- B-NP O
NEG NN I-NP O
) -RRB- O O
UA-pH NNP B-NP O
6.0 CD I-NP O
( -LRB- I-NP O
5.0-9.0) CD O O
UA-Albumin NN B-NP O
3+ NN I-NP O
( -LRB- I-NP O
NEG NNP I-NP O
) -RRB- O O
UA-Urobilinogen NN B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-Nitrite JJ B-NP O
NEGATIVE JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-WBC NNP B-NP O
Screen NNP I-NP O
Trace NNP I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- O O
UA-SED-RBC JJ B-NP O
PACKED JJ I-NP O
(0-2 NN I-NP O
) -RRB- B-NP O
/hpf NN I-NP O
UA-SED-WBC NNP B-NP O
50-100 CD I-NP O
(0-2 NN I-NP O
) -RRB- B-NP O
/hpf NN I-NP O
UA-SED-Bacteria NNP B-NP O
Moderate NNP I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- B-NP O
/hpf NN I-NP O
Hyaline NNP B-NP O
Cast NNP I-NP O
0-2 JJ I-NP O
(0-5 CD I-NP O
) -RRB- B-NP O
/lpf NN I-NP O
Squamous NNP B-NP O
Cells NNP I-NP O
Many JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- B-NP O
/hpf NN I-NP O
Uric NNP B-NP O
Acid NNP I-NP O
Crystals NNP I-NP O
Many JJ I-NP O
( -LRB- I-NP O
NEG NN I-NP O
) -RRB- B-NP O
/hpf NN I-NP O
Microscopic NNP B-NP O
Sediment NNP I-NP O
Completed NNP I-NP O
EKG NNP B-NP O
: : O O
NSR NNP B-NP O
, , O O
borderline NN B-NP O
LVH CC O O
CXR NN B-NP O
: : O O
perihilar JJ B-NP O
opacities NNS I-NP O
, , O O
o/w RB B-ADVP O
clear JJ B-ADJP O
. . O O
Assessment NNP B-NP O
and CC I-NP O
Plan NNP I-NP O
: : O O
27 CD B-NP B-AGE
yo NNP I-NP O
h/o JJ I-NP O
insulin NN I-NP O
dependent JJ B-NP O
DM NNP I-NP O
, , O O
not RB B-VP O
medically RB I-VP O
followed VBN I-VP O
, , O O
p/w NN B-NP O
witnessed VBD B-VP O
seizure NN B-NP O
episode NN I-NP O
in IN B-PP O
context NN B-NP O
of IN B-PP O
severe JJ B-NP O
hypertension NN I-NP O
. . O O
1 LS O O
. . B-NP O
Neuro NNP I-NP O
- : O O
seizure NN B-VP O
episode NN B-NP O
/ NN I-NP O
unresponsiveness NN I-NP O
with IN B-PP O
non JJ B-NP O
localizing JJ I-NP O
neuro NN I-NP O
exam NN I-NP O
. . B-NP O
Concern NN I-NP O
for IN B-PP O
hypertensive JJ B-NP O
encephalopathy NN I-NP O
. . O O
Pt NNP B-NP O
had VBD B-VP O
LP VBN I-VP O
at IN B-PP O
outside JJ B-NP O
hospital NN I-NP O
which WDT B-NP O
did VBD B-VP O
not RB I-VP O
suggest VB I-VP O
meningitis NN B-NP O
. . O O
Other JJ B-NP O
possibilities NNS I-NP O
include VBP B-VP O
infarct NN B-NP O
, , I-NP O
encephalitis NN I-NP O
. . O O
Neurology NNP B-NP O
consulted VBD B-VP O
, , O O
with IN B-PP O
recommendations NNS B-NP O
for IN B-ADVP O
: : O O
n NN B-NP O
EEG NN I-NP O
n NN B-NP O
MRI NNP I-NP O
w/ CD I-NP O
susceptibility NN I-NP O
to TO B-VP O
evaluate VB I-VP O
for IN B-PP O
posterior JJ B-NP O
leukoencephalopathy NN I-NP O
, , O O
MRA NNP B-NP O
head/neck NN I-NP O
, , O O
MRV NNP B-NP O
brain NN I-NP O
n NN B-NP O
Dilantin NNP I-NP O
( -LRB- I-NP O
continued VBD B-VP O
from IN B-PP O
OSH) NNP B-NP O
n RB B-ADVP O
Check VB B-VP O
tox DT B-NP O
screen NN I-NP O
, , I-NP O
ammonia NN I-NP O
. . O O
Mother NN B-NP O
has VBZ B-VP O
brought VBN I-VP O
in IN B-PP O
some DT B-NP O
unknown JJ I-NP O
pills NNS I-NP O
which WDT B-NP O
we PRP B-NP O
will MD B-VP O
try VB I-VP O
to TO I-VP O
identify VB I-VP O
. . O O
2. DT B-NP O
ID NNP I-NP O
- : O O
increased VBD B-VP O
WBC NNP B-NP O
, , O O
low JJ B-NP O
grade NN I-NP O
temp NN I-NP O
s/p VBD B-VP O
LP. NNP B-NP O
No DT B-NP O
bacterial JJ I-NP O
source NN I-NP O
for IN B-PP O
now RB B-NP O
, , O O
but CC O O
CXR NNP B-NP O
with IN B-PP O
opacities NNS B-NP O
suspicious JJ B-ADJP O
for IN B-PP O
pneumonia NN B-NP O
. . O O
Will MD B-VP O
start VB I-VP O
Vancomycin NNP B-NP O
and CC O O
cefepime JJ B-ADVP O
empirically RB I-ADVP O
, , O O
and CC O O
narrow JJ B-ADJP O
per IN B-PP O
culture NN B-NP O
results NNS I-NP O
. . O O
Concern NN B-VP O
for IN B-PP O
encephalitis NN B-NP O
, , O O
as IN B-SBAR O
HSV NNP B-NP O
can MD B-VP O
present VB I-VP O
w/ JJ B-NP O
HTN NNP I-NP O
and CC I-NP O
seizures NNS I-NP O
. . O O
Will NNP B-NP O
ask VBP B-VP O
Linden NNP B-NP B-HOSPITAL
Health NNP I-NP I-HOSPITAL
to TO B-VP O
add VB I-VP O
HSV NNP B-NP O
PCR NNP I-NP O
to TO B-PP O
CSF NNP B-NP O
taken VBN B-VP O
from IN B-PP O
LP NNP B-NP O
prior RB B-ADVP O
to TO B-VP O
transfer VB I-VP O
. . B-NP O
Start NNP I-NP O
Acyclovir NNP I-NP O
empirically RB B-ADVP O
in IN B-PP O
interim NN B-NP O
. . O O
3. CD B-NP O
Resp NN I-NP O
- : O O
s/p JJ B-NP O
multiple JJ I-NP O
attempted VBN I-NP O
intubations NNS I-NP O
at IN B-PP O
OSH NNP B-NP O
, , O O
currently RB B-ADVP O
breathing VBG B-VP O
adequately RB B-ADVP O
on IN B-PP O
RA NNP B-NP O
, , O O
with IN B-PP O
audible JJ B-NP O
obstructive JJ I-NP O
physiology NN I-NP O
. . O O
Given VBN B-VP O
need NN B-NP O
for IN B-PP O
MRI NNP B-NP O
, , O O
may MD B-VP O
have VB I-VP O
to TO I-VP O
sedate VB I-VP O
and CC I-VP O
intubate VB I-VP O
. . O O
Will MD B-VP O
call VB I-VP O
anesthesia DT B-NP O
. . I-NP O
Continue NNP I-NP O
intubated VBD B-VP O
until IN B-PP O
MS NNP B-NP O
more JJR I-NP O
alert JJ I-NP O
, , O O
for IN B-PP O
airway NN B-NP O
protection NN I-NP O
. . O O
Will MD B-VP O
start VB I-VP O
ARDSnet NN B-NP O
for IN B-PP O
criteria NNS B-NP O
meeting VBG B-VP O
low JJ B-NP O
PaO2/FIO2 NNP I-NP O
ratio NN I-NP O
and CC O O
bilateral JJ B-NP O
pulmonary JJ I-NP O
infiltrates NNS I-NP O
. . O O
4 CD B-LST O
. . O O
CV- -RRB- B-VP O
severe JJ B-NP O
hypertension NN I-NP O
w/ IN B-PP O
evidence NN B-NP O
of IN B-PP O
potential JJ B-NP O
end NN I-NP O
organ NN I-NP O
damage NN I-NP O
(kidney/brain/cardiac NN I-NP O
) -RRB- B-NP O
. . O O
Will MD O O
control NN B-NP O
BP NNP B-NP O
w/ , O O
Nipride NNP B-NP O
drip VBD B-VP O
, , O O
with IN B-PP O
addition NN B-NP O
of IN B-PP O
labetalol NN B-NP O
for IN B-PP O
HR NN B-NP O
control NN I-NP O
. . O O
Target NNP B-NP O
goal NN I-NP O
25 CD I-NP O
% NN I-NP O
decrease NN I-NP O
to TO B-PP O
SPB~160 NNP B-NP O
today NN I-NP O
, , O O
and CC O O
SBP NNP B-NP O
120 CD I-NP O
the DT B-NP O
following VBG I-NP O
day NN I-NP O
. . O O
Check VB B-VP O
CK/TPNs NNP B-NP O
. . I-NP O
Continue NNP I-NP O
IVF NNP I-NP O
for IN B-PP O
potential JJ B-NP O
rhabdo NN I-NP O
. . O O
5 CD B-NP O
. . O O
Renal NNP O O
- : O O
Renal JJ B-NP O
failure NN I-NP O
w/ VBD B-VP O
Cr NNP B-NP O
2.6 CD I-NP O
, , I-NP O
unclear JJ I-NP O
baseline NN I-NP O
. . O O
Suspect VB B-VP O
acute JJ B-ADJP O
on IN B-PP O
chronic JJ B-NP O
component NN I-NP O
given VBN B-VP O
DM NNP B-NP O
w/ IN B-PP O
poor JJ B-NP O
follow-up NN I-NP O
. . O O
Will MD B-VP O
check VB I-VP O
Urine NNP B-NP O
sediment NN I-NP O
, , O O
lytes NNS B-NP O
to TO B-VP O
evaluate VB I-VP O
. . O O
Reading NNP O O
by IN B-SBAR O
me PRP B-NP O
is VBZ B-VP O
+hyaline/waxy JJ B-NP O
casts NNS I-NP O
but CC O O
no DT B-NP O
WBC NNP I-NP O
or CC I-NP O
RBC NNP I-NP O
casts VBZ B-VP O
. . B-NP O
Kidney NNP I-NP O
U/S NNP I-NP O
pending VBG B-VP O
, , O O
also RB B-ADVP O
with IN B-PP O
Doppler NNP B-NP O
to TO B-VP O
evaluate VB I-VP O
for IN B-PP O
RAS. NNP B-NP O
Also RB B-ADVP O
check VB B-VP O
urine NN B-NP O
renin/aldo NN I-NP O
and CC O O
24hr JJ B-NP O
metanephrine NN I-NP O
for IN B-PP O
pheochromocytoma NN B-NP O
, , O O
serum NN B-NP O
metanephrine NN I-NP O
, , O O
and CC O O
24hr JJ B-NP O
protein NN I-NP O
for IN B-PP O
nephritic JJ B-NP O
syndrome NN I-NP O
in IN B-PP O
presence NN B-NP O
of IN B-PP O
HTN NNP B-NP O
and CC I-NP O
hematuria NN I-NP O
. . O O
6 CD B-NP O
. . O O
Endo NNP O O
- : O O
tight JJ B-NP O
glucose NN I-NP O
control NN I-NP O
; : O O
CZI NNP B-NP O
drip VBD B-VP O
for IN B-PP O
DM. NNP B-NP O
Has VBZ B-VP O
gap NN B-NP O
but CC O O
No DT B-NP O
ketones NNS I-NP O
at IN B-PP O
OSH NNP B-NP O
; : O O
did VBD B-VP O
not RB I-VP O
arrive VB I-VP O
in IN B-PP O
DKA. NNP B-NP O
Will MD B-VP O
need VB I-VP O
reg JJ B-NP O
insulin NN I-NP O
after IN B-PP O
drip VBG B-VP O
DC NNP B-NP O
'd NNP I-NP O
in IN B-PP O
future NN B-NP O
. . O O
7. DT B-NP O
Access NNP I-NP O
- : O O
PIV NN B-NP O
8. DT B-NP O
Prophylaxis NNP I-NP O
- : O O
nexium JJ B-NP O
, , O O
heparin IN B-PP O
SQ NNP B-NP O
, , O O
peridex NN B-NP O
, , O O
HOB NNP B-NP O
30 CD I-NP O
. . O O
Infant NNP B-NP B-DOCTOR
Ledford NNP I-NP I-DOCTOR
# # B-NP O
12182 CD I-NP B-PHONE
