Record NNP B-NP O
date NN I-NP O
: : O O
2068-01-04 CD O B-DATE
Patient NNP B-NP O
Name NNP I-NP O
: : O O
JOINER,CAITLIN NNP B-NP B-PATIENT
[ NNP I-NP O
MRN NNP I-NP O
: : O O
3041038 CD B-NP B-MEDICALRECORD
MARY NN I-NP B-HOSPITAL
] . O O
Date NNP B-NP O
of IN B-PP O
Visit NNP B-NP O
: : O O
1/04/2068 CD O B-DATE
Here RB B-ADVP O
for IN B-PP O
Urgent NNP B-NP O
Visit NNP I-NP O
. . O O
She PRP B-NP O
felt VBD B-VP O
well RB B-ADJP O
until IN B-PP O
yesteday NNP B-NP O
evening NN I-NP O
. . O O
Noted VBD B-VP O
that IN B-SBAR O
her PRP B-NP O
R NN B-NP O
ear NN I-NP O
was VBD B-VP O
popping VBG I-VP O
and CC O O
felt VBD B-VP O
congested VBN I-VP O
. . O O
No DT B-NP O
pain NN I-NP O
or CC I-NP O
fever NN I-NP O
. . O O
Went VBD B-VP O
to TO I-VP O
bed VB I-VP O
feeling VBG I-VP O
relatively RB B-ADVP O
well RB I-ADVP O
but CC O O
awoke VBD B-VP O
at IN B-PP O
about IN B-NP O
3 CD I-NP O
AM VBP I-NP O
dizzy JJ I-NP O
and CC I-NP O
nauseated JJ I-NP O
. . O O
Dizziness NNP B-NP O
passed VBD B-VP O
but CC O O
she PRP B-NP O
remained VBD B-VP O
nauseated JJ B-ADJP O
for IN B-PP O
about IN B-PP O
an DT B-NP O
hour NN I-NP O
and CC O O
vomited VBD B-VP O
white JJ B-NP O
spittle NN I-NP O
. . O O
She PRP B-NP O
awoke VBD B-VP O
this DT B-NP O
am VBP B-VP O
still RB B-ADVP O
queezy JJ B-ADJP O
with IN B-PP O
small JJ B-NP O
amounts NNS I-NP O
of IN B-PP O
vomiting NN B-NP O
spittle NN I-NP O
. . O O
Her PRP$ B-VP O
temp NN I-VP O
this DT B-NP O
am RB B-ADVP O
was VBD B-VP O
98.2 CD B-NP O
. . O O
Went VBD B-VP O
back RB B-ADVP O
to TO B-PP O
bed NN B-NP O
about IN B-PP O
11 CD B-NP O
am VBP I-NP O
and CC O O
awoke VBD B-VP O
at IN B-PP O
one CD B-NP O
o'clock RB I-NP O
still RB I-NP O
nauseous JJ I-NP O
. . O O
No DT B-NP O
cough NN I-NP O
, , O O
dysuria NNS B-NP O
. . O O
Foot NN B-NP O
care NN I-NP O
is VBZ B-VP O
good JJ B-ADJP O
with IN B-PP O
no DT B-NP O
ulcers NNS I-NP O
. . O O
Efforts NNS B-VP O
to TO I-VP O
control VB I-VP O
nausea NN B-NP O
in IN B-PP O
past JJ B-NP O
with IN B-PP O
compazine NN B-NP O
have VBP B-VP O
not RB I-VP O
been VBN I-VP O
successful JJ B-ADJP O
. . O O
She PRP B-NP O
took VBD B-VP O
meds NNS B-NP O
including VBG B-VP O
15u CD B-NP O
NPH. NNP I-NP O
Her PRP$ I-NP O
BS NNP I-NP O
this DT I-NP O
am VBP I-NP O
was VBD B-VP O
170n IN B-PP O
which WDT B-NP O
is VBZ B-VP O
high JJ B-ADJP O
for IN B-PP O
her PRP B-NP O
. . O O
She PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
unable JJ B-ADJP O
to TO B-VP O
eat VB I-VP O
anything NN B-NP O
despite IN B-PP O
trying VBG B-VP O
to TO I-VP O
eat VB I-VP O
saltines NNS B-NP O
. . O O
Patient NNP B-NP O
started VBD B-VP O
to TO I-VP O
vomit VB I-VP O
at IN B-PP O
the DT B-NP O
end NN I-NP O
of IN B-PP O
exam NN B-NP O
. . O O
AODM NNP B-NP O
Type NNP I-NP O
1- NNP I-NP O
First NNP I-NP O
dx'ed VBD B-VP O
in IN B-PP O
12/25 CD B-NP B-DATE
when WRB B-ADVP O
she PRP B-NP O
presented VBD B-VP O
with IN B-PP O
R NN B-NP O
foot NN I-NP O
foot NN I-NP O
osteo NN I-NP O
in IN B-PP O
mild JJ B-NP O
DKA. NNP I-NP O
She PRP B-NP O
ended VBD B-VP O
up RP B-PRT O
with IN B-PP O
a DT B-NP O
TMA NNP I-NP O
and CC O O
is VBZ B-VP O
followed VBN I-VP O
now RB B-ADVP O
by IN B-PP O
Dr. NNP B-NP O
Pete NNP I-NP B-DOCTOR
Quintanar NNP I-NP I-DOCTOR
and CC B-PP O
by IN B-PP O
Dr. NNP B-NP O
Infant NNP I-NP B-DOCTOR
Church NNP I-NP I-DOCTOR
of IN B-PP O
surgery NN B-NP O
. . O O
Last JJ B-ADJP O
HgbA1c NNP B-NP O
6.4 CD I-NP O
11/28/67 CD I-NP B-DATE
. . O O
ROS NNP B-NP O
Denies NNS I-NP O
C NNP I-NP O
, , I-NP O
SOB NNP I-NP O
, , O O
No DT B-NP O
GU NNP I-NP O
or CC I-NP O
GI NNP I-NP O
sx . O O
== NN B-NP O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
HealthMaintenance NNP B-NP O
== , O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
< NN B-NP O
< IN B-PP O
New NNP B-NP O
Item NNP I-NP O
> NNP I-NP O
> VBD B-VP O
09/14/2066 CD O B-DATE
Breast NN B-NP O
Exam NNP I-NP O
08/31/2067 CD I-NP B-DATE
nl NN I-NP O
Done . O O
Cholesterol NNP B-NP O
08/21/2067 CD I-NP B-DATE
140 CD I-NP O
DESIRABLE JJ I-NP O
: : O O
<200 CD O O
HBA1C NNP B-NP O
11/28/2067 CD I-NP B-DATE
6.40 CD O O
Mammogram NNP B-NP O
08/31/2067 CD I-NP B-DATE
Done/scheduled VBN O O
Microalbumin NNP B-NP O
05/03/2066 CD I-NP B-DATE
6 CD O O
Ophthal NNP B-NP O
Exam NNP I-NP O
08/31/2067 CC I-NP B-DATE
Done NNP I-NP O
elsewhere RB B-ADVP O
Dr. NNP B-NP O
J NNP I-NP B-DOCTOR
Gaines NNP I-NP I-DOCTOR
Pap NNP B-NP O
Smear NNP I-NP O
09/14/2066 CD I-NP B-DATE
Done . O O
Podiatry NNP B-NP O
exam NN I-NP O
08/09/2066 CD B-NP B-DATE
Dr. NNP I-NP O
Vazquez NNP I-NP B-DOCTOR
will MD B-VP O
see VB I-VP O
q NN B-NP O
3 CD I-NP O
months NNS I-NP O
Rectal NNP B-NP O
exam NN I-NP O
09/14/2066 CD B-NP B-DATE
neg NN I-NP O
Sigmoidoscopy NNP B-NP O
08/31/2067 CD I-NP B-DATE
Discussed VBN B-VP O
with IN B-PP O
patient NN B-NP O
. . O O
She PRP B-NP O
refuses VBZ B-VP O
. . O O
Smoking VBG B-NP O
status NN I-NP O
09/14/2066 IN B-PP B-DATE
Never RB B-NP O
a DT I-NP O
smoker NN I-NP O
Stool NNP B-NP O
Guaiac NNP I-NP O
09/14/2066 CD I-NP B-DATE
Done NNP I-NP O
- : O O
negative JJ O O
Tetanus NNP B-NP O
02/08/2066 CD I-NP B-DATE
Will MD B-VP O
do VB I-VP O
at IN B-PP O
next JJ B-NP O
visit NN I-NP O
UA-Protein NNP B-NP O
06/08/2067 CD I-NP B-DATE
NEGATIVE CD O O
Vision NNP B-NP O
Exam NNP I-NP O
09/13/2066 VBD B-VP B-DATE
no DT B-NP O
change NN I-NP O
Dr. NNP I-NP O
Gaines NNP I-NP B-DOCTOR
, , O O
will MD B-VP O
see VB I-VP O
in IN B-PP O
one CD B-NP O
year NN I-NP O
== NN B-NP O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM B-NP O
Problems NNPS I-NP O
== NNP I-NP O
= SYM B-VP O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
Foot NNP B-NP O
ulcer NN I-NP O
Diabetes NNS B-NP O
== NN B-NP O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
Allergies NNP B-NP O
== , O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
NKDA NNP B-NP O
== NN B-NP O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM B-NP O
Medications NNPS I-NP O
== NNP I-NP O
= SYM B-VP O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
= SYM O O
REGLAN NNP B-NP O
( -LRB- I-NP O
METOCLOPRAMIDE NNP I-NP O
HCL NNP I-NP O
) -RRB- I-NP O
10MG . I-NP O
PO NNP I-NP O
BID NNP I-NP O
INSULIN NNP B-NP O
NPH NNP I-NP O
HUMAN NNP I-NP O
15UNITS VBZ B-VP O
SC NNP B-NP O
QAM NNP I-NP O
ASA NNP B-NP O
(ACETYLSALICYLIC NN I-NP O
ACID NNP I-NP O
) -RRB- I-NP O
325MG JJ I-NP O
1 CD I-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QD . O O
CAPTOPRIL NNP B-NP O
50MG VBD B-VP O
PO NNP B-NP O
BID NNP I-NP O
* JJ B-NP O
ACTOS NNP I-NP O
45mg CD I-NP O
PO NNP I-NP O
QD NNP I-NP O
LIPITOR NNP B-NP O
( -LRB- I-NP O
ATORVASTATIN NNP I-NP O
) -RRB- I-NP O
10MG . B-VP O
1 CD B-NP O
Tablet( NN I-NP O
s VBZ B-VP O
) -RRB- B-NP O
PO NN I-NP O
QHS . O O
* JJ B-NP O
B/D NNP I-NP O
INSULIN NNP I-NP O
SYRINGES NNP I-NP O
U100 IN B-PP O
29G JJ B-NP O
0.5 CD I-NP O
ML NNP I-NP O
1SYRINGE NNP I-NP O
BID NNP I-NP O
PE NN B-NP O
: : O O
WD/WN NNP B-NP O
in IN B-PP O
NAD NNP B-NP O
HEENT NNP B-NP O
- : O O
nl NN B-NP O
though IN B-PP O
L NNP B-NP O
ear NN I-NP O
partially RB B-VP O
blocked VBN I-VP O
by IN B-PP O
cerumen NNS B-NP O
Nodes NNP B-NP O
- : O O
w/o NN B-NP O
Carotids NNP B-NP O
- : O O
no DT B-NP O
bruits NNS I-NP O
Lungs NNP B-NP O
- : O O
clear JJ B-ADJP O
to TO B-VP O
P&A VB I-VP O
Cor NNP B-NP O
- : O O
RRR NN B-VP O
w/o NN B-NP O
g NN I-NP O
or CC O O
m NN B-NP O
Abd NNP B-NP O
- : O O
benign JJ O O
Ext JJ O O
- : O O
no DT B-NP O
edema NN I-NP O
U/A NNP B-NP O
unable JJ I-NP O
to TO B-VP O
give VB I-VP O
a DT B-NP O
sample NN I-NP O
FS NNS B-NP O
bs NNS I-NP O
- : O O
167 CD B-NP O
nmg NN I-NP O
% NN I-NP O
Due JJ B-ADVP O
to TO B-PP O
inability NN B-NP O
to TO B-VP O
keep VB I-VP O
any DT B-NP O
fluids NNS I-NP O
and CC I-NP O
food NN I-NP O
down RB B-ADVP O
and CC O O
the DT B-NP O
fact NN I-NP O
that IN B-SBAR O
she PRP B-NP O
has VBZ B-VP O
already RB I-VP O
taken VBN I-VP O
her PRP B-NP O
Isulin IN B-SBAR O
we PRP B-NP O
will MD B-VP O
admit VB I-VP O
for IN B-PP O
antiemetics NNS B-NP O
and CC O O
IV NNP B-NP O
hydration NN I-NP O
. . O O
I PRP B-NP O
have VBP B-VP O
informed VBN I-VP O
Dr. NNP B-NP O
Quintanar NNP I-NP B-DOCTOR
. . O O
Yan NNP B-NP B-DOCTOR
D. NNP I-NP I-DOCTOR
Ball NNP I-NP I-DOCTOR
, , O O
MD . O O
