Record NNP B-NP O
date NN I-NP O
: : O O
2092-05-16 CD O B-DATE
Correction NNP B-NP B-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
Physician NNP I-NP O
Group NNP I-NP O
925 CD B-NP B-STREET
Tolles NNP I-NP I-STREET
Street NNP I-NP I-STREET
HOOPER NNP I-NP I-PATIENT
, , O I-PATIENT
PABLO NNP B-NP I-PATIENT
Labelle NNP B-NP B-CITY
, , O O
MI NNP B-NP B-STATE
97848 CD I-NP B-ZIP
90338035 CD O B-MEDICALRECORD
( -LRB- B-NP I-PHONE
055 CD I-NP I-PHONE
) -RRB- I-NP I-PHONE
025-9878 CD I-NP I-PHONE
05/16/92 CD O B-DATE
(908 CD B-NP I-PHONE
) -RRB- I-NP I-PHONE
649-3317 CD O I-PHONE
CHIEF JJ B-NP O
COMPLAINT NNP I-NP O
: : O O
Follow-up NN B-VP O
laboratory NN B-NP O
testing NN I-NP O
. . O O
HISTORY NN B-NP O
OF IN B-PP O
PRESENT JJ B-NP O
ILLNESS NNS I-NP O
: : O O
The DT B-NP O
patient NN I-NP O
is VBZ B-VP O
a DT B-NP O
56 CD I-NP B-AGE
-year-old JJ I-NP O
white JJ I-NP O
man NN B-NP O
who WP B-NP O
I PRP B-NP O
have VBP B-VP O
not RB I-VP O
seen VBN I-VP O
since IN B-PP O
November NNP B-NP B-DATE
of IN B-PP I-DATE
2088 CD B-NP I-DATE
. . O O
Approximately RB O O
four CD B-NP O
weeks NNS I-NP O
ago RB B-ADVP O
, , O O
he PRP B-NP O
started VBD B-VP O
noting VBG I-VP O
visual JJ B-NP O
changes NNS I-NP O
. . O O
He PRP B-NP O
saw VBD B-VP O
colored JJ O O
spots NNS B-NP O
floating VBG B-VP O
in IN B-PP O
his PRP$ B-NP O
visual JJ I-NP O
field NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
noting VBG I-VP O
some DT O O
decreased VBN B-NP O
depth NN I-NP O
perception NN I-NP O
and CC O O
visual JJ B-NP O
acuity NN I-NP O
. . O O
At IN B-PP O
the DT B-NP O
same JJ I-NP O
time NN I-NP O
, , O O
he PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
getting VBG I-VP O
throbbing DT B-NP O
unilateral JJ I-NP O
headaches NNS I-NP O
, , O O
which WDT B-NP O
he PRP B-NP O
believes VBZ B-VP O
were VBD B-NP O
migraines NNS I-NP O
. . O O
He PRP B-NP O
saw VBD B-VP O
an DT B-NP O
ophthalmologist NN I-NP O
at IN B-PP O
Mediquik NNP B-NP B-HOSPITAL
who WP B-NP O
told VBD B-VP O
him PRP B-NP O
that IN B-SBAR O
his PRP$ B-NP O
eye NN I-NP O
exam NN I-NP O
was VBD B-VP O
within IN B-PP O
normal JJ B-NP O
limits NNS I-NP O
. . O O
He PRP B-NP O
was VBD B-VP O
then RB I-VP O
referred VBN I-VP O
to TO B-PP O
Dr. NNP B-NP O
Gill NNP I-NP B-DOCTOR
for IN B-PP O
neurologic JJ B-NP O
evaluation NN I-NP O
. . O O
Dr. NNP B-NP O
Gill NNP I-NP B-DOCTOR
did VBD B-VP O
not RB I-VP O
note VB I-VP O
any DT B-NP O
significant JJ I-NP O
neurologic NN I-NP O
deficits NNS I-NP O
. . O O
However RB B-ADVP O
, , O O
during IN B-PP O
his PRP$ B-NP O
workup NN I-NP O
, , O O
he PRP B-NP O
did VBD B-VP O
check VB I-VP O
a DT B-NP O
hemoglobin NN I-NP O
A1c NNP I-NP O
, , O O
which WDT O O
came VBD B-VP O
back RB B-ADVP O
at IN B-PP O
10.2 CD B-NP O
. . O O
Of IN B-PP O
note NN B-NP O
, , O O
the DT B-NP O
last JJ I-NP O
time NN I-NP O
I PRP B-NP O
saw VBD B-VP O
the DT B-NP O
patient NN I-NP O
, , O O
I PRP B-NP O
had VBD B-VP O
sent VBN I-VP O
him PRP B-NP O
a DT B-NP O
letter NN I-NP O
stating VBG B-VP O
that IN B-PP O
his PRP$ B-NP O
glucose NN I-NP O
was VBD B-VP O
slightly RB O O
elevated JJ B-NP O
and CC O O
asking VBG B-VP O
him PRP B-NP O
to TO B-VP O
return VB I-VP O
for IN B-PP O
a DT B-NP O
fasting JJ I-NP O
glucose NN I-NP O
. . O O
He PRP O O
never RB B-ADVP O
returned VBD B-VP O
for IN B-PP O
that DT B-NP O
testing NN I-NP O
. . O O
PAST NN B-NP O
MEDICAL NNP I-NP O
HISTORY NNP I-NP O
: : O O
Hypertension NNP B-NP O
, , I-NP O
hypercholesterolemia NN I-NP O
, , O O
obesity NN B-NP O
, , O O
and CC O O
gout NN B-NP O
. . O O
MEDICATIONS NNS B-NP O
: : O O
HCTZ NN B-NP O
50 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d. '' O O
, , O O
Atenolol NNP B-NP O
50 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
b.i.d. '' O O
, , O O
allopurinol DT B-NP O
300 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d '' O O
. . O O
ALLERGIES NNP B-NP O
: : O O
No DT B-NP O
known VBN I-NP O
drug NN I-NP O
allergies NNS I-NP O
. . O O
FAMILY NNP B-NP O
HISTORY NNP I-NP O
: : O O
Negative JJ B-ADJP O
for IN B-PP O
diabetes NN B-NP O
but CC I-NP O
positive JJ I-NP O
for IN B-PP O
kidney NN B-NP O
failure NN B-NP O
. . O O
This DT B-NP O
is VBZ B-VP O
thought VBN I-VP O
to TO I-VP O
be VB I-VP O
due JJ B-ADJP O
to TO B-PP O
glomerulonephritis NN B-NP O
. . O O
SOCIAL JJ B-NP O
HISTORY NN I-NP O
: : O O
He PRP B-NP O
is VBZ B-VP O
a DT B-NP O
Graphic NNP I-NP B-PROFESSION
Arts NNP I-NP I-PROFESSION
Technician NNP I-NP I-PROFESSION
in IN B-PP O
Oconto NNP B-NP B-CITY
. . O O
He PRP B-NP O
is VBZ B-LST O
currently RB B-ADVP O
on IN B-PP O
a DT B-NP O
leave NN I-NP O
of IN B-PP O
absence NN B-NP O
from IN B-PP O
work NN B-NP O
. . O O
He PRP B-NP O
is VBZ B-VP O
a DT B-NP O
nonsmoker NN I-NP O
. . O O
REVIEW NN B-NP O
OF IN B-PP O
SYSTEMS NNP B-NP O
: : O O
He PRP B-NP O
believes VBZ B-VP O
that IN B-SBAR O
he PRP B-NP O
has VBZ B-VP O
lost VBN I-VP O
some DT B-NP O
weight NN I-NP O
over IN B-PP O
the DT B-NP O
past JJ I-NP O
four CD I-NP O
weeks NNS I-NP O
but CC O O
cannot MD B-VP O
quantify VB I-VP O
the DT B-NP O
amount NN I-NP O
. . O O
He PRP B-NP O
has VBZ B-VP O
been VBN I-VP O
noting VBG B-VP O
anxiety NN B-NP O
symptoms NNS I-NP O
, , O O
increased VBD B-VP O
urinary JJ B-NP O
frequency NN I-NP O
, , O O
and CC O O
nocturia NN B-NP O
. . O O
Otherwise RB B-ADVP O
, , O O
constitutional JJ B-NP O
, , I-NP O
HEENT NNP I-NP O
, , I-NP O
cardiac NN I-NP O
, , O O
respiratory NN B-NP O
, , O O
GI NNP B-NP O
, , O O
GU NNP B-NP O
, , O O
musculoskeletal NN B-NP O
, , O O
neurologic NN B-NP O
, , O O
and CC O O
dermatologic NN B-NP O
are VBP B-VP O
negative JJ B-ADJP O
. . O O
PHYSICAL NNP B-NP O
EXAMINATION NN I-NP O
: : O O
In IN B-PP O
general JJ B-NP O
, , O O
he PRP B-NP O
is VBZ B-VP O
a DT B-NP O
pleasant JJ I-NP O
obese JJ I-NP O
white JJ I-NP O
man NN B-NP O
in IN B-PP O
no DT B-NP O
acute JJ I-NP O
distress NN I-NP O
. . O O
Vitals NNS B-NP O
: : O O
Blood NN B-NP O
pressure NN I-NP O
134/90 CD I-NP O
, , O O
pulse NN B-NP O
66 CD B-NP O
and CC I-NP O
regular JJ I-NP O
, , I-NP O
and CC I-NP O
weight NN I-NP O
249 IN B-PP O
pounds NNS B-NP O
. . B-NP O
HEENT NN I-NP O
: : O O
PERRL NN B-NP O
, , O O
EOMI NNP B-NP O
, , O O
anicteric JJ B-NP O
sclerae NNS I-NP O
. . O O
Clear NN B-VP O
oropharynx NN B-NP O
with IN B-PP O
dry JJ B-NP O
mucous JJ I-NP O
membranes NNS I-NP O
. . O O
Neck NNP B-NP O
is VBZ B-VP O
supple NN B-NP O
with IN B-PP O
no DT B-NP O
lymphadenopathy NN I-NP O
, , O O
no DT B-NP O
thyromegaly NN I-NP O
. . O O
Chest NNP B-NP O
: : O O
CTA&P NNP B-NP O
bilaterally RB B-ADVP O
. . B-VP O
Heart VB I-VP O
: : O O
RRR NNP B-NP O
, , O O
no DT B-NP O
MRG. NNP I-NP O
Abdomen NNP I-NP O
: : O O
Obese NNP B-NP O
, , I-NP O
soft JJ I-NP O
, , O O
NT/ND NNP B-NP O
, , O O
NABS NNP B-NP O
, , O O
no DT B-NP O
HSM. NNP I-NP O
Extremities NNP I-NP O
: : O O
No DT B-NP O
CCE. NNP I-NP O
Neuro NNP I-NP O
: : O O
A&O NNP B-NP O
x NN I-NP O
3 CD B-NP O
, , O O
2+ CD O O
DTRs NNS B-NP O
bilaterally RB B-ADVP O
. . O O
LABORATORY NNP B-NP O
DATA NNP I-NP O
: : O O
EKG NNP B-NP O
shows VBZ B-VP O
normal JJ B-ADJP O
sinus IN B-PP O
rhythm NN B-NP O
at IN B-PP O
73 CD B-NP O
beats NNS I-NP O
per IN B-PP O
minute NN B-NP O
, , O O
normal JJ B-NP O
axis NN I-NP O
and CC I-NP O
intervals NNS I-NP O
, , O O
no DT B-NP O
ST-T-wave JJ I-NP O
changes NNS I-NP O
. . O O
ASSESSMENT NNP B-NP O
AND CC I-NP O
PLAN NNP I-NP O
: : O O
1 LS O O
. . B-NP O
Diabetes NNP I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
was VBD B-VP O
advised VBN I-VP O
that IN B-PP O
his PRP$ B-NP O
laboratory NN I-NP O
testing NN B-NP O
and CC I-NP O
symptoms NNS I-NP O
are VBP B-VP O
all DT O O
consistent JJ B-ADJP O
with IN B-PP O
adult-onset NN B-NP O
diabetes NNS B-NP O
. . B-VP O
Given VBN I-VP O
the DT B-NP O
severity NN I-NP O
of IN B-PP O
his PRP$ B-NP O
symptoms NNS I-NP O
, , O O
I PRP B-NP O
have VBP B-VP O
elected VBN I-VP O
to TO I-VP O
start VB B-VP O
him PRP B-NP O
on IN B-PP O
metformin NN B-NP O
500 CD I-NP O
mg NN I-NP O
p.o NN I-NP O
. . O O
q.d VBD B-VP O
. . I-VP O
Use NNP B-NP O
and CC I-NP O
side NN I-NP O
effects NNS I-NP O
were VBD B-VP O
reviewed VBN I-VP O
. . O O
He PRP B-NP O
will MD B-VP O
have VB I-VP O
Chem-7 NNP B-NP O
, , O O
urinary JJ B-NP O
microalbumin NN I-NP O
and CC O O
fasting VBG B-VP O
lipid JJ B-NP O
profile NN I-NP O
checked VBN I-NP O
today NN B-NP O
. . O O
Unfortunately RB B-ADVP O
, , O O
he PRP B-NP O
was VBD B-VP O
not RB O O
actually RB B-ADVP O
fasting VBG B-VP O
. . O O
He PRP B-NP O
will MD B-VP O
also RB I-VP O
be VB I-VP O
referred VBN I-VP O
to TO B-PP O
Gretchen NNP B-NP B-DOCTOR
Drew NNP I-NP I-DOCTOR
and CC O O
Bertha NNP B-NP B-DOCTOR
Ely NNP I-NP I-DOCTOR
for IN B-PP O
further JJ B-NP O
diabetic NN I-NP O
and CC O O
nutritional JJ B-NP O
education NN I-NP O
. . O O
He PRP B-NP O
will MD B-VP O
be VB I-VP O
started VBN I-VP O
on IN B-PP O
lisinopril NN B-NP O
instead RB B-ADVP O
of IN B-PP O
HCTZ. NNP B-NP O
He PRP B-NP O
is VBZ B-VP O
asked VBN I-VP O
to TO B-VP O
return VB I-VP O
in IN B-PP O
six CD B-NP O
weeks NNS I-NP O
for IN B-PP O
follow VBP B-VP O
up IN B-PRT O
of IN B-PP O
his PRP$ B-NP O
blood NN I-NP O
pressure NN I-NP O
. . O O
He PRP O O
was VBD B-VP O
advised VBN I-VP O
that IN B-PP O
his PRP$ B-NP O
visual JJ I-NP O
changes NNS I-NP O
are VBP B-VP O
likely JJ B-ADJP O
due RB I-ADJP O
to TO B-PP O
lens NN B-NP O
swelling VBG B-VP O
due JJ B-ADJP O
to TO B-PP O
the DT B-NP O
uncontrolled JJ I-NP O
diabetes NN I-NP O
. . O O
I PRP B-NP O
assume VBP B-VP O
that IN B-SBAR O
this DT B-NP O
will MD B-VP O
resolve VB I-VP O
as IN B-PP O
the DT B-NP O
blood NN I-NP O
sugars NNS I-NP O
come VBP B-VP O
under IN B-PP O
better JJR B-NP O
control NN I-NP O
. . O O
He PRP O O
was VBD B-VP O
given VBN I-VP O
a DT B-NP O
written JJ I-NP O
note NN I-NP O
regarding VBG I-NP O
leave NN I-NP O
of IN B-PP O
absence NN B-NP O
from IN B-PP O
his PRP$ B-NP O
job NN I-NP O
until IN B-PP O
his PRP$ B-NP O
symptoms NNS I-NP O
clear JJ B-ADJP O
. . O O
2. DT B-NP O
Migraines NNP I-NP O
. . O O
The DT B-NP O
patient NN I-NP O
does VBZ B-VP O
sound VB I-VP O
as IN B-ADVP O
if IN B-SBAR O
he PRP B-NP O
is VBZ B-VP O
also RB I-VP O
having VBG I-VP O
migraines NNS B-NP O
. . O O
We PRP B-NP O
will MD B-VP O
address VB I-VP O
this DT B-NP O
at IN B-PP O
future JJ B-NP O
visits NNS I-NP O
. . O O
Patti NNP B-NP B-DOCTOR
O. NNP I-NP I-DOCTOR
Bush NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
eScription NN B-NP O
document NN I-NP O
: : O O
3-6062838 CD B-NP B-IDNUM
EMSSten NNP I-NP O
Tel NNP I-NP O
DD NNP B-NP O
: : O O
05/16/92 CD O B-DATE
DT NNP B-NP O
: : O O
05/17/92 CD O B-DATE
DV NNP B-NP O
: : O O
05/16/92 CD O B-DATE
