Record NNP B-NP O
date NN I-NP O
: : O O
2096-09-17 CD O B-DATE
Medicine NNP B-NP O
Admission NNP I-NP O
Note NNP I-NP O
Patient NNP B-NP O
Name NNP I-NP O
: : O O
Fay NNP B-NP I-PATIENT
, , O I-PATIENT
Brook NNP B-NP I-PATIENT
MRN NNP B-NP O
: : O O
11289501 CD O B-MEDICALRECORD
Date NNP B-NP O
: : O O
9/16/96 CD O B-DATE
Admitting NNP B-NP O
Staff NNP I-NP O
: : O O
Tellez NNP B-NP B-DOCTOR
Location NN B-NP O
: : O O
59H CD O O
Reason NN B-NP O
for IN B-PP O
Admission NNP B-NP O
: : O O
Dysphagia NNP O O
HPI NNP B-NP O
: : O O
Ms. NNP B-NP O
Fay NNP I-NP B-PATIENT
is VBZ B-VP O
a DT B-NP O
69 CD I-NP B-AGE
year-old JJ I-NP O
woman NN I-NP O
with IN B-PP O
diabetes NNS B-NP O
who WP B-NP O
presented VBD B-VP O
from IN B-PP O
home NN B-NP O
with IN B-PP O
an DT B-NP O
approximately RB I-NP O
2 CD I-NP O
month NN I-NP O
history NN I-NP O
of IN B-PP O
progressive JJ B-NP O
dysphagia NN I-NP O
, , O O
solid JJ B-NP O
and CC I-NP O
liquid JJ I-NP O
. . O O
About IN B-PP O
that DT B-NP O
time NN I-NP O
she PRP B-NP O
was VBD B-VP O
prescribed VBN I-VP O
Amoxicillin NNP B-NP O
and CC I-NP O
Metronidazole NNP I-NP O
, , O O
presumably RB B-ADVP O
for IN B-PP O
H. NNP B-NP O
pylori NN I-NP O
eradication NN I-NP O
( -LRB- B-VP O
not RB I-VP O
confirmed VBN I-VP O
) -RRB- B-ADVP O
; : O O
she PRP B-NP O
reports VBZ B-VP O
an DT B-NP O
adverse JJ I-NP O
reaction NN I-NP O
to TO B-VP O
amoxicillin VB I-VP O
with IN B-PP O
rash JJ B-NP O
and CC I-NP O
facial JJ I-NP O
swelling VBG I-NP O
. . O O
The DT B-NP O
meds NNS I-NP O
were VBD B-VP O
discontinued VBN I-VP O
and CC O O
she PRP B-NP O
started VBD B-VP O
a DT B-NP O
course NN I-NP O
of IN B-PP O
oral JJ B-NP O
methylprednisolone NN I-NP O
. . O O
She PRP B-NP O
stopped VBD B-VP O
this DT B-NP O
several JJ I-NP O
weeks NNS I-NP O
ago RB B-ADVP O
because IN B-SBAR O
it PRP B-NP O
made VBD B-VP O
her PRP$ B-NP O
jittery JJ I-NP O
. . O O
Approximately RB O O
the DT B-NP O
same JJ I-NP O
time NN I-NP O
she PRP B-NP O
began VBD B-VP O
to TO I-VP O
notice VB I-VP O
that IN B-PP O
food NN B-NP O
and CC I-NP O
pills NNS I-NP O
would MD B-VP O
feel VB I-VP O
stuck VBN I-VP O
in IN B-PP O
the DT B-NP O
throat NN I-NP O
; : O O
on IN B-PP O
further JJ B-NP O
questioning NN I-NP O
, , O O
she PRP B-NP O
also RB B-ADVP O
may MD B-VP O
have VB I-VP O
noted VBN I-VP O
the DT B-NP O
presence NN I-NP O
of IN B-PP O
white JJ B-NP O
spots NNS I-NP O
in IN B-PP O
the DT B-NP O
mouth NN I-NP O
around IN B-PP O
this DT B-NP O
time NN I-NP O
as RB B-ADVP O
well RB I-ADVP O
. . O O
No DT B-NP O
fevers NNS I-NP O
, , O O
chills NNS B-NP O
, , O O
night NN B-NP O
sweats VBZ B-VP O
, , O O
nausea NN B-NP O
, , O O
vomiting VBG B-VP O
, , O O
chest NN B-NP O
pain NN I-NP O
, , O O
palpitations NNS B-NP O
, , O O
headache NN B-NP O
, , O O
lightheadedness NN B-NP O
, , O O
vertigo RB B-ADVP O
, , O O
rash NN B-NP O
or CC O O
new JJ B-NP O
joint JJ I-NP O
pain NN I-NP O
; : O O
no DT B-NP O
recent JJ I-NP O
travel NN I-NP O
. . O O
She PRP B-NP O
does VBZ B-VP O
note VB I-VP O
that IN B-PP O
her PRP$ B-NP O
blood NN I-NP O
sugars NNS I-NP O
at IN B-PP O
home NN B-NP O
have VBP B-VP O
been VBN I-VP O
consistently RB I-VP O
elevated VBN I-VP O
to TO B-PP O
the DT B-NP O
200-300 CD I-NP O
range NN I-NP O
. . O O
In IN B-PP O
the DT B-NP O
ED NNP I-NP O
, , O O
Ms. NNP B-NP O
Fay NNP I-NP B-PATIENT
was VBD B-VP O
afebrile JJ B-ADJP O
and CC O O
hemodynamically RB B-ADJP O
stable JJ I-ADJP O
. . O O
She PRP B-NP O
was VBD B-VP O
evaluated VBN I-VP O
by IN B-PP O
the DT B-NP O
GI JJ I-NP O
department NN I-NP O
. . O O
A DT B-NP O
screening NN I-NP O
HIV NN I-NP O
test NN I-NP O
was VBD B-VP O
negative JJ B-ADJP O
. . O O
She PRP B-NP O
was VBD B-VP O
found VBN I-VP O
to TO I-VP O
have VB I-VP O
mild JJ B-NP O
hyponatremia NN I-NP O
and CC O O
mild JJ B-NP O
hyperkalemia NN I-NP O
, , O O
as RB B-CONJP O
well RB I-CONJP O
as IN I-CONJP O
a DT B-NP O
question NN I-NP O
of IN B-PP O
subtle JJ B-NP O
ECG JJ I-NP O
changes NNS I-NP O
. . B-PP O
The DT B-NP O
above IN B-PP O
findings NNS B-NP O
prompted VBD B-VP O
admission NN B-NP O
for IN B-PP O
further JJ B-NP O
workup NN I-NP O
. . O O
ROS NNP B-NP O
: : O O
Pertinent JJ B-NP O
positives NNS I-NP O
and CC I-NP O
negatives NNS I-NP O
above IN B-ADVP O
. . O O
PMH/PSH NNP B-NP O
: : O O
Diabetes NNP B-NP O
mellitus NN I-NP O
Hypertension NN B-NP O
Hyperlipidemia NNP B-NP O
Obesity NN B-NP O
GERD NNP B-NP O
Osteoarthritis NNP B-NP O
and CC I-NP O
low JJ I-NP O
back RB B-ADVP O
pain NN O O
H/o NN B-NP O
AVNRT NNP I-NP O
( -LRB- I-NP O
2094 CD I-NP B-DATE
) -RRB- O O
ALLERGIES NNS B-NP O
: : O O
Reported JJ B-NP O
rash NN I-NP O
and CC O O
facial JJ B-NP O
swelling VBG I-NP O
with IN B-PP O
Amoxicillin NNP B-NP O
MEDICATIONS NNS B-NP O
: : O O
Atenolol NNP B-NP O
50mg CD I-NP O
daily JJ O O
Diclofenac NNP B-NP O
75 CD I-NP O
mg NN I-NP O
Q8 IN B-PP O
prn NN B-NP O
Metformin NNP B-NP O
500mg CD I-NP O
PO NNP I-NP O
BID NNP I-NP O
Pantoprazole NNP B-NP O
40 CD I-NP O
mg NN I-NP O
daily RB B-SBAR O
Loratadine NNP B-NP O
Albuterol NNP B-NP O
MDI NNP I-NP O
Meclizine NNP B-NP O
25mg CD I-NP O
PRN . O O
Aledronate NNP B-NP O
70mg JJ I-NP O
weekly JJ I-NP O
FAMILY NNP B-NP O
HISTORY NNP I-NP O
: : O O
Noncontributory NN B-NP O
SOCIAL JJ B-NP O
HISTORY NN I-NP O
: : O O
Lives NNS B-NP O
alone RB B-ADVP O
; : O O
family NN B-NP O
heavily RB B-ADJP O
involved VBN I-ADJP O
in IN B-PP O
her PRP$ B-NP O
care NN I-NP O
and CC O O
assist VB B-VP O
with IN B-PP O
secondary JJ B-NP O
ADLs NNP I-NP O
. . O O
No DT B-NP O
alcohol NN I-NP O
, , I-NP O
tobacco NN I-NP O
or CC I-NP O
drug NN I-NP O
use NN I-NP O
. . O O
Born VBN B-VP O
in IN B-PP O
Peru NNP B-NP B-COUNTRY
, , O O
last JJ B-NP O
visit NN I-NP O
about IN B-PP O
one CD B-NP O
year NN I-NP O
ago RB B-ADVP O
. . O O
PHYSICAL NNP B-NP O
EXAM NNP I-NP O
: : O O
Gen NNP B-NP O
: : O O
Alert NNP B-NP O
, , O O
NAD NNP B-NP O
VS NNP B-NP O
: : O O
Afebrile JJ B-NP O
82 CD I-NP O
100/54 CD I-NP O
18 CD I-NP O
100 CD I-NP O
% NN I-NP O
RA NN I-NP O
HEENT NNP B-NP O
: : O O
Conjunctivae NNP B-NP O
clear JJ I-NP O
, , I-NP O
anicteric JJ I-NP O
, , I-NP O
NP NNP I-NP O
clear JJ I-NP O
, , O O
OP NNP B-NP O
with IN B-PP O
mild JJ B-NP O
thrush NN I-NP O
, , O O
upper JJ B-NP O
dentures NNS I-NP O
; : O O
no DT B-NP O
sinus NN I-NP O
tenderness NN I-NP O
Neck NNP B-NP O
: : O O
Supple NNP B-NP O
, , O O
no DT B-NP O
adenopathy NN I-NP O
; : O O
no DT B-NP O
palpable JJ I-NP O
thyromegaly NN I-NP O
Heart NNP B-NP O
: : O O
RRR NNP B-NP O
, , O O
s1s2 NN B-NP O
without IN B-PP O
murmur VBG B-NP O
Lungs NNP B-NP O
: : O O
CTA NNP B-NP O
bilaterally , O O
without IN B-PP O
wheeze/rales NNS B-NP O
ABD NNP B-NP O
: : O O
Soft NNP B-NP O
, , I-NP O
nontender NN I-NP O
, , I-NP O
nondistended JJ I-NP O
, , I-NP O
nabs NNS I-NP O
, , O O
no DT B-NP O
mass NN I-NP O
EXT NNP B-NP O
: : O O
Warm NNP B-NP O
, , O O
no DT B-NP O
edema NN I-NP O
Skin NNP B-NP O
: : O O
No DT B-NP O
rash NN I-NP O
or CC O O
petechiae NN B-NP O
Neuro NNP B-NP O
: : O O
A&Ox3 NNP B-NP O
, , O O
no DT B-NP O
focal JJ I-NP O
deficits NNS I-NP O
LABORATORY NN B-NP O
: : O O
15.6 CD B-NP O
> NN I-NP O
42.3 CD B-NP O
< NN I-NP O
487 CD B-NP O
( -LRB- O O
77 CD B-NP O
poly NN I-NP O
, , O O
17 CD B-NP O
lymph NN I-NP O
) -RRB- O O
130 CD B-NP O
/ NNS I-NP O
5.3 CD B-NP O
/ NN I-NP O
99 CD I-NP O
/ NN I-NP O
21 CD I-NP O
/ NNP I-NP O
38 CD I-NP O
/ NN I-NP O
1.1 CD B-NP O
< , O O
375 CD B-NP O
eGFR NN I-NP O
48 CD O O
ALT/AST NNP B-NP O
normal JJ I-NP O
CK/MG/Troponin NNP B-NP O
normal JJ I-NP O
x NN I-NP O
2 CD B-NP O
sets NNS I-NP O
UA NNP B-NP O
: : O O
3+ JJ B-NP O
glucose NN I-NP O
, , O O
otherwise RB B-ADVP O
negative JJ O O
MICROBIOLOGY NNP B-NP O
: : O O
Urine NNP B-NP O
culture NN I-NP O
pending VBG I-NP O
RADIOLOGY NNP B-NP O
: : O O
None NN B-NP O
ECG NNP B-NP O
: : O O
NSR NNP B-NP O
, , O O
incomplete JJ B-NP O
RBBB NNP I-NP O
; : O O
T NNP B-NP O
wave NN I-NP O
flattening/inversion NN I-NP O
in IN B-PP O
V2-V3 NNP B-NP O
that WDT B-NP O
was VBD B-VP O
not RB I-VP O
noted VBN I-VP O
on IN B-PP O
2094 CD B-NP B-DATE
ECG . O O
IMPRESSION NNP B-NP O
and CC I-NP O
PLAN NNP I-NP O
: : O O
66 CD B-NP B-AGE
year-old JJ I-NP O
woman NN I-NP O
with IN B-PP O
solid/liquid JJ B-NP O
dysphagia NN I-NP O
, , O O
oral JJ B-NP O
candidiasis NN I-NP O
, , O O
and CC O O
poorly RB B-VP O
controlled VBN I-VP O
diabetes NN B-NP O
mellitus NN I-NP O
. . O O
The DT B-NP O
presence NN I-NP O
of IN B-PP O
thrush NN B-NP O
raises VBZ B-VP O
suspicion NN B-NP O
for IN B-PP O
esophageal NN B-NP O
candidiasis NN I-NP O
, , O O
though IN B-SBAR O
she PRP B-NP O
does VBZ B-VP O
not RB I-VP O
report VB I-VP O
odynophagia NNP B-NP O
. . I-NP O
Mechanical NNP I-NP O
obstruction NN I-NP O
should MD B-VP O
be VB I-VP O
ruled VBN I-VP O
out RP B-PRT O
. . O O
The DT B-NP O
presence NN I-NP O
of IN B-PP O
mild JJ B-NP O
hyponatremia NN I-NP O
and CC I-NP O
hyperkalemia NN I-NP O
is VBZ B-VP O
likely JJ B-ADJP O
attributable JJ I-ADJP O
to TO B-PP O
the DT B-NP O
fact NN I-NP O
that IN B-SBAR O
she PRP B-NP O
abruptly RB B-VP O
discontinued VBN I-VP O
exogenous JJ B-NP O
corticosteroids NNS I-NP O
after IN B-PP O
a DT B-NP O
several JJ I-NP O
week NN I-NP O
course NN I-NP O
; : O O
she PRP B-NP O
is VBZ B-VP O
hemodynamically RB B-ADJP O
stable JJ I-ADJP O
. . O O
Finally RB B-ADVP O
, , O O
there EX B-NP O
is VBZ B-VP O
little RB B-ADVP O
here RB B-ADVP O
to TO B-VP O
suggest VB I-VP O
acute JJ B-NP O
coronary JJ I-NP O
syndrome NN I-NP O
, , O O
though IN B-SBAR O
she PRP B-NP O
falls VBZ B-VP O
into IN B-PP O
a DT B-NP O
subgroup NN I-NP O
of IN B-PP O
patients NNS B-NP O
more RBR B-ADJP O
likely JJ I-ADJP O
to TO B-VP O
present VB I-VP O
with IN B-PP O
minimal JJ B-NP O
symptoms NNS I-NP O
. . O O
ECG NNP B-NP O
warrants NNS I-NP O
following VBG B-VP O
. . O O
Diabetes NNP B-NP O
is VBZ B-VP O
poorly RB I-VP O
controlled VBN I-VP O
and CC O O
may MD B-VP O
require VB I-VP O
initiation NN B-NP O
of IN B-PP O
insulin NN B-NP O
therapy NN I-NP O
; : O O
though IN B-SBAR O
sugars NNS B-NP O
here RB B-ADVP O
may MD B-VP O
have VB I-VP O
been VBN I-VP O
confounded VBN I-VP O
by IN B-PP O
the DT B-NP O
dose NN I-NP O
of IN B-PP O
steroids NNS B-NP O
given VBN B-VP O
in IN B-PP O
ED. NNP B-NP O
CV NNP B-NP O
: : O O
CR VBD B-VP O
monitor NN B-NP O
overnight JJ I-NP O
; : O O
cycle NN B-NP O
ECG NNP I-NP O
and CC I-NP O
cardiac JJ I-NP O
biomarkers NNS I-NP O
; : O O
aspirin NN B-NP O
, , O O
continue VBP B-VP O
beta JJ B-NP O
blocker NN I-NP O
Pulm NNP B-NP O
: : O O
No DT B-NP O
issues NNS I-NP O
; : O O
albuterol NN B-NP O
prn NN I-NP O
GI NNP B-NP O
: : O O
Upper NNP B-NP O
endoscopy VBP B-VP O
tentatively RB I-VP O
planned VBN I-VP O
for IN B-PP O
the DT B-NP O
morning NN I-NP O
; : O O
NPO NNP B-NP O
after IN B-PP O
midnight NN B-NP O
; : O O
continue VB B-VP O
home NN B-NP O
ppi NN I-NP O
Endocrine NNP B-NP O
: : O O
Sliding VBG B-VP O
scale NN B-NP O
insulin NN I-NP O
, , O O
metformin NN B-NP O
; : O O
consider VB B-NP O
diabetes NNS I-NP O
education NN I-NP O
, , O O
and CC O O
discuss VB B-VP O
with IN B-PP O
PCP NNP B-NP O
whether IN B-PP O
initiation NN B-NP O
of IN B-PP O
insulin NN B-NP O
is VBZ B-VP O
warranted VBN I-VP O
. . I-VP O
Check VB I-VP O
HbA1c CC I-VP O
, , O O
TFTs . O O
FEN NNS B-NP O
: : O O
Monitor NNP B-NP O
lytes NNS I-NP O
; : O O
lowfat JJ B-NP O
ADA NNP I-NP O
diet NN I-NP O
Infectious JJ B-NP O
Disease NN I-NP O
: : O O
Following VBG B-VP O
EGD NNP B-NP O
, , O O
fluconazole NN B-NP O
for IN B-PP O
candidiasis NN B-NP O
; : O O
leukocytosis NN B-NP O
is VBZ B-VP O
unexplained JJ B-ADJP O
, , O O
but CC O O
not RB B-NP O
focal JJ I-NP O
evidence NN I-NP O
of IN B-PP O
infection NN B-NP O
PPx NNP B-NP O
: : O O
Enoxaparin NNP B-NP O
may MD B-VP O
be VB I-VP O
started VBN I-VP O
after IN B-PP O
EGD NNP B-NP O
Social NNP B-NP O
work VBP B-VP O
consult VB I-VP O
to TO I-VP O
assess VB I-VP O
support NN B-NP O
network NN I-NP O
and CC O O
assist VB B-VP O
with IN B-PP O
discharge NN B-NP O
planning VBG I-NP O
Terry NNP B-NP B-DOCTOR
Iyer NNP I-NP I-DOCTOR
will MD B-VP O
assume VB I-VP O
care NN B-NP O
in IN B-PP O
the DT B-NP O
morning NN I-NP O
. . O O
Please VB B-VP O
page NN B-NP O
Dr. NNP I-NP O
Iyer NNP I-NP B-DOCTOR
directly RB B-ADVP O
at IN B-PP O
00450 CD B-NP B-PHONE
with IN B-PP O
questions NNS B-NP O
arising VBG B-VP O
after IN B-PP O
8:00am NN B-NP O
. . O O
Paul NNP B-NP B-DOCTOR
Gardner NNP I-NP I-DOCTOR
, , O O
MD . O O
Pager NNP B-NP O
48272 CD I-NP B-PHONE
