Record NNP B-NP O
date NN I-NP O
: : O O
2106-10-07 CD O B-DATE
OFFICE NNP B-NP O
NOTE NNP I-NP O
SAINT NNP B-NP B-HOSPITAL
LUKE'S-ROOSEVELT NNP I-NP I-HOSPITAL
HOSPITAL NNP I-NP I-HOSPITAL
CENTER NNP I-NP I-HOSPITAL
799 CD B-NP B-STREET
SARGENT NNP I-NP I-STREET
AVENUE . O I-STREET
KAUFMAN NNP B-NP B-CITY
, , O O
MO VBZ B-VP B-STATE
85156 CD I-VP B-ZIP
Tanya NNP B-NP B-PATIENT
Do VBP O I-PATIENT
MRN NNP B-NP O
: : O O
63925217 CD O B-MEDICALRECORD
October NNP B-NP B-DATE
07 CD I-NP I-DATE
, , I-NP I-DATE
2106 CD O I-DATE
CHIEF JJ B-NP O
COMPLAINT. NNP I-NP O
Follow-up NN I-NP O
with IN B-PP O
regard NN B-NP O
to TO B-PP O
multiple JJ B-NP O
medical JJ I-NP O
problems NNS I-NP O
. . O O
SUBJECTIVE. NNP B-NP O
She PRP B-NP O
begins VBZ B-VP O
with IN B-PP O
a DT B-NP O
very RB I-NP O
long JJ I-NP O
reprise NN I-NP O
of IN B-PP O
her PRP$ B-NP O
complaints NNS I-NP O
about IN B-PP O
her PRP$ B-NP O
hospitalization NN B-NP O
at IN B-PP O
Sawtelle NNP B-NP B-HOSPITAL
Veterans NNP I-NP I-HOSPITAL
Hospital NNP I-NP I-HOSPITAL
earlier RBR B-NP O
this DT I-NP O
fall NN I-NP B-DATE
. . O O
She PRP B-NP O
then RB B-ADVP O
follows VBZ B-VP O
with IN B-PP O
a DT B-NP O
long JJ I-NP O
discussion NN I-NP O
of IN B-PP O
the DT B-NP O
difficulties NNS I-NP O
in IN B-PP O
securing VBG B-NP O
diabetic JJ B-NP O
supplies NNS I-NP O
. . B-PP O
Her PRP$ B-NP O
home NN I-NP O
blood NN I-NP O
glucoses NNS I-NP O
have VBP B-VP O
been VBN I-VP O
variable JJ B-ADJP O
, , O O
reportedly RB O O
due JJ B-ADJP O
to TO B-VP O
poorly RB I-VP O
functioning VBG I-VP O
glucose NN B-NP O
meter NN I-NP O
. . O O
The DT B-NP O
Neurology NNP I-NP O
Consultant NNP I-NP O
has VBZ B-VP O
added VBN I-VP O
lisinopril NN B-NP O
and CC O O
Plavix NNP B-NP O
to TO B-PP O
her PRP$ B-NP O
regimen NNS I-NP O
. . O O
Had VBD O O
what WP B-NP O
appears VBZ B-VP O
to TO I-VP O
have VB I-VP O
been VBN I-VP O
an DT B-NP O
injection NN I-NP O
of IN B-PP O
epidural JJ B-NP O
steroids NNS I-NP O
for IN B-PP O
treatment NN B-NP O
of IN B-PP O
symptoms NNS B-NP O
referable JJ B-ADJP O
to TO B-PP O
spinal JJ B-NP O
stenosis NN I-NP O
per IN B-PP O
Dr. NNP B-NP O
Jaeger NNP I-NP B-DOCTOR
, , O O
to TO B-PP O
good JJ B-NP O
effect NN I-NP O
. . O O
Her PRP$ O O
back RB B-ADVP O
pain NN B-NP O
has VBZ B-VP O
now RB I-VP O
begun VBN I-VP O
to TO I-VP O
recrudesce VB I-VP O
, , O O
and CC O O
she PRP B-NP O
is VBZ B-VP O
considering VBG I-VP O
another DT B-NP O
such JJ I-NP O
injection NN B-NP O
. . O O
There EX B-NP O
are VBP B-VP O
multiple JJ B-NP O
other JJ I-NP O
somatic JJ I-NP O
complaints NNS I-NP O
-- : O O
neck NN B-VP O
pain NN B-NP O
; : O O
recurring VBG B-NP O
nocturnal JJ I-NP O
sweating VBG B-VP O
; : O O
dry JJ B-NP O
cough NN I-NP O
; : O O
runny JJ B-NP O
nose NN I-NP O
; : O O
other JJ B-ADVP O
. . O O
MEDICATIONS. NNP B-NP O
Baby NNP I-NP O
aspirin NN I-NP O
; : O O
supplements NNS B-NP O
of IN B-PP O
calcium NN B-NP O
and CC I-NP O
vitamin NN I-NP O
D NNP I-NP O
; : O O
Fosamax NNP B-NP O
70 CD B-NP O
mg NN I-NP O
once RB B-ADJP O
weekly JJ I-ADJP O
; : O O
prednisone NN B-NP O
5 CD I-NP O
mg NN I-NP O
b.i.d NN I-NP O
. . O O
; : O O
folic JJ B-NP O
acid NN I-NP O
1 CD I-NP O
mg NN I-NP O
per IN B-PP O
day NN B-NP O
; : O O
methotrexate NN B-NP O
15 CD I-NP O
mg NN I-NP O
per IN B-PP O
week NN B-NP O
; : O O
Celebrex NNP B-NP O
200 CD B-NP O
mg NN I-NP O
b.i.d NN I-NP O
. . B-VP O
; : O O
Glucophage NNP B-NP O
500 CD I-NP O
mg NN I-NP O
2 CD B-NP O
PO NN I-NP O
b.i.d NN B-NP O
. . B-VP O
; : O O
Zebeta NNP B-NP O
2.5 CD I-NP O
mg NN I-NP O
per IN B-PP O
day NN B-NP O
; : O O
lisinopril NN B-NP O
20 CD I-NP O
mg NN I-NP O
per IN B-PP O
day NN B-NP O
; : O O
Plavix NNP B-NP O
75 CD I-NP O
mg NN I-NP O
per IN B-PP O
day NN B-NP O
; : O O
Lipitor NNP B-NP O
10 CD B-NP O
mg NN I-NP O
t.i.w NN I-NP O
. . O O
PMH. NNP B-NP O
Reviewed NNP I-NP O
. . O O
REVIEW NN B-NP O
OF IN B-PP O
SYSTEMS. NNP B-NP O
Other JJ I-NP O
systems NNS I-NP O
reviewed VBN B-VP O
and CC O O
are VBP B-VP O
negative JJ B-ADJP O
. . O O
OBJECTIVE. NNP B-NP O
General NNP I-NP O
appearance NN I-NP O
. . O O
In IN B-PP O
no DT B-NP O
distress NN I-NP O
. . O O
Vital JJ B-NP O
signs NNS I-NP O
. . O O
Blood NN O O
pressure NN B-NP O
128/60 VBD B-VP O
left VBN I-VP O
arm NN B-NP O
sit VB B-VP O
. . B-PP O
Pulse NNP B-NP O
64 CD I-NP O
and CC O O
regular JJ B-ADVP O
. . B-NP O
Respiratory NN I-NP O
rate NN I-NP O
12 CD I-NP O
. . O O
Chest NNP B-NP O
. . I-NP O
Clear NNP I-NP O
. . I-NP O
Cardiovascular NNP I-NP O
. . O O
No DT B-NP O
murmurs NNS I-NP O
. . B-NP O
Abdomen NNP I-NP O
. . O O
No DT B-NP O
mass NN I-NP O
, , O O
tenderness NN B-NP O
, , O O
or CC O O
organomegaly NNP B-NP O
. . I-NP O
Bowel NNP I-NP O
sounds VBZ B-VP O
normal JJ B-ADJP O
. . O O
LABORATORY NN B-NP O
DATA. NNP I-NP O
Imaging NNP I-NP O
studies NNS I-NP O
reviewed VBN B-VP O
; : O O
a DT B-NP O
PA NNP I-NP O
and CC I-NP O
lateral JJ I-NP O
chest NN I-NP O
x-ray NN I-NP O
, , O O
obtained VBN B-VP O
on IN B-PP O
April NNP B-NP B-DATE
13 CD I-NP I-DATE
, , O O
showed VBD B-VP O
only RB B-NP O
bibasilar JJ I-NP O
atelectasis NN I-NP O
. . O O
Hemoglobin NNP B-NP O
A1C NNP I-NP O
was VBD B-VP O
6.5 CD B-NP O
. . O O
IMPRESSION. . O O
1 LS O O
. . B-NP O
Chronic NNP I-NP O
rheumatoid VBD B-VP O
arthritis NN B-NP O
: : O O
apparently RB B-ADJP O
unchanged JJ I-ADJP O
. . O O
3. DT B-NP O
DM NNP I-NP O
: : O O
? . B-NP O
current JJ I-NP O
status NN I-NP O
. . B-VP O
Last JJ B-NP O
time NN I-NP O
's POS B-NP O
hemoglobin NN I-NP O
A1C . O O
was VBD B-VP O
slightly RB O O
elevated VBN B-ADJP O
. . O O
6 CD B-NP O
. . O O
Psychosocial NNP B-NP O
stresses VBZ B-VP O
. . O O
29 CD B-LST O
. . O O
? . B-VP O
TIA NNP B-NP O
: : O O
Now RB B-ADVP O
on IN B-PP O
lisinopril NN B-NP O
and CC I-NP O
Plavix NNP I-NP O
per IN B-PP O
Neurology NNP B-NP O
. . O O
Tanya NNP B-NP B-PATIENT
Do VBP O I-PATIENT
MRN NNP B-NP O
: : O O
63925217 CD O B-MEDICALRECORD
October NNP B-NP B-DATE
07 CD I-NP I-DATE
, , I-NP I-DATE
2106 CD O I-DATE
Page NNP B-NP O
2 CD I-NP O
. . B-NP O
Spinal NNP I-NP O
stenosis NN I-NP O
: : O O
Reportedly RB B-NP O
good JJ I-NP O
symptomatic JJ I-NP O
response NN I-NP O
to TO B-PP O
epidural NN B-NP O
steroids NNS B-NP O
. . O O
. . B-NP O
Hypercholesterolemia NNP I-NP O
: : O O
Now RB B-ADVP O
on IN B-PP O
low-dose JJ B-NP O
Lipitor NNP I-NP O
: : O O
? . B-NP O
current JJ I-NP O
status NN I-NP O
. . O O
( -LRB- B-NP O
a DT I-NP O
) -RRB- I-NP O
Nasal NNP I-NP O
congestion NN I-NP O
, , O O
other JJ B-NP O
: : O O
? . B-NP O
etiology NN I-NP O
. . O O
PLAN. . O O
Diagnostic NNP B-NP O
. . I-NP O
CBC NNP I-NP O
, , O O
hepatic JJ B-NP O
function NN I-NP O
profile NN I-NP O
. . O O
BUN '' O O
and CC O O
creatinine VB B-VP O
. . O O
Hemoglobin '' O O
A1C. DT B-NP O
Lipid NNP I-NP O
profile NN I-NP O
, , O O
CPK. . O O
Therapeutic JJ B-NP O
. . O O
All DT B-NP O
medications NNS I-NP O
refilled VBN B-VP O
. . B-NP O
Continue NNP I-NP O
current JJ I-NP O
regimen NNS I-NP O
. . O O
Activity NN O O
as IN B-NP O
tolerated VBD B-VP O
. . B-NP O
Flu NNP I-NP O
shot VBD B-VP O
. . B-NP O
Return VBN I-NP O
visit NN I-NP O
later RB B-ADVP O
in IN B-PP O
the DT B-NP O
year NN I-NP O
. . O O
Harold NNP B-NP B-DOCTOR
G. NNP I-NP I-DOCTOR
Keane NNP I-NP I-DOCTOR
, , O O
M.D. NNP B-NP O
DD NNP B-NP O
: : O O
10/07/06 CD O B-DATE
DT NNP B-NP O
: : O O
10/11/06 CD O B-DATE
DV NNP B-NP O
: : O O
10/07/06 CD O B-DATE
/ NN B-NP O
talbert NN I-NP B-DOCTOR
